### PR TITLE
Ensure that request logs are completed for empty responses

### LINKED ISSUE #4790: Handle exceptions thrown by Servlet
> Hi folks, we recently encountered an issue where Armeria (we are on Armeria 1.16.2) won’t finish collecting the response information for a RequestLog when the corresponding HttpResponse is closed without any data written. As a result, RequestLogAccess.whenComplete() never completes after closing the HttpResponse. A simple reproduction can be found [here](https://gist.github.com/linwuz-db/2c7adae5a546c87760c69a89ddccc70e). So far we find this issue is exposed in [JettyService](https://github.com/line/armeria/blob/main/jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java#L323) and [TomcatService](https://github.com/line/armeria/blob/main/tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java#L427) when the exception is thrown outside the “servlet handling” code path. We have a couple of questions:
Is it expected behavior that the RequestLog never completes when neither data nor failure is being set on the response (just close)? This leads us to the second question:
Is it a legit use of the API to close a HttpResponse without writing anything or “failing” it.

Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1679553378276729

If `JettyService` get an exception while handling a request, it closes the response silently without propagating the exception. 
https://github.com/line/armeria/blob/49054ad7f22a7f2d64faaeb694674b0df09ad165/jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java#L322-L324
https://github.com/line/armeria/blob/49054ad7f22a7f2d64faaeb694674b0df09ad165/tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java#L424-L428
These can make the failed response publish no `HttpObject`s.
https://github.com/line/armeria/blob/cef7b9c359b383e2b703f13c135f7800e980e422/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L307-L317

As a result, 1) the exception is not propagated to `RequestLog.responseCause()` and 2) the `RequestLog.whenComplete()` isn't completed because of the bug in `HttpResponseSubscriber`.

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

Request logs are not completed for empty responses, which may cause resource leaks.
I propose that we complete request logs for empty responses with a `ProtocolViolationException` since the session is closed without any response.

Modifications:

- Add `ProtocolViolationException#get`
- Call `fail(ProtocolViolationException.get());` instead of `tryComplete(null)` to complete the request log
- Ensure that other paths in `HttpResponseSubscriber#onComplete` or `HttpResponseSubscriber#onError` all lead to either `HttpResponseSubscriber#fail` or `HttpResponseSubscriber#succeed` being called
- Close the response with the exception if `JettyService` fails to process a request

Result:

- Closes #4790

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java [hunk 1]
```diff
@@ -309,7 +310,7 @@ public void onComplete() {
             responseEncoder.writeReset(req.id(), req.streamId(), Http2Error.INTERNAL_ERROR)
                            .addListener(future -> {
                                try (SafeCloseable ignored = RequestContextUtil.pop()) {
-                                   tryComplete(null);
+                                   fail(ProtocolViolationException.get());
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java:313]: - What do you think of removing the warning since the exception will be logged to `RequestLog`?
- The message would help to debug.
```suggestion
                                   fail(new ProtocolViolationException(ctx.channel() + "..."));
```

File: core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java [hunk 2]
```diff
@@ -176,4 +192,23 @@ void contentLengthIsNotSetWhenTrailerExists() {
         assertThat(res.headers().get(HttpHeaderNames.CONTENT_LENGTH)).isNull();
         assertThat(res.trailers().get(HttpHeaderNames.of("foo"))).isEqualTo("baz");
     }
+
+    @ParameterizedTest
+    @EnumSource(value = SessionProtocol.class, names = {"H1C", "H2C"})
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java:197]: Should we also check `ExchangeType` on the server side?

File: jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java [hunk 3]
```diff
@@ -318,6 +318,9 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) {
                 });
                 success = true;
                 return null;
+            } catch (Exception e) {
+                res.close(e);
```
Comment (ikhoon) [inline jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java:322]: I prefer `.abort(e)` because `.close(e)` does not clean up internal resources.
A byte array is used to convey the data though.

File: core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java (hunk 2 above)
Comment (jrhee17) [reply core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java]: I realized that the behavior differs between unary and streaming responses at the moment.
- Unary: A 500 internal exception is returned.
- Streaming: The connection is terminated immediately.

I've unified the behavior for both cases such that the connection is terminated immediately for consistency.
I doubt this is a normal path for users anyways.

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java (hunk 1 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java]: I've decided to define an explicit exception to handle https://github.com/line/armeria/pull/4791#discussion_r1154019387 more easily instead 👍 
I think the exception name is self-explanatory, but let me know if you think more information should be included

File: jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java (hunk 3 above)
Comment (jrhee17) [reply jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java]: Done!

File: core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseContentException.java [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+ * under the License.
+ */
+
+package com.linecorp.armeria.common;
+
+import com.linecorp.armeria.common.annotation.Nullable;
+import com.linecorp.armeria.common.annotation.UnstableApi;
+
+/**
+ * An exception which is thrown when a {@link HttpResponse} without any headers
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseContentException.java:23]: nit:
```suggestion
 * An exception which is thrown when an {@link HttpResponse} without any headers
```

File: core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseContentException.java [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+ * or body is attempted to be sent over the wire.
+ */
+@UnstableApi
+public final class EmptyHttpResponseContentException extends RuntimeException {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseContentException.java:27]: How about `EmptyHttpResponseException`?
It sounds like only the body of an `HttpResponse` is empty.

**Review by minwoox — APPROVED** [review]
Left a small suggestion. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java [hunk 6]
```diff
@@ -104,6 +105,10 @@ private void recoverAndWrite(Throwable cause) {
         } else if (Exceptions.isStreamCancelling(cause)) {
             resetAndFail(cause);
         } else {
+            if (cause instanceof EmptyHttpResponseContentException) {
+                resetAndFail(cause);
+                return;
+            }
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java:111]: nit: This branch may be merged into `Exceptions.isStreamCancelling(cause)`.
```java
} else if (Exceptions.isStreamCancelling(cause) || 
           cause instanceof EmptyHttpResponseContentException) {
    resetAndFail(cause);
}
```

File: core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseException.java [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+    /**
+     * Returns a {@link EmptyHttpResponseException} which may be a singleton or a new instance,
+     * depending on {@link Flags#verboseExceptionSampler()}'s decision.
+     */
+    public static EmptyHttpResponseException get() {
+        return isSampled() ? new EmptyHttpResponseException(null, null, true, true) : INSTANCE;
+    }
+
+    private static boolean isSampled() {
+        return Flags.verboseExceptionSampler().isSampled(ClosedSessionException.class);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseException.java:43]: Should it be?
```suggestion
        return Flags.verboseExceptionSampler().isSampled(EmptyHttpResponseException.class);
```

**Review by ikhoon — APPROVED** [review]
Thanks! Left a comment for sampling.

File: core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseException.java (hunk 7 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseException.java]: 😱

File: jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java [hunk 8]
```diff
@@ -318,6 +318,9 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) {
                 });
                 success = true;
                 return null;
+            } catch (Exception e) {
+                res.abort(e);
+                throw e;
             } finally {
```
Comment (vkostyukov) [inline jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java:324]: Can we get rid of finally block (including the `success` flag) now that we catch an exception explicitly?  It seems to be a no-op now.

**Review by vkostyukov — COMMENTED** [review]
Do we need to fix TomcatService as well?

File: jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java (hunk 8 above)
Comment (trustin) [reply jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java:324]: Maybe should we catch `Throwable` then?

**Review by trustin — APPROVED** [review]
LGTM once @vkostyukov's comments are addressed. 🙇

**Review by vkostyukov — APPROVED** [review]
Thank you! This is a great way to fix this issue.

File: tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java [hunk 9]
```diff
@@ -445,7 +445,7 @@ public final HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) thro
                 });
             } catch (Throwable t) {
                 logger.warn("{} Failed to invoke Tomcat:", ctx, t);
-                res.close();
+                res.abort(t);
```
Comment (ikhoon) [inline tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java:448]: - Since the exception is propagated, we may remove the warning message.
  ```java
  res.abort(new IllegalStateException("Failed to invoke Tomcat", t);
  ```
- Should we also abort `res` when an exception is raised in L440 ~ L443?

File: tomcat10/src/test/java/com/linecorp/armeria/server/tomcat/ManagedTomcatServiceTest.java [hunk 10]
```diff
@@ -117,4 +139,18 @@ void jarBasedWebAppWithAlternativeRoot() throws Exception {
...
+    void throwingExceptionIsLogged(SessionProtocol sessionProtocol) throws Exception {
+        final AggregatedHttpResponse res = WebClient.builder(sessionProtocol, server.httpEndpoint())
+                                                    .build().blocking().get("/throwing");
+        assertThat(res.status().code()).isEqualTo(500);
+
+        assertThat(server.requestContextCaptor().size()).isEqualTo(1);
+        final ServiceRequestContext sctx = server.requestContextCaptor().poll();
+        await().atMost(10, TimeUnit.SECONDS).until(() -> sctx.log().isComplete());
+        assertThat(sctx.log().ensureComplete().responseCause()).isSameAs(RUNTIME_EXCEPTION);
+        System.out.println(sctx.log().ensureComplete());
```
[the remark this answers is not in the document]
Comment (jrhee17) [reply tomcat10/src/test/java/com/linecorp/armeria/server/tomcat/ManagedTomcatServiceTest.java]: 🙀

File: tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java (hunk 9 above)
Comment (jrhee17) [reply tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java]: > Should we also abort res when an exception is raised in L440 ~ L443?

Updated, but I didn't add a test case since I couldn't think of a good way to verify this change 😅

**Review by ikhoon — APPROVED** [review]
I'm happy with the new changes!
