### PR TITLE
Fix test failures

### LINKED ISSUE #1581: Intermittent test failure at GrpcServiceServerTest.error_thrown_streamMessage()
```
com.linecorp.armeria.server.grpc.GrpcServiceServerTest > error_thrown_streamMessage FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <"armeria.grpc.testing.UnitTestService/StaticUnaryCall">
    to be equal to:
     <"armeria.grpc.testing.UnitTestService/StreamThrowsError">
    but was not.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.server.grpc.GrpcServiceServerTest.lambda$error_thrown_streamMessage$8(GrpcServiceServerTest.java:445)
        at com.linecorp.armeria.server.grpc.GrpcServiceServerTest.checkRequestLog(GrpcServiceServerTest.java:856)
        at com.linecorp.armeria.server.grpc.GrpcServiceServerTest.error_thrown_streamMessage(GrpcServiceServerTest.java:444)
```

### LINKED ISSUE #1598: Test failure: RequestContextTest.makeContextAwareCompletableFutureWithAsyncChaining()
```
com.linecorp.armeria.common.RequestContextTest > makeContextAwareCompletableFutureWithAsyncChaining FAILED
    java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at com.linecorp.armeria.common.RequestContextTest.makeContextAwareCompletableFutureWithAsyncChaining(RequestContextTest.java:285)
        Caused by:
        java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
            at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
            at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
            at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
            at java.base/java.util.Objects.checkIndex(Objects.java:372)
            at java.base/java.util.ArrayList.remove(ArrayList.java:535)
            at com.linecorp.armeria.common.RequestContextTest.lambda$createContext$29(RequestContextTest.java:414)
```

### LINKED ISSUE #1602: Intermittent test failure at GrpcServiceServerTest.compressedClient_compressedEndpoint
```
com.linecorp.armeria.server.grpc.GrpcServiceServerTest > compressedClient_compressedEndpoint FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <"armeria.grpc.testing.UnitTestService/ErrorWithMessage">
    to be equal to:
     <"armeria.grpc.testing.UnitTestService/StaticUnaryCallSetsMessageCompression">
    but was not.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.server.grpc.GrpcServiceServerTest.lambda$compressedClient_compressedEndpoint$16(GrpcServiceServerTest.java:555)
        at com.linecorp.armeria.server.grpc.GrpcServiceServerTest.checkRequestLog(GrpcServiceServerTest.java:869)
        at com.linecorp.armeria.server.grpc.GrpcServiceServerTest.compressedClient_compressedEndpoint(GrpcServiceServerTest.java:554)
```
https://travis-ci.com/line/armeria/builds/101253972

### LINKED ISSUE #1640: Test failure due to TCP/IP port conflict
We need to bind at port `0` in our example project tests as well.

```
example.springframework.boot.minimal.HelloApplicationIntegrationTest > success FAILED
    java.lang.IllegalStateException: Failed to load ApplicationContext
        Caused by:
        org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'armeriaServer' defined in class path resource [com/linecorp/armeria/spring/ArmeriaAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
            Caused by:
            org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
                Caused by:
                java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
                    Caused by:
                    java.lang.IllegalStateException: Armeria server failed to start
                        Caused by:
                        java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
                            Caused by:
                            io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
example.springframework.boot.minimal.HelloApplicationIntegrationTest > failure FAILED
    java.lang.IllegalStateException: Failed to load ApplicationContext
        Caused by:
        org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'armeriaServer' defined in class path resource [com/linecorp/armeria/spring/ArmeriaAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
            Caused by:
            org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
                Caused by:
                java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
                    Caused by:
                    java.lang.IllegalStateException: Armeria server failed to start
                        Caused by:
                        java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
                            Caused by:
                            io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

### PR DESCRIPTION
**Pull request by trustin**
- Fixed intermittent test failures in `GrpcServiceServerTest`.
  - Made sure all `RequestLog`s are consumed by each test method.
  - Fixes #1581
  - Fixes #1602
- Fixed Spring Boot integration example tests.
  - Made sure an ephemeral port is used for testing.
  - Fixes #1640
- Added more assertions to `RequestContextTest`
  - Closes #1598
- Used `await().untilAsserted()` in `RequestContext` instead of
  waiting for an event loop to shut down completely.

### CODE REVIEW

**Comment by trustin** [comment]
Travis CI and AppVeyor builds have succeeded 5 times in a row for each. I believe the flaky tests are gone. Please review.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java [hunk 1]
```diff
@@ -849,6 +855,7 @@ public void grpcWeb_error() throws Exception {
                 GrpcTestUtil.uncompressedFrame(GrpcTestUtil.requestByteBuf())).aggregate().get();
         assertThat(response.headers()).contains(entry(GrpcHeaderNames.GRPC_STATUS, "10"),
                                                 entry(GrpcHeaderNames.GRPC_MESSAGE, "aborted call"));
+        requestLogQueue.take();
```
Comment (anuraaga) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java]: I wonder if there isn't a more automatic way of handling this. It's a bit tedious to deal with request log queue in tests that aren't testing the request logs. Can we add the `isEmpty` assertion to the tests that actually care about it and in `TearDown` clear the queue instead?

Comment (trustin) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java]: It is not possible unfortunately due to timing issues. `RequestLog` may be put into the queue after the test execution is finished. Because tear-down method has no prior information about how many `RequestLog` a test method will produce, it has to wait like up to N seconds to ensure that, which will increase the test run time quite a bit.

**Comment by trustin** [comment]
Ready for reviews, @minwoox @hyangtack

File: examples/spring-boot-webflux/src/test/resources/application-testbed.yml [hunk 2]
```diff
@@ -0,0 +1,9 @@
+# Use a random port to avoid a potential port conflict.
+server:
+  port: 0
+  ssl:
+    enabled: false
+
+# Disable all other ports which were defined in src/main/resources/application.yml.
+armeria:
+  ports:
```
Comment (minwoox) [inline examples/spring-boot-webflux/src/test/resources/application-testbed.yml]: nit: missing new line?

Comment (trustin) [reply examples/spring-boot-webflux/src/test/resources/application-testbed.yml]: Oops. Added a new line.
