### PR TITLE
Provide a way to determine circuit, and retry with response duration

### LINKED ISSUE #4782: Provide a way to easily create `CircuitBreakerRule` with `RequestLog`
`ResponseHeaders`, `HttpStatus` and an exception is used to decide if a request fails and the result is reported to `CircuitBreaker`.
https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java#L127-L143
That would be sufficient if users may want to build a fine-grained rule based on the information in `RequestLog` such as response duration.
I proposed to add new builder methods to create a rule with `RequestLog`
```java
class CircuitBreakerRuleBuilder {

    @Override
    public CircuitBreakerRuleBuilder onRequestLog(
            Predicate<RequestLog> requestLogFilter) {
        ...
    }
}
```

### PR DESCRIPTION
**Pull request by babjo**
Motivation:

We can't report a failure to circuit breaker when a response duration exceeds a certain point. To solve this, I've added AbstractRuleBuilder#onResponseDuration to access success or failure with response duration.

Modifications:

1. Added `responseDurationFilter` field to `AbstractRuleBuilder`
2. Modified RetryRuleBuilder, and CircuitBreakerRuleBuilder to use the `responseDurationFilter`

Result:

- Closes #4782
- You can now report a failure to a circuit breaking when the total duration exceeds a certain threshold.
  ```
  final CircuitBreakerRuleWithContent<HttpResponse> rule =
        CircuitBreakerRuleWithContent
                .<HttpResponse>builder()
                .onTotalDuration((ctx, duration) -> duration.toMillis() > 10000)
                .thenFailure();
  ```

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java [hunk 1]
```diff
@@ -372,10 +373,15 @@ private void handleResponse(RetryConfig<HttpResponse> retryConfig, ClientRequest
...
         assert response != null || aggregatedRes != null;
         final RequestLogProperty logProperty =
-                retryConfig.requiresResponseTrailers() ?
-                RequestLogProperty.RESPONSE_TRAILERS : RequestLogProperty.RESPONSE_HEADERS;
+                retryConfig.requiresResponseTrailers() ? null : RequestLogProperty.RESPONSE_HEADERS;
 
-        derivedCtx.log().whenAvailable(logProperty).thenAccept(log -> {
+        final CompletableFuture<RequestLog> logFuture;
+        if (logProperty == null) {
+            logFuture = derivedCtx.log().whenComplete();
```
Comment (babjo) [inline core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:380]: `GrpcClientRetryTest#childrenContextsHaveSameRpcRequest` unittest failed because `RequestLogProperty.RESPONSE_CONTENT` wasn't set, and the chain of this `whenComplete` couldn't be invoked.

Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:380]: I'll take some time to think about how I can address this issue.

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java [hunk 2]
```diff
@@ -335,11 +335,13 @@ private void doExecute0(ClientRequestContext ctx, HttpRequestDuplicator rootReqD
                                                  future, derivedCtx, HttpResponse.ofFailure(cause), cause);
                     return null;
                 }
+                derivedCtx.logBuilder().responseContent(null, null);
                 handleResponse(config, ctx, rootReqDuplicator, originalReq, returnedRes, future, derivedCtx,
                                null, aggregated);
                 return null;
             });
         } else {
+            derivedCtx.logBuilder().responseContent(null, null);
```
Comment (babjo) [inline core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: I've set the response content for this issue below.
https://github.com/line/armeria/pull/4827#discussion_r1167421937

According to the `RequestLog`'s javadoc, response content is null for non-RPC. Retry client is for retries of HTTP requests, and so I've put `null` as the response content/preview. @ikhoon nim, may I do like this?
```java
    /**
     * Returns the high-level content object of the {@link Response}, which is specific
     * to the {@link SerializationFormat}.
     *
     * @return {@link RpcResponse} for RPC, or {@code null} for others
     *
     * @throws RequestLogAvailabilityException if the property is not available yet.
     * @see RequestLogProperty#RESPONSE_CONTENT
     */
    @Nullable
    Object responseContent();
```

Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: > What do you think of changing the API name to onResponseEnd() and using RequestLogProperty.RESPONSE_END_TIME as the waiting flag?
We need to note that deferred properties may not be available on the callback of rule.onResponseEnd((ctx, log) -> ...)

I got what you meant. Let me update this PR.

Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: > We need to note that deferred properties may not be available on the callback of rule.onResponseEnd((ctx, log) -> ...)

How about changing the interface to the following: `rule.onResponseDuration((ctx, nanos) -> {})`? As previously mentioned, we have to make clients aware that some properties may not available. To do that, we'll need to add javadoc or something. Instead, to ensure clarity, we just wait for RequestLogProperty.RESPONSE_END_TIME flag to be set, and pass only the responseDurationNanos rather than the entire requestLog?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: Only a response duration is exposed by `onResponseDuration((ctx, nanos) -> {})`. I'd like to make it more general to access available information when a response ends.

Anyway, we can simply implement `onResponseDuration(..)` on top of `onResponseEnd()`.
What do you think of adding both versions and getting feedback from other maintainers?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: I don't think it's a good idea to add `onResponseDuration` because
- we can get the duration easily via the log.
- the duration usually doesn't play a role in Retrying or CircuitBreaking.

I'm also worried about the situation that we end up with a bunch of APIs that are useless.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: I'm also leaning toward removing the `requestLog` from the `onResponseEnd()` method because
- we can get the `requestLog` easily via `ctx.log()`
- we, anyway, have to check the `RequestLogAvailiability` using `ctx.log().isAvailable(pro)` for the deferred properties.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: I've changed my mind and I actually like the idea of adding `onResponseDuration((ctx, nanos) -> {...})` instead of `onResponseEnd()`.
We can use the duration when we make a decision for circuit breaking and I think adding `onResponseDuration((ctx, nanos) -> {...})` is much better than adding `onResponseEnd((ctx, log) -> {...})` which uses `RequestLog` for the BiPredicate. `RequestLog` is simple retrievable via `ctx.log()`

Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:344]: > What do you think of adding both versions and getting feedback from other maintainers?

@ikhoon nim no problem, but according to @minwoox nim, `onResponseDuration` looks better for him like below. Let me add `onResponseDuration(...)` 🙇 

> I've changed my mind and I actually like the idea of adding onResponseDuration((ctx, nanos) -> {...}) instead of onResponseEnd().
We can use the duration when we make a decision for circuit breaking and I think adding onResponseDuration((ctx, nanos) -> {...}) is much better than adding onResponseEnd((ctx, log) -> {...}) which uses RequestLog for the BiPredicate. RequestLog is simple retrievable via ctx.log()

Thank you for your advice!

File: core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java [hunk 3]
```diff
@@ -197,6 +201,17 @@ public AbstractRuleBuilder onUnprocessed() {
         return onException(UnprocessedRequestException.class);
     }
 
+    /**
+     * Adds the specified {@code responseDurationNanosFilter}.
+     */
+    public AbstractRuleBuilder onResponseDurationNanos(
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java:207]: How about adding `onResponseDuration(BiPredicate<? super ClientRequestContext, ? super Duration>)` as well? We could delegate to `onResponseDurationNanos()`.

**Review by trustin — COMMENTED** [review]
What if a user is interested in request duration or total duration rather than response duration? Can we generalize it a little bit more? e.g.

```java
builder
  .onLogComplete((ctx, log) -> log.requestDurationNanos() > 100)
  .thenFailure();
// .. or ..
builder
  .onLog((ctx, log) -> ...,
         RequestLogProperty.RESPONSE_END, ...)
  .thanFailure();
```

Then, we could implement `onResponseDuration` (and/or some existing builder methods) on top of it.

File: core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java (hunk 3 above)
Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java:207]: > Can we generalize it a little bit more?

Looks good to me. Let me update this PR! Thank you for your comment!

**Comment by babjo** [comment]
@ikhoon nim, gentle ping 🙇

**Comment by ikhoon** [comment]
I prefer to only add `onResponseDuration(BiPredicate<? super ClientRequestContext, ? super Duration>)` and its variant at the moment until we have a better idea to avoid the deadlock.

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java [hunk 4]
```diff
@@ -382,10 +385,10 @@ default RetryRule orElse(RetryRule other) {
...
     /**
-     * Returns whether this rule requires the response trailers to determine if a {@link Response} is
-     * successful or not.
+     * Returns a set of {@link RequestLogProperty} to be required to evaluate this rule and to determine
+     * if a {@link Response} is successful or not.
      */
-    default boolean requiresResponseTrailers() {
-        return false;
+    default Set<RequestLogProperty> getRequiredLogProperties() {
+        return Collections.emptySet();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java:392]: Should we revert this? `RetryRule` is an API created for users to inherit and implement.
The breaking change would not be acceptable to them in a minor upgrade.

Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java]: Updated!

File: core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java [hunk 5]
```diff
@@ -86,8 +92,9 @@ public Boolean apply(ClientRequestContext ctx, Throwable cause) {
 
             // Safe to return true since no filters are set
             if (exceptionFilter == null && responseHeadersFilter == null &&
-                responseTrailersFilter == null && grpcTrailersFilter == null &&
-                !hasResponseFilter) {
+                    responseTrailersFilter == null && grpcTrailersFilter == null &&
+                    responseDurationFilter == null &&
+                    !hasResponseFilter) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java:97]: nit: Indent
```suggestion
                responseTrailersFilter == null && grpcTrailersFilter == null &&
                responseDurationFilter == null &&
                !hasResponseFilter) {
```

File: core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java [hunk 6]
```diff
@@ -135,7 +142,8 @@ private boolean applySlow(ClientRequestContext ctx, @Nullable Throwable cause, R
                 }
             }
 
-            return false;
+            return responseDurationFilter != null &&
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java:145]: - Don't we need to change `RequestLogProperty.RESPONSE_TRAILERS` to `RequestLogProperty.RESPONSE_END_TIME`?
https://github.com/line/armeria/blob/2bb48ade4cbdcfd10506003fb7420b20cfd97f55/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L377-L378
https://github.com/line/armeria/blob/2bb48ade4cbdcfd10506003fb7420b20cfd97f55/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java#L335-L336
- Should we add `log.isAvailable(RequestLogProperty.RESPONSE_END_TIME)` to the condition just in case?

**Review by ikhoon — COMMENTED** [review]
Sorry for the late review. 😅
I believe we are on the same page.

**Comment by babjo** [comment]
Thank you for your review. Let me check this soon.

File: core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java (hunk 6 above)
Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java:145]: > Don't we need to change RequestLogProperty.RESPONSE_TRAILERS to RequestLogProperty.RESPONSE_END_TIME?

In the code below, I checked that `responseTrailers(log.responseTrailers())` set RequestLogProperty.RESPONSE_TRAILERS value first and `endResponse0(...)` set RequestLogProperty.RESPONSE_END_TIME value. Then, is the below correct?
```java
log().whenAvailable(RESPONSE_END_TIME).thenAccept(log ->  {
    // Here, can I ensure that `log` has response trailers?
    ...
})
```

https://github.com/line/armeria/blob/ce5b42f36a4a5515a28cee7a15b2a3e2ca5f76c2/core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java#L642-L648

> Should we add log.isAvailable(RequestLogProperty.RESPONSE_END_TIME) to the condition just in case?

Let me add that.

Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java]: Updated!

**Comment by babjo** [comment]
@ikhoon nim, gently ping 🙇

File: core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java [hunk 7]
```diff
@@ -135,6 +142,13 @@ private boolean applySlow(ClientRequestContext ctx, @Nullable Throwable cause, R
                 }
             }
 
+            if (responseDurationFilter != null && log.isAvailable(RequestLogProperty.RESPONSE_END_TIME)) {
+                final long responseEndTimeNanos = log.responseEndTimeNanos();
+                if (responseDurationFilter.test(ctx, Duration.ofNanos(responseEndTimeNanos))) {
```
[the remark this answers is not in the document]
Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java:147]: Oops let me update this.

File: core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java (hunk 5 above)
Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java]: No problem

File: core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java [hunk 8]
```diff
@@ -211,6 +215,15 @@ public AbstractRuleBuilder onUnprocessed() {
         return onException(UnprocessedRequestException.class);
     }
 
+    /**
+     * Adds the specified {@code totalDurationFilter}.
+     */
+    public AbstractRuleBuilder onTotalDuration(
+            BiPredicate<? super ClientRequestContext, ? super Duration> totalDurationFilter) {
+        this.totalDurationFilter = combinePredicates(this.totalDurationFilter, totalDurationFilter, "totalDurationFilter");
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java:223]: nit: lint 😉 
```suggestion
        this.totalDurationFilter = combinePredicates(this.totalDurationFilter, totalDurationFilter,
                                                     "totalDurationFilter");
```

**Review by minwoox — APPROVED** [review]
Just one nit. Thanks!

File: core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java (hunk 8 above)
Comment (babjo) [reply core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java]: Sure 🚀

**Review by ikhoon — APPROVED** [review]
Thanks a lot, @babjo! 🚀🚀

**Review by jrhee17 — APPROVED** [review]
Changes seem straightforward enough! Thanks @babjo 🙇 👍 🙇
