### PR TITLE
Fix flaky test in WebSocketServiceHttp2RequestCompleteTest

### LINKED ISSUE #6156: Flaky test: `WebSocketServiceHttp2RequestCompleteTest.closeAfterTimeoutWhenCloseFrameIsNotSent()`
```
WebSocketServiceHttp2RequestCompleteTest > closeAfterTimeoutWhenCloseFrameIsNotSent() FAILED
    org.awaitility.core.ConditionTimeoutException: Condition was evaluated in 100 milliseconds which is earlier than expected minimum timeout 1 seconds
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:172)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1129)
        at app//com.linecorp.armeria.server.websocket.WebSocketServiceHttp2RequestCompleteTest.closeAfterTimeoutWhenCloseFrameIsNotSent(WebSocketServiceHttp2RequestCompleteTest.java:124)

```

### LINKED ISSUE #6215: Test failure: `com.linecorp.armeria.server.websocket.WebSocketServiceHttp2RequestCompleteTest.closeAfterTimeoutWhenCloseFrameIsNotSent()`
```
org.awaitility.core.ConditionTimeoutException: Condition was evaluated in 105 milliseconds which is earlier than expected minimum timeout 1 seconds
	at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:172)
	at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
	at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1129)
	at app//com.linecorp.armeria.server.websocket.WebSocketServiceHttp2RequestCompleteTest.closeAfterTimeoutWhenCloseFrameIsNotSent(WebSocketServiceHttp2RequestCompleteTest.java:124)
	at java.base@17.0.14/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base@17.0.14/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.14/java.util.ArrayList.forEach(ArrayList.java:1511)

```

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
The test calls `updateRequest` on the client with an arbitrary request because the client closes the request upon receiving a response from the server, which triggers the WebSocket close frame. However, there's a race condition: `updateRequest` can be invoked after the client has already closed the request, leading to test failures. See:
https://github.com/line/armeria/blob/b78d9515dc8b4b997dd65787f717443b38a21869/core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceHttp2RequestCompleteTest.java#L117

Result:
- Close #6156
- Close #6215

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceHttp2RequestCompleteTest.java [hunk 1]
```diff
@@ -109,15 +107,13 @@ void closeAfterTimeoutWhenCloseFrameIsNotSent() throws InterruptedException {
...
-                captor.get().updateRequest(HttpRequest.of(HttpMethod.GET, "/"));
-            });
-            split.body().subscribe(bodySubscriber);
-        }
+        final SplitHttpResponse split = WebClient.builder(client.uri())
+                                                 // Not to send the close frame from the client.
+                                                 .requestAutoAbortDelayMillis(Long.MAX_VALUE)
+                                                 .build()
+                                                 .execute(requestWriter).split();
+        split.headers().thenAccept(headers -> assertThat(headers.status()).isSameAs(HttpStatus.OK));
```
Comment (jrhee17) [inline core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceHttp2RequestCompleteTest.java]: nit; not that it matters but I believe assertions that aren't thrown from the main junit test thread won't be propagated (i.e. won't count towards test failure)

**Review by jrhee17 — APPROVED** [review]

File: core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceHttp2RequestCompleteTest.java (hunk 1 above)
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceHttp2RequestCompleteTest.java]: That is true. Updated. 😉
