### PR TITLE
Record causes of failed attempts for RetryingClient

### LINKED ISSUE #5283: Record causes of failed attempts for `RetryingClient`
Only the number of failure attempts is recorded, it is difficult to know why the attempts failed.
https://github.com/line/armeria/blob/90969d1fec7a8d47957daf958474339f6e11f523/core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java#L171

It would be good if the cause was recorded as a tag of the meter.
```
"actual.requests.attempts{result=failure, cause=ResponseTimeoutException}=NN"
```

### PR DESCRIPTION
**Pull request by my4-dev**
Motivation:
#5283

Modifications:
- Separating `onResponse` into `onResponseOnClient` and `onResponseOnServer` as refactoring
- Add `failureAttempts(Throwable error)` and `failureAttempts(HttpStatus httpstatus)` at `ClientRequestMetrics` and make us enable to record causes of failed attempts

Result:

- Closes #5283
- The metrics for failed requests while retrying now include the cause of the failure.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java [hunk 1]
```diff
@@ -345,6 +391,9 @@ private static class DefaultClientRequestMetrics
             final String timeouts = idPrefix.name("timeouts");
             writeTimeouts = parent.counter(timeouts, idPrefix.tags("cause", "WriteTimeoutException"));
             responseTimeouts = parent.counter(timeouts, idPrefix.tags("cause", "ResponseTimeoutException"));
+
+            failureAttemptsWithCause = new HashMap<>();
+            failureAttemptsWithHttpStatus = new HashMap<>();
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java:396]: To be honest, I don't think this optimization is really necessary since we'll be doing a map search once anyways when calling `MeterRegistry#counter`.

**Review by jrhee17 — COMMENTED** [review]
Looks good overall! Left some minor comments 🙇

File: core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java [hunk 2]
```diff
@@ -411,6 +436,14 @@ public DistributionSummary failureAttempts() {
                                                             idPrefix.tags("result", "failure"),
                                                             distributionStatisticConfig());
         }
+
+        @Override
+        public Counter actualRequestsCause(@Nullable Throwable cause, HttpStatus status) {
+            final String causeStr = cause != null ? cause.getClass().getSimpleName() : "null";
+            return parent.counter(
+                    idPrefix.name("actual.requests.cause"),
+                    idPrefix.tags("cause", causeStr, "http.status", status.codeAsText()));
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java:445]: note: I think we can potentially add a `direction` tag later to denote if this is `requestCause` or `responseCause`.

**Review by jrhee17 — APPROVED** [review]
Pushed a small commit since we're about to cut the next release. Let me know if anything doesn't make sense 🙇

**Review by minwoox — APPROVED** [review]
Looks great, thanks!

File: core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java [hunk 3]
```diff
@@ -169,15 +171,22 @@ private static void updateMetrics(
...
         metrics.actualRequests().increment(childrenSize);
-
         if (isSuccess) {
             metrics.successAttempts().record(childrenSize);
         } else {
             metrics.failureAttempts().record(childrenSize);
         }
+
+        final int failedAttempts = isSuccess ? childrenSize - 1 : childrenSize;
+        for (int i = 0; i < failedAttempts ; i++) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java:184]:
```suggestion
        for (int i = 0; i < failedAttempts; i++) {
```

**Comment by minwoox** [comment]
Thanks a lot, @my4-dev!
