### PR TITLE
Merge DynamicHttpService into the core (Go HTTP-only, part 2)

### LINKED ISSUE #439: Simplify the call stack of DynamicHttpService deserialization failure
DynamicHttpService produces unnecessarily nested stack traces when parameter deserialization fails:

```
10:40:41.052 [armeria-server-epoll-50-7] WARN  c.l.a.s.http.HttpResponseSubscriber - [id: 0xcf5e4766, L:/127.0.0.1:45115 - R:/127.0.0.1:35144] Unexpected exception from a service or a response publisher: LoggingService(com.linecorp.armeria.server.http.dynamic.DynamicHttpService@a8a2d31)
java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at com.linecorp.armeria.common.AbstractRequestContext.lambda$makeContextAware$1(AbstractRequestContext.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpFunctionImpl.lambda$serve$0(DynamicHttpFunctionImpl.java:90)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 5 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpFunctionImpl.lambda$serve$0(DynamicHttpFunctionImpl.java:88)
	... 6 common frames omitted
Caused by: java.lang.IllegalArgumentException: bad var!
	at com.linecorp.armeria.server.http.HttpServiceTest$ResponseStrategy.exception(HttpServiceTest.java:191)
	... 11 common frames omitted
```

IllegalStateException and InvocationTargetException could be omitted from the exception.

Potentially this one as well (NumberFormatException could be omitted?):

```
10:40:41.042 [armeria-server-epoll-50-4] WARN  c.l.a.s.http.HttpResponseSubscriber - [id: 0xeb213359, L:/127.0.0.1:45115 - R:/127.0.0.1:35138] Unexpected exception from a service or a response publisher: LoggingService(com.linecorp.armeria.server.http.dynamic.DynamicHttpService@a8a2d31)
java.lang.IllegalArgumentException: Can't deserialize fourty-two to type int
	at com.linecorp.armeria.server.http.dynamic.Deserializers.deserialize(Deserializers.java:56)
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpFunctionImpl.parameters(DynamicHttpFunctionImpl.java:75)
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpFunctionImpl.serve(DynamicHttpFunctionImpl.java:82)
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpFunctions.executeSyncOrAsync(DynamicHttpFunctions.java:127)
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpFunctions.lambda$of$3(DynamicHttpFunctions.java:119)
	at com.linecorp.armeria.server.http.dynamic.MappedDynamicFunction.serve(MappedDynamicFunction.java:38)
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpService.serve(DynamicHttpService.java:60)
	at com.linecorp.armeria.server.http.dynamic.DynamicHttpService.serve(DynamicHttpService.java:36)
	at com.linecorp.armeria.server.logging.LoggingService.serve(LoggingService.java:65)
	at com.linecorp.armeria.server.http.HttpServerHandler.handleRequest(HttpServerHandler.java:300)
	at com.linecorp.armeria.server.http.HttpServerHandler.channelRead(HttpServerHandler.java:206)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at com.linecorp.armeria.server.http.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:137)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at com.linecorp.armeria.internal.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "fourty-two"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.linecorp.armeria.server.http.dynamic.Deserializers.deserialize(Deserializers.java:41)
	... 50 common frames omitted
```

/cc @dongjinleekr

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

It would be much more convenient if a user can add an annotated HTTP
service object to a ServerBuilder or a VirtualHostBuilder.

Modifications:

- Move DynamicHttpService and its related implementation classes to
  com.linecorp.armeria.server
- Add ServerBuilder.service(...) which adds an annotated service object
  - Remove DynamicHttpServiceBuilder
- Reorganize DynamicHttpService and its related implementations
  - Merge DynamicHttpService, DynamicHttpFunctionEntry and
    MappedDynamicFunction into AnnotatedHttpService
  - Replace DynamicHttpFunction with BiFunction
  - Rename DynamicHttpFunctionImpl to AnnotatedHttpServiceMethod
  - Move various utility methods in DynamicHttpFunctions and
    Deserializers to their related classes so that it's easier to read
    the code
    - Remove DynamicHttpFunctions and Deserializers
  - Rename ParameterEntry to Parameter and make it an inner class of
    AnnotatedHttpServiceMethod
- Split HttpServiceTest into two
  - HttpServiceTest tests basic HttpService support
  - AnnotatedHttpServiceTest tests annotated service support
- Miscellaneous:
  - Add 'Unspecified', an inner class of the Converter annotation which
    is dedicated to represent the case where 'target' is unspecified
    - Change the default value of Converter.target() to Unspecified.class
  - Add more factory methods to HttpResponse for convenience and use
    them where possible
  - Simplify the stack trace of the exception which is raised when
    conversion fails

Result:

- DynamicHttpService has been merged into the core. A user does not need
  to instantiate a certain service type to bind an annotated service
  object.
- Fixes #439

To-dos:

- Add path overlap detection again
- Overall package reorganization
  - There's no point of having 'http' or 'dynamic' in a package name.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java [hunk 1]
```diff
@@ -0,0 +1,322 @@
...
+        for (Class<?> iface : Types.getAllInterfaces(type)) {
+            ResponseConverter converter = converters.get(iface);
+            if (converter != null) {
+                return converter;
+            }
+        }
+
+        // Search for the converter mapped to Object.class.
+        if (converters.containsKey(Object.class)) {
+            return converters.get(Object.class);
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java]: 👍

File: core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java [hunk 2]
```diff
@@ -237,6 +241,41 @@ public B service(PathMapping pathMapping,
     }
 
     /**
+     * Binds the specified annotated service object.
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java]: ` to all URLs (e.g., catch-all).` ?

Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java]: Not really. It will create a path mapping from the `@Path` annotation.

Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java]: Then maybe `under the path prefix "/"`, which is consistent with the docstring of the versions that take `pathPrefix`. I think it does need some sort of clarification.

File: core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java (hunk 1 above)
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java]: I didn't write this. :-)

File: core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java (hunk 2 above)
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java]: Good idea. Fixed.

File: core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java [hunk 3]
```diff
@@ -45,48 +49,52 @@
     private final PathMapping pathMapping;
 
     /**
-     * {@link DynamicHttpFunction} instance that will be invoked with given {@link HttpMethod} and
-     * {@link PathMapping}.
+     * The {@link BiFunction} that will be handle the request actually.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java]: will handle?

Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java]: Fixed
