### PR TITLE
Listens to the result of querying DnsRecords

### LINKED ISSUE #4690: Provide a way to set the number of attempts to decide whether to warn or not when DNS query failed
I occasionally see the following warning
`DNS query failed; retrying in {} ms (attempts so far: 1)`

This warning is important when we make DNS query for the first time.
However, considering retrying,  I guess that it is not so important when making DNS query due to TTL expiration.

How about setting the number of attempts to decide whether outputting the warning for queries due to TTL expiration?

### PR DESCRIPTION
**Pull request by ta7uw**
Motivation:

Described in https://github.com/line/armeria/issues/4690

Modifications:

- Add `DnsQueryListener` to listen to the result of querying `DnsRecord`s.
- Add `DnsEndpointGroupBuilder#addDnsQueryListeners `

Result:

- Closes #4690
- Users can easily write their own processes based on the results of the DNS records. 
   For example, users can ignore warnings due to TTL expiration.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java [hunk 1]
```diff
@@ -223,4 +230,18 @@ public String toString() {
                 .add("attemptsSoFar", attemptsSoFar)
                 .toString();
     }
+
+    class DnsQuestionListenerImpl implements DnsQuestionListener {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java:234]: Should we make this singleton? We can add a factory method for the default instance.
```java
// Returns the default instance.
DnsQuestionListener.of();
```
This might be useful to explain the default behavior in Javadoc when no custom `DnsQuestionListener` is configured.

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java [hunk 2]
```diff
@@ -253,4 +253,15 @@ public DnsAddressEndpointGroupBuilder selectionTimeout(Duration selectionTimeout
     public DnsAddressEndpointGroupBuilder selectionTimeoutMillis(long selectionTimeoutMillis) {
         return (DnsAddressEndpointGroupBuilder) super.selectionTimeoutMillis(selectionTimeoutMillis);
     }
+
+    @Override
+    public DnsAddressEndpointGroupBuilder addDnsQuestionListeners(
+            Iterable<DnsQuestionListener> dnsQuestionListeners) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java:259]:
```suggestion
            Iterable<? extends DnsQuestionListener> dnsQuestionListeners) {
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java [hunk 3]
```diff
@@ -153,6 +157,29 @@ final DefaultDnsResolver buildResolver(Consumer<DnsNameResolverBuilder> customiz
                                      hostsFileEntriesResolver());
     }
 
+    /**
+     * Adds the {@link DnsQuestionListener}s that listens to the result of querying {@link DnsRecord}s.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java:161]: Should we add the comment to other Javadocs as well?
```suggestion
     * Adds the {@link DnsQuestionListener}s that listens to the result of querying {@link DnsRecord}s.
     * If no {@link DnsQuestionListener} is configured, {@link DnsQuestionListener#of()}
     * is used by default
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java [hunk 4]
```diff
@@ -153,6 +157,29 @@ final DefaultDnsResolver buildResolver(Consumer<DnsNameResolverBuilder> customiz
...
+     */
+    public DnsEndpointGroupBuilder addDnsQuestionListeners(Iterable<DnsQuestionListener> dnsQuestionListeners) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java:163]: Please add `@UnstableApi` to the new public APIs.
```suggestion
    @UnstableApi
    public DnsEndpointGroupBuilder addDnsQuestionListeners(Iterable<DnsQuestionListener> dnsQuestionListeners) {
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsQuestionListener.java [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+ *  Listens to the result of querying {@link DnsRecord}s.
+ */
+@UnstableApi
+public interface DnsQuestionListener {
+
+    /**
+     * Invoked when querying {@link DnsRecord}s successfully.
+     *
+     * @param oldRecords old dns records which were to be updated. If {@code null}, it indicates that
+     *                   this querying is called after initialization.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsQuestionListener.java:36]: `oldRecords` could be null even after initialization when a custom `DnsCache` using a weak reference is used.
```suggestion
     *                   this querying is called after initialization or the old
     *                   records were garbage-collected by the {@link DnsCache}
     *                   implementation.
```

**Review by ikhoon — COMMENTED** [review]
Mostly looks good.

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQuestionListener.java [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+
+import com.linecorp.armeria.common.annotation.Nullable;
+import com.linecorp.armeria.common.annotation.UnstableApi;
+
+import io.netty.handler.codec.dns.DnsRecord;
+
+/**
+ * A default implementation of {@link DnsQuestionListener} interface.
+ */
+@UnstableApi
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQuestionListener.java:32]: We don't `@UnstableApi` for non-public class
```suggestion
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java [hunk 7]
```diff
@@ -143,38 +148,41 @@ private void sendQueries(List<DnsQuestionWithoutTrailingDot> questions) {
...
-            final long delayMillis = backoff.nextDelayMillis(attemptsSoFar);
-            logger.warn("{} DNS query failed; retrying in {} ms (attempts so far: {}):",
-                        logPrefix, delayMillis, attemptsSoFar, cause);
-            scheduledFuture = eventLoop.schedule(() -> sendQueries(questions),
-                                                 delayMillis, TimeUnit.MILLISECONDS);
-            return null;
-        }
+            dnsQuestionListeners.forEach(dnsQuestionListener -> dnsQuestionListener.onSuccess(oldRecords,
+                                                                                              newRecords,
+                                                                                              logPrefix));
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java:168]: - How about using for-loop which is more concise in this case?
- We need to wrap code with try-catch block when calling user-defined code.
```java
for (DnsQuestionListener listener : dnsQuestionListeners) {
    try {
        listener.onSuccess(oldRecords, newRecords, logPrefix);
    } catch (Exception ex) {
        logger.warn("Unexpected exception while invoking {}", listener, ex);
    }
}
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java [hunk 8]
```diff
@@ -143,38 +148,41 @@ private void sendQueries(List<DnsQuestionWithoutTrailingDot> questions) {
...
 
-    private Void onDnsRecords(@Nullable List<DnsRecord> records, @Nullable Throwable cause) {
-        if (isClosing()) {
-            return null;
-        }
+            if (cause != null) {
+                // Failed. Try again with the delay given by Backoff.
+                final long delayMillis = backoff.nextDelayMillis(attemptsSoFar);
+                dnsQuestionListeners.forEach(dnsQuestionListener -> dnsQuestionListener.onFailure(
+                        oldRecords, cause, logPrefix, delayMillis, attemptsSoFar));
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java:160]: Ditto.

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQuestionListener.java [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+final class DefaultDnsQuestionListener implements DnsQuestionListener {
+
+    static final DnsQuestionListener DEFAULT_INSTANCE = new DefaultDnsQuestionListener();
+
+    private final Logger logger = LoggerFactory.getLogger(getClass());
+
+    @Override
+    public void onSuccess(@Nullable List<DnsRecord> oldRecords, List<DnsRecord> newRecords, String logPrefix) {}
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQuestionListener.java:40]: Question: Can we use an empty list to signity 'no old records'?

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java [hunk 10]
```diff
@@ -253,4 +253,15 @@ public DnsAddressEndpointGroupBuilder selectionTimeout(Duration selectionTimeout
...
     }
+
+    @Override
+    public DnsAddressEndpointGroupBuilder addDnsQuestionListeners(
+            Iterable<? extends DnsQuestionListener> dnsQuestionListeners) {
+        return (DnsAddressEndpointGroupBuilder) super.addDnsQuestionListeners(dnsQuestionListeners);
+    }
+
+    @Override
+    public DnsAddressEndpointGroupBuilder addDnsQuestionListener(DnsQuestionListener dnsQuestionListener) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java:264]: - Could use a plural form with varargs?
- This class is already about DNS, how about simplifying the names a little bit, e.g. `addQueryListener()`?
  - `DnsQuestionListener` could be renamed to `DnsQueryListener`

**Comment by trustin** [comment]
I see a little bit of overlap between `DnsQueryLifecycleObserver` although `DnsQuestionListener` acts at a higher level. I'm curious if we could reuse `DnsQueryLifecycleObserver` somehow, although I don't have a good idea at the moment.

**Comment by ta7uw** [comment]
It would be difficult to reuse `DnsQueryLifecycleObserver`  because of the different target layers.

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQueryListener.java [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import io.netty.handler.codec.dns.DnsRecord;
+
+/**
+ * A default implementation of {@link DnsQueryListener} interface.
+ */
+final class DefaultDnsQueryListener implements DnsQueryListener {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQueryListener.java:29]: nit: We could use the enum singleton pattern?

**Review by trustin — APPROVED** [review]
LGTM. Just one nit which is probably OK to ignore.

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java [hunk 12]
```diff
@@ -153,6 +159,35 @@ final DefaultDnsResolver buildResolver(Consumer<DnsNameResolverBuilder> customiz
                                      hostsFileEntriesResolver());
     }
 
+    /**
+     * Adds the {@link DnsQueryListener}s that listens to the result of querying {@link DnsRecord}s.
+     * If no {@link DnsQueryListener} is configured, {@link DnsQueryListener#of()} is used by default
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java:164]:
```suggestion
     * If no {@link DnsQueryListener} is configured, {@link DnsQueryListener#of()} is used by default.
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java [hunk 13]
```diff
@@ -153,6 +159,35 @@ final DefaultDnsResolver buildResolver(Consumer<DnsNameResolverBuilder> customiz
...
+        requireNonNull(dnsQueryListeners, "dnsQueryListeners");
+        for (DnsQueryListener listener: dnsQueryListeners) {
+            this.dnsQueryListeners.add(listener);
+        }
+        return this;
+    }
+
+    /**
+     * Adds the {@link DnsQueryListener} that listens to the result of querying {@link DnsRecord}s.
+     * If no {@link DnsQueryListener} is configured, {@link DnsQueryListener#of()} is used by default
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java:178]:
```suggestion
     * If no {@link DnsQueryListener} is configured, {@link DnsQueryListener#of()} is used by default.
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java [hunk 14]
```diff
@@ -153,6 +159,35 @@ final DefaultDnsResolver buildResolver(Consumer<DnsNameResolverBuilder> customiz
...
+     */
+    @UnstableApi
+    public DnsEndpointGroupBuilder addDnsQueryListeners(DnsQueryListener... dnsQueryListeners) {
+        requireNonNull(dnsQueryListeners, "dnsQueryListeners");
+        this.dnsQueryListeners.addAll(Arrays.asList(dnsQueryListeners));
+        return this;
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java:184]: Delegate to `Iterable` version?
```suggestion
        return dnsQueryListeners(ImmutableList.copyOf(dnsQueryListeners));
```

**Review by ikhoon — APPROVED** [review]
Thanks, @ta7uw! 🙇‍♂️

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQueryListener.java [hunk 15]
```diff
@@ -26,9 +26,9 @@
 /**
  * A default implementation of {@link DnsQueryListener} interface.
  */
-final class DefaultDnsQueryListener implements DnsQueryListener {
+enum DefaultDnsQueryListener implements DnsQueryListener {
 
-    static final DnsQueryListener DEFAULT_INSTANCE = new DefaultDnsQueryListener();
+    DEFAULT_INSTANCE;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQueryListener.java:31]: nit: just `INSTANCE`?

**Review by trustin — APPROVED** [review]

**Review by jrhee17 — APPROVED** [review]
Left a super minor comment but looks good overall! 🙏  Thanks @ta7uw 🙇 👍 🚀

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQueryListener.java [hunk 16]
```diff
@@ -0,0 +1,44 @@
...
+import io.netty.handler.codec.dns.DnsRecord;
+
+/**
+ * A default implementation of {@link DnsQueryListener} interface.
+ */
+enum DefaultDnsQueryListener implements DnsQueryListener {
+
+    INSTANCE;
+
+    private final Logger logger = LoggerFactory.getLogger(getClass());
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQueryListener.java:33]: nit:
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(DefaultDnsQueryListener.class);
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java [hunk 17]
```diff
@@ -143,38 +149,50 @@ private void sendQueries(List<DnsQuestionWithoutTrailingDot> questions) {
...
-            return null;
-        }
+            if (cause != null) {
+                // Failed. Try again with the delay given by Backoff.
+                final long delayMillis = backoff.nextDelayMillis(attemptsSoFar);
+                for (DnsQueryListener listener : dnsQueryListeners) {
+                    try {
+                        listener.onFailure(oldRecords, cause, logPrefix, delayMillis, attemptsSoFar);
+                    } catch (Exception ex) {
+                        logger.warn("Unexpected exception while invoking {}", listener, ex);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java:164]: nit:
```suggestion
                        logger.warn("Unexpected exception while invoking listener.onFailure(). listener: {}",
                                    listener, ex);
```

File: core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java [hunk 18]
```diff
@@ -143,38 +149,50 @@ private void sendQueries(List<DnsQuestionWithoutTrailingDot> questions) {
...
-                        logPrefix, delayMillis, attemptsSoFar, cause);
-            scheduledFuture = eventLoop.schedule(() -> sendQueries(questions),
-                                                 delayMillis, TimeUnit.MILLISECONDS);
-            return null;
-        }
+            for (DnsQueryListener listener : dnsQueryListeners) {
+                try {
+                    listener.onSuccess(oldRecords, newRecords, logPrefix);
+                } catch (Exception ex) {
+                    logger.warn("Unexpected exception while invoking {}", listener, ex);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java:176]: nit:
```suggestion
                    logger.warn("Unexpected exception while invoking listener.onSuccess(). listener: {}",
                                    listener, ex);
```

**Review by minwoox — APPROVED** [review]
Just nits. 
Thanks a lot, @ta7uw!

**Comment by ikhoon** [comment]
Thanks always, @ta7uw! 🙇
