### PR TITLE
Do not collect metrics of the requests to `TransientService` by default

### LINKED ISSUE #3061: Should we exclude health check requests from metrics by default?
If a user uses Armeria client and server, the duration for a health check request is 60 seconds by default.
This might confuse the user that something is wrong with the server because a request takes so long if he/she monitors the request metric together.

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
Related #3061
It will be nice if the request and response to/from `TransientService` are not logged in the server-side by default.

Modifications:
- Do not collect metrics of the requests and responses to/from a `TransientService`.
  - Do not leave access logs and service logs as well.
- Added `TransientServiceOption` enum:
  - `WITH_MECTIC_COLLECTION`, `WITH_SERVICE_LOGGING` and `WITH_ACCESS_LOGGING`.
- Added `TransientServiceBuilder.transientServiceOptions(...)` to enable the options.
- `PrometheusExpositionService` now implements `TransientService`.
  - `PrometheusExpositionService.builder()` is also added.

Result:
- The metrics of requests to a `TransientService` are not collected by default.
  - You should call `TransientServiceBuilder.transientServiceOptions(WITH_METRIC_COLLECTION)` to collect.
  - Access logs and service logs are not recorded as well.
- Close #3061
- (Deprecated) `new PrometheusExpositionService(CollectorRegistry)` is now deprecated.
  - Use `PrometheusExpositionService.of(CollectorRegistry)`.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java [hunk 1]
```diff
@@ -35,20 +38,50 @@
...
+     */
+    public static PrometheusExpositionService of(CollectorRegistry collectorRegistry) {
+        return new PrometheusExpositionService(collectorRegistry, false);
+    }
+
+    /**
+     * Returns a new {@link PrometheusExpositionService} that exposes Prometheus metrics from the specified
+     * {@link CollectorRegistry}.
+     *
+     * @param shouldLogRequest tells whether the request and response are logged or recorded by
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java:57]: How about: 
... whether the request and response handled by this {@link PrometheusExpositionService} are logged ...?

File: core/src/main/java/com/linecorp/armeria/server/Service.java [hunk 2]
```diff
@@ -103,4 +106,12 @@ default void serviceAdded(ServiceConfig cfg) throws Exception {}
     default boolean shouldCachePath(String path, @Nullable String query, Route route) {
         return route.pathType() == RoutePathType.EXACT && query == null;
     }
+
+    /**
+     * Returns whether the request and response are logged or recorded by
+     * {@link LoggingService}, {@link MetricCollectingService} and {@link AccessLogWriter}.
+     */
+    default boolean shouldLogRequest() {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/Service.java:114]: How about removing this method and checking by?:
```java
if (service instanceof TransientService && (TransientService service).shouldLogRequest()) {
   ...
  
}
```

**Comment by trustin** [comment]
Wouldn't it be better allowing a user to set whether a service is transient or not via service binding builders, so that the user doesn't need to provide the override option for every service:

```java
Server
  .builder()
  .route()
    .get(...)
    .transient(true) // Force-enable transient
    .build(...)
  .route()
    .get(...)
    .transient(false) // Force-disable transient
    .build(...)
  .route()
    .get(...)
    .build(...) // Transient if implements TransientService
  .build();
```

We will also need to add `ServiceConfig.isTransient()` and change how we determine if a service is transient in some places, e.g. graceful shutdown.

**Comment by minwoox** [comment]
All fixed. PTAL. 😉

File: core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java [hunk 3]
```diff
@@ -405,7 +405,8 @@ private void handleRequest(ChannelHandlerContext ctx, DecodedHttpRequest req) th
 
             // Keep track of the number of unfinished requests and
             // clean up the request stream when response stream ends.
-            final boolean isTransient = service.as(TransientService.class) != null;
+            final boolean isTransient = service.as(TransientService.class) != null ||
+                                        serviceCfg.transientService();
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java:409]: We should only check `ServiceConfig.transientService()` and set `true` to it when `service.as(TransientService.class) != null` *and* a user did not override it with `transientService(false)`.

**Comment by trustin** [comment]
@minwoox and I had a chat about this pull request and decided to do the following:

- Provide a way to specify an exclusion rule when binding a route decorator:
  ```java
  sb.routeDecorator()
    .pathPrefix("/foo")
    .except(SomeService.class)
    .except(someRoute)
    .build(...)
  ```
- Provide a way to specify an exclusion rule when creating an `AccessLogWriter`:
  ```java
  AccessLogWriter.common().except(SomeService.class);
  AccessLogWriter.common().except(someRoute);
  ```
- We will have to think more about the API design, so that we can specify more complex exclusion rules:
  - Exclude by service type
  - Exclude by route
  - ...

**Comment by trustin** [comment]
The reasoning behind this decision is that we cannot really know what user wants; we can't assume all  users want not to log health check requests for example.

**Comment by m50d** [comment]
> The reasoning behind this decision is that we cannot really know what user wants; we can't assume all users want not to log health check requests for example.

This is true; at the same time we should make sure to have reasonable behaviour by default (but overrideable as necessary) rather than forcing the user to repeat a lot of manual configuration even for the common case.

**Comment by trustin** [comment]
@m50d Agreed. What reasonable default behavior would you suggest?

**Comment by m50d** [comment]
I'd suggest a default filter (assuming some common filter interface shared by`LoggingService`, `AccessLogWriter` and `MetricCollectingService` ) that excludes `HealthCheckService` (by service type), since I think that's the behaviour that most users will want?

**Comment by trustin** [comment]
It's probably OK not to log health check requests, but I'm not sure if it's a good idea to collect metrics for health check requests. Why should it be handled differently from other services in terms of metric collection? Each service gets its own meters anyway, since it has a different `service` tag.

**Comment by m50d** [comment]
Actually metrics are the case where I really want to exclude health check requests: I'd like to have an overall 95th/99th/etc. percentile response time metric for my server, but including the (long-polling) health check response time makes that useless. Of course more sophisticated users will want to track each `service` individually, and/or will have other services that do long-polling so just excluding the healthcheck would be useless to them. But for the common/basic case where all my services are supposed to respond quickly and I want to see a single-number overview of what my performance looks like (and maybe alert on it etc.), a default of excluding the healthcheck but including everything else is the behaviour I'd like.

**Comment by trustin** [comment]
That makes sense. :+1:

Just wrapping my head to figure out how we can disable loggic/metric collection for them and allow enabling it optionally. Thoughts? @minwoox @ikhoon

**Comment by trustin** [comment]
A workaround for metric collection at the moment is to use Micrometer's meter filters.

**Comment by minwoox** [comment]
Thanks @m50d for the valuable opinion.
Yeah, I agree that it's better to disable logging/metric for those requests by default.

> Just wrapping my head to figure out 

I even got a headache for that. 🤣 
I don't have a better solution for now. So let me keep thinking about it.

**Comment by ikhoon** [comment]
> the (long-polling) health check response time makes that useless

Agreed. The long polling metric seems to polluate other metrics. It would be noisy and hard to detect actual long reponses by metric.

>  Yeah, I agree that it's better to disable logging/metric for those requests by default.

In my opinion, there is no harm to enable to log health check requests by default. 
I think most users grep logs in the terminal or web console such as Kibana. 
Sometime it would be useful whether to check the L7 load balancer is working by tailing log messages.
Any thought on this? @m50d

**Comment by m50d** [comment]
I don't have a strong view one way or the other on logging. I guess it's less surprising to see the healthcheck in the logs than not.

File: core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java [hunk 4]
```diff
@@ -250,13 +259,23 @@ public HealthCheckServiceBuilder updatable(HealthCheckUpdateHandler updateHandle
         return this;
     }
 
+    /**
+     * Sets whether the specified {@link ActionType} is enabled or not for the
+     * {@link #build() HealthCheckService}. All {@link ActionType}s are disabled by default.
+     */
+    public HealthCheckServiceBuilder transientServiceAction(ActionType actionType, boolean enable) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java:266]: Can use varags by removing `enable` from parameters?
```java
enableTransientServiceAction(ActionType... actionTypes);
```

File: core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java [hunk 5]
```diff
@@ -121,8 +123,10 @@ public static LoggingServiceBuilder builder() {
 
     @Override
     public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
-        if (sampler.isSampled(ctx)) {
-            logWhenComplete(logger, ctx, requestLogger, responseLogger);
+        if (TransientServiceUtil.countFor(ctx, ActionType.LOGGING)) {
+            if (sampler.isSampled(ctx)) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java:127]: nit: Merge two `if` conditions?

File: core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+        this.collectorRegistry = requireNonNull(collectorRegistry, "collectorRegistry");
+        transientServiceActions = new EnumMap<>(ActionType.class);
+        transientServiceActions.putAll(defaultTransientServiceActions());
+    }
+
+    /**
+     * Sets whether the specified {@link ActionType} is enabled or not for the
+     * {@link #build() PrometheusExpositionService}. All {@link ActionType}s are disabled by default.
+     */
+    public PrometheusExpositionServiceBuilder transientServiceAction(ActionType actionType, boolean enable) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java:49]: Ditto.

**Review by ikhoon — COMMENTED** [review]
Mostly LGTM. Left only minor nits.

File: core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java (hunk 4 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java:266]: Had a chat with @ikhoon and we decided to leave it as it is because the default value might be changed in the future.

File: core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java (hunk 5 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java]: Fixed. 😉

File: core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java [hunk 7]
```diff
@@ -250,13 +259,23 @@ public HealthCheckServiceBuilder updatable(HealthCheckUpdateHandler updateHandle
...
     /**
      * Returns a newly created {@link HealthCheckService} built from the properties specified so far.
      */
     public HealthCheckService build() {
         return new HealthCheckService(healthCheckers.build(),
                                       healthyResponse, unhealthyResponse,
                                       maxLongPollingTimeoutMillis, longPollingTimeoutJitterRate,
-                                      pingIntervalMillis, updateHandler);
+                                      pingIntervalMillis, updateHandler,
+                                      Maps.newEnumMap(ImmutableMap.copyOf(transientServiceActions)));
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java:279]: Could use `Maps.immutableEnumMap(...)`?
```suggestion
                                      Maps.immutableEnumMap(transientServiceActions));
```

File: core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java [hunk 8]
```diff
@@ -35,20 +41,45 @@
...
     public PrometheusExpositionService(CollectorRegistry collectorRegistry) {
-        requireNonNull(collectorRegistry, "collectorRegistry");
-        this.collectorRegistry = collectorRegistry;
+        this(collectorRegistry, defaultTransientServiceActions());
+    }
+
+    PrometheusExpositionService(CollectorRegistry collectorRegistry,
+                                EnumMap<ActionType, Boolean> transientServiceActions) {
+        this.collectorRegistry = requireNonNull(collectorRegistry, "collectorRegistry");
+        this.transientServiceActions = ImmutableMap.copyOf(transientServiceActions);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java:82]: Could use `Maps.immutableEnumMap()` to avoid addtional copies?
https://github.com/google/guava/blob/7ef9f97cad23efee4cc18c63b5f3c90ca320f131/guava/src/com/google/common/collect/Maps.java#L148-L152

File: core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java [hunk 9]
```diff
@@ -0,0 +1,61 @@
...
+        transientServiceActions.put(requireNonNull(actionType, "actionType"), enable);
+        return this;
+    }
+
+    /**
+     * Returns a newly-created {@link PrometheusExpositionService} based on the properties of this builder.
+     */
+    public PrometheusExpositionService build() {
+        return new PrometheusExpositionService(collectorRegistry,
+                                               Maps.newEnumMap(ImmutableMap.copyOf(transientServiceActions)));
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java:59]: Ditto

File: core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java (hunk 7 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java:279]: This is only used for the builder. It doesn't create many objects. You can ignore this review. :-)

**Review by ikhoon — APPROVED** [review]
Thanks! @minwoox  👍

File: core/src/main/java/com/linecorp/armeria/server/TransientService.java [hunk 10]
```diff
@@ -27,4 +30,41 @@
...
+        return false;
+    }
+
+    /**
+     * The type of actions that is used in {@link TransientService#countFor(ActionType)}.
+     */
+    enum ActionType {
+
+        /**
+         * Whether Graceful shutdown counts the requests to the {@link TransientService} as processing requests.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/TransientService.java:47]: G -> g

File: core/src/main/java/com/linecorp/armeria/server/TransientService.java [hunk 11]
```diff
@@ -27,4 +30,41 @@
  */
 @FunctionalInterface
 public interface TransientService<I extends Request, O extends Response> extends Service<I, O> {
+
+    /**
+     * Tells whether the specified {@link ActionType} is enabled for this {@link TransientService}.
+     */
+    default boolean countFor(ActionType type) {
+        return false;
+    }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/TransientService.java:39]: Should this be dynamic or static? If static, I guess we can just have this:

```java
default Set<ActionType> countedActionTypes() {
    return ALL_ACTION_TYPES;
}
```

.. and expose it in `ServiceConfig` for faster retrieval, because it will be queried very often.

File: core/src/main/java/com/linecorp/armeria/internal/server/TransientServiceUtil.java [hunk 12]
```diff
@@ -0,0 +1,60 @@
...
+import com.linecorp.armeria.server.TransientService;
+import com.linecorp.armeria.server.TransientService.ActionType;
+
+public final class TransientServiceUtil {
+
+    private static final EnumMap<ActionType, Boolean> defaultTransientServiceActions =
+            Maps.newEnumMap(ImmutableMap.of(GRACEFUL_SHUTDOWN, false,
+                                            METRIC_COLLECTION, false,
+                                            LOGGING, false,
+                                            ACCESS_LOGGING, false));
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/TransientServiceUtil.java:39]: - Could use an immutable `EnumSet` and `EnumSet.contains()`? It's O(1) anyways.
- `Flags`?

**Review by trustin — COMMENTED** [review]
Could we also have `TransientServiceBuilder` interface where all builders of `TransientService`s can implement?

File: core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java (hunk 4 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java:266]: How about this:

- If `transientServiceActions()` is not invoked at all, use the default settings.
- If invoked at least once, use the specified ones.

**Comment by minwoox** [comment]
@trustin All fixed. 😉 
I made `TransientServiceBuilder` as an interface, but just let me know if you think making it as a class is more appropriate.

File: core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java [hunk 13]
```diff
@@ -250,13 +258,34 @@ public HealthCheckServiceBuilder updatable(HealthCheckUpdateHandler updateHandle
...
+    public HealthCheckServiceBuilder optOutFeatures(OptOutFeature... optOutFeatures) {
+        return optOutFeatures(ImmutableSet.copyOf(requireNonNull(optOutFeatures, "optOutFeatures")));
+    }
+
+    @Override
+    public HealthCheckServiceBuilder optOutFeatures(Iterable<OptOutFeature> optOutFeatures) {
+        if (this.optOutFeatures == null) {
+            this.optOutFeatures = EnumSet.noneOf(OptOutFeature.class);
+        }
+        this.optOutFeatures.addAll(ImmutableSet.copyOf(optOutFeatures));
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java:271]: requireNonNull?

File: core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java [hunk 14]
```diff
@@ -0,0 +1,75 @@
...
+        return optOutFeatures(ImmutableSet.copyOf(requireNonNull(optOutFeatures, "optOutFeatures")));
+    }
+
+    @Override
+    public PrometheusExpositionServiceBuilder optOutFeatures(Iterable<OptOutFeature> optOutFeatures) {
+        requireNonNull(optOutFeatures, "optOutFeatures");
+        if (this.optOutFeatures == null) {
+            this.optOutFeatures = EnumSet.noneOf(OptOutFeature.class);
+        }
+        this.optOutFeatures.addAll(ImmutableSet.copyOf(optOutFeatures));
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java:58]: requireNonNull?

**Review by ikhoon — APPROVED** [review]
Still LGTM

File: core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java (hunk 13 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java]: Oops thanks fixed. 😉

File: core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java [hunk 15]
```diff
@@ -0,0 +1,50 @@
...
+ * under the License.
+ */
+package com.linecorp.armeria.server;
+
+import com.linecorp.armeria.server.logging.AccessLogWriter;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.server.metric.MetricCollectingService;
+
+/**
+ * The opt-out features that are disabled for a {@link TransientService}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java:23]: How about:

    Specifies which feature should be disabled for a {@link TransientService}.

..?

Could we also add a simple example that involves a builder?

File: core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java [hunk 16]
```diff
@@ -0,0 +1,50 @@
...
+ */
+public enum OptOutFeature {
+
+    /**
+     * Whether graceful shutdown counts the requests to the {@link TransientService} as processing requests.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java:28]: For all enum values: The Javadoc needs an update. For example:

    Prevents a {@link Server} from counting the requests to ...

File: core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java [hunk 17]
```diff
@@ -230,6 +248,13 @@ public boolean shutdownAccessLogWriterOnStop() {
         return shutdownAccessLogWriterOnStop;
     }
 
+    /**
+     * Returns the {@link Set} of {@link OptOutFeature}s that are disabled for the {@link #service()}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java:252]: Could we also add:

    This method always returns an empty {@link Set} for a non-{@link TransientService},
    because only a {@link TransientService} can opt out from {@link OptOutFeature}s.

File: core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java [hunk 18]
```diff
@@ -0,0 +1,75 @@
...
+    /**
+     * Returns a newly-created {@link PrometheusExpositionService} based on the properties of this builder.
+     */
+    public PrometheusExpositionService build() {
+        final Set<OptOutFeature> optOutFeatures;
+        if (this.optOutFeatures == null) {
+            optOutFeatures = Flags.optOutFeatures();
+        } else {
+            optOutFeatures = ImmutableSet.copyOf(this.optOutFeatures);
+        }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java:71]: Could we deduplicate this, perhaps extracting to an internal utility?

e.g.

```java
public final class MyBuilder implements TransientServiceBuilder {
    private final OptOutFeaturesBuilder optOutFeaturesBuilder = new OptOutFeaturesBuilder();

    public MyBuilder optOutFeatures(...) {
        optOutFeaturesBuilder.add(...);
        return this;
    }

    public MySomething build() {
        Set<OptOutFeature> optOutFeatures = optOutFeaturesBuilder.build();
        ...
    }
}
```

**Comment by minwoox** [comment]
@trustin All fixed. PTAL 🙇

File: core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java [hunk 19]
```diff
@@ -20,30 +20,41 @@
...
+ * For example, if you do:
+ * <pre>{@code
+ * ServerBuilder sb = Server.builder();
+ * sb.service("/health", HealthCheckService.builder() // A TransientService
+ *                                         .optOutFeatures(OptOutFeature.GRACEFUL_SHUTDOWN,
+ *                                                         OptOutFeature.ACCESS_LOGGING,
+ *                                                         OptOutFeature.METRIC_COLLECTION)
+ *                                         .build());
+ * }</pre>
+ * then, every feature is opted out except logging from {@link LoggingService}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java:33]: HealthCheckService or LoggingService? 😆

File: core/src/main/java/com/linecorp/armeria/internal/server/OptOutFeaturesBuilder.java [hunk 20]
```diff
@@ -0,0 +1,63 @@
...
+            this.optOutFeatures = EnumSet.noneOf(OptOutFeature.class);
+        }
+        this.optOutFeatures.addAll(ImmutableSet.copyOf(requireNonNull(optOutFeatures, "optOutFeatures")));
+        return this;
+    }
+
+    /**
+     * Returns the {@link Set} of {@link OptOutFeature}s set so far. {@link Flags#optOutFeatures()} if not set.
+     */
+    public Set<OptOutFeature> optOutFeatures() {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/OptOutFeaturesBuilder.java:57]: Maybe just `build()`?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/server/OptOutFeaturesBuilder.java:57]: That's a good idea. 👍

File: core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java (hunk 19 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/OptOutFeature.java]: Fixed. 😆

File: core/src/main/java/com/linecorp/armeria/internal/server/TransientServiceOptionsBuilder.java [hunk 21]
```diff
@@ -0,0 +1,68 @@
...
+    }
+
+    @Override
+    public TransientServiceOptionsBuilder transientServiceOptions(
+            Iterable<TransientServiceOption> transientServiceOptions) {
+        if (this.transientServiceOptions == null) {
+            this.transientServiceOptions = EnumSet.noneOf(TransientServiceOption.class);
+        }
+        this.transientServiceOptions.addAll(
+                ImmutableSet.copyOf(requireNonNull(transientServiceOptions, "transientServiceOptions")));
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/TransientServiceOptionsBuilder.java:54]:
```suggestion
        requireNonNull(transientServiceOptions, "transientServiceOptions");
        if (this.transientServiceOptions == null) {
            this.transientServiceOptions = EnumSet.noneOf(TransientServiceOption.class);
        }
        transientServiceOptions.forEach(this.transientServiceOptions::add);
```

File: core/src/main/java/com/linecorp/armeria/common/Flags.java [hunk 22]
```diff
@@ -372,6 +377,18 @@
...
+            Streams.stream(CSV_SPLITTER.split(getNormalized("transientServiceOptions", "", val -> {
+                try {
+                    Streams.stream(CSV_SPLITTER.split(val))
+                           .forEach(feature -> TransientServiceOption.valueOf(Ascii.toUpperCase(feature)));
+                    return true;
+                } catch (Exception e) {
+                    return false;
+                }
+            }))).map(feature -> TransientServiceOption.valueOf(Ascii.toUpperCase(feature)))
+                   .collect(toImmutableSet());
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/Flags.java:390]: Could we make this an immutable enum set? Otherwise, `TransientServiceOptionsBuilder.build()` will sometimes return an immutable enum set and sometimes not.

File: core/src/main/java/com/linecorp/armeria/server/TransientServiceOption.java [hunk 23]
```diff
@@ -0,0 +1,70 @@
...
+     */
+    WITH_LOGGING,
+
+    /**
+     * Enables {@link AccessLogWriter} to produce the access logs of the requests to the
+     * {@link TransientService}.
+     */
+    WITH_ACCESS_LOGGING;
+
+    private static final Set<TransientServiceOption> allOf = ImmutableSet.of(WITH_METRIC_COLLECTION,
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/TransientServiceOption.java:60]: Ditto - use an immutable enum set.

File: core/src/main/java/com/linecorp/armeria/common/Flags.java (hunk 22 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/Flags.java]: That's a good suggestion. Fixed 😉

File: core/src/main/java/com/linecorp/armeria/server/TransientService.java [hunk 24]
```diff
@@ -27,4 +30,15 @@
...
 public interface TransientService<I extends Request, O extends Response> extends Service<I, O> {
+
+    /**
+     * Returns the {@link Set} of {@link TransientServiceOption}s that are enabled for this
+     * {@link TransientService}. This returns {@link Flags#transientServiceOptions()} if you didn't
+     * specify any {@link TransientServiceOption}s using
+     * {@link TransientServiceBuilder#transientServiceOptions(TransientServiceOption...)} when you create
+     * this {@link TransientService}.
+     */
+    default Set<TransientServiceOption> options() {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/TransientService.java:41]: Should we rename this to `transientServiceOptions()`, just in case a user wants to use the method name `option`, since it's fairly generic?

File: core/src/main/java/com/linecorp/armeria/server/TransientServiceOption.java [hunk 25]
```diff
@@ -0,0 +1,70 @@
...
+    /**
+     * Enables {@link MetricCollectingService} to collect the metrics of the requests to the
+     * {@link TransientService}.
+     */
+    WITH_METRIC_COLLECTION,
+
+    /**
+     * Enables {@link LoggingService} to log the requests to the {@link TransientService}.
+     */
+    WITH_LOGGING,
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/TransientServiceOption.java:52]: Would `WITH_SERVICE_LOGGING` be better? 🤔

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/TransientServiceOption.java:52]: That's better. 👍

File: core/src/main/java/com/linecorp/armeria/server/TransientService.java (hunk 24 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/TransientService.java:41]: No objection. 👍

**Review by trustin — APPROVED** [review]
Seems like we ended up with better API after a few iterations. Thanks for your patience, @minwoox and thanks for waiting, @m50d.

@minwoox Could you update the PR description?

**Comment by minwoox** [comment]
> @minwoox Could you update the PR description?

Done. 😄
