### PR TITLE
Reduce the search space of AnnotationUtil.getAnnotations() and find()

### LINKED ISSUE #1632: StackOverflowError exception with annotatedService in Kotlin
Hi.
I am using armeria with kotlin lang. When I create an annotatedService a StackOverflowError exception occur in server start-up.
```
class PikaRest {

    @Get("/{id}")
    fun redirect(ctx: ServiceRequestContext, @Param("id") id: String): HttpResponse {

    }

}
```

### LINKED ISSUE #1633: Stack overflow in armeria 0.80 (works in 0.79) with AnnotatedServices in Kotlin
In #1569 the behaviour of annotations was modified to allow for recursive annotations(?). Unfortunately, there is a bug in it causing AnnotatedServices written in Kotlin to stack overflow on server init. The following is a short test
```kotlin
fun startTestWebserver() =
   ServerBuilder()
       .annotatedService("/", MiniServer)
       .apply {
           port(12341, SessionProtocol.HTTP)
       }
       .build()

object MiniServer {
   @Post("/test/{pathParam}")
   @Consumes("application/json")
   fun test(@Param("pathParam") pathParam: String?, doodle: String) = HttpResponse.of(HttpStatus.NO_CONTENT)
}
```

In kotlin there are a couple of annotations similar but with extensions to the java annotations explicitly excluded via `BUILT_IN_META_ANNOTATIONS`. Unless there are strong reasons for it, a cache might be better for avoiding stack overflows rather than expanding the black list.

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

There is no cyclic reference detection implemented in `AnnotationUtil`,
which means an annotation like the following can trigger a
`StackOverflowError`:

    @Cyclic
    @Retention(RUNTIME)
    @interface Cyclic {}

This was not a problem before because we blacklisted well known JDK
classes that has cyclic references, but it does not work for other
classes.

Modifications:

- Added cyclic dependency detection in the traversal logic.
- Added a thread-local blacklist of the annotation types with cyclic
  dependencies.

Result:

- Annotation scanning is faster.
- Annotation scanning does not trigger a `StackOverflowException`.
- Fixes #1632
- Fixes #1633

/cc @iEAmi @tobias-

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java [hunk 1]
```diff
@@ -70,11 +77,17 @@
     }
 
     /**
-     * Built-in meta annotations defined in {@code java.lang.annotation} package.
+     * A thread-local hash set of annotation classes that contain cyclic references.
      */
-    private static final Set<Class<? extends Annotation>> BUILT_IN_META_ANNOTATIONS =
-            ImmutableSet.of(Documented.class, Inherited.class, Native.class,
-                            Retention.class, Repeatable.class, Target.class);
+    private static final ThreadLocal<Set<Class<? extends Annotation>>> knownCyclicAnnotationTypes =
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java]: Chose to use a thread-local variable instead of a global one to avoid class loader leak.

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java]: Actually I have to use `WeakHashMap` to avoid class loader leak. Not enough sleep :-)

**Comment by trustin** [comment]
Replaced `IdentityHashMap` with `WeakHashMap` to fix the class loader leak. Will merge once build finishes.

File: core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java (hunk 1 above)
Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java]: Mostly out of curiosity, if using a weak map, do you still need to use threadlocal?

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java]: I thought `WeakHashMap` is not thread safe, no?

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java]: .. or did you mean using a concurrent version of weak key hash map?

Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java]: Yeah was comparing to using synchronizedMap with a weak hash map.

**Comment by tobias-** [comment]
Tested with simple Kotlin class and works.

File: core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java (hunk 1 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java]: Yeah, switched to `MapMaker`.

**Comment by trustin** [comment]
Thanks for reviewing.
