### PR TITLE
Map `FailFastException` to gRPC `Status.UNAVAILABLE`

### LINKED ISSUE #4805: In gRPC client, map `FailFastException` to `Status.UNAVAILABLE`
Currently, `FailFastException` is mapped to `Status.UNKNOWN`. The easiest way to reproduce it is:

```java
GrpcStatus.fromThrowable(t) // `t` is a `FailFastException`. This method returns `Status.UNKNOWN`.
```

### More context:
When the circuit breaker in the gRPC client gets in the "OPEN" state, it starts rejecting requests. When a request is rejected, a `FailFastException` is thrown and this exception is later converted to a `StatusRuntimeException` with `Status.UNKNOWN` in `ArmeriaClientCall` (where `GrpcStatus.fromThrowable` is called on the `FailFastException`).

### Slack discussion
https://line-armeria.slack.com/archives/C1NGPBUH2/p1680558358251399

### Proposal
```java
// `t` is a `FailFastException`. This method returns `Status.UNAVAILABLE`
// instead of `Status.UNKNOWN`.
GrpcStatus.fromThrowable(t)
```

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

`FailFastException` is mapped to `Status.UNKNOWN` while `UnprocessedRequestException` is mapped to `Status.UNAVAILABLE`. https://github.com/line/armeria/blob/4c9dccf996dc062f8f77d7013de504141d9c8306/grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java#L125-L127
Both `FailFastException` and `UnprocessedRequestException` mean that a request did not work on a server, so it would be better to map to the same `Status`.

See #4805 for the detail.

Modifications:

- Fixed `GrpcStatus.fromThrowable()` to convert `FailFastException` to `Status.UNAVAILABLE`

Result:

- `FailFastException` is now correctly converted to `Status.UNAVAILABLE`.
- Fixes #4805

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
👍 👍 👍

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java [hunk 1]
```diff
@@ -122,7 +123,9 @@ private static Status statusFromThrowable(Throwable t) {
         if (t instanceof ClosedStreamException || t instanceof RequestTimeoutException) {
             return Status.CANCELLED.withCause(t);
         }
-        if (t instanceof UnprocessedRequestException || t instanceof IOException) {
+        if (t instanceof UnprocessedRequestException ||
+            t instanceof IOException ||
+            t instanceof FailFastException) {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java:128]: `CallNotPermittedException` raised by the resilience4j module has been converted to `Status.UNAVAILABLE` already because it is wrapped by `UnprocessedRequestException`.
https://github.com/line/armeria/blob/ab7488bafc2912445f026fb6d02420f134937073/resilience4j2/src/main/java/com/linecorp/armeria/resilience4j/circuitbreaker/client/Resilience4JCircuitBreakerClientHandler.java#L115-L118

**Review by jrhee17 — APPROVED** [review]
Thanks for the quick fix @ikhoon 👍 🙇 👍

**Review by trustin — APPROVED** [review]
Thanks, @ikhoon!
