### PR TITLE
Prevent self reference in addSuppressed

### LINKED ISSUE #4749: Http1ObjectEncoder.combine may fail if both futures fail for the same reason
With Armeria 1.22.1, on an unstable connection with many timeouts, I am observing the following issue once in a while

```
java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1064)
	at com.linecorp.armeria.internal.common.Http1ObjectEncoder$1.operationComplete(Http1ObjectEncoder.java:156)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
```

Root cause, which is likely not relevant to this issue, is :
```
Caused by: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:861)
	... 53 common frames omitted
```

I suppose that `addSuppressed` should be skipped if `firstCause == secondCause`

### PR DESCRIPTION
**Pull request by mauhiz**
Motivation:

Prevent an **IllegalArgumentException** from being thrown when the following conditions match
- `Http1VerboseWriteException` is sampled
- Both calls to `Http1ObjectEncoder.write` fail for the same reason (same `Throwable` instance)

Modifications:

- Fix Throwable combination code

Result:

- Closes #4749

### CODE REVIEW

**Comment by mauhiz** [comment]
CI error has nothing to do with me ( `DnsAddressEndpointGroupTest > dnsQueryListener() FAILED` )

**Comment by jrhee17** [comment]
Right, don't worry about it.  Should be fixed with https://github.com/line/armeria/pull/4748

**Review by jrhee17 — APPROVED** [review]
Thanks a lot for finding this 👍 🚀 🙇

File: core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java [hunk 1]
```diff
@@ -145,18 +145,15 @@ public void operationComplete(Future<Void> ignore) throws Exception {
...
-                        } else {
-                            combinedCause.addSuppressed(secondCause);
+                    final Throwable combinedCause;
+                    if (firstCause == null) {
+                        combinedCause = secondCause;
+                    } else {
+                        if (secondCause != null && secondCause != firstCause) {
+                            firstCause.addSuppressed(secondCause);
                         }
+                        combinedCause = firstCause;
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java:155]: Super nit: What do you think of using `==` that might be easier to read?
```java
if (firstCause == null || firstCause == secondCause) {
    combinedCause = secondCause;
} else {
   if (secondCause != null) {
       firstCause.addSuppressed(secondCause);
   }
   combinedCause = firstCause;
}
```

**Review by ikhoon — APPROVED** [review]
Thanks! 🙇‍♂️

File: core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java (hunk 1 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java:155]: Not strong here. The review could be ignored.

Comment (mauhiz) [reply core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java:155]: Then I will ignore :D feel free to make other style changes after this.

**Review by minwoox — APPROVED** [review]
Thanks a lot, @mauhiz!

**Review by trustin — APPROVED** [review]
Thanks for fixing this, @mauhiz! 🙇
