### PR TITLE
Fix a bug where NPE is raised when retrying a gRPC request

### LINKED ISSUE #3248: NPE when retrying RPC requests with armeria-client (suspect race condition around `NonWrappingRequestContext#rpcReq`)
Hi,

We're seeing exceptions like:

````
io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.close(ArmeriaClientCall.java:464)
        at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.transportReportStatus(ArmeriaClientCall.java:416)
        at com.linecorp.armeria.internal.common.grpc.TransportStatusListener.transportReportStatus(TransportStatusListener.java:28)
        at com.linecorp.armeria.internal.common.grpc.HttpStreamDeframerHandler.processOnError(HttpStreamDeframerHandler.java:124)
        at com.linecorp.armeria.common.stream.DefaultHttpDeframer.onError0(DefaultHttpDeframer.java:281)
        at com.linecorp.armeria.common.stream.DefaultHttpDeframer.onError(DefaultHttpDeframer.java:272)
        at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onError(DeferredStreamMessage.java:346)
        at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:281)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:264)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:256)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:436)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:368)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:239)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:224)
        at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:224)
        at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onSubscribe(DeferredStreamMessage.java:334)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:139)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$subscribe$0(DefaultStreamMessage.java:129)
        at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:502)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: rpcReq
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at com.linecorp.armeria.client.DefaultClientRequestContext.<init>(DefaultClientRequestContext.java:361)
        at com.linecorp.armeria.client.DefaultClientRequestContext.newDerivedContext(DefaultClientRequestContext.java:410)
        at com.linecorp.armeria.client.retry.AbstractRetryingClient.newDerivedContext(AbstractRetryingClient.java:268)
        at com.linecorp.armeria.client.retry.RetryingClient.doExecute0(RetryingClient.java:282)
        at com.linecorp.armeria.client.retry.RetryingClient.doExecute(RetryingClient.java:241)
        at com.linecorp.armeria.client.retry.RetryingClient.doExecute(RetryingClient.java:56)
        at com.linecorp.armeria.client.retry.AbstractRetryingClient.execute(AbstractRetryingClient.java:96)
        at com.linecorp.armeria.client.limit.AbstractConcurrencyLimitingClient$PendingTask.run(AbstractConcurrencyLimitingClient.java:237)
        at com.linecorp.armeria.client.limit.AbstractConcurrencyLimitingClient.drain(AbstractConcurrencyLimitingClient.java:184)
        at com.linecorp.armeria.client.limit.AbstractConcurrencyLimitingClient$PendingTask.lambda$run$0(AbstractConcurrencyLimitingClient.java:240)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        ... 7 common frames omitted
````

`RetryingClient#doExecute0` passes `ctx.rpcRequest()` to `newDerivedContext`, so I think this can only happen if `ctx.rpcReq` is `null` on this line but then becomes non-null when the constructor of `DefaultClientRequestContext` is executed. However that does seem entirely possible: `rpcReq` is `volatile` and `DefaultRequestLog#requestContent` calls `ctx.updateRpcRequest` if `ctx.rpcRequest()` is `null`. `DefaultRequestLog#requestContent` is called from several places; while I don't have a specific scenario for why it would be called at the same time as `AbstractRetryingClient#execute`, there doesn't seem to be any synchronisation is place to prevent that.

Under what circumstances is it permitted for `ctx.rpcReq` to change from `null` to non-`null`, and does `newDerivedContext` handle all of those cases correctly? Or is there some other reason for this exception?

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
When creating a derived context, we check whether the `RpcRequest` is `null` or not
if `ctx.rpcRequest()` is not `null` in the consturctor of `DefaultClientRequestContext`.
```
private DefaultClientRequestContext(...) {
    if (ctx.rpcRequest() != null) {
        assert rpcRequest != null;
    }
    ...
}
```
However, the assertion can be false.
The `rpcRequest` of the derived context is set later after the derived context is created so we don't know the timing.
Also, we call:
```java
ctx.logBuilder().defer(RequestLogProperty.REQUEST_CONTENT,
                       RequestLogProperty.RESPONSE_CONTENT);
```
that guarantees the `rpcRequest` of the derived context is set later when the request content of the parent context is set.
So we can completely remove the assertion.

Modification:
- Remove the assertion in `DefaultClientRequestContext`.

Result:
- Close #3248
- You will no longer see NPE when retrying a gRPC request.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java [hunk 1]
```diff
@@ -276,45 +276,39 @@ protected static ClientRequestContext newDerivedContext(ClientRequestContext ctx
...
         final RequestLogBuilder parentLogBuilder = ctx.logBuilder();
         if (parentLogBuilder.isDeferred(RequestLogProperty.REQUEST_CONTENT)) {
             logBuilder.defer(RequestLogProperty.REQUEST_CONTENT);
         }
-        parentLog.whenAvailable(RequestLogProperty.REQUEST_CONTENT).thenApply(requestLog -> {
-            logBuilder.requestContent(requestLog.requestContent(), requestLog.rawRequestContent());
-            return null;
-        });
+        parentLog.whenAvailable(RequestLogProperty.REQUEST_CONTENT)
+                 .thenAccept(requestLog -> logBuilder.requestContent(
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java:291]: These just changed to use `thenAccept` instead of `thenApply`.

File: core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java [hunk 2]
```diff
@@ -908,11 +909,10 @@ public void requestContent(@Nullable Object requestContent, @Nullable Object raw
 
         this.requestContent = requestContent;
         this.rawRequestContent = rawRequestContent;
-        updateFlags(RequestLogProperty.REQUEST_CONTENT);
-
         if (requestContent instanceof RpcRequest && ctx.rpcRequest() == null) {
             ctx.updateRpcRequest((RpcRequest) requestContent);
         }
+        updateFlags(RequestLogProperty.REQUEST_CONTENT);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:915]: This is not a bug.
But it does not break anything and I think it's better to call after calling `updateRpcRequest `.

File: core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java [hunk 3]
```diff
@@ -276,45 +276,39 @@ protected static ClientRequestContext newDerivedContext(ClientRequestContext ctx
...
-            if (name != null) {
-                if (serviceName != null) {
-                    logBuilder.name(serviceName, name);
-                } else {
-                    logBuilder.name(name);
-                }
+            if (serviceName != null) {
+                logBuilder.name(serviceName, name);
+            } else {
+                logBuilder.name(name);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java:282]: 👍

**Review by ikhoon — COMMENTED** [review]
Question: The error stacktrace in #3248 shows the new derived context created at
https://github.com/line/armeria/blob/1a118f64d7968357c20c07029631504b30f1bc86/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L282-L283

Does it make sense to change `ctx.rpcRequest` by other threads while creating a new derived context?

**Comment by minwoox** [comment]
> Does it make sense to change ctx.rpcRequest by other threads while creating a new derived context?

rpcRequest can be set by other threads. 😄 
https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java#L168

**Comment by ikhoon** [comment]
> > Does it make sense to change ctx.rpcRequest by other threads while creating a new derived context?
> 
> rpcRequest can be set by other threads. 😄
> [https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java#L168](https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java?rgh-link-date=2020-12-29T05%3A14%3A59Z#L168)

I got it. 👍 `newDerivedContext` could be executed by a user thread for the first time. I missed that point.

**Review by ikhoon — APPROVED** [review]
Thanks! @minwoox

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java [hunk 4]
```diff
@@ -357,9 +357,6 @@ private DefaultClientRequestContext(DefaultClientRequestContext ctx,
         if (ctx.request() != null) {
             requireNonNull(req, "req");
         }
-        if (ctx.rpcRequest() != null) {
-            requireNonNull(rpcReq, "rpcReq");
-        }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:362]: How about adding some comment about why we don't check nullness of `rpcReq` here unlike `req`?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:362]: Added. 😄

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:362]: And please add a link to the related github issue and PR? 😉

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:362]: Added again. 😄

**Review by trustin — APPROVED** [review]
Thanks, @minwoox !
