### PR TITLE
Make MultipartDecoder/MimeParser can request just right data from upstream

### LINKED ISSUE #3774: Make BodyPart can be requested on demand without loading whole bodypart into queue
In https://gist.github.com/kojilin/575fdeb752a22e6d6a328c5ce545d4a1, it doesn’t work, because https://gist.github.com/kojilin/575fdeb752a22e6d6a328c5ce545d4a1#file-multipartcollector-java-L45 trigger the first bodypart. And DecodedHttpStreamMessage will stop request upstream HttpData, because it thinks the downstream just need 1 bodypart. So it will stop without request/onNext anymore.

So even I subscribe the body part and request 1 `HttpData`, it’s just request the queue in memory of DefaultStreamMessage. What I want is keep reading DecodedHttpStreamMessage’s upstream, but not request next bodypart directly. IIUC, the code works like below now?

1. subscribe `StreamMessage<BodyPart>` and call `request(1)` on subscription.
2. After request 1 bodypart, `MimeParser` and `MultipartDecoder` will continue request until add `BodyPart` to queue. see https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java#L233-L237 
3. The subscriber of BodyPart call `request(1)` on subscription. And it won't trigger the askUpstreamForElement of DecodedHttpStreamMessage but just request data from`DefaultStreamMessage` made at https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java#L233.
4. Stream of DecodedHttpStreamMessage stuck.

If I want to force my code working, I need to do multipartSubscription.request(Long.MAX_VALUE);  to make it just keeping reading all bodypart items. 

Not sure how to modify `DecodedHttpStreamMessage` & `MimeParser` yet. But looks like we may need to modify `DefaultStreamMessage` at https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java#L233 to make requesting of `DefaultStreamMessage` can trigger `DecodedHttpStreamMessage` requesting upstream and let it send more data to `MimeParser` and add data to queue at https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java#L251 ?

### PR DESCRIPTION
**Pull request by kojilin**
Motivation:

Original idea is implementing #3578, but found that I can't request the file one by one(request next file after saving one file). So creating the issue #3774 and want to fix it.

Modifications:

- Make MultipartDecoder can control the demand of BodyPart. 
- Make MimeParser can check and request more HttpData when it needs more body
- Add integration test for testing Multipart/BodyPart with request limit control. Now `MultipartCollector` is in the test package. Move it to production code for #3578 in the future.

Result:
- Closes #3774

### CODE REVIEW

**Comment by kojilin** [comment]
Create this PR for sync the idea. Because I wanna confirm if the change is what everyone expect ^^.

File: it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+    }
+
+    public CompletableFuture<CustomAggregatedMultipart> future() {
+        return future;
+    }
+
+    @Override
+    public void onSubscribe(Subscription s) {
+        multipartSubscription = s;
+        eventLoop = RequestContext.mapCurrent(RequestContext::eventLoop,
```
Comment (kojilin) [inline it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java:167]: Curious if we can guarantee that `onSubscribe` runs with `RequestContext`? I used `eventLoop` to guarantee all the callback of nested `BodyPart` subscribe can run on the same thread.

File: it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java [hunk 2]
```diff
@@ -0,0 +1,287 @@
...
+        try {
+            final Path path = Files.createTempFile("armeria", "tmp");
+            files.compute(bodyPart.name(), (s, paths) -> {
+                if (paths == null) {
+                    paths = new ArrayList<>();
+                }
+                paths.add(path);
+                return paths;
+            });
+            eventLoop.execute(() -> {
```
Comment (kojilin) [inline it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java:226]: Due to `onNext` may not have `RequestContext`. If we just call `subscribe` in  `toPath`, it will use `CommonPools.workerGroup()::next` in `defaultSubscriberExecutor`. So force it use context-awared eventoop.

File: core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java [hunk 3]
```diff
@@ -230,7 +238,15 @@ void parse() {
...
                         startOfLine = true;
 
-                        bodyPartPublisher = new DefaultStreamMessage<>();
+                        bodyPartPublisher = new DefaultStreamMessage<HttpData>() {
+                            @Override
+                            protected void onRequest(long n) {
+                                // Should we limit this to 1? Because downstream can request aggressively
+                                // and ignore the demand number of BodyPart. Or how can we control
+                                // this stop when we meet END_PART.
+                                onBodyPartRequestHttpData.accept(n);
```
Comment (kojilin) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java:247]: Maybe I need to store the `n` and request one by one at `state == BODY` case below.

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/DecodedHttpStreamMessage.java [hunk 4]
```diff
@@ -242,7 +250,11 @@ public void onNext(HttpObject obj) {
                 } else {
                     // Handler didn't produce anything, which means it needs more elements from the upstream
                     // to produce something.
-                    askUpstreamForElement();
+                    if (demand() > 0) {
```
Comment (kojilin) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/DecodedHttpStreamMessage.java:253]: This will make test failed due to other codes may want decoder try to decode until it gets the item. But it means the BodyPart' subscribe will get all the data even we just request 1 `HttpData`. Maybe need help about this part. 🙇

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/DecodedHttpStreamMessage.java:253]: Try to fix this by 
```
diff --git a/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java b/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
index 625fd077f..7f47c7ab9 100644
--- a/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
+++ b/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
@@ -249,8 +249,6 @@ public class DefaultStreamMessage<T> extends AbstractStreamMessageAndWriter<T> {
     }

     private void doRequest(long n) {
-        onRequest(n);
-
         final long oldDemand = demand;
         if (oldDemand >= Long.MAX_VALUE - n) {
             demand = Long.MAX_VALUE;
@@ -258,6 +256,8 @@ public class DefaultStreamMessage<T> extends AbstractStreamMessageAndWriter<T> {
             demand = oldDemand + n;
         }

+        onRequest(n);
+
         if (oldDemand == 0 && !queue.isEmpty()) {
             notifySubscriber0();
         }
```

Because the `onRequest` will cause `onNext` works, and I want it also check the `demand` in implementation. Not sure if it's make sense or not.

File: it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java (hunk 1 above)
Comment (ikhoon) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java:166]: As you did, it is only guaranteed when a context-aware executor is specified.

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/DecodedHttpStreamMessage.java [hunk 5]
```diff
@@ -157,14 +157,22 @@ protected void onRequest(long n) {
         }
     }
 
-    private void askUpstreamForElement() {
+    /**
+     * Directly requests n elements to the {@code streamMessage} that was specified when creating this
+     * {@link StreamMessage}. It is useful when the {@link HttpDecoder} emits another {@link StreamMessage}s.
+     */
+    public void askUpstreamForElements(long n) {
         if (!askedUpstreamForElement) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/DecodedHttpStreamMessage.java:165]: A request for elements might be lost if `askedUpstreamForElement` is true.
How about separately tracking the directly requested number of elements?

For example:
```java
// Should be updated in an event loop
private long directRequest;

public void askUpstreamForElements(long n) {
    // Make sure that this API should be called after subscribing.
    assert executor != null;
    // Update in an event loop which subscribed this stream message.
    directRequest += n;
    // Call the original API.
    askUpstreamForElement();
}

private final class HttpMessageSubscriber implements Subscriber<HttpObject> {

    public void onNext(HttpObject obj) {
        ...
        if (directRequest > 0) {
            directRequest--;
        }
        // If there is a remaining demand, ask upstream for more elements
        if (directRequest > 0) {
            askUpstreamForElement();
            return;
        }
        
        
        if (handlerProduced) {
             // Keep the original code path.
             ...
        }
    }
```

I'm not 100% sure the example code correctly works. But it might be worth to try it. 😄

**Comment by kojilin** [comment]
Let me rethink the approach again. 

The direct request count looks ok, but I'm thinking if the subscriber of BodyPartPublisher call `request(n)` with too large, it will affects original `DecodedHttpStreamMessage` that even we don't need more HttpData, it still request until `direct request count` become zero. 

Maybe what we want is let `DecodedHttpStreamMessage` can ask `MultipartDecoder` if it need more elemetns?

**Comment by trustin** [comment]
@ikhoon Any additional suggestions for @kojilin?

**Comment by ikhoon** [comment]
> The direct request count looks ok, but I'm thinking if the subscriber of BodyPartPublisher call `request(n)` with too large n,

That's true. After thinking of it, my other idea is to leverage `demand()` and `whenConsumed()` for backpressure.
- If a demand is greater than zero in some points, we can request the next element to upstream.
```java
if (boundaryStart == -1 || bodyContent == NEED_MORE) {
    if (bodyContent == NEED_MORE) {
        // Need more data
        if (bodyPartPublisher.demand() > 0) {
            upstream.askUpstreamForElement();
        }
        return;
    }
} else {
    startOfLine = false;
}
final HttpData data = HttpData.wrap(bodyContent);
bodyPartPublisher.write(data);
bodyPartPublisher.whenConsumed().thenRun(() -> {
    if (bodyPartPublisher.demand() > 0) {
        upstream.askUpstreamForElement();
    }
});
```

**Comment by kojilin** [comment]
Follow the suggestion and mix the idea of making `MultipartDecoder` control the upstream.(Always limit 1 request of bodypart. So `DecodedHttpStreamMessage` won't  request next item until inner bodypart subscriber complete.

Still need to add more code, but this change want to show the current idea.
Some concerns:
* Like `testMultipleChunksOfPartsBeforeContent`, need to force inner subscriber using same eventloop. If not we may make MultipartDecoder broken. (Can we force client of inner BodyPart using the same channel?)
* What happened when inner subscriber want to cancel or throw exception. Cancel outer subscription also or just single bodypart.(Achievable?)

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 6]
```diff
@@ -110,4 +121,92 @@ public void abort() {
...
+        subscriber.onError(t);
+    }
+
+    @Override
+    public void onComplete() {
+        assert subscriber != null;
+        subscriber.onComplete();
+    }
+
+    BodyPartPublisher onBodyPartBegin() {
```
Comment (kojilin) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:171]: Any idea of this part. I want to make MultipartDecoder can know BodyPartPublisher and let BodyPartPublisher can call `decoded.askUpstreamForElement();`.

**Comment by kojilin** [comment]
Updated.

* Please ignore `core/src/main/java/com/linecorp/armeria/common/stream/AsyncFileWriter.java` and `core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java`  from https://github.com/line/armeria/pull/3874, I think #3784 will be merged first.
* I created BodyParts, looks like it's good to put to Multiparts? And I think it's hard to put in to `Multipart` or becomming `AggregatedMultipart`.

**Comment by kojilin** [comment]
updated

File: it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+                    subscription.request(1);
+                    if (canComplete) {
+                        doComplete();
+                    }
+                }
+            }, eventExecutor);
+            return;
+        }
+
+        final Path path = mappingFileName.apply(name);
```
[the remark this answers is not in the document]
Comment (kojilin) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/MultipartCollector.java]: I'm thinking just abort the request due to if we use random, we many need to ask user giving default folder where we can put random path, which is redundant for user already provide correct mapping function.

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 8]
```diff
@@ -98,16 +129,242 @@ public long demand() {
...
+            // Already aborted before
+            return;
+        }
+        abortCause = cause;
+        if (subscribedUpdater.compareAndSet(this, 0, -1)) {
+            // There is no subscriber
+            return;
+        }
+        subscribedCompleteFuture.handle((unused, throwable) -> {
+            decoded.abort(cause);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:178]: Can't we just abort `decoded` without using the `subscribedCompleteFuture`?
The subscriber would get `AbortedStreamException` if `decoded.abort(cause);` happens before the subscription which is fine.

File: core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java [hunk 9]
```diff
@@ -168,8 +168,10 @@ protected void subscribe0(EventExecutor executor, SubscriptionOption[] options)
 
     /**
      * Invoked whenever a new demand is requested.
+     * @param newDemand Newly requested demand
+     * @param oldDemand Existing demand before adding newDemand
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java:172]: Is there any reason that you add `oldDemand`? It doesn't seem like used. 🤔

**Review by minwoox — COMMENTED** [review]
Basically looking good. 😄

File: core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java [hunk 10]
```diff
@@ -241,13 +245,22 @@ void parse() {
...
                             }
                         } else {
                             startOfLine = false;
                         }
-                        bodyPartPublisher.write(HttpData.wrap(bodyContent));
+
+                        // Use tryWrite() to avoid throwing exception.
+                        // For example, when body part is cancelled, MimeParser need to ignore it without
+                        // throwing exception.
+                        bodyPartPublisher.tryWrite(HttpData.wrap(bodyContent));
```
[the remark this answers is not in the document]
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java:260]: `tryWrite` will handle the case like body is cancelled.
Due to even body is cancelled, the upstream will still sending the httpdata until next BodyPart starts. So here just ignore it to like we want the data, but just ignore it.

If we make state fails, it will handle whole multipart as failed IIUC.

File: core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java (hunk 9 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java]: right, let me remove it.( I added it when using different way to implement this PR, but looks like I don't need it anymore and if some other implementation in the future need it, we can add it back)

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 11]
```diff
@@ -16,43 +16,69 @@
...
 final class MultipartDecoder implements StreamMessage<BodyPart>, HttpDecoder<BodyPart> {
 
-    private static final Logger logger = LoggerFactory.getLogger(MultipartDecoder.class);
+    private static final AtomicIntegerFieldUpdater<MultipartDecoder>
+            subscribedUpdater = AtomicIntegerFieldUpdater.newUpdater(MultipartDecoder.class, "subscribed");
 
-    private final StreamMessage<BodyPart> decoded;
+    private final DecodedHttpStreamMessage<BodyPart> decoded;
     private final String boundary;
+    private final CompletableFuture<Void> subscribedCompleteFuture = new CompletableFuture<>();
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:52]: I guess we don't need this anymore.

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 12]
```diff
@@ -98,16 +125,239 @@ public long demand() {
...
+
+    final class BodyPartPublisher extends DefaultStreamMessage<HttpData> {
+        @Override
+        protected void onRequest(long n) {
+            // Because whenConsumed will run in the same thread(called by onRequest) after looping the existing
+            // queue.(onRequest & event notification in whenConsumed will run in the same executor specified
+            // at subscribe)
+            // So if there is no change, it means there is no buffered data processed.
+            whenConsumed().thenRun(() -> {
+                // There isn't any buffered data, or it's not enough
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:209]: Question: Is there any chance that we should request more to the upstream?
e.g. The downstream request 1 but the body part was split into 3 frames so we should request 3 to the upstream. 🤔

**Review by minwoox — COMMENTED** [review]
Thanks! I think it's almost done. 😄

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java (hunk 11 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:52]: I see, so DecodedHttpStreamMessage's abort & subscribe are safe to be called in different thread concurrently, right?

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java (hunk 12 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:209]: IIUC, if we mean HttpData of body at MimeParser in that case, downstream should request more by self, because what downstream request is the HttpData and it means subscribe needs request more manually. e..g 1GB file is split in many frames, so downstream control the speed 1 by 1.

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java (hunk 11 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:52]: I think so because the `subscriptionUpdater` in the `decoded` handles it. 😄

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java (hunk 12 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:209]: Thanks for the explanation. 😄

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java (hunk 11 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:52]: Ah I mean if i remove this(also the previous change of after complete), the abort & subscribe may trigger by different thread, so it means DecodedHttpStreamMessage need to handle by self, curious if it's ok to do it. Looks like it's handled correctly, just double confirm.

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 13]
```diff
@@ -98,16 +125,239 @@ public long demand() {
...
     @Override
     public void abort(Throwable cause) {
+        requireNonNull(cause, "cause");
+        if (subscribed == -1) {
+            // Already aborted before
+            return;
+        }
+        abortCause = cause;
+        if (subscribedUpdater.compareAndSet(this, 0, -1)) {
+            // There is no subscriber
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:170]: Shouldn't we still abort `decoded` here?

**Comment by kojilin** [comment]
Updated
* Remove `subscribedCompleteFuture`
* To handle `multiple subscribing` and `abort before subscribing`, create another `AtomicReferenceFieldUpdater` to preserve the Throwable.
  * `multiple subscribing` will have null abortCause, so exception is `new IllegalStateException("subscribed by other subscriber already")`
  * `abort before subscribing` will set `abortCause` before setting subscribed to -1. So subscriber after it will always see abortCause
  * abortCause is set non-null -> subscriber successfully pass compareAndSet check in subscribe -> `subscribed become -1`, it's ok to let subscriber subscribing, because soon it will be aborted through `decoded.abort(abortCause)` 
  * `multiple subscribing` may have chance to see the abortCause when `subscribe1`-> `subscribe2`  -> `abort` . The 2nd one may see the abortCause even it's called earlier than abort.

**Comment by minwoox** [comment]
> create another AtomicReferenceFieldUpdater to preserve the Throwable

Instead of adding a new updater, how about changing the old one to `subscriberUpdater` and using it together?

```java
private static final AtomicReferenceFieldUpdater<MultipartDecoder, MultipartSubscriber> subscriberUpdater =
        AtomicReferenceFieldUpdater.newUpdater(MultipartDecoder.class, MultipartSubscriber.class,
                                               "subscriber");

@Nullable
private volatile MultipartSubscriber subscriber;

...
@Override
public void subscribe(Subscriber<? super BodyPart> subscriber, EventExecutor executor,
                      SubscriptionOption... options) {
    requireNonNull(subscriber, "subscriber");
    requireNonNull(executor, "executor");
    requireNonNull(options, "options");

    final MultipartSubscriber multipartSubscriber = new MultipartSubscriber(subscriber, executor);
    if (!subscriberUpdater.compareAndSet(this, null, multipartSubscriber)) {
        // In failLateSubscriber, the cause is different depending on it's late or aborted.
        failLateSubscriber(multipartSubscriber);
        return;
    }
    ...
}

@Override
public void abort(Throwable cause) {
    requireNonNull(cause, "cause");

    if (subscriber == null) {
        final MultipartSubscriber abortedSubscriber = new MultipartSubscriber(
                AbortingSubscriber.get(cause), EventLoopGroups.directEventLoop());
        subscriberUpdater.compareAndSet(this, null, abortedSubscriber);
    }
    // abort the `decoded` anyway. Only the first abort effects though.
    decoded.abort(abortCause);
}

```

**Comment by kojilin** [comment]
Thanks for suggestion.
I tried to use your idea and think it works.
But a little tricky that I'm using MultipartSubscirber to wrap original Subscriber and I need to be careful that MultipartSubscriber should not doing anything in constructor in the future.

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 14]
```diff
@@ -98,16 +120,236 @@ public long demand() {
...
+        }
+
+        @Override
+        public void onNext(BodyPart bodyPart) {
+            if (demandOfMultipart != Long.MAX_VALUE) {
+                demandOfMultipart--;
+            }
+
+            currentExposedBodyPartPublisher = bodyPart.content();
+            // We only publish one bodyPart one time.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:240]: nit:
```suggestion
            // We only publish one bodyPart at a time.
```
How about just `currentBodyPart`?

File: it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java [hunk 15]
```diff
@@ -0,0 +1,112 @@
...
+     *
+     * @param multipart the source of {@link Multipart} to be processed
+     * @param mappingFileName the {@link Function} that generates a {@link Path} from the name in the part
+     * @param options the {@link OpenOption} specifying how the file is opened
+     * @return a {@link CompletableFuture} that completes with the aggregated {@link CollectedBodyParts} or an
+     *         error
+     *
+     * @see StreamMessages
+     */
+    public static CompletableFuture<CollectedBodyParts> collect(
```
[the remark this answers is not in the document]
Comment (minwoox) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java:86]: Are we going to do this in the follow-up PR?

**Review by minwoox — COMMENTED** [review]
I think it's almost done.
Thanks a lot for your hard work, @kojilin! 😄

File: core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java [hunk 16]
```diff
@@ -239,15 +243,21 @@ void parse() {
...
-                        } else {
+                        if (bodyContent == NEED_MORE) {
+                            final BodyPartPublisher currentPublisher = bodyPartPublisher;
+                            currentPublisher.whenConsumed().thenRun(() -> {
+                                if (currentPublisher.demand() > 0 && !currentPublisher.isComplete()) {
+                                    multipartDecoder.requestUpstreamForBodyPartData();
+                                }
+                            });
+                            return;
+                        } else if (boundaryStart != -1) {
```
[the remark this answers is not in the document]
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java:254]: oops

File: it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (kojilin) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java:86]: Not sure, do u think it's better to add to this PR? this will add new method to existing Multipart and will user confuse the behavior with aggregate?

[the remark this answers is not in the document]
Comment (kojilin) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java:86]: Also the 
```
 public static CompletableFuture<CollectedBodyParts> collect(
            Multipart multipart,
            Function<String, Path> mappingFileName,
            OpenOption... options) {
```
is already write to file or aggregate to memory. But here 
```
interface Multipart {
   CompletableFuture<List<T>> collect(Function<? super BodyPart, CompletableFuture<? extends T>> function);
}
```
is asking user do to by self, right? It means we won't need `ContentAwareMultipartCollector` to do `bodyPart.aggregateWithPooledObjects` and `bodyPart.writeFile` and just delegate onNext to user?

[the remark this answers is not in the document]
Comment (minwoox) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java:86]: So we probably don't need this as a public API. 😄

[the remark this answers is not in the document]
Comment (kojilin) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java:86]: Let me think ^^;;; No strong opinion here yet. Just curious if we add it, it's hard to change. But if we decide to add, I can add in this PR or in next PR.

File: core/src/main/java/com/linecorp/armeria/common/multipart/BodyPart.java [hunk 17]
```diff
@@ -138,6 +147,50 @@ static BodyPartBuilder builder() {
...
+     * {@link StandardOpenOption#TRUNCATE_EXISTING} and {@link StandardOpenOption#WRITE}.
+     *
+     * @param path the {@link Path} to write to
+     * @param eventExecutor the {@link EventExecutor} to subscribe to this given publisher
+     * @param blockingTaskExecutor the {@link ExecutorService} to which blocking tasks are submitted to handle
+     *                             file I/O events and write operations
+     * @param options the {@link OpenOption} specifying how the file is opened
+     * @return a {@link CompletableFuture} to handle asynchronous result
+     */
+    CompletableFuture<Void> writeFile(Path path, EventExecutor eventExecutor,
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/multipart/BodyPart.java:162]: Should this be `writeTo()` or `writeToFile()`?

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 18]
```diff
@@ -69,8 +90,9 @@ public void processOnError(Throwable cause) {
         if (parser != null) {
             try {
                 parser.close();
-            } catch (MimeParsingException ex) {
-                logger.warn(ex.getMessage(), ex);
+            } catch (MimeParsingException ignore) {
+                // There is a cause already happened and passed to subscriber already
+                // So the parsing exception is not important for user and miss leading if we log here.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:95]: How about rephrasing like this:

```suggestion
                // This exception has been passed to the subscriber already and will be handled there,
                // so we shouldn't log it because otherwise it may mislead a user.
```

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java [hunk 19]
```diff
@@ -98,16 +120,213 @@ public long demand() {
...
+        }
+    }
+
+    final class BodyPartPublisher extends DefaultStreamMessage<HttpData> {
+        @Override
+        protected void onRequest(long n) {
+            // Because whenConsumed will run in the same thread(called by onRequest) after looping the existing
+            // queue.(onRequest & event notification in whenConsumed will run in the same executor specified
+            // at subscribe)
+            // So if there is no change, it means there is no buffered data processed.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:171]: I'm not sure I understood the intention of this comment block. Could you elaborate? It'd be even nice if you can rephrase it a little bit.

File: core/src/main/java/com/linecorp/armeria/common/stream/AbortedStreamException.java [hunk 20]
```diff
@@ -28,7 +28,7 @@
 
     private static final long serialVersionUID = -5271590540551141199L;
 
-    static final AbortedStreamException INSTANCE = new AbortedStreamException(false);
+    public static final AbortedStreamException INSTANCE = new AbortedStreamException(false);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/AbortedStreamException.java:31]: We need to hide this from the public API somehow. Maybe using reflection? :joy:

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java [hunk 21]
```diff
@@ -0,0 +1,130 @@
...
+ * A utility class for {@link StreamMessage}.
+ */
+@UnstableApi
+public final class StreamMessages {
+
+    /**
+     * Write the specified {@link  StreamMessage} to the given {@link Path} with {@link OpenOption}.
+     * If the {@link OpenOption} is not specified, defaults to {@link StandardOpenOption#CREATE},
+     * {@link StandardOpenOption#TRUNCATE_EXISTING} and {@link StandardOpenOption#WRITE}.
+     *
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java:48]:
```suggestion
     * Writes the specified {@link StreamMessage} to the given {@link Path} with {@link OpenOption}s.
     * If the {@link OpenOption}s are not specified, they default to {@link StandardOpenOption#CREATE},
     * {@link StandardOpenOption#TRUNCATE_EXISTING} and {@link StandardOpenOption#WRITE}.
     *
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java [hunk 22]
```diff
@@ -0,0 +1,130 @@
...
+     * @param publisher the source of {@link HttpData} to be written
+     * @param destination the {@link Path} to write to
+     * @param options the {@link OpenOption} specifying how the file is opened
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java:51]:
```suggestion
     * @param options the {@link OpenOption}s specifying how the file is opened
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java [hunk 23]
```diff
@@ -0,0 +1,130 @@
...
+ */
+@UnstableApi
+public final class StreamMessages {
+
+    /**
+     * Write the specified {@link  StreamMessage} to the given {@link Path} with {@link OpenOption}.
+     * If the {@link OpenOption} is not specified, defaults to {@link StandardOpenOption#CREATE},
+     * {@link StandardOpenOption#TRUNCATE_EXISTING} and {@link StandardOpenOption#WRITE}.
+     *
+     * @param publisher the source of {@link HttpData} to be written
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java:49]:
```suggestion
     * @param publisher the source of {@link HttpData} to be read from
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java [hunk 24]
```diff
@@ -0,0 +1,130 @@
...
+            blockingTaskExecutor = CommonPools.blockingTaskExecutor();
+        }
+
+        return writeTo(publisher, destination, eventExecutor, blockingTaskExecutor, options);
+    }
+
+    /**
+     * Write the specified {@link  StreamMessage} to the given {@link Path} with {@link OpenOption}.
+     * If the {@link OpenOption} is not specified, defaults to {@link StandardOpenOption#CREATE},
+     * {@link StandardOpenOption#TRUNCATE_EXISTING} and {@link StandardOpenOption#WRITE}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java:82]:
```suggestion
     * Writes the specified {@link StreamMessage} to the given {@link Path} with {@link OpenOption}s.
     * If the {@link OpenOption}s are not specified, they default to {@link StandardOpenOption#CREATE},
     * {@link StandardOpenOption#TRUNCATE_EXISTING} and {@link StandardOpenOption#WRITE}.
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java [hunk 25]
```diff
@@ -0,0 +1,130 @@
...
+     *
+     * @param publisher the source of {@link HttpData} to be written
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java:84]:
```suggestion
     * @param publisher the source of {@link HttpData} to be read from
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java [hunk 26]
```diff
@@ -0,0 +1,130 @@
...
+     * @param destination the {@link Path} to write to
+     * @param eventExecutor the {@link EventExecutor} to subscribe to the given publisher
+     * @param blockingTaskExecutor the {@link ExecutorService} to which blocking tasks are submitted to handle
+     *                             file I/O events and write operations
+     * @param options the {@link OpenOption} specifying how the file is opened
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessages.java:89]:
```suggestion
     * @param options the {@link OpenOption}s specifying how the file is opened
```

**Review by trustin — COMMENTED** [review]
Minor comments only. Great job, @kojilin :bow:

**Comment by trustin** [comment]
@kojilin, sorry but could you resolve the conflicts?

File: core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java (hunk 19 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java:171]: Let me recheck my comment here

**Comment by kojilin** [comment]
updated. Except 1 comment not resolve yet.

And I will recheck the logic and move BodyParts and ContentAwareMultipartCollector to main.

File: it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (trustin) [reply it/multipart/src/test/java/com/linecorp/armeria/common/multipart/BodyParts.java:86]: I think it will still be useful to add `Multipart.collect(): CompletableFuture` for users who want to write a test case that consumes `Multipart`, just like we have `HttpRequest.collect()`. Please feel free to refactor in this or follow-up PR. :bow:

**Review by trustin — COMMENTED** [review]
Thanks @kojilin for updating this PR. I believe we're getting close!

> I will recheck the logic and move BodyParts and ContentAwareMultipartCollector to main. Do you think it's good to move to public API in this PR?

Left a comment on this [here](https://github.com/line/armeria/pull/3783#discussion_r782000067).

**Comment by kojilin** [comment]
* Create collect method in Multipart
* Move tests related to collect method

File: core/src/main/java/com/linecorp/armeria/common/multipart/Multipart.java [hunk 27]
```diff
@@ -361,4 +367,45 @@ static Multipart from(String boundary, Publisher<? extends HttpData> contents, B
...
+    /**
+     * Collects the elements published by this {@link Multipart}.
+     * The returned {@link CompletableFuture} will be notified when the elements are fully consumed.
+     *
+     * <p>Note that if this {@link Multipart} was subscribed by other {@link Subscriber} already,
+     * the returned {@link CompletableFuture} will be completed with an {@link IllegalStateException}.
+     */
+    @UnstableApi
+    <T> CompletableFuture<List<T>> collect(Function<? super BodyPart, CompletableFuture<? extends T>> function,
+                                           SubscriptionOption... options);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/multipart/Multipart.java:410]: Recently, thanks to @sleeplesslord, `StreamMessage.mapAsync()` that was added which might be perfect for this. #3962

```suggestion
    default <T> CompletableFuture<List<T>> collect(Function<? super BodyPart, CompletableFuture<? extends T>> function,
                                           SubscriptionOption... options) {
        return bodyParts().mapAsync(function).collect(options);                                
   }
```

**Review by trustin — APPROVED** [review]
Very nice, @kojilin :bow:

**Comment by ikhoon** [comment]
Thanks for your patience! 🙇‍♂️ It was a non-trival problem. I will wait for your next PR about multipart for annotated services. 🥰
