### PR TITLE
Address `maxConcurrentStreams` violation on write timeout

### LINKED ISSUE #3858: Received a `Maximum active streams violated for this endpoint.` from client side
armeria version: 1.8.0
verified client-side isn't changing `MAX_CONCURRENT_STREAMS`

```
 java.util.concurrent.CompletionException: com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.linecorp.armeria.internal.common.HttpObjectAggregator.fail(HttpObjectAggregator.java:145)
	at com.linecorp.armeria.internal.common.HttpObjectAggregator.onError(HttpObjectAggregator.java:61)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onError(DeferredStreamMessage.java:347)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:276)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:284)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:276)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:448)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:391)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:259)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:242)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:218)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onSubscribe(DeferredStreamMessage.java:335)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:147)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:130)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.safeOnSubscribeToUpstream(DeferredStreamMessage.java:282)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.delegate(DeferredStreamMessage.java:121)
	at com.linecorp.armeria.common.DeferredHttpResponse.delegate(DeferredHttpResponse.java:48)
	at com.linecorp.armeria.common.DeferredHttpResponse.lambda$delegateWhenComplete$0(DeferredHttpResponse.java:59)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleBackoff$9(RetryingClient.java:398)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:143)
	at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleResponse$6(RetryingClient.java:352)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at com.linecorp.armeria.client.retry.RetryingClient.handleResponse(RetryingClient.java:312)
	at com.linecorp.armeria.client.retry.RetryingClient.doExecute0(RetryingClient.java:297)
	at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleBackoff$8(RetryingClient.java:392)
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:546)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
	at com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45)
	at com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:134)
	at com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:54)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:205)
	at com.linecorp.armeria.client.HttpRequestSubscriber.onSubscribe(HttpRequestSubscriber.java:181)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$DownstreamSubscription.invokeOnSubscribe0(DefaultStreamMessageDuplicator.java:672)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$DownstreamSubscription.invokeOnSubscribe(DefaultStreamMessageDuplicator.java:663)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$StreamMessageProcessor.doSubscribe(DefaultStreamMessageDuplicator.java:292)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$StreamMessageProcessor.subscribe(DefaultStreamMessageDuplicator.java:272)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$ChildStreamMessage.subscribe0(DefaultStreamMessageDuplicator.java:537)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$ChildStreamMessage.subscribe(DefaultStreamMessageDuplicator.java:525)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$ChildStreamMessage.subscribe(DefaultStreamMessageDuplicator.java:515)
	at com.linecorp.armeria.common.stream.StreamMessageWrapper.subscribe(StreamMessageWrapper.java:80)
	at com.linecorp.armeria.client.HttpSessionHandler.invoke(HttpSessionHandler.java:203)
	at com.linecorp.armeria.client.HttpClientDelegate.doExecute(HttpClientDelegate.java:276)
	at com.linecorp.armeria.client.HttpClientDelegate.acquireConnectionAndExecute(HttpClientDelegate.java:162)
	at com.linecorp.armeria.client.HttpClientDelegate.finishResolve(HttpClientDelegate.java:123)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:106)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:51)
	at com.linecorp.armeria.client.metric.AbstractMetricCollectingClient.execute(AbstractMetricCollectingClient.java:62)
	at com.linecorp.armeria.internal.client.ClientUtil.pushAndExecute(ClientUtil.java:150)
	at com.linecorp.armeria.internal.client.ClientUtil.executeWithFallback(ClientUtil.java:138)
	at com.linecorp.armeria.client.retry.RetryingClient.doExecute0(RetryingClient.java:286)
	... 11 common frames omitted
Caused by: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:152)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:896)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:748)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:668)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:201)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:151)
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:45)
	at com.linecorp.armeria.client.ClientHttp2ObjectEncoder.doWriteHeaders(ClientHttp2ObjectEncoder.java:73)
	at com.linecorp.armeria.client.ClientHttpObjectEncoder.writeHeaders(ClientHttpObjectEncoder.java:41)
	at com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:204)
	... 30 common frames omitted
```

### PR DESCRIPTION
**Pull request by jrhee17**
**Background**

Currently, armeria maintains a state `HttpResponseDecoder#unfinishedResponses` to check how many in-flight requests are being processed for a connection.

Armeria uses this value to check if all connections occupy too many concurrent streams, and creates a new connection if necessary.

On the other hand, netty maintains it's own state to check how many in-flight requests are being processed for a connection. (`DefaultHttp2Connection.DefaultEndpoint#numActiveStreams`)

Netty checks this value before creating a stream, and throws a `Http2Exception$StreamException` if `MAX_CONCURRENT_STREAMS` is unavailable.

**Problem Statement**

Currently, when a `WriteTimeoutException` is triggered, armeria decrements `unfinishedResponses` and removes the response. (A `WriteTimeoutException` is thrown when a request header isn't written within a predefined `writeTimeoutMillis`)
However, netty may not be aware that armeria has failed the response. Consequently, netty's `numActiveStreams` is greater than armeria's `unfinishedResponses`. This may cause a violation of `MAX_CONCURRENT_STREAMS` for additional requests on the connection.

**Motivation**
Netty always calls `Http2ResponseDecoder.onStreamClosed` before decrementing `numActiveStreams`.
If we want `numActiveStreams` to be in sync with `unfinishedResponses`, I propose that we modify the timing of decrementing `unfinishedResponses` to `Http2ResponseDecoder.onStreamClosed`.

In detail, when a `WriteTimeoutException` is scheduled

https://github.com/line/armeria/blob/117a21e17ec9e30b0c3c2d74d16fdde3cab62434/core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java#L171-L173

the response is closed.

https://github.com/line/armeria/blob/117a21e17ec9e30b0c3c2d74d16fdde3cab62434/core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java#L318

Consequently, after the stream processes the `close` event, `whenComplete` is triggered.

https://github.com/line/armeria/blob/117a21e17ec9e30b0c3c2d74d16fdde3cab62434/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L83-L90

And the response is removed (and `unfinishedResponses` is decremented)

https://github.com/line/armeria/blob/117a21e17ec9e30b0c3c2d74d16fdde3cab62434/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L101

However, as far as netty is concerned, the request may have been written and may still be processing.

**Misc**

Reproduced `maxConcurrentStreams` when `WriteTimeoutException` occurs at 225a684d88b67267ae44e5e65644abaaaa15d841

**Modifications**

- Remove the `removeResponse` call from `Http2ResponseDecoder. onWrapperCompleted`, and rely on `onStreamClosed` to remove the response/decrement `unfinishedResponses`
- When receiving callbacks for `onHeadersRead`, `onDataRead`, `onRstStreamRead`, also check if `resWrapper` had been closed. This preserves behavior since `res` was previously removed on `WriteTimeoutException`, resulting in `res == null`.

*Update*

I realized that if we simply don't process values when headers/data/rst are received, then we might not send a `GoAway` and close the connection when `disconnectWhenFinished = true` due to df43379ce3e7a2b36c8634ac013a6af3e16db57e.

I've verified this behavior from test cases added in 8018da1a42240061bfa273a074736effbf3207ae

I've modified further such that:
- Only remove responses when `onStreamClosed` is called.
- Remove calls to `channel().close();` if `shouldSendGoAway()` is true for `onDataRead`, `onHeadersRead` since `onStreamClosed` will handle this instead.
- Remove `onStreamClosed` to try to close the `ResponseWrapper` only if the underlying `delegate` is open.

d1183d8a03eaa5ec541e245ee605c3832a07f23e

There is a slight change of behavior, where a `GoAway` may be triggered from `onRstStream` as well. Let me know if this change shouldn't be made 🙏 

Result:

- Closes #3858

### CODE REVIEW

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTimeoutTest.java [hunk 1]
```diff
@@ -104,6 +104,7 @@ void clientTimeout() throws InterruptedException {
         assertThat(loggingEventCaptor.getAllValues()).noneMatch(event -> {
             return event.getLevel() == Level.WARN &&
                    event.getThrowableProxy() != null &&
+                   event.getThrowableProxy().getMessage() != null &&
```
Comment (minwoox) [inline grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTimeoutTest.java:107]: revert?

File: core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java [hunk 2]
```diff
@@ -96,9 +96,9 @@ private void onWrapperCompleted(HttpResponseWrapper resWrapper, int id, @Nullabl
         resWrapper.onSubscriptionCancelled(cause);
 
         if (cause != null) {
-            // We are not closing the connection but just send a RST_STREAM,
-            // so we have to remove the response manually.
-            removeResponse(id);
+            // Removing the response and decrementing {@code unfinishedResponses} isn't done immediately
+            // here. Instead, we rely on {@code Http2ResponseDecoder#onStreamClosed} to decrement
+            // `unfinishedResponses` to match the timing where netty decrements {@code numActiveStreams}.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java:101]: How about?
```suggestion
            // `unfinishedResponses` after Netty decrements `numActiveStreams` in `DefaultHttp2Connection` so that `unfinishedResponses` is never greater than `numActiveStreams`.
```

**Review by minwoox — APPROVED** [review]
What an awesome analysis! 😄

File: core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java [hunk 3]
```diff
@@ -96,9 +96,9 @@ private void onWrapperCompleted(HttpResponseWrapper resWrapper, int id, @Nullabl
         resWrapper.onSubscriptionCancelled(cause);
 
         if (cause != null) {
-            // We are not closing the connection but just send a RST_STREAM,
-            // so we have to remove the response manually.
-            removeResponse(id);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java:101]: I think we can't only rely on the close events notified by Netty's HTTP2 stream handler.
A request could be failed before writing the first headers if the request fails early.
https://github.com/line/armeria/blob/2920a1ddc2188f150a0d8b77de1d4e2e409997cf/core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java#L169-L172
The early cancelation does not decrease the `unfinishedResponses` and it could be a leak. It rarely happens though.

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java:101]: > The early cancelation does not decrease the unfinishedResponses and it could be a leak. It rarely happens though.

Thanks for the detailed review!

I think you're right in that `unfinishedResponses` may not be decremented in the scenario you mentioned.

I'm not sure there will be a leak since the actual `HttpResponseWrapper` isn't created at that point, but I think a connection may not utilize the maximum allowed number of streams. (for instance, although `MAX_CONCURRENT_STREAMS == 5`, the connection may end up using only 3 streams)

I'd like to handle this issue separately in #3920 since this problem slightly diverges from the original issue 🙏

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java:101]: Agreed to handle in the f/u PR.

**Review by ikhoon — APPROVED** [review]
Thanks!

**Comment by jrhee17** [comment]
Sorry @reviewers

While taking another look, I realized that the channel might not send a goAway frame when necessary.
Let me add a unit test and a revised commit soon - sorry 🙏

**Comment by jrhee17** [comment]
Sorry 😅  I've added 3 commits, I'd appreciate if you can take another look 🙏

File: core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java [hunk 4]
```diff
@@ -54,6 +58,14 @@ protected void configure(ServerBuilder sb) {
             sb.idleTimeoutMillis(0);
             sb.requestTimeoutMillis(0);
             sb.service("/", (ctx, req) -> HttpResponse.of(OK));
+            sb.annotatedService("/delayed", new Object() {
+
+                @Get
+                public HttpResponse delayed(@Param("seconds") String seconds) {
+                    return HttpResponse.delayed(
+                            HttpResponse.of(200), Duration.of(Long.valueOf(seconds), ChronoUnit.SECONDS));
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java:66]: nit:
```suggestion
                            HttpResponse.of(200), Duration.ofSeconds(Long.valueOf(seconds)));
```
I think we can also change the type of `seconds` to `Long`(perhaps Duration) in the method definition.

File: core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java [hunk 5]
```diff
@@ -160,4 +172,48 @@ void shouldCloseIdleConnectionByMaxConnectionAge(SessionProtocol protocol) {
...
+                                                  .idleTimeoutMillis(0)
+                                                  .maxConnectionAgeMillis(MAX_CONNECTION_AGE)
+                                                  .tlsNoVerify()
+                                                  .build()) {
+            final WebClient client = WebClient.builder(server.uri(protocol))
+                                              .factory(factory)
+                                              .responseTimeoutMillis(0)
+                                              .build();
+
+            assertThat(client.get("/delayed?seconds=4").aggregate().join().status()).isEqualTo(OK);
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java:190]: The request doesn't seem to be closed unlike what the method name says?

I maybe miss something, but if the `MAX_CONNECTION_AGE` is two seconds and the response is sent after 4 seconds, shouldn't the connection should be closed forcefully? 🤔

**Review by minwoox — COMMENTED** [review]
Thanks, left some questions. 😄

File: core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java (hunk 5 above)
Comment (jrhee17) [reply core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java:190]: Sorry about the late check

Maybe I'm misunderstanding the specification, but I thought that even if `MAX_CONNECTION_AGE` is reached, the client waits for requests to finish (so it doesn't forcefully fail long-running requests). I've updated the test name to better reflect this 😅 

1) A timer is scheduled for `MAX_CONNECTION_AGE`, but is only respected if there are no running requests
https://github.com/line/armeria/blob/b77bfbb931d8c5b51f65715db7a50c97c12ba622/core/src/main/java/com/linecorp/armeria/internal/common/AbstractKeepAliveHandler.java#L436-L440

2) Instead, every time a request may have finished, we check if `MAX_CONNECTION_AGE` has passed, and there are no running requests.

https://github.com/line/armeria/blob/b77bfbb931d8c5b51f65715db7a50c97c12ba622/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L153-L155
https://github.com/line/armeria/blob/b77bfbb931d8c5b51f65715db7a50c97c12ba622/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L215-L217
https://github.com/line/armeria/blob/b77bfbb931d8c5b51f65715db7a50c97c12ba622/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L275-L279

3) At the same time, we don't allow future requests for connections where `MAX_CONNECTION_AGE` has passed.
https://github.com/line/armeria/blob/b77bfbb931d8c5b51f65715db7a50c97c12ba622/core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java#L163

Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java:189]: > I've updated the test name to better reflect this 😅

Thanks for that. 😄 

> but I thought that even if MAX_CONNECTION_AGE is reached, the client waits for requests to finish (so it doesn't forcefully fail long-running requests)

Exactly. My memory was wrong. Thanks for checking it. 😄

File: core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java [hunk 6]
```diff
@@ -184,8 +187,8 @@ public void onSettingsAckRead(ChannelHandlerContext ctx) {}
     public void onHeadersRead(ChannelHandlerContext ctx, int streamId, Http2Headers headers, int padding,
                               boolean endOfStream) throws Http2Exception {
         keepAliveChannelRead();
-        final HttpResponseWrapper res = getResponse(streamIdToId(streamId), endOfStream);
-        if (res == null) {
+        final HttpResponseWrapper res = getResponse(streamIdToId(streamId));
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java:190]: nit: `getResponse(int id, boolean remove)` is used only in `onStreamClosed()`.
Could we remove `getResponse(int id, boolean remove)` and use `removeResponse()` instread?

**Review by ikhoon — COMMENTED** [review]
Still LGTM!

**Comment by minwoox** [comment]
https://github.com/line/armeria/runs/4285541086?check_suite_focus=true#step:6:1154
@jrhee17 Could you check if the failure is related to the change, please?

**Comment by jrhee17** [comment]
I've tried force pushing to rerun the test.

> Could you check if the failure is related to the change, please?

`SessionProtocol[3]` is `H1`, and this PR doesn't touch anything `http1` related so I think this change probably isn't related.
Let me look into the source of flakiness separately 🙏  (unless the same test fails again with the re-run 😅 )

**Comment by ikhoon** [comment]
> I've tried force pushing to rerun the test.

You might want to install @trustin's awesome script https://gist.github.com/trustin/05cbb70e22fc5e7c8b5ffbd1f0d99c8b

**Comment by minwoox** [comment]
Thanks for checking it. 😅 

> Let me look into the source of flakiness separately

We don't have to do it right now. I just wanted to make sure. 😄

**Comment by ikhoon** [comment]
> [line/armeria/runs/4285541086?check_suite_focus=true#step:6:1154](https://github.com/line/armeria/runs/4285541086?check_suite_focus=true#step:6:1154) @jrhee17 Could you check if the failure is related to the change, please?

I guess The flaky test seems not related to this PR.

**Comment by minwoox** [comment]
Thanks a lot, @jrhee17 for fixing this bug which is really hard to find the cause. 😄
