### PR TITLE
Fix PathMapping implementations to produce their loggerName and metricName correctly

### LINKED ISSUE #651: Add specific name field to AnnotatedHttpService related annotations for logger/metrics
## problem
currrently when we use `AnnotatedHttpService`, logger/metrics names become followings 

- loggerName
  - `armeria.services.__UNKNOWN__`
- metricName example (get from metrics path)
  - `server.${serviceName}.__UNKNOWN_PATH__.GET.successes`

## proposal
add metricName or something into `@Get`, `@Post`, ... annotations. then fill-in into logger/metrics name.

### PR DESCRIPTION
**Pull request by hyangtack**
Motivation:

- For some cases, a user may get `__UNKNOWN__` as `loggerName` and/or `__UNKNOWN_PATH__` as `metricName`.

Modifications:

- Set `loggerName` and `metricName` when instantiating `PrefixAddingPathMapping` and `DefaultPathMapping` class.
- A glob pattern not starting with '/' will be treated as `/**/..pattern..` for `loggerName` and `metricName`.
- Make `metricName` of `RegexPathMapping` as `/regex:...` instead of `regex:...`.

Result:

- Fixes #651

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java [hunk 1]
```diff
@@ -326,17 +326,21 @@ private AnnotatedHttpServices() {}
     /**
      * A {@link PathMapping} implementation that combines path prefix and another {@link PathMapping}.
      */
-    private static final class PrefixAddingPathMapping extends AbstractPathMapping {
+    static final class PrefixAddingPathMapping extends AbstractPathMapping {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java]: Could be `private`?

Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java]: It's for test. I'll add `@VisibleForTesting`.

File: core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java [hunk 2]
```diff
@@ -326,17 +327,22 @@ private AnnotatedHttpServices() {}
...
+        private final String metricName;
 
         PrefixAddingPathMapping(String pathPrefix, PathMapping mapping) {
             assert mapping instanceof GlobPathMapping || mapping instanceof RegexPathMapping
                     : "unexpected mapping type: " + mapping.getClass().getName();
 
             this.pathPrefix = pathPrefix;
             this.mapping = mapping;
+            loggerName = loggerName(pathPrefix) + '.' + mapping.loggerName();
+            metricName = pathPrefix + mapping.metricName();
```
Comment (krrrr38) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java]: 🙆‍♂️
