### PR TITLE
Fix NoSuchElementException raised by RampingUpEndpointWeightSelector

### LINKED ISSUE #3776: `NoSuchElementException` raised by `RampingUpEndpointWeightSelector`
```
  java.util.NoSuchElementException: null
    at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
    at com.linecorp.armeria.client.endpoint.WeightRampingUpStrategy$RampingUpEndpointWeightSelector.updateEndpoints(WeightRampingUpStrategy.java:188)
    at com.linecorp.armeria.client.endpoint.WeightRampingUpStrategy$RampingUpEndpointWeightSelector.lambda$new$0(WeightRampingUpStrategy.java:143)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:835)
```

I got a report from @m50d 
> I think this was during a restart, not hugely important but it seems like a bug somehow? AFAICS that can only happen if RampingUpEndpointWeightSelector#close ran and updateEndpoints  ran afterwards or in parallel, but they're supposed to only run on the same single-threaded executor and close should only be called after the EndpointGroup (which is the only place that calls updateEndpoints) has closed. Looking at the code I can't see exactly how that scenario would occur, but maybe there's an EndpointGroup implementation that doesn't close properly?

### PR DESCRIPTION
**Pull request by kojilin**
Motivation:

A `NoSuchElementException` can be raised when the endpoints are fully replaced in
`RampingUpEndpointWeightSelector`, because `shouldRampUpWithPreviousRampedUpEntry`
may return `true` but `filterOldEndpoints` clears the entries.

Modifications:

- Call `filterOldEndpoints` at the beginning and reuse its result for all the cases
  including `ramp up with previous`, `rampup with next` or `add new entry`.

Result:

- Closes #3776
- No more `NoSuchElementException` when endpoints are fully changed.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java [hunk 1]
```diff
@@ -187,8 +187,8 @@ private void updateEndpoints(List<Endpoint> newEndpoints) {
             if (rampingUpTaskWindowNanos > 0) {
                 // Check whether we can ramp up with the previous ramped up endpoints which are at the last
                 // of the rampingUpEndpointsEntries.
+                final Set<EndpointAndStep> newlyAddedEndpoints = filterOldEndpoints(newEndpoints);
```
Comment (kojilin) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java:190]: This affects existing ramping up(removing endpoints if disappeared). I'm curious if it's still ok to use `newEndpoints` for line [203](https://github.com/line/armeria/blob/13e6d13546ea60cf65e148e9e0e5771f518608e1/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L203), I think it should be ok because `filterOldEndpoints(unhandledNewEndpoints)` is called at `updateWeightAndStep`.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java:190]: > I'm curious if it's still ok to use newEndpoints for line [203](https://github.com/line/armeria/blob/13e6d13546ea60cf65e148e9e0e5771f518608e1/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L203) I think it should be ok 

So do I. 😆

**Review by minwoox — APPROVED** [review]
Thanks a lot for fixing this bug, @kojilin! 😄

**Review by ikhoon — APPROVED** [review]
Thanks, @kojilin!

**Review by jrhee17 — APPROVED** [review]
Thanks for the analysis and fix @kojilin 💯 👍 🙇

**Comment by kojilin** [comment]
Updated, sorry for changing the behavior and it may need review again. But I think the 2nd change is better(avoid filtering/updating existing entry twice).
Please see the last commit https://github.com/line/armeria/pull/4102/commits/b520fb5aef435e82ff5e2b61675198cf54c9d734 and let me know if you like this or not(I can rollback to previous commit if needed).

**Comment by trustin** [comment]
@kojilin Could you update the PR description if your last change affects it?

**Comment by kojilin** [comment]
Refine and updated desc.

**Review by jrhee17 — APPROVED** [review]
The new changes still look good to me 👍  Thanks for the cleanup @kojilin 🙇 🙇 🙇

**Review by trustin — APPROVED** [review]
Thanks a lot for fixing this tricky problem, @kojilin 🙇:bow:

**Comment by trustin** [comment]
I updated the PR description so it's a little bit easier to digest 🙂
