### PR TITLE
Easier way to specify a success function / Different sampler for successful and failed requests

### LINKED ISSUE #3666: Log all failure responses regardless of the sampler
Currently, `LoggingService` uses the same sampling rate for the success and failure responses. 
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java#L124
It will be nice if we sample all failure responses and just samples for the success responses.

### PR DESCRIPTION
**Pull request by kojilin**
Motivation:

- It would be nice if a user can specify a success function, which
  determines whether a request was handled successful or not, when
  building a client or server, not when building a decorator, so
  a user doesn't have to specify the same success function for each
  decorator that requires it, such as `LoggingService` and
  `MetricCollectingService`.
- As described in #3666, it'd be nice if we can log all failed
  responses while using sampling for the successful responses.

Modifications:

- Deprecated `MetricCollecting{Client,Service}Builder.successFunction()`
  in favor of `SuccessFunction` that can be specified when constructing
  a client or server.
- Added `successSampler` and `failureSampler`
- Added `successSamplingRate` and `failureSamplingRate`
- Deprecated `samplingRate` in favor of `successSamplingRate` and
  `failureSamplingRate`
- `Logging{Client,Server}` now waits until it knows whether the request
  was successful or not before calling the sampler.
  - Therefore, `Logging{Client,Server}` will log a request after it's
    handled completely, because otherwise we don't know which sampler
    to use.

Result:

- Closes #3666
- A user can now specify a `SuccessFunction` when constructing a client
  or server rather than specifying it for each decorator.
- A user can now specify different sampler for successful and failed requests.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java [hunk 1]
```diff
@@ -115,13 +117,20 @@
...
+        this.failedSampler = requireNonNull(failedSampler, "failedSampler");
     }
 
     @Override
     public final O execute(ClientRequestContext ctx, I req) throws Exception {
-        if (sampler.isSampled(ctx)) {
-            logWhenComplete(logger, ctx, requestLogger, responseLogger);
-        }
+        ctx.log().whenComplete().thenAccept(log -> {
+            if (log.responseCause() == null) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: How about also adding a Predicate that determines if a request is failed or not?
Users might want to `failureSampler` when the status is 5XX.

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java [hunk 2]
```diff
@@ -51,4 +64,17 @@ public AbstractLoggingClientBuilder sampler(Sampler<? super ClientRequestContext
     final Sampler<? super ClientRequestContext> sampler() {
         return sampler;
     }
+
+    /**
+     * Sets the {@link Sampler} that determines which failed request needs logging.
+     */
+    public AbstractLoggingClientBuilder failedSampler(
```
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java:71]: How about also adding `successSampler`? i.e `sampler` is set to both `successSampler` and `failureSampler` so that we keep the current behavior.

**Review by minwoox — COMMENTED** [review]
Thanks! Left some suggestions. 😄

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java (hunk 1 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: `MetricCollecting{Service,Client}` has its own success function.
https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClient.java#L68
If we also provide another predicate separately, a request could be considered a different result depending on the decorators.
Should we need to support a `Client` level and server level `success function?
```java
Server.builder()
      .successFunction(log -> ...)

WebClient.builder()
      .successFunction(log -> ...)
```

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: I completely missed that. 😅 
Yeah, I think it's a great idea. 👍

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: You mean adding successFunction to ServerBuilder? So `MetricCollectingServiceBuilder`  also need to check if ServerBuilder's successFunction if there is no successFunction at MetricCollectingBuilder?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: > You mean adding successFunction to ServerBuilder? 

Right.

> check if ServerBuilder's successFunction if there is no successFunction at MetricCollectingBuilder?

I think we can give `ServerBuilder.successFunction()` lower priority.

- Promote the default success function into the default function at `ServerBuilder` and `ClientBuilder` level.
- Deprecate `MetricCollectingClientBuilder.successFunction()`.
- Use `ServiceRequestContext.config().successFunction()` or `ClientRequestContext.options().sucessFunction()`
  if a custom success function is not specified. In short, if a custom success function is specified in 
  `MetricCollecting{Service,Client}`, ignore successFunction() in `RequestContext`.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: Additionally, it would be nice to configure a success function at `Service` level.

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: > Additionally, it would be nice to configure a success function at Service level.
About Service level is ServiceBindingBuilder? 


Adding this successFunction looks ok for me, but curious if it's appropriate due to Server it self is not using it but decorators/services lookup through  ServerConfig. Or just let user pass the same `BiPredicate` for decorators.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: > About Service level is ServiceBindingBuilder?

I think we can follow how the `BlockingTaskExecutor` is configured.

> if it's appropriate due to Server it self is not using it but decorators/services lookup through ServerConfig. Or just let user pass the same BiPredicate for decorators.

It should be passed via `ServiceConfig`. Users can set a custom success function per service.

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: > I think we can follow how the BlockingTaskExecutor is configured.
> It should be passed via ServiceConfig. Users can set a custom success function per service.  

I see.

And one question is if it's good idea to add this to `ServiceConfig`? For example if armeria have another built-in decorators with other `Function` or `Predicate`, will we add all of them to `ServiceConfig` or keep it at Decorator level. 

```
Server.builder()
      .successFunction((requestContext, requestLog) -> ...) // server level
      .blockingTaskExecutor(12)  // server level
      .route()
      .successFunction((requestContext, requestLog) -> ...)  // service level
      .blockingTaskExecutor(12)   // service level
      .build(thriftService)
```

or

```

BiPredicate<? super RequestContext, ? super RequestLog> successFunction = (requestContext, requestLog)->{...};

Server.builder()
          .service("/", service.decorate(LoggingService.newDecorator().successFunction(successFunction)
                                         .decorate(MetricCollectingService.builder( MeterIdPrefixFunction.ofDefault(""))
                                                                      .successFunction(successFunction)
                                                                      .newDecorator())));
```

Other user designed decorators can utilize this also, but not sure if it's easy to be aware of general successFunction setting through ServerBuilder/ServiceBindingBuilder.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:126]: > but not sure if it's easy to be aware of general successFunction setting through ServerBuilder/ServiceBindingBuilder.

Agreed. I think it has pros and cons. It doesn't look intuitive but users can easily configure the success function at the service level which is a bit verbose with decorators.

`ServiceConfig.transientServiceOptions()` is a similar case. It is configured through Server/Service builder and used in some built-in decorators. 
https://github.com/line/armeria/blob/aa647fae9278fa54c4f303c29e1db8f058fbaf78/core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java#L293
https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingService.java#L91

**Comment by kojilin** [comment]
Updated, maybe check if I address the comments correctly.
Will update TODO comments & adding test for `successFunction` customization.

File: core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java [hunk 3]
```diff
@@ -1891,6 +1910,29 @@ private static void warnIfServiceHasMultipleRoutes(String path, HttpService serv
         }
     }
 
+    /**
+     * Default success response classification function which checks
+     * {@link RequestLog#responseCause()} is null, 100 &lt;= {@link HttpStatus} &lt; 400
+     * and {@link RpcResponse#isCompletedExceptionally()} == {@code false}.
+     */
+    private static boolean isSuccess(RequestContext ctx, RequestLog log) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java:1918]: How about introducing `SuccessFunction` interface so that Spring users easily make an instance of `SuccessFunction` Spring `@Bean`?
The `SuccessFunction` could be placed in `armeria.common`.
```java
public interface SuccessFunction {

   static of() {
       // Move `isSuccess` method to here.
       ...
   }

   boolean isSuccess(RequestContext ctx, RequestLog log);
```

File: core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java [hunk 4]
```diff
@@ -178,6 +184,17 @@ public AbstractClientOptionsBuilder requestIdGenerator(Supplier<RequestId> reque
...
     }
 
+    /**
+     * Sets the {@link BiPredicate} to allow custom definition of successful responses.
+     * {@link MetricCollectingClient}, {@link LoggingClient} and {@link LoggingRpcClient} will use this custom
+     * definition if set.
+     * If not set, default one in {@link ClientOptions} is used.
+     */
+    public AbstractClientOptionsBuilder successFunction(
+            BiPredicate<? super RequestContext, ? super RequestLog> successFunction) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java:194]: `requireNonNull`?

File: core/src/main/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilder.java [hunk 5]
```diff
@@ -67,7 +69,11 @@ protected MeterIdPrefixFunction meterIdPrefixFunction() {
      *         })
      *         .newDecorator();
      * }</pre>
+     *
+     * @deprecated Use {@link ClientBuilder#successFunction(BiPredicate)} or
+ *                 {@link ServerBuilder#successFunction(BiPredicate)} instead.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilder.java:74]: 👍; nit indent?

**Review by ikhoon — COMMENTED** [review]
Solid work! 💯 Left minor comment. :-)

File: core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java (hunk 4 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java:194]: Should we make all subclasses of this class override this method?

File: core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java (hunk 3 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java]: Done. Not making `AbstractArmeriaAutoConfiguration` support this yet. Do you think it's better to do it for server level?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java]: > Do you think it's better to do it for server level?

I think so. But we don't need to add it to this PR. We can easily add it later when there is a demand for it.

File: core/src/main/java/com/linecorp/armeria/client/AbstractWebClientBuilder.java [hunk 6]
```diff
@@ -44,7 +44,7 @@
     private static final Set<SessionProtocol> SUPPORTED_PROTOCOLS =
             Sets.immutableEnumSet(
                     ImmutableList.<SessionProtocol>builder().addAll(SessionProtocol.httpValues())
-                                                            .addAll(SessionProtocol.httpsValues()).build());
+                                 .addAll(SessionProtocol.httpsValues()).build());
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/AbstractWebClientBuilder.java:47]: nit: How about adding a new line after `builder()`?
```java
ImmutableList.<SessionProtocol>builder()
             .addAll(SessionProtocol.httpValues())
             .addAll(SessionProtocol.httpsValues())
             .build());
```

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java [hunk 7]
```diff
@@ -114,14 +116,21 @@
...
         this.responseTrailersSanitizer = requireNonNull(responseTrailersSanitizer, "responseTrailersSanitizer");
         this.responseCauseSanitizer = requireNonNull(responseCauseSanitizer, "responseCauseSanitizer");
-        this.sampler = requireNonNull(sampler, "sampler");
+        this.successSampler = requireNonNull(successSampler, "successSampler");
+        this.failureSampler = requireNonNull(failureSampler, "failureSampler");
     }
 
     @Override
     public final O execute(ClientRequestContext ctx, I req) throws Exception {
-        if (sampler.isSampled(ctx)) {
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:122]: Instead of having 2 new axes, success/failure function then sucess/failure sampler, could sampler just be updated to accept both ctx and log? The default sampler would still be implemented to behave as it does right now

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java [hunk 8]
```diff
@@ -28,27 +28,81 @@
...
                       "samplingRate: %s (expected: 0.0 <= samplingRate <= 1.0)", samplingRate);
         return sampler(Sampler.random(samplingRate));
     }
 
+    /**
+     * Sets the rate at which to sample requests to log. Any number between {@code 0.0} and {@code 1.0} will
+     * cause a random sample of the failure requests to be logged.
+     * This method sets both success and failure, if you want to specify different values for the success
+     * and failure samplers, use {@link #successSampler(Sampler)} and * {@link #failureSampler(Sampler)}
+     * instead.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java:53]:
```suggestion
     * Sets the rate at which to sample failure requests to log. Any number between {@code 0.0} and 
     * {@code 1.0} will cause a random sample of the failure requests to be logged.
```

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java [hunk 9]
```diff
@@ -28,27 +28,81 @@
...
+    public AbstractLoggingClientBuilder failureSamplingRate(float failureSamplingRate) {
+        checkArgument(0.0 <= failureSamplingRate && failureSamplingRate <= 1.0,
+                      "failureSamplingRate: %s (expected: 0.0 <= failureSamplingRate <= 1.0)",
+                      failureSamplingRate);
+        return failureSampler(Sampler.random(failureSamplingRate));
+    }
+
+    /**
+     * Sets the rate at which to sample requests to log. Any number between {@code 0.0} and {@code 1.0} will
+     * cause a random sample of the success requests to be logged.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java:64]:
```suggestion
     * Sets the rate at which to sample success requests to log. Any number between {@code 0.0} and 
     * {@code 1.0} will cause a random sample of the success requests to be logged.
```

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java (hunk 7 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:122]: You mean like
```
CompletableFututre<Boolean> isSampled(ctx, RequestLog);
```
So the sampler can have ability to check sample or not? Let me check if it can fit in other place also.

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 10]
```diff
@@ -0,0 +1,63 @@
...
+
+import com.linecorp.armeria.common.logging.RequestLog;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.server.metric.MetricCollectingService;
+
+/**
+ * A function that accepts {@link RequestContext} and {@link RequestLog} for checking if the response is
+ * success.
+ *
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:27]: Could you add examples that describes how a custom `SuccessFunction` could be used `ServerBuilder.successFunction()` and `WebClientBuilder.successFunction()`?

File: core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java [hunk 11]
```diff
@@ -321,6 +327,13 @@ public boolean shutdownBlockingTaskExecutorOnStop() {
         return shutdownBlockingTaskExecutorOnStop;
     }
 
+    /**
+     * Returns the {@link BiPredicate} for checking if the response is success.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java:331]:
```suggestion
     * Returns the {@link SuccessFunction} for checking if the response is success.
```

File: core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java [hunk 12]
```diff
@@ -138,4 +141,11 @@ ServiceConfigSetters blockingTaskExecutor(ScheduledExecutorService blockingTaskE
      * @param numThreads the number of threads in the executor
      */
     ServiceConfigSetters blockingTaskExecutor(int numThreads);
+
+    /**
+     * Defines a custom {@link SuccessFunction} to allow custom definition of successful requests and responses.
+     * {@link MetricCollectingService} and {@link LoggingService}  use this custom
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java:147]:
```suggestion
     * {@link MetricCollectingService} and {@link LoggingService} use this custom
```

File: core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java [hunk 13]
```diff
@@ -59,6 +59,13 @@
      */
     float samplingRate() default 1.0f;
 
+    /**
+     * The rate at which to sample failed requests to log. Any number between {@code 0.0} and {@code 1.0} will
+     * cause a random sample of the requests to be logged. The random sampling is appropriate for low-traffic
+     * (ex servers that each receive &lt;100K requests). If unset, all requests will be logged.
+     */
+    float failedSamplingRate() default 1.0f;
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java:67]: - Should we also need to add `successSamplingRate`?
- `failedSamplingRate` -> `failureSamplingRate` for consistency?
- `samplingRate()` and `failedSamplingRate()` are mutually exclusive. How about setting the default value of `failedSamplingRate` and `successSamplingRate` to `-1.0f`?
  We can override the `sampleRate` if they are positive.
```java
// In LoggingDecoratorFactoryFunction
float successSamplingRate = parameter.successSamplingRate() != -1.0f ? parameter.successSamplingRate() : parameter.samplingRate();
float failureSamplingRate = ...;
```

File: core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java [hunk 14]
```diff
@@ -40,28 +40,78 @@
...
+    private Sampler<? super ServiceRequestContext> successSampler = Sampler.always();
+
+    private Sampler<? super ServiceRequestContext> failureSampler = Sampler.always();
 
     LoggingServiceBuilder() {}
 
     /**
      * Sets the {@link Sampler} that determines which request needs logging.
+     * This method sets both success and failure, if you want to specify different values for the success
+     * and failure samplers, use {@link #successSampler(Sampler)} and * {@link #failureSampler(Sampler)}
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java:52]:
```suggestion
     * and failure samplers, use {@link #successSampler(Sampler)} and {@link #failureSampler(Sampler)}
```

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java (hunk 7 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:122]: Checked the source and maybe wanna discuss if possible.  
`Sampler` is public interface with `boolean isSampled(T object);` already, so we may not want to change it to `CompletableFututre<Boolean> isSampled(ctx, RequestLog)`


And @ikhoon Do you think it's good idea to make `SuccessFunction#isSuccess` returns `CompletableFuture<Boolean>` ? Because we may prefer the implementation of `isSuccess` using `requestLog.whenComplete()` directly but not at decorator like `LoggingService`?

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java:122]: Just realized that Sampler is exposed and maybe I misunderstood what you mean.

Refactor the code to combine `successSampler`, `failureSampler` and `successFunction` to single Sampler inside LoggingClient/Server

**Comment by kojilin** [comment]
Updated, may want to check if `LoggingDecoratorFactoryFunction` works well with fallback. Due to it's not setting logger, not that easy to check with `ServerExtension` or calling `LoggingDecoratorFactoryFunction#newDecorator` directly. :thinking:

File: core/src/main/java/com/linecorp/armeria/client/ClientOptions.java [hunk 15]
```diff
@@ -283,6 +291,13 @@ public HttpHeaders headers() {
         return get(REQUEST_ID_GENERATOR);
     }
 
+    /**
+     * Returns the {@link BiPredicate} that determine if the request is success.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/ClientOptions.java:295]:
```suggestion
     * Returns the {@link SuccessFunction} that determine if the request is successful or not.
```

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 16]
```diff
@@ -0,0 +1,84 @@
...
+
+            return true;
+        };
+    }
+
+    /**
+     * Return true if the response is success.
+     *
+     * @see LoggingService#serve(ServiceRequestContext, HttpRequest)
+     * @see MetricCollectingService#serve(ServiceRequestContext, HttpRequest)
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:81]: I'm not sure users will get anything useful from the Javadoc of these methods. How about referencing the builder methods?

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 17]
```diff
@@ -0,0 +1,84 @@
...
+ *         .decorator(LoggingClient.newDecorator()))
+ *         .build();
+ * }
+ * </pre>
+ *
+ */
+@FunctionalInterface
+public interface SuccessFunction {
+    /**
+     * Default success response classification function which checks
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:53]:
```suggestion
     * Returns the default success classification function which checks
```

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 18]
```diff
@@ -0,0 +1,84 @@
...
+import com.linecorp.armeria.server.metric.MetricCollectingService;
+
+/**
+ * A function that accepts {@link RequestContext} and {@link RequestLog} for checking if the response is
+ * success. Like {@link ServerBuilder} and {@link WebClientBuilder} are using this interface to decide
+ * the response is success or not for Metric and Logging decorator.
+ *
+ * <p>Example:
+ * <pre>{@code
+ * ServerBuilder sb = ServerBuilder
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:33]: `Server.builder()`?
```suggestion
 * ServerBuilder sb = Server
 *         .builder()
```

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 19]
```diff
@@ -0,0 +1,63 @@
...
+
+package com.linecorp.armeria.common;
+
+import com.linecorp.armeria.common.logging.RequestLog;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.server.metric.MetricCollectingService;
+
+/**
+ * A function that accepts {@link RequestContext} and {@link RequestLog} for checking if the response is
```
[the remark this answers is not in the document]
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:27]: How about this:
```suggestion
 * A function that determines whether a {@link Client} or {@link Service} handled
 * a request successfully or not.
```

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 20]
```diff
@@ -0,0 +1,84 @@
...
+import com.linecorp.armeria.common.logging.RequestLog;
+import com.linecorp.armeria.server.ServerBuilder;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.server.metric.MetricCollectingService;
+
+/**
+ * A function that accepts {@link RequestContext} and {@link RequestLog} for checking if the response is
+ * success. Like {@link ServerBuilder} and {@link WebClientBuilder} are using this interface to decide
+ * the response is success or not for Metric and Logging decorator.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:29]:
```suggestion
 * This function can be used by the decorators like the following to determine
 * whether the request was handled successfully or not:
 * <ul>
 *   <li>{@link MetricCollectingClient}</li>
 *   <li>{@link MetricCollectingService}</li>
 *   <li>{@link LoggingClient}</li>
 *   <li>{@link LoggingService}</li>
 * </ul>
```

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 21]
```diff
@@ -0,0 +1,84 @@
...
+ *
+ * <p>Example:
+ * <pre>{@code
+ * ServerBuilder sb = ServerBuilder
+ *         .successFunction((ctx, req) -> req.responseHeaders().status().code() == 200
+ *                                        || req.responseHeaders().status().code() == 404)
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:35]: `||` could come at the end of the line.

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 22]
```diff
@@ -0,0 +1,84 @@
...
+ *         .decorator(MetricCollectingService.newDecorator(MeterIdPrefixFunction.ofDefault("myServer")))
+ *         .decorator(LoggingService.newDecorator()));
+ *
+ * WebClient client = WebClient
+ *         .builder(uri)
+ *         .successFunction((ctx, req) -> req.responseHeaders().status().code() == 200
+ *                                        || req.responseHeaders().status().code() == 404)
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:42]: `||` could come at the end of the line.

File: core/src/main/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilder.java [hunk 23]
```diff
@@ -67,7 +70,11 @@ protected MeterIdPrefixFunction meterIdPrefixFunction() {
      *         })
      *         .newDecorator();
      * }</pre>
+     *
+     * @deprecated Use {@link ClientBuilder#successFunction(SuccessFunction)} or
+     *                 {@link ServerBuilder#successFunction(SuccessFunction)} instead.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilder.java:75]: 'instead` is redundant.
```suggestion
     *                 {@link ServerBuilder#successFunction(SuccessFunction)}.
```

File: core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java [hunk 24]
```diff
@@ -138,4 +141,10 @@ ServiceConfigSetters blockingTaskExecutor(ScheduledExecutorService blockingTaskE
      * @param numThreads the number of threads in the executor
      */
     ServiceConfigSetters blockingTaskExecutor(int numThreads);
+
+    /**
+     * Defines a custom {@link SuccessFunction} to allow custom definition of successful requests and responses.
+     * {@link MetricCollectingService} and {@link LoggingService} use this custom definition if set.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java:147]:
```suggestion
     * Sets a {@link SuccessFunction} that determines whether a request was handled
     * successfully or not. If unspecified, {@link SuccessFunction#ofDefault()} is used.
     *
     * @see MetricCollectingServiceBuilder#...
     * @see LoggingServiceBuilder#...
```

Please make the similar change for the client side and any other builders applicable.

File: core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java [hunk 25]
```diff
@@ -56,9 +56,30 @@
...
+    @Deprecated
     float samplingRate() default 1.0f;
 
+    /**
+     * The rate at which to sample success requests to log. Any number between {@code 0.0} and {@code 1.0} will
+     * cause a random sample of the requests to be logged. The random sampling is appropriate for low-traffic
+     * (ex servers that each receive &lt;100K requests). If unset, all requests will be logged.
+     * Set this attribute with negative value will fall back to {@link #samplingRate()}.
+     */
+    float successSamplingRate() default -1.0f;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java:73]: Thanks for taking care of this! 🙇 :+1:

File: core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java [hunk 26]
```diff
@@ -108,7 +114,8 @@ void simpleTypeName_nestedClass() {
         final ServiceConfig config =
                 new ServiceConfig(Route.ofCatchAll(), new NestedClass(),
                                   null, null, null, 0, 0, false, AccessLogWriter.common(), false,
-                                  CommonPools.blockingTaskExecutor(), true);
+                                  CommonPools.blockingTaskExecutor(), true,
+                                  (requestContext, requestLog) -> true);
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java:118]: Should we add `SuccessFunction.always()` and `.never()`? 🤔

File: core/src/test/java/com/linecorp/armeria/server/metric/MetricCollectingServiceTest.java [hunk 27]
```diff
@@ -0,0 +1,120 @@
...
+              .route().path("/failure402").defaultServiceName("failure402")
+              .build((ctx, req) -> HttpResponse.of(402))
+              // Service level successFunction customization
+              .route().path("/success402").defaultServiceName("success402")
+              .successFunction((ctx, req) -> req.responseHeaders().status().code() == 402)
+              .build((ctx, req) -> HttpResponse.of(402))
+              // Service level successFunction customization
+              .route().path("/failure401").defaultServiceName("failure401")
+              .successFunction((ctx, req) -> req.responseHeaders().status().code() == 402)
+              .build((ctx, req) -> HttpResponse.of(401));
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/server/metric/MetricCollectingServiceTest.java:58]: Awesome work :+1:

**Review by trustin — COMMENTED** [review]
Thanks a lot for implementing this. Very useful! 🙇

File: core/src/main/java/com/linecorp/armeria/client/ClientOptions.java [hunk 28]
```diff
@@ -283,6 +290,13 @@ public HttpHeaders headers() {
         return get(REQUEST_ID_GENERATOR);
     }
 
+    /**
+     * Returns the {@link SuccessFunction} that determine if the request is success or not.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/ClientOptions.java:294]:
```suggestion
     * Returns the {@link SuccessFunction} that determines if the request is successful or not.
```

File: core/src/main/java/com/linecorp/armeria/client/ClientOptions.java [hunk 29]
```diff
@@ -103,6 +104,12 @@
     public static final ClientOption<Supplier<RequestId>> REQUEST_ID_GENERATOR = ClientOption.define(
             "REQUEST_ID_GENERATOR", RequestId::random);
 
+    /**
+     * The {@link SuccessFunction} that defines successful responses.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/ClientOptions.java:108]:
```suggestion
     * The {@link SuccessFunction} that determines if the request is successful or not.
```

File: core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java [hunk 30]
```diff
@@ -0,0 +1,109 @@
...
+            if (responseContent instanceof RpcResponse) {
+                return !((RpcResponse) responseContent).isCompletedExceptionally();
+            }
+
+            return true;
+        };
+    }
+
+    /**
+     * Return true if the response is success.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/SuccessFunction.java:103]:
```suggestion
     * Returns {@code true} if the response is success.
```

File: core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java [hunk 31]
```diff
@@ -809,6 +814,17 @@ public ServerBuilder blockingTaskExecutor(int numThreads) {
         return blockingTaskExecutor(executor, true);
     }
 
+    /**
+     * Defines a custom {@link SuccessFunction} to allow custom definition of successful responses.
+     * {@link MetricCollectingService} and {@link LoggingService} will use this custom
+     * definition if set.
+     * If not set, {@link SuccessFunction#isSuccess(RequestContext, RequestLog)} is used.
+     */
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java:822]:
```suggestion
    /**
     * Sets a {@link SuccessFunction} that determines whether a request was handled successfully or not.
     * If unspecified, {@link SuccessFunction#ofDefault()} is used.
     */
```

File: core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java [hunk 32]
```diff
@@ -321,6 +326,13 @@ public boolean shutdownBlockingTaskExecutorOnStop() {
         return shutdownBlockingTaskExecutorOnStop;
     }
 
+    /**
+     * Returns the {@link SuccessFunction} for checking if the response is success.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java:330]:
```suggestion
     * Returns the {@link SuccessFunction} that determines whether a request was
     * handled successfully or not.
```

File: core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java [hunk 33]
```diff
@@ -40,28 +40,78 @@
...
+
+    private Sampler<? super ServiceRequestContext> failureSampler = Sampler.always();
 
     LoggingServiceBuilder() {}
 
     /**
      * Sets the {@link Sampler} that determines which request needs logging.
+     * This method sets both success and failure, if you want to specify different values for the success
+     * and failure samplers, use {@link #successSampler(Sampler)} and {@link #failureSampler(Sampler)}
+     * instead.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java:53]:
```suggestion
     * This method sets both success and failure sampler.
     * Use {@link #successSampler(Sampler)} and {@link #failureSampler(Sampler)}
     * if you want to specify different sampler for each case.
```

File: core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java [hunk 34]
```diff
@@ -28,27 +28,78 @@
...
+    private Sampler<? super ClientRequestContext> successSampler = Sampler.always();
+
+    private Sampler<? super ClientRequestContext> failureSampler = Sampler.always();
 
     /**
      * Sets the rate at which to sample requests to log. Any number between {@code 0.0} and {@code 1.0} will
      * cause a random sample of the requests to be logged.
+     * This method sets both success and failure, if you want to specify different values for the success
+     * and failure samplers, use {@link #successSamplingRate(float)} and
+     * {@link #failureSamplingRate(float)} instead.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java:40]:
```suggestion
     * This method sets both success and failure sampling rate.
     * Use {@link #successSamplingRate(float)} and {@link #failureSamplingRate(float)}
     * if you want to specify a different sampling rate for each case.
```

File: core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java [hunk 35]
```diff
@@ -40,28 +40,78 @@
...
+        this.failureSampler = sampler;
         return this;
     }
 
     /**
      * Sets the rate at which to sample requests to log. Any number between {@code 0.0} and {@code 1.0} will
      * cause a random sample of the requests to be logged.
+     * This method sets both success and failure, if you want to specify different values for the success
+     * and failure samplers, use {@link #successSamplingRate(float)} and
+     * {@link #failureSamplingRate(float)} instead.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java:67]:
```suggestion
     * This method sets both success and failure sampling rate.
     * Use {@link #successSamplingRate(float)} and {@link #failureSamplingRate(float)}
     * if you want to specify a different sampling rate for each case.
```

File: core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java [hunk 36]
```diff
@@ -56,9 +56,30 @@
      * The rate at which to sample requests to log. Any number between {@code 0.0} and {@code 1.0} will
      * cause a random sample of the requests to be logged. The random sampling is appropriate for low-traffic
      * (ex servers that each receive &lt;100K requests). If unset, all requests will be logged.
+     * This attribute sets both success and failure, if you want to specify different values for the success
+     * and failure samplers, use {@link #successSamplingRate()} and {@link #failureSamplingRate()} instead.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java:60]:
```suggestion
     * This attribute sets both success and failure sampling rate.
```

File: core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java [hunk 37]
```diff
@@ -56,9 +56,30 @@
...
+     *
+     * @deprecated use {@link #successSamplingRate()} and {@link #failureSamplingRate()} instead.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java:62]:
```suggestion
     * @deprecated Use {@link #successSamplingRate()} and {@link #failureSamplingRate()}.
```

File: core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java [hunk 38]
```diff
@@ -56,9 +56,29 @@
...
+     * @deprecated Use {@link #successSamplingRate()} and {@link #failureSamplingRate()}.
      */
+    @Deprecated
     float samplingRate() default 1.0f;
 
+    /**
+     * The rate at which to sample success requests to log. Any number between {@code 0.0} and {@code 1.0} will
+     * cause a random sample of the requests to be logged. The random sampling is appropriate for low-traffic
+     * (ex servers that each receive &lt;100K requests). If unset, all requests will be logged.
+     * Set this attribute with negative value will fall back to {@link #samplingRate()}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java:70]:
```suggestion
     * If the value of this attribute is negative, the value from {@link #samplingRate()} will be used as a fallback.
```

File: core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java [hunk 39]
```diff
@@ -56,9 +56,29 @@
...
+     */
+    float successSamplingRate() default -1.0f;
+
+    /**
+     * The rate at which to sample failed requests to log. Any number between {@code 0.0} and {@code 1.0} will
+     * cause a random sample of the requests to be logged. The random sampling is appropriate for low-traffic
+     * (ex servers that each receive &lt;100K requests). If unset, all requests will be logged.
+     * Set this attribute with negative value will fall back to {@link #samplingRate()}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java:78]:
```suggestion
     * If the value of this attribute is negative, the value from {@link #samplingRate()}
     * will be used as a fallback.
```

**Review by trustin — APPROVED** [review]
I pushed some fixes for documentation to this PR and it now looks good to me. :-)

**Comment by kojilin** [comment]
Thanks, let me check the changes.(I need to improve by writing^^;;)

**Review by ikhoon — COMMENTED** [review]
Mostly looks good.
Left comments for `@Unstable` and others are nit.

File: core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java [hunk 40]
```diff
@@ -178,6 +182,16 @@ public AbstractClientOptionsBuilder requestIdGenerator(Supplier<RequestId> reque
         return option(ClientOptions.REQUEST_ID_GENERATOR, requestIdGenerator);
     }
 
+    /**
+     * Sets the {@link SuccessFunction} to allow custom definition of successful responses.
+     * {@link MetricCollectingClient}, {@link LoggingClient} and {@link LoggingRpcClient} will use this custom
+     * definition if set.
+     * If not set, default one in {@link ClientOptions} is used.
+     */
+    public AbstractClientOptionsBuilder successFunction(SuccessFunction successFunction) {
```
[the remark this answers is not in the document]
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java:187]: That's a good question I don't have a good answer for. How about keeping `@deprecated` annotation in this case given the possibility of changing this method's signature is fairly low? 🤞

File: core/src/test/java/com/linecorp/armeria/server/metric/MetricCollectingServiceTest.java [hunk 41]
```diff
@@ -0,0 +1,120 @@
...
+
+            sb.meterRegistry(registry)
+              .decorator(MetricCollectingService.newDecorator(MeterIdPrefixFunction.ofDefault("foo")));
+        }
+    };
+
+    @Test
+    void countResponseAsSuccessByServerBuilderSuccessFunction() throws InterruptedException {
+        final WebClient client = WebClient.of(server.httpUri());
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/server/metric/MetricCollectingServiceTest.java:67]: Note (recommended but could be ignored):
- `server.webClient()` could be used.
- We can convert a `WebClient` into a `BlockingWebClient` with `.blocking()` to avoid `.aggregate().join()`.

**Review by jrhee17 — APPROVED** [review]
Wow, this was beautifully done. Thank you @kojilin ! 💯 👍 🙇

**Review by ikhoon — APPROVED** [review]
Awesome work, @kojilin! ❤️
