### PR TITLE
Fix `HttpResponse` not propagating cancellation signal to upstream

### LINKED ISSUE #3690: Cancellation is not propagated to upstream future or publisher in a few cases
`HttpResponse` gets aborted in the following cases:
* `RequestTimeoutException`
* `ClosedSessionException`

Usually, a cancellation signal gets propagated once `HttpResponse` is aborted but that's not true in a few cases.
Following code summarizes when it does and doesn't...:

It would be nice to know if this behavior is something that requires a fix.
```java
Server.builder()
      .requestTimeoutMillis(1000L)
      // `Mono` gets cancellation signal if `HttpResponse` is aborted.
      .service("/http-response-from-publisher",
               (ctx, req) -> HttpResponse.of(
                       Mono.just(ResponseHeaders.of(200))
                           .delayElement(Duration.ofMillis(200))
                           .doOnNext(ignored -> System.out.println("Running..."))
                           .flatMap(data -> Mono.<HttpData>error(new RuntimeException()))
                           .retry()))
      // `Mono` doesn't get cancellation signal though the returned `HttpResponse` is aborted
      // and keeps running forever since `DeferredHttpResponse` doesn't propagate cancellation
      // to the `CompletionStage`.
      .service("/http-response-from-future",
               (ctx, req) -> HttpResponse.from(
                       Mono.just(ResponseHeaders.of(200))
                           .delayElement(Duration.ofMillis(200L))
                           .doOnNext(ignored -> System.out.println("Running..."))
                           .flatMap(data -> Mono.<HttpData>error(new RuntimeException()))
                           .retry()
                           .map(HttpResponse::of)
                           .toFuture()))
      .annotatedService(new Object() {
          // `Mono` doesn't get cancellation signal since `AbstractCollectingSubscriber` and 
          // `ResponseConversionUtil#aggregateFrom` doesn't propagate cancellation to upstream.
          @Get("/single-value-publisher")
          @ProducesJson
          public Mono<String> singleValuePublisher() {
              return Mono.just("hello, armeria!")
                         .delayElement(Duration.ofMillis(200L))
                         .doOnNext(ignored -> System.out.println("Running..."))
                         .flatMap(data -> Mono.<String>error(new RuntimeException()))
                         .retry();
          }

          // `Flux` gets cancellation signal normally.
          @Get("/multi-value-publisher")
          @ProducesJsonSequences
          public Flux<String> multiValuePublisher() {
              return Flux.just("hello,", " armeria!")
                         .delayElements(Duration.ofMillis(200L))
                         .doOnNext(ignored -> System.out.println("Running..."))
                         .repeat();
          }

          // The `future` gets never cancelled as `AnnotatedService#serve0` doesn't propagate
          // cancellation to the upstream future. - `AnnotatedService.java:L312`.
          @Get("/future")
          public CompletableFuture<String> future() {
              final CompletableFuture<String> future = new CompletableFuture<>();
              future.whenComplete((ignored, cause) -> {
                  if (future.isCancelled()) {
                      System.out.println("Future is cancelled!");
                  }
              });
              return future;
          }
      });
```
```kotlin
Server.builder()
    .requestTimeoutMillis(1000L)
    .annotatedService(object {
        // The coroutine never gets cancelled and runs forever as `AnnotatedService#serve0` doesn't
        // propagate cancellation to `KOTLIN_COROUTINES`.
        @Get("/coroutine")
        suspend fun coroutine(): String {
            try {
                while (true) {
                    delay(200L)
                    println("Running...)
                }
            } catch (e: CancellationException) {
                println("It never reaches here")
            }
            return "hello, armeria!"
        }
    })
```

### PR DESCRIPTION
**Pull request by ks-yim**
Motivation:

Cancellation signal is supposed to be propagated to upstream future or publisher once `HttpResponse` is aborted or cancelled, but currently it's not true in the following cases.

- `HttpService` whose `HttpResponse` type is `DeferredHttpResponse`.
- `AnnotatedService` whose return type is one of:
  - Single object publisher
  - `CompletionStage` including `KOTLIN_COROUTINES` and `SCALA_FUTURE`.

Modifications:

- Make `DeferredHttpResponse` propagates cancellation signal to its backing `CompletionStage`.
- Make `AbstractCollectingSubscriber` propagates cancellation signal to upstream `Publisher`.
- Make `AnnotatedService` propagates cancellation signal to `Future` of various types. 

Result:

- Closes #3690
- `HttpResponse`'s upstream `Publisher` and `Future` of various types now gets a cancellation signal properly.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java [hunk 1]
```diff
@@ -69,4 +80,43 @@ public EventExecutor defaultSubscriberExecutor() {
         }
         return super.defaultSubscriberExecutor();
     }
+
+    @Override
+    public void subscribe(Subscriber<? super HttpObject> subscriber, EventExecutor executor,
+                          SubscriptionOption... options) {
+        super.subscribe(new Subscriber<HttpObject>() {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java:87]: We already wrap the `Subscriber` given by a user in `DeferredStreamMessage`. Would it be possible to consolidate this into `DeferredStreamMessage` somehow so we don't have to wrap the `Subscriber` twice?

**Comment by minwoox** [comment]
I was rather thinking of handling it in `HttpResponse`. 🤔 
```java
static HttpResponse from(CompletionStage<? extends HttpResponse> stage) {
    // We should warn the stage might not be complete exceptionally if it's not an instance of CompletableFuture
    // in the Javadoc.
    return from(stage.toCompletableFuture()); 
}

static HttpResponse from(CompletableFuture<? extends HttpResponse> future) {
    requireNonNull(future, "future");
    final DeferredHttpResponse res = new DeferredHttpResponse();
    res.delegateWhenComplete(future);
    res.whenComplete().handle((unused, cause) -> {
        if (cause != null && !future.isDone()) {
            future.completeExceptionally(cause);
        }
        return null;
    });
    return res;
}

```

**Comment by ikhoon** [comment]
Let's continue the discussion https://github.com/line/armeria/issues/3690#issuecomment-877931762 here. I didn't notice that other folks have been discussing the issue here. 😅

> Okay, I will try to work on that.
>
> The other case we should have in mind is `AnnotatedService` returning `CompletionStage`.
> If a user want to add a callback for cancellation, they will do...:
> ```java
> future.whenComplete((result, cause) -> {
>    if (future.isCancelled()) { ... }
>    ...
> }
> ```
> But `future.isCancelled()` will evaluate to `false` if the future complete exceptionally with `CancelledSubscriptionException`.
> The same goes for `KOTLIN_COROUTINES` I guess (not sure).
> 
> Maybe it's an overkill, though 😅.

It is a bit tricky because if a stream is cancelled, Armeria uses `CancelledSubscriptionException` 
for completing a `CompletableFuture` such as ``HttpResponse.whenComplete()` and `HttpResponse.aggregate()`.
It sounds natural that a `CompletableFuture` returned by a service cancels with 
a `java.util.concurrent.CancellationException`. However it does not tell the detail reason why the future is cancelled. 

I'm still leaning toward canceling a `CompletableFuture` only for `MonoToCompletableFuture`.

**Comment by minwoox** [comment]
I think it's better to cancel the future that is used when `HttpResponse.from(future)`.
The stream message is one-time subscribable, and so is the `future` which means we cannot create multiple responses from the future:
```java
CompletableFuture<HttpResponse> future = ...
HttpResponse res1 = HttpResponse.from(future);
HttpResponse res2 = HttpResponse.from(future); // res2 cannot be subscribable.
```
So if the `HttpResponse` is canceled or aborted, we don't need the `future` anymore so I think we can just complete the future with the exception.
If we do that, we can also use the future to check if the response is canceled not to retry in the retrying client.

> However it does not tell the detail reason why the future is cancelled.

If that's your concern, we can probably add the detail to the exception and cancel the future.
However, I think it's enough to cancel the future with the downstream exception.

**Comment by ks-yim** [comment]
@minwoox Maybe I am not getting the whole sense of your saying, but the discussion was about "HOW" to cancel the future. More specifically, about choosing between `future.cancel(true)` or `future.completeExceptionally(downstreamCause)` when the `downstreamCause` is `CancelledSubscriptionException`.

There seems to be a few cases where completing a future exceptionally with `CancelledSubscriptionException` is an undesirable mode of cancellation since the future will stop propagating cancellation to further upstream. [`MonoToCompletableFuture`](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/MonoToCompletableFuture.java#L38-L48) is a good example of such a case as @ikhoon stated.

And I was suggesting all futures (including `KOTLIN_COROUTINES`) be cancelled by `future.cancel(true)` as users may want the check `future.isCancelled()` or `CancellationException` to add a fallback logic for cancellation, while @ikhoon wanted to allow the use of `future.cancel(true)` only for `MonoToCompletableFuture`.

**Comment by minwoox** [comment]
>  but the discussion was about "HOW" to cancel the future.

It's not just about how to cancel the future.
@ikhoon suggested canceling only the `MonoToCompletableFuture` so I added my opinion that we need to cancel all futures that are used when `HttpResponse.from(future)`.

So, there are two points. 😄 
- Which future should we cancel. Only for `MonoToCompletableFuture` or all futures that are used `HttpResponse.from(future)`.
- How to cancel the future.

I already explained about the first one that we need to cancel all futures of `HttpResponse.from(future)` so I will skip this part. 😄 

For the second one, either way is fine for me. One thing I have to tell you is that 
I guess people do not use `future.isCancelled()` to check nowadays because `isCancelled()` is an old API from `Future` interface and people use `future.isCompletedExceptionally()` for `CompletableFuture`.

**Comment by ikhoon** [comment]
> How to cancel the future.

I think we should use `CompletableFuture.cancel(boolean)` to cancel a future because IIUC, it is the only way to cancel the upstream `Mono`.

**Comment by minwoox** [comment]
> I think we should use CompletableFuture.cancel(boolean) to cancel a future because IIUC, it is the only way to cancel the upstream Mono.

If so, then we don't have any choice. 😄

**Comment by ikhoon** [comment]
> If so, then we don't have any other choice. 😄

By the way, isn't it better to raise an issue to Reactor? If a future is completed exceptionally before a `Mono` produces a value,
the `Mono` should be cancelled. That means we can apply this as a workaround, but it needs to be fixed by the upstream.
@ks-yim What do you think about it?

**Comment by ks-yim** [comment]
@minwoox Thank you for correcting my understanding!
> That means we can apply this as a workaround, but it needs to be fixed by the upstream.
@ks-yim What do you think about it?

Sounds good to me. Let me fix the PR in that way! 😄

File: core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java [hunk 2]
```diff
@@ -107,6 +107,12 @@
 
         @Override
         public void onSubscribe(Subscription s) {
+            future.handle((ignored, t) -> {
+                if (t != null) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java:111]: Naming nit
```suggestion
            future.handle((ignored, cause) -> {
                if (cause != null) {
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 3]
```diff
@@ -310,21 +311,40 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exc
...
+                // Propagate cancellation to the upstream.
+                resFuture.handle((ignored, cause) -> {
+                    if (cause != null) {
+                        final CompletionStage<?> upstream = upstreamStage.get();
+                        if (upstream != null) {
+                            upstream.toCompletableFuture().completeExceptionally(cause);
+                        }
+                    }
+                    return null;
+                });
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:346]: Could these two `handle()` calls be merged into a single call? The semantic will change slightly (`upstream.completeExceptionally()` will be invoked before `resFuture` is completed, but maybe that's fine?

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 4]
```diff
@@ -610,7 +630,14 @@ public HttpResponse convertResponse(ServiceRequestContext ctx,
                 } catch (Exception e) {
                     return handleExceptionWithContext(exceptionHandler, ctx, ctx.request(), e);
                 }
-            }));
+            });
+            resFuture.handle((ignored, cause) -> {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:634]: Ditto - could merge two `handle()`s into one?

**Review by trustin — COMMENTED** [review]
Excellent work, @ks-yim!

File: core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java [hunk 5]
```diff
@@ -250,6 +250,7 @@ private void doCancel() {
             }
         } else {
             cancelPending = true;
+            abort(CancelledSubscriptionException.get());
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java:253]: Do we need this?
Isn't it enough to call `upstreamSubscription.cancel();` here?
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java#L387

File: core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java [hunk 6]
```diff
@@ -86,6 +86,10 @@ private static HttpResponseWriter aggregateFrom(CompletableFuture<?> future,
                                                     ResponseHeaders headers, HttpHeaders trailers,
                                                     Function<Object, HttpData> contentConverter) {
         final HttpResponseWriter writer = HttpResponse.streaming();
+        writer.whenComplete().handle((ignored, cause) -> {
+            future.completeExceptionally(cause);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java:90]: How about calling this only when `cause` is not null?

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java [hunk 7]
```diff
@@ -672,7 +672,7 @@ public void onError(Throwable t) {}
                     public void onComplete() {}
                 });
 
-        await().untilAsserted(() -> assertThat(subscriberCancelServiceCallCounter.get()).isEqualTo(3));
+        await().untilAsserted(() -> assertThat(subscriberCancelServiceCallCounter.get()).isEqualTo(1));
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java:675]: Could you explain why the value is changed from 3 to 1? 🤔

Comment (ks-yim) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java:675]: I wanted to asked you about this 😅..
After this PR, `DeferredStreamMessages`'s `completionFuture` completes as soon as it is cancelled and this makes `RetryingClient` stop retrying as it's caught in [this line](https://github.com/line/armeria/blob/27f1d605bea0874bf0bd68962f5e405812ba55fd/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L259) in `RetryingClient`.

File: core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java (hunk 6 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java:90]: My mistake, 😅 I will fix it. Thanks for catching this.

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java (hunk 7 above)
Comment (ks-yim) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java:675]: According to https://github.com/line/armeria/pull/1242, it seems `RetryingClient` should stop retrying if either `HttpRequest` or `HttpResponse` gets aborted.

Is there a reason why it shouldn't do so when `subscription.cancel()` is called?
Currently, calling `DeferredStreamMesages#cancel` doesn't complete its `completionFuture`  and it passes the test.

File: core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java (hunk 5 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java:253]: `upstreamSubscription` is lazily initialized, so it is null in the `else` block.
The conditional does null check for `upstreamSubscription`.

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java:253]: Oh,I got it wrong about the comment. 

`upstreamSubscription.cancel()` can never be called before the backing future completes, as the subscription gets lazily initialized once its backing future completes.

But, we may want to cancel the pending future before it completes once `DeferredStreamMessage` gets cancelled.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java:253]: > can never be called before the backing future completes, as the subscription gets lazily initialized once its backing future completes.

IIRC, that was the intention of the `DeferredStreamMessage` so that `upstream.cancel()` is propagated correctly when the `upstream` is set.
However, aborting the `DeferredStreamMessage` as soon as possible seems a good approach as well. 👍

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java (hunk 7 above)
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java:675]: Yeah, that should be one, I guess. 😄 
Could you also change the name of the test, please?

File: core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java [hunk 8]
```diff
@@ -50,9 +72,29 @@ void delegate(HttpResponse delegate) {
...
+        });
         stage.handle((delegate, thrown) -> {
             if (thrown != null) {
-                close(Exceptions.peel(thrown));
+                final Throwable cause = Exceptions.peel(thrown);
+                // Ignore exceptions caused by downstream cancellation.
+                if (cause instanceof CancelledSubscriptionException || cause instanceof CancellationException) {
+                    return null;
+                }
+                close(cause);
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java:97]: +1 It could be recursively trigged by the `whenComplete().handle((..., cause) -> ...)` above.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 3 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:346]: I've tried to find a way, but it seems the nature of `CompletableFuture` doesn't allow me to do that since its chaining only works from upstream to downstream.

Having `upstream.completeExceptionally()` within `composedFuture.handle(...)` and just returning `resFuture` didn't work since cancelling the `resFuture` doesn't trigger the callback attached to `composedFuture`.

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java (hunk 7 above)
Comment (ks-yim) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java]: Fixed!
I've also chosen to not use `await().untilAsserted(...)` since this will make it always pass the test regardless of how many retry will actually happen.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 3 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:346]: By the way, the `composedFuture` will be removed in the https://github.com/line/armeria/pull/3674/files#diff-a5b50e72b0031befe6de444cf1fc3d47c573cd73a65312068dd7ba99d440f8b1
How about preceding this PR after #3674 is merged. I will try to finish the PR as soon as possible. 💪

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:346]: @ikhoon I will, thanks for letting me know!

File: core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java]: Nice, fixed too!

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 3 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:346]: @ks-yim #3674 has been merged. Could you merge master and continue this PR? :bow:

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:346]: Thank you for your patience. It's your turn. 😉

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: @ikhoon @trustin Resolved the conflict, PATL! 🙏

File: core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java (hunk 5 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java:253]: Now that we abort `DeferredStreamMessage` even without its backing future completed, could we remove `cancelPending` flag and its related logic?

Build is successful even after I do so, but still not sure if there's any side effect.

File: core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java [hunk 9]
```diff
@@ -107,6 +107,12 @@
 
         @Override
         public void onSubscribe(Subscription s) {
+            future.handle((ignored, cause) -> {
+                if (cause != null) {
+                    s.cancel();
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java:112]: How about adding a boolean flag `onErrorCalled`? so that we don't unnecessarily call `s.cancel()`?

File: core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java (hunk 5 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java:253]: I have checked the execution flow and yeah we can remove the flag. 😉

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 10]
```diff
@@ -327,16 +328,37 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exc
             case KOTLIN_COROUTINES:
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:328]: Question: Do These changes also solve the Coroutines issue mentioned in #3690?
If so, could you add a test for it?

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:328]: It does seem to work as expected in my local build.
But, would you give me some advice where should I place the test? Maybe in `kotlin` module?

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 11]
```diff
@@ -327,16 +328,37 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exc
...
             case SCALA_FUTURE:
                 final CompletableFuture<?> composedFuture;
+                final AtomicReference<CompletionStage<?>> upstreamStage = new AtomicReference<>();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:331]: Could we remove `AtomicReference` if we create a response future early?
For example:
```java
final CompletableFuture<HttpResponse> responseFuture = new CompletableFuture<>();
...
composedFuture = f.thenCompose(
                            // Add a callback that cancels upstream future in `toCompletionStage(...)`
                            aReq -> toCompletionStage(invoke(ctx, req, aReq), ctx.eventLoop(), responseFuture));

composedFuture.handle((result, cause) -> {
    if (cause != null) {
        responseFuture.completeExceptionally(cause);
    } else {
        responseFuture.complete(convertResponse(ctx, null, result, HttpHeaders.of()));
    }
    return null;
});
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 10 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:328]: You can add tests any place under https://github.com/line/armeria/blob/97ee35c59560d44ab4529ba5d6916f47c572ec03/kotlin/src/test/kotlin/com/linecorp/armeria/server/ :-)

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 11 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: Awesome, looks more reasonable!

Refactored as per the suggestion!
But, I'd decided to introduce a separate method for cancellation propagation logic rather than having it into `toCompletionStage()`.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 10 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:327]: Test added!

File: core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java (hunk 9 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java:114]: Added the flag as per the suggestion.
I had the flag as a volatile field because `onError` may get called in a different thread than the subscription's thread.

Please, correct me if I am wrong 🙏.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java:114]: We don't need the volatile flag because the thread that calls `future.completeExceptionally(...)` also invokes `future.handle(...)`. 😉

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java:114]: Ah, callback is not executed in the subscription thread, thanks!!

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 12]
```diff
@@ -447,6 +459,21 @@ private ResponseHeaders setHttpStatus(ResponseHeadersBuilder headers) {
...
+    private static CompletionStage<?> cancelOnDownstreamException(
+            CompletionStage<?> upstream, CompletionStage<? extends HttpResponse> downstream) {
+        downstream.exceptionally(cause -> {
+            final CompletableFuture<?> upstreamFuture = upstream.toCompletableFuture();
+            if (!upstreamFuture.isDone()) {
+                upstreamFuture.completeExceptionally(cause);
+            }
+            return null;
+        });
+        return upstream;
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:474]: Question: should we remove https://github.com/line/armeria/pull/3691/files#diff-376b1094f9e3a90b5d82ef6a3799eb9e07bf0cf2a5b6e5921da9b10ce1c2154bR89-R94 in `ResponseConversionUtil.java` and https://github.com/line/armeria/pull/3691/files#diff-bd13fd7b1fbdc0f156dc2031491affde55933cb442ac1d2ab3480ac081fa643aR111 in `ObjectCollectingUtil.java` 
if we add a callback for `HttpResponse` here?
```suggestion
        downstream.handle((httpResponse, cause) -> {
            if (cause != null) {
	            final CompletableFuture<?> upstreamFuture = upstream.toCompletableFuture();
	            if (!upstreamFuture.isDone()) {
	                upstreamFuture.completeExceptionally(cause);
	            }
	            return null;
            }
            
            httpResponse.whenComplete().exceptionally(cause -> {
               // Cancel upstream
               ...
            });
            
        });
        return upstream;
```

**Review by trustin — APPROVED** [review]
Still LGTM

File: kotlin/src/test/kotlin/com/linecorp/armeria/server/SuspendingAnnotatedServiceTest.kt [hunk 13]
```diff
@@ -187,7 +197,20 @@ class SuspendingAnnotatedServiceTest {
                             return "OK"
                         }
                     })
+                    .annotatedService("/downstream-cancellation", object {
+                        @Get("/long-running-suspend-fun")
+                        suspend fun longRunningSuspendFun(): String {
+                            try {
+                                delay(10000L)
+                            } catch (e: CancellationException) {
+                                cancellationCallCounter.incrementAndGet()
```
Comment (ikhoon) [inline kotlin/src/test/kotlin/com/linecorp/armeria/server/SuspendingAnnotatedServiceTest.kt:206]: 👍

File: core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java [hunk 14]
```diff
@@ -100,18 +100,27 @@
...
         private final CompletableFuture<Object> future;
+        private boolean onErrorCalled;
 
         AbstractCollectingSubscriber(CompletableFuture<Object> future) {
             this.future = future;
         }
 
         @Override
         public void onSubscribe(Subscription s) {
+            future.exceptionally(ignored -> {
```
[the remark this answers is not in the document]
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java]: Added!

[the remark this answers is not in the document]
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java]: It's a question which is slightly off the topic here..
Which one should I prefer between `exceptionally` and `handle`?

It seems `cause` supplied to `exceptionally` is wrapped in `CompletionException` in some cases.

[the remark this answers is not in the document]
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java]: I'd prefer `handle` if it doesn't wrap the exception unlike `exceptionally`. Otherwise both are OK.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 12 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: I've tried but this doesn't seem to work😂 because `CompletionStage<HttpResponse>` will never be completed when the further downstream(e.g. `DeferredStreamMessage`) gets cancelled earlier.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: Checked and it was a wrong comment. 😅

File: core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java [hunk 15]
```diff
@@ -50,9 +70,28 @@ void delegate(HttpResponse delegate) {
...
+                if (MONO_TO_FUTURE_CLASS != null && MONO_TO_FUTURE_CLASS.isAssignableFrom(future.getClass())) {
+                    // A workaround for 'MonoToCompletableFuture' not propagating cancellation to the upstream
+                    // publisher when it completes exceptionally.
+                    future.cancel(true);
+                } else {
+                    future.completeExceptionally(cause);
+                }
+            }
+            return null;
+        });
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java:87]: How about extracting this method as an internal utility and also use it for others such as `ResponseConversionUtil`, `cancelOnDownstreamException()` and so on?
```java
class CompletableFutureUtil {
   
    static void propagateException(CompletableFuture<?> source, CompletionStage<?> target) {
        source.handle((unused, cause)) -> {
             ....
        })
    }
}

CompletableFutureUtil.propagateException(whenComplete(), stage);
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 16]
```diff
@@ -521,13 +551,20 @@ public HttpResponse convertResponse(ServiceRequestContext ctx,
...
                     return Exceptions.throwUnsafely(ex);
                 }
-            }));
+            });
+            resFuture.handle((ignored, cause) -> {
+                if (cause != null && !f.isDone()) {
+                    f.completeExceptionally(cause);
+                }
+                return null;
+            });
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: This might not catch an exception in `HttpResponse`
How about moving this into `f.thenApply(...)`?
```java
try {
    HttpResponse response = responseConverter.convertResponse(ctx, headers, aggregated, trailers);
    CompletableFutureUtil.propagateException(response.whenComplete(), f);
} catch (Exception ex) {
    if(!f.isDone()) {
        f.completeExceptionally(cause);
    }
}
```

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: Wouldn't [this change](https://github.com/line/armeria/pull/3691/files/4bd4e6327e6e0d28fb674c058e8340064b918832#diff-379aaf6327a539eea91e32b7f5393ce200dbc155f30edb6d04486140ecf3cad6R75-R87) in `DeferredHttpResponse` propagate exception from `HttpResponse`?

The propagation chain will be..:
`HttpResponse(DeferredHttpResponse)` -> `resFuture` -> `f` I guess?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: > The propagation chain will be..:

You are right. 👍 I missed that point.

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: And it seems moving the exception (back)propagation logic into `f.thenApply(...)` will not work since `thenApply(...)` callback is only triggered after `f` is completed but we are trying to complete `f` earlier before it would otherwise have completed.

File: core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java (hunk 15 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java:87]: Let me try! 😆

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 16 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: I can't help but agree.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: By the way, is it a more general way to cancel the upstream `CompletableFuture` or `Publisher`.
I don't see the several callbacks are maintainable. I am also concerned about performance degradation.
How about introducing a new API to `ResponseConverterFunction`? I'm not sure 100% that this is the right decision. 
```java
public interface ResponseConverterFunction {
    @Deprecate
    @CheckReturnValue
    HttpResponse convertResponse(ServiceRequestContext ctx,
                                 ResponseHeaders headers,
                                 @Nullable Object result,
                                 HttpHeaders trailers) throws Exception;

    // Add new API for supporting cancellation
    // `whenCancelled` will be injected from AnnotatedService
    @CheckReturnValue
    default HttpResponse convertResponse(
            ServiceRequestContext ctx, ResponseHeaders headers, @Nullable Object result,
            HttpHeaders trailers, CompletableFuture<Void> whenCancelled) throws Exception {
        return convertResponse(ctx, headers, result, trailers);
    }
}

// In ObjectCollectingUtil.java
// Use whenCancelled for cancel upstream publisher
public static CompletableFuture<Object> collectFrom(Publisher<?> publisher, CompletableFuture<Void> whenCancelled) {
    ...
}
```

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: Otherwise, we can use `ServiceRequestContext.whenRequestCancelling()` rather than introducing new API.

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: > is it a more general way to cancel the upstream CompletableFuture or Publisher.

Agree that it would be nice if we have a more general way to back-propagate cancellation.

There are 2 cases that we tried to fix in this PR.
* Converting `CompletableFuture` to `Publisher(HttpResponse)` - In `AnnotatedService` and `ResponseConversionUtil`.
  - +1 for using `ctx.whenCancelling()` or `HttpResponse.whenComplete()` rather than extending the `ResponseConverterFunction` API. But I doubt `ResponseConverterFunction` is the right place to put cancellation propagation logic since it won't be called until the future that we want to cancel gets completed.
  - (By the way, thanks for the insight! I didn't notice `ctx.whenRequestCancelling()` API 😆)

* Converting `Publisher<?>` to `CompletableFuture<?>`
  - Maybe this will giv
  - IMHO, it is as good as it is now, since we will almost always use `ObjectCollectingUtil.collectFrom(...)` in this case, and it already propagates cancellation to publisher if this PR is merged.

> I am also concerned about performance degradation.

Currently, 2~3 (depending on the return type) callbacks will be triggered for every request which could be non-trivial. I can't think of a good way to improve this in case of `FUTURE` or `COROUTINE` return type, but maybe there's a room for `Publisher` return type if we introduce a new method in `ObjectCollectinUtil` which returns another publisher after collecting elements from the source, just like `Mono.collect(...)` whose implementation doesn't rely on `CompletableFuture`.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:566]: > Collecting Publisher<?> to CompletableFuture<?>

IIUC, if `AbstractCollectingSubscriber` adds the cancellation callback on `ctx.whenRequestCancelling()` instead of the collection `future`, 
we could remove the lines 561 to 566 (https://github.com/line/armeria/pull/3691/files#diff-a5b50e72b0031befe6de444cf1fc3d47c573cd73a65312068dd7ba99d440f8b1R561-R566) in `AnnotatedService`.

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: @ikhoon Thanks for the idea, I've sent a new commit to check if I understood your points correctly, PTAL 🙏.
https://github.com/line/armeria/pull/3691/commits/5563f7f37cefd0a306307164f1b3645fb78ad4b9

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: Perfect! That is what I imagined. 💯

File: core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java [hunk 17]
```diff
@@ -239,6 +242,21 @@ void testStreamingError() {
...
+        @SuppressWarnings("unchecked")
+        final Subscriber<Object> subscriber = mock(Subscriber.class);
+        m.subscribe(subscriber, ImmediateEventExecutor.INSTANCE);
+        m.cancel();
+
+        final CompletableFuture<Void> completionFuture = m.whenComplete();
+        // completionFuture completes immediately upon cancellation.
+        assertThat(completionFuture.isCompletedExceptionally()).isTrue();
+        assertThatExceptionOfType(ExecutionException.class).isThrownBy(completionFuture::get)
+                .havingCause().isInstanceOf(CancelledSubscriptionException.class);
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java:257]: TIL

**Review by ikhoon — APPROVED** [review]
Thanks a lot for your hard work! @ks-yim

**Comment by ikhoon** [comment]
> ```
> Error: eckstyle] [ERROR] /home/verda-user/_work/armeria/armeria/core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java:87: Line is longer than 112 characters (found 114). [LineLength]
> Error: eckstyle] [ERROR] /home/verda-user/_work/armeria/armeria/core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java:60: Line is longer than 112 characters (found 117). [LineLength]
> ```
Please check lint errors.

**Review by minwoox — APPROVED** [review]
LGTM once @ikhoon's comment is addressed. 😉
Thanks!

File: core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java [hunk 18]
```diff
@@ -82,15 +85,20 @@
...
      * @param publisher publishes objects
+     * @param ctx {@link ServiceRequestContext}
      * @return a {@link CompletableFuture} which will complete when all published objects are collected
      */
-    public static CompletableFuture<Object> collectFrom(Publisher<?> publisher) {
+    @SuppressWarnings("unchecked")
+    public static CompletableFuture<Object> collectFrom(Publisher<?> publisher, ServiceRequestContext ctx) {
         requireNonNull(publisher, "publisher");
+        if (publisher instanceof StreamMessage) {
+            return (CompletableFuture<Object>) (CompletableFuture<?>) ((StreamMessage<?>) publisher).collect();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java:95]: It would be better to abort `StreamMessage` when cancelling.
```java
ctx.whenRequestCancelling().thenAccept(cause -> {
   ((StreamMessage<?>) publisher).abort(cause);
});
```

File: core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java [hunk 19]
```diff
@@ -82,15 +85,22 @@
...
+     * @param ctx {@link ServiceRequestContext}
      * @return a {@link CompletableFuture} which will complete when all published objects are collected
      */
-    public static CompletableFuture<Object> collectFrom(Publisher<?> publisher) {
+    @SuppressWarnings("unchecked")
+    public static CompletableFuture<Object> collectFrom(Publisher<?> publisher, ServiceRequestContext ctx) {
         requireNonNull(publisher, "publisher");
+        if (publisher instanceof StreamMessage) {
+            final StreamMessage<?> stream = (StreamMessage<?>) publisher;
+            ctx.whenRequestCancelling().thenAccept(cause -> stream.abort());
```
Comment (ks-yim) [inline core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java:96]:
```suggestion
            ctx.whenRequestCancelling().thenAccept(cause -> stream.abort(cause));
```
