### PR TITLE
Use a custom error response mapper for unframed requests

### LINKED ISSUE #3777: Use an `Content-type` header to encode an error mesasge in `UnframedGrpcService`
Currently, `UnframedGrpcService` returns an error message as plain text.
https://github.com/line/armeria/blob/54b70906bcd813f0b9b2c6715ad4086160ac49b2/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java#L255-L272
It would be nice to return a JSON object if the content type is JSON compatible.
```json
{ 
   "code": "FAILED_PRECONDITION",
   "message": "Input validation failed"
}
```

### PR DESCRIPTION
**Pull request by vivekkothari**
Motivation:

This will help users to customise the error response of a unframed gRPC service.

Modifications:

- I created a new utility class which contains the default mapper (which maps based on the current plaintext format)
- I also added a json based mapper.

Result:

- Closes #3777.
- When the PR is merged, the format of error would automatically change from plaintext to json if the `Content-Type` header is json compatible.

Test Result:

Before
Screenshot 2021-08-21 at 9 57 26 AM

After
Screenshot 2021-08-21 at 9 58 29 AM

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 1]
```diff
@@ -685,6 +701,7 @@ public GrpcService build() {
                 unsafeWrapRequestBuffers,
                 useClientTimeoutHeader,
                 maxInboundMessageSizeBytes);
-        return enableUnframedRequests ? new UnframedGrpcService(grpcService, handlerRegistry) : grpcService;
+        return enableUnframedRequests ? new UnframedGrpcService(grpcService, handlerRegistry,
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:704]: As you know `unframedErrorResponseMapper` is vaild only when unframed gRPC is enabled.
How about raisng an `IllegalStateException` if unframed gRPC is disabled.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 2]
```diff
@@ -288,6 +292,18 @@ public GrpcServiceBuilder intercept(Iterable<? extends ServerInterceptor> interc
         return this;
     }
 
+    /**
+     * Set a custom error response mapper. This is useful to serve custom response when using unframed gRPC
+     * service.
+     * @param unframedErrorResponseMapper The function which maps {@link HttpHeaders} to a {@link HttpResponse}.
+     */
+    public GrpcServiceBuilder unframedErrorResponseMapper(
+            Function<HttpHeaders, HttpResponse> unframedErrorResponseMapper) {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:301]: It would be useful to see `ServiceRequestContext` to handle an error.

How about introducing an interface to type safely take more values.
```java
public interface UnframedGrpcErrorHandler {
    static UnframedGrpcErrorHandler of() {
        // Implement the default handler using you did in `UnframedErrorResponseMappers`
        return DefaultUnframedGrpcErrorHandler.INSTANCE;
    }

    HttpResponse handler(ServiceRequestContext ctx, Status status, AggregatedHttpResponse response);
} 

class GrpcServiceBuilder {
    @Nullable
    UnframedGrpcErrorHandler unframedGrpcErrorHandler;

    public GrpcServiceBuilder unframedErrorHandler(UnframedGrpcErrorHandler unframedErrorHandler) {
       ...
    }
```
Addtionally, we can pass`UnframedGrpcErrorHandler.of()` to `UnframedGrpcService` by default when unframed is enabled.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedErrorResponseMappers.java [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+    static final Function<HttpHeaders, HttpResponse> JSON_UNFRAMED_RESPONSE_MAPPER = headers -> {
+        final String grpcStatusCode = headers.get(GrpcHeaderNames.GRPC_STATUS);
+        final Status grpcStatus = Status.fromCodeValue(Integer.parseInt(grpcStatusCode));
+        final HttpStatus httpStatus = GrpcStatus.grpcCodeToHttpStatus(grpcStatus.getCode());
+        final ImmutableMap.Builder<String, Object> builder =
+                ImmutableMap.<String, Object>builder()
+                            .put("code", grpcStatus.getCode().name())
+                            .put("http_status", httpStatus.code())
+                            .put("grpc_status", grpcStatusCode);
```
[the remark this answers is not in the document]
Comment (vivekkothari) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedErrorResponseMappers.java:66]: I can remove it

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 4]
```diff
@@ -645,6 +659,13 @@ public GrpcService build() {
                     new ArmeriaCoroutineContextInterceptor(useBlockingTaskExecutor);
             interceptors().add(coroutineContextInterceptor);
         }
+        if (!enableUnframedRequests && unframedGrpcErrorHandler != null) {
+            throw new IllegalStateException(
+                    "'unframedGrpcErrorHandler' can only be set if unframed requests are enabled");
+        }
+        if (unframedGrpcErrorHandler == null) {
+            unframedGrpcErrorHandler = UnframedGrpcErrorHandler.of();
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:667]: 👍

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+            if (grpcMessage != null) {
+                builder.put("message", grpcMessage);
+            }
+            final ResponseHeaders responseHeaders = ResponseHeaders.builder(httpStatus)
+                                                                   .contentType(MediaType.JSON_UTF_8)
+                                                                   .add(GrpcHeaderNames.GRPC_STATUS, grpcStatusCode)
+                                                                   .build();
+            return HttpResponse.ofJson(responseHeaders, builder.build());
+        };
+    }
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:67]: How about providing three types of factory methods?
- `of()` that automatically negotiates the content type generates either JSON or TEXT.
- `ofText()` always produces an error as plain text.
- `ofJson()` always produces an error as JSON.

We can set `of()` by default for users' convenience.

**Review by ikhoon — COMMENTED** [review]
Mostly looks good. :-)

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+            final ResponseHeaders responseHeaders = ResponseHeaders.builder(httpStatus)
+                                                                   .contentType(MediaType.PLAIN_TEXT_UTF_8)
+                                                                   .add(GrpcHeaderNames.GRPC_STATUS,
+                                                                        grpcStatusCode)
+                                                                   .build();
+            return HttpResponse.of(responseHeaders, HttpData.ofUtf8(message.toString()));
+        };
+    }
+
+    HttpResponse handler(ServiceRequestContext ctx, Status status, AggregatedHttpResponse response);
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:80]: `handle()`?
```suggestion
    HttpResponse handle(ServiceRequestContext ctx, Status status, AggregatedHttpResponse response);
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 7]
```diff
@@ -0,0 +1,81 @@
...
+            }
+            final ResponseHeaders responseHeaders = ResponseHeaders.builder(httpStatus)
+                                                                   .contentType(MediaType.JSON_UTF_8)
+                                                                   .add(GrpcHeaderNames.GRPC_STATUS, grpcStatusCode)
+                                                                   .build();
+            return HttpResponse.ofJson(responseHeaders, builder.build());
+        };
+    }
+
+    static UnframedGrpcErrorHandler ofPlain() {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:53]: Which one is better `ofPlain()` vs `ofText()`? 😄

**Review by ikhoon — COMMENTED** [review]
Thanks! everything is good except for the naming.
Let's listen to other folks' opinions!

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 8]
```diff
@@ -288,6 +291,17 @@ public GrpcServiceBuilder intercept(Iterable<? extends ServerInterceptor> interc
         return this;
     }
 
+    /**
+     * Set a custom error response mapper. This is useful to serve custom response when using unframed gRPC
+     * service.
+     * @param unframedGrpcErrorHandler The function which maps the error response to a {@link HttpResponse}.
+     */
+    public GrpcServiceBuilder unframedGrpcErrorHandler(UnframedGrpcErrorHandler unframedGrpcErrorHandler) {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:299]: Let's add `@UnstableApi`.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+import com.linecorp.armeria.common.MediaType;
+import com.linecorp.armeria.common.ResponseHeaders;
+import com.linecorp.armeria.common.grpc.protocol.GrpcHeaderNames;
+import com.linecorp.armeria.internal.common.grpc.GrpcStatus;
+import com.linecorp.armeria.server.ServiceRequestContext;
+
+import io.grpc.Status;
+
+@FunctionalInterface
+public interface UnframedGrpcErrorHandler {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:19]: Let's add `@UnstableApi`.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java (hunk 7 above)
Comment (vivekkothari) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:53]: I am bad with coming up with names

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java [hunk 10]
```diff
@@ -139,4 +140,17 @@ private static UnframedGrpcService buildUnframedGrpcService(BindableService bind
...
+        IllegalStateException exception = assertThrows(IllegalStateException.class, () ->
+                GrpcService.builder()
+                           .setMaxInboundMessageSizeBytes(MAX_MESSAGE_BYTES)
+                           .setMaxOutboundMessageSizeBytes(MAX_MESSAGE_BYTES)
+                           .supportedSerializationFormats(GrpcSerializationFormats.values())
+                           .enableUnframedRequests(false)
+                           .unframedGrpcErrorHandler(UnframedGrpcErrorHandler.of())
+                           .build());
+        assertThat(exception).hasMessage("'unframedGrpcErrorHandler' can only be set if unframed requests are enabled");
+    }
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java:155]: Could you add integration tests that a client receives either JSON or plain text depending on the `UnframedGrpcErrorHandler`?

Comment (vivekkothari) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java:155]: Can you point me to any existing integration tests if any?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java (hunk 7 above)
Comment (vivekkothari) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:53]: how about `ofPlainText`?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 11]
```diff
@@ -0,0 +1,120 @@
...
+ */
+@FunctionalInterface
+@UnstableApi
+public interface UnframedGrpcErrorHandler {
+
+    /**
+     * Returns a plain text or json response based on the content type.
+     */
+    static UnframedGrpcErrorHandler of() {
+        return (ctx, status, response) -> {
```
[the remark this answers is not in the document]
Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:45]: Please forget about the comment. 😅 
JVM optimizes creating a singleton when the lambda does not capture any parameters from its enclosing scope.

**Review by minwoox — COMMENTED** [review]
Thanks! Left some more comments. 😉

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+            final MediaType grpcMediaType = response.contentType();
```
[the remark this answers is not in the document]
Comment (vivekkothari) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:47]: should we return json response in that case?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+     * Returns a json response.
+     */
+    static UnframedGrpcErrorHandler ofJson() {
+        return (ctx, status, response) -> {
+            final HttpHeaders headers = !response.trailers().isEmpty() ?
+                                        response.trailers() : response.headers();
+            final Code grpcCode = status.getCode();
+            final HttpStatus httpStatus = GrpcStatus.grpcCodeToHttpStatus(grpcCode);
+            final ImmutableMap.Builder<String, Object> builder = ImmutableMap.builder();
+            builder.put("code", grpcCode.name());
```
[the remark this answers is not in the document]
Comment (vivekkothari) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:66]: @ikhoon suggested that since httpStatus is included in headers, its not needed.

[the remark this answers is not in the document]
Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:66]: If so, should we also remove the status from the plain response? 🤔

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:47]: Well, I'm not sure about this as well. It's probably okay to send the plain response because we were sending it. /cc @ikhoon

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:66]: > If so, should we also remove the status from the plain response? 🤔

+1 That sounds good.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:47]: I think gRPC clients will not try to parse if a status is non-OK.
So either way is fine to me. But I prefer JSON response because it is easier to parse if some clients need it.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 14]
```diff
@@ -0,0 +1,113 @@
...
+            final HttpStatus httpStatus = GrpcStatus.grpcCodeToHttpStatus(grpcCode);
+            final StringBuilder message = new StringBuilder("grpc-code: " + grpcCode.name());
+            final String grpcMessage = headers.get(GrpcHeaderNames.GRPC_MESSAGE);
+            if (grpcMessage != null) {
+                message.append(", ").append(grpcMessage);
+            }
+            final ResponseHeaders responseHeaders = ResponseHeaders.builder(httpStatus)
+                                                                   .contentType(MediaType.PLAIN_TEXT_UTF_8)
+                                                                   .add(GrpcHeaderNames.GRPC_STATUS,
+                                                                        String.valueOf(grpcCode.value()))
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:97]:
```suggestion
                                                                   .addInt(GrpcHeaderNames.GRPC_STATUS,
                                                                           grpcCode.value())
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 15]
```diff
@@ -0,0 +1,113 @@
...
+                                                                   .build();
+            return HttpResponse.of(responseHeaders, HttpData.ofUtf8(message.toString()));
+        };
+    }
+
+    /**
+     * Maps the gRPC error response to the http response.
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:104]:
```suggestion
     * Maps the gRPC error response to the {@link HttpResponse}.
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 16]
```diff
@@ -0,0 +1,113 @@
...
+     *
+     * @param ctx the service context.
+     * @param status the gRPC {@link Status} code.
+     * @param response the gRPC response.
+     *
+     * @return the http response.
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:110]:
```suggestion
     * @return the {@link HttpResponse}.
```

**Review by ikhoon — APPROVED** [review]
Thanks a lot! @vivekkothari 🚀
Left minor nits. :-)

**Comment by ikhoon** [comment]
Hmm... some tests seem not to be finished.

**Comment by ikhoon** [comment]
Could you fix lint errors?
```
Error: eckstyle] [ERROR] /home/verda-user/actions-runner/_work/armeria/armeria/grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java:146:31: Variable 'exception' should be declared final. [FinalLocalVariable]

Error: eckstyle] [ERROR] /home/verda-user/actions-runner/_work/armeria/armeria/grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java:154: Line is longer than 112 characters (found 120). [LineLength]
> Task :grpc:checkstyleTest
```

File: examples/grpc/src/main/java/example/armeria/grpc/HelloServiceImpl.java [hunk 17]
```diff
@@ -20,7 +21,11 @@
      */
     @Override
     public void hello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
-        responseObserver.onNext(buildReply(toMessage(request.getName())));
+        if (request.getName().isEmpty()) {
+            responseObserver.onError(Status.FAILED_PRECONDITION.withDescription("Name cannot be empty").asException());
+        } else {
+            responseObserver.onNext(buildReply(toMessage(request.getName())));
+        }
         responseObserver.onCompleted();
```
Comment (ikhoon) [inline examples/grpc/src/main/java/example/armeria/grpc/HelloServiceImpl.java:29]: `onCompleted()` might not be expected after `onError()`.
```suggestion
        if (request.getName().isEmpty()) {
            responseObserver.onError(Status.FAILED_PRECONDITION.withDescription("Name cannot be empty").asException());
        } else {
            responseObserver.onNext(buildReply(toMessage(request.getName())));
            responseObserver.onCompleted();
        }

```

**Comment by ikhoon** [comment]
Following tests were failed.
https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java#L190-L192
https://github.com/line/armeria/blob/b315183a2056c29780591eb49c7dc106e168b3f3/grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java#L99-L102

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java [hunk 18]
```diff
@@ -0,0 +1,113 @@
...
+     * Returns a json response.
+     */
+    static UnframedGrpcErrorHandler ofJson() {
+        return (ctx, status, response) -> {
+            final HttpHeaders headers = !response.trailers().isEmpty() ?
+                                        response.trailers() : response.headers();
+            final Code grpcCode = status.getCode();
+            final HttpStatus httpStatus = GrpcStatus.grpcCodeToHttpStatus(grpcCode);
+            final ImmutableMap.Builder<String, Object> builder = ImmutableMap.builder();
+            builder.put("code", grpcCode.name());
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java:66]: Let's use the same key `grpc-code` as we do in https://github.com/line/armeria/pull/3782/files#diff-e4a2f87a91362fd158f50fb15908d3e6878ce1bf6db39b364b991c6685b94237R89

**Review by minwoox — COMMENTED** [review]
Thanks! Just a couple of nits. 😄

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 19]
```diff
@@ -645,6 +661,13 @@ public GrpcService build() {
                     new ArmeriaCoroutineContextInterceptor(useBlockingTaskExecutor);
             interceptors().add(coroutineContextInterceptor);
         }
+        if (!enableUnframedRequests && unframedGrpcErrorHandler != null) {
+            throw new IllegalStateException(
+                    "'unframedGrpcErrorHandler' can only be set if unframed requests are enabled");
+        }
+        if (unframedGrpcErrorHandler == null) {
+            unframedGrpcErrorHandler = UnframedGrpcErrorHandler.of();
```
[the remark this answers is not in the document]
Comment (vivekkothari) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:669]: Fixed

**Review by minwoox — APPROVED** [review]
Thanks a lot for your work. 😄

**Review by trustin — APPROVED** [review]
:+1::+1::+1:
