### PR TITLE
Disable TLS v1.3 when using JdkSslContext

### LINKED ISSUE #1984: Do not enable `TLSv1.3` when the current `SSLEngine` does not support it.
For example, when a user is running Armeria on an old JDK without TLSv1.3 support *and* BoringSSL is not loaded, he or she will get the following exception:

```
[armeria-common-worker-epoll-2-1] WARN com.linecorp.armeria.server.HttpServerPipelineConfigurator - [id: 0xc833df45, L:/127.0.0.1:8080 - R:/127.0.0.1:46360] Unexpected exception:
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: TLSv1.3
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:475)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: TLSv1.3
	at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187)
	at sun.security.ssl.ProtocolList.convert(ProtocolList.java:84)
	at sun.security.ssl.ProtocolList.<init>(ProtocolList.java:52)
	at sun.security.ssl.SSLEngineImpl.setEnabledProtocols(SSLEngineImpl.java:2070)
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:341)
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:330)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:943)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:935)
	at io.netty.handler.ssl.SniHandler.newSslHandler(SniHandler.java:151)
	at io.netty.handler.ssl.SniHandler.replaceHandler(SniHandler.java:133)
	at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:114)
	at io.netty.handler.ssl.AbstractSniHandler.select(AbstractSniHandler.java:211)
	at io.netty.handler.ssl.AbstractSniHandler.decode(AbstractSniHandler.java:203)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	... 19 more
[armeria-common-worker-epoll-2-1] WARN com.linecorp.armeria.server.HttpServerPipelineConfigurator - [id: 0xc833df45, L:/127.0.0.1:8080 ! R:/127.0.0.1:46360] Unexpected exception:
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: TLSv1.3
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:475)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:408)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:375)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1416)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:816)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:331)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: TLSv1.3
	at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187)
	at sun.security.ssl.ProtocolList.convert(ProtocolList.java:84)
	at sun.security.ssl.ProtocolList.<init>(ProtocolList.java:52)
	at sun.security.ssl.SSLEngineImpl.setEnabledProtocols(SSLEngineImpl.java:2070)
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:341)
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:330)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:943)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:935)
	at io.netty.handler.ssl.SniHandler.newSslHandler(SniHandler.java:151)
	at io.netty.handler.ssl.SniHandler.replaceHandler(SniHandler.java:133)
	at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:114)
	at io.netty.handler.ssl.AbstractSniHandler.select(AbstractSniHandler.java:211)
	at io.netty.handler.ssl.AbstractSniHandler.decode(AbstractSniHandler.java:203)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	... 18 more
```

We could avoid enabling `TLSv1.3` when the current `SSLEngine` implementation we are going to use does not support it.

See: https://github.com/line/armeria/blob/44a7e1291c34fa4f6a1f2ae1b876129676b61f19/core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java#L66-L78

### PR DESCRIPTION
**Pull request by rmohta**
Motivation:
  Netty's JdkSslContext does not support TLSv1.3. Armeria should disable TLS v1.3 when using JdkSslContext. 

Result:
  Fixes #1984

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java [hunk 1]
```diff
@@ -65,20 +65,31 @@
...
-                  .protocols(DEFAULT_PROTOCOLS.toArray(new String[0]));
-
-        builder.ciphers(DEFAULT_CIPHERS, SupportedCipherSuiteFilter.INSTANCE);
-
+        if (Flags.useOpenSsl()) {
+            builder.sslProvider(SslProvider.OPENSSL)
+                   .protocols(DEFAULT_PROTOCOLS.toArray(new String[0]));
+            builder.ciphers(DEFAULT_CIPHERS, SupportedCipherSuiteFilter.INSTANCE);
+        } else {
+            //Netty's JdkSslContext does not support TLSv1.3 by default. In future when it does, we will update.
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: Thanks for helping with this! Actually JDK enginre does support it on Java 11+ and we should continue to enable that.

I think you can instead inspect the actual supported protocols using a pattern like this one

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/Flags.java#L286

Comment (rmohta) [reply core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: @anuraaga Yes, JDK 11 has TLSv1.3. Looking at https://github.com/netty/netty/blob/ee8206cb2615e1b4e843cf9e52781fdcf2de85f4/handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java#L107, TLSv1.3 is not enabled by default.

Comment (rmohta) [reply core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: Should I check - use JdkEngine and running JDK 11, then enable TLSv1.3. Anything else, disable TLSv1.3

Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: I don't think you should need to worry about whether or is JDK or 11.

With similar code to the link I gave, you can create a SSLContext, and check the `supportedProtocols`. On Java 8, this should not include TLSv1.3 whole on Java 11 it would.

Comment (rmohta) [reply core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: @anuraaga I have updated the code. Can you please check? Testing it on JDK 11, it shows below message. 
`[main] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1]`

File: core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java [hunk 2]
```diff
@@ -65,20 +71,45 @@
...
                                               boolean forceHttp1,
                                               Consumer<? super SslContextBuilder> userCustomizer) {
         final SslContextBuilder builder = sslContextSupplier.get();
 
-        builder.sslProvider(Flags.useOpenSsl() ? SslProvider.OPENSSL : SslProvider.JDK)
-                  .protocols(DEFAULT_PROTOCOLS.toArray(new String[0]));
-
-        builder.ciphers(DEFAULT_CIPHERS, SupportedCipherSuiteFilter.INSTANCE);
-
+        if (Flags.useOpenSsl()) {
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: We don't need to branch on this flag since the below check will still work correctly for openssl and is more precise. Basically, we want to do feature detection instead of version detection.

File: core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java [hunk 3]
```diff
@@ -65,20 +71,45 @@
...
+            builder.sslProvider(SslProvider.OPENSSL)
+                   .protocols(DEFAULT_PROTOCOLS.toArray(new String[0]))
+                   .ciphers(DEFAULT_CIPHERS, SupportedCipherSuiteFilter.INSTANCE);
+        } else {
+            try {
+                // use this to determine actual supported protocols.
+                final SslContextBuilder jdkBuilder = sslContextSupplier.get();
+                final SSLEngine jdkEngine = jdkBuilder.build().newEngine(ByteBufAllocator.DEFAULT);
+                builder.sslProvider(SslProvider.JDK)
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: Let's set `protocols` to something like

```java

Set<String> supportedProtocols = ImmutableSet.copyOf(engine.supportedProtocols());
DEFAULT_PROTOCOLS.stream().filter(protocol -> supportedProtocols.contains(protocols)).toArray(String[]:new);
```

Comment (rmohta) [reply core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: @anuraaga I am a bit confused. `SslContextUtil` is the builder for for `SSLEngine` & we are using `SSLEngine` to detect feature in `SslContextUtil`. This looks to be cyclic check. May be SSLContextUtil should not set protocol and cipherSuite, thereby relying on SSLEngine defaults. Sorry, if this discussion is going in circle.

**Comment by trustin** [comment]
I'd like to make this fix a part of todays 0.90.1 release. Let me add some commits to address @anuraaga's comments.

File: core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java (hunk 3 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java]: Address the comment by creating an `SSLEngine` with the default settings to get the support protocol list and filter.

File: CONTRIBUTING.md [hunk 4]
```diff
@@ -35,7 +35,7 @@ After importing the project, import the IDE settings as well.
 #### IntelliJ IDEA
 
 - [`settings.jar`](https://raw.githubusercontent.com/line/armeria/master/settings/intellij_idea/settings.jar) -
-  See [Importing settings from a JAR archive](https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html#23c8afba).
+  See [Import settings from a ZIP archive](https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html#7a4f08b8).
```
Comment (trustin) [inline CONTRIBUTING.md]: Thanks, @rmohta !

**Comment by anuraaga** [comment]
Thanks!

**Comment by trustin** [comment]
Thanks, @rmohta and others.
