### PR TITLE
Make DNS resolver handle timeout correctly when querying AAAA & A…

### LINKED ISSUE #2664: DNS resolver may throws IllegalStateException when client is not using IPv4 only
When we have ipv4, ipv6 DNS query, 
If DNS query timeout is shorter than retry failed of DNS query, the cancels mechanism of DefaultDnsNameResolver at https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java#L145 will set aggregatedPromise to failed. 
But due to it also calls promises' cancel method. At https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java#L86 will enter with Future of CancelException and try to set aggregatedPromise again and throw IllegalStateException.

### PR DESCRIPTION
**Pull request by kojilin**
… records at same time

If one of the DNS query timeouts when resolver sends A/AAAA queries together, the resolver will have IllegalStateException internally and return DnsTimeoutException. The resolver should return resolved one instead of return error.

Modifications:
* Return DNS timeout exception only when all the queries are not completed yet.
* Make result follow the preferred order

Result:
* Fixes #2664

### CODE REVIEW

**Comment by kojilin** [comment]
looks like we use same timeout for netty and RefreshingAddressResolver, so the test is flaky.

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java [hunk 1]
```diff
@@ -140,9 +148,8 @@ private void configureTimeout(List<DnsQuestion> questions, String logPrefix,
             final DnsTimeoutException exception = new DnsTimeoutException(
                     '[' + logPrefix + "] " + questions + " are timed out after " +
                     queryTimeoutMillis + " milliseconds.");
-            result.setFailure(exception);
             promises.forEach(promise -> {
-                promise.cancel(true);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: We should cancel the `promise` to stop sending DNS queries internally. https://github.com/netty/netty/pull/10171/files#diff-6107a6de600a6f941beb29f082976653R357
Is there any reason that `DnsTimeoutException` shouldn't be propagated to the caller?

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: I change back to cancel, one reason I delete DnsTimeoutException in here is that it will trigger `operationComplete` with CancellationException. When we have A & AAAA queries, we may have A query sucess but AAAA query failed, it will call `aggregatedPromise.setSuccess` and throws IllegalStateException. So I move the `DnsTimeoutException` to `operationComplete`.

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java [hunk 2]
```diff
@@ -96,12 +89,22 @@ public void operationComplete(Future<List<DnsRecord>> future) throws Exception {
 
                 if (--remaining == 0) {
                     if (!records.isEmpty()) {
+                        if (records.size() > 1) {
+                            final List<DnsRecordType> preferredOrder =
+                                    questions.stream().map(DnsRecord::type).collect(toImmutableList());
+                            records.sort(Comparator.comparingInt(
+                                    record -> preferredOrder.indexOf(record.type())));
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:96]: Thanks for this!

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java (hunk 1 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: Then how about just using `try(Success|failure)`? Becuase we can't be sure that the `CancellationException` is triggered by our side. (i.e. `DnsNameResolver` could cancel it internally)

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: Originally I have the same idea..
But it can't allow one of the request success.
If one of A/AAAA success, we still return DnsTimeoutException. or we need to check all the future again here.

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java [hunk 3]
```diff
@@ -96,12 +89,22 @@ public void operationComplete(Future<List<DnsRecord>> future) throws Exception {
 
                 if (--remaining == 0) {
                     if (!records.isEmpty()) {
+                        if (records.size() > 1) {
+                            final List<DnsRecordType> preferredOrder =
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:93]: I think we always have a fixed set of types, so since this is an internal class we could pass them to the constructor and only do this once. Can also use Ordering.explicit

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java (hunk 1 above)
Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: Curious you mean tryFailure instead of canceling? or make listener using  `try(Success|failure)`?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: > or make listener using try(Success|failure)?

Yes, that's what I meant. 😄

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: But then, we always failed when one of A/AAAA is succeed.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: Yes, as you said, if the query succeeded after the timeout, we are still going to get timeout, but I think it's ok. 😄

Comment (kojilin) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: I mean one of the query succeed, e.g. A is before timeout and AAAA is timeout.
Now I change to check if all of the query promises are done or not.

**Comment by kojilin** [comment]
updated.

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java (hunk 1 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java:145]: > I mean one of the query succeeds before timeout, e.g. A is before timeout and AAAA is timeout.

Ah, I completely missed that. Thanks!
