### PR TITLE
Resolve `WildcardType` to get upper bound

### LINKED ISSUE #4007: `AnnotatedService` can't use wildcard type for parameters
When I use a wildcard type for parameter like as follows, `AnnotatedService` is failed to initialize due to `Unsupported or invalid parameter type: ?`:

```java
@Get("/wildcard")
public String wildcard(RequestContext ctx, @Param List<? extends Object> container) {
    return ctx.path();
}
```

It'd be ok for Java users since they may not use like the above. However, for Kotlin, it isn't when they use an interface as a generic type. IMHO, this is because Kotlin changes the type to the upper-bounded wildcard type. This is the reproducible code:
```kotlin
class AnnotatedService {
    @Get("/")
    fun foo(@Param("values") values: List<MyInterface>): String {
        return "Hello, $values!";
    }
}

interface MyInterface
```

Here's the stack trace:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported or invalid parameter type: ? extends MyInterface
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.toRawType(AnnotatedValueResolver.java:1254)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.getElementType(AnnotatedValueResolver.java:1216)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.build(AnnotatedValueResolver.java:1090)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.access$800(AnnotatedValueResolver.java:924)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.ofQueryParam(AnnotatedValueResolver.java:524)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.of(AnnotatedValueResolver.java:420)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.of(AnnotatedValueResolver.java:378)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.lambda$of$3(AnnotatedValueResolver.java:319)
```

### PR DESCRIPTION
**Pull request by ghkim3221**
Motivation:

When I use a wildcard type for parameter like as follows, `AnnotatedService` is failed to initialize due to `Unsupported or invalid parameter type: ?`:

```java
@Get("/wildcard")
public String wildcard(RequestContext ctx, @Param List<? extends Object> container) {
    return ctx.path();
}
```

It'd be ok for Java users since they may not use like the above. However, for Kotlin, it isn't when they use an interface as a generic type. IMHO, this is because Kotlin changes the type to the upper-bounded wildcard type. This is the reproducible code:
```kotlin
class AnnotatedService {
    @Get("/")
    fun foo(@Param("values") values: List<MyInterface>): String {
        return "Hello, $values!";
    }
}

interface MyInterface
```

Modifications:

- Resolve `WildcardType` to get the first upper bound when getting the raw type in annotated services' `@Param`s.

Result:

- Closes #4007
- Users can use upper-bounded wildcard type as a `@Param` in annotated services.
  - Especially Kotlin users can use interface as a generic type.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java [hunk 1]
```diff
@@ -1250,6 +1251,9 @@ private static Type unwrapOptional(Type parameterizedType) {
             if (type instanceof ParameterizedType) {
                 return (Class<?>) ((ParameterizedType) type).getRawType();
             }
+            if (type instanceof WildcardType) {
+                return (Class<?>) ((WildcardType) type).getUpperBounds()[0];
+            }
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:1256]: * Check the length of `getUpperBounds()` before accessing the first element?
* Could we also consider a generic `TypeVariable` such as `<T extends Foo> foo(@Param List<T> foo)`?

**Review by minwoox — APPROVED** [review]
LGTM, once @ikhoon's comment is addressed. 😄

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java (hunk 1 above)
Comment (ghkim3221) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java]: > Check the length of getUpperBounds() before accessing the first element?

👍 `IllegalArgumentException` is better than `IndexOutOfBoundException`.

 > Could we also consider a generic TypeVariable such as `<T extends Foo> foo(@Param List<T> foo)`?

I added resolving `TypeVariable`. But what do I do when bounds are multiple such as `<T extends Foo | Comparable> foo(@Param List<T> foo)`? Retrofit had the same thought and resolved to `Object`: https://github.com/square/retrofit/blob/963af06c02a8ae8193037ccaa597b5091ba95e06/retrofit/src/main/java/retrofit2/Utils.java#L88-L92

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java]: > But what do I do when bounds are multiple such as <T extends Foo | Comparable> foo(@Param List<T> foo)

It makes sense to support a single bound.

**Review by ikhoon — APPROVED** [review]

**Comment by ikhoon** [comment]
> eckstyle] [ERROR] /home1/www/_work/armeria/armeria/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:61:8: Unused import - com.google.common.collect.Iterables. [UnusedImports]

Could you check the lint error?

**Comment by ghkim3221** [comment]
> Could you check the lint error?

Ooops 😅 Thanks!

**Review by trustin — APPROVED** [review]
Much appreciated, @ghkim3221 ! :bow:

**Review by jrhee17 — APPROVED** [review]
💯 Looks great! Thank you! 🙇 👍 🎉
