### PR TITLE
Fix `IllegalReferenceCountException` in `TwoElementFixedStreamMessage`

### LINKED ISSUE #1687: `IllegalReferenceCountException` in `TwoElementFixedStreamMessage`?
Found this:

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
 at io.netty.buffer.AbstractReferenceCountedByteBuf.toLiveRealCnt(AbstractReferenceCountedByteBuf.java:190)
 at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:142)
 at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:133)
 at com.linecorp.armeria.unsafe.ByteBufHttpData.release(ByteBufHttpData.java:119)
 at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
 at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
 at com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.cleanupObjects(TwoElementFixedStreamMessage.java:57)
 at com.linecorp.armeria.common.stream.FixedStreamMessage.cleanup(FixedStreamMessage.java:70)
 at com.linecorp.armeria.common.stream.FixedStreamMessage.notifySubscriberOfCloseEvent(FixedStreamMessage.java:129)
 at com.linecorp.armeria.common.stream.FixedStreamMessage.cleanup(FixedStreamMessage.java:66)
 at com.linecorp.armeria.common.stream.FixedStreamMessage.cancelOrAbort(FixedStreamMessage.java:163)
 at com.linecorp.armeria.common.stream.FixedStreamMessage.cancel(FixedStreamMessage.java:135)
 at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.cancel(AbstractStreamMessage.java:275)
 at com.linecorp.armeria.common.stream.DeferredStreamMessage.doCancel(DeferredStreamMessage.java:206)
 at com.linecorp.armeria.common.stream.DeferredStreamMessage.cancel(DeferredStreamMessage.java:196)
 at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.cancel(AbstractStreamMessage.java:275)
 at com.linecorp.armeria.server.HttpResponseSubscriber.lambda$write$1(HttpResponseSubscriber.java:360)
 at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
 at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
 at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
 at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
 at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
 at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
 at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:57)
 at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31)
 at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
 at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
 at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
 at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
 at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
 at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:380)
 at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryFailure(Http2CodecUtil.java:301)
 at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
 at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:709)
 at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:294)
 at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:646)
 at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:749)
 at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:951)
 at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:514)
 at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:906)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1370)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:739)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:731)
 at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:717)
 at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:739)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:731)
 at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:717)
 at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:206)
 at io.netty.handler.flush.FlushConsolidationHandler.flush(FlushConsolidationHandler.java:140)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:739)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:731)
 at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:717)
 at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:739)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:731)
 at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:717)
 at com.linecorp.armeria.internal.TrafficLoggingHandler.flush(TrafficLoggingHandler.java:49)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:739)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:731)
 at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:717)
 at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:201)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:739)
 at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:731)
 at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:717)
 at com.linecorp.armeria.server.HttpResponseSubscriber.write(HttpResponseSubscriber.java:366)
 at com.linecorp.armeria.server.HttpResponseSubscriber.onNext(HttpResponseSubscriber.java:243)
 at com.linecorp.armeria.server.HttpResponseSubscriber.onNext(HttpResponseSubscriber.java:51)
 at com.linecorp.armeria.common.stream.FilteredStreamMessage$FilteringSubscriber.onNext(FilteredStreamMessage.java:196)
 at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onNext(DeferredStreamMessage.java:305)
 at com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.doNotifyObject(TwoElementFixedStreamMessage.java:122)
 at com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.doNotify(TwoElementFixedStreamMessage.java:110)
 at com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.doRequest(TwoElementFixedStreamMessage.java:72)
 at com.linecorp.armeria.common.stream.FixedStreamMessage.request(FixedStreamMessage.java:88)
 at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:269)
 at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onSubscribe(DeferredStreamMessage.java:298)
 at com.linecorp.armeria.common.stream.FixedStreamMessage.subscribe(FixedStreamMessage.java:115)
 at com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:72)
 at com.linecorp.armeria.common.stream.DeferredStreamMessage.safeOnSubscribeToDelegate(DeferredStreamMessage.java:261)
 at com.linecorp.armeria.common.stream.DeferredStreamMessage.delegate(DeferredStreamMessage.java:115)
 at com.linecorp.armeria.common.DeferredHttpResponse.delegate(DeferredHttpResponse.java:39)
 at com.linecorp.armeria.common.HttpResponse.lambda$from$0(HttpResponse.java:72)
 at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
 at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
 at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
 at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
 at com.linecorp.armeria.server.thrift.THttpService.respond(THttpService.java:703)
 at com.linecorp.armeria.server.thrift.THttpService.handleSuccess(THttpService.java:665)
 at com.linecorp.armeria.server.thrift.THttpService.lambda$invoke$4(THttpService.java:623)
 at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
 at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
 at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
 at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:110)
 at com.linecorp.armeria.server.thrift.THttpService.invoke(THttpService.java:611)
 at com.linecorp.armeria.server.thrift.THttpService.decodeAndInvoke(THttpService.java:580)
 at com.linecorp.armeria.server.thrift.THttpService.lambda$doPost$3(THttpService.java:434)
 at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
 at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
 at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
 at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
 at com.linecorp.armeria.common.HttpMessageAggregator.apply(HttpMessageAggregator.java:151)
 at com.linecorp.armeria.common.HttpMessageAggregator.apply(HttpMessageAggregator.java:36)
 at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
 at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
 at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:745) 
```

Server setup:

https://github.com/line/centraldogma/blob/422cec92ab1b4999e52277097883bacd4c15292e/server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java#L560-L573

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
We should assign `null` to fields in `TwoElementFixedStreamMessage` before calling
`Subscriber.onNext()` as we do in `OneElementFixedStreamMessage` and `RegularElementFixedStreamMessage`.

Modification:
- Assign `null` to fields before calling `Subscriber.onNext()`.

Misc:
- Remove `EventLoopStreamMessage`.

Result:
- Close #1687
- `IllegalReferenceCountException` is no longer raised when using `TwoElementFixedStreamMessage`.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/stream/EventLoopStreamMessage.java [hunk 1]
```diff
@@ -1,467 +0,0 @@
...
- * removing the need for most synchronization from the hot path. This should satisfy standard cases when using
- * Armeria. It is not required for writes or reads to use the provided {@link EventLoop} but in such a case, it
- * will be significantly faster to use {@link DefaultStreamMessage}.
- *
- * <p>Note that when {@link Subscription#cancel()} or {@link #abort()} are called from a different thread, the
- * stream will continue to signal objects until demand is satisfied, rather than stopping in the middle. If this
- * is an issue, it is recommended to use {@link DefaultStreamMessage}.
- */
-// NB: Methods in this class prefixed with 'do' must be run on the stream's event loop.
-public class EventLoopStreamMessage<T> extends AbstractStreamMessageAndWriter<T> {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/EventLoopStreamMessage.java]: Thanks :-)
