### PR TITLE
Provide a way to recover a failed `StreamMessage`

### LINKED ISSUE #3719: `RequestLog` with `ContentPreviewingService` is not ended when `HttpStatusException` is thrown
When `ContentPreviewingService` is used, request is not ended if the request fails while routing. `LoggingClient` logs only request and `armeria.server.active.requests` meter increase.

With a little digging, I found that the problem occurred when `service.serve` in `HttpServerHandler` fails with `HttpStatusException`. Because `HttpStatusException` is not set to the `raisedException` not to log as cause, `HttpResponseSubscriber` is created with null `primaryCause`:
https://github.com/line/armeria/blob/9a66de992195a6f1d2fe11c798e9b1a1e31464b4/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L408-L412

So this response is ended without `primaryCause `: 
https://github.com/line/armeria/blob/9a66de992195a6f1d2fe11c798e9b1a1e31464b4/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L552-L558

Null `responseCause` can be problem when `RequestLog` is deferred with `RESPONSE_CONTENT` or `RESPONSE_CONTENT_PREVIEW` because their flags are not cleared:
https://github.com/line/armeria/blob/9a66de992195a6f1d2fe11c798e9b1a1e31464b4/core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java#L1320-L1326

So `whenComplete` futures are not satisfied and not completed. I think this is why the `RequestLog` is not ended.

But I don't have any good idea yet to fix while keeping not logging `HttpStatusException` 😅

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

We don't have a general way to handle a failed `StreamMessage` and
`HttpResponse`. It would be nice to recover or resume
a failed stream with a fallback function which returns a new stream.

Modifications:

- Recoverable `StreamMessage`.
  - Add `StreamMessage.recoverAndResume(Function)` that resumes a failed
    `StreamMessage` with a fallback `StreamMessage`.
  - `HttpResponse.recover(Function)` that recovers a failed
    `HttpResponse` with a fallback `HttpResponse` only when non-transient
    objects were written before.
  - Add `RecoverableStreamMessage` that recovers or resumes a failed
    `StreamMessage` with a fallback function.
  - Add `AbortedStreamMessage` as a light-weight implementation for
    a failed `StreamMessage`.
    - `AbortedHttpResponse` is also added together.
  - Move `SubscriptionArbiter` to the internal package.
    - Make `SubscriptionArbiter` executed in an event loop.
- Migrate the existing error handling code.
  - Attach the default exception handler by default to the `HttpResponse` returned by
    a service chaining in `HttpServerHandler`.
  - Remove exception handling code in `HttpResponseSubcriber`.
  - Clean up scattered error handling code in `AnnotatedService`.
    - Use `HttpResponse.recover()` right before returning an `HttpResponse`.
    - `ExceptionFilteredHttpResponse` and
      `ExceptionFilteredHttpResponseDecorator` have been removed.
  - Consolidate the default annotated service's exception handler and 
    the global exception handler.
    - `server.annotation.DefaultExceptionHandler` has been removed.
    - `server.DefaultExceptionHandler` is newly added.
- Breaking
  - `ExceptionHandler` now returns `HttpResponse` instead of
	`AggregatedHttpReponse`.
	```java
	// Before:
	ExceptionHandler handler = (ctx, cause) -> {
	    if (cause instanceof IllegalArgumentException) {
	        return AggregatedHttpResponse.of(HttpStatus.BAD_REQUEST);
	    }
	    return null;
	}
	  
	// After:
	ExceptionHandler handler = (ctx, cause) -> {
	    if (cause instanceof IllegalArgumentException) {
	        return HttpResponse.of(HttpStatus.BAD_REQUEST); // 👈👈👈
	    }
	    return null;
	}
	```
  - `ResponseConverterFunctionProvider.createResponseConverterFunction(Type,ResponseConverterFunction,ExceptionHandlerFunction)`
    has been removed in favor of 
    `ResponseConverterFunctionProvider.createResponseConverterFunction(Type,ResponseConverterFunction)`.
    - The exception handler is now applied automatically.
- Deprecation
  - `-Dcom.linecorp.armeria.annotatedServiceExceptionVerbosity` and 
    `c.l.a.server.annotation.ExceptionVerbosity` has been deprecated.
     - Use `LoggingService` or log exceptions using `ServerBuilder.exceptionHandler()`
  - `ObservableResponseConverterFunction(ResponseConverterFunction,ExceptionHandlerFunction)`
    has been deprecated in favor of `ObservableResponseConverterFunction(ResponseConverterFunction)`.
  - `HttpResponseException.of(HttpStatus)` and `HttpResponseException(int)` has been deprecated in favor of `HttpStatusException`.  
- Bug fixes
  - Reset a stream if `ServiceRequestContext.cancel()` is called.
    - Previously 503 Service Unavailable is returned.
  - Fixes #3719
  - An `IllegalArgumentException` raised in annotated service will be logged by `LoggingService` by default.
    - It was logged only when `c.l.a.server.annotation.ExceptionVerbosity` is higher than `UNHANDLED`
  - An HTTP/1 service now correctly returns 404 Not Found even though a request content is too large.
- Revert #3054 and properly handle `HttpResponseException` and `HttpStatusException` with `DefaultRequestLog`. 
- Allow creating an `HttpResponseException` which a cause.

Result:

- New features
  - You can now resume a failed `StreamMessage` with a fallback
    `StreamMessage`.
    ```java
    DefaultStreamMessage<Integer> stream = new DefaultStreamMessage<>();
    stream.write(1);
    stream.write(2);
    stream.close(new IllegalStateException("Oops...");
    StreamMessage<Integer> resumed = stream.recoverAndResume(cause -> StreamMessage.of(3, 4));

    assert resumed.collect().join().equals(List.of(1, 2, 3, 4));
    ```
  - You can now recover a failed `HttpResponse` with a fallback
    `HttpResponse`. It would be useful for handing an error of 
    `HttpResponse` in a decorator.
    ```java
    HttpResponse response = HttpResponse.ofFailure(new IllegalStateException("Oops..."));
    // The failed HttpResponse will be recovered by the fallback function.
    HttpResponse recovered = response.recover(cause -> HttpResponse.of("Fallback"));
    assert recovered.aggregate().join().contentUtf8().equals("Fallback");
    ```
  - You can now create `HttpResponseException` with a cause.

- Bug fixes
  - You no longer see an incomplete `RequestLog` when an `HttpStatusException` is raised.
  - You no longer see `ClosedSessionException` when a large content is sent to an invalid path.
  - A request is now reset when `ServiceRequestContext.cancel()` is called.
  - An `IllegalArgumentException` raised in annotated service is correctly logged by `LoggingService` by default.
- Deprecation  
  - `-Dcom.linecorp.armeria.annotatedServiceExceptionVerbosity` and
    `c.l.a.server.annotation.ExceptionVerbosity` has been deprecated.
    - Use `LoggingService` or log exceptions using `ServerBuilder.exceptionHandler()`.
  - `ObservableResponseConverterFunction(ResponseConverterFunction,ExceptionHandlerFunction)`
    has been deprecated in favor of `ObservableResponseConverterFunction(ResponseConverterFunction)`.
  - `HttpResponseException.of(HttpStatus)` and `HttpResponseException(int)` has been deprecated in favor of `HttpStatusException`.
- Breaking changes
  - See the modifications.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 1]
```diff
@@ -629,4 +628,32 @@ default HttpResponse mapTrailers(Function<? super HttpHeaders, ? extends HttpHea
         });
         return of(stream);
     }
+
+    /**
+     * Recovers a failed {@link HttpResponse} by switching to a returned fallback {@link StreamMessage}
+     * when any error occurs before an {@link HttpHeaders} is written.
+     * Note that the failed {@link HttpResponse} cannot be recovered from an error if an {@link HttpHeaders}
+     * was written already.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:636]:
```suggestion
     * Recovers a failed {@link HttpResponse} by switching to a returned fallback {@link HttpResponse}
     * when any error occurs before a {@link ResponseHeaders} is written.
     * Note that the failed {@link HttpResponse} cannot be recovered from an error if a {@link ResponseHeaders}
     * was written already.
```

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 2]
```diff
@@ -629,4 +628,32 @@ default HttpResponse mapTrailers(Function<? super HttpHeaders, ? extends HttpHea
...
+     * HttpResponse recovered = response.recover(cause -> HttpResponse.of("Fallback"));
+     * assert recovered.aggregate().join().contentUtf8().equals("Fallback");
+     *
+     * // As HTTP headers and body were written already before an error occurred,
+     * // the fallback function could not be applied for the failed HttpResponse.
+     * HttpResponseWriter response = HttpResponse.streaming();
+     * response.write(ResponseHeaders.of(HttpStatus.OK));
+     * response.write(HttpData.ofUtf8("Hello"));
+     * response.close(new IllegalStateException("Oops..."));
+     * HttpResponse notRecovered = response.recover(cause-> HttpResponse.of("Fallback"));
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:650]:
```suggestion
     * HttpResponse notRecovered = response.recover(cause -> HttpResponse.of("Fallback"));
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 3]
```diff
@@ -527,4 +527,23 @@ default EventExecutor defaultSubscriberExecutor() {
...
+     * DefaultStreamMessage<Integer> stream = new DefaultStreamMessage<>();
+     * stream.write(1);
+     * stream.write(2);
+     * stream.close(new IllegalStateException("Oops...");
+     * StreamMessage<Integer> resumed = stream.resume(cause -> StreamMessage.of(3, 4));
+     *
+     * assert resumed.collect().join().equals(List.of(1, 2, 3, 4));
+     * }</pre>
+     */
+    default StreamMessage<T> resume(Function<? super Throwable, ? extends StreamMessage<T>> function) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:545]: `resume` doesn't convey its behavior that recovers from an exception. How about renaming to `recoverAndResume()`?

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 4]
```diff
@@ -454,75 +427,6 @@ private ResponseHeaders setHttpStatus(ResponseHeadersBuilder headers) {
         return CompletableFuture.completedFuture(obj);
     }
 
-    /**
-     * Returns a {@link Function} which produces an {@link HttpService} wrapped with an
-     * {@link ExceptionFilteredHttpResponseDecorator}.
-     */
-    public Function<? super HttpService, ? extends HttpService> exceptionHandlingDecorator() {
-        return ExceptionFilteredHttpResponseDecorator::new;
-    }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:463]: :clap::clap::clap:

File: core/src/main/java/com/linecorp/armeria/server/ExceptionHandler.java [hunk 5]
```diff
@@ -82,7 +84,7 @@ static ExceptionHandler ofDefault() {
      * @see #orElse(ExceptionHandler)
      */
     @Nullable
-    AggregatedHttpResponse convert(ServiceRequestContext context, Throwable cause);
+    HttpResponse convert(ServiceRequestContext context, Throwable cause);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ExceptionHandler.java:87]: :clap::clap::clap:

File: core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java [hunk 6]
```diff
@@ -419,6 +410,16 @@ private void handleRequest(ChannelHandlerContext ctx, DecodedHttpRequest req) th
                     req.close();
                 }
             }
+
+            serviceResponse = serviceResponse.recover(cause -> {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java:414]: We didn't wrap the response returned by a service before. What'd be the performance impact of this? Could you share some benchmark results?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java:414]: I also considered the performance impact. 

> Could you share some benchmark results?

Sure, let me check the performance with some success and failure cases.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java:404]: I ran benchmarks and the working branch seems like having 2~3% overhead.
I am going to profile and find room for optimization.
* Working branch
  * HttpService
  ```
  go-wrk -M GET -c 10 -d 30 http://127.0.0.1:8080/http
  Running 30s test @ http://127.0.0.1:8080/http
    10 goroutine(s) running concurrently
  1194483 requests in 29.492190824s, 151.51MB read
  Requests/sec:		40501.67
  Transfer/sec:		5.14MB
  Avg Req Time:		246.903µs
  Fastest Request:	58.389µs
  Slowest Request:	128.902189ms
  Number of Errors:	0
  ```
  * Annotated service
	```
	go-wrk -M GET -c 10 -d 30 http://127.0.0.1:8080/anno/
	Running 30s test @ http://127.0.0.1:8080/anno/
	  10 goroutine(s) running concurrently
	1143563 requests in 29.512220953s, 145.05MB read
	Requests/sec:		38748.80
	Transfer/sec:		4.91MB
	Avg Req Time:		258.072µs
	Fastest Request:	60.938µs
	Slowest Request:	126.904941ms
	Number of Errors:	0
	```
* Master branch
	* HttpService
  ```
  go-wrk -M GET -c 10 -d 30 http://127.0.0.1:8080/http
  Running 30s test @ http://127.0.0.1:8080/http
    10 goroutine(s) running concurrently
  1220807 requests in 29.477914933s, 154.85MB read
  Requests/sec:		41414.29
  Transfer/sec:		5.25MB
  Avg Req Time:		241.462µs
  Fastest Request:	57.35µs
  Slowest Request:	125.217814ms
  Number of Errors:	0
  ```
	* Annotated service
  ```
  go-wrk -M GET -c 10 -d 30 http://127.0.0.1:8080/anno/
  Running 30s test @ http://127.0.0.1:8080/anno/
    10 goroutine(s) running concurrently
  1212290 requests in 29.479147698s, 153.77MB read
  Requests/sec:		41123.64
  Transfer/sec:		5.22MB
  Avg Req Time:		243.169µs
  Fastest Request:	57.252µs
  Slowest Request:	64.730558ms
  Number of Errors:	0
  ```

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java [hunk 7]
```diff
@@ -60,91 +56,81 @@
...
-        if (subscription != noopSubscription) {
-            subscription = newSubscriptionUpdater.getAndSet(this, noopSubscription);
-            if (subscription != noopSubscription) {
-                if (subscription != null) {
-                    subscription.cancel();
-                }
-            }
+        if (newSubscription == null) {
+            newSubscription = noopSubscription;
+        } else if (newSubscription != NoopSubscription.get()) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java:129]:
```suggestion
        } else if (newSubscription != noopSubscription) {
```

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java [hunk 8]
```diff
@@ -191,18 +176,18 @@ final void drain() {
 
         do {
             // Get snapshots from volatile values and initialize them
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java:178]: this is not volatile anymore?

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java [hunk 9]
```diff
@@ -191,18 +176,18 @@ final void drain() {
...
-            long newReq = newRequested;
+            final long newReq = newRequested;
             if (newReq != 0L) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java:180]: How about removing this if branch because assigning 0 is cheaper than having this branch?

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java [hunk 10]
```diff
@@ -191,18 +176,18 @@ final void drain() {
...
-                newReq = newRequestedUpdater.getAndSet(this, 0L);
+                newRequested = 0;
             }
-            long newProd = newProduced;
+            final long newProd = newProduced;
             if (newProd != 0L) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java:184]: ditto.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 11]
```diff
@@ -149,11 +141,16 @@
                       method.getDeclaringClass().getSimpleName(), method.getName());
         isKotlinSuspendingMethod = KotlinUtil.isSuspendingFunction(method);
         this.resolvers = requireNonNull(resolvers, "resolvers");
-        exceptionHandler =
-                new CompositeExceptionHandlerFunction(object.getClass().getSimpleName(), method.getName(),
-                                                      requireNonNull(exceptionHandlers, "exceptionHandlers"));
+
+        requireNonNull(exceptionHandlers, "exceptionHandlers");
+        if (exceptionHandlers.isEmpty()) {
+            exceptionHandler = NoopExceptionHandlerFunction.INSTANCE;
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:147]: Can't we just assign `null` instead of defining `NoopExceptionHandlerFunction` and using it?

File: core/src/main/java/com/linecorp/armeria/server/DefaultExceptionHandler.java [hunk 12]
```diff
@@ -0,0 +1,81 @@
...
+import org.slf4j.LoggerFactory;
+
+import com.linecorp.armeria.common.Flags;
+import com.linecorp.armeria.common.HttpResponse;
+import com.linecorp.armeria.common.HttpStatus;
+import com.linecorp.armeria.common.util.Exceptions;
+import com.linecorp.armeria.internal.server.annotation.AnnotatedService;
+
+/**
+ * A default exception handler is used when a user does not specify an {@link ExceptionHandler}. It returns:
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/DefaultExceptionHandler.java:30]: nit:
```suggestion
 * A default exception handler that is used when a user does not specify an {@link ExceptionHandler}. It returns:
```

File: core/src/main/java/com/linecorp/armeria/server/ExceptionHandler.java (hunk 5 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/ExceptionHandler.java:70]: Awesome!

**Review by minwoox — COMMENTED** [review]
It's much simplified now. Thanks! 😉

File: core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java (hunk 6 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java:404]: When HttpHeaders cache(#3714) is applied, `HttpResponse.recover()` does not seem to have performance regression.
Some benchmarks show better performance than the master branch, thanks to  HttpHeaders cache(#3714).
| branch | service | Requests/sec | Transfer/sec | Avg Req Time | Fastest Request | Slowest Request | Number of Errors | 
| ------ | ------- | ------------ | ------------ | ------------ | --------------- | --------------- | ---------------- |  
| recover | HttpService | 42926.76 | 5.44MB | 232.954µs | 57.712µs | 108.570215ms | 0|
| recover | HttpService | 42353.22 | 5.37MB | 236.109µs | 54.949µs | 114.236967ms | 0|
| recover | HttpService | 43605.76 | 5.53MB | 229.327µs | 57.688µs | 124.909328ms | 0|
| recover | Annotated service | 41665.45 | 5.28MB | 240.007µs | 60.026µs | 84.9303ms|
| recover | Annotated service | 41119.65 | 5.22MB | 243.192µs | 57.256µs | 126.482998ms | 0|
| recover | Annotated service | 41406.57 | 5.25MB | 241.507µs | 59.819µs | 125.234891ms | 0|
| master | HttpService | 42112.26 | 5.34MB | 237.46µs | 54.834µs | 127.838011ms | 0|
| master | HttpService | 42256.39 | 5.36MB | 236.65µs | 56.247µs | 110.931958ms | 0|
| master | HttpService | 42108.98 | 5.34MB | 237.479µs | 58.551µs | 123.010129ms | 0|
| master | Annotated service | 41324.97 | 5.24MB | 241.984µs | 59.693µs | 114.15864ms | 0|
| master | Annotated service | 40893.37 | 5.19MB | 244.538µs | 60.023µs | 82.101197ms | 0|
| master | Annotated service | 41360.49 | 5.25MB | 241.776µs | 59.42µs | 103.278116ms | 0|

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java [hunk 13]
```diff
@@ -0,0 +1,263 @@
...
+        return completionFuture;
+    }
+
+    @Override
+    public void subscribe(Subscriber<? super T> subscriber, EventExecutor executor,
+                          SubscriptionOption... options) {
+        requireNonNull(subscriber, "subscriber");
+        requireNonNull(executor, "executor");
+        requireNonNull(options, "options");
+        this.executor = executor;
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java:112]: I didn't think of the case. How about setting the `executor` when `RecoverableSubscriber.onSubscribe()`?
Actually, I'd like to minimize the overhead of `RecoverableStreamMessage`. Every `HttpResponse` of 
server-side is wrapped with `RecoverableStreamMessage` before they are written to a channel.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 11 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:147]: +1 That is also a good idea.

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java]: > How about setting the executor when RecoverableSubscriber.onSubscribe()
is called?

Yeah, that's a good idea. We need to move that logic. 😄

[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java]: Finally, I removed `executor` and added `abortCause` to prevent a race condition `onError()` and `abort()`.

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java [hunk 14]
```diff
@@ -0,0 +1,263 @@
...
+            this.executor = executor;
+            this.options = options;
+        }
+
+        @Override
+        public void onSubscribe(Subscription s) {
+            setUpstreamSubscription(s);
+            if (!errorHandled) {
+                downstream.onSubscribe(this);
+            }
```
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java:186]: Thanks for the explanation. 😉

**Comment by minwoox** [comment]
https://github.com/line/armeria/pull/3674/checks?check_run_id=3142694048#step:6:2779

Oops, could you check the failure? 😉

**Comment by ikhoon** [comment]
> [#3674 (checks)](https://github.com/line/armeria/pull/3674/checks?check_run_id=3142694048#step:6:2779)
> 
> Oops, could you check the failure? 😉

😱😱😱

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java [hunk 15]
```diff
@@ -60,91 +56,81 @@
...
-                return;
-            }
-            final long updated = LongMath.saturatedAdd(current, n);
-            if (updater.compareAndSet(this, current, updated)) {
-                return;
-            }
+    private void request0(long n) {
+        if (newRequested < Long.MAX_VALUE) {
+            newRequested = LongMath.saturatedAdd(newRequested, n);
         }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java:112]: `if` is redundant:
```suggestion
        newRequested = LongMath.saturatedAdd(newRequested, n);
```

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java [hunk 16]
```diff
@@ -60,91 +56,81 @@
...
     }
 
     @Override
     public void cancel() {
-        // Swap newSubscription with NoopSubscription and call cancel() on any previous Subscription held.
-        Subscription subscription = newSubscription;
+        if (executor.inEventLoop()) {
+            doCancel();
+        } else {
+            executor.execute(this::cancel);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java:121]:
```suggestion
            executor.execute(this::doCancel);
```

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 17]
```diff
@@ -33,42 +35,63 @@
...
     public static HttpResponseException of(HttpResponse httpResponse) {
-        return new HttpResponseException(httpResponse);
+        return new HttpResponseException(httpResponse, null);
+    }
+
+    /**
+     * Returns a new {@link HttpResponseException} instance with the specified {@link HttpResponse} and
+     * {@link Throwable}.
+     */
+    public static HttpResponseException of(HttpResponse httpResponse, Throwable cause) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java:81]:
```suggestion
    public static HttpResponseException of(HttpResponse httpResponse, @Nullable Throwable cause) {
```

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 18]
```diff
@@ -33,42 +35,63 @@
...
     public static HttpResponseException of(AggregatedHttpResponse aggregatedResponse) {
-        return of(requireNonNull(aggregatedResponse, "aggregatedResponse").toHttpResponse());
+        return of(requireNonNull(aggregatedResponse, "aggregatedResponse").toHttpResponse(), null);
+    }
+
+    /**
+     * Returns a new {@link HttpResponseException} instance with the specified {@link AggregatedHttpResponse}
+     * and {@link Throwable}.
+     */
+    public static HttpResponseException of(AggregatedHttpResponse aggregatedResponse, Throwable cause) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java:66]:
```suggestion
    public static HttpResponseException of(AggregatedHttpResponse aggregatedResponse, @Nullable Throwable cause) {
```

File: core/src/main/java/com/linecorp/armeria/server/ServerConfig.java [hunk 19]
```diff
@@ -620,12 +623,27 @@ public boolean isDateHeaderEnabled() {
...
+    /**
+     * Returns the {@link ExceptionVerbosity} logged by services. The value of this property
+     * is one of the following:
+     * <ul>
+     *     <li>{@link ExceptionVerbosity#ALL} - logging all exceptions raised from services</li>
+     *     <li>{@link ExceptionVerbosity#UNHANDLED} - logging exceptions which are not handled by
+     *     {@link ExceptionHandler}s provided by a user and are not well-known exceptions
+     *     <li>{@link ExceptionVerbosity#NONE} - no logging exceptions</li>
+     * </ul>
+     * A log message would be written at {@code WARN} level.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ServerConfig.java:641]: If the default behavior is `NONE`, should we need this feature at all? A user could specify his/her own `ExceptionHandler` that logs all or certain exceptions they are interested in, e.g.

```java
Server
  .builder()
  .exceptionHandler((ctx, cause) -> {
    // .. log ..
    return ExceptionHandler.ofDefault().convert(ctx, cause);
  })
```

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/ServerConfig.java:641]: Nice suggestion. I guess most users prefer to use `LoggingService` and `ExceptionVerbosity` is seldom used. Let me remove `ExceptionVerbosity` and make it only working with annotated services for backward compatibility.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/ServerConfig.java:641]: Sounds good to me too.

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java (hunk 16 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java:121]: Oops... 😱

File: core/src/main/java/com/linecorp/armeria/server/ServerConfig.java (hunk 19 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/ServerConfig.java]: `ServerBuilder.exceptionVerbosity()` has been removed at https://github.com/line/armeria/pull/3674/commits/bd833a3acad30dcaa27df2bf0d4e5c00746d4c9b.

**Review by trustin — APPROVED** [review]

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 20]
```diff
@@ -601,14 +499,11 @@ public HttpResponse convertResponse(ServiceRequestContext ctx,
             }
 
             assert f != null;
-            return HttpResponse.from(f.handle((aggregated, cause) -> {
-                if (cause != null) {
-                    return handleExceptionWithContext(exceptionHandler, ctx, ctx.request(), cause);
-                }
+            return HttpResponse.from(f.thenApply(aggregated -> {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:502]: Question: Just wanted to make sure that this is working even the `f` is completed exceptionally. Right?

File: core/src/main/java/com/linecorp/armeria/server/DefaultExceptionHandler.java [hunk 21]
```diff
@@ -0,0 +1,110 @@
...
+            // A stream has been cancelled. No need to send a response with a status.
+            return HttpResponse.ofFailure(cause);
+        }
+
+        if (cause instanceof RequestTimeoutException) {
+            return HttpResponse.ofFailure(HttpStatusException.of(HttpStatus.SERVICE_UNAVAILABLE, cause));
+        }
+
+        if (isAnnotatedService && needsToWarn() && !Exceptions.isExpected(cause)) {
+            logger.warn("{} Unhandled exception from an service:", context, cause);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/DefaultExceptionHandler.java:100]: nit: 
```suggestion
            logger.warn("{} Unhandled exception from a service:", context, cause);
```

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/AbortedStreamMessage.java [hunk 22]
```diff
@@ -0,0 +1,103 @@
...
+        return completionFuture;
+    }
+
+    @Override
+    public void subscribe(Subscriber<? super T> subscriber, EventExecutor executor,
+                          SubscriptionOption... options) {
+        requireNonNull(subscriber, "subscriber");
+        requireNonNull(executor, "executor");
+        requireNonNull(options, "options");
+        if (!subscribedUpdater.compareAndSet(this, 0, 1)) {
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/AbortedStreamMessage.java:73]: If it is fine that `whenComplete()` could be completed before subscribed, it is possible.
Do you think it does not violate our `StreamMessage`'s specification?

[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/AbortedStreamMessage.java:73]: That's actually why I asked. 😆
Let's keep it as it is now and make a change later if we need.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 23]
```diff
@@ -454,101 +435,21 @@ private ResponseHeaders setHttpStatus(ResponseHeadersBuilder headers) {
...
             this.functions = ImmutableList.copyOf(functions);
         }
 
         @Override
         public HttpResponse handleException(ServiceRequestContext ctx, HttpRequest req, Throwable cause) {
             final Throwable peeledCause = Exceptions.peel(cause);
 
-            if (Flags.annotatedServiceExceptionVerbosity() == ExceptionVerbosity.ALL &&
-                logger.isWarnEnabled()) {
-                logger.warn("{} Exception raised by method '{}' in '{}':",
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:548]: Ah, good point. Let me revert it.

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java [hunk 24]
```diff
@@ -0,0 +1,279 @@
...
+                return true;
+            }
+            return fallbackStream.isOpen();
+        } else {
+            final StreamMessage<T> fallbackStream = this.fallbackStream;
+            if (fallbackStream == null) {
+                return false;
+            }
+            return fallbackStream.isOpen();
+        }
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java:83]: Much simpler! 👍

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 20 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:502]: If `f` is completed exceptionally, the exception is propagated to the returned `HttpResponse`.
https://github.com/line/armeria/blob/6f21290a3e6e3bb2af22d8a9061d472dcabda545/core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java#L54-L56

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 23 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:548]: By the way, if users do not specify an exception, this `exceptionHandler` will not be invoked. 
Let me use `mapError` for that case.

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/AbortedStreamMessage.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/AbortedStreamMessage.java:73]: OK, let me try later. I believe it is possible. 
That could enhance performance.

File: core/src/main/java/com/linecorp/armeria/common/Flags.java [hunk 25]
```diff
@@ -1150,7 +1151,11 @@ public static String dnsCacheSpec() {
      * to override the default value.
      *
      * @see ExceptionVerbosity
+     *
+     * @deprecated Use {@link LoggingService} or log exceptions using
+     *             {@link ServerBuilder#exceptionHandler(com.linecorp.armeria.server.ExceptionHandler)}.
      */
+    @Deprecated
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/Flags.java:1158]: We don't have to deprecate this anymore because it's actually used?

**Review by minwoox — APPROVED** [review]
Just one nit. Thanks a lot!

File: core/src/main/java/com/linecorp/armeria/common/Flags.java (hunk 25 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/common/Flags.java:1158]: According to this discussion(https://github.com/line/armeria/pull/3674#discussion_r676595119), 
I thought we decided not to recommend using `ExceptionVerbosity`. I wonder `annotatedServiceExceptionVerbosity` is useful in the real world.
@KarboniteKream @ks-yim Any thought on this?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/Flags.java:1158]: > According to this discussion(#3674 (comment)),

Isn't it about the `ExceptionVerbosity` that we have tried to newly introduce in this PR?
Users can achieve the same behavior using `exceptionHandler` so we revert it.
However, Isn't `annotatedServiceExceptionVerbosity` different? At least, it's used some places so I wonder if we can remove it someday. 🤔

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/common/Flags.java:1158]: Perhaps, we can remove it Armeria 2.0.
I thought it is awkward to support exception verbosity only for annotated service. That was the reason I added exception verbosity to a `SeverBuilder`

**Comment by trustin** [comment]
@ikhoon Could you update the PR description to match what we have now?

File: core/src/main/java/com/linecorp/armeria/common/Flags.java (hunk 25 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/Flags.java:1158]: Had a chat with @ikhoon and we decide to remove this from Armeria 2.0
because users can check the exception using `LoggingSerivce` by this change: https://github.com/line/armeria/pull/3674/commits/39f25996291727edb181e3e3750f2e1a2f739288

**Comment by ikhoon** [comment]
> @ikhoon Could you update the PR description to match what we have now?

Updated!

**Comment by ikhoon** [comment]
The build failure will be fixed once #3704 is merged.

**Comment by ikhoon** [comment]
Thanks for the awesome reviews! ❤️
