### PR TITLE
Extract grpc-status from responseContent when not in headers/trailers

### LINKED ISSUE #6606: grpc-status not recorded in RequestLog when client cancels (RST_STREAM)
## Description

When a gRPC client cancels a request (e.g., deadline exceeded → RST_STREAM), the `grpc-status` is not available in `RequestLog.responseHeaders()` or `RequestLog.responseTrailers()`, making the grpc status code come up as null or UNKNOWN in logs + metrics.

However, `RequestLog.responseCause()` correctly contains the `ClosedStreamException`. 

Per the [gRPC HTTP/2 spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses):

> Implementations must synthesize a Status & Status-Message to propagate to the application layer when this occurs.

**Question**: Should Armeria synthesize the `grpc-status` from `responseCause()` when trailers cannot be sent? Or is this expected behavior and consumers should derive the status themselves?

## Steps to Reproduce

1. Create a gRPC server using Armeria with `GrpcService`
2. Have the server handler include a delay (e.g., `delay(500ms)`)
3. Use `grpcurl` with a short deadline to call the endpoint:
   grpcurl -max-time 0.1 -plaintext localhost:8080 your.service/YourMethod
4. Client deadline expires → client sends RST_STREAM
5. Check `RequestLog` in access log writer or metrics decorator

## Expected Behavior

`RequestLog` should contain `grpc-status: 1` (CANCELLED) somewhere accessible, either:
- In `responseTrailers()` (synthesized even if not sent on wire)
- Or derivable via `GrpcMeterIdPrefixFunction` for metrics

## Actual Behavior

| RequestLog Field | Value |
|------------------|-------|
| `responseHeaders().get("grpc-status")` | `null` |
| `responseTrailers().get("grpc-status")` | `null` |
| `responseCause()` | `ClosedStreamException` ✓ |

The `grpc-status` is empty/missing in both access logs and metrics collected via `GrpcMeterIdPrefixFunction`.

## Environment

- Armeria version: 1.31.3
- Java version: 
- OS:

### PR DESCRIPTION
**Pull request by sallylyen**
## Motivation

When a client cancels a gRPC request (e.g., via RST_STREAM), the grpc-status may not be present in response headers or trailers, causing metrics to be recorded with UNKNOWN status.

Resolves #6606

## Modifications

- Added fallback in `GrpcMeterIdPrefixFunction` to extract grpc-status from `responseContent` using `Status.fromThrowable()`
- Added integration test for client cancellation scenario

## Result

- gRPC metrics now correctly record the status when client cancels
- Closes #6606

### CODE REVIEW

File: grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunctionTest.java [hunk 1]
```diff
@@ -229,5 +270,18 @@ public void unaryCall2(SimpleRequest request, StreamObserver<SimpleResponse> res
             responseObserver.onNext(SimpleResponse.getDefaultInstance());
             responseObserver.onCompleted();
         }
+
+        @Override
+        public void unaryCallWithAllDifferentParameterTypes(
+                ExtendedTestMessage request, StreamObserver<ExtendedTestMessage> responseObserver) {
+            try {
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunctionTest.java]: nit; as event loops are shared across tests within a single jvm fork, rescheduling instead of sleeping may help with test flakiness overall.

e.g. 
```java
            final ServiceRequestContext ctx = ServiceRequestContext.current();
            ctx.eventLoop().schedule(() -> {
                responseObserver.onNext(ExtendedTestMessage.getDefaultInstance());
                responseObserver.onCompleted();
            }, 1, TimeUnit.SECONDS);
```

File: grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunctionTest.java [hunk 2]
```diff
@@ -182,6 +187,35 @@ void unaryCall2(SerializationFormat serializationFormat) {
...
+        final TestServiceFutureStub client =
+                GrpcClients.builder(server.uri(SessionProtocol.H2C, GrpcSerializationFormats.PROTO))
+                           .factory(clientFactory)
+                           .decorator(MetricCollectingClient.newDecorator(
+                                   GrpcMeterIdPrefixFunction.of("client")))
+                           .build(TestServiceFutureStub.class);
+
+        final ClientRequestContext ctx;
+        try (ClientRequestContextCaptor captor = Clients.newContextCaptor()) {
+            final ListenableFuture<ExtendedTestMessage> future =
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunctionTest.java]: This unfortunately fails due to how `shadedTest` works in our codebase at the moment.
You may need to either:
- Avoid using `*FutureStub` in tests
- Or move the added test to a module without the `relocate` flag (i.e. `:it:grpc:java`)

**Review by jrhee17 — COMMENTED** [review]
Changes look good once CI passes

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunction.java [hunk 3]
```diff
@@ -113,6 +114,21 @@ private static void addGrpcStatus(ImmutableList.Builder<Tag> tagListBuilder, Req
...
+        // Check responseContent for gRPC status when headers/trailers
+        // don't contain grpc-status (e.g., when client cancels via RST_STREAM)
+        final Object responseContent = log.responseContent();
+        if (responseContent instanceof RpcResponse) {
+            final RpcResponse rpcResponse = (RpcResponse) responseContent;
+            if (rpcResponse.isCompletedExceptionally()) {
+                final Throwable cause = rpcResponse.cause();
+                if (cause != null) {
+                    final Status grpcStatus = Status.fromThrowable(cause);
+                    tagListBuilder.add(statusTag(String.valueOf(grpcStatus.getCode().value())));
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunction.java]:
```suggestion
                    tagListBuilder.add(statusTag(StringUtil.toString(grpcStatus.getCode().value())));
```

**Comment by sallylyen** [comment]
@minwoox @jrhee17 is there anything else that needs to be done before this can be merged? Hoping to get this out as part of the 1.37.0 release

**Comment by jrhee17** [comment]
Sorry, I've been off for the past week. We'll try to include this in the next release which will probably be at the end of the month. ping @minwoox
