### PR TITLE
Warn when pushing a wrong context using ContextFuture

### LINKED ISSUE #2173: `RequestContextAwareCompletableFuture` callback not invoked when context mismatches.
Let's say we have the following code:

```java
ServiceRequestContext ctx1 = ServiceRequestContext.of(...);
ServiceRequestContext ctx2 = ServiceRequestContext.of(...);
try (SafeCloseable sc1 = ctx1.push()) {
    CompletableFuture f = ctx2.makeContextAware(new CompletableFuture());
    AtomicBoolean callbackCalled = new AtomicBoolean();
    f.whenComplete((res, cause) -> callbackCalled.set(true));

    f.complete(null);    

    // The callback will never be invoked and
    // the following assertion will fail.
    assert callbackCalled.get(); // <-- Failure!
}
```

It seems like everything is working as expected. The callback (`BiConsumer`) was not invoked because it was decorated by `ctx2.makeContextAware(BiConsumer)` and the callback is invoked only when `ctx2.pushIfAbsent()` succeeds ([see](https://github.com/line/armeria/blob/armeria-0.94.0/core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java#L138)), to protect our users from the accidental context conflict like the above example.

The problem is that a user does not have a way to know this happened. It is really confusing because the callback will *never* be invoked. It is neither possible to handle the `IllegalStateException` raised by `pushIfAbsent()`:

```java
f.whenComplete((res, cause) -> callbackCalled.set(true))
 .exceptionally(cause -> {
     // We never reach here, either, because this callback
     // will be decorated again and fail at `pushIfAbsent()` again.
     ...
 });
```

What would be the best way to let a user know about this problem?

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
Related #2173

In that case, which is trying to push a wrong context when the current thread had an unrelated context already, the `RequestContextAwareCompletableFuture` just swallows the exception and a user has no way what is going wrong.

Modification:
- Leave a warning log every time a wrong context is pushed to let the user something is going wrong.

Result:
- You can now easily get noticed when pushing the wrong context.
- Close #2173

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/internal/ContextFutureCallbackArgumentsProvider.java [hunk 1]
```diff
@@ -0,0 +1,263 @@
...
+
+    @Override
+    public Stream<? extends Arguments> provideArguments(ExtensionContext context) throws Exception {
+        final Arguments thenApply = Arguments.of(
+                (BiConsumer<CompletableFuture<?>, AtomicBoolean>) (future, called) -> {
+                    future.thenApply(res -> {
+                        called.set(true);
+                        return null;
+                    }).exceptionally(cause -> {
+                        called.set(true);
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/internal/ContextFutureCallbackArgumentsProvider.java]: This is not called because in `exceptionally`, pushing with a wrong context happens as well.
I'm wondering we should mitigate this by not pushing the context in `exceptionally`. 🤔

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java [hunk 2]
```diff
@@ -545,7 +545,10 @@ public String toString() {
             return strVal;
         }
 
-        final StringBuilder buf = new StringBuilder(96);
+        final StringBuilder buf = new StringBuilder(117);
+        buf.append('[')
+           .append(ClientRequestContext.class.getSimpleName())
+           .append(']');
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java]: Could we make it much shorter? It will increase the amount of our logs by large margin.

File: core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+    }
+
+    protected Runnable makeContextAwareLoggingException(Runnable runnable) {
+        requireNonNull(runnable, "runnable");
+        return () -> {
+            try (SafeCloseable ignored = ctx.push()) {
+                runnable.run();
+            } catch (Throwable th) {
+                logger.warn("An error occurred when pushing a context", th);
+                throw th;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java]: Could extract into a new method and deduplicate

File: core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java [hunk 4]
```diff
@@ -584,7 +584,10 @@ public String toString() {
             return strVal;
         }
 
-        final StringBuilder buf = new StringBuilder(96);
+        final StringBuilder buf = new StringBuilder(119);
+        buf.append('[')
+           .append(ServiceRequestContext.class.getSimpleName())
+           .append(']');
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java]: Ditto

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java (hunk 2 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java]: Then how about `[ClientCtx]`? or `[Client]`? I really wish to know whether the context is `ClientRequestContext` or `ServiceRequestContext` from the logs. 🤔

File: core/src/test/java/com/linecorp/armeria/internal/ContextFutureCallbackArgumentsProvider.java (hunk 1 above)
Comment (trustin) [reply core/src/test/java/com/linecorp/armeria/internal/ContextFutureCallbackArgumentsProvider.java]: That's a good question. :thinking: 

It is also possible that a user tries to handle an exception using `handle` or `whenComplete`, so I think it's not a good idea to handle `exceptionally` exceptionally. (pun intended :laughing:) i.e. I can't think of a good solution other than just logging.

Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/internal/ContextFutureCallbackArgumentsProvider.java]: 😆

File: core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java (hunk 3 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java]: Fixed. 😉

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java (hunk 2 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java]: Changed to `[ClientCtx]` and `[ServiceCtx]`

File: core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java [hunk 5]
```diff
@@ -351,10 +352,7 @@ default SafeCloseable push(boolean runCallbacks) {
 
         // Put the oldCtx back before throwing an exception.
         RequestContextThreadLocal.set(oldCtx);
-        throw new IllegalStateException(
-                "Trying to call object wrapped with context " + this + ", but context is currently " +
-                "set to " + oldCtx + ". This means the callback was called from " +
-                "unexpected thread or forgetting to close previous context.");
+        return throwIllegalContextPushing(this, oldCtx);
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java]: Ah here's where I first saw the pattern - see my comment here https://github.com/line/armeria/pull/2371#discussion_r363069843

Using `return` instead of `throw` doesn't seem to improve verbosity but makes the code much less readable.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java]: Yes, it's now much readable. Thanks!

File: core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+    protected <I, U, V> BiFunction<I, U, V> makeContextAwareLoggingException(BiFunction<I, U, V> function) {
+        requireNonNull(function, "function");
+        return (t, u) -> makeContextAwareLoggingException0(() -> function.apply(t, u));
+    }
+
+    private void makeContextAwareLoggingException0(Runnable runnable) {
+        try (SafeCloseable ignored = ctx.push()) {
+            runnable.run();
+        } catch (Throwable th) {
+            logger.warn("An error occurred when pushing a context", th);
```
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java]: That's a good point. Let me update the message. 😄

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java (hunk 2 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java]: How about shortening even more, like `[C]` and `[S]`?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java]: It's fine for me. Let me change that. 😄

File: core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java [hunk 7]
```diff
@@ -67,35 +67,35 @@ protected Runnable makeContextAwareLoggingException(Runnable runnable) {
...
-    private void makeContextAwareLoggingException0(Runnable runnable) {
+    private void makeContextAwareLoggingException0(Runnable action) {
         try (SafeCloseable ignored = ctx.push()) {
-            runnable.run();
+            action.run();
         } catch (Throwable th) {
-            logger.warn("An error occurred when pushing a context", th);
+            logger.warn("An error occurred when pushing a context and executing the action", th);
             throw th;
         }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java]: We should not log exceptions raised by `.run()`

```java
final SafeCloseable handle;
try {
    handle = ctx.push();
} catch (Throwable t) {
    logger.warn(...);
    Exceptions.throwUnsafely(t);
    return;
}

try {
    action.run();
} finally {
    handle.close();
}
```

File: core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java [hunk 8]
```diff
@@ -67,35 +67,35 @@ protected Runnable makeContextAwareLoggingException(Runnable runnable) {
...
-    private <V> V makeContextAwareLoggingException0(Supplier<? extends V> action) {
+    private <V> V makeContextAwareLoggingException0(Supplier<? extends V> fn) {
         try (SafeCloseable ignored = ctx.push()) {
-            return action.get();
+            return fn.get();
         } catch (Throwable th) {
-            logger.warn("An error occurred when pushing a context", th);
+            logger.warn("An error occurred when pushing a context and executing the fn", th);
             throw th;
         }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/AbstractRequestContextAwareCompletableFuture.java]: Ditto

File: core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java [hunk 9]
```diff
@@ -87,5 +87,20 @@ public static SafeCloseable pushWithRootAndOldCtx(ClientRequestContext currentCt
         }
     }
 
+    /**
+     * An {@link IllegalStateException} which is raised when pushing a context from the unexpected thread
+     * or forgetting to close the previous context.
+     */
+    public static final class IllegalContextPushingException extends IllegalStateException {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]: Could you make it a top-level class and make it part of `common` package?

File: core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java [hunk 10]
```diff
@@ -87,5 +87,20 @@ public static SafeCloseable pushWithRootAndOldCtx(ClientRequestContext currentCt
...
+
+        private static final long serialVersionUID = 5431942355463120798L;
+
+        public IllegalContextPushingException(RequestContext newCtx, RequestContext oldCtx) {
+            super("Trying to call object wrapped with context " + newCtx + ", but context is currently " +
+                  "set to " + oldCtx + ". This means the callback was called from " +
+                  "unexpected thread or forgetting to close previous context.");
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]: Now that we have a dedicated exception type, we could add getters for the two contexts? We could also simplify the exception message and add more details to the class Javadoc.

File: core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java [hunk 11]
```diff
@@ -87,5 +87,20 @@ public static SafeCloseable pushWithRootAndOldCtx(ClientRequestContext currentCt
...
 
+    /**
+     * An {@link IllegalStateException} which is raised when pushing a context from the unexpected thread
+     * or forgetting to close the previous context.
+     */
+    public static final class IllegalContextPushingException extends IllegalStateException {
+
+        private static final long serialVersionUID = 5431942355463120798L;
+
+        public IllegalContextPushingException(RequestContext newCtx, RequestContext oldCtx) {
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]: This type looks good but just to clarify, I was just expecting the old factory method to return `IllegalStateException` instead of throwing it ;)

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]: Ah, I misunderstood. 😅

File: core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java (hunk 9 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]: So If I change just to return the `IllegalStateException` from the previous method, I don't have to declare this new exception type. And I think we don't have to have this another exception, especially for this case. (Sorry I made this class because I misunderstood the comment. 🙏) Do you think we still need this?

File: core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java [hunk 12]
```diff
@@ -87,5 +87,19 @@ public static SafeCloseable pushWithRootAndOldCtx(ClientRequestContext currentCt
...
 
+    /**
+     * Returns an {@link IllegalStateException} which is raised when pushing a context from
+     * the unexpected thread or forgetting to close the previous context.
+     */
+    public static IllegalStateException newIllegalContextPushingException(
+            RequestContext newCtx, RequestContext oldCtx) {
+        requireNonNull(newCtx, "newCtx");
+        requireNonNull(oldCtx, "oldCtx");
+        throw new IllegalStateException(
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]:
```suggestion
        return new IllegalStateException(
```

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]: Oops forgot to change that.

File: core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java (hunk 9 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java]: Nope. Let's continue using `IllegalStateException`.

**Comment by minwoox** [comment]
Thanks reviewers!
