### PR TITLE
Less verbose error logging / Fix incorrect behavior when 'verboseExceptions' is set.

### LINKED ISSUE #1515: Do not log 'Sent a GOAWAY frame: debugData="Error flushing"'
.. because it basically means the connection is already over or the connection has been reset.

Related: #1401

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

1)

`Exceptions.isExpected(Throwable)` should always return `false` when
`verboseExceptions` flag is set. However, it currently always returns
`true` by coding mistake.

2)

I found a few more exception messages which do not really need to be
logged at high level:

    SSLException: SSLEngine closed already
    Sent a GOAWAY frame: lastStreamId=..., errorCode=INTERNAL_ERROR(2), debugData="Error flushing"

Both errors can happen when a socket connection has been closed by a
remote peer, which should be treated in a similar manner with
'connection reset by peer' errors.

Modifications:

- Update `Exceptions.isExpected()` to always return `false` when
  `verboseExceptions` flag is set.
- Update `Exceptions.isExpected()` to return `true` for
  `SSLException: SSLEngine closed already`.
- Update `Http2GoAwayHandler` to log at DEBUG level for
  `Sent a GOAWAY frame: ... debugData="Error flushing"`.

Result:

- Fixes #1515
- `com.linecorp.armeria.verboseExceptions` flag works as expected.
- Cleaner log file with less WARN-level log messages.

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java [hunk 1]
```diff
@@ -66,4 +77,31 @@ public void testTraceText() {
         assertThat(trace).startsWith(Exception.class.getName() + ": foo\n" +
                                      "\tat " + ExceptionsTest.class.getName());
     }
+
+    @Test
+    public void testIsExpected() {
+        final boolean expected = !Flags.verboseExceptions();
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java]: Just wondering if we can just make this as `true`.(not using `!Flags.verboseExceptions()`)

Comment (trustin) [reply core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java]: There was actually a bug in `Exceptions.isExpected()` where a wrong boolean value is returned when `Flags.verboseExceptions()` is `true`.

**Comment by trustin** [comment]
Thanks for reviewing.
