### PR TITLE
Make `GrpcService` handle the `@Decorator` annotations in a gRPC stub

### LINKED ISSUE #3967: Provide a way to decorate gRPC services and methods via annotation
Armeria has a mechanism to add decorators via [`@Decorator`](https://github.com/line/armeria/blob/f03b400cff136a710dbdbeb75e0e4f741387d296/core/src/main/java/com/linecorp/armeria/server/annotation/Decorator.java#L35).
However, it only works for annotated services at the moment. https://armeria.dev/docs/server-annotated-service#decorating-an-annotated-service
If `@Decorator` is supported for gRPC services and methods, users can easily manage access control of RPC methods with HTTP level decorators.

I think we can add a routing decorator that wraps `(Un)FramedGrpcService`.
```java
class GrpcDecoratingService extends SimpleDecoratingHttpService {

    // A pair of a service or a method path and decorators that are extracted from `@Decorator` and composite already.
    private Map<String, HttpService> decorators = ...;

    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
        // A method level decorator would be wrapped by a service level decorator if it was specified.
		HttpService methodDecorator = decorators.get(req.path());
        if (methodDecorator != null) {
            return methodDecorator.serve(ctx, req);
        }
        // No method level decorator was defined. Try to get a gRPC service level decorator.
        String serviceName = extractServiceName(req.path());
        HttpService serviceDecorator = decorators.get(serviceName);
        if (serviceDecorator != null) {
            return serviceDecorator.serve(ctx, req);
        }

        return unwrap.serve(ctx, req);
    }
}
```

### PR DESCRIPTION
**Pull request by ta7uw**
Motivation:

Armeria has a mechanism to add decorators via `@Decorator`.
However, it only works for annotated services at the moment. 
https://armeria.dev/docs/server-annotated-service#decorating-an-annotated-service

We should provide a way to decorate gRPC services and methods via annotation 

Modifications:

- Add `GrpcDecoratingService` to route a decorated service or method
- Add features for collecting decorators from annotated gRPC service to `GrpcServiceBuilder`
- Add `DecoratorAnnotationUtil` to provide useful ways for decorators
- Extract features for decorators from  `AnnotatedServiceFactory` to `AnnotatedObjectFactory`

Result:

- Closes #3967
- A user can easily add features to a gRPC service or method by adding decorators.
  e.g.  A user can easily manage access control of RPC methods with HTTP level decorators.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/DecoratorUtil.java [hunk 1]
```diff
@@ -0,0 +1,303 @@
...
+import com.linecorp.armeria.server.HttpService;
+import com.linecorp.armeria.server.annotation.Decorator;
+import com.linecorp.armeria.server.annotation.DecoratorFactory;
+import com.linecorp.armeria.server.annotation.DecoratorFactoryFunction;
+import com.linecorp.armeria.server.annotation.Decorators;
+
+/**
+ * A utility class for {@link Decorator}.
+ */
+public final class DecoratorUtil {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/DecoratorUtil.java:52]: Thanks for collecting decorator-related methods into this utility. :bow:

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+    }
+
+    @Override
+    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
+        final HttpService methodDecorator = methodDecorators.get(req.path());
+        if (methodDecorator != null) {
+            return methodDecorator.serve(ctx, req);
+        }
+        final String serviceName = extractServiceName(req.path());
+        final HttpService serviceDecorator = serviceDecorators.get(serviceName);
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:76]: What do you think about converting service-level decorators into method-level ones so we only keep one map? Decorator construction takes place only once but `extractServiceName` will many times, so it may be a win after all.

Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:76]: Sorry for the late reply. I missed it.

> What do you think about converting service-level decorators into method-level ones so we only keep one map?

It seems good.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/DecoratorUtil.java [hunk 3]
```diff
@@ -0,0 +1,303 @@
...
+            try {
+                return getInstance0(type);
+            } catch (Exception e) {
+                throw new IllegalStateException("A class must have an accessible default constructor: " +
+                                                type.getName(), e);
+            }
+        }
+    };
+
+    private DecoratorUtil() {}
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/DecoratorUtil.java:69]: Could you move down this private constructor below static methods?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+        this.methodDecorators = methodDecorators;
+    }
+
+    @Override
+    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
+        final HttpService methodDecorator = methodDecorators.get(req.path());
+        if (methodDecorator != null) {
+            return methodDecorator.serve(ctx, req);
+        }
+        final String serviceName = extractServiceName(req.path());
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:75]: We can use `MethodDescriptor.extractFullServiceName()`.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 5]
```diff
@@ -88,6 +94,16 @@
...
     private static final boolean USE_COROUTINE_CONTEXT_INTERCEPTOR;
 
+    private static Map<String, HttpService> applyGrpcServiceToDecorators(
+            Map<String, List<DecoratorAndOrder>> mp,
+            GrpcService grpcService) {
+        final Map<String, HttpService> result = new HashMap<>();
+        for (Map.Entry<String, List<DecoratorAndOrder>> entry : mp.entrySet()) {
+            result.put(entry.getKey(), DecoratorUtil.applyDecorators(entry.getValue(), grpcService));
+        }
+        return result;
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:104]: Use immutable Map and stream?
```suggestion
        return mp.entrySet()
                 .stream()
                 .collect(toImmutableMap(Map.Entry::getKey,
                                         e -> DecoratorUtil.applyDecorators(e.getValue(), grpcService)));
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 6]
```diff
@@ -242,8 +263,38 @@ public GrpcServiceBuilder addService(String path, BindableService bindableServic
...
+     * <pre>{@code
+     * GrpcService.builder()
+     *            .addService(new TestServiceImpl,
+     *                        impl -> ServerInterceptors.intercept(impl, interceptors));
+     * }</pre>
+     */
+    public <T> GrpcServiceBuilder addService(
+            T implementation,
+            Function<? super T, ServerServiceDefinition> serviceDefinitionFactory) {
+        final ServerServiceDefinition serverServiceDefinition = serviceDefinitionFactory.apply(implementation);
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:295]: Add `requireNonNull`?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 2 above)
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:76]: IIUC, we can safely remove `serviceDecorators` because `methodDecorators` is a combination of service decorators and method decorators.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/DecoratorUtil.java [hunk 7]
```diff
@@ -0,0 +1,303 @@
...
+    }
+
+    private static <T> T getInstance0(Class<? extends T> clazz) throws Exception {
+        @SuppressWarnings("unchecked")
+        final Constructor<? extends T> constructor =
+                Iterables.getFirst(getConstructors(clazz, withParametersCount(0)), null);
+        assert constructor != null : "No default constructor is found from " + clazz.getName();
+        constructor.setAccessible(true);
+        return constructor.newInstance();
+    }
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/DecoratorUtil.java:205]: How about extracting these methods into a utility class named `AnnotatedObjectFactory` so that 
`AnnotatedServiceFactory` and `DecoratorUtil` share code and the populated objects.

File: grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java [hunk 8]
```diff
@@ -375,9 +375,12 @@ void newStructInfo() throws Exception {
...
     void httpEndpoint() {
-        final GrpcService grpcService =
-                GrpcService.builder().addService(mock(HttpJsonTranscodingTestServiceImplBase.class))
-                           .enableHttpJsonTranscoding(true).build();
+        final GrpcService grpcService = (GrpcService) GrpcService
+                .builder()
+                .addService(mock(HttpJsonTranscodingTestServiceImplBase.class))
+                .enableHttpJsonTranscoding(true)
+                .build()
+                .unwrap();
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java:383]: This change could be reverted if https://github.com/line/armeria/pull/4041/files#r811707115 is applied.

**Comment by ikhoon** [comment]
Sorry for the late review. This PR is really solid! I believe many gRPC users would love this awesome feature. 🙂

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 4 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:67]: How can we use `MethodDescriptor.extractFullServiceName()` in `GrpcDecratingService`?

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:67]: Couldn't we access `MethodDescriptor` from `GrpcDecratingService`?
```
final String serviceName = MethodDescriptor.extractFullServiceName(req.path());
```
Anyway, I think we only keep `methodDecorators` in `GrpcDecratingService`. Therefore, we don't need to extract a service name from a request path anymore.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 9]
```diff
@@ -717,6 +771,48 @@ static GrpcStatusFunction toGrpcStatusFunction(
...
+                path == null ? serverServiceDefinition.getServiceDescriptor().getName() : path;
+        final List<DecoratorAndOrder> serviceDecorators = DecoratorUtil.collectDecorators(clazz);
+        if (!serviceDecorators.isEmpty()) {
+            methodDecorators.put('/' + serviceName, DecoratorUtil.collectDecorators(clazz));
+        }
+        // In gRPC, A method name is unique.
+        final Map<String, Method> methods = DecoratorUtil.decoratorMethods(clazz)
+                                                         .stream()
+                                                         .collect(Collectors.toMap(Method::getName,
+                                                                                   Function.identity()));
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:787]: Should we remove serviceDecorators and check all public methods to create `methodDecorators`?
```suggestion
        // In gRPC, a method name is unique.
        final Map<String, Method> methods = new HashMap<>();
        for (Method method: getAllMethods(clazz, withModifier(Modifier.PUBLIC))) {
            methods.put(method.getName(), method);
        }
```

Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java]: I understand it.
Fixed it -> acc8668

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+    private final GrpcService delegate;
+
+    /**
+     * A pair of a method path (e.g. '/armeria.grpc.sample.SampleService/UnaryCall') and decorators
+     * that are extracted from `@Decorator` and composite already.
+     */
+    private final Map<String, HttpService> methodDecorators;
+
+    GrpcDecoratingService(GrpcService delegate,
+                          Map<String, HttpService> methodDecorators) {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:47]: nit: Could join two lines?
```suggestion
    GrpcDecoratingService(GrpcService delegate, Map<String, HttpService> methodDecorators) {
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+        this.methodDecorators = methodDecorators;
+    }
+
+    @Override
+    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
+        final HttpService methodDecorator = methodDecorators.get(req.path());
+        if (methodDecorator != null) {
+            return methodDecorator.serve(ctx, req);
+        }
+        return unwrap().serve(ctx, req);
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:59]: How about consistently using `delegate` rather than mixing `delegate` and `unwrap()`?
```suggestion
        return delegate.serve(ctx, req);
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 12]
```diff
@@ -88,6 +97,15 @@
 
     private static final boolean USE_COROUTINE_CONTEXT_INTERCEPTOR;
 
+    private static Map<String, HttpService> applyGrpcServiceToDecorators(
+            Map<String, List<DecoratorAndOrder>> mp,
+            GrpcService grpcService) {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:102]: Could join two lines?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 13]
```diff
@@ -148,6 +166,8 @@
 
     private boolean useClientTimeoutHeader = true;
 
+    private final Map<String, List<DecoratorAndOrder>> methodDecorators = new HashMap<>();
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:169]: Should we use `ImmutableMap.Builder`?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 14]
```diff
@@ -242,8 +263,40 @@ public GrpcServiceBuilder addService(String path, BindableService bindableServic
...
+     *            .addService(new TestServiceImpl,
+     *                        impl -> ServerInterceptors.intercept(impl, interceptors));
+     * }</pre>
+     */
+    public <T> GrpcServiceBuilder addService(
+            T implementation,
+            Function<? super T, ServerServiceDefinition> serviceDefinitionFactory) {
+        requireNonNull(implementation, "implementation");
+        requireNonNull(serviceDefinitionFactory, "serviceDefinitionFactory");
+        final ServerServiceDefinition serverServiceDefinition = serviceDefinitionFactory.apply(implementation);
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:297]: nit:
```java
requireNonNull(serverServiceDefinition, "serviceDefinitionFactory.apply() returned null");
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 15]
```diff
@@ -717,6 +771,41 @@ static GrpcStatusFunction toGrpcStatusFunction(
         return interceptors;
     }
 
+    private void collectDecorators(Class<?> clazz,
+                                   @Nullable String path,
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:775]:
```suggestion
    private void collectDecorators(Class<?> clazz, @Nullable String path,
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 16]
```diff
@@ -717,6 +771,41 @@ static GrpcStatusFunction toGrpcStatusFunction(
...
+                                   ServerServiceDefinition serverServiceDefinition) {
+        final String serviceName =
+                path == null ? serverServiceDefinition.getServiceDescriptor().getName() : path;
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:778]: Should we flip the condition for readability because `path` has a higher priority?
 
```suggestion
        final String serviceName =
                path != null ? path : serverServiceDefinition.getServiceDescriptor().getName();
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java [hunk 17]
```diff
@@ -0,0 +1,179 @@
...
+import com.linecorp.armeria.server.HttpService;
+import com.linecorp.armeria.server.ServerBuilder;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.annotation.Decorator;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.testing.junit5.server.ServerExtension;
+
+import io.grpc.stub.StreamObserver;
+
+class GrpcDecoratingServiceTest {
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:49]: Could you also add simple integration tests for other gRPC stub implementations?
You can see test modules in `it/grpc/*`.

**Review by ikhoon — COMMENTED** [review]
Mostly looking good! Left only minor comments. 😉

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java (hunk 17 above)
Comment (ta7uw) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:49]: Which implementation can I add as other gRPC stub implementations?
Could you give me an example?

Comment (ikhoon) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:49]: The following example seems enough for integration tests.
```java
@Decorator(FirstDecorator.class)
private static class TestServiceImpl extends TestServiceImplBase {

    @Override
    @Decorator(MethodFirstDecorator.class)
    public void unaryCall(SimpleRequest request, StreamObserver<SimpleResponse> responseObserver) {
        responseObserver.onNext(SimpleResponse.newBuilder()
                                              .setUsername("test user")
                                              .build());
        responseObserver.onCompleted();
    }
}
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java [hunk 18]
```diff
@@ -0,0 +1,179 @@
...
+
+    @RegisterExtension
+    static ServerExtension server = new ServerExtension(true) {
+        @Override
+        protected void configure(ServerBuilder sb) {
+            sb.requestTimeoutMillis(5000);
+            sb.decorator(LoggingService.newDecorator());
+            sb.service(GrpcService.builder()
+                                  .addService(new TestServiceImpl())
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:58]: Should we also test `.addService("/foo", new TestServiceImpl())`?
You can override a request path at the client side using a decorator.
For example:
```java
final HttpRequest newReq = req.mapHeaders(headers -> {
     return headers.toBuilder()
                   .path(path.replace(...))
                   .build();
   });
ctx.updateRequest(newReq);
delegate.execute(ctx, newReq);
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java [hunk 19]
```diff
@@ -0,0 +1,179 @@
...
+        }
+    };
+
+    private static String FIRST_TEST_RESULT = "";
+    private static String SECOND_TEST_RESULT = "";
+    private static String THIRD_TEST_RESULT = "";
+
+    @Test
+    void methodDecorators() {
+        final TestServiceBlockingStub client = Clients.builder(server.httpUri(GrpcSerializationFormats.PROTO))
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:71]: Use `GrpcClients.builder()`?
```suggestion
        final TestServiceBlockingStub client = GrpcClients.builder(server.httpUri())
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java (hunk 17 above)
Comment (ta7uw) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:49]: @ikhoon 
Sorry for the late response. 🙇‍♂️
Please review again.

Comment (ikhoon) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:49]: Don't worry about that. Take your time.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 20]
```diff
@@ -717,6 +773,40 @@ static GrpcStatusFunction toGrpcStatusFunction(
...
     }
 
+    private void collectDecorators(Class<?> clazz, @Nullable String path,
+                                   ServerServiceDefinition serverServiceDefinition) {
+        final String serviceName =
+                path != null ? path : '/' + serverServiceDefinition.getServiceDescriptor().getName();
+        // In gRPC, A method name is unique.
+        final Map<String, Method> methods = new HashMap<>();
+        for (Method method : getAllMethods(clazz, withModifier(Modifier.PUBLIC))) {
+            if (method.getDeclaringClass().equals(clazz)) {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:783]: Should we limit the declaring class to `clazz`?
I think some users might want a hierarchical structure for stub implementations.
For example:
```java
abstract class AbstractMyService extends MyServiceImplBase {
    @Decorator(MyDecorator.class)
    public void foo(...) {
        ...
    }

    public void bar(...) {
        ...
    }
}


class BarService extends AbstractMyService {

    @Decorator(BarDecorator.class)
    @Override
    public void bar(...) {
        ...
    }
}
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 21]
```diff
@@ -792,6 +882,14 @@ public GrpcService build() {
...
                                                             : UnframedGrpcErrorHandler.ofJson());
         }
-        return grpcService;
+        final Map<String, List<DecoratorAndOrder>> methodDecorators = methodDecoratorBuilder.build();
+        if (methodDecorators.isEmpty()) {
+            return grpcService;
+        } else {
+            final Map<String, HttpService> composedMethodDecorators = applyGrpcServiceToDecorators(
+                    methodDecorators,
+                    grpcService);
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:891]:
```suggestion
                    methodDecorators, grpcService);
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 22]
```diff
@@ -0,0 +1,80 @@
...
+
+    GrpcDecoratingService(GrpcService delegate, Map<String, HttpService> methodDecorators) {
+        super(delegate);
+        this.delegate = delegate;
+        this.methodDecorators = methodDecorators;
+    }
+
+    @Override
+    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
+        final HttpService methodDecorator = methodDecorators.get(req.path());
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:54]: Should we make this class to support HTTP-JSON transcoding?
It would be possible if we place this decorator after `HttpJsonTranscodingService`.
You may want to refer to:
https://github.com/line/armeria/blob/8df42aa225af877ef13781ec1b27c1fe0ce37883/grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java#L188-L197

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java (hunk 20 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java]: We should not limit this.
I supported a hierarchical structure for stub implementations. -> [9f4ad54](https://github.com/line/armeria/pull/4041/commits/9f4ad54b34e678d8f02c026a17ba206d48df33dc)

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 22 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:54]: Does this mean that the decorator-related processing is performed in FramedGrpcService?

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:54]: We may not determine the target gRPC service using `req.path()` if HTTP/JSON transcoding is enabled. 
‘/v1/api/items/{itemId}’ could be a request path. So `RESOLVED_GRPC_METHOD` injected by `HttpJsonTranscodingService` should be used to find a target gRPC service method.

**Review by jrhee17 — COMMENTED** [review]
Left some preliminary comments 😄

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 22 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java]: Thank you for the explanation.
support http-json transcoding -> d528040

**Review by ikhoon — COMMENTED** [review]
Almost there! I think we are on the same page.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 23]
```diff
@@ -0,0 +1,95 @@
...
+    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
+        final ServerMethodDefinition<?, ?> method = lookupMethodFromAttribute ? ctx.attr(RESOLVED_GRPC_METHOD)
+                                                                              : null;
+        final String path;
+        if (method != null && method.getMethodDescriptor() != null) {
+            path = '/' + method.getMethodDescriptor().getFullMethodName();
+        } else {
+            path = req.path();
+        }
+        final HttpService methodDecorator = methodDecorators.get(path);
```
[the remark this answers is not in the document]
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:69]: @ikhoon 
I think that we should not use`ServerMethodDefinition` as a key of a map because `hashCode` of `ServerMethodDefinition`  is not implemented.

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java [hunk 24]
```diff
@@ -0,0 +1,101 @@
...
+
+    @RegisterExtension
+    static ServerExtension server = new ServerExtension(true) {
+        @Override
+        protected void configure(ServerBuilder sb) {
+            sb.requestTimeoutMillis(5000);
+            sb.decorator(LoggingService.newDecorator());
+            sb.service(GrpcService.builder()
+                                  .addService(new TestServiceImpl())
+                                  .build());
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java:53]: Should we also test with a prefix?
```java
sb.serviceUnder("/grpc", GrpcService...)
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 23 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:69]: I see. Let's keep it as is. On top of that, should we avoid the string concatenation -`'/' + method.getMethodDescriptor().getFullMethodName()`?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 25]
```diff
@@ -0,0 +1,95 @@
...
+
+    @Override
+    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
+        final ServerMethodDefinition<?, ?> method = lookupMethodFromAttribute ? ctx.attr(RESOLVED_GRPC_METHOD)
+                                                                              : null;
+        final String path;
+        if (method != null && method.getMethodDescriptor() != null) {
+            path = '/' + method.getMethodDescriptor().getFullMethodName();
+        } else {
+            path = req.path();
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:67]: Should we use `ctx.mappedPath()`? Please check out the new comment in `GrpcDecoratingServiceTest`.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 23 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:69]: To avoid the concatenation, we may add both paths to the hash map.

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceSupportHttpJsonTranscodingTest.java [hunk 26]
```diff
@@ -0,0 +1,102 @@
...
+            sb.decorator(LoggingService.newDecorator());
+            sb.service(grpcService);
+        }
+    };
+
+    private static String FIRST_TEST_RESULT = "";
+
+    private final ObjectMapper mapper = JacksonUtil.newDefaultObjectMapper();
+
+    private final WebClient webClient = WebClient.builder(server.httpUri()).build();
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceSupportHttpJsonTranscodingTest.java:64]:
```suggestion
    private final BlockingWebClient webClient = server.webClient().blocking();
```

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java [hunk 27]
```diff
@@ -0,0 +1,101 @@
...
+        }
+    };
+
+    private static String FIRST_TEST_RESULT = "";
+
+    @Test
+    void methodDecorators() {
+        final TestServiceBlockingStub client = GrpcClients.builder(server.httpUri(
+                                                                  GrpcSerializationFormats.PROTO))
+                                                          .build(TestServiceBlockingStub.class);
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java:63]: We don't need to specify `GrpcSerializationFormats.PROTO` to `GrpcClients`. No `GrpcSerializationFormats` is set, `GrpcSerializationFormats.PROTO` is used by default.
```suggestion
        final TestServiceBlockingStub client = 
                GrpcClients.newClient(server.httpUri(), TestServiceBlockingStub.class);
```

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java [hunk 28]
```diff
@@ -0,0 +1,101 @@
...
+import com.linecorp.armeria.server.grpc.GrpcService;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.testing.junit5.server.ServerExtension;
+
+import io.grpc.stub.StreamObserver;
+
+public class GrpcDecoratingServiceTest {
+
+    @RegisterExtension
+    static ServerExtension server = new ServerExtension(true) {
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java:46]:
```suggestion
    static final ServerExtension server = new ServerExtension() {
```

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java [hunk 29]
```diff
@@ -0,0 +1,101 @@
...
+import com.linecorp.armeria.server.ServerBuilder;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.annotation.Decorator;
+import com.linecorp.armeria.server.grpc.GrpcService;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.testing.junit5.server.ServerExtension;
+
+import io.grpc.stub.StreamObserver;
+
+public class GrpcDecoratingServiceTest {
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java:43]:
```suggestion
class GrpcDecoratingServiceTest {
```

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceSupportHttpJsonTranscodingTest.java [hunk 30]
```diff
@@ -0,0 +1,102 @@
...
+import com.linecorp.armeria.server.ServerBuilder;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.annotation.Decorator;
+import com.linecorp.armeria.server.grpc.GrpcService;
+import com.linecorp.armeria.server.logging.LoggingService;
+import com.linecorp.armeria.testing.junit5.server.ServerExtension;
+
+import io.grpc.stub.StreamObserver;
+
+public class GrpcDecoratingServiceSupportHttpJsonTranscodingTest {
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceSupportHttpJsonTranscodingTest.java:46]:
```suggestion
class GrpcDecoratingServiceSupportHttpJsonTranscodingTest {
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java [hunk 31]
```diff
@@ -0,0 +1,237 @@
...
+
+    private static String FIRST_TEST_RESULT = "";
+    private static String SECOND_TEST_RESULT = "";
+    private static String THIRD_TEST_RESULT = "";
+    private static String FOURTH_TEST_RESULT = "";
+
+    @Test
+    void methodDecorators() {
+        final TestServiceBlockingStub client = GrpcClients.builder(server.httpUri(
+                                                                  GrpcSerializationFormats.PROTO))
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:74]:
```suggestion
        final TestServiceBlockingStub client = GrpcClients.builder(server.httpUri())
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java [hunk 32]
```diff
@@ -0,0 +1,237 @@
...
+                                                          .build(TestServiceBlockingStub.class);
+        client.unaryCall(SimpleRequest.getDefaultInstance());
+        assertThat(FIRST_TEST_RESULT)
+                .isEqualTo("FirstDecorator/SecondDecorator/MethodFirstDecorator/MethodSecondDecorator");
+    }
+
+    @Test
+    void serviceDecorators() {
+        final MetricsServiceBlockingStub client = GrpcClients.builder(server.httpUri(
+                                                                     GrpcSerializationFormats.PROTO))
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:84]:
```suggestion
        final MetricsServiceBlockingStub client = GrpcClients.builder(server.httpUri()
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java [hunk 33]
```diff
@@ -0,0 +1,237 @@
...
+                                                             .build(MetricsServiceBlockingStub.class);
+        client.getGauge(GaugeRequest.getDefaultInstance());
+        assertThat(SECOND_TEST_RESULT).isEqualTo("ThirdDecorator");
+    }
+
+    @Test
+    void nonDecorators() {
+        final ReconnectServiceBlockingStub client = GrpcClients.builder(server.httpUri(
+                                                                       GrpcSerializationFormats.PROTO))
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java:93]:
```suggestion
        final ReconnectServiceBlockingStub client = GrpcClients.builder(server.httpUri())
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java [hunk 34]
```diff
@@ -295,4 +368,105 @@ public <REQ, RESP> Listener<REQ> interceptCall(ServerCall<REQ, RESP> call, Metad
...
+                           return ((Decorator) annotation).value();
+                       }
+                       final DecoratorFactory factory =
+                               annotation.annotationType().getAnnotation(DecoratorFactory.class);
+                       if (factory != null) {
+                           return factory.value();
+                       }
+                       throw new Error("Should not reach here.");
+                   })
+                   .collect(Collectors.toList());
```
Comment (ikhoon) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java:470]:
```suggestion
                   .collect(toImmutableList());
```

**Review by trustin — APPROVED** [review]
Thanks a lot for adding such a useful feature, @ta7uw. We might want to add something similar to Thrift as well in the future. LGTM once @ikhoon's comments are addressed.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 25 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java]: Oops. sorry.
I addressed this.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 23 above)
[the remark this answers is not in the document]
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java]: I think that having two maps is a bit redundant, this seems better In terms of performance.
I addressed this.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java [hunk 35]
```diff
@@ -745,6 +806,68 @@ private ImmutableList.Builder<ServerInterceptor> interceptors() {
...
+            }
+            for (Method method : foundMethods) {
+                final List<DecoratorAndOrder> decorators = DecoratorAnnotationUtil.collectDecorators(clazz,
+                                                                                                     method);
+                if (!decorators.isEmpty()) {
+                    String key = serviceName + '/' + targetMethodName;
+                    if (pathToDecorators.containsKey(key)) {
+                        if (decorators.size() > pathToDecorators.get(key).size()) {
+                            pathToDecorators.put(key, decorators);
+                        }
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:842]: @ta7uw Could you explain why we need this condition?

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java [hunk 36]
```diff
@@ -0,0 +1,153 @@
...
+
+        final TestServiceBlockingStub prefixClient = GrpcClients
+                .builder(server.httpUri())
+                .decorator((delegate, ctx, req) -> {
+                    final String path = req.path();
+                    final HttpRequest newReq = req.mapHeaders(
+                            headers -> headers.toBuilder()
+                                              .path(path.replace(
+                                                      "armeria.grpc.testing.TestService",
+                                                      "grpc/armeria.grpc.testing.TestService"))
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java]: Fixed by [`153fb92` (#4041)](https://github.com/line/armeria/pull/4041/commits/153fb9253379615220df150cb3100925a98a0621)

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java (hunk 35 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:842]: @ikhoon 
Consider the folliowing hierarchical service class,  the key for `UnaryCall` is `/armeria.grpc.testing.TestService/UnaryCall` and the keys generated from each of `ThirdTestServiceImpl`  and `AbstractThirdTestServiceImpl` is the same.
We should register the decorators of `ThirdTestServiceImpl`, so the number of decorators is used to determine which class is subclasses at each path.

```java
    @Decorator(Decorator1.class)
    private abstract static class AbstractThirdTestServiceImpl extends TestServiceImplBase {

        @Override
        @Decorator(Decorator2.class)
        public void unaryCall(SimpleRequest request, StreamObserver<SimpleResponse> responseObserver) {
            responseObserver.onNext(SimpleResponse.newBuilder()
                                                  .setUsername("test user")
                                                  .build());
            responseObserver.onCompleted();
        }
    }

    private static class ThirdTestServiceImpl extends AbstractThirdTestServiceImpl {

        @Override
        @Decorator(Decorator3.class)
        public void emptyCall(Empty request, StreamObserver<Empty> responseObserver) {
            responseObserver.onNext(Empty.getDefaultInstance());
            responseObserver.onCompleted();
        }
    }
```

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:842]: Thanks for the detailed explanation.

>  We should register the decorators of ThirdTestServiceImpl, so the number of decorators is used to determine which class is subclasses at each path.

It might be abnormal to pick up a super method because it has many more decorators. 
Based on the implementation of `ReflectionUtils.getAllMethods()`, it recursively collects methods from the bottom type so I can assume the order of method are sorted. A lower type will take precedence.
Should we modify the following code to get only the lowest implemented method?
https://github.com/line/armeria/blob/aca2ba6e5337c8d58adf48887453f735d664e5df/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L815-L822

Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:842]: > Based on the implementation of ReflectionUtils.getAllMethods(), it recursively collects methods from the bottom type so I can assume the order of method are sorted

I think these methods are collected into HashSet, so the order of methods is not sorted

Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:842]: > Based on the implementation of ReflectionUtils.getAllMethods(), it recursively collects methods from the bottom type so I can assume the order of method are sorted.

I think that methods are collected into HashSet in `ReflectionUtils`, so the order of methods is not sorted.
Should we copy methods in `ReflectionUtils` and refactor them to return collections as an ArrayList?

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java:842]: > so the order of methods is not sorted.

Good point. I missed the detail.

>  Should we copy methods in ReflectionUtils and refactor them to return collections as an ArrayList?

Sounds good!

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/InternalReflectionUtils.java [hunk 37]
```diff
@@ -0,0 +1,66 @@
...
+import com.google.common.base.Predicate;
+import com.google.common.base.Predicates;
+import com.google.common.collect.Iterables;
+import com.google.common.collect.Lists;
+
+/**
+ * Utility class which is used by {@link GrpcServiceBuilder} to get all sorted methods
+ * from a bottom service class.
+ */
+class InternalReflectionUtils extends ReflectionUtils {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/InternalReflectionUtils.java:35]: - Should we remove `extends`?
```suggestion
final class InternalReflectionUtils {
```
- Add a private constructor?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/InternalReflectionUtils.java [hunk 38]
```diff
@@ -0,0 +1,66 @@
...
+     * get all methods of given type which are sorted from bottom class, up the super class hierarchy,
+     * optionally filtered by predicates
+     */
+    static List<Method> getAllSortedMethods(final Class<?> type,
+                                            Predicate<? super Method>... predicates) {
+        final List<Method> result = Lists.newArrayList();
+        for (Class<?> t : getAllSortedSuperTypes(type)) {
+            result.addAll(getMethods(t, predicates));
+        }
+        return result;
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/InternalReflectionUtils.java:47]:
```suggestion
        final ImmutableList.Builder<Method> result = ImmutableList.builder();
        for (Class<?> t : getAllSortedSuperTypes(type)) {
            result.addAll(getMethods(t, predicates));
        }
        return result.build();
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/InternalReflectionUtils.java [hunk 39]
```diff
@@ -0,0 +1,66 @@
...
+                result.addAll(getAllSortedSuperTypes(supertype));
+            }
+        }
+        return filter(result, predicates);
+    }
+
+    private static <T> List<T> filter(final Iterable<T> elements, Predicate<? super T>... predicates) {
+        return isEmpty(predicates) ? Lists.newArrayList(elements) :
+               Lists.newArrayList(Iterables.filter(elements, Predicates.and(predicates)));
+    }
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/InternalReflectionUtils.java:65]:
```suggestion
    private static Iterable<Class<?>> getAllSortedSuperTypes(final Class<?> type,
                                                         Predicate<? super Class<?>>... predicates) {
        final List<Class<?>> result = new ArrayList<>;
        if (type != null && (includeObject || !type.equals(Object.class))) {
            result.add(type);
            for (Class<?> supertype : getSuperTypes(type)) {
                result.addAll(getAllSortedSuperTypes(supertype));
            }
        }
        return filter(result, predicates);
    }

    private static <T> List<T> filter(final Iterable<T> elements, Predicate<? super T>... predicates) {
        return isEmpty(predicates) ? Lists.newArrayList(elements)
                                   : Streams.stream(elements)
                                            .filter(Predicates.and(predicates)::apply)
                                            .collect(toImmutableList());
    }
```

**Review by ikhoon — COMMENTED** [review]
Overall, looks good! ❤️

**Review by ikhoon — APPROVED** [review]
Awesome work, @ta7uw! 🙇‍♂️💯
