### PR TITLE
Fix `AnnotatedService` behavior with `void` return types

### LINKED ISSUE #4390: Improve confusing `AnnotatedService` behavior with `void` return type
Currently, the behavior of `AnnotatedService` with void return type(including `Mono<Void>`) is quite confusing and users often struggles to find the right way to return `204 No Content` with `AnnotatedService`.
 
The following code demonstrates common attempts to give `204 No Content` and its actual result.

```java
@ProducesJson // It's common to add class-level @ProducesJson REST API service.
public class FooService {

    @Get("/foo") // 500 error; cause: IllegalArgumentException
    public void foo() {}

    @Get("/foo-mono") // 200 OK, Content-Type: application/json, body: "null" (4-bytes string)
    public Mono<Void> fooMono() {
        return Mono.empty();
    }

    @Get("/foo-mono-204") // 500 error; cause: IllegalArgumentException
    @StatusCode(204)
    public Mono<Void> fooMono204() {
        return Mono.empty();
    }
}

// Without @ProducesJson
public class BarService {

    @Get("/bar") // 204 No Content
    public void bar() {}

    @Get("/bar-mono") // 200 OK with empty body
    public Mono<Void> barMono() {
        return Mono.empty();
    }

    @Get("/bar-mono-204") // 204 No Content
    @StatusCode(204)
    public Mono<Void> barMono204() {
        return Mono.empty();
    }
}
```

Adding `NullToNoContentResponseConverterFunction` would be of some help but it doesn't cover `Mono<Void>` cases.

This behavior could possibly be fixed by..:
1. modifying `AnnotatedServiceFactory#defaultResponseStatus` to return `HttpStatus.NO_CONTENT` for `Mono<Void>`.
2. modifying `AnnotatedServiceFactory#routes` to ignore `producibleMediaTypes`.
   - Or by ignoring `negotiatedResponseMediaType` in `AnnotatedService` when the status code is 204.

### PR DESCRIPTION
**Pull request by ks-yim**
Motivation:

Currently, the behavior of `AnnotatedService` with void return type(including `Publisher<Void>` and `CompletableFuture<Void>`) is confusing and users often struggle to find the right way to return `204 No Content` with `AnnotatedService`.
- Adding `@StatusCode(204)` with class-level `@ProducesJson` results in 500 errors if the return type is `void`)
- Returning `Mono<Void>` or `CompletableFuture<Void>` gives 200 response by default while returning `void` gives 204.

Modifications:

- Make `AnnotatedService` not set `Content-Type` header when the `status.isContentAlwaysEmpty()` is `true`.
- Make `Publisher<Void>`, `CompletionStage<Void>` return type gives 204 status code by default.

Result:

- Closes #4390
- You no longer see 500 errors for returning `void`, `Publisher<Void>` or `CompletionStage<Void>` when `@ProducesJson` and `@StatusCode(204)` are used at the same time.
- Returning `Publisher<Void>` or `CompletionStage<Void>` correctly gives 204 response by default.

### CODE REVIEW

**Comment by ks-yim** [comment]
cc. @hllee1021

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java [hunk 1]
```diff
@@ -166,11 +170,26 @@ public static List<AnnotatedServiceElement> find(
                       .collect(toImmutableList());
     }
 
-    private static HttpStatus defaultResponseStatus(Method method) {
+    private static HttpStatus defaultResponseStatus(Method method, Class<?> clazz) {
         final StatusCode statusCodeAnnotation = AnnotationUtil.findFirst(method, StatusCode.class);
         if (statusCodeAnnotation == null) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java:175]: nit: Let's do the early return because this block gets bigger.
```java
if (statusCodeAnnotation != null) {
    ...
}
...
```

**Review by minwoox — APPROVED** [review]
Just one small nit. Thanks for cleaning this up! 😄

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java [hunk 2]
```diff
@@ -166,11 +170,26 @@ public static List<AnnotatedServiceElement> find(
...
+            if (!producibleMediaTypes(method, clazz).isEmpty()) {
+                return HttpStatus.OK;
+            }
             // Set a default HTTP status code for a response depending on the return type of the method.
             final Class<?> returnType = method.getReturnType();
+
+            if (Publisher.class.isAssignableFrom(returnType) ||
+                CompletionStage.class.isAssignableFrom(returnType)) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java:183]: Should we use `ClassUtil.unwrapAsyncType()`? `MONO_CLASS` seems enough for no_content status.

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java]: I haven't noticed the existence of `ClassUtil.unwrapAsyncType(Type)` 👀.

From what I understand, `Publisher<Void>` indicates that you should not expect a data signal but rather only `onComplete()` and `onError(Throwable)` signals and it can cover other reactive implementations(e.g. [suspend fun to publisher](https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/kotlinx-coroutines-reactive/src/Publish.kt#L36)), too so I thought it's reasonable to give 204 when the return type is `Publisher<Void>`.

And isn't it a bit weird to give different status codes depending on which return type is declared on the method?
```java
@Get("/foo") // 200
public Publisher<Void> voidPublisher() {
    return Mono.empty();
}

@Get("/bar") // 204
public Mono<Void> voidMono() {
    return Mono.empty();
}
```

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java]: But, fixed the code anyways, to get aligned with the other code with regards to how they treat `Publisher` return type.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java (hunk 1 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java]: Thanks! Should've read this more carefully 😆.
https://armeria.dev/community/developer-guide#prefer-early-return-style

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java (hunk 2 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java]: That looks weird. 😆 
+1 for supporting `Publisher<Void>` as well.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java]: Makes sense. Let's return 204 for `Publisher<Void>`.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 3]
```diff
@@ -420,19 +420,18 @@ private Object invoke(ServiceRequestContext ctx, HttpRequest req, AggregatedResu
...
      */
-    private HttpResponse convertResponse(ServiceRequestContext ctx, @Nullable HttpHeaders headers,
+    private HttpResponse convertResponse(ServiceRequestContext ctx, @Nullable ResponseHeaders headers,
                                          @Nullable Object result, HttpHeaders trailers) {
         final ResponseHeaders newHeaders;
         final HttpHeaders newTrailers;
         if (result instanceof HttpResult) {
             final HttpResult<?> httpResult = (HttpResult<?>) result;
-            newHeaders = setHttpStatus(addNegotiatedResponseMediaType(ctx, httpResult.headers()));
+            newHeaders = addNegotiatedResponseMediaType(ctx, setHttpStatus(httpResult.headers()));
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:429]: It is not related to this PR so you don't have to address it in this PR.
If so, could you leave a `TODO` comment for it?

Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:429]:
```suggestion
            // TODO(ikhoon): Consolidate `addNegotiatedResponseMediaType` and `setHttpStatus` to 
            //               avoid creating temporal `ResponseHeadersBuilder`s
            newHeaders = addNegotiatedResponseMediaType(ctx, setHttpStatus(httpResult.headers()));
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 4]
```diff
@@ -455,28 +454,27 @@ private HttpResponse convertResponse(ServiceRequestContext ctx, @Nullable HttpHe
...
-
-        return ResponseHeaders.builder()
-                              .add(headers)
-                              .contentType(negotiatedResponseMediaType);
+        return headers.contentType(negotiatedResponseMediaType).build();
     }
 
-    private ResponseHeaders setHttpStatus(ResponseHeadersBuilder headers) {
+    private ResponseHeadersBuilder setHttpStatus(HttpHeaders headers) {
+        final ResponseHeadersBuilder builder = ResponseHeaders.builder().add(headers);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:472]: `builder.add()` is an expensive operation. It would be better to avoid calling it if `headers` is an instance of `ResponseHeaders`
```suggestion
        final ResponseHeadersBuilder builder;
        if (headers instanceof ResponseHeaders) {
            header = ((ResponseHeaders) headers).toBuilder();
        } else {
            builder = ResponseHeaders.builder().add(headers);
        }
```

**Review by ikhoon — COMMENTED** [review]
Overall, looking good. Left minor comments.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:429]: Oh, I am preparing a commit, please wait a bit. Sorry 😭.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java (hunk 2 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java]: Reverted the change but extracted the async type unwrapping logic here to `ClassUtil`, PTAL 🙏.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 4 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: Refactored `convertResponse` method taking your comments into account.
Sorry that I updated the code too late.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 5]
```diff
@@ -420,63 +419,81 @@ private Object invoke(ServiceRequestContext ctx, HttpRequest req, AggregatedResu
...
-                              .contentType(negotiatedResponseMediaType);
+    private ResponseHeaders buildResponseHeaders(ServiceRequestContext ctx) {
+        return addContentTypeIfNeeded(ctx, ResponseHeaders.builder(defaultStatus)).build();
     }
 
-    private ResponseHeaders setHttpStatus(ResponseHeadersBuilder headers) {
-        if (headers.contains(HttpHeaderNames.STATUS)) {
-            // Do not overwrite HTTP status.
-            return headers.build();
+    private static ResponseHeadersBuilder addContentTypeIfNeeded(ServiceRequestContext ctx,
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:484]: Ignorable) We usually use `maybe` prefix if an operation is performed conditionally. 
```suggestion
    private static ResponseHeadersBuilder maybeAddContentType(ServiceRequestContext ctx,
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java [hunk 6]
```diff
@@ -166,20 +168,24 @@ public static List<AnnotatedServiceElement> find(
...
-        if (statusCodeAnnotation == null) {
-            // Set a default HTTP status code for a response depending on the return type of the method.
-            final Class<?> returnType = method.getReturnType();
-            return returnType == Void.class ||
-                   returnType == void.class ||
-                   KotlinUtil.isSuspendingAndReturnTypeUnit(method) ? HttpStatus.NO_CONTENT : HttpStatus.OK;
+        if (statusCodeAnnotation != null) {
+            final int statusCode = statusCodeAnnotation.value();
+            checkArgument(statusCode >= 0,
+                          "invalid HTTP status code: %s (expected: >= 0)", statusCode);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java:176]: Not releated to this PR but we can remove this validation because `HttpStatus.valueOf()` throws IAE if the status is negative.
```suggestion
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 7]
```diff
@@ -420,63 +419,81 @@ private Object invoke(ServiceRequestContext ctx, HttpRequest req, AggregatedResu
...
-                                                                         HttpHeaders headers) {
+    private ResponseHeaders buildResponseHeaders(ServiceRequestContext ctx, HttpHeaders customHeaders) {
+        final ResponseHeadersBuilder builder;
 
-        final MediaType negotiatedResponseMediaType = ctx.negotiatedResponseMediaType();
-        if (negotiatedResponseMediaType == null || headers.contentType() != null) {
-            // Do not overwrite 'content-type'.
-            return ResponseHeaders.builder()
-                                  .add(headers);
+        // Prefer ResponseHeaders#toBuilder because builder#add is an expensive operation.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:467]: ❤️

**Review by ikhoon — APPROVED** [review]
What a high-quality PR. Thanks a lot, @ks-yim! 💯🚀

**Review by jrhee17 — APPROVED** [review]
Looks really nice! Thanks @ks-yim ! 🙇 👍 🙇

**Comment by ks-yim** [comment]
@ikhoon @jrhee17 Resolved all of your comments! Thanks for the review 👍.

FYI, I am worrying that this PR may cause conflict with https://github.com/line/armeria/pull/4336 because the behavior of `unwrapAsyncType` method has been changed (`unwrapUnaryAsyncType` should be used instead).

**Comment by ikhoon** [comment]
> FYI, I am worrying that this PR may cause conflict with https://github.com/line/armeria/pull/4336 because the behavior of unwrapAsyncType method has been changed (unwrapUnaryAsyncType should be used instead).

Thanks for the note. Let me handle the conflict after merging this PR. 😀

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 8]
```diff
@@ -420,63 +419,80 @@ private Object invoke(ServiceRequestContext ctx, HttpRequest req, AggregatedResu
...
-            result = httpResult.content();
-            newTrailers = httpResult.trailers();
-        } else {
-            newHeaders = setHttpStatus(
-                    headers == null ? addNegotiatedResponseMediaType(ctx, HttpHeaders.of())
-                                    : ResponseHeaders.builder().add(headers));
-            newTrailers = trailers;
-        }
-
+    private HttpResponse convertResponse(ServiceRequestContext ctx, @Nullable Object result) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:422]: Thanks for cleaning this method. 👍

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 9]
```diff
@@ -420,63 +419,80 @@ private Object invoke(ServiceRequestContext ctx, HttpRequest req, AggregatedResu
...
-                                                                         HttpHeaders headers) {
+    private ResponseHeaders buildResponseHeaders(ServiceRequestContext ctx, HttpHeaders customHeaders) {
+        final ResponseHeadersBuilder builder;
 
-        final MediaType negotiatedResponseMediaType = ctx.negotiatedResponseMediaType();
-        if (negotiatedResponseMediaType == null || headers.contentType() != null) {
-            // Do not overwrite 'content-type'.
-            return ResponseHeaders.builder()
-                                  .add(headers);
+        // Prefer ResponseHeaders#toBuilder because builder#add is an expensive operation.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:466]: Let's use `builder#add(Iterable)` because it may confuse others. Or we can remove this sentence completely.

**Review by minwoox — APPROVED** [review]
Still LGTM and left just one nit. 👍

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 9 above)
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:466]:
```suggestion
        // Prefer ResponseHeaders#toBuilder because builder#add(Iterable) is an expensive operation.
```

**Comment by minwoox** [comment]
Thanks, @ks-yim! 🎉 🎉 🎉
