### PR TITLE
Make `ClosedSessionException` extend `ClosedStreamException`

### LINKED ISSUE #2596: Make `ClosedSessionException` extend `ClosedStreamException`
When a connection is closed, it inherently means that all streams associated with it are closed. Therefore, `ClosedSessionException` could be a `ClosedStreamException`.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

`ClosedSessionException` also means that all sessions are closed.
If `ClosedSessionException` extends `ClosedSessionException`,
a `ClosedSessionException` can be caught by `ClosedSessionException`.
It will be useful when a user wants to make their own retrying strategy.

Modifications:

- Make `ClosedStreamException` extensible
- `ClosedSessionException` extends `ClosedStreamException` instead of `RuntimeException`

Result:

- You can now catch `ClosedSessionException` by `ClosedStreamException`
- Fixes #2596

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java [hunk 1]
```diff
@@ -81,7 +82,7 @@ public static Status fromThrowable(Throwable t) {
         if (s.getCode() != Code.UNKNOWN) {
             return s;
         }
-        if (t instanceof ClosedStreamException) {
+        if (t instanceof ClosedStreamException && !(t instanceof ClosedSessionException)) {
```
Comment (anuraaga) [inline grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: Can we add a helper somewhere that just returns this boolean condition with documentation? It's not clear to me what the semantic meaning of this is. Or perhaps it's an overridden method of `ClosedStreamException`.

Though one thought is given the complexity of this sort of check, is it actually a good idea to have the inheritance relationship after all?

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: > Can we add a helper somewhere that just returns this boolean condition with documentation?

That's good. Will add it to `Exceptions`.

> Though one thought is given the complexity of this sort of check, is it actually a good idea to have the inheritance relationship after all?

I know both approaches have cons. 
- Cons of inheritance: Devs should pay attention to filter an exception caused by a closed stream not closed session. 
- Cons of isolation: When a request fails to write a stream, users should catch both `ClosedStreamException` and `ClosedSessionException`. Because it could be failed by a closed session.

Comment (anuraaga) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: I think it's common for methods to throw different types of exceptions and Java even has special syntax to catch `ClosedStreamException | ClosedSessionException`. 

On the flip side, filtering subclasses when working with anything, even non-exceptions is quite unusual. Inheritance should express "is a", so I don't find it to be idiomatic in Java to want to catch `ClosedStreamException` but not want it's subclasses, which are supposed to be semantically the same.

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: > filtering subclasses when working with anything, even non-exceptions is quite unusual.

Yes, I understand what you are concerned about and greatly appreciate your opinion. 🙏 Let's discuss this with other folks at the beginning of next week. 😀

Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: My guess is that most users wouldn't need to distinguish between closed streams and closed sessions, while Armeria devs might in some cases, so it's probably better for users' standpoint?

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: question: Don't we need to return `Status.CANCELLED` for `ClosedSessionException`?

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: That's an interesting point. I've tried to keep the original condition. 
Any thoughts on this @anuraaga ?

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: The test with reverting this, `GrpcServiceServerTest.clientSocketClosedBeforeHalfClose` is failed.
https://github.com/line/armeria/blob/46eff82ddbf52af751fb31debc2273638ae6a5f9/grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java#L807-L808

The assert of the test expects `UNKNOWN` when the connection has been closed.

Comment (anuraaga) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: Upstream only uses CANCELLED with `RST_STREAM`. Actually it is a bit more complex, looking at the http error code too which I guess we aren't but don't think we can catch connection failure here.

It's hard to know what a user would do but I guess they might implement a client type and run into this, or otherwise will generally just catch `Throwable` anyways.

Anyways I guess having this sort of complexity is ok, but it looks like wrong Java to me. It makes me question `ClosedStreamException` a little - this was meant to only map `RST_STREAM` but is that still the case?

Also what if stream extends session instead other way around? There is generic concept of session, whild HTTP/2 specializes that to the concept of a stream? Semantically it seems just a little better.

Comment (alex-lx) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: Hi, all. I'm a fan and a user of Armeria and I'm interested in this topic. Would you mind I join the discussion? :-) What's about to create a new base class, let's say `BaseClosedException`, and make both `ClosedSessionException` and `ClosedStreamException` to extend it?

Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: Hi @alex-lx, thanks a *lot* for joining in! Sure, that also could be an option, but I guess we need to name it properly. Another issue is that `ClosedStreamException` is in `com.linecorp.armeria.common.stream` while `ClosedSessionException` is in `com.linecorp.armeria.common`. Which package should the parent exception go to?

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: > Hi, all. I'm a fan and a user of Armeria and I'm interested in this topic.

♥️ Welcome @alex-lx

> What's about to create a new base class, let's say `BaseClosedException`

Yes. That is another option that an exception includes `ClosedSessionException` and `ClosedStreamException`.

Let's say a user make their own `RetryStrategy`:
```
RetryStrategy.onStatus((status, cause) -> {
    // retry if a request fails to write a stream
    if (cause instanceof ClosedStreamException) {
        return backoff;
    }
    return null;
});
```

If we make `ClosedSessionException` and `ClosedStreamException` extend `BaseClosedException`, a user needs to know the exceptions' hierarchy. I'm not sure this is best for Armeria users. 🤔

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: If we want to keep the class hierarchy and need to return `UNKNOWN` for `ClosedSessionException` and `CANCELLED` for `ClosedStreamException`, don't we need to always check if the exception is the subclass or not, first? So that we can get rid of this complex condition?
```suggestion
if (t instanceof ClosedSessionException | t instanceof ClosedChannelException) { // Remove line 88 as well.
    return s;
}
if (t instanceof ClosedStreamException) {
    return Status.CANCELLED;
}
```

Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: > If we make ClosedSessionException and ClosedStreamException extend BaseClosedException, a user needs to know the exceptions' hierarchy. I'm not sure this is the best choice for Armeria users.

I think it's fine since we didn't release 1.0 just yet :-)

File: core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java [hunk 2]
```diff
@@ -106,7 +106,8 @@
 
     static final ChannelFutureListener CLOSE_ON_FAILURE = future -> {
         final Throwable cause = future.cause();
-        if (cause != null && !(cause instanceof ClosedStreamException)) {
+        if (cause != null && (!(cause instanceof ClosedStreamException) ||
+                              cause instanceof ClosedSessionException)) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: `cause instanceof ClosedSessionException` is `true` when the cause is `ClosedStreamException`.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: So I think checking if it's subclass or not is better and readable not to make mistakes.
```java
if (cause instanceof ClosedSessionException) {
    return;
}
...
```

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: `if (cause instanceof ClosedSessionException) {` will return `ClosedSessionException` but,
The `ClosedSessionException` have to invoke `safeClose` so we cannot just return `ClosedSessionException`.

The channel will be closed if:
* the cause is not null
* accept all causes except `ClosedStreamException`

How about inverting the boolean expression?
```java
if (cause == null) {
    return;
}
if (cause instanceof ClosedStreamException && !(cause instanceof ClosedSessionException)) {
    return;
}

// or just one if 
if (cause == null || (cause instanceof ClosedStreamException &&
                      !(cause instanceof ClosedSessionException))) {
    return;
}
```

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: Ah, I didn't mean to return when the `cause` is an instance of `ClosedSessionException`, but call `safeClose`.
The original condition was wrong and I think these kinna expression will confuse others as well.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: So this could be:
```java
static final ChannelFutureListener CLOSE_ON_FAILURE = future -> {
    final Throwable cause = future.cause();
    if (cause == null) {
        return;
    }
    if (cause instanceof ClosedSessionException) {
        logAndSafeClose(future, cause);
        return;
    }
    if (cause instanceof ClosedStreamException) {
        return;
    }
    logAndSafeClose(future, cause);
};

private static void logAndSafeClose(ChannelFuture future, Throwable cause) {
    final Channel ch = future.channel();
    logException(ch, cause);
    safeClose(ch);
}

```

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: And we might change this listener to send RST_STREAM when `cause` is an instance of `ClosedStreamException`.

**Comment by minwoox** [comment]
> And we might change this listener to send RST_STREAM when cause is an instance of ClosedStreamException.

Realize that this is not possible. 🤔

File: core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java (hunk 2 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: Also, I'm wondering if we can add this listener a little bit more inside such as encoder so that we can send RST_STREAM or close the channel completely.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: Let me address this comment once we decide our direction. 😀

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java (hunk 1 above)
Comment (anuraaga) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: I think one reasonable naming would for a base class would be `ClosedByPeerException` - both are the message being closed by the peer. One type of closing is a connection close, another is a HTTP/2 `RST_STREAM`.

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: > let's say BaseClosedException, and make both ClosedSessionException and ClosedStreamException to extend it?

The name of `BaseClosedException` is a little vague.
How about reviving `ClosedPublisherException`(#2468) and making `ClosedSessionException and `ClosedStreamException` extend it?

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: > `ClosedByPeerException`

I think we use the exception even if it's not closed by the peer. For example:
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java#L151

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: Perhaps, we can define another exception for other cases and use `ClosedStreamException` and `ClosedSessionException` only when it's closed by the peer?

Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: > Other cases mean that the client and server want to close the stream and session.

I guess it may not always be easy to determine who closed stream/session and there's nothing much a user can do with such distinction.

Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: After thinking a little bit more, I'm leaning toward the original idea of leaving this PR as it is. Here's why:

- A user doesn't really care about why the stream was aborted but only about whether the stream was aborted or not.
  - If a user wants to know why, then he or she can catch `ClosedSessionException` first, e.g.
    ```java
    try { ... }
    catch (ClosedSessionException e) { ... }
    catch (ClosedStreamException e) { ... }
    // or
    if (e instanceof ClosedSessionException) { ... }
    else if (e instanceof ClosedStreamException) { ... }
    ```
    .. and this isn't that complex. It's like catching `FileNotFoundException` before `IOException`.
- I'm not sure if a common base exception helps the situation. It helps users catch the 'stream closed but not disconnected' case easily, but again, I don't think users are interested in this in most cases. If interested, an extra `instanceof` or `catch()` does the job.

Comment (anuraaga) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java]: Ok SGTM
