### PR TITLE
Fix `#` character encoding in URIs

### LINKED ISSUE #4751: Improper decoding of reserved char by `PathAndQuery`
The purpose of reserved characters is to provide a set of delimiting characters that are distinguishable from other data within a URI. If reserved chars are used as data in a component, they should be percent-encoded. On the other way, percent-encoded reserved chars (`/foo/x%23y.json`) should not be decoded into (`/foo/x#y.json`).

`#` is a reserved char that delimits a fragment. https://www.rfc-editor.org/rfc/rfc1738 says:
> The character "#" is unsafe and should always be encoded because it is used in World Wide Web and in other systems to delimit a URL from a fragment/anchor identifier that might follow it.

However, `PathAndQuery` violates the specification.
```java
assert PathAndQuery.parse("/%23.json").path().equals("/#.json");
```

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

When a path or query string contains a `#` character, Armeria normalizes it into `#` regardless whether its percent-encoded or not. For example, the following two paths are normalized into `/#.json`, which is not desirable:

- `/#.json`
- `/%23.json`

Modifications:

- Made `PathAndQuery` always percent-encode `#`.
- Renamed the poorly named `RESERVER_CHARS`.

Result:

- Fixes #4751
- `#` character is now always percent-encoded in both path and query string.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java [hunk 1]
```diff
@@ -55,31 +55,34 @@ public final class PathAndQuery {
     private static final BitSet ALLOWED_QUERY_CHARS = new BitSet();
 
     /**
-     * The lookup table for the reserved characters that require percent-encoding.
+     * The lookup table for the characters that whose percent encoding must be preserved
+     * when used in a query string because whether they are percent-encoded or not affects
+     * their semantics. For example, 'A%3dB=1' should NOT be encoded into 'A=B=1' because
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java:60]: nit:
```suggestion
     * their semantics. For example, 'A%3dB=1' should NOT be decoded into 'A=B=1' because
```

**Review by minwoox — APPROVED** [review]
Thanks!

**Review by ikhoon — APPROVED** [review]
Thanks!

File: core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java (hunk 1 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java:60]: Let me change to `normalized into`

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

**Comment by minwoox** [comment]
Thanks, @trustin!
