### PR TITLE
Fix file serving from OSGI bundle classloader

### LINKED ISSUE #4371: Failed to serve HttpFile from OSGI bundle classloader
Right now we are checking the protocol to be `file`, `jar:file` and `jrt`
When getting from bundle classloader from OSGI, the protocol is `bundle` which breaks for OSGI now

I could not find any doc talking about it but here is the question in stackoverflow that talks about the URL pattern
https://stackoverflow.com/questions/6474634/how-do-i-access-a-file-inside-an-osgi-bundle

### PR DESCRIPTION
**Pull request by ngyukman**
Motivation:

Able to serve file from OSGI bundle classloader

Modifications:

Add bundle: as the allowed protocol to create HttpFile

Result:

- Closes #4371

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks, @ngyukman!

File: core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java [hunk 1]
```diff
@@ -200,11 +200,12 @@ static HttpFileBuilder builder(URL url) {
 
             return builder(f.toPath());
         } else if ("jar".equals(url.getProtocol()) && url.getPath().startsWith("file:") ||
-                   "jrt".equals(url.getProtocol())) {
+                   "jrt".equals(url.getProtocol()) ||
+                   "bundle".equals(url.getProtocol())) {
             return new ClassPathHttpFileBuilder(url);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java:205]: So this `ClassPathHttpFileBuilder` supports the bundle scheme correctly, right?

Comment (ngyukman) [reply core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java:205]: yes, as it was working before the check introduced here
The actual handling of the scheme is done by OSGi

**Review by jrhee17 — APPROVED** [review]
Thanks @ngyukman 👍 🙇 👍
