### PR TITLE
Do not swallow server errors of `TransientService`

### LINKED ISSUE #3551: Should not swallow errors of `TransientService`
I got a report that `PrometheusExpositionService` is not working without any error logs.
I investigated the reason by debugging the code with some break points.
There was a dependency mismatch and the following line raised `NosuchMethodException`.
https://github.com/line/armeria/blob/198c247f2e9092601e920f900412f3cd1c70d7e0/core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java#L90

The error raised by `PrometheusExpositionService` was not logged, because the `TransientService`s are excluded from `LoggingService` by default.
It is difficult for users to detect errors early. Especially when they are upgrading Armeria versions.
  
I propose to change the sensible default behavior of `LoggingService` for the `TransientService`. 
- As-Is: Do not leave logs for requests served by the `TransientService`
- To-Be: Leave a log for a failed request(5xx Server Error) even though the request is served by `TransientService`.

### PR DESCRIPTION
**Pull request by hexoul**
Motivation:
- #3551 Should not swallow server errors of `TransientService`

Modifications:
- Log response in case of server error regardless of `TransientServiceOption`.
- Modify verifications of `HealthCheckServiceTest` and `PrometheusExpositionServiceTest` as they are `TransientService`s.

Result:
- Leave a log for a failed request(5xx Server Error) even though the request is served by `TransientService`.
- Close #3551

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java [hunk 1]
```diff
@@ -48,13 +50,19 @@ private LoggingDecorators() {}
...
-        });
+        boolean isTransientService = isTransientService(ctx);
+        if (!isTransientService) {
+            ctx.log().whenRequestComplete().thenAccept(requestLogger).exceptionally(e -> {
+                try (SafeCloseable ignored = ctx.push()) {
+                    logger.warn("{} Unexpected exception while logging request: ", ctx, e);
+                }
+                return null;
+            });
+        }
```
[the remark this answers is not in the document]
Comment (hexoul) [reply core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java]: SGTM! Updated.

**Comment by ikhoon** [comment]
The following test looks flaky.
https://github.com/line/armeria/pull/3559/checks?check_run_id=2573691460#step:7:2150
```
HealthCheckServiceTest > waitWithWrongTimeout() FAILED
    Wanted but not invoked:
    logger.isDebugEnabled();
    -> at com.linecorp.armeria.server.healthcheck.HealthCheckServiceTest.waitWithWrongTimeout(HealthCheckServiceTest.java:327)
    Actually, there were zero interactions with this mock.
        at com.linecorp.armeria.server.healthcheck.HealthCheckServiceTest.waitWithWrongTimeout(HealthCheckServiceTest.java:327)
```

File: core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java [hunk 2]
```diff
@@ -48,12 +51,23 @@ private LoggingDecorators() {}
...
+                }
+                return null;
+            });
+        } else {
+            requestCompletionFuture.exceptionally(e -> {
+                try (SafeCloseable ignored = ctx.push()) {
+                    logger.warn("{} Unexpected exception while logging request: ", ctx, e);
+                }
+                return null;
+            });
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java:69]: This `.exceptionally()` call seems to be a duplicate. Could be simplified to:

```java
final CompletableFuture<RequestOnlyLog> requestCompletionFuture;
if (!isTransientService) {
    requestCompletionFuture = ctx.log().whenRequestComplete().thenAccept(...);
} else {
    requestCompletionFuture = ctx.log().whenRequestComplete();
}
requestCompletionFuture.exceptionally(...);
```

**Review by ikhoon — APPROVED** [review]
LGTM once Trustin's comment is addressed.
Thanks a lot! @hexoul

File: core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java (hunk 2 above)
Comment (hexoul) [reply core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java:69]: I also considered. But, even if `whenRequestComplete()` returns `CompletableFuture<RequestOnlyLog>`, `whenRequestComplete().thenAccept(...)` returns `CompletableFuture<Void>`. Meanwhile, raw use of `CompletableFuture` is ambiguous and using a template seems complicated. 🤔

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java:69]: Then, perhaps we can use `thenApply`? 😄
```java
requestCompletionFuture = ctx.log().whenRequestComplete().thenApply(log -> {
    requestLogger.accept(log);
    return log;
});
```
It's a bit verbose though. 😄

**Review by minwoox — APPROVED** [review]
Thanks a lot!

**Comment by hexoul** [comment]
I like this way! https://github.com/line/armeria/pull/3559#discussion_r632249089

**Review by trustin — APPROVED** [review]
Thanks a lot!
