### PR TITLE
Fix byte buf leak when a `ContentTooLargeException` is raised

### LINKED ISSUE #3803: When grpc streams requests over `maxRequestLength`, the request may not be handled
Found this issue while trying to run benchmarks for the `EventLoopStreamMessage` issue

**Background**

This issue tries to address the following comment in benchmarks

https://github.com/line/armeria/blob/3e2185083fdd7ad45b9b7a71cf5b573cbd8791d2/benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/LargePayloadBenchmark.java#L121

I found that increasing `maxRequestLength`, `maxResponseLength` results in the benchmark succeeding with 3 requests.

I also verified that the default `maxRequestLength` is 10MB, which explains why the 3rd request fails.

Although I think it makes sense that the request fails, I believe the problem is that the request isn't processed, and is subsequently terminated due to timeout (the user doesn't know why the 3rd request timed out)

**Analysis**

The 3rd request hits the `maxRequestLength` limit. However, since response headers have already started to be written, the request is aborted

https://github.com/line/armeria/blob/3e2185083fdd7ad45b9b7a71cf5b573cbd8791d2/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L255

It seems like `ArmeriaServerCall` fails to process this and propagate the failure to the client-side.

https://github.com/line/armeria/blob/3e2185083fdd7ad45b9b7a71cf5b573cbd8791d2/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L516

As a result, it seems like the 3rd request isn't processed and the request is idle until timeout kicks in.

**Expected Result**
The stream abortion is notified to the user somehow: either to the client-side via grpc/http code, or at least via logs to the user.
I am yet to analyze further how upstream handles this case

**Note**: I've tested only with http2 for now, but it remains to be analyzed if http1 has the same issue.

### LINKED ISSUE #5180: LEAK: ByteBuf.release() was not called before it's garbage-collected using verison 1.25.2
Hello,
Using armeria version 1.25.2 with spring boot 2.7.7. I am observing the following leak and any pointers on how to go about debugging this would be helpful. Please let me know if you have any more questions

```
LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.handler.codec.http.DefaultHttpContent.release(DefaultHttpContent.java:92)
	io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
	com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:352)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1385)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1259)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1299)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:829)
#2:
	Hint: {8192B, pooled, <unknown>}
	com.linecorp.armeria.common.HttpData.wrap(HttpData.java:110)
	com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:319)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1385)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1259)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1299)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:829)
#3:
	com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:319)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1385)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1259)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1299)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:829)
#4:
	Hint: 'Http1RequestDecoder#0' will handle the message from this point.
	io.netty.handler.codec.http.DefaultHttpContent.touch(DefaultHttpContent.java:86)
	io.netty.handler.codec.http.DefaultHttpContent.touch(DefaultHttpContent.java:25)
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:417)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1385)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1259)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1299)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:829)
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:144)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:108)
	io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:363)
	io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:140)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1385)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1259)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1299)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:829)
: 1 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.```

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
There are three bugs when the size of a request exceeds the max content length:
- The `ResponseHeaders` that are sent to the client and recorded to `RequestLog` are different.
- The `AggregatingDecodedHttpRequest` is not aborted thus `ByteBuf`s are leaked. (When HTTP/1.1 is used)
- The `AggregatingDecodedHttpRequest` does not get through the decorators so `LoggingService` doesn't log the exception.

Modifications:
- Send 413 responses using `HttpResponseSubscriber` instead of sending them from `HttpRequestDecoder` by aborting the response.
  - 413 is not a protocol error so we should send it from the `HttpResponseSubscriber`.
  - If a responseHeaders is already sent, the stream is reset. (the channel is closed if HTTP/1.1) 
- Call `ctx.fireChannelRead()` if the request wasn't handed over to `HttpServerHandler`.
  - This lets the `LoggingService` log the `ContentTooLargeException`.
  - `AggregatingDecodedHttpRequest` is converted to `StreamingDecodedHttpRequest` not to raise an aggregate exception.
- (misc) Raise a stream error instead of a connection error if it is stream level.

Result:
- Fix #3803, #5180
- No more leaks when the size of a request exceeds the max content length.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java [hunk 1]
```diff
@@ -68,18 +68,20 @@ public Void apply(@Nullable AggregatedHttpResponse response, @Nullable Throwable
 
     private void apply0(@Nullable AggregatedHttpResponse response, @Nullable Throwable cause) {
         clearTimeout();
+        if (failIfStreamOrSessionClosed()) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java:71]: Question) Do you mind explaining why this change is necessary?

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 2]
```diff
@@ -394,7 +406,12 @@ public void onRstStreamRead(ChannelHandlerContext ctx, int streamId, long errorC
 
         final ClosedStreamException cause =
                 new ClosedStreamException("received a RST_STREAM frame: " + Http2Error.valueOf(errorCode));
-        req.abortResponse(cause, /* cancel */ true);
+        if (req.needsAggregation() && !req.isInitialized()) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:409]:
```suggestion
        if (req.needsAggregation()) {
            assert !req.isInitialized();
```

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 3]
```diff
@@ -296,7 +303,8 @@ public int onDataRead(
             // Received an empty DATA frame
             if (endOfStream) {
                 req.close();
-                if (req.needsAggregation()) {
+                if (!req.isInitialized()) {
+                    assert req.needsAggregation();
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:307]:
```suggestion
                if (req.needsAggregation()) {
                    assert !req.isInitialized();
```

**Review by jrhee17 — COMMENTED** [review]
> not to raise an aggregate exception.

Do you mind explaining what points raised an aggregate exception?


Also, I think it will take too long for me to thoroughly review this PR.
Feel free to merge without my approval 🤞

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriberUtil.java [hunk 4]
```diff
@@ -50,7 +52,7 @@ private static void failLateSubscriber0(Subscriber<?> lateSubscriber, Throwable
         }
     }
 
-    public static Throwable abortedOrLate(Subscriber<?> oldSubscriber) {
+    public static Throwable abortedOrLate(@Nullable Subscriber<?> oldSubscriber) {
```
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriberUtil.java:55]: It's a cruft. 😓

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java (hunk 2 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:409]: This isn't true because the server can receive an RST_STREAM after the aggregating request is initialized.

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 5]
```diff
@@ -211,13 +211,15 @@ public void onHeadersRead(ChannelHandlerContext ctx, int streamId, Http2Headers
             try {
                 // Trailers is received. The decodedReq will be automatically closed.
                 decodedReq.write(trailers);
-                if (req.needsAggregation()) {
+                if (!req.isInitialized()) {
+                    assert req.needsAggregation();
```
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:215]: My original fix was calling `ctx.fireChannelRead(req);` with the aggregating request itself (without converting to stream request) so I need to check if the `fireChannelRead` method is called or not using `isInitialized()`. But I've changed the logic so let me revert it. 😉

**Comment by minwoox** [comment]
> not to raise an aggregate exception.
Do you mind explaining what points raised an aggregate exception?

An `AggregatingDecodedHttpRequest` must be closed to be subscribed:
https://github.com/line/armeria/blob/871d87297e4d051241589cb1ae95641cbc83f880/core/src/main/java/com/linecorp/armeria/internal/common/stream/AggregatingStreamMessage.java#L94
However, we can just close it without fully receiving the request body.

> Also, I think it will take too long for me to thoroughly review this PR.

Oh, please let me know if there're any points that you don't understand. 😉

File: core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java (hunk 1 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java:71]: If the session closed, we don't have to send the response using `recoverAndWrite(...)`. So we should check this first. 😉

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java]: > AggregatingDecodedHttpRequest is converted to StreamingDecodedHttpRequest not to raise an aggregate exception.

If the request is incomplete, wouldn't be clear to raise an exception when being aggregated?

[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java]: `AggregatingDecodedHttpRequest` was implemented on the assumption that it is aggregated after being closed.
Do you mean we need to fix `AggregatingDecodedHttpRequest` not to raise an exception when aggregated?

File: core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java [hunk 6]
```diff
@@ -186,6 +186,7 @@ public static boolean isExpected(Throwable cause) {
      * Returns {@code true} if the specified exception will cancel the current request or response stream.
      */
     public static boolean isStreamCancelling(Throwable cause) {
+        // TODO(minwoox): return true if the cause is "io.grpc.StatusRuntimeException: CANCELLED"
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java:189]: Maybe file a new issue scheduled for the next milestone?

File: core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java (hunk 1 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java:71]: How about adding some comment?
```suggestion
        // Close early to avoid sending data unnecessarily on a closed stream.
        if (failIfStreamOrSessionClosed()) {
```

File: core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java [hunk 7]
```diff
@@ -100,6 +102,11 @@ static DecodedHttpRequest of(boolean endOfStream, EventLoop eventLoop, int id, i
      */
     void abortResponse(Throwable cause, boolean cancel);
 
+    /**
+     * Tells whether {@link #abortResponse(Throwable, boolean)} was called or not.
+     */
+    boolean abortedResponse();
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java:108]: `isResponseAborted`?

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 8]
```diff
@@ -280,6 +282,11 @@ public int onDataRead(
                 logInvalidStream = true;
             }
         } else {
+            if (req.abortedResponse()) {
+                // Additional DATA frame can be sent after the response has been aborted.
+                return dataLength + padding;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:287]: Maybe you meant this:
```suggestion
                // Discard the DATA frame received after the response has been aborted
                // because an aborted response means we have finished handling the
                // request.
                return dataLength + padding;
```

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 9]
```diff
@@ -310,53 +318,44 @@ public int onDataRead(
...
-                decodedReq.abort();
+                decodedReq.abortResponse(httpStatusException, true);
             }
         } else if (decodedReq.isOpen()) {
             try {
                 // The decodedReq will be automatically closed if endOfStream is true.
                 decodedReq.write(HttpData.wrap(data.retain()).withEndOfStream(endOfStream));
-                if (endOfStream && decodedReq.needsAggregation()) {
+                if (endOfStream && req.needsAggregation()) {
+                    assert !req.isInitialized();
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:344]: Should we move the assertion into `needsAggregation()` and `isInitialized()`, given that you always do an assertion for them? e.g.

```java
boolean needsAggregation() {
  assert !needsAggregation || !initialized :
      "needsAggregation: " ... + ", isInitialized: " + ...;
  return needsAggregation;  
}
```

File: core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java [hunk 10]
```diff
@@ -43,20 +43,22 @@ final class StreamingDecodedHttpRequest extends DefaultHttpRequest implements De
     private final long requestStartTimeNanos;
     private final long requestStartTimeMicros;
     private final boolean http1WebSocket;
+    private final boolean resetAfterResponseSent;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java:46]: How about renaming to `shouldResetAfterSendingResponse`?

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java (hunk 9 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:344]: There's one exception that is calling it when received an RST stream so we cannot add the assertion.
https://github.com/line/armeria/blob/86d656927dfd363f5bd371c0ace8cbe5588ac4f8/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L396

File: core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java (hunk 6 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java:189]: Created. https://github.com/line/armeria/issues/5254 😉

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java:189]: Thanks!

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java (hunk 9 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:346]: I see. No worries, then!

**Review by trustin — APPROVED** [review]
:+1:

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 11]
```diff
@@ -310,53 +320,44 @@ public int onDataRead(
...
+                    ContentTooLargeException.builder()
+                                            .maxContentLength(maxContentLength)
+                                            .contentLength(req.headers())
+                                            .transferred(transferredLength)
+                                            .build();
+
+            final HttpStatusException httpStatusException =
+                    HttpStatusException.of(HttpStatus.REQUEST_ENTITY_TOO_LARGE, cause);
+            if (req.needsAggregation()) {
+                assert !req.isInitialized();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:333]: Should we use `decodedReq` for consistency?
```suggestion
            if (decodedReq.needsAggregation()) {
                assert !decodedReq.isInitialized();
```

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 12]
```diff
@@ -310,53 +320,44 @@ public int onDataRead(
...
-                decodedReq.abort();
+                decodedReq.abortResponse(httpStatusException, true);
             }
         } else if (decodedReq.isOpen()) {
             try {
                 // The decodedReq will be automatically closed if endOfStream is true.
                 decodedReq.write(HttpData.wrap(data.retain()).withEndOfStream(endOfStream));
-                if (endOfStream && decodedReq.needsAggregation()) {
+                if (endOfStream && req.needsAggregation()) {
+                    assert !req.isInitialized();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:346]: Ditto

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java (hunk 2 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:398]: > request is initialized.

Q: Initialization seems more important to call `req.toAbortedStreaming()`. What do you think of checking `req.isInitialized()` where a call to `req.toAbortedStreaming()` is necessary for here and L335?
```java
if (!req.isInitialized()) {
   ctx.fireChannelRead(req.toAbortedStreaming(inboundTrafficController, cause, false));
}
```

**Review by ikhoon — COMMENTED** [review]
Overall looks good.

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java (hunk 2 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:398]: That's a good suggestion. Let me change it back. 😉

File: core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java [hunk 13]
```diff
@@ -82,8 +82,14 @@ public final ChannelFuture doWriteData(int id, int streamId, HttpData data, bool
     }
 
     @Override
-    public final ChannelFuture doWriteReset(int id, int streamId, Http2Error error) {
+    public final ChannelFuture doWriteReset(int id, int streamId, Http2Error error,
+                                            boolean sendResetIfRemoteIsOpen) {
         final Http2Stream stream = encoder.connection().stream(streamId);
+
+        if (sendResetIfRemoteIsOpen && !stream.state().localSideOpen()) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java:89]: Q: Why is the local side open checked? `sendResetIfRemoteIsOpen` says reset if the remote is open.

File: core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseSubscriber.java [hunk 14]
```diff
@@ -384,6 +384,9 @@ private void addCallbackAndFlush(Throwable cause, State oldState, ChannelFuture
                 try (SafeCloseable ignored = RequestContextUtil.pop()) {
                     if (f.isSuccess() && !isReset) {
                         maybeLogFirstResponseBytesTransferred();
+                        if (req.shouldResetIfRemoteIsOpen()) {
+                            responseEncoder.writeReset(req.id(), req.streamId(), Http2Error.CANCEL, false);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseSubscriber.java:388]: Should be? Because `shouldResetIfRemoteIsOpen` is true.
```suggestion
                            responseEncoder.writeReset(req.id(), req.streamId(), Http2Error.CANCEL, true);
```

File: core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java (hunk 13 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java:89]: I copied it from [here](https://github.com/line/armeria/blob/b2e31ee12941a7dd3883dde3a66f3ececa94e8fb/core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java#L135-L137) and I think it's also fixed. 😓

File: core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java [hunk 15]
```diff
@@ -82,11 +82,15 @@ public final ChannelFuture doWriteData(int id, int streamId, HttpData data, bool
...
     @Override
-    public final ChannelFuture doWriteReset(int id, int streamId, Http2Error error) {
+    public final ChannelFuture doWriteReset(int id, int streamId, Http2Error error,
+                                            boolean sendResetIfRemoteIsOpen) {
         final Http2Stream stream = encoder.connection().stream(streamId);
+
         // Send a RST_STREAM frame only for an active stream which did not send a RST_STREAM frame already.
         if (stream != null && !stream.isResetSent()) {
-            return encoder.writeRstStream(ctx, streamId, error.code(), ctx.newPromise());
+            if (!sendResetIfRemoteIsOpen || stream.state().remoteSideOpen()) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java:91]: Q: Do we need to send RST_FRAME when half-close on remote? An EOF for the stream has been received from the remote peer already.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java]: Change not to send RST if EOF is received. 😉

**Review by ikhoon — APPROVED** [review]
Thanks for handling this non-trivial issue. 🙇‍♂️🙇‍♂️

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 16]
```diff
@@ -320,13 +339,14 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
...
 
-                if (msg instanceof LastHttpContent) {
+                if (endOfStream) {
                     final HttpHeaders trailingHeaders = ((LastHttpContent) msg).trailingHeaders();
                     if (!trailingHeaders.isEmpty()) {
                         decodedReq.write(ArmeriaHttpUtil.toArmeria(trailingHeaders));
                     }
                     decodedReq.close();
                     if (decodedReq.needsAggregation()) {
+                        assert !decodedReq.isInitialized();
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:349]: Looks like this can be removed

```suggestion
```

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 17]
```diff
@@ -297,6 +306,7 @@ public int onDataRead(
             if (endOfStream) {
                 req.close();
                 if (req.needsAggregation()) {
+                    assert !req.isInitialized();
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:309]: Seems like we can remove this assertion

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 18]
```diff
@@ -212,12 +212,14 @@ public void onHeadersRead(ChannelHandlerContext ctx, int streamId, Http2Headers
                 // Trailers is received. The decodedReq will be automatically closed.
                 decodedReq.write(trailers);
                 if (req.needsAggregation()) {
+                    assert !req.isInitialized();
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:215]: ditto, can remove this assertion

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java (hunk 2 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java]: The original reason for my suggestion was because I wanted to do some testing on rescheduling the layer between channel and service event loops.

Let me just handle this separately then if needed

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 19]
```diff
@@ -306,12 +307,30 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
...
-                        decodedReq.abortResponse(
-                                HttpStatusException.of(HttpStatus.REQUEST_ENTITY_TOO_LARGE, cause),
-                                true);
+                        final HttpStatusException httpStatusException =
+                                HttpStatusException.of(HttpStatus.REQUEST_ENTITY_TOO_LARGE, cause);
+                        if (!decodedReq.isInitialized()) {
+                            assert decodedReq.needsAggregation();
+                            final StreamingDecodedHttpRequest streamingReq = decodedReq.toAbortedStreaming(
+                                    inboundTrafficController, httpStatusException, shouldReset);
+                            ctx.fireChannelRead(streamingReq);
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:329]: Question) It seems like we don't early return when `encoder` is swapped to http2 and an upgrade request is received.

Is there a code point where we guard against `ctx.fireChannelRead` being invoked twice? (once for HTTP1 upgrade, once for HTTP2)

**Review by jrhee17 — APPROVED** [review]
Only left a minor question but looks good 👍  Thanks @minwoox 🙇 👍 🙇

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 19 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:329]: Sure. 😉 
An `UpgradeEvent` is created when it receives the upgrade event:
https://github.com/line/armeria/blob/b7c14c4564f7137b421292fb01bda0ee58fbe93b/core/src/main/java/com/linecorp/armeria/server/HttpServerUpgradeHandler.java#L297
`Http2ConnectionHandler` is added to the pipleline:
https://github.com/line/armeria/blob/e7be74e738a49448afe98773e1bbf7ab09080c2f/core/src/main/java/com/linecorp/armeria/server/Http2ServerUpgradeCodec.java#L109
`Http1RequestDecoder` receives the `UpgradeEvent` and calls `channelRead()` with the HTTP/1.1 request:
https://github.com/line/armeria/blob/091d193bac243d1463a03bd42a5174b88adb479e/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L453
After handling the request, `Http1RequestDecoder` is removed:
https://github.com/line/armeria/blob/091d193bac243d1463a03bd42a5174b88adb479e/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L275-L279

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:329]: My question was rather when `ctx.pipeline().remove(this); ` is called, but the content length of the request is exceeded.

Let me do some testing in my local env. instead and follow up if needed, feel free to merge 😄

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:329]: I misunderstood it. 😓 
No, I didn't consider that case and I have to fix it. Thanks!

**Comment by minwoox** [comment]
Thanks all for the review. 😉
