### PR TITLE
Return `204 No Content` if there is no response converter for 'null' …

### LINKED ISSUE #1165: NPE from void service method
Void service methods throw a NPE and result in a `HTTP 500 Internal Server Error` response. IMHO they shouldn't result in a NPE and be handled as `HTTP 204 No Content`.

```java
public class FooService {
  @Get("/foo")
  public void doFoo() {
  }
}
```

```java
2018-04-26 12:53:23,200 [armeria-common-worker-epoll-5-6] HttpResponseSubscriber WARN : [id: 0xbb5add58, L:/127.0.0.1:8080 - R:/127.0.0.1:4052] Unexpected exception from a service or a response publisher: AnnotatedHttpService{pathMapping=[exact:/foo, {supportedMethods=[GET], consumeTypes=[], produceTypes=[]}], delegate=com.linecorp.armeria.server.AnnotatedHttpServiceMethod@5fafa7d1, decorator=java.util.function.Function$$Lambda$34/1952194564@58efa595}
 java.lang.NullPointerException: null
	at com.linecorp.armeria.server.AnnotatedHttpServiceMethod.convertResponse(AnnotatedHttpServiceMethod.java:218) ~[armeria-0.62.0.jar:?]
	at com.linecorp.armeria.server.AnnotatedHttpServiceMethod.lambda$serve$0(AnnotatedHttpServiceMethod.java:124) ~[armeria-0.62.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[?:1.8.0_162]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[?:1.8.0_162]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_162]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) ~[?:1.8.0_162]
	at com.linecorp.armeria.common.AbstractRequestContext.lambda$makeContextAware$1(AbstractRequestContext.java:72) ~[armeria-0.62.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.24.Final.jar:4.1.24.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

### PR DESCRIPTION
**Pull request by hyangtack**
…result

Modifications:
- Return `204 No Content` response if there is no response converter which is able to convert 'null' result to a response. Until now, `500 Internal Server Error` has been sent.

Result:
- Closes #1165

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java [hunk 1]
```diff
@@ -214,9 +215,14 @@ private HttpResponse convertResponse(ServiceRequestContext ctx, @Nullable Object
...
         }
+        // There is no response converter which is able to convert 'null' result to a response.
+        // In this case, we deal the result as '204 No Content' instead of '500 Internal Server Error'.
+        if (result == null) {
+            return HttpResponse.of(HttpStatus.NO_CONTENT);
+        }
         throw new IllegalStateException(
                 "No response converter exists for a result: " +
-                result != null ? result.getClass().getSimpleName() : "(null)");
+                (result != null ? result.getClass().getSimpleName() : "(null)"));
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java]: Then we can simply do `"No response converter exists for a result: " + result.getClass().getSimpleName()`

Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java]: Oops! You're right. Thanks!

**Comment by trustin** [comment]
Thanks, @hyangtack !
