### PR TITLE
Fix a bug where CORS headers are not injected when a `ServerErrorHandler` is set

### LINKED ISSUE #5493: `CorsService` does not inject CORS headers to error responses
I've created an error handler, and they won't affected by `CorsDecorator` I've attached...

```kotlin
Server.builder().apply {
        errorHandler(ServiceExceptionHandler())
        errorHandler(UniversalFailureHandler())
        errorHandler(UniversalIgnoreHandler())
        errorHandler(UniversalExceptionHandler())
        http(14000)

        decorator(corsDecorator)
}
```

 In this situation, cors won't do their Jobs when error Handler catches the error.

I've digged some code and figured that decorators and errorHandlers are managed differently... Is there any way to decorate errorHandlers to follow the CORS rules?

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

`ServerErrorHandler.renderStatus()` is used in `DefaultServerErrorHandler` and may not be called in a custom `ServerErrorHandler`. Attempting to inject CORS headers via `CorsServerErrorHandler.renderStatus()` may not work.

Modifications:

- Use `ctx.mutateAdditionalResponseHeaders()` to set CORS headers instead of mutating the response headers.
- Store whether a CORS is set by `CorsService` to ctx.attr().
  - The value is used in `CorsServerErrorHandler` to set if missing

Result:

- CORS headers for failed requests are now correctly set even when a custom `ServerErrorHandler` is configured.
- Fixes #5493

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java [hunk 1]
```diff
@@ -50,49 +47,19 @@ public AggregatedHttpResponse renderStatus(@Nullable ServiceRequestContext ctx,
...
-                return null;
-            }
-            final CorsService corsService = ctx.findService(CorsService.class);
-            if (corsService == null) {
-                return oldRes;
-            }
-            return oldRes.recover(HttpResponseException.class, ex -> {
-                return ex.httpResponse()
-                         .mapHeaders(oldHeaders -> addCorsHeaders(ctx, corsService.config(), oldHeaders));
+        final CorsService corsService = ctx.findService(CorsService.class);
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java:56]: Note: this was a problem before also, but preflight requests won't be handled correctly if an exception occurs before reaching `CorsService`.

Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java:56]: Note: This is also a similar issue, but a debug level log will be printed every time an exception is thrown for an Origin which doesn't have a policy defined:

https://github.com/line/armeria/blob/683bd74b91eec18a1a5007c4ac1013327e7b5a62/core/src/main/java/com/linecorp/armeria/internal/server/CorsHeaderUtil.java#L127

Normally, this log wouldn't be printed if a request goes through `CorsService`

**Review by jrhee17 — APPROVED** [review]

File: core/src/main/java/com/linecorp/armeria/internal/server/CorsHeaderUtil.java [hunk 2]
```diff
@@ -47,6 +50,8 @@ public final class CorsHeaderUtil {
     public static final String DELIMITER = ",";
     private static final Joiner HEADER_JOINER = Joiner.on(DELIMITER);
 
+    private static AttributeKey<Boolean> IS_CORS_SET = AttributeKey.valueOf(CorsService.class, "IS_CORS_SET");
+
     public static ResponseHeaders addCorsHeaders(ServiceRequestContext ctx, CorsConfig corsConfig,
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/CorsHeaderUtil.java:55]: Nice catch!

File: core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java (hunk 1 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java:59]: I've changed to apply CORS headers only for [simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests
).

If there is an error in processing preflight requests, I don't think we need to set CORS headers.

**Review by minwoox — APPROVED** [review]
👍 👍 👍
