### PR TITLE
Fix a bug where reactive-grpc fails to send stream responses

### LINKED ISSUE #3090: Q. Does armeria + grpc-reactor require the response be written from armeria's event loop?
I have an armeria server serving requests using grpc-reactor and have to say it's looking pretty good so far 👍 

All seemed to work well, except I found that some responses were disappearing without any indications in logging.

After looking at armeria+grpc-reactor examples, I am guessing the response should be written via armeria's event loop.

https://github.com/line/armeria/blob/464521caef452c0d04e7bbb262dceb8dfce2d7e3/examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java#L81

I would like to check if my understanding is correct before moving forward

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

Reactive gRPC starts to subscribe to upstream messages when `onReady` signal is delivered.
https://github.com/salesforce/reactive-grpc/blob/ce3b3b20e8192c5e6b38b2ed596531242d9708c0/common/reactive-grpc-common/src/main/java/com/salesforce/reactivegrpc/common/AbstractSubscriberAndProducer.java#L91-L97
Upstream gRPC-Java server invokes the signal - `onReady` when an HTTP headers is received.
https://github.com/grpc/grpc-java/blob/9b73e2365da502a466b01544f102cd487e374428/core/src/main/java/io/grpc/internal/AbstractStream.java#L280-L287

However, `ArmeriaServerCall` invokes `listener.onReady()` only when a response is written completely.
https://github.com/line/armeria/blob/2bc23e60cea9f6adc1415c8d08a34baf2b90ce80/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L254-L262

This is a deadlock because:
- `ArmeriaServerCall` waits a message and calls `onReady()`.
- Reactive gRPC waits `onReady()` signal and send a message.

Modifications:

- Invoke `listener.onReady()` as soon as it is set and `onHalfClose()` is invoked

Result:

- Armeria gRPC server now invokes `ServerCall.Listener.onReady()` properly.
- You no longer see `UNKNOWN` error code while sending stream messages with Reactive gRPC stub.
- Fixes #3090

### CODE REVIEW

**Review by trustin — APPROVED** [review]
We are using examples as a test suite which is not a good idea in my opinion.

Could we simplify the examples and move this sort of tests to somewhere else like `armeria-grpc`? Perhaps in a follow-up PR.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java [hunk 1]
```diff
@@ -431,6 +431,7 @@ private void invokeHalfClose() {
         try (SafeCloseable ignored = ctx.push()) {
             assert listener != null;
             listener.onHalfClose();
+            listener.onReady();
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java:434]: Is there any chance where `onReady()` is called multiple times? e.g. `invokeHalfClosed()` is called after `setListener()`.

**Comment by ikhoon** [comment]
> Could we simplify the examples and move this sort of tests to somewhere else like armeria-grpc? Perhaps in a follow-up PR.

That's a good idea! I've added many test code in the example. 🙈

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java (hunk 1 above)
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java]: I missed pushing my last work. (https://github.com/line/armeria/pull/3099/commits/0ff6981f8f1a4dd07d9b660a7c0b354f14ab005b)
I do not fully understand the `listener`'s life cycle. Based on the upstream gRPC server, the `listener.onReady()` is called two times if it is an unary stream listener.
1) When a stream is activated
2) `onHalfClose()` is invoked

---
-  `onHalfClose` in `StreamingServerCallListener` does not call `onReady`.
https://github.com/grpc/grpc-java/blob/9b73e2365da502a466b01544f102cd487e374428/stub/src/main/java/io/grpc/stub/ServerCalls.java#L263-L267
```java
      @Override
      public void onHalfClose() {
        halfClosed = true;
        requestObserver.onCompleted();
      }
```

- `onHalfClose` in `UnaryServerCallListener` calls `onReady`.
https://github.com/grpc/grpc-java/blob/9b73e2365da502a466b01544f102cd487e374428/stub/src/main/java/io/grpc/stub/ServerCalls.java#L170-L190
```java
      public void onHalfClose() {
        if (!canInvoke) {
          return;
        }
        if (request == null) {
          // Safe to close the call, because the application has not yet been invoked
          call.close(
              Status.INTERNAL.withDescription(MISSING_REQUEST),
              new Metadata());
          return;
        }


        method.invoke(request, responseObserver);
        request = null;
        responseObserver.freeze();
        if (wasReady) {
          // Since we are calling invoke in halfClose we have missed the onReady
          // event from the transport so recover it here.
          onReady();
        }
      }
```

Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java]: I see. So it's meant to be invoked multiple times whenever something's ready. Thanks for explanation!

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java]: Yes. :-)

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java]: FJYI, the Javadoc for `Listener.onReady()
```
     * This indicates that the call may now be capable of sending additional messages (via
     * {@link #sendMessage}) without requiring excessive buffering internally. This event is
     * just a suggestion and the application is free to ignore it, however doing so may
```
https://github.com/grpc/grpc-java/blob/18e7e2ddca1323bcdfec4649d7a1dd91a68f8223/api/src/main/java/io/grpc/ServerCall.java#L86-L88

**Review by trustin — APPROVED** [review]
Thanks, @ikhoon !

**Review by minwoox — APPROVED** [review]
The master of Reactive Streams. 👍
