### PR TITLE
Log the exception raised while serializing gRPC metadata

### LINKED ISSUE #4625: Record the exception raised while serializing gRPC metadata
Armeria currently doesn't catch and record the exception raised by `io.grpc.Metadata.serialize()`. As a result, when gRPC fails to serialize some metadata, the request will time out or fail silently. The exception should instead be recorded into `RequestLog.request/responseCause()` so a user can analyze the root cause more easily.

Here's an example stack trace of such exceptions:

```
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
 at io.grpc.Metadata.serialize(Metadata.java:473)
 at io.grpc.InternalMetadata.serialize(InternalMetadata.java:78)
 at com.linecorp.armeria.internal.common.grpc.MetadataUtil.fillHeaders(MetadataUtil.java:68)
 at com.linecorp.armeria.server.grpc.ArmeriaServerCall.statusToTrailers(ArmeriaServerCall.java:663)
 at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doClose(ArmeriaServerCall.java:422)
 at com.linecorp.armeria.server.grpc.ArmeriaServerCall.lambda$close0$6(ArmeriaServerCall.java:362)
 at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:547)
 at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by aki-s**
Motivation:

I found an exception is thrown when "Armeria tries to set Metadata, but the Metadata is corrupted". 

Modifications:

- Log an exception thrown while Armeria tries to set Metadata.
- Returns the default `Metadata` with `INTERNAL` code instead as a fallback `Metadata`.

Result:

- Fixed `GrpcService` to return an INTERNAL error code if an error occurs while serializing gRPC metadata.
- Closes #4625

### CODE REVIEW

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 1]
```diff
@@ -0,0 +1,432 @@
...
+    @AfterAll
+    static void tearDownChannel() {
+        channel.shutdownNow();
+        blockingChannel.shutdownNow();
+    }
+
+    @Test
+    void clientUnaryCall2() throws InterruptedException {
+        Throwable throwable = catchThrowable(() -> {
+            TestServiceBlockingStub service = TestServiceGrpc.newBlockingStub(blockingChannel);
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:126]: We're requesting to `blockingChannel` (which points to `serverWithBlockingExecutor`), but we're checking for the request context for `server` at L136.

I think we want to unify check the request context for the correct server

```suggestion
            TestServiceBlockingStub service = TestServiceGrpc.newBlockingStub(channel);
```

Comment (jrhee17) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:126]: I think once this change is made unary server call tests are passing without a problem. Can you also check? 😄

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 2]
```diff
@@ -0,0 +1,432 @@
...
+        RequestLog log = server.requestContextCaptor().take().log().whenComplete()
+                               .join(); //todo: <- Never 'complete', so timeout. why?
+//         InternalMetadata#serialize causes ArrayIndexOutOfBoundsException.class
+        assertThat(log.responseCause()).isInstanceOf(ArrayIndexOutOfBoundsException.class);
+    }
+
+    @Test
+    void clientUnaryCallServerStreamingOutputCall() throws InterruptedException {
+        Throwable throwable = catchThrowable(() -> {
+            TestServiceBlockingStub service = TestServiceGrpc.newBlockingStub(blockingChannel);
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:168]: I think once this is fixed, then streaming requests is not returned immediately and waits until timeout happens (by default 10 seconds). Can you also also check? 😄 

```suggestion
            TestServiceBlockingStub service = TestServiceGrpc.newBlockingStub(channel);
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java [hunk 3]
```diff
@@ -218,6 +218,8 @@ void doClose(Status status, Metadata metadata, boolean completed) {
             if (res.tryWrite(responseTrailers(ctx, status, metadata, trailersOnly))) {
                 res.close();
             }
+        } catch (RuntimeException e) {
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java:221]: If an exception is raised, we need to create a new `StatusAndMetadata` from the exception. Otherwise, a call fails to write trailers but returns OK status.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java (hunk 1 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java]: Yes, that's right.
My brain was fog when I have implemented.
It's resolved now 🙇

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (aki-s) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java:221]: > How about catching Exception, like we do in UnaryServerCall

@trustin 
There's no checked-exception as of now, so I thought using RuntimeException was natural and narrow.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java (hunk 2 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java]: Now all test ends like a charm.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 4]
```diff
@@ -0,0 +1,288 @@
...
+        });
+
+        RequestLog log = serverWithBlockingExecutor.requestContextCaptor().take().log().whenComplete().join();
+        assertThat(log.responseCause())
+                .isInstanceOf(StatusRuntimeException.class)
+                .satisfies(cause -> {
+                    assertThat(Status.fromThrowable(cause).getCode()).isEqualTo(Status.ABORTED.getCode());
+                    assertThat(Status.trailersFromThrowable(cause)).satisfies(metadata -> {
+                        assertThat(metadata).isEqualTo(validMetadata);
+                    });
```
Comment (aki-s) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:144]: @ikhoon 

The `cause` of L131 and L142 returns different kind of metadata.
Was this a kind of what you afraid of at
https://github.com/line/armeria/pull/4686#discussion_r1124165001 ?

Please point out incorrect assertions in this unit test, as I've never used GRPC of Armeria... I'm sorry...

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java:221]: A checked exception can be thrown unsafely with some trick like https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java#L235

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java [hunk 5]
```diff
@@ -0,0 +1,325 @@
...
+                    .isInstanceOf(StatusRuntimeException.class)
+                    .satisfies(cause -> {
+                        assertThat(Status.fromThrowable(cause).getCode()).isEqualTo(Status.ABORTED.getCode());
+                        assertThat(Status.trailersFromThrowable(cause)).satisfies(metadata -> {
+                            assertThat(metadata).isNotEqualTo(validMetadata);
+                        });
+                    });
+        }
+    }
+
```
Comment (aki-s) [inline grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java:136]: @ikhoon 

I've created new test class from the view point of client.
This class
- uses `GrpcClients.newClient` instead of raw `ManagedChannel`.
- uses `Clients.newContextCaptor()` instead of `ServerExtension#requestContextCaptor`.

It's interesting to compare two test classes side by side.
These two classes are just to compare and confirm current behaviors as of now.
I suspect we need to tidy up response behavior about what should be set.

image

I think I didn't understand what you said here properly,
https://github.com/line/armeria/pull/4686#discussion_r1124165001
but I suspect this might be related to unexpected behavior (e.g. in steaming case, error has occurred at server side, but `GrpcClients.newClient` says it has cancelled the request).
I'm very appreciated if you point out each unexpected line 🙇

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java [hunk 6]
```diff
@@ -0,0 +1,325 @@
...
+                assertThat(Status.trailersFromThrowable(cause)).isNotEqualTo(corruptedMetadata);
+            });
+
+            final RequestLog log = captor.get().log().whenComplete().join();
+            assertThat(log.responseStatus()).isEqualTo(HttpStatus.OK);
+            assertThat(log.responseCause())
+                    .isInstanceOf(StatusRuntimeException.class)
+                    .satisfies(cause -> {
+                        assertThat(Status.fromThrowable(cause).getCode()).isEqualTo(
+                                Status.CANCELLED.getCode());
```
Comment (aki-s) [inline grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java:192]: My understanding is that;

Shouldn't we expect `Status.UNKNOWN` or `INTERNAL` , because the main cause is at server side for example?

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java (hunk 5 above)
Comment (ikhoon) [reply grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java:136]: > I think I didn't understand what you said here properly,

Could you check the gRPC status code on the client side? If a response is [trailers-only](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses), a gRPC status can be acquired from `RequestLog.responseHeaders()`. Otherwise, `RequestLog.responseTrailers()` includes a gRPC status.
```java
final RequestLog log = captor.get().log().whenComplete().join();
String grpcStatus = log.responseHeaders().get(GrpcHeaderNames.GRPC_STATUS);
if (grpcStatus == null) {
    grpcStatus = log.responseTrailres().get(GrpcHeaderNames.GRPC_STATUS);
}

assertThat(grpcStatus).isNotNull();
// Maybe an internal error?
assertThat(grpcStatus).isEqualTo("13");
```

This case also need to cover the interceptor case mentioned in https://github.com/line/armeria/pull/4686#discussion_r1125403731

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java [hunk 7]
```diff
@@ -0,0 +1,325 @@
...
+                        assertThat(Status.trailersFromThrowable(cause)).satisfies(metadata -> {
+                            assertThat(isSameSizeAndNameAndValues(metadata, corruptedMetadata)).isFalse();
+                        });
+                    });
+        }
+    }
+
+    // Error inside #onError at bidirectional streaming RPC
+    @Test
+    void fullDuplexCall() throws Exception {
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java:202]: What do you think of removing the duplex call since it doesn't seem to be adding any value at the moment? (the streaming case is covered by `clientUnaryCallServerStreamingOutputCall` test

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorFromServerViewTest.java [hunk 8]
```diff
@@ -0,0 +1,299 @@
...
+
+import io.grpc.InternalMetadata;
+import io.grpc.ManagedChannel;
+import io.grpc.ManagedChannelBuilder;
+import io.grpc.Metadata;
+import io.grpc.Status;
+import io.grpc.StatusRuntimeException;
+import io.grpc.stub.StreamObserver;
+
+class GrpcServiceImplErrorFromServerViewTest {
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorFromServerViewTest.java:56]: I think the extra test class makes it harder to review the changes 😅   What do you think of just removing one of them?

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java [hunk 9]
```diff
@@ -0,0 +1,325 @@
...
+                @Override
+                public void onCompleted() {
+                    // no-op
+                }
+            };
+        }
+    }
+
+    // Use this method to ensure to escape assertion in the constructor of Metadata.
+    private static boolean isSameSizeAndNameAndValues(Metadata a, Metadata b) {
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java:310]: I think just using `toString` to compare the metadata is sufficient 😄

**Review by jrhee17 — COMMENTED** [review]
I think this PR will likely end up with only a few line changes in the main source and mostly we'll be reviewing that the tests are correctly set up.

I've left some comments on cleaning up tests 🙏

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java (hunk 9 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java:310]: Yeah, if I could, I'll do as you said.
I suspect `toString`  might use invalid `size` field to serialize the field `nameAndValues`, so `IndexOutOfBoundsException` would be thrown. (I didn't check it strictly. I'll check the way of `toString` anyway.)

As far as I've seen, `assertThat#isEqualTo`  fails for `corruptedMetadata`.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorFromServerViewTest.java (hunk 8 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorFromServerViewTest.java:56]: Yes. I strongly agree with you. 👍 Short and simple code is the best for maintainability.

This might be caused by my misunderstanding, but they tests from different view point, from `server` and `client`.
Test for `server` intercepts and checks IO at server side only, and test for `client` intercepts and checks IO at client side only.

This is the reason java package is also split as `com.linecorp.armeria.{server,client}.grpc...
`. It might be better to use `common` package although it tends to be unclear naming. 

The current PR is just ask you experts to see the effect of my changes. 
These are the reason why two test class exist as of now.

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java (hunk 7 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java:202]: I see,
 including https://github.com/line/armeria/pull/4686#discussion_r1126101270,
if there's some prior knowledge about Armeria Server, this test may be useless.

My original intention of creating this test is something like as black box testing.
(Just test all scenarios of GRPC.)

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 10]
```diff
@@ -0,0 +1,307 @@
...
+        try (ClientRequestContextCaptor captor = Clients.newContextCaptor()) {
+            assertThatThrownBy(() -> {
+                final TestServiceBlockingStub client =
+                        GrpcClients.newClient("http://127.0.0.1:" + server.httpPort(),
+                                              TestServiceBlockingStub.class);
+                client.unaryCall2(REQUEST_MESSAGE);
+            }).satisfies(cause -> {
+                assertThat(Status.fromThrowable(cause).getCode()).isEqualTo(Status.ABORTED.getCode());
+                assertThat(Status.trailersFromThrowable(cause)).satisfies(metadata -> {
+                    assertThat(metadata).isEqualTo(validMetadata); // fixme: why unexpectedly fails here.
```
Comment (aki-s) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:152]: @jrhee17 

This is the test for normal case, because the argument for `#onError` uses  `validMetadata`.
I've expected it is retuned to client, but it was not in fact.
What do you think of this?
If we comment count L.152 and L169, then this test case finishes successfully.

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java (hunk 7 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java]: > What do you think of removing the duplex

Yes. I've removed now.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorFromServerViewTest.java (hunk 8 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorFromServerViewTest.java]: > What do you think of just removing one 

Yes. I've removed one.

File: grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java (hunk 9 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServiceImplErrorFromClientViewTest.java]: I've checked, but it fails with `IndexOutOfBoundsException` as I've said unfortunately..

**Review by jrhee17 — COMMENTED** [review]
Looking good 👍

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java [hunk 11]
```diff
@@ -540,7 +540,13 @@ static HttpHeaders statusToTrailers(
         GrpcTrailersUtil.addStatusMessageToTrailers(
                 trailersBuilder, status.getCode().value(), status.getDescription());
 
-        MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        try {
+            MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        } catch (Exception e) {
+            // Continue by squashing catch,
```
[the remark this answers is not in the document]
Comment (aki-s) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java]: Yes.
I've set the status https://github.com/line/armeria/pull/4686/files#diff-77a9c8cba521c7ccb32f217b4a1c0f7f32450a51aeef23ee68b04447c0cecea0R548 . 👍

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java [hunk 12]
```diff
@@ -540,7 +540,14 @@ static HttpHeaders statusToTrailers(
         GrpcTrailersUtil.addStatusMessageToTrailers(
                 trailersBuilder, status.getCode().value(), status.getDescription());
 
-        MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        try {
+            MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        } catch (Exception e) {
+            // Catching exception is necessary, because server implementer could have set corrupted metadata.
+            return trailersBuilder
+                    .set(GrpcHeaderNames.GRPC_STATUS, "13")
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java:548]: Can we extract this into a `private static final` field?

```
private static final String INTERNAL_ERROR_CODE_STR =
    String.valueOf(Status.Code.INTERNAL_ERROR.value());
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java [hunk 13]
```diff
@@ -540,7 +540,14 @@ static HttpHeaders statusToTrailers(
         GrpcTrailersUtil.addStatusMessageToTrailers(
                 trailersBuilder, status.getCode().value(), status.getDescription());
 
-        MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        try {
+            MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        } catch (Exception e) {
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java:545]: Should we log `e`?

Comment (aki-s) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java:545]: Yeh, I think so too.
What do you think @jrhee17 ?

The other code like this has logged this kind of error
with log level of `WARN`.
It might be good to write the log to notify server implementer.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java (hunk 12 above)
Comment (aki-s) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java:548]: Yep.
nits;

How about rewording to

```
    private static final String GRPC_STATUS_CODE_INTERNAL =
            String.valueOf(Status.Code.INTERNAL.value());
```

Code.INTERNAL is 13.
Java is typed language, so I thinkg `_STR` is extra one.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java (hunk 13 above)
Comment (jrhee17) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java:545]: Sure, sounds good

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 14]
```diff
@@ -0,0 +1,319 @@
...
+    @RegisterExtension
+    static ServerExtension server = new ServerExtension() {
+        @Override
+        protected void configure(ServerBuilder sb) {
+            configureGrpcService(sb);
+        }
+    };
+
+    @RegisterExtension
+    static ServerExtension serverUsingCorruptedInterceptor = new ServerExtension() {
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:92]: We may use a single `server` by doing the following:

1. modify `configureGrpcService` to accept an extra prefix
```
private static void configureGrpcService(
    String prefix, ServerBuilder sb, ServerInterceptor... interceptors) {
sb.serviceUnder(prefix, GrpcService.builder().addService(new ServerImplErrorAtMetadataService())
                      .intercept(interceptors).build());
sb.decorator(LoggingService.newDecorator());
}
```

2. Add a service with the interceptor:
```
configureGrpcService("/interceptor", sb, corruptedServerInterceptor);
```

3. Call with a prefix from clients if needed
```
final TestServiceBlockingStub client =
        GrpcClients.builder("http://127.0.0.1:" + server.httpPort())
                   .pathPrefix("/interceptor")
                   .build(TestServiceBlockingStub.class);
```

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 15]
```diff
@@ -0,0 +1,319 @@
...
+            });
+            assertThat(log.responseCause())
+                    .isInstanceOf(StatusRuntimeException.class)
+                    .satisfies(cause -> {
+                        assertThat(Status.fromThrowable(cause).getCode()).isEqualTo(Status.INTERNAL.getCode());
+                        assertThat(Status.trailersFromThrowable(cause)).satisfies(metadata -> {
+                            assertThat(isSameSizeAndNameAndValues(metadata, corruptedMetadata)).isFalse();
+                        });
+                    });
+        }
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:144]: I think we should be checking server-side `responseCause` instead of client-side.

```suggestion
final ServiceRequestContextCaptor serviceCaptor = server.requestContextCaptor();
assertThat(serviceCaptor.size()).isEqualTo(1);
final ServiceRequestContext serviceCtx = serviceCaptor.take();
assertThat(serviceCtx.log().ensureComplete().responseCause())
        .isInstanceOf(IndexOutOfBoundsException.class);
```

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java [hunk 16]
```diff
@@ -540,7 +540,14 @@ static HttpHeaders statusToTrailers(
         GrpcTrailersUtil.addStatusMessageToTrailers(
                 trailersBuilder, status.getCode().value(), status.getDescription());
 
-        MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        try {
```
Comment (jrhee17) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java:543]: What do you think of moving this statement before L540?
The line above may add a message which may turn out to be invalid if an exception is reached here

**Review by jrhee17 — COMMENTED** [review]
Looks close to finish, left some minor comments 🙇

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 17]
```diff
@@ -0,0 +1,319 @@
...
+
+    private static void configureGrpcService(
+            ServerBuilder sb, ServerInterceptor... interceptors) {
+        sb.service(GrpcService.builder().addService(new ServerImplErrorAtMetadataService())
+                              .intercept(interceptors).build());
+        sb.decorator(LoggingService.newDecorator());
+    }
+
+    // Use this method to ensure to escape assertion in the constructor of Metadata.
+    private static boolean isSameSizeAndNameAndValues(Metadata a, Metadata b) {
```
[the remark this answers is not in the document]
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:304]: Yes.
You noticed good points.
Current commit is useless, so it's better to be deleted.

I had thought that it might be better to create `this-metadata-is-not-contained` method instead.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java (hunk 15 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:144]: Why do you think so?

From the implementor side of client,
we should test from the view point of client (mine) (JFYI: https://github.com/line/armeria/pull/4686#discussion_r1127457836).

But from the implementor of server side,
your suggestion is right.

As a conclusion,
should not we accept the both tests?

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java (hunk 14 above)
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:92]: This looks good, because this follows Armeria's `decorator` visitor design pattern.
I'll try to apply your suggestion.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java (hunk 15 above)
Comment (jrhee17) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java]: > From the implementor side of client,
we should test from the view point of client (mine) (JFYI: https://github.com/line/armeria/pull/4686#discussion_r1127457836).

I think the original comment you mentioned is referring to checking headers/trailers which make sense.

The current code I mentioned above seems to be checking whether the correct `StatusRuntimeException` will be raised if `grpc-status = 13` is returned.

I think it's fine to check this, but I still think we need the check on `ServiceRequestContextCaptor` which is missing at the moment. Without the check on server-side, I would guess server-side owners will not be aware of why a response has failed if the cause is not shown in server-side `log.responseCause`.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java (hunk 16 above)
Comment (jrhee17) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java]: Is it possible that with an invalid metadata, the status is overridden but the message is not?

https://github.com/line/armeria/blob/be306ab4c9de5386e74999baec5ebaae82618b91/grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/GrpcTrailersUtil.java#L50

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java [hunk 18]
```diff
@@ -540,7 +540,14 @@ public static HttpHeaders statusToTrailers(
         GrpcTrailersUtil.addStatusMessageToTrailers(
                 trailersBuilder, status.getCode().value(), status.getDescription());
 
-        MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        try {
+            MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        } catch (Exception e) {
+            // Catching exception is necessary, because server implementer could have set corrupted metadata.
+            return trailersBuilder
+                    .set(GrpcHeaderNames.GRPC_STATUS, "13")
```
Comment (jrhee17) [inline grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java:548]: Can we extract the `13` to a meaningful field variable so that others don't have to look up the code value to know what this means?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java (hunk 16 above)
Comment (aki-s) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java]: Oh, I see. For the consistency. This makes sence.

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java [hunk 19]
```diff
@@ -540,7 +540,14 @@ public static HttpHeaders statusToTrailers(
         GrpcTrailersUtil.addStatusMessageToTrailers(
                 trailersBuilder, status.getCode().value(), status.getDescription());
 
-        MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        try {
+            MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        } catch (Exception e) {
```
[the remark this answers is not in the document]
Comment (aki-s) [reply grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java:544]: ok.

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 20]
```diff
@@ -0,0 +1,299 @@
...
+                    Payload.newBuilder().setBody(ByteString.copyFromUtf8("pong1")).build()).build());
+            if (request.equals(STREAMING_OUTPUT_CALL_REQUEST_MESSAGE)) {
+                responseObserver.onError(
+                        new StatusRuntimeException(Status.FAILED_PRECONDITION, corruptedMetadata));
+                return; // onError must be the last call.
+            }
+            // The following lines are not reached.
+            responseObserver.onNext(StreamingOutputCallResponse.newBuilder().setPayload(
+                    Payload.newBuilder().setBody(ByteString.copyFromUtf8("pong2")).build()).build());
+            responseObserver.onCompleted();
```
[the remark this answers is not in the document]
Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java]: OK. I did. Please check [9aa63d5](https://github.com/line/armeria/pull/4686/commits/9aa63d5bfb638cf77df536e6eb9f79898bd97229)

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 21]
```diff
@@ -0,0 +1,303 @@
...
+                            assertThat(metadata.keys()).doesNotContain(KEY_OF_CORRUPTED_METADATA);
+                        });
+                    });
+
+            // Test from server side viewpoint.
+            final ServiceRequestContextCaptor serviceCaptor = server.requestContextCaptor();
+            assertThat(serviceCaptor.size()).isEqualTo(1);
+            final ServiceRequestContext serviceCtx = serviceCaptor.take();
+            assertThat(serviceCtx.log().ensureComplete().responseCause())
+                    .isInstanceOf(StatusRuntimeException.class)
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:148]: What do you think of setting the out of bounds exception to `RequestLog#responseCause`?

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java [hunk 22]
```diff
@@ -0,0 +1,303 @@
...
+            assertThat(log.responseStatus()).isEqualTo(HttpStatus.OK);
+            assertThat(log.responseTrailers().get(GrpcHeaderNames.GRPC_STATUS)).isNull();
+            assertThat(log.responseHeaders().get(GrpcHeaderNames.GRPC_STATUS)).satisfies(grpcStatus -> {
+                assertThat(grpcStatus).isNotNull();
+                assertThat(grpcStatus).isEqualTo(String.valueOf(Status.ABORTED.getCode().value()));
+            });
+            assertThat(log.responseCause())
+                    .isInstanceOf(StatusRuntimeException.class)
+                    .satisfies(cause -> {
+                        assertThat(Status.fromThrowable(cause).getCode()).isEqualTo(Status.ABORTED.getCode());
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:192]:
```suggestion
                        assertThat(Status.fromThrowable(cause).getCode()).isEqualTo(Status.INTERNAL.getCode());
```

I think this probably needs to be `INTERNAL` since that was what was sent from server-side.
To do this, I guess we can't get away with catching the exception in `AbstractServerCall#statusToTrailers` and we need to catch the exception in the upper layer.

What do you think of moving the exception catching logic up to `AbstractServerCall#onClose`? I've drafted a simple poc on what I think might be a potential fix. Sorry about the direction change 😅 

https://github.com/jrhee17/armeria/commit/117339f2d9bf2e4f4dd37319d26ec2b7c22f1f62

Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:192]: No problem.

If you are alright about the method signatures, etc in https://github.com/aki-s/armeria/pull/1/commits
,
I wish to merge your changes

Comment (aki-s) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:181]: Alright, I've merged it.

**Comment by trustin** [comment]
There's a test failure in this PR:
```
GrpcServiceImplErrorTest > unaryCallInvalidMetadata() FAILED
    com.linecorp.armeria.common.logging.RequestLogAvailabilityException: RequestLog not complete
        at app//com.linecorp.armeria.common.logging.DefaultRequestLog.ensureComplete(DefaultRequestLog.java:292)
        at app//com.linecorp.armeria.server.grpc.GrpcServiceImplErrorTest.unaryCallInvalidMetadata(GrpcServiceImplErrorTest.java:227)
```

**Comment by trustin** [comment]
Thanks a lot! You might want to open a new PR since our default branch has been changed to `main`. Sorry for your inconveniences :bow:

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java [hunk 23]
```diff
@@ -537,11 +539,20 @@ protected final HttpObject responseTrailers(ServiceRequestContext ctx, Status st
     // Returns ResponseHeaders if headersSent == false or HttpHeaders otherwise.
     public static HttpHeaders statusToTrailers(
             ServiceRequestContext ctx, HttpHeadersBuilder trailersBuilder, Status status, Metadata metadata) {
+        try {
+            MetadataUtil.fillHeaders(metadata, trailersBuilder);
+        } catch (Exception e) {
+            // Continue by squashing Exception by catch,
+            // because server implementer could have set corrupted metadata.
+            logger.warn("{} {} status: {}", ctx, "Error at filling header with metadata.", status);
+            // Catching exception is necessary, because server implementer could have set corrupted metadata.
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java:548]: We could clean up the comments and logging sentence a little bit:
```suggestion
            // A buggy user-implemented custom metadata serializer may throw
            // an exception. Leave a log message and set the INTERNAL status.
            logger.warn("{} Failed to serialize metadata; overriding the original status ({}) with INTERNAL:", ctx, status, e);
```

**Review by trustin — COMMENTED** [review]
Looking good! Left one nit

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java (hunk 22 above)
Comment (trustin) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java:192]: `unaryCall2()` returns valid metadata with ABORT, so this line doesn't have to change.

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java:545]: If I understood correctly, what @jrhee17 asked is to ensure `RequestLog.responseCause()` returns the exception we caught in this block when this happened. I think there's no clean way to propagate this exception at the moment because this method is currently called from different places and it'd be their responsibility to catch and handling them properly to achieve the idea.

Given the usage of custom metadata serializer is fairly rare and we already tell our users about their bad implementation, I'd suggest keeping this as it is in this PR and follow-up when we find a bad serializer implementation is more common problem than we thought.

**Review by trustin — APPROVED** [review]
Thank you so much for your patience as well as this nice improvement, @aki-s! :bow:

**Review by jrhee17 — APPROVED** [review]
Thanks @aki-s ! This patch will help armeria gRPC users troubleshoot issues more easily 👍 🙇 🚀

**Review by ikhoon — APPROVED** [review]
Thanks, @aki-s! 🚀🚀

**Review by minwoox — APPROVED** [review]
Thanks, @aki-s! 👍
