### PR TITLE
Fix to send 400 from gRPC HTTP/JSON transcoding service when the request is invalid

### LINKED ISSUE #5306: Malformed JSON request to a JSON around gRPC service continues with an empty request
Currently when sending malformed json to a json around gRPC API:

```json
{
  "a": "b",,,
}
```

Expected behavior:
- A 400 BAD REQUEST is returned

Actual behavior:
- Request continues as if the body was an empty json object

This is happening because of the method `com.linecorp.armeria.server.grpc.HttpJsonTranscodingService#getBodyContent`, which ignores the `JsonProcessingException` and returns null (empty body) instead.

### PR DESCRIPTION
**Pull request by mraasvel**
Motivation:

Malformed json requests continued with an empty request instead of returning an error.

Modifications:

Throw an illegal argument exception when json processing fails instead of ignoring it. The surrounding service will translate it into a BAD_REQUEST response.

Result:

- Closes #5306 
- Requests with a malformed json body will now return a BAD_REQUEST status

### CODE REVIEW

**Comment by mraasvel** [comment]
@natsumehu could you take a look at it, please? Also whether it's a logical change in terms of behavior.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java [hunk 1]
```diff
@@ -651,7 +651,7 @@ private static JsonNode getBodyContent(AggregatedHttpRequest request) {
         try {
             return mapper.readTree(request.contentUtf8());
         } catch (JsonProcessingException e) {
-            return null;
+            throw new IllegalArgumentException("error ocurred while parsing json request", e);
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:654]: `ocurred` -> `occurred` Or, just
` throw new IllegalArgumentException("invalid JSON request", e);`

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:654]: Question: What's the expected behavior when the content type is missing? Shouldn't we also raise an exception?

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java [hunk 2]
```diff
@@ -788,12 +788,11 @@ void shouldAcceptResponseBodyValueAnonymusField() throws JsonProcessingException
     }
 
     @Test
-    void shouldAcceptResponseBodyValueNoMatchInside() throws JsonProcessingException {
+    void shouldDenyMalformedJson() throws JsonProcessingException {
         final String jsonContent = "{\"value\":\"value\",\"structBody\":{\"structBody\":\"struct_value\"}";
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java:792]: I actually think this is a typo where a `}` character at the end is missing.

```
final String jsonContent = "{\"value\":\"value\",\"structBody\":{\"structBody\":\"struct_value\"}}";
```
Do you mind reverting this test and creating a separate test case which tests for malformed json requests?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java (hunk 1 above)
Comment (jrhee17) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:654]:
```suggestion
            throw new IllegalArgumentException("Failed to parse JSON request.", e);
```

**Review by jrhee17 — COMMENTED** [review]
Thanks for the PR! Left a comment

**Review by minwoox — COMMENTED** [review]
Hi, thanks for the PR! 
I left a question. 😉

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java (hunk 2 above)
Comment (mraasvel) [reply grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java:792]: Yes, my mistake, I misread the test. I thought it was explicitly testing the invalid json returning an empty body

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java (hunk 1 above)
Comment (mraasvel) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java]: I believe that makes sense, since it's part of the JsonTranscodingService, if there's any body, it should be a json type. I changed it so it throws an exception as well.

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java]: How about raising an exception when the body is not null or empty?
I've also created a relevant issue. 😉 
#5311

Comment (mraasvel) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java]: Empty node is invalid JSON, so I think it makes sense to throw an error too (currently it produces MissingNode)
I'm thinking the calling code, for the case where the body is `*`, it should be an error if the resulting node is not an ObjectNode regardless.
For the other case, I think we can allow all valid json, though NULL would likely result in a later error during proto conversion but I think that's better since then the json is at least valid.

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java]: Sorry for making you get confused. 
What I meant was returning null when there's no content type and the body was empty here:
https://github.com/line/armeria/pull/5307/files#diff-a9d03eb106960c77af7b39790659dfa479f644ef0745c2e0075e56a5de8badacR648

Comment (mraasvel) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java]: Ah yes, can do that, I think it makes sense.

I'm also thinking of throwing an exception here since it also defaults to an empty request if the resulting node is not ObjectNode:
https://github.com/line/armeria/blob/22163ca6dd7fa8d77e6f5104c486eda9b6018f79/grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java#L614C6-L614C6

Comment (mraasvel) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java]: @minwoox can you take a look again?

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java]: Shouldn't it be okay if it's null?
```java
if (body instanceof ObjectNode) {
    root = (ObjectNode) body;
} else if (body == null) {
    root = mapper.createObjectNode();
} else {
    throw new IllegalArgumentException("unexpected JSON: " + body +
                                       ", (expected: ObjectNode or null)");
}
```
Could you also add tests for cases that
- the request body is empty and content type is JSON
- the request body is empty and content type is null

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java [hunk 3]
```diff
@@ -646,12 +649,15 @@ private static JsonNode getBodyContent(AggregatedHttpRequest request) {
         @Nullable
         final MediaType contentType = request.contentType();
         if (contentType == null || !contentType.isJson()) {
-            return null;
+            if (request.contentUtf8().isEmpty()) {
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:652]: nit:
```suggestion
            if (request.content().isEmpty()) {
```

**Review by minwoox — APPROVED** [review]
Thanks for fixing this, @mraasvel! 😄

**Review by ikhoon — APPROVED** [review]
Thanks, @mraasvel!

**Comment by mraasvel** [comment]
No problem and thanks for the nice reviews :)

**Review by jrhee17 — APPROVED** [review]
Thanks for the report/fix 👍 🙇 👍

**Comment by mraasvel** [comment]
Not sure why `CI / build-self-hosted-jdk-8 (pull_request) Failing after 10m` failed, it passes for me locally. Can anyone help me with it? Maybe it should be retried?

**Comment by mraasvel** [comment]
@trustin could you also please take a look when you have time, thank you :)
