### PR TITLE
Server-side `RequestHeaders` uses the encoded path

### LINKED ISSUE #4694: Unencoded square brackets are not correctly handled at server-side
Armeria clients correctly encode square brackets when sending requests.
However, some browsers and `curl` seem to send requests without encoding square brackets which is a violation of the [rfc](https://www.ietf.org/rfc/rfc3986.txt))

When an armeria server receives a request where the URI contains unencoded square brackets, the request is processed normally.
However, when `request.uri()` is invoked, Java's `java.net.URI()` is invoked.
Because square brackets are not allowed in `java.net.URI`'s implementation, an exception occurs.

```
java.lang.IllegalStateException: not a valid URI: http://localhost:57893/uri-valid/[...foobar]
    at com.linecorp.armeria.common.HttpHeadersBase.uri(HttpHeadersBase.java:214)
    at com.linecorp.armeria.common.DefaultRequestHeaders.uri(DefaultRequestHeaders.java:46)
    at com.linecorp.armeria.common.HttpRequest.uri(HttpRequest.java:299)
    at com.linecorp.armeria.client.BlockingWebClientTest$1.lambda$configure$4(BlockingWebClientTest.java:62)
```

This is a surprise since a user would assume a request is valid if the service was invoked.
We may either:
1. Check for unencoded characters when `HttpRequest#uri` is invoked
2. Just reject requests with invalid paths/headers to begin with

ref: https://line-armeria.slack.com/archives/C1NGPBUH2/p1676961228194539
reproducer: https://github.com/tobias-/armeria/tree/bracket_test

Credit to @tobias- 🙇 👍 🙇

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

Unlike `ServiceRequestContext` which stores the encoded path, `RequestHeaders` uses the raw path.
This can be a problem when `RequestHeaders#uri` is invoked since a request path may contain unencoded characters.
I propose that `HttpRequest.path` also stores the encoded path.

Modifications:

- Call `PathAndQuery` for each request preemptively.
  - `*`, HEAD requests will not require `PathAndQuery` and will be processed normally
  - Invalid paths will be failed later
  - Valid paths will have a non-null `PathAndQuery`
- Use the `PathAndQuery` to set values respectively in `HttpHeaders#path` and `RequestContext#path`.

Result:

- Closes #4694 

cc. @tobias-

### CODE REVIEW

**Review by trustin — COMMENTED** [review]
This change will make `PathAndQuery.parse()` called more than once per request. Can we fix that somehow in this PR? We could alternatively file a new issue and fix it in the next release cycle since we obviously don't want to let this inefficiency stay longer. The new behavior itself LGTM though.

File: core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java [hunk 1]
```diff
@@ -125,6 +126,11 @@ public void onHeadersRead(ChannelHandlerContext ctx, int streamId, Http2Headers
                 return;
             }
 
+            final PathAndQuery pathAndQuery = PathAndQuery.parse(nettyHeaders.path().toString());
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java:129]: Suggestion by @minwoox :

`PathAndQuery` can be passed to `ArmeriaHttpUtil.toArmeriaRequestHeaders` since it might be easier to test behavior since the logic is grouped in a separate method.

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 2]
```diff
@@ -160,10 +161,13 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
                     // immutability.
                     final boolean hasInvalidExpectHeader = !handle100Continue(id, nettyReq);
 
+                    final String path = HttpHeaderUtil
+                            .maybeTransformAbsoluteUri(nettyReq.uri(), cfg.absoluteUriTransformer());
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:165]: I wanted to make sure that we want to pass the original path as an input of `absoluteUriTransformer`, right?

File: core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java [hunk 3]
```diff
@@ -174,4 +177,58 @@ static void ensureUniqueMediaTypes(Iterable<MediaType> types, String typeName) {
...
+            warnedIllegalAbsoluteUriTransformer = true;
+            logger.warn("absoluteUriTransformer.apply() returned null; returning 400 Bad Request");
+        }
+    }
+
+    private static URISyntaxException newInvalidPathException(String path) {
+        return new URISyntaxException(path, "neither origin form nor asterisk form");
+    }
+
+    private static boolean isValidHttp2Path(String path) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java:230]: This isn't your fault but I think we need to check if the method is OPTION when the path is `*`.
https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.3

**Review by minwoox — COMMENTED** [review]
Looks good all in all. Left a small suggestion. 😉

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 2 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:165]: Right 😄   I think this was the original implementation as well.

https://github.com/line/armeria/blob/5f6a3b4836a9f0e15d4d074729054993597888c8/core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java#L621

File: core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java (hunk 3 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java:230]: I understood your suggestion to mean throw an exception when a path is invalid.
I don't see a reason to only check * with OPTIONS, but we could also short-circuit when `pathAndQuery == null`.

Unfortunately, I think this potentially changes behavior and may print incorrect warning logs.
https://github.com/line/armeria/pull/4721#issuecomment-1481199075

While I think it is a good idea to throw an exception on path validation, I think the scope of change is large and deserves its own PR.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java:230]: > I don't see a reason to only check * with OPTIONS,

We are doing it here so I thought we needed to apply the same approach:
https://github.com/line/armeria/blob/3f83c66a1c73dea6aac31a6b8072edefbea10e62/core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java#L42

> While I think it is a good idea to throw an exception on path validation, I think the scope of change is large and deserves its own PR.

Yeah, let's solve it in another PR. 👍

File: core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java [hunk 4]
```diff
@@ -45,7 +46,6 @@ static RoutingContext newRoutingContext(ServerConfig serverConfig, Channel chann
                 routingStatus = RoutingStatus.INVALID_PATH;
             }
         } else {
-            pathAndQuery = PathAndQuery.parse(originalPath);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java:48]: The original if-else block is designed to minimize to call `PathAndQuery.parse(originalPath)`.
As `PathAndQuery` is given from the input parameter, should we simplify the code?
 
For example:
```java
if (pathAndQuery != null) {
    if (isCorsPreflightRequest(headers)) {
        routingStatus = RoutingStatus.CORS_PREFLIGHT;
    } else {
        routingStatus = RoutingStatus.OK;
    }
} else {
    if (headers.method() == HttpMethod.OPTIONS && "*".equals(originalPath)) {
        routingStatus = RoutingStatus.OPTIONS;
    } else {
        routingStatus = RoutingStatus.INVALID_PATH;
    }
}
```

**Review by ikhoon — APPROVED** [review]
Very nice! 👍

File: core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java [hunk 5]
```diff
@@ -174,4 +177,58 @@ static void ensureUniqueMediaTypes(Iterable<MediaType> types, String typeName) {
     }
 
     private HttpHeaderUtil() {}
+
+    static String maybeTransformAbsoluteUri(
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java:181]: Move `HttpHeaderUtil` to the bottom?

**Review by trustin — APPROVED** [review]
Nice work, @jrhee17! 🚀
