### PR TITLE
Fix `RoutingTrie` fails with a parameterized rest paths(`{*foo}`) pattern

### LINKED ISSUE #4034: `RoutingTrie` fails to navigate an `HttpService` mapped by a parameterized rest paths(`{*foo}`) pattern
If a service is bound with a parameterized rest paths(`/foo/{*bar}`) pattern, 
`RoutingTrie` fails to find the target service when traversing the tree.
```java
@RegisterExtension
static ServerExtension server = new ServerExtension() {
    @Override
    protected void configure(ServerBuilder sb) {
        sb.decorator(LoggingService.newDecorator());
        sb.service("/foo/{*qux}", (ctx, req) -> {
            return HttpResponse.of(ctx.pathParam("qux"));
        });
    }
};

@Test
void test() {
    final WebClient client = server.webClient();
    final AggregatedHttpResponse response = client.get("/foo/bar/qux").aggregate().join();
    // 404 not found is returned.
    assertThat(response.status()).isEqualTo(HttpStatus.OK);
}
```
I think the first path of `Route.paths()` has to return 1) `/foo/*` so that `RoutingTrie` correctly builds 2) the trie tree.

1) https://github.com/line/armeria/blob/510a57b213de5590649fe1634f8ee3274f545a38/core/src/main/java/com/linecorp/armeria/server/Route.java#L148
2) https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/server/RoutingTrieBuilder.java#L211-L215

Note: As #3997 is not released yet, we don't need to mention this on the release note.

### PR DESCRIPTION
**Pull request by policeman-kh**
Motivation:

Fix `RoutingTrie` fails with a parameterized rest paths( `{*foo}` ) pattern.

Modifications:

- Set trie path with `PREFIX` `"/foo/*` in `skeleton` , also `paths` if the path is rest paths pattern.
- Set `/foo/:*bar` pattern in normalized path pattern if the path is rest paths pattern.
- Replace `normalizeParameterized` to using `Route.patternString` in DocService.

Result:

- Closes #4034. (If this resolves the issue.)

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java [hunk 1]
```diff
@@ -207,10 +207,19 @@ private static String normalizeParameterized(Route route) {
...
         final StringBuilder sb = new StringBuilder();
         for (String paramName : route.paramNames()) {
-            final int colonIndex = path.indexOf(':', beginIndex);
+            int colonIndex = path.indexOf(':', beginIndex);
+            boolean restPathsPattern = false;
+            if (colonIndex == -1) {
+                colonIndex = path.indexOf('*', beginIndex);
+                restPathsPattern = colonIndex != -1;
+            }
             assert colonIndex != -1;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:216]: Is `restPathsPattern` always `true` here inside `if (colonIndex == -1) { ... }`? If so, this could be simplified into:
```suggestion
            if (colonIndex == -1) {
                colonIndex = path.indexOf('*', beginIndex);
                assert colonIndex != -1;
                restPathsPattern = true;
            }
```

File: core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java [hunk 2]
```diff
@@ -144,7 +146,7 @@
             }
 
             normalizedPatternJoiner.add(':' + paramName);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java:148]: How about prepending `*` to `paramName` if `captureRestPathMatching` is true so that users easily see rest paths patterns from the startup logs produced by `Routers`.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java [hunk 3]
```diff
@@ -207,10 +207,19 @@ private static String normalizeParameterized(Route route) {
...
+                colonIndex = path.indexOf('*', beginIndex);
+                assert colonIndex != -1;
+                restPathsPattern = true;
+            }
             sb.append(path, beginIndex, colonIndex);
             sb.append('{');
+            if (restPathsPattern) {
+                // Set a parameterized rest paths pattern "{*foo}".
+                sb.append('*');
+            }
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:222]: By the way, could we just use `Route.patternString()` instead of re-assembling the path of `Route`? `/foo/bar/:baz/:*qux` seems readable enough.
What do you think @trustin? 🤔

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:222]: +1

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:222]: +1

Comment (policeman-kh) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:222]: So.... you mean. can I change the logic of this method to just returning `Route.patternString` instead of re-assembling in this PR ? 🤔  @ikhoon

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:222]: You can just remove `normalizeParameterized()` and replace it with `patternString()`. 
```diff
- builder = EndpointInfo.builder(hostnamePattern, normalizeParameterized(route));
+ builder = EndpointInfo.builder(hostnamePattern, route.patternString());
```

**Comment by ikhoon** [comment]
Please check out the failed test. 🙇‍♂️
```
ParameterizedPathMappingTest > patternString() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: "/service/*value"
     but was: "/service/:*value"
```

**Comment by policeman-kh** [comment]
> Please check out the failed test

Ah. Sorry. fixed 🙇‍♂️

**Review by ikhoon — APPROVED** [review]
Thanks, @policeman-kh!

**Review by jrhee17 — APPROVED** [review]
Thanks for the quick fix @policeman-kh ! 🙇 👍 💯

**Review by trustin — APPROVED** [review]
Nice work, @policeman-kh :bow:

**Review by minwoox — APPROVED** [review]
Thanks a lot for fixing this. 😄

**Comment by ikhoon** [comment]
Thank you @policeman-kh again for your hard work. 🙇‍♂️
