### PR TITLE
Provide a way to encode and decode Protobuf in annotated services

### LINKED ISSUE #3088: Add Protocol Buffers codec for annoated service
When a Protocol Buffers object is returned in an annotated service, Jackson serializer will throw the following exception because Jackson does not know how to serialize Protocol Buffers.
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.google.protobuf.UnknownFieldSet$Parser and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.linecorp.armeria.internal.shaded.guava.collect.RegularImmutableList[0]->....PongResponse["unknownFields"]->com.google.protobuf.UnknownFieldSet["parserForType"])
```

If a `ResponseConverterFunction` for Protocol Buffers is provided with `armeria-grpc`, users could easily build HTTP proxy server in front of gRPC server. For example: 
```java
@Get("/ping-pong-lot-of-pongs/{from}")
@ProducesJson
public Flux<PongResponse> restful(@Param("from") int from) {
		var lotOfPongsRequest = LotOfPongsRequest.newBuilder()
				.setFromTimestamp(...)
				.setLimit(...)
				.build();
		return grpcClient.receiveLotOfPongs(lotOfPongsRequest)
				.publishOn(Schedulers.fromExecutor(ServiceRequestContext.current().blockingTaskExecutor())
				.log();
}
``` 
https://line-armeria.slack.com/archives/C1NGPBUH2/p1601299777043700

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

Protocol Buffers is a universal serialization protocol. The usage is not limit to gRPC.
It could be used an HTTP payload for REST API.
It is also useful when building an HTTP proxy server in front of a gRPC server.

Modifications:

- Add `RequestConverterFunctionProvider` that can load a custom `RequestConverterFunction` using SPI
- Add `@ConsumesProtobuf` and `@ProducesProtobuf` annotations
- [Protobuf](https://developers.google.com/protocol-buffers/docs/javatutorial)
  - Create `armeria-protobuf` module to use Protobuf in annotated services
  - Add `ProtobufRequestConverterFunction` that decodes Protocol Buffers or JSON body into Protobuf Message type
  - Add `ProtobufResponseConverterFunction` that encodes Protobuf Message(s) into Protocol Buffers or JSON
  - Add `ProtobufRequestConverterFunctionProvider` and `ProtobufResponseConverterFunctionProvider` to support Protobuf converters automatically via SPI
- [ScalaPB](https://scalapb.github.io/docs/generated-code)
  - Create `armeria-scalapb_2.12` and `armeria-scalapb_2.13` module to use ScalaPB in annotated services 
  - Add `ScalaPbRequestConverterFunction` that decodes Protocol Buffers or JSON body into ScalaPB `GenreatedMessage` type
  - Add `ScalaPbResponseConverterFunction` that encodes ScalaPB `GenerratedMesage`(s) into Protocol Buffers or JSON
  - Add `ScalaPbRequestConverterFunctionProvider` and `ScalaPbResponseConverterFunctionProvider` to support ScalaPB converters automatically via SPI
- These converters are applied only when the content-type is:
  - Protobuf - `application/protobuf`, `application/x-protobuf` or `application/octet-stream`
  - JSON - `application/json; charset=utf-8` or subtype ends with `+json`

Result:

- You can now use Protobuf's `Message` and ScalaPB's `GeneratedMessage` as a request/response object in annotated service.
- Closes #3088

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+               (contentType.is(MediaType.JSON) || contentType.subtype().endsWith("+json"));
+    }
+
+    private static Message.Builder getMessageBuilder(Class<?> clazz) throws Exception {
+        Method method = methodCache.get(clazz);
+        if (method == null) {
+            method = clazz.getMethod("newBuilder");
+            methodCache.put(clazz, method);
+        }
+        return (Message.Builder) method.invoke(clazz);
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:158]: I was just wondering how slower is `Method.invoke(...)` than `MethodHandle.invoke(...)`.  
```
Benchmark                          Mode  Cnt         Score         Error  Units
MethodCallBenchmark.directCall    thrpt    5  30697469.267 ± 5620688.880  ops/s
MethodCallBenchmark.method        thrpt    5  24412855.684 ± 4318917.364  ops/s
MethodCallBenchmark.methodHandle  thrpt    5  29439498.151 ± 1840979.485  ops/s
```

There is 20% performance degression in `Method.invoke(...)`. Let me change this with `MethodHandle`. :-)

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java [hunk 2]
```diff
@@ -90,18 +90,43 @@
...
-            RequestObjectResolver.of(new StringRequestConverterFunction()),
-            RequestObjectResolver.of(new ByteArrayRequestConverterFunction()));
+    @Nullable
+    private static final RequestConverterFunction protobufRequestConverterFunction;
+
+    static {
+        RequestConverterFunction converterFunction;
+        try {
+            final Class<?> protobufConverterClass =
+                    Class.forName("com.linecorp.armeria.server.grpc.ProtobufRequestConverterFunction");
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:100]: We use SPI to find `ResponseConverterFunction` implementations.
Shouldn't we use the same approach for `RequestConverterFunction`?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+ * <p>The Protocol Buffers spec does not have an official way to sending multiple messages because
+ * an encoded message does not have self-delimiting.
+ * See
+ * <a href="https://developers.google.com/protocol-buffers/docs/techniques#streaming">Streaming Multiple Messages</a>
+ * for more information.
+ * Therefore a sequence of Protocol Buffer messages can not be handled by this {@link RequestConverterFunction}.
+ * However a <a href="https://tools.ietf.org/html/rfc7159#section-5">JSON array</a> body
+ * could be converted into a {@link Collection} type. e.g, {@code List<Message>} and {@code Set<Message>}.
+ */
+public final class ProtobufRequestConverterFunction implements RequestConverterFunction {
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:69]: Shouldn't we make a separate module so that the user doesn't have to bring gRPC dependencies to use this?

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java (hunk 2 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:100]: That's a good suggestion. Let me add a SPI provider.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java (hunk 3 above)
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:69]: I thought this feature would be interesting to some users who want to gRPC service and client already. Do we need `armeria-protobuf`? 🤔

Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:69]: I'm not sure. 🤣  @anuraaga Do you have any suggestions?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java [hunk 4]
```diff
@@ -0,0 +1,211 @@
...
+                                 @Nullable ParameterizedType expectedParameterizedResultType) throws Exception {
+
+        final MediaType contentType = request.contentType();
+        if (resultType == ResultType.PROTOBUF ||
+            (resultType == ResultType.UNKNOWN && Message.class.isAssignableFrom(expectedResultType))) {
+            final Message.Builder messageBuilder = getMessageBuilder(expectedResultType);
+
+            if (contentType == null ||
+                contentType.subtype().contains("protobuf") || contentType.is(MediaType.OCTET_STREAM)) {
+                return messageBuilder.mergeFrom(request.content().array(), extensionRegistry).build();
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:131]: Would it be better using `toInputStream()` instead of `array()` so that `HttpData` does not create a backing array?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java [hunk 5]
```diff
@@ -0,0 +1,211 @@
...
+            throw new IllegalStateException(
+                    "Failed to create an empty instance of " + clazz + " using newBuilder() method", throwable);
+        }
+    }
+
+    enum ResultType {
+        UNKNOWN,
+        PROTOBUF,
+        LIST_PROTOBUF,
+        SET_PROTOBUF
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:209]: Do we need to support map as well?

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufResponseConverterFunctionProvider.java [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+import org.reactivestreams.Publisher;
+
+import com.google.protobuf.MessageLite;
+
+import com.linecorp.armeria.server.annotation.ExceptionHandlerFunction;
+import com.linecorp.armeria.server.annotation.ResponseConverterFunction;
+import com.linecorp.armeria.server.annotation.ResponseConverterFunctionProvider;
+
+/**
+ * Provides an {@link ProtobufResponseConverterFunction} to annotated services.
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufResponseConverterFunctionProvider.java:31]: an -> a

File: core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunctionProvider.java [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+
+import com.linecorp.armeria.common.AggregatedHttpRequest;
+import com.linecorp.armeria.common.annotation.UnstableApi;
+
+/**
+ * A {@link RequestConverterFunction} provider interface which creates a new
+ * {@link RequestConverterFunction} for converting an {@link AggregatedHttpRequest} to an object of
+ * the given type.
+ */
+@UnstableApi
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunctionProvider.java:30]: Could you also check other classes and add `@UnstableApi` if applicable?

File: grpc/build.gradle [hunk 8]
```diff
@@ -20,6 +20,7 @@ dependencies {
     testImplementation 'io.grpc:grpc-okhttp'
     testImplementation 'io.grpc:grpc-testing'
     testImplementation 'io.micrometer:micrometer-registry-prometheus'
+    testImplementation 'io.projectreactor:reactor-test'
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply grpc/build.gradle:23]: That's a good idea!

File: core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java [hunk 9]
```diff
@@ -106,6 +120,10 @@ public Object convertRequest(
                 }
             }
 
+            if (isProtobufType(expectedResultType, expectedParameterizedResultType)) {
+                return RequestConverterFunction.fallthrough();
+            }
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java:125]: Ah... We don't need to skip ProtoBuf message anymore. 
Before implementing `RequestConverterFunctionProvider`, `ProtobufRequestConverterFunction` is registered after `JacksonRequestConverterFunction`.
```java
ImmutableList.of(
            new JacksonRequestConverterFunction(),
            new ProtobufRequestConverterFunction(),
            new StringRequestConverterFunction(),
            new ByteArrayRequestConverterFunction());
```
But now, `RequestConverterFunctionProvider`s have always higher priorities than `defaultRequestConverterFunctions`.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java (hunk 3 above)
Comment (anuraaga) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:69]: Sorry for late reply - it does seem strange to have this in gRPC package since it seems to have nothing to do with gRPC. Perhaps core with compileOnly dependency on protobuf so it's next to the other annotated service functionality? not sure

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java:69]: Yeah, the code is too small to create a seperate module. Let me move this code to core and add `@UnstableApi` in case we need `armeria-protobuf` later.

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java (hunk 5 above)
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtobufRequestConverterFunction.java]: `MAP_PROTOBUF` is added for JSON format.

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java [hunk 10]
```diff
@@ -0,0 +1,229 @@
...
+        this(defaultJsonParser, ExtensionRegistry.getEmptyRegistry());
+    }
+
+    /**
+     * Creates an instance with the specified {@link Parser} and {@link ExtensionRegistry}.
+     */
+    public ProtobufRequestConverterFunction(Parser jsonParser, ExtensionRegistry extensionRegistry) {
+        this.jsonParser = requireNonNull(jsonParser, "jsonParser");
+        this.extensionRegistry = requireNonNull(extensionRegistry, "extensionRegistry");
+        resultType = ResultType.UNKNOWN;
```
Comment (minwoox) [inline protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:122]: nit: how about making a private constructor and delegating setting?

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java [hunk 11]
```diff
@@ -0,0 +1,229 @@
...
+
+            if (contentType == null ||
+                contentType.subtype().contains("protobuf") || contentType.is(MediaType.OCTET_STREAM)) {
+                try (InputStream is = request.content().toInputStream()) {
+                    return messageBuilder.mergeFrom(is, extensionRegistry).build();
+                }
+            }
+
+            if (isJson(contentType)) {
+                jsonParser.merge(request.contentUtf8(), messageBuilder);
```
Comment (minwoox) [inline protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:144]: Shouldn't we use charset?
`jsonParser.merge(request.content().toReader(contentType.charset(Charsets.UTF_8)), ...`

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java [hunk 12]
```diff
@@ -0,0 +1,172 @@
...
+
+    @Override
+    public HttpResponse convertResponse(ServiceRequestContext ctx, ResponseHeaders headers,
+                                        @Nullable Object result, HttpHeaders trailers) throws Exception {
+        final MediaType mediaType = headers.contentType();
+        if (result instanceof MessageLite) {
+            if (mediaType != null) {
+                if (mediaType.is(MediaType.JSON) || mediaType.subtype().endsWith("+json")) {
+                    final Charset charset = mediaType.charset(StandardCharsets.UTF_8);
+                    if (charset.contains(StandardCharsets.UTF_8)) {
```
Comment (minwoox) [inline protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java:95]: So this is not working if the charset is not UTF_8, right?

File: site/src/pages/docs/setup.mdx [hunk 13]
```diff
@@ -50,6 +50,8 @@ the list of major Armeria artifacts which might interest you:
 |                                             | request information.                                                            |
 |                                             | See [Logging contextual information](/docs/advanced-logging).                   |
 +---------------------------------------------+---------------------------------------------------------------------------------+
+| `armeria-protobuf`                          | Protocol Buffers support.                                                       |
```
Comment (minwoox) [inline site/src/pages/docs/setup.mdx:53]: Support Protocol Buffers in annotated service?

**Review by minwoox — APPROVED** [review]
Just nits.
Great job, @ikhoon!

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java (hunk 12 above)
Comment (trustin) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java:95]: Maybe we can support other encodings as well?

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java (hunk 11 above)
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:144]: I thought UTF-8 is only used for JSON.

Just out of curiosity, which is better `toReader(Charset)` or `content(Charset)` here?
If you are also curious, let me run a simple benchmark for it. 😉

Comment (minwoox) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:144]: I think using the reader was more efficient but not 100% sure. 😄 
Could you run the benchmark if you don't mind?

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java [hunk 14]
```diff
@@ -0,0 +1,229 @@
...
+
+        return RequestConverterFunction.fallthrough();
+    }
+
+    private static boolean isJson(@Nullable MediaType contentType) {
+        return contentType != null &&
+               (contentType.is(MediaType.JSON) || contentType.subtype().endsWith("+json"));
+    }
+
+    private static Message.Builder getMessageBuilder(Class<?> clazz) {
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:201]: I don't think so. A message class generated by ScalaPB extends `scalapb.GeneratedMessage`. 
However it is possible by using another reflection API. Let me try it with optionalApi of ScalaPB.

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java [hunk 15]
```diff
@@ -0,0 +1,88 @@
...
+                if (isProtobufMessage((Class<?>) typeArguments[1])) {
+                    return ResultType.MAP_PROTOBUF;
+                }
+            }
+        }
+        return ResultType.UNKNOWN;
+    }
+
+    private static boolean isProtobufMessage(Class<?> clazz) {
+        return Message.class.isAssignableFrom(clazz);
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java:86]: `c` class extends `MessageLite`. When build a message from protobuf, `Message` class is required to get `Builder` class. However, when serialize a message to protobuf,  `MessageLite` is enough.
However, this can confuse users. Let me just use `Message` instead of `MessageLite`.

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java (hunk 11 above)
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:144]: There is no big difference among them. `contentUtf8()` is 3% ~ 4% faster. It seems that within tolerance.

```
GrpcParseBenchmark.parseWithReader  thrpt    5  777.928 ± 4.739  ops/s
GrpcParseBenchmark.parseWithString  thrpt    5  806.419 ± 8.637  ops/s
```

The benchamrk code:
```java
static final String json = JsonFormat.printer().print(SEARCH_RESPONSE);
static final HttpData httpData = HttpData.wrap(json.getBytes(StandardCharsets.UTF_8));
static final Parser parser = JsonFormat.parser();

@Benchmark
public SearchResponse parseWithString() throws InvalidProtocolBufferException {
    final SearchResponse.Builder builder = SearchResponse.newBuilder();
    parser.merge(httpData.toStringUtf8(), builder);
    return builder.build();
}

@Benchmark
public SearchResponse parseWithReader() throws IOException {
    final SearchResponse.Builder builder = SearchResponse.newBuilder();
    parser.merge(httpData.toReader(StandardCharsets.UTF_8), builder);
    return builder.build();
}
```

Comment (minwoox) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:144]: Thanks for the test, yeah using `contentUtf8` seems more efficient. 😄

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java [hunk 16]
```diff
@@ -0,0 +1,172 @@
...
+                return HttpResponse.of(headers, toProtobuf(result), trailers);
+            }
+
+            return HttpResponse.of(headers.toBuilder().contentType(MediaType.PROTOBUF).build(),
+                                   toProtobuf(result), trailers);
+        }
+
+        if (mediaType != null) {
+            final String subtype = mediaType.subtype();
+            if (subtype.contains("protobuf")) {
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java:108]: The following two media types seem to be widely used. 
- `application/x-protobuf` by Spring
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/converter/protobuf/ProtobufHttpMessageConverter.html
- `application/protobuf` by Guava

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java [hunk 17]
```diff
@@ -0,0 +1,172 @@
...
+                checkArgument(result != null, "a null value is not allowed for %s", mediaType);
+                final Charset charset = mediaType.charset(StandardCharsets.UTF_8);
+                final boolean isJson = subtype.contains("+json") && charset.contains(StandardCharsets.UTF_8);
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java]: Fixed

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:227]: ScalaPB converters are added to `armeria-scalapb` module.
https://github.com/line/armeria/pull/3124/commits/f5ef663b80f84a15d2d2ebebe0faf8e99927771d

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (anuraaga) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java:86]: `MessageLite` is very rare in servers btw (though I remember an issue filed by someone that was actually using it don't remember the reasoning)

[the remark this answers is not in the document]
Comment (ikhoon) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java:86]: >  I remember an issue filed by someone that was actually using it don't remember the reasoning

Maybe #3085? He said it was caused by wrong dependencies.

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (trustin) [reply protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java:227]: Nice!

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/CompositeConverterFunctions.java [hunk 18]
```diff
@@ -0,0 +1,113 @@
...
+import com.linecorp.armeria.common.HttpHeaders;
+import com.linecorp.armeria.common.HttpResponse;
+import com.linecorp.armeria.common.ResponseHeaders;
+import com.linecorp.armeria.common.util.SafeCloseable;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.annotation.FallthroughException;
+import com.linecorp.armeria.server.annotation.RequestConverterFunction;
+import com.linecorp.armeria.server.annotation.ResponseConverterFunction;
+
+final class CompositeConverterFunctions {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/CompositeConverterFunctions.java:36]: Could we move the inner classes to the top level? This parent class doesn't seem to do anything.

File: gradle.properties [hunk 19]
```diff
@@ -26,3 +26,7 @@ org.gradle.jvmargs=-Xmx1280m
 systemProp.https.protocols=TLSv1,TLSv1.1,TLSv1.2
 
 jacocoExclusions=com/linecorp/armeria/internal/common/CurrentJavaVersionSpecific,META-INF/versions/**
+
+# Scala options
+scalaVersions=2.13.3
+defaultScalaVersions=2.13.2
```
Comment (trustin) [inline gradle.properties:32]: Question: Why these properties have two different versions?

File: gradle/scripts/lib/java-publish.gradle [hunk 20]
```diff
@@ -23,7 +23,16 @@ configure(projectsWithFlags('publish', 'java')) {
                     jarOverrideFile = tasks.trimShadedJar.outJarFiles.find() as File
                     jarOverrideTask = tasks.trimShadedJar
                 } else if (tasks.findByName('shadedJar')) {
-                    jarOverrideFile = tasks.shadedJar.archivePath
+                    def archivePath = tasks.shadedJar.archivePath
+                    if (project.hasFlags('scala')) {
+                        def microVersionIndex = project.ext.defaultScalaVersions.lastIndexOf('.')
+                        def scalaVersionSuffix = project.ext.defaultScalaVersions.substring(0, microVersionIndex)
```
Comment (trustin) [inline gradle/scripts/lib/java-publish.gradle:29]: - Could we do a little bit more strict regular expression matching to extract the suffix, so that a poorly formatted version number is not accepted?
- Shouldn't we detect the Scala version from the `scala-library` dependency in `dependencies.yml`?

File: gradle/scripts/lib/java-shade.gradle [hunk 21]
```diff
@@ -70,7 +70,15 @@ configure(relocatedProjects) {
             description: 'Extracts the shaded test JAR.',
             dependsOn: tasks.shadedTestJar) {
 
-        from(zipTree(tasks.shadedTestJar.archivePath))
+        def archivePath = tasks.shadedTestJar.archivePath
+        if (project.hasFlags('scala')) {
+            def microVersionIndex = project.ext.defaultScalaVersions.lastIndexOf('.')
+            def scalaVersionSuffix = project.ext.defaultScalaVersions.substring(0, microVersionIndex)
```
Comment (trustin) [inline gradle/scripts/lib/java-shade.gradle:76]: Ditto

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java [hunk 22]
```diff
@@ -0,0 +1,182 @@
...
+ * <h3>Conversion of multiple Protobuf messages</h3>
+ * A sequence of Protocol Buffer messages can not be handled by this {@link ResponseConverterFunction},
+ * because Protocol Buffers wire format is not self-delimiting.
+ * See
+ * <a href="https://developers.google.com/protocol-buffers/docs/techniques#streaming">Streaming Multiple Messages</a>
+ * for more information.
+ * However, {@link Publisher}, {@link Stream} and {@link Iterable} are supported when converting to
+ * <a href="https://tools.ietf.org/html/rfc7159#section-5">JSON array</a>.
+ *
+ * <p>Note that this {@link ResponseConverterFunction} is applied to the annotated service by default,
```
Comment (trustin) [inline protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java:67]: the annotated service -> an annotated service?

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java [hunk 23]
```diff
@@ -0,0 +1,182 @@
...
+ * so you don't have to set explicitly unless you want to use your own {@link Printer}.
```
Comment (trustin) [inline protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java:68]: set -> specify this converter

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/package-info.java [hunk 24]
```diff
@@ -0,0 +1,28 @@
...
+ * under the License.
+ */
+
+/**
+ * Provides a default {@link com.linecorp.armeria.server.annotation.ResponseConverterFunction}
+ * which automatically converts a {@link com.google.protobuf.Message} into
+ * an {@link com.linecorp.armeria.common.HttpResponse} and
+ * a default {@link com.linecorp.armeria.server.annotation.RequestConverterFunction} which automatically
+ * converts an {@link com.linecorp.armeria.common.AggregatedHttpRequest} into
+ * a {@link com.google.protobuf.Message}.
```
Comment (trustin) [inline protobuf/src/main/java/com/linecorp/armeria/server/protobuf/package-info.java:23]: a default -> the default?

File: protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufRequestAnnotatedServiceTest.java [hunk 25]
```diff
@@ -0,0 +1,145 @@
...
+    }
+
+    private static class GreetingService {
+        @Post("/default-content-type")
+        public String noContentType(SimpleRequest request) {
+            return "Hello, Armeria!";
+        }
+
+        @Post("/json")
+        @ConsumesJson
```
Comment (trustin) [inline protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufRequestAnnotatedServiceTest.java:120]: Should we also add `@Consumes/ProducesProtobuf`?

File: scalapb/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala [hunk 26]
```diff
@@ -0,0 +1,284 @@
...
+  * or ends with `+json`.
+  *
+  * ===Conversion of multiple Protobuf messages===
+  * A sequence of Protocol Buffer messages can not be handled by this
+  * [[com.linecorp.armeria.server.annotation.RequestConverterFunction]],
+  * because Protocol Buffers wire format is not self-delimiting.
+  * See [[https://developers.google.com/protocol-buffers/docs/techniques#streaming Streaming Multiple Messages]]
+  * for more information.
+  * However, [[scala.Iterable]] types such as `List[scalapb.GeneratedMessage]` and
+  * `Set[scalapb.GeneratedMessage]` are supported when converted from
```
Comment (trustin) [inline scalapb/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala:57]: when -> only when

File: scalapb/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala [hunk 27]
```diff
@@ -0,0 +1,284 @@
...
+  * [[https://tools.ietf.org/html/rfc7159#section-5 JSON array]].
+  *
+  * Note that this [[com.linecorp.armeria.server.annotation.RequestConverterFunction]] is applied to
+  * the annotated service by default, so you don't have to set explicitly unless you want to
```
Comment (trustin) [inline scalapb/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala:61]: the annotated -> an annotated

File: scalapb/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala [hunk 28]
```diff
@@ -0,0 +1,185 @@
...
+        Arguments.of(set, toJson(set), new TypeToken[Set[SimpleRequest]]() {}),
+        Arguments.of(jlist, toJson(jlist), new TypeToken[java.util.List[SimpleRequest]]() {}),
+        Arguments.of(jset, toJson(jset), new TypeToken[java.util.Set[SimpleRequest]]() {})
+      )
+    }
+
+  }
+
+  private class JsonObjectRequestProvider extends ArgumentsProvider {
+    override def provideArguments(context: ExtensionContext): stream.Stream[Arguments] = {
```
Comment (trustin) [inline scalapb/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala:146]: We're mixing `stream.Stream` and `java.util.stream.Stream`. Maybe better using a single form?

File: gradle.properties (hunk 19 above)
Comment (ikhoon) [reply gradle.properties]: Oops... it was cruft. Actually, I removed [gradle-scala-multiversion-plugin](https://github.com/ADTRAN/gradle-scala-multiversion-plugin) and add `scalapb_2.12` and `scalapb_2.13` because it is difficult to integrate gradle-scala-multiversion-plugin with Armeria's gradle scripts.
And we need a lot of workarounds and some of them are flaky. 😅

File: scalapb/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala (hunk 28 above)
Comment (ikhoon) [reply scalapb/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala]: Agreed!

**Comment by ikhoon** [comment]
Finally, all builds are passed. 😆

File: core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunctionProvider.java [hunk 29]
```diff
@@ -0,0 +1,46 @@
+/*
+ * Copyright 2018 LINE Corporation
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunctionProvider.java:2]: ❓

File: scalapb/scalapb_2.13/build.gradle [hunk 30]
```diff
@@ -0,0 +1,56 @@
...
+    implementation project(':grpc')
+    implementation 'org.scala-lang:scala-library:2.13.3'
+
+    // ScalaPB
+    api "com.thesamet.scalapb:scalapb-json4s_2.13"
+    implementation "com.thesamet.scalapb:scalapb-runtime_2.13"
+    implementation "com.thesamet.scalapb:scalapb-runtime-grpc_2.13"
+}
+
+
```
Comment (minwoox) [inline scalapb/scalapb_2.13/build.gradle:17]: nit: two empty lines

File: scalapb/scalapb_2.13/build.gradle [hunk 31]
```diff
@@ -0,0 +1,56 @@
...
+    test {
+        scala {
+            srcDirs "${protobuf.generatedFilesBaseDir}/test/scalapb"
+        }
+    }
+}
+
+// Run `scalafmt` to automatically format scala code from source sets
+// https://github.com/alenkacz/gradle-scalafmt#tasks
+project.ext.getLintTask().dependsOn tasks.checkScalafmt
```
Comment (minwoox) [inline scalapb/scalapb_2.13/build.gradle:38]: 👍

**Review by minwoox — APPROVED** [review]
Still LGTM 👍 
(Do not know much about the Scala part 🤣 )

File: core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunctionProvider.java (hunk 29 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunctionProvider.java:2]: 😱

File: protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java [hunk 32]
```diff
@@ -0,0 +1,183 @@
...
+import com.linecorp.armeria.common.ResponseHeaders;
+import com.linecorp.armeria.common.annotation.UnstableApi;
+import com.linecorp.armeria.common.util.Exceptions;
+import com.linecorp.armeria.server.ServiceRequestContext;
+import com.linecorp.armeria.server.annotation.ResponseConverterFunction;
+
+/**
+ * A {@link ResponseConverterFunction} which creates an {@link HttpResponse} with
+ * {@code content-type: application/protobuf} or {@code content-type: application/json; charset=utf-8}.
+ * If the returned object is instance of {@link MessageLite}, the object can be converted to either
```
Comment (trustin) [inline protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java:54]: instance of -> a (or an instance of)

File: scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala [hunk 33]
```diff
@@ -0,0 +1,286 @@
...
+
+  private val companionCache: ConcurrentMap[Class[_], GeneratedMessageCompanion[_]] =
+    new MapMaker().weakKeys.makeMap()
+
+  private val defaultJsonParser: Parser = new Parser().ignoringUnknownFields
+  private val mapper = new ObjectMapper
+
+  /**
+    * Creates a new instance with the specified [[scalapb.json4s.Parser]].
+    */
```
Comment (trustin) [inline scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala:82]: Global comment: indentation?

File: site/src/pages/docs/setup.mdx [hunk 34]
```diff
@@ -58,6 +60,8 @@ the list of major Armeria artifacts which might interest you:
 +---------------------------------------------+---------------------------------------------------------------------------------+
 | `armeria-saml`                              | SAML support                                                                    |
 +---------------------------------------------+---------------------------------------------------------------------------------+
+| `armeria-scalapb`                           | Support ScalaPB in annotated service.                                           |
```
Comment (trustin) [inline site/src/pages/docs/setup.mdx:63]: `armeria-scalapb_2.12` and `armeria-scalapb_2.13`?

**Review by trustin — COMMENTED** [review]
How will we have to expose Scaladoc in our web site by the way?

**Comment by ikhoon** [comment]
> How will we have to expose Scaladoc in our web site by the way?

How about adding a dedicated documentation page for ScalaPB? The page will have a simple introduction and a Scaladoc link.
I think we can add the page after migrating ScalaPB plugins from examples/examples/grpc-scala.

**Review by trustin — APPROVED** [review]
Great work, @ikhoon. ScalaPB users will love this.

**Comment by trustin** [comment]
@ikhoon Could you update the PR description?

**Comment by ikhoon** [comment]
> @ikhoon Could you update the PR description?

Sure! The PR description is updated.
