### PR TITLE
Fix race condition where `log.whenComplete` may not complete

### LINKED ISSUE #5981: Potential Race Condition in `FramedGrpcService` with `ctx.log.whenComplete` Not Completing in v1.30.1
# Summary
In Armeria v1.30.1, we observed that callbacks on `ctx.log.whenComplete` in `FramedGrpcService` were not consistently triggered. This issue was not present in v1.16.3. The `RequestProperty.NAME` property, which in some cases was missing, resulting in incomplete request logs despite successful request and response flows. We believe this is because the `endRequest` running in a eventloop is racing with `requestContent` running in a blocking task executor, as a result, neither of the `setNamesIfAbsent` callsites is able to call into it.

# Service Setting
Armeria Version: v1.30.1 (both server and client)
FramedGrpcService has set blocking task executor
QPS: ~10K/s
Server Specs: 8-core server
Payload:
Request size: ~1 KB
Response size: 5 B

# Investigation and Findings
To trace the source of the incomplete logs, we added debugging logs to our `Tracker` object, installed in a decorator as an attribute in the `ServiceRequestContext`. Also, we put up [PR](https://github.com/line/armeria/pull/5980/files) for testing.

```scala
class Tracker {
   val whenComplete = ctx.log.whenComplete
   
   override override def finalize(): Unit = {
    try {
      if (!whenComplete.isCompleted) {
        val log = armeriaCtx.log().partial()
        logger.warn($log)
    } finally {
      super.finalize()
    }
}
```

# Key findings:

- Missing `RequestProperty.NAME`: Logs showed `log.availabilityStamp` to  be `4194271` (`1111111111111111011111`), indicating only `RequestProperty.NAME` was missing, and that prevents the `RequestLog` to be completed.

- Successful Request Flow: The request and response were both successful, with request content, service name, and method name visible in request log, indicating `requestContent` was triggered in `RequestLogBuilder`. It also means the `setNamesIfAbsent` was skipped in `requestContent` method.

-  Analysis of `setNamesIfAbsent` Call:
    - Call Trace: We verified that `setNamesIfAbsent`, the only setter for `RequestProperty.NAME`, was not called at all.
    - Stack Trace for `requestContent`: `requestContent` calls originated from a blocking task executor thread, with different flag states when it is called:
        - Flags: `413 (110011101)`: Missing `REQUEST_END_TIME`, `NAME`, and `AUTHENTICATED_USER`. This explains why `setNamesIfAbsent` was skipped because the `REQUEST_END_TIME` isn't available yet.
        - Flags: `8159 (1111111011111)`: `REQUEST_END_TIME` was available, yet `isAvailable` val was false, indicating the flags were just updated during logging.

# Root Cause Analysis
We believe a race condition exists between the following events:
- `endRequest`, running in eventloop, can initiate early and complete after `requestContent`.
    - `setNamesIfAbsent` is skipped there, because `REQUEST_CONTENT` is deferred and `REQUEST_CONTENT` hasn't been set yet;
- `requestContent`, running in blocking task executor, attempting to set the NAME, and `REQUEST_COMPLETE_FLAG` is not available at the time and it also skips `setNamesIfAbsent` part.

This results in uncompleted logs due to RequestProperty.NAME not being set in time.

# Validation
To confirm this hypothesis, we conducted two validations:

- Manual name Setting: We manually set `ctx.logBuilder.name`.
- Run on eventloop directly: We ran `FramedGrpcService` on the eventloop directly, as that actually is what happens in v1.16.3.

The issue no longer occurred for both validations.

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

It has been reported that `log.whenComplete` is not completing in some cases in #5981.
The cause seems to be a race condition between `DefaultRequestLog#endRequest` and `DefaultRequestLog#requestContent`. Completion of `log.whenComplete` is important because
1) it is semantically bound to an HTTP request 2) users (including us) have clean up logic using `log.whenComplete`.

I propose that simply `endRequest` only sets `name` if content is not deferred, and `requestContent` sets `name` if content is deferred. The logic is easier to reason about, and there are minimal performance implications since a lock is held anyways.

Modifications:

- `#endRequest` sets `name` if `requestContent` isn't deferred
- `#requestContent` sets name if `requestContent` is deferred

Result:

- Closes #5981

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java [hunk 1]
```diff
@@ -1104,12 +1100,11 @@ private void endRequest0(@Nullable Throwable requestCause, long requestEndTimeNa
             }
         }
 
-        // Set names if request content is not deferred or it was deferred but has been set
-        // before the request completion.
-        if (!hasInterestedFlags(deferredFlags, RequestLogProperty.REQUEST_CONTENT) ||
-            isAvailable(RequestLogProperty.REQUEST_CONTENT)) {
+        // Set names if request content is not deferred
+        if (!hasInterestedFlags(deferredFlags, RequestLogProperty.REQUEST_CONTENT)) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:1104]: Previously, the default name was filled in if there was no custom value before a request ended. If a deferred request content is called before `endRequest()`, `RequestLogBuilder.name()` is ignored, which could be a breaking change. Would it be worth specifying this change in Javadoc?

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:1104]: Sure, done

**Review by minwoox — APPROVED** [review]
The change makes sense. 👍

**Review by ikhoon — APPROVED** [review]
Thanks!
