### PR TITLE
Fix a bug where DNS resolution is not timed out

### LINKED ISSUE #2621: DNS resolution timeout may take longer
Let's say that `/etc/resolve.conf` contains:
```
a.svc.cluster.local svc.cluster.local cluster.local
```
If `queryTimeoutMillis` is 5 seconds and the client tries to find the address of `a.com`, it sends DNS queries sequencially as follow:
```
a.com.a.svc.cluster.local.  // 5 seconds timeout.
a.com.svc.cluster.local.    // 5 seconds timeout.
a.com.cluster.local.        // 5 seconds timeout.
a.com.                      // 5 seconds timeout.
```
The timeout is for the individual query not for whole DNS resolution, so it could take more than 5 seconds.

To fix this, we can:
1. Provide to set the whole timeout for DNS resolution, or
2. Apply `queryTimeoutMillis` to whole DNS resolution.

I prefer to just do 2) because a user does not care about the individual queries, but just wants to get the result.
If there's a demand for 1) later, I will implement it later.

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
DNS resolution could take longer when there's more than one `DnsServerAddressStream`.

Modifications:
- DNS resolution is timed out after `queryTimeoutMillis`.

Result:
- DNS resolution is timed out after `queryTimeoutMillis`.
- Close #2621

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java [hunk 1]
```diff
@@ -103,10 +118,39 @@ public void operationComplete(Future<List<DnsRecord>> future) throws Exception {
...
+        eventLoop.schedule(() -> {
+            if (result.isDone()) {
+                // Received a response before the query times out.
+                return;
+            }
+            final DnsTimeoutException exception = new DnsTimeoutException(
+                    '[' + logPrefix + "] " + questions + " are timed out after " +
+                    queryTimeoutMillis + " milliseconds.");
+            result.tryFailure(exception);
+            promises.forEach(promise -> {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java]: I realized that the search domain query is not cancellable right now. I will send a PR to Netty to fix this.

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java [hunk 2]
```diff
@@ -103,10 +118,39 @@ public void operationComplete(Future<List<DnsRecord>> future) throws Exception {
...
+                if (promise.isDone()) {
+                    return;
+                }
+                promise.cancel(true);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java]: `isDone()` check is redundant. `cancel()` does nothing when promise is done already.

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java [hunk 3]
```diff
@@ -103,10 +118,39 @@ public void operationComplete(Future<List<DnsRecord>> future) throws Exception {
...
+        }
+        eventLoop.schedule(() -> {
+            if (result.isDone()) {
+                // Received a response before the query times out.
+                return;
+            }
+            final DnsTimeoutException exception = new DnsTimeoutException(
+                    '[' + logPrefix + "] " + questions + " are timed out after " +
+                    queryTimeoutMillis + " milliseconds.");
+            result.tryFailure(exception);
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java]: setFailure? I think we're not checking the return value since we don't expect the result to be completable since we own the event loop so may as well make that explicit.

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java [hunk 4]
```diff
@@ -103,10 +118,39 @@ public void operationComplete(Future<List<DnsRecord>> future) throws Exception {
             }
         };
 
-        questions.forEach(q -> delegate.resolveAll(q).addListener(listener));
+        final Builder<Promise<List<DnsRecord>>> promises =
+                ImmutableList.builderWithExpectedSize(questions.size());
+        questions.forEach(q -> {
+            final Promise<List<DnsRecord>> promise = executor().newPromise();
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java]: I think we should either use `eventLoop` here or `executor()` below when scheduling for consistency.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java]: Oops. I removed `executor()` completely. Thanks!

File: core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java (hunk 3 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java]: Yeah, that makes sense. Fixed.
