### PR TITLE
FIX-5017 Add authorization metrics

### LINKED ISSUE #5017: Provide a metric that measures the time for authorizing
Usually, it takes a long to authorize a request because the authorizer mostly needs to call another backend.
It would be nice if we provide a timer for the `AuthService` so that users easily get to know how long it takes.

### PR DESCRIPTION
**Pull request by yashmurty**
Motivation:

Fixing an open improvement issue. https://github.com/line/armeria/issues/5017

Modifications:

- Modified the `AuthService.java` file to use `MoreMeters.newTimer`.
- Updated the tests. I think some are still remaining to be fixed, so opening the PR as draft.
  - Any feedback is welcome as it's my first time! 😄  

Result:

- Closes #5017. (If this resolves the issue.)
- Describe the consequences that a user will face after this PR is merged.

The metrics would look like:
```
# HELP armeria_server_auth_seconds  
# TYPE armeria_server_auth_seconds summary
armeria_server_auth_seconds_count 1.0
armeria_server_auth_seconds_sum 0.018437417
# HELP armeria_server_auth_seconds_max  
# TYPE armeria_server_auth_seconds_max gauge
armeria_server_auth_seconds_max 0.018437417
```

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java [hunk 1]
```diff
@@ -75,17 +80,23 @@ public static AuthServiceBuilder builder() {
...
         super(delegate);
         this.authorizer = authorizer;
         this.defaultSuccessHandler = defaultSuccessHandler;
         this.defaultFailureHandler = defaultFailureHandler;
+        this.meterRegistry = meterRegistry;
     }
 
     @Override
     public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
+        final Timer timer = MoreMeters.newTimer(meterRegistry, "authorization", Tags.empty());
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:97]: How about `armeria.server.auth`?

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java [hunk 2]
```diff
@@ -75,17 +80,23 @@ public static AuthServiceBuilder builder() {
...
+        final Timer.Sample sample = Timer.start();
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:98]: This is OK, but can we use two `System.nanoTime()` calls instead so we don't create an extra object for each request?

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java [hunk 3]
```diff
@@ -153,17 +156,26 @@ public AuthServiceBuilder onFailure(AuthFailureHandler failureHandler) {
         return this;
     }
 
+    /**
+     * Sets the {@link MeterRegistry} that collects stats.
+     * If unspecified, a default one is used.
+     */
+    public AuthServiceBuilder meterRegistry(MeterRegistry meterRegistry) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java:163]: We don't need this because we can get the sever's current `MeterRegistry` from `ServiceConfig`. Please check my comment on `AuthService.java`.

**Comment by trustin** [comment]
I don't see a test case that actually checks whether the metric is recorded. Could you add one? Thanks! :bow:

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java (hunk 2 above)
Comment (yashmurty) [reply core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java]: Got it!
I have modified my implementation to use `System.nanoTime()`. 

> we don't create an extra object for each request?

That's a good point!

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java (hunk 3 above)
Comment (yashmurty) [reply core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java]: Thank you! 
I tried to refactor based on your feedback. 
Could you PTAL again? 🙇

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java [hunk 4]
```diff
@@ -84,8 +90,18 @@ public static AuthServiceBuilder builder() {
         this.defaultFailureHandler = defaultFailureHandler;
     }
 
+    @Override
+    public void serviceAdded(ServiceConfig cfg) throws Exception {
+        super.serviceAdded(cfg);
+        final MeterRegistry meterRegistry = cfg.server().meterRegistry();
+        timer = Timer.builder("armeria.server.auth")
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:97]: If there are multiple `AuthService`s loaded in a single JVM, I think this timer may not produce accurate results.

What do you think of providing a way for users to specify the meter name with a `MeterIdPrefixFunction` in `AuthServiceBuilder`?

**Review by jrhee17 — COMMENTED** [review]
Looks good overall, left a minor comment

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java (hunk 4 above)
Comment (yashmurty) [reply core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:97]: For more context, my modifications look like:

My AuthServiceBuilder:
```
public AuthServiceBuilder meterIdPrefixFunction(MeterIdPrefixFunction meterIdPrefixFunction) {
    this.meterIdPrefixFunction = requireNonNull(meterIdPrefixFunction, "meterIdPrefixFunction");
    return this;
}
```

My AuthService:
```
@Override
public void serviceAdded(ServiceConfig cfg) throws Exception {
    super.serviceAdded(cfg);
    final MeterRegistry meterRegistry = cfg.server().meterRegistry();

    final String meterName = meterIdPrefixFunction.activeRequestPrefix(meterRegistry, null).name(); # null for requestOnlyLog
    timer = Timer.builder(meterName).register(meterRegistry);
}
```

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:97]: @jrhee17, Isn't `MeterIdPrefix` enough for this case?
```java
public AuthServiceBuilder meterIdPrefix(MeterIdPrefix meterIdPrefix) { ...}


class AuthService ...
    ...
    private final MeterIdPrefix meterIdPrefix;
    ...
    AuthService(HttpService delegate, Authorizer<HttpRequest> authorizer, MeterIdPrefix meterIdPrefix, ...) {...}

    @Override
    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
        final long startNanos = System.nanoTime();
        return HttpResponse.of(AuthorizerUtil.authorizeAndSupplyHandlers(authorizer, ctx, req)
                                             .handleAsync((result, cause) -> {
            try {
                ...
            } finally {
                MoreMeters.newTimer(ctx.meterRegistry(), meterIdPrefix.name(), meterIdPrefix.tags())
                          .record(System.nanoTime() - startNanos, TimeUnit.NANOSECONDS);
            }
        }, ctx.eventLoop()));
    }
    ...
}    
```

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:97]: I realized that `MeterIdPrefixFunction` would provide more information so we need it.
```java

class AuthService ...
    ...
    private final MeterIdPrefixFuntion meterIdPrefixFuntion;
    ...
    AuthService(HttpService delegate, Authorizer<HttpRequest> authorizer, MeterIdPrefixFunction meterIdPrefixFuntion, ...) {...}

    @Override
    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
        final long startNanos = System.nanoTime();
        return HttpResponse.of(AuthorizerUtil.authorizeAndSupplyHandlers(authorizer, ctx, req)
                                             .handleAsync((result, cause) -> {
            try {
                ...
            } finally {
                final MeterIdPrefix meterIdPrefix =
                        meterIdPrefixFunction.activeRequestPrefix(ctx.meterRegistry(), ctx.log().partial());
                MoreMeters.newTimer(ctx.meterRegistry(), meterIdPrefix.name(), meterIdPrefix.tags())
                          .record(System.nanoTime() - startNanos, TimeUnit.NANOSECONDS);
            }
        }, ctx.eventLoop()));
    }
    ...
}    
```
We might also want to add a tag that indicates success or failure if needed.

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:97]: Sorry about the late reply and thanks @minwoox .

Like @minwoox  mentioned, I think we can accept a `MeterIdPrefixFunction` from the constructor.
Additionally, I agree it's useful to also add tags indicating success/failure.

Having said this, if this feels like too much work I think it's fine to do this in a separate iteration

File: core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java [hunk 5]
```diff
@@ -429,11 +434,23 @@ void shouldPeelRedundantAuthorizerExceptions() throws Exception {
...
                                causeRef.set(cause);
                                return HttpResponse.of(HttpStatus.FORBIDDEN);
-                           }).build((ctx, req) -> HttpResponse.of("OK"));
+                           })
+                           .build((ctx, req) -> HttpResponse.of("OK"));
+
+        // Create a meter registry and set a timer to the service.
+        final MeterRegistry meterRegistry = new SimpleMeterRegistry();
+        final Field timerField = AuthService.class.getDeclaredField("timer");
+        timerField.setAccessible(true);
```
Comment (jrhee17) [inline core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java:443]: I don't think we need reflection + what do you think of creating a dedicated test for recording metrics instead

```java
diff --git a/core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java b/core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
index cb65d5c8b..580f6f7de 100644
--- a/core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
+++ b/core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
@@ -36,6 +36,7 @@ import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
 import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
 import org.apache.hc.client5.http.impl.classic.HttpClients;
 import org.assertj.core.util.Strings;
+import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
 import org.junit.jupiter.api.extension.RegisterExtension;
 
@@ -43,6 +44,7 @@ import com.google.common.collect.ImmutableMap;
 
 import com.linecorp.armeria.client.BlockingWebClient;
 import com.linecorp.armeria.client.WebClient;
+import com.linecorp.armeria.common.AggregatedHttpResponse;
 import com.linecorp.armeria.common.HttpHeaderNames;
 import com.linecorp.armeria.common.HttpHeaders;
 import com.linecorp.armeria.common.HttpMethod;
@@ -83,10 +85,14 @@ class AuthServiceTest {
 
     private static final AsciiString CUSTOM_TOKEN_HEADER = HttpHeaderNames.of("X-Custom-Authorization");
 
+    private static final SimpleMeterRegistry meterRegistry = new SimpleMeterRegistry();
+
     @RegisterExtension
     static final ServerExtension server = new ServerExtension() {
         @Override
         protected void configure(ServerBuilder sb) throws Exception {
+            sb.meterRegistry(meterRegistry);
+
             final HttpService ok = new AbstractHttpService() {
                 @Override
                 protected HttpResponse doGet(ServiceRequestContext ctx, HttpRequest req) {
@@ -227,6 +233,11 @@ class AuthServiceTest {
         }
     }
 
+    @BeforeEach
+    void beforeEach() {
+        meterRegistry.clear();
+    }
+
     @Test
     void testBasicAuth() throws Exception {
         final BlockingWebClient webClient = WebClient.builder(server.httpUri())
@@ -422,6 +433,15 @@ class AuthServiceTest {
         }
     }
 
+    @Test
+    void shouldRecordMetrics() throws Exception {
+        assertThat(MoreMeters.measureAll(meterRegistry)).containsEntry("armeria.server.auth#count", 0.0);
+        AggregatedHttpResponse res = server.blockingWebClient(cb -> cb.auth(AuthToken.ofBasic("brown", "cony")))
+                                           .get("/on_failure_exception");
+        assertThat(res.status().code()).isEqualTo(200);
+        assertThat(MoreMeters.measureAll(meterRegistry)).containsEntry("armeria.server.auth#count", 1.0);
+    }
+
     @Test
     void shouldPeelRedundantAuthorizerExceptions() throws Exception {
         final AtomicReference<Throwable> causeRef = new AtomicReference<>();

```

File: grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcHttpJsonTranscodingServiceAnnotatedAuthServiceTest.java [hunk 6]
```diff
@@ -66,41 +56,45 @@ public class GrpcHttpJsonTranscodingServiceAnnotatedAuthServiceTest {
         @Override
         protected void configure(ServerBuilder sb) throws Exception {
             final GrpcService grpcService = GrpcService.builder()
-                    .addService(new AuthenticatedHttpJsonTranscodingTestService())
-                    .enableHttpJsonTranscoding(true)
-                    .build();
+                                                 .addService(new AuthenticatedHttpJsonTranscodingTestService())
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcHttpJsonTranscodingServiceAnnotatedAuthServiceTest.java:59]: Do you mind reverting incorrect indentations in this file?

**Review by jrhee17 — COMMENTED** [review]
Sorry about the delay 😅    I think once test related comments are addressed this PR should be good for merging 🙇

**Review by jrhee17 — APPROVED** [review]
Sorry it took a while 😄   Looks good to me 👍 🙇 👍

File: core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java [hunk 7]
```diff
@@ -110,22 +136,39 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exc
...
+                                       ServiceRequestContext ctx, HttpRequest req,
+                                       long startNanos)
             throws Exception {
         final AuthSuccessHandler handler = authorizerSuccessHandler == null ? defaultSuccessHandler
                                                                             : authorizerSuccessHandler;
-        return handler.authSucceeded(delegate, ctx, req);
+        try {
+            return handler.authSucceeded(delegate, ctx, req);
+        } finally {
+            maybeRecordTimer(successTimer, startNanos);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java:147]: The timer will include the additional time it takes to fully complete the request, which doesn't address the original issue. Let me move this before calling the handler. 😉

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java [hunk 8]
```diff
@@ -61,6 +61,9 @@ public void serviceAdded(ServiceConfig cfg) throws Exception {
                                                          .config()
                                                          .dependencyInjector();
         decorated = handlerRegistry.applyDecorators(delegate, dependencyInjector);
+        for (HttpService decorator : decorated.values()) {
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:64]: I found a bug where `Service.serviceAdded()` isn't called for the gRPC decorators.
it's a relatively simple fix, I've included the change here instead of creating a separate PR.

**Review by minwoox — APPROVED** [review]
Thanks, @yashmurty!

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java (hunk 8 above)
Comment (yashmurty) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java:64]: Thank you for the fix! 🙇
