### PR TITLE
Fix not to raise ConcurrentModificationException in HealthCheckedEndp…

### LINKED ISSUE #1989: `ConcurrentModificationException` in `HealthCheckedEndpointGroup.<init>`
```
Caused by: java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:979)
	at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroup.<init>(HealthCheckedEndpointGroup.java:126)
	at com.linecorp.armeria.client.endpoint.healthcheck.AbstractHealthCheckedEndpointGroupBuilder.build(AbstractHealthCheckedEndpointGroupBuilder.java:147)
```

### PR DESCRIPTION
**Pull request by minwoox**
…ointGroup.<init>

Fix #1989

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java [hunk 1]
```diff
@@ -123,7 +123,11 @@ public static HealthCheckedEndpointGroupBuilder builder(EndpointGroup delegate,
         updateCandidates(delegate.initialEndpointsFuture().join());
 
         // Wait until the initial health of all endpoints are determined.
-        contexts.values().forEach(ctx -> ctx.initialCheckFuture.join());
```
Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java]: Would be nice to add a test that previously failed - I think it's possible to do it deterministically by having a initial endpoints future that doesn't complete while adding endpoints.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java]: Ah, thanks! Let me make it in another PR.
