### PR TITLE
Provide an easier way to include additional error information into gRPC response

### LINKED ISSUE #4614: Provide easier way to include google error details to response in GrpcStatusFunction
Motivation:
currently, Users define method `io.grpc.Status apply(RequestContext ctx, Throwable throwable, Metadata metadata);` of `GrpcStatusFunction` to customize gRPC error responses.
Also, armeria supports google error formats by checking the grpc-status-details-bin trailer.
While this trailer is automatically set when throwing a `io.grpc.StatusException` created from `com.google.rpc.Status`,
i.e)
```java
throw StatusProto.toStatusException(
    Status.newBuilder()
        .setCode(1)
        .setMessage("some_message")
        .addDetails(
            Any.pack(
                BadRequest.newBuilder()
                    .addFieldViolations(
                        BadRequest.FieldViolation.newBuilder()
                            .setDescription("some_description")
                            .build()
                    )
                    .build()
            )
        )
);
```
It is not easy to include details from `GrpcStatusFunction` because io.grpc.Status does not know of grpc-status-details.
there is a workaround that I am currently using:
```java
class CustomExceptionHandler implements GrpcStatusFunction {
    @Override
    Status apply(RequestContext ctx, Throwable throwable, Metadata metadata) {
        StatusException statusException = StatusProto
                                            .toStatusException(
                                                Status.newBuilder()
                                                    .setCode(1)
                                                    .setMessage("some_message")
                                                    .addDetails(
                                                        Any.pack(
                                                            BadRequest.newBuilder()
                                                                .addFieldViolations(
                                                                    BadRequest.FieldViolation.newBuilder()
                                                                        .setDescription("some_description")
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                    )
                                            );
        metadata.merge(statusException.trailers);
        return Status.fromThrowable(statusException);
    }
}
```
which explicitly sets the grpc-status-details-bin trailer to the metadata, but this requires prior knowledge of how grpc status details work.
Can we make some changes to make this easier?

Suggestions:
1. make GrpcStatusFunction return a armeria-native Status, which contains a field about grpc status details and could be converted to io.grpc.Status
2. create a GoogleGrpcStatusFunction that instead of io.grpc.Status, returns a com.google.rpc.Status for its apply method. then, add a convert method to GrpcStatusFunction which sets the required trailers to metadata while converting.

etc

### PR DESCRIPTION
**Pull request by ta7uw**
Motivation:

It would be nice if Armeria gRPC users could easily develop their own richer error-handling model

Modifications:

- Add `GoogleGrpcStatusFunction` 

Result:

- Closes #4614
- Users can easily implement gRPC richer error model. This model enables servers to return and clients to consume additional error details expressed as one or more protobuf messages

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+    }
+
+    /**
+     * Maps the specified {@link Throwable} to a {@link com.google.rpc.Status},
+     * and mutates the specified {@link Metadata}.
+     * The `grpc-status-details-bin` key is ignored since it will be overwritten
+     * by {@link GoogleGrpcStatusFunction#apply(RequestContext, Throwable, Metadata)}.
+     * If {@code null} is returned, the built-in mapping rule is used by default.
+     */
+    com.google.rpc.Status applyStatusProto(RequestContext ctx, Throwable throwable, Metadata metadata);
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:78]: nit: `@Nullable`?

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+import io.grpc.Status;
+import io.grpc.StatusException;
+import io.grpc.StatusRuntimeException;
+import io.grpc.protobuf.lite.ProtoLiteUtils;
+
+/**
+ * A {@link GrpcStatusFunction} that provides a way to include details of a status into a {@link Metadata}.
+ * The details are stored in the `grpc-status-details-bin` key in the {@link Metadata}
+ * as a {@link com.google.rpc.Status}.
+ * You can implement a mapping function to converts {@link Throwable} into a {@link com.google.rpc.Status}
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:37]:
```suggestion
 * You can implement a mapping function to convert {@link Throwable} into a {@link com.google.rpc.Status}
```

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java (hunk 1 above)
Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:78]: Can we also make this method as default? I'm asking because, if we can make it, we can provide a default implementation for this interface so that users easily use this function.
`GrpcService.builder().exceptionMapping(GoogleGrpcStatusFunction.of())`

Can we do something like below? 🤔  
```java
default com.google.rpc.Status applyStatusProto(RequestContext ctx, Throwable throwable, Metadata metadata) {
    final Status status = Status.fromThrowable(throwable);
    return com.google.rpc.Status.newBuilder()
                                .setCode(status.getCode().value())
                                .setMessage(throwable.getMessage())
                                .build();
}
```

**Review by minwoox — COMMENTED** [review]
Thanks! Looks good overall. 😉

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+ * which is stored in the `grpc-status-details-bin` key in the {@link Metadata}.
+ * If a given {@link Throwable} is an instance of either {@link StatusRuntimeException} or
+ * {@link StatusException}, returns a {@link Status} retrieved from the exception
+ * prior to the mapping function you implemented.
+ */
+@UnstableApi
```
[the remark this answers is not in the document]
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:43]: When adding `@FunctionalInterface`, the following compile error happens.
Should I suppress this?
```
 [FunctionalInterfaceMethodChanged] Casting a lambda to this @FunctionalInterface can cause a behavior change from casting to a functional superinterface, which is surprising to users.  Prefer decorator methods to this surprising behavior.
    default Status apply(RequestContext ctx, Throwable throwable, Metadata metadata) {
                   ^
    (see https://errorprone.info/bugpattern/FunctionalInterfaceMethodChanged)
```

[the remark this answers is not in the document]
Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:43]: Oh no, let's leave it as is then. Sorry about it. 😓

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java (hunk 1 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:78]: It seems good!

Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:78]: I found a problem with this deafult implmentation.
We already have checked `throwable` to allow users to throw `StatusRuntimeException` created from `StatusProto.toStatusRuntimeException()` in users' own code below.

https://github.com/line/armeria/blob/6b3b73193eee8e4c131366ebf7ad4a946e38b459/grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java#L53-L59

Therefore, The default implementation you suggested would not be used.

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+
+    /**
+     * Maps the specified {@link Throwable} to a {@link com.google.rpc.Status},
+     * and mutates the specified {@link Metadata}.
+     * The `grpc-status-details-bin` key is ignored since it will be overwritten
+     * by {@link GoogleGrpcStatusFunction#apply(RequestContext, Throwable, Metadata)}.
+     * If {@code null} is returned, the built-in mapping rule is used by default.
+     */
+    com.google.rpc.@Nullable Status applyStatusProto(RequestContext ctx, Throwable throwable,
+                                                     Metadata metadata);
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:74]: Such peculiar syntax :thinking:

**Review by trustin — APPROVED** [review]
Nice addition to the project, @ta7uw! :bow:

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java (hunk 1 above)
Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java]: So, you mean adding the `throwable.getMessage()` to `com.google.rpc.Status` wouldn't be useful, right?
Then, let's go without the default implementation. 😉

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+
+import io.grpc.Metadata;
+import io.grpc.Metadata.Key;
+import io.grpc.protobuf.lite.ProtoLiteUtils;
+
+/**
+ * Common {@link Key}s that stored in a gRPC {@link Metadata}.
+ */
+@UnstableApi
+public interface GrpcMetadataKeys {
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java:32]: How about removing this interface and putting it to `MetadataUtil`?
```java
public final class MetadataUtil {
    static Key<Status> GRPC_STATUS_DETAILS_BIN_KEY = ... // Note that public modifier isn't needed.
}
```

**Review by minwoox — APPROVED** [review]
Just one nit. Thanks! 👍

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+
+    /**
+     * A key for {@link Status} whose name is {@code "grpc-status-details-bin"}.
+     */
+    Key<Status> GRPC_STATUS_DETAILS_BIN_KEY = Key.of(
+            GrpcHeaderNames.GRPC_STATUS_DETAILS_BIN.toString(),
+            ProtoLiteUtils.metadataMarshaller(Status.getDefaultInstance()));
```
Comment (jrhee17) [inline grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java:39]: I think there's a good chance `lite` isn't used in server-side applications. Did you use `ProtoLiteUtils` intentionally?

```suggestion
            ProtoUtils.metadataMarshaller(Status.getDefaultInstance()));
```

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java (hunk 5 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java:32]: we need to declare this public because `GoogleGrpcStatusFunction` refers to this key.
also, it seems useful when gRPC clients need to get an error model by using this key.

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+
+/**
+ * A {@link GrpcStatusFunction} that provides a way to include details of a status into a {@link Metadata}.
+ * The details are stored in the `grpc-status-details-bin` key in the {@link Metadata}
+ * as a {@link com.google.rpc.Status}.
+ * You can implement a mapping function to convert {@link Throwable} into a {@link com.google.rpc.Status}
+ * which is stored in the `grpc-status-details-bin` key in the {@link Metadata}.
+ * If a given {@link Throwable} is an instance of either {@link StatusRuntimeException} or
+ * {@link StatusException}, returns a {@link Status} retrieved from the exception
+ * prior to the mapping function you implemented.
```
Comment (jrhee17) [inline grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:40]:
```suggestion
 * {@link StatusException}, the {@link Status} retrieved from the exception is
 * returned with higher priority.
```

File: grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+
+import io.grpc.Metadata;
+import io.grpc.Status;
+import io.grpc.StatusException;
+import io.grpc.StatusRuntimeException;
+
+/**
+ * A {@link GrpcStatusFunction} that provides a way to include details of a status into a {@link Metadata}.
+ * The details are stored in the `grpc-status-details-bin` key in the {@link Metadata}
+ * as a {@link com.google.rpc.Status}.
```
Comment (jrhee17) [inline grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunction.java:35]: I think these lines are duplicate and removable
```suggestion
```

**Review by jrhee17 — APPROVED** [review]
Left some minor comments but looks good to me! Thanks @ta7uw ! 🙇 👍 🙇

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java (hunk 5 above)
Comment (minwoox) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java]: > we need to declare this public because GoogleGrpcStatusFunction refers to this key.

Oops, I thought `GoogleGrpcStatusFunction` is in the same package. Sorry about it.😓

File: grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java (hunk 6 above)
Comment (ta7uw) [reply grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMetadataKeys.java]: No, I didn't.
There seems not to be a difference internally.
it's okay to use it.

**Review by ikhoon — APPROVED** [review]
Thanks a lot, @ta7uw! 🙇‍♂️🙇‍♂️
Sorry for the late review.
