### PR TITLE
Fix route decorator evaluation order

### LINKED ISSUE #3160: Incorrect route decorator evaluation order
Route decorators are currently evaluated in incorrect order.

For example, the decorators in the following two examples should be evaluated in different orders:

```java
// Example A:
Server.builder()
      .decorator("glob:/**", decorator1)
      .decorator("glob:/foo/*", decorator2);
// Example B:
Server.builder()
      .decorator("glob:/foo/*", decorator3)
      .decorator("glob:/**", decorator4);
```

`decorator2` and `decorator4` must be evaluated before `decorator1` and `decorator3`, but it's `decorator1` and `decorator4` that are evaluated first.

To fix this issue, we need to change how we choose route decorators, e.g. do not use a trie but evaluate all routes of route decorators sequentially. Not efficient, but it's correct.

### PR DESCRIPTION
**Pull request by heowc**
Motivation:
Related #3160 

Modifications:

- In the case of route decorator router, modified to be created as `SequentialRouter`
- Modified to insert the route decorator forward when adding
- Modified order to `configureServerWithArmeriaSettings`
- Modified test
    - `AnnotatedServiceRequestLogNameTest`
    - `ContentPreviewingServiceTest`
    - `RouteDecoratingTest`
- Modified javadoc of `RouteDecoratingService`

Result:
- Correct route decorator evaluation order
- Fixed #3160

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java [hunk 1]
```diff
@@ -187,7 +187,7 @@ void decorateInOrder(String path, List<Integer> orders) {
             "/api/admin/1, , 401, ",
             "/assets/index.html, , 200, ",
             "/assets/resources/index.html, , 200, public",
-            "/assets/resources/private/profile.jpg, , 200, private",
+            "/assets/resources/private/profile.jpg, , 200, public",
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java:190]: Shouldn't we update the decorator ordering instead of updating the test parameters? Returning `public` on `.../private/...` doesn't sound right to me.

File: core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java [hunk 2]
```diff
@@ -71,16 +71,16 @@ protected void configure(ServerBuilder sb) throws Exception {
                            return HttpResponse.of(responseHeaders,
                                                   HttpData.ofUtf8("Hello " + aggregated.contentUtf8() + '!'));
                        }));
+            sb.decorator("/beforeEncoding", ContentPreviewingService.newDecorator(100));
             sb.decorator("/beforeEncoding", EncodingService.builder()
                                                            .minBytesToForceChunkedEncoding(1)
                                                            .newDecorator());
-            sb.decorator("/beforeEncoding", ContentPreviewingService.newDecorator(100));
             sb.service("/beforeEncoding", httpService);
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java:78]: How about moving this sentence before `.decorator()` for readability?

**Review by trustin — COMMENTED** [review]
Didn't think the fix was that easy 😄 Nice!

File: core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java (hunk 1 above)
Comment (heowc) [reply core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java]: Yes, I fixed the order. 👍

File: core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java (hunk 2 above)
Comment (heowc) [reply core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java]: I fixed 👍

**Review by trustin — APPROVED** [review]
Nice work, @heowc :+1:

File: core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java [hunk 3]
```diff
@@ -591,7 +592,7 @@ VirtualHostBuilder addServiceConfigSetters(ServiceConfigSetters serviceConfigSet
     }
 
     VirtualHostBuilder addRouteDecoratingService(RouteDecoratingService routeDecoratingService) {
-        routeDecoratingServices.add(routeDecoratingService);
+        routeDecoratingServices.add(0, routeDecoratingService);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java:595]: - How about using `LinkedList.addFirst(...)`?
- Could you add `The specified decorators are executed in reverse order of the insertion.` to the Javadoc of `ServerBuilder.decorator(...)` and `VirtualHostBuilder.decorator(...)`?

Comment (heowc) [reply core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java:595]: > How about using LinkedList.addFirst(...)?

Sound good to me! 👍 

> Could you add The specified decorator(s) is/are executed in reverse order of the insertion. to the Javadoc of ServerBuilder.decorator(...) and VirtualHostBuilder.decorator(...)?

It seems a bit insufficient to add only to the mentioned point. Or is it enough? 🤔
- `{ServerBuilder|VirtualHostBuilder}.routeDecorator(...)`
- `{ServerBuilder|VirtualHostBuilder}.decoratorUnder(...)`

Shouldn't we add it here too? What do you think?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java]: It looks good to add to `routeDecorator` and `decoratorUnder` too. :)

Comment (heowc) [reply core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java]: I fixed 👍

**Review by minwoox — APPROVED** [review]
Just one nit:
Could you add a test case for the example specified in #3160?

**Review by ikhoon — APPROVED** [review]
Thanks! @heowc

**Comment by heowc** [comment]
I need to modify the javadoc as well.

https://github.com/line/armeria/blob/0605acd3eb9aa410c929c3c9b837fc7d9c2efb67/core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java#L32...L64
