### PR TITLE
Make server build fail when duplicate route and fail handler.

### LINKED ISSUE #6498: `RejectRouterHandler.FAIL` does not work as intended.
Aremeria has three types of `RejectRouterHandler`.
- `DISABLED`
- `WARN`
- `FAIL`

However, both `WARN` and `FAIL` ultimately only produce warning logs, and the server builds successfully.
Therefore, to preserve the intended behavior of `FAIL`, the server build should fail when FAIL is used.

```java
Server.builder()
                     .virtualHost("foo.com")
                     .rejectedRouteHandler(RejectedRouteHandler.FAIL)
                     .service("/foo", (ctx, req) -> HttpResponse.of("ok"))
                     .service("/foo", (ctx, req) -> HttpResponse.of("duplicate"));
```

### PR DESCRIPTION
**Pull request by chickenchickenlove**
### Motivation:
`RejectRouterHandler.FAIL` does not work as intended.

### Modifications:
- The call site that calls `rejectionHandler.handleDuplicateRoute(virtualHost, route, existingRoute)` catch`IllegalStateException` and throw it.
- Fix false alert in `ContextPathTest`. (`ContextPathTest` already has duplicated route with `RejectRouterHandler.FAIL`, but it just warn not fail. )

### Result:
- If there are duplicated routes and `RejectRouterHandler.FAIL` is configured, 
Server build will be failed.
- Close #6498

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 1]
```diff
@@ -72,6 +72,8 @@ static Router<ServiceConfig> ofVirtualHost(VirtualHost virtualHost, Iterable<Ser
         final BiConsumer<Route, Route> rejectionConsumer = (route, existingRoute) -> {
             try {
                 rejectionHandler.handleDuplicateRoute(virtualHost, route, existingRoute);
+            } catch (IllegalStateException shouldFailException) {
+                throw shouldFailException;
             } catch (Exception e) {
                 logger.warn("Unexpected exception from a {}:",
                             RejectedRouteHandler.class.getSimpleName(), e);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java]: I personally prefer removing these catch clauses and changing the signature of `handleDuplicateRoute`. But since that was a breaking change, I'm fine with the current change. Thanks!

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java]: What do you think of introducing a new exception (e.g. `DuplicateRouteException`) instead of using `IllegalStateException`? This might prevent rethrowing an `IllegalStateException` which is raised from a user-defined handler.

Comment (chickenchickenlove) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java]: @minwoox 
Sounds good. I prefer to do so as well! 
Let me make new commits based on your comments! 🙇‍♂️

File: core/src/test/java/com/linecorp/armeria/server/RejectRouterHandlerTest.java [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+import java.util.List;
+
+import org.junit.jupiter.api.Test;
+
+import com.google.common.collect.ImmutableList;
+
+import com.linecorp.armeria.client.DuplicateRouteException;
+import com.linecorp.armeria.common.HttpResponse;
+
+public class RejectRouterHandlerTest {
```
Comment (jrhee17) [inline core/src/test/java/com/linecorp/armeria/server/RejectRouterHandlerTest.java]:
```suggestion
class RejectRouterHandlerTest {
```

File: core/src/main/java/com/linecorp/armeria/server/DuplicateRouteException.java [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+package com.linecorp.armeria.client;
+
+/**
+ * A {@link RuntimeException} thrown when attempting to register a route
+ * that conflicts with an existing route for the same path.
+ *
+ * <p>This exception is raised when multiple routes share an identical path
+ * and thus cannot be uniquely distinguished.</p>
+ */
+public final class DuplicateRouteException extends RuntimeException {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/DuplicateRouteException.java:29]: Do you think we should place this in the server-side package?

Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/DuplicateRouteException.java:29]:
```suggestion
@UnstableApi
public final class DuplicateRouteException extends RuntimeException {
```

Comment (chickenchickenlove) [reply core/src/main/java/com/linecorp/armeria/server/DuplicateRouteException.java:29]: Addressed!

Comment (chickenchickenlove) [reply core/src/main/java/com/linecorp/armeria/server/DuplicateRouteException.java:29]: Addressed!

**Review by minwoox — APPROVED** [review]
Still, looks great. Thanks!
