### PR TITLE
Potential fix for flaky HttpServerTest.testTimeout()

### LINKED ISSUE #467: HttpServerTest.testTimeout flaky
Had this failure happen on a build, rebuild with no code change fixed.

```
:shaded-test:shadedCoreTest[jetty-alpn-agent] Using: alpn-boot-8.1.10.v20161026.jar
com.linecorp.armeria.server.http.HttpServerTest > testTimeout[1: h1] FAILED
    java.lang.AssertionError: 
    Expected: is <503>
         but: was <200>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.linecorp.armeria.server.http.HttpServerTest.testTimeout(HttpServerTest.java:407)
```

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

HttpServerTest.testTimeout() sometimes fails with the following
assertion failure:

    com.linecorp.armeria.server.http.HttpServerTest > testTimeout[1: h1] FAILED
        java.lang.AssertionError:
        Expected: is <503>
             but: was <200>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
            at com.linecorp.armeria.server.http.HttpServerTest.testTimeout(HttpServerTest.java:407)

which means the server sent the '503 Service Unavailable' response
correctly, but the RequestLog in the queue contains '200 OK'.

We clean the queue of RequestLogs before starting each test, but it is
possible that the RequestLog of the previous test is added *after* the
next test is started. i.e. '200 OK' ResponseLog may not be for the
current test.

Modifications:

- Keep the number of expected RequestLogs and wait until all RequestLogs
  are complete between each test
- Fix a bug where a RequestLog is never completed when '413 Request
  Entity Too Large' error occurs

Result:

- May fix #467. It's difficult to say this will fix the flakiness
  because it's been only reproducible in CI machines at low chance.
- RequestLog is completed even when '413 Request Entity Too Large' error
  occurs.

### CODE REVIEW

**Comment by trustin** [comment]
@anuraaga SGTM. Will push a fix tomorrow.

**Comment by trustin** [comment]
@anuraaga @hyangtack Updated the pull request to use a counter and fixed a bug thanks to it. Please review again.

File: core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java [hunk 1]
```diff
@@ -394,6 +400,16 @@ public void reset() {
         clientMaxResponseLength = MAX_CONTENT_LENGTH;
     }
 
+    @After
+    public void clearRequestLogs() {
+        try {
+            await().atMost(10, TimeUnit.SECONDS).until(() -> pendingRequestLogs.get() == 0);
```
Comment (anuraaga) [inline core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java]: 10 secs is the default so no need to set atMost (we never do elsewhere either to remove verbosity)

Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java]: Oh, didn't know about the default :-)

Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java]: Fixed. Also removed all atMost() calls throughout the code. /cc @hyangtack
