### PR TITLE
Complete session after SessionProtocol and ProxyConnectionEvent are t…

### LINKED ISSUE #2606: Intermittent failure in ProxyClientIntegrationTest
```
ProxyClientIntegrationTest > testHttpsProxyBasicCase() FAILED
    java.util.concurrent.CompletionException: com.linecorp.armeria.client.WriteTimeoutException
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2115)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
        at com.linecorp.armeria.client.proxy.ProxyClientIntegrationTest.testHttpsProxyBasicCase(ProxyClientIntegrationTest.java:232)

        Caused by:
        com.linecorp.armeria.client.WriteTimeoutException
            at com.linecorp.armeria.client.WriteTimeoutException.get(WriteTimeoutException.java:36)
            at com.linecorp.armeria.client.HttpRequestSubscriber.lambda$onSubscribe$0(HttpRequestSubscriber.java:145)
            at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
            at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
            at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
            at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:830)
```

### PR DESCRIPTION
**Pull request by minwoox**
…riggered

Motivation:
When we use the client-side proxy, we use the channel as soon as it's established to the proxy.
However, the writing to the channel is pending until the proxy connects to the final destination.
This causes a problem especially the distance is far away between the proxy and the final destination because
it triggers `WriteTimeoutException`.

Modification:
- Complete sesessin after `SessionProtocol` event and `ProxyConnectionEvent` are triggered.

Result:
- Close #2606
- You no longer see `WriteTimeoutException` due to the pending write when using the client-side proxy.

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java [hunk 1]
```diff
@@ -546,6 +544,17 @@ protected void channelRead0(ChannelHandlerContext ctx, FullHttpRequest msg) thro
         }
     }
 
+    private static final class SleepHandler extends ChannelInboundHandlerAdapter {
+
+        @Override
+        public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
+            if (evt instanceof ProxySuccessEvent) {
+                Thread.sleep(Flags.defaultWriteTimeoutMillis());
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java:552]: Could you add some comments about what this sentence does? e.g. why we block the event loop

Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java:554]: Fixed. 😉

File: core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java [hunk 2]
```diff
@@ -120,6 +123,16 @@
...
+
+        switch (proxyConfig.proxyType()) {
+            case SOCKS4:
+            case SOCKS5:
+            case CONNECT:
+                useProxyConnection = true;
+                break;
+            default:
+                useProxyConnection = false;
+        }
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java:135]: nit: Not strong here 😉
```
useProxyConnection = proxyConfig.proxyType() != ProxyType.DIRECT;
```

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java:135]: better using explicit `case` and throwing something at `default`?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java:135]: > useProxyConnection = proxyConfig.proxyType() != ProxyType.DIRECT;

A user might implement his own `ProxyConfig` and returns `null` for `proxyType()`. So we should check it explicitly.

> better using explicit case and throwing something at default?

We've already gone through the logic [here](
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java#L170) which just leaves a warning log.
I thought we don't have to leave a log twice. 😄
