### PR TITLE
Fix `byte[]` and `HttpData` conversion

### LINKED ISSUE #1999: ByteArrayResponseConverterFunction clamped to two MediaTypes
The following snippet should imho work:
```
    @Get("/favicon.ico")
    @Produces("image/gif")
    private ByteArray favicon() {
        return new byte[0]
    }
```

It does not work however, because if the `contentType` isn't null, and isn't one of APPLICATION_BINARY or OCTET_STREAM, the converter will not be used.

Discussion about problem:
https://app.slack.com/client/T1NH00FK9/C1NGPBUH2/thread/C1NGPBUH2-1565946569.136900

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

The following annotated service method will fail because
`ByteArrayResponseConverterFunction` currently does not convert `byte[]`
or `HttpData` with the content type other than
`application/octet-stream` or `application/binary`.

Modifications:

- Convert `byte[]` or `HttpData` even if the content type is neither
  `application/octet-stream` nor `application/binary`.
- Also fix the case where `byte[]` or `HttpData` is not converted when a
  service method produces text content.

Result:

- Fixes #1999

### CODE REVIEW

**Comment by trustin** [comment]
For @tobias-

File: core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java [hunk 1]
```diff
@@ -563,15 +599,33 @@ public void produceTypeAnnotationBasedDefaultResponseConverter() throws Exceptio
...
+        System.err.println(res.contentUtf8());
+        assertThat(res.content().array()).isEqualTo(BYTEARRAY);
+
+        res = aggregated(client.get("/byteArrayTxt"));
+        assertThat(res.contentType()).isEqualTo(MediaType.PLAIN_TEXT_UTF_8);
+        assertThat(res.content().array()).isEqualTo(BYTEARRAY);
+
+        res = aggregated(client.get("/httpDataTxt"));
+        assertThat(res.contentType()).isEqualTo(MediaType.PLAIN_TEXT_UTF_8);
+        System.err.println(res.contentUtf8());
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java]: ditto

File: core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java [hunk 2]
```diff
@@ -563,15 +599,33 @@ public void produceTypeAnnotationBasedDefaultResponseConverter() throws Exceptio
...
-        assertThat(res.content().array()).isEqualTo("¥".getBytes());
+        assertThat(res.content().array()).isEqualTo(BYTEARRAY);
+
+        res = aggregated(client.get("/byteArrayGif"));
+        assertThat(res.contentType()).isEqualTo(MediaType.GIF);
+        assertThat(res.content().array()).isEqualTo(BYTEARRAY);
+
+        res = aggregated(client.get("/httpDataPng"));
+        assertThat(res.contentType()).isEqualTo(MediaType.PNG);
+        System.err.println(res.contentUtf8());
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java]: nit: remove this? 😀

Comment (trustin) [reply core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java]: Oops :sweat_smile:
