### PR TITLE
Fix StackOverFlow when dumpOpenSslInfo is set to true

### LINKED ISSUE #2417: Dcom.linecorp.armeria.dumpOpenSslInfo=true flag throws server into infinite loop
Version: Armeria 0.95

```
2020-01-23 19:24:36.539  INFO 6 --- [           main] c.l.a.c.Flags                            : Using OpenSSL: BoringSSL, 0x1010007f
2020-01-23 19:24:36.539  INFO 6 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.useOpenSsl: true (default)
2020-01-23 19:24:36.539  INFO 6 --- [           main] c.l.a.c.Flags                            : Using OpenSSL: BoringSSL, 0x1010007f
2020-01-23 19:24:36.539  INFO 6 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.useOpenSsl: true (default)
2020-01-23 19:24:36.539  INFO 6 --- [           main] c.l.a.c.Flags                            : Using OpenSSL: BoringSSL, 0x1010007f
2020-01-23 19:24:36.539  INFO 6 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.useOpenSsl: true (default)
2020-01-23 19:24:36.539  INFO 6 --- [           main] c.l.a.c.Flags                            : Using OpenSSL: BoringSSL, 0x1010007f
2020-01-23 19:24:36.543  WARN 6 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'armeriaServer' defined in com.linecorp.armeria.spring.ArmeriaAutoConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.lang.StackOverflowError
2020-01-23 19:24:36.577  INFO 6 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-23 19:24:36.595 ERROR 6 --- [           main] o.s.b.SpringApplication                  : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'armeriaServer' defined in com.linecorp.armeria.spring.ArmeriaAutoConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.lang.StackOverflowError
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:625) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at zipkin.server.ZipkinServer.main(ZipkinServer.java:54) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [zipkin-server/:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [zipkin-server/:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [zipkin-server/:?]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597) [zipkin-server/:?]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.lang.StackOverflowError
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        ... 25 more
Caused by: java.lang.StackOverflowError
        at org.apache.logging.log4j.core.pattern.DatePatternConverter.getThreadLocalFormatter(DatePatternConverter.java:299) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.pattern.DatePatternConverter.formatWithoutAllocation(DatePatternConverter.java:295) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.pattern.DatePatternConverter.format(DatePatternConverter.java:288) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.pattern.DatePatternConverter.format(DatePatternConverter.java:265) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.springframework.boot.logging.log4j2.ColorConverter.format(ColorConverter.java:121) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:341) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:197) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:543) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:485) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:460) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.core.Logger.log(Logger.java:162) ~[log4j-core-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2190) ~[log4j-api-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2144) ~[log4j-api-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2127) ~[log4j-api-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2026) ~[log4j-api-2.12.1.jar:2.12.1]
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899) ~[log4j-api-2.12.1.jar:2.12.1]
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:189) ~[log4j-slf4j-impl-2.12.1.jar:2.12.1]
        at com.linecorp.armeria.common.Flags.getNormalized(Flags.java:931) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.common.Flags.getBoolean(Flags.java:875) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.common.Flags.getBoolean(Flags.java:871) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.common.Flags.useOpenSsl(Flags.java:413) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.internal.SslContextUtil.createSslContext(SslContextUtil.java:90) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.common.Flags.useOpenSsl(Flags.java:426) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.internal.SslContextUtil.createSslContext(SslContextUtil.java:90) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.common.Flags.useOpenSsl(Flags.java:426) ~[armeria-0.95.0.jar:?]
        at com.linecorp.armeria.internal.SslContextUtil.createSslContext(SslContextUtil.java:90) ~[armeria-0.95.0.jar:?]
		```

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
Related #2417

Modification:
- Set `Flags.useOpenSsl` first so that `useOpenSsl()` does not call recursively.
- `Flags.dumpOneSslInfo()` returns `false` when `Flags.useOpenSsl()` returns `false`.
- Add a test case

Result:
- Closes #2417
- You can now set `com.linecorp.armeria.dumpOpenSslInfo=true` property.

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/common/FlagsTest.java [hunk 1]
```diff
@@ -48,12 +48,21 @@ public void epollAvailableOnLinux() {
...
         assumeFalse("false".equals(System.getProperty("com.linecorp.armeria.useOpenSsl")));
 
         assertThat(Flags.useOpenSsl()).isTrue();
         assertThat(OpenSsl.isAvailable()).isTrue();
     }
+
+    @Test
+    void dumpOpenSslInfoDoNotThrowStackOverFlowError() {
+        System.setProperty("com.linecorp.armeria.dumpOpenSslInfo", "true");
+        System.setProperty("com.linecorp.armeria.useOpenSsl", "true");
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/FlagsTest.java]: You don't need to address this review. Just I guess `@SetSystemProperty` in JUnit Pioneer seems cleaner to set a system property.

```java
@SetSystemProperty(key = "some property", value = "new value")
```

https://junit-pioneer.org/docs/system-properties/

**Comment by ikhoon** [comment]
```java
com.linecorp.armeria.common.FlagsTest > dumpOpenSslInfoDoNotThrowStackOverFlowError() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <false>
    to be equal to:
     <true>
    but was not.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.common.FlagsTest.dumpOpenSslInfoDoNotThrowStackOverFlowError(FlagsTest.java:66)
```

The test was failed. https://ci.appveyor.com/project/line/armeria/builds/30334389/job/vjjctumxs00550m4#L1219

File: core/src/test/java/com/linecorp/armeria/common/FlagsTest.java (hunk 1 above)
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/common/FlagsTest.java]: That's a nice suggestion. Let me used that. Thanks!

**Comment by minwoox** [comment]
> The test was failed.

Oops. 😅 Fixed using `@SetSystemProperty` as suggested by @ikhoon.

**Comment by ikhoon** [comment]
The static field in Flags was initialized before setting test system properties. I think we need a new method for the test.

```java
// in Flags.java
public static boolean useOpenSsl() {
        if (useOpenSsl != null) {
            return useOpenSsl;
        }
        useOpenSsl(dumpOpenSslInfo());
}

// this method read system properties lazily
@VisibleForTest
static boolean useOpenSsl(boolean dumpOpenSslInfo) {
  
   ...
}

// in FlagsTest.java
@Test
void dumpOpenSslInfoDoNotThrowStackOverFlowError() {
    Flags.useOpenSsl(true /* dumpOpenSslInfo */);
}
```

By the way, enjoy lunar new year. 😀

**Comment by minwoox** [comment]
Thanks for the suggestion. 😄
I rather change the field to set lazily after `useOpenSsl` is set.
I think `dumpOpenSslInfo` needs to be false when `useOpenSsl` is false. 😄

**Comment by minwoox** [comment]
Will reopen when it's ready. 😉

**Comment by minwoox** [comment]
This is ready for the review. 😉

File: core/src/test/java/com/linecorp/armeria/common/FlagsTest.java [hunk 2]
```diff
@@ -48,12 +61,69 @@ public void epollAvailableOnLinux() {
...
         assertThat(OpenSsl.isAvailable()).isTrue();
     }
+
+    @Test
+    void dumpOpenSslInfoDoNotThrowStackOverFlowError() throws Throwable {
+        assumeTrue(OpenSsl.isAvailable());
+        System.setProperty("com.linecorp.armeria.dumpOpenSslInfo", "true");
+
+        // There's a chance that Flags.useOpenSsl() is already called by other test cases, which means that
+        // we cannot set dumpOpenSslInfo. So we use our own class loader to load the Flags class.
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/FlagsTest.java]: nit: The current workaround is not bad. But how about making `useOpenSsl` and `dumpOpenSslInfo` package-private? 
I think We can test `Flags.useOpenSsl()` after setting `null` to `useOpenSsl` and `dumpOpenSslInfo`.

Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/common/FlagsTest.java]: > I think We can test Flags.useOpenSsl() after setting useOpenSsl and dumpOpenSslInfo to null.

Yes, we can do that way as well. But I'm not sure if it's a good way. 🤔 

> The current workaround is not bad.

So you think setting `null` to the field and calling the method again is better?

Comment (ikhoon) [reply core/src/test/java/com/linecorp/armeria/common/FlagsTest.java]: I guess the two options have both pros and cons. I'm fine with the class loader version. 😀

File: core/src/test/java/com/linecorp/armeria/common/FlagsTest.java [hunk 3]
```diff
@@ -16,25 +16,38 @@
 package com.linecorp.armeria.common;
 
 import static org.assertj.core.api.Assertions.assertThat;
-import static org.junit.Assume.assumeFalse;
-import static org.junit.Assume.assumeTrue;
+import static org.junit.jupiter.api.Assumptions.assumeFalse;
+import static org.junit.jupiter.api.Assumptions.assumeTrue;
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/common/FlagsTest.java]: AssertJ also has `assumeThat`.

Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/common/FlagsTest.java]: Fixed. 😉

**Comment by trustin** [comment]
Thanks, @minwoox!

**Comment by minwoox** [comment]
Thanks for reviewing!
