### PR TITLE
Customize http status for error response

### LINKED ISSUE #543: Allow more customization of error response when resetting the stream
When resetting the stream with `HttpResponseWriter.close(Throwable)`, currently the possible error behavior is mostly hard-coded into armeria.

https://github.com/line/armeria/blob/924b3fa564930cfd36d6aa4d87ca2f35313c4d7d/core/src/main/java/com/linecorp/armeria/server/http/HttpResponseSubscriber.java#L218

There can be some use cases for allowing customizing the error code. Implementation could be simply adding a `ArmeriaHttpException` that takes an HttpStatus and Http2Error as parameters.

### PR DESCRIPTION
**Pull request by imasahiro**
Motivations:
- The error behavior of HttpResponseSubscriber#onError is hard-coded and cannot customize error code.

Modifications:
- Add ArmeriaHttpException which makes more customizable error handling

Results:
- A user can customize error code through ArmeriaHttpException
- Fixes #543

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+import com.linecorp.armeria.common.HttpStatus;
+
+import io.netty.handler.codec.http2.Http2Error;
+
+/**
+ * A {@link RuntimeException} that is raised when an armeria internal http exception has occurred.
+ * This class is the general class of exceptions produced by a failed request or a reset stream.
+ */
+public abstract class ArmeriaHttpException extends RuntimeException {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java]: - A user may want to instantiate this exception?
- How about overriding `fillInStackTrace()` and doing nothing when `Flags.verboseExceptions()` is disabled?
- Could be renamed so it doesn't have `Armeria` in its name? e.g. `HttpResponseException`

File: core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+    private static final long serialVersionUID = 3487991462085151316L;
+
+    private final HttpStatus httpStatus;
+    private final Http2Error http2error;
+
+    /**
+     * Creates a new instance.
+     */
+    protected ArmeriaHttpException(HttpStatus httpStatus, Http2Error http2error) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java]: I'm curious when a user wants to decide which `Http2Error` code to use. I think it's session-layer-specific matter so a user doesn't need to know about it. i.e. `HttpResponseSubscriber` should decide from the `HttpStatus` automatically. What do you think?

Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java]: When looking through `Http2Error`, I wasn't too sure on the semantics of `INTERNAL_ERROR` and `CANCEL` and thought they might be user-specified but if there are clear semantics for them, it makes sense to me. I've somewhat forgotten the context of filing the issue when trying to match gRPC upstream (oops!), but think it was mainly related to the HTTP/1 code, not HTTP/2

Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java]: Looking from the specification (http://httpwg.org/specs/rfc7540.html#ErrorCodes) I'm pretty sure HTTP/2 Error Codes are not for applications but for session-layer implementations, so I think it's better hiding it from users.

Comment (anuraaga) [inline core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java]: SGTM

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+     * Creates a new instance.
+     */
+    protected HttpResponseException(HttpStatus httpStatus) {
+        this.httpStatus = httpStatus;
+    }
+
+    /**
+     * Returns the {@link HttpStatus} that will be sent to a client.
+     */
+    HttpStatus httpStatus() {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java]: Perhaps this could be public?

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+public abstract class HttpResponseException extends RuntimeException {
+    private static final long serialVersionUID = 3487991462085151316L;
+
+    private final HttpStatus httpStatus;
+
+    /**
+     * Creates a new instance.
+     */
+    protected HttpResponseException(HttpStatus httpStatus) {
+        this.httpStatus = httpStatus;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java]: - Null check?
- Should we prohibit specifying 1xx~3xx?

File: core/src/test/java/com/linecorp/armeria/server/HttpResponseExceptionTest.java [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+import org.junit.Test;
+
+import com.linecorp.armeria.common.HttpStatus;
+
+public class HttpResponseExceptionTest {
+    static {
+        System.setProperty("com.linecorp.armeria.verboseExceptions", "false");
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/server/HttpResponseExceptionTest.java]: I think this will affect other tests. How about just removing this test or checking parameter validations only?

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+    private static final long serialVersionUID = 3487991462085151316L;
+
+    private final HttpStatus httpStatus;
+
+    /**
+     * Creates a new instance.
+     */
+    protected HttpResponseException(HttpStatus httpStatus) {
+        requireNonNull(httpStatus, "httpStatus");
+        if (100 <= httpStatus.code() && httpStatus.code() < 399) {
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java]: nit: `< 399` -> `< 400`?

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+            throw new IllegalArgumentException("httpStatus: " + httpStatus +
+                                               " (expected: code < 100 || 400 <= code");
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java]: - `400 <= code` -> `code >= 400`?
- Missing closing parenthesis

**Comment by imasahiro** [comment]
Updated

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+    private final HttpStatus httpStatus;
+
+    /**
+     * Creates a new instance.
+     */
+    protected HttpResponseException(HttpStatus httpStatus) {
+        requireNonNull(httpStatus, "httpStatus");
+        if (100 <= httpStatus.code() && httpStatus.code() < 400) {
+            throw new IllegalArgumentException("httpStatus: " + httpStatus +
+                                               " (expected: code < 100 || code >= 400)");
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java]: Sorry but how about this?

` (expected: a status that's neither informational, success nor redirection)`

.. which reads better (at least to me)

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+public abstract class HttpResponseException extends RuntimeException {
+    private static final long serialVersionUID = 3487991462085151316L;
+
+    private final HttpStatus httpStatus;
+
+    /**
+     * Creates a new instance.
+     */
+    protected HttpResponseException(HttpStatus httpStatus) {
+        requireNonNull(httpStatus, "httpStatus");
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java]: Just one last nit: how about:

    super(requireNonNull(httpStatus, "httpStatus").toString());

**Comment by trustin** [comment]
Thanks a lot, @imasahiro !
