### PR TITLE
Increase timeout for BraveClientIntegrationTest

### LINKED ISSUE #2534: Flaky test: BraveClientIntegrationTest
```
BraveClientIntegrationTest > asyncRootSpan[1] FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <698454d500542dc9/698454d500542dc9>
    to be equal to:
     <null>
    but was not.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at brave.test.http.ITHttpAsyncClient.asyncRootSpan(ITHttpAsyncClient.java:142)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
`BraveClientIntegrationTest` has 5 seconds timeout but it could take longer because of instrumenting test coverage.
We should increase it to 10 seconds.

Modification:
- Increase timeout for `BraveClientIntegrationTest`

Result:
- Close #2534

### CODE REVIEW

**Comment by trustin** [comment]
Let me rebuild a few more times.

File: brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java [hunk 1]
```diff
@@ -49,6 +53,9 @@
 @RunWith(Parameterized.class)
 public class BraveClientIntegrationTest extends ITHttpAsyncClient<WebClient> {
 
+    @Rule(order = Integer.MAX_VALUE)
```
Comment (adriancole) [inline brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java]: neat. didn't know you could override like this. We can increase upstream also. Main thing was to not hang terribly long.

Comment (minwoox) [reply brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java]: Ah, let me send a PR for that. Thanks!
