### PR TITLE
Close in-progress responses when channel is closed.

### LINKED ISSUE #1028: Zombie gRPC connections
When using constructs of the type:
```
rpc StreamClientCancels2(SimpleRequest) returns (stream SimpleResponse);
```
there is no way to know if the client has disconnected. OnCancelHandler is not called, nor is there any exception thrown when sending more data. It will just silently discard all data sent.

I've added a test case (CC0 on my changes, claim ownership if you want)
https://github.com/tobias-/armeria/tree/zombie_connections

### PR DESCRIPTION
**Pull request by anuraaga**
This ended up being more complicated than I expected. Please check that my understanding makes sense :)

Currently, there is no notification to response streams if the client disconnects. If the client disconnects before finishing a request, server logic will be notified in the request stream, but if it disconnects after finshing a request but before finishing a response, the server logic has no way of knowing to abort processing.

- Now, any in-progress response streams are aborted when channel is closed
- Default behavior of `StreamMessage.write` changed to throw an exception when stream is closed, which is more natural. `tryWrite` can be used when this is not desired.
- Also fix that a client close on HTTP/1 request did not notify the request stream of closure
- Fixes a test which kept a stream in a static variable and writing consecutively to it

Fixes #1028

### CODE REVIEW

**Comment by tobias-** [comment]
Just to confirm, yes, I've tested with this patch, and it solves the main issue with messages sent over gRPC being silently dropped.

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java [hunk 1]
```diff
@@ -33,6 +35,31 @@
...
+    /**
+     * Writes the specified object to the {@link StreamMessage}. The written object will be transferred to the
+     * {@link Subscriber}.
+     *
+     * @throws AbortedStreamException if the stream was already closed
+     * @throws IllegalArgumentException if the publication of the specified object has been rejected
+     */
+    default void write(T o) {
+        if (!tryWrite(o)) {
+            throw AbortedStreamException.get();
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: How about using `new IllegalStateException("stream closed")`? `AbortedStreamException` is specifically for the notification of `abort()`.

Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: Sure - done

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java [hunk 2]
```diff
@@ -33,6 +35,31 @@
...
+        if (!tryWrite(o)) {
+            throw new IllegalStateException("stream closed");
+        }
+    }
+
+    /**
+     * Writes the specified object {@link Supplier} to the {@link StreamMessage}. The object provided by the
+     * {@link Supplier} will be transferred to the {@link Subscriber}.
+     *
+     * @throws AbortedStreamException if the stream was already closed.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: You need to update Javadoc as well. :-)

Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: Oops

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java [hunk 3]
```diff
@@ -33,6 +35,32 @@
      */
     boolean isOpen();
 
+    /**
+     * Writes the specified object to the {@link StreamMessage}. The written object will be transferred to the
+     * {@link Subscriber}.
+     *
+     * @throws IllegalArgumentException if the stream was already closed or the publication of the specified
+     *         object has been rejected
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: `IllegalStateException` is raised when stream was closed.

Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: Urgh - too much coffee can't read

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: covfefe

**Comment by trustin** [comment]
Oops. Build failure?

**Comment by trustin** [comment]
Another failure:

```
com.linecorp.armeria.server.grpc.GrpcServiceServerTest > clientSocketClosedAfterHalfCloseBeforeCloseHttp1 FAILED
    java.lang.IllegalStateException: stream closed
com.linecorp.armeria.server.grpc.GrpcServiceServerTest > clientSocketClosedAfterHalfCloseBeforeCloseHttp2 FAILED
    java.lang.IllegalStateException: stream closed
```

**Comment by trustin** [comment]
Thanks, @anuraaga!
