### PR TITLE
Fix `NullPointerException` in `HttpResponseDecoder`

### LINKED ISSUE #3729: `NullPointerException` in `client.HttpResponseDecoder`
I got reported a NPE issue from [a Armeria Slack thread](https://line-armeria.slack.com/archives/C1NGPBUH2/p1627494312253700?thread_ts=1626604451.208400&cid=C1NGPBUH2).
```
Caused by:java.lang.NullPointerException: Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null(Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null)
  at com.linecorp.armeria.client.HttpResponseDecoder.failUnfinishedResponses(HttpResponseDecoder.java:131)
  at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:415)
```

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

```
Caused by:java.lang.NullPointerException: Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null(Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null)
  at com.linecorp.armeria.client.HttpResponseDecoder.failUnfinishedResponses(HttpResponseDecoder.java:131)
  at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:415)
```

`HttpResponseDecoder` MUST be executed in an event loop. The NPE might be
caused by recursive calls of `failUnfinishedResponses()`.
Even though we use `Iterator`, a null reference could be returned.

Modifications:

- Add `closing` flag to ensure serialized executions

Result:

- You no longer see `NullPointerException` when HTTP/1 connection of a client is closed.
- Fixes #3729

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java [hunk 1]
```diff
@@ -122,14 +123,21 @@ final boolean reserveUnfinishedResponse(int maxUnfinishedResponses) {
...
 
     final void failUnfinishedResponses(Throwable cause) {
-        for (final Iterator<HttpResponseWrapper> iterator = responses.values().iterator();
-             iterator.hasNext();) {
-            final HttpResponseWrapper res = iterator.next();
-            // To avoid calling removeResponse by res.close(cause), remove before closing.
-            iterator.remove();
-            unfinishedResponses--;
-            res.close(cause);
+        if (wip++ > 0) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:126]: How about just using a boolean flag? such as we use `inOnNext`?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:126]: Otherwise, how about adding `closing` flag? I think we should call failUnfinishedResponses() only once.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:126]: That also sounds good. 👍

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:126]: By the way, the recursive remove might be called by `removeResponse()`.
Added a checking logic there too.

**Review by minwoox — APPROVED** [review]
Thanks!

**Review by trustin — APPROVED** [review]
