### PR TITLE
Ensure response body is not sent for a HEAD request

### LINKED ISSUE #4511: Should not return a content body for `HEAD` method in `AggregatedHttpResponseHandler`
There is a regression that a content body could be sent even if a `HEAD` method is set in a request header.
`HttpResponseSubscriber` handles the `HEAD` method correctly, but `AggregatedHttpResponseHandler` does not consider the `HEAD` method.
https://github.com/line/armeria/blob/5d1d9a5525ffe2305fcb56f32763748d1aa30168/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L153-L154
https://github.com/line/armeria/blob/5d1d9a5525ffe2305fcb56f32763748d1aa30168/core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java#L129-L134

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

`AbstractHttpResponseHandler` writes the response body generated by a service as it is, even if the method it handles always has empty response body, such as HEAD.

Modification:

- Fixed `AbstractHttpResponseHandler` so it doesn't write the response body when the request method is HEAD.
  - Also, explicitly released the body which was unnecessarily generated by a service.

Result:

- Armeria doesn't send a bad response with non-empty body anymore when:
  - a service's `ExchangeType` is `UNARY`; and
  - a service generates non-empty body for a HEAD request.
- Fixes #4511

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks for fixing the regression, @trustin! 🙇‍♂️❤️

**Review by jrhee17 — APPROVED** [review]
Looks great! Thanks @trustin ! 🙇 👍 🚀

File: core/src/test/java/com/linecorp/armeria/server/AggregatedHttpResponseHandlerTest.java [hunk 1]
```diff
@@ -130,6 +163,26 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exc
...
+    @AfterAll
+    static void verifyResponseBufs() {
+        responseBufs.forEach(buf -> {
+            assertThat(buf.refCnt()).isZero();
+        });
+    }
+
+    @Test
+    void shouldReturnEmptyBodyOnHead() throws Exception {
+        final BlockingWebClient client = WebClient.of(server.httpUri()).blocking();
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/server/AggregatedHttpResponseHandlerTest.java:180]: nit:
```suggestion
        final BlockingWebClient client = server.blockingWebClient();
```

**Review by minwoox — APPROVED** [review]
Just one nit. Thanks and nice video! 😄

**Comment by minwoox** [comment]
Thanks, @trustin! 😄
