### PR TITLE
Apply gRPC exception handler function to cancellations as well

### LINKED ISSUE #5329: Convert `RequestTimeoutException` to gRPC `Status` using `GrpcExceptionHandlerFunction`
The logic converting `RequestTimeoutException` to gRPC `Status` is hard-coded so users can't override the message or customize the `Status`.

https://github.com/line/armeria/blob/d30db0c88d178468c3bb03a4e1d920b4c7a897b9/grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java#L323-L325

Before applying the default logic, we may first apply a user-defined `GrpcExceptionHandlerFunction`.

### PR DESCRIPTION
**Pull request by Dogacel**
Motivation:

https://github.com/line/armeria/issues/5329

Control over the returned status when a cancellation happens using a custom function.

Modifications:

- Use the method's gRPC exception handler function during cancellation. Fallback to old logic if it doesn't exist.

Result:

- Closes #5329

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java [hunk 1]
```diff
@@ -319,10 +329,11 @@ private <I, O> void startCall(ServerMethodDefinition<I, O> methodDef, ServiceReq
         call.setListener(listener);
         call.startDeframing();
         ctx.whenRequestCancelling().handle((cancellationCause, unused) -> {
-            Status status = Status.CANCELLED.withCause(cancellationCause);
-            if (cancellationCause instanceof RequestTimeoutException) {
-                status = status.withDescription("Request timed out");
-            }
+            final Status status = call.exceptionHandler()
+                .orElse(cancellationGrpcExceptionHandler)
+                .apply(ctx, cancellationCause, headers);
```
Comment (Dogacel) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java:334]: Now sure if we should pass the request headers or just empty headers. If this represents response headers, then I suppose it should be empty?

**Comment by Dogacel** [comment]
Let me handle the tests tomorrow.

**Review by minwoox — APPROVED** [review]
Resolved the conflict caused by https://github.com/line/armeria/pull/5571. 😉

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java [hunk 2]
```diff
@@ -936,10 +936,11 @@ public void onCompleted() {
 
         final RpcResponse rpcResponse = (RpcResponse) log.responseContent();
         final StatusRuntimeException cause = (StatusRuntimeException) rpcResponse.cause();
-        assertThat(cause.getStatus().getCode()).isEqualTo(Code.CANCELLED);
         if (protocol.isMultiplex()) {
+            assertThat(cause.getStatus().getCode()).isEqualTo(Code.CANCELLED);
             assertThat(cause.getStatus().getCause()).isInstanceOf(ClosedStreamException.class);
         } else {
+            assertThat(cause.getStatus().getCode()).isEqualTo(Code.UNKNOWN);
```
Comment (minwoox) [inline grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java:943]: I think this is the limitation of gRPC with HTTP/1.1.
We shouldn't treat a closed connection as a cancellation from the client.
Please let me know if you have a different thought.

Comment (jrhee17) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java:943]: I think this can go either way.

I'm slightly in favor of the previous behavior since:
- Looking at the API names, I think it's reasonable to assume that calling `ClientRequestContext#cancel` will result in a `CANCELLED` status
- `CANCELLED` doesn't necessarily mean "cancellation from the client.". For instance, a timeout due to `RequestTimeoutException` is also considered `CANCELLED`. Network failure in the upstream implementation is also considered `CANCELLED`.

Having said this, I'm not too strong on this.

**Review by jrhee17 — APPROVED** [review]
Left a minor comment but looks good overall 👍 👍 👍

File: grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java (hunk 2 above)
Comment (minwoox) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java:943]: >  Network failure in the upstream implementation is also considered CANCELLED.

Could you give me the link to it? If that's true, I think we can change to return canceled when a ClosedSesessionException is raised here:
https://github.com/line/armeria/blob/1e1439664309f457458517c42dd38e201e98cad7/grpc/src/main/java/com/linecorp/armeria/common/grpc/DefaultGrpcExceptionHandlerFunction.java#L53-L58

Comment (jrhee17) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java:943]: Actually, I can't say I'm too confident of my previous statement.

It is based on the seeing the following lines
https://github.com/grpc/grpc-java/blob/db96219be1ed6a996ed3a4cd8812446166118c06/stub/src/main/java/io/grpc/stub/ServerCalls.java#L287-L292
and the following issue:
https://github.com/grpc/grpc-java/issues/9682#issuecomment-1309254805

Having said this, I haven't actually tested this out.

Comment (minwoox) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java:943]: I see. Then let's wait for @ikhoon who implemented the logic.

Comment (ikhoon) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java:943]: Between `UNKNOWN` and `CANCELLED`, I slightly prefer `CANCELLED` to synchronize with the upstream behavior.

Comment (minwoox) [reply grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java:943]: Have checked that the upstream uses `CANCELLED` when a connection is closed.
Thus, use the same approach.

**Review by ikhoon — APPROVED** [review]
Thanks, @Dogacel and @minwoox! 🙇‍♂️

**Comment by minwoox** [comment]
@Dogacel 👍 👍 👍
