### PR TITLE
Propagate exceptions thrown from `RequestConverter` to `ExceptionHandler`

### LINKED ISSUE #4824: @Param annotation swallows @RequestConverter exceptions
I am attempting to combine @Param annotation and @RequestConverter into one data class. The reason is I need information from both the body and the path parameters and want the least code possible.

Request data class:
```
data class Request(
    @Param("something") val something: String,

    @RequestConverter(ExampleRequestConverter::class)
    val body: RequestBody
)

data class RequestBody(
   requiredField: String
)
```

Request converter:
```
class ExampleRequestConverter : RequestConverterFunction {
    override fun convertRequest(
        ctx: ServiceRequestContext,
        request: AggregatedHttpRequest,
        expectedResultType: Class<*>,
        expectedParameterizedResultType: ParameterizedType?
    ): Any {
        return try {
            Gson().fromJson(request.contentUtf8(), RequestBody::class.java)
                ?: throw customException
        } catch (e: Exception) {
            throw customException
        }
    }
}
```

The problem is, if the `fromJson` method fails (for example, if all required fields are not provided in the body), then we throw a custom exception. Unfortunately, Armeria will swallow that exception due to the Param annotation and throw an IllegalArgumentException with its own custom message.

I was wondering if there is a way to surface my custom exception instead of the Armeria exception? Thanks!

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

It seems like some users expect that an exception thrown from `RequestConverterFunction` is relayed to the `ExceptionHandler`.
I think for exceptions raised internally in armeria it is fine to wrap these exceptions, but for exceptions produced from user-land it makes sense to relay such exceptions transparently.

I propose that when a `RequestConverterFunction` throws an exception, the exception is always propagated as-is to the `ExceptionHandler`.

Note that this is already the default behavior for single-depth conversions. This PR handles the case where a resolve is done when resolving the internals of a bean.

Modifications:

- Don't catch and propagate the exception as-is when a bean is constructed and a nested `RequestConverterFunction` throws an exception.

Result:

- Closes #4824. (If this resolves the issue.)
- Describe the consequences that a user will face after this PR is merged.

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceExceptionHandlerTest.java [hunk 1]
```diff
@@ -277,6 +300,26 @@ public HttpResponse handler3(ServiceRequestContext ctx, HttpRequest req) {
         }
     }
 
+    @LoggingDecorator
+    @ExceptionHandler(CapturingExceptionHandler.class)
+    public static class MyService6 extends MyService1 {
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceExceptionHandlerTest.java:305]: Should we remove `MyService1` from super class because the `requestConverterExceptionIsRelayed` tests methods only in `MyService6`?

**Review by ikhoon — APPROVED** [review]
Thanks, @jrhee17!

**Review by minwoox — APPROVED** [review]
Thanks! 👍

**Review by trustin — APPROVED** [review]
:+1:
