### PR TITLE
Fix a bug where an `IllegalStateException` is raised on a non-ready `EndpointGroup`

### LINKED ISSUE #3332: `IllegalStateException` when making a gRPC call to a non-ready `EndpointGroup`.
If a user makes a gRPC call to an `EndpointGroup` that's not ready yet, the user will get the following exception:

```
io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3830513a
java.lang.IllegalStateException: Should call init(endpoint) before invoking this method.
	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:508)io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3830513a
java.lang.IllegalStateException: Should call init(endpoint) before invoking this method.
	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:508)
	at com.linecorp.armeria.client.DefaultClientRequestContext.eventLoop(DefaultClientRequestContext.java:437)
	at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.start(ArmeriaClientCall.java:225)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:332)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:306)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:218)
	at scalapb.grpc.ClientCalls$.asyncUnaryCall(ClientCalls.scala:25)
	at com.linecorp.armeria.client.DefaultClientRequestContext.eventLoop(DefaultClientRequestContext.java:437)
	at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.start(ArmeriaClientCall.java:225)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:332)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:306)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:218)
	at scalapb.grpc.ClientCalls$.asyncUnaryCall(ClientCalls.scala:25)
```

Instead, we should fail with an exception like `EmptyEndpointGroupException`.

Related Slack conversation: https://line-armeria.slack.com/archives/C1NGPBUH2/p1612507683054200

### PR DESCRIPTION
**Pull request by ikhoon**
…EndpointGroup`

Motivation:

If an `EndpointGroup` is not initialized with initial values,
a gRPC client will raise an `IllegalStateException` with the following message:
```java
io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3830513a
java.lang.IllegalStateException: Should call init(endpoint) before invoking this method.
```

A `WebClient` waits a connection timeout for the `EndpointGroup` to have at least one Endpoint by @trustin's work (#2837)
However, a gRPC client does not wait for the `EndPointGroup` and start a gRPC request immediately.

Modifications:

- Add `DefaultClientRequestContext.whenIntialized()` which completes
  when a `ctx` is initialized with an `EndpointGroup`.
- Defer a gRPC call until a `whenIntialized()` is completed.

Result:

- You no longer see an `IllegalStateException` if a gRPC call is sent to a non-ready `EndpointGroup`
- Fixes #3332

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java [hunk 1]
```diff
@@ -478,4 +502,48 @@ private void notifyExecutor() {
...
+            addPendingTask(task);
+        }
+    }
+
+    private void runPendingTask() {
+        for (;;) {
+            final Runnable pendingTask = this.pendingTask;
+            if (pendingTaskUpdater.compareAndSet(this, pendingTask, NO_OP)) {
+                if (pendingTask != null) {
+                    ctx.eventLoop().execute(pendingTask);
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java:523]: how about executing right away if `ctx.eventLoop().inEventLoop()` is `true`?

File: grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java [hunk 2]
```diff
@@ -478,4 +502,48 @@ private void notifyExecutor() {
...
+        }
+    }
+
+    private void addPendingTask(Runnable pendingTask) {
+        if (!pendingTaskUpdater.compareAndSet(this, null, pendingTask)) {
+            for (;;) {
+                final Runnable oldPendingTask = this.pendingTask;
+                assert oldPendingTask != null;
+                if (oldPendingTask == NO_OP) {
+                    ctx.eventLoop().execute(pendingTask);
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java:536]: ditto

File: grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java (hunk 1 above)
Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java:523]: If so, the order of execution could be reversed.

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java [hunk 3]
```diff
@@ -81,6 +81,11 @@
     private static final AtomicReferenceFieldUpdater<DefaultClientRequestContext, HttpHeaders>
             additionalRequestHeadersUpdater = AtomicReferenceFieldUpdater.newUpdater(
             DefaultClientRequestContext.class, HttpHeaders.class, "additionalRequestHeaders");
+
+    private static final AtomicReferenceFieldUpdater<DefaultClientRequestContext, CompletableFuture>
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:86]: Fixed. :-)

**Review by minwoox — APPROVED** [review]
Thanks!

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java [hunk 4]
```diff
@@ -266,14 +273,58 @@ private static ServiceRequestContext serviceRequestContext() {
...
+            } else {
+                future = CompletableFuture.supplyAsync(() -> success, acquiredEventLoop);
+            }
+            if (whenInitializedUpdater.compareAndSet(this, null, future)) {
+                return future;
+            }
+            whenInitialized = this.whenInitialized;
+        }
+
+        final CompletableFuture<Boolean> finalWhenInitialized = whenInitialized;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:299]: Maybe early-return when `whenInitialized.isDone()` is true?

File: grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java [hunk 5]
```diff
@@ -478,4 +502,56 @@ private void notifyExecutor() {
             executor.execute(NO_OP);
         }
     }
+
+    private boolean needsDirectInvocation() {
+        return (endpointInitialized || ctx.whenInitialized().isDone()) && ctx.eventLoop().inEventLoop();
+    }
+
+    private void execute(Runnable task) {
+        if (endpointInitialized || ctx.whenInitialized().isDone()) {
```
Comment (trustin) [inline grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java:511]: We could use `assert` for this condition if we always guard this method with `needsDirectInvocation()`.

Comment (ikhoon) [reply grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java:511]: `endpointInitialized` could be either `true`, `false` here. 
Because `endpointInitialized || ctx.whenInitialized().isDone()` and `ctx.eventLoop().inEventLoop()` are connected by `&&` condition.

Comment (trustin) [reply grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java:511]: Ah, indeed. Sorry for a bad comment :sweat_smile:

**Comment by trustin** [comment]
Thanks, @ikhoon!
