### PR TITLE
Show more stack trace of CompositeException

### LINKED ISSUE #4347: Show more stack trace of CompositeException
This is an example stack trace of a `CompositeException`:
```
com.linecorp.armeria.common.util.CompositeException: 2 exceptions occurred. 
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:273)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$notifySubscriberOfCloseEvent$3(DefaultStreamMessage.java:294)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: com.linecorp.armeria.common.util.CompositeException$ExceptionOverview: Multiple exceptions (2)
|-- java.util.NoSuchElementException: null
    at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
|-- com.linecorp.armeria.common.stream.AbortedStreamException: null
    at com.linecorp.armeria.common.stream.AbortedStreamException.get(AbortedStreamException.java:39)
```

The exceptions in `ExceptionOverview` just show two lines of stack traces so it's really hard to get a context what's going on from it.
We might need to increase the lines (20 is sensible default?) and show full stack trace when `-Dcom.linecorp.armeria.verboseExceptions=true`.

### PR DESCRIPTION
**Pull request by devdynam0507**
### Motivation:
If one or more exceptions are raised just show 1 stack trace in Exception Overview.
This can be very inconvenient.
So we may need to increase the number of lines in the output stacktrace. (20 is sensible default?)   
and show full stack trace when   
`-Dcom.linecorp.armeria.verboseExceptions=true`

Modifications:
- if `-Dcom.linecorp.armeria.verboseExceptions=true`, I increased the number of output lines of the stacktrace.
- If the stacktrace line is lower than the `maxStacktraceSize`, a lower line is output.

Result:

- Closes #4347
```java
Caused by: com.linecorp.armeria.common.util.CompositeException: 2 exceptions occurred. 
	at app//com.linecorp.armeria.internal.common.stream.RecoverableStreamMessage$RecoverableSubscriber.onError(RecoverableStreamMessage.java:226)
	at app//com.linecorp.armeria.internal.common.stream.AbortedStreamMessage.subscribe0(AbortedStreamMessage.java:91)
	at app//com.linecorp.armeria.internal.common.stream.AbortedStreamMessage.lambda$subscribe$1(AbortedStreamMessage.java:85)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
Caused by: com.linecorp.armeria.common.util.CompositeException$ExceptionOverview: Multiple exceptions (2)
|-- java.lang.NullPointerException: null
    at com.linecorp.armeria.common.util.CompositeExceptionTest.lambda$verboseExceptionOptionDisabledTest$1(CompositeExceptionTest.java:73)
    at com.linecorp.armeria.internal.common.stream.RecoverableStreamMessage$RecoverableSubscriber.onError(RecoverableStreamMessage.java:221)
    at com.linecorp.armeria.internal.common.stream.AbortedStreamMessage.subscribe0(AbortedStreamMessage.java:91)
    at com.linecorp.armeria.internal.common.stream.AbortedStreamMessage.lambda$subscribe$1(AbortedStreamMessage.java:85)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
|-- java.lang.IllegalArgumentException: null
    at com.linecorp.armeria.common.util.CompositeExceptionTest.verboseExceptionOptionDisabledTest(CompositeExceptionTest.java:72)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
    at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
    at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
    at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
    at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
```

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 1]
```diff
@@ -155,12 +163,18 @@ public synchronized Throwable getCause() { // NOPMD
...
-                        for (int i = 0; i < depth + 2; i++) {
-                            aggregateMessage.append("  ");
-                        }
                         final StackTraceElement[] st = inner.getStackTrace();
                         if (st.length > 0) {
-                            aggregateMessage.append("at ").append(st[0]).append(separator);
+                            final boolean isEnableVerboseExceptionFlag =
+                                    verboseExceptionFlag.isSampled(inner.getClass());
+                            final int loopCount = isEnableVerboseExceptionFlag ?
+                                  Math.min(st.length, maxStacktraceSize) : disabledVerboseExceptionLoopCount;
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:171]: I don't see that this correctly applies the contract in #4347
- If `verboseExceptionFlag.isSampled(inner.getClass())` is `true`, 
  full stack traces should be appended.
- If `verboseExceptionFlag.isSampled(inner.getClass())` is `false`, 
  at most 20 stack frames could be appended.

**Review by ikhoon — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java (hunk 1 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:171]: Should we add a test for the change?

Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:171]: > I don't see that this correctly applies the contract in #4347
> 
> * If `verboseExceptionFlag.isSampled(inner.getClass())` is `true`,
>   full stack traces should be appended.
> * If `verboseExceptionFlag.isSampled(inner.getClass())` is `false`,
>   at most 20 stack frames could be appended.

Sorry I misunderstood.  this will be fixed soon

Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:171]: > Should we add a test for the change?

I think testing is necessary.  Here's the scenario I was thinking of:  Set the value of `verboseExceptions` using `System.setProperty` in unit tests.  As a result, the `ExceptionOverview` created by calling `getCause()` of the `CompositeException` class is obtained, the stack trace String is cut with `line.separator`, and the output stack trace length is compared.  What do you think about it?

Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:171]: Since the stack trace is output differently for each `Flag`(**verboseExceptions**), I think a test to compare the number of output lines is necessary.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:171]: > . As a result, the ExceptionOverview created by calling getCause() of the CompositeException class is obtained, the stack trace String is cut with line.separator, and the output stack trace length is compared. What do you think about it?

Sounds good.

For the convenience of tests, we can add a package-private constructor like:
```java
    public CompositeException(Iterable<? extends Throwable> errors) {
        this(errors, Flags.verboseExceptionSampler());
    }

    @VisibleForTesting
    CompositeException(Iterable<? extends Throwable> errors, Sampler<Class<? extends Throwable>> verboseExceptionSampler) {
        ...
    }
```

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 2]
```diff
@@ -89,8 +96,16 @@ public CompositeException(Throwable... exceptions) {
...
      */
     public CompositeException(Iterable<? extends Throwable> errors) {
+        this(errors, Flags.verboseExceptionSampler());
+    }
+
+    @VisibleForTesting
+    CompositeException(Iterable<? extends Throwable> errors,
+                       Sampler<Class<? extends Throwable>> verboseExceptionFlag) {
         requireNonNull(errors, "errors");
+        requireNonNull(verboseExceptionFlag, "verboseExceptionFlag");
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:106]:
```suggestion
                       Sampler<Class<? extends Throwable>> verboseExceptionSampler) {
        requireNonNull(errors, "errors");
        requireNonNull(verboseExceptionFlag, "verboseExceptionSampler");
```

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+    Sampler<Class<? extends Throwable>> sampler = Flags.verboseExceptionSampler();
+
+    @Test
+    void verboseExceptionEnabledTest() {
+        final IllegalStateException ex1 = new IllegalStateException();
+        final IllegalArgumentException ex2 = new IllegalArgumentException();
+        final CompositeException compositeException = new CompositeException(
+                Arrays.asList(ex1, ex2), sampler);
+
+        when(sampler.isSampled(any())).thenReturn(true);
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:43]: Should we just use `Sampler.always()` rather than using a mock?

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 4]
```diff
@@ -155,12 +171,19 @@ public synchronized Throwable getCause() { // NOPMD
...
-                            aggregateMessage.append("at ").append(st[0]).append(separator);
+                            final boolean isEnableVerboseExceptionFlag =
+                                    verboseExceptionFlag.isSampled(inner.getClass());
+                            final int loopCount = isEnableVerboseExceptionFlag ?
+                                                  st.length : Math.min(
+                                                          disabledVerboseExceptionLoopCount, st.length);
+                            for (int i = 0; i < loopCount; i++) {
+                                for (int j = 0; j < depth + 2; j++) {
+                                    aggregateMessage.append("  ");
+                                }
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:184]: Should we pre-calculate the message padding and reuse it?
It would be inefficient to loop and append the same message.
```java
final String messagePadding = Strings.repeat("  ", depth + 2);
...

aggregateMessage.append(messagePadding).append("at ").append(st[i]).append(separator);
```

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 5]
```diff
@@ -155,12 +171,19 @@ public synchronized Throwable getCause() { // NOPMD
...
-                            aggregateMessage.append("  ");
-                        }
                         final StackTraceElement[] st = inner.getStackTrace();
                         if (st.length > 0) {
-                            aggregateMessage.append("at ").append(st[0]).append(separator);
+                            final boolean isEnableVerboseExceptionFlag =
+                                    verboseExceptionFlag.isSampled(inner.getClass());
+                            final int loopCount = isEnableVerboseExceptionFlag ?
+                                                  st.length : Math.min(
+                                                          disabledVerboseExceptionLoopCount, st.length);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:180]: Would it be better to give more meaningful names to the variables?
- `isEnableVerboseExceptionFlag`: Grammatically incorrect.
- `loopCount`: Looks general and does not tell the current context
- `disabledVerboseExceptionLoopCount`: Difficult to understand the context
```suggestion
                            final int maxStackTraceSize = isVerboseException ?
                                                  st.length : Math.min(
                                                          DEFAULT_MAX_NUM_STACK_TRACES, st.length);
```

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 6]
```diff
@@ -57,15 +59,20 @@
  *
  * <p>If you invoke {@link #getCause()}, it will lazily create the causal chain but will stop if it finds any
  * Throwable in the chain that it has already seen.
+ *
+ * <p>If the inner exception is sampled by {@link Flags#verboseExceptionSampler()},
+ * full stack traces are captured. Otherwise, only 20 stack frames are preserved by default.
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:64]:
```suggestion
 * full stack traces are captured. Otherwise, only {@value DEFAULT_MAX_NUM_STACK_TRACES} stack frames are preserved by default.
```

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 7]
```diff
@@ -0,0 +1,108 @@
...
+
+    @Mock
+    Sampler<Class<? extends Throwable>> sampler = Flags.verboseExceptionSampler();
+
+    @Test
+    void verboseExceptionEnabledTest() {
+        final IllegalStateException ex1 = new IllegalStateException();
+        final IllegalArgumentException ex2 = new IllegalArgumentException();
+        final CompositeException compositeException = new CompositeException(
+                Arrays.asList(ex1, ex2), sampler);
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:41]: We prefer `ImmutableList`.
```suggestion
                ImmutableList.of(ex1, ex2), sampler);
```

**Review by ikhoon — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java (hunk 4 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:184]: I agree with that opinion. Iteration logic (calculate message padding **depth+2**) is being executed throughout the getCause() method.
Since there is no section in which the depth variable increases in the middle of the logic, i will finish the message padding calculation in advance.

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java (hunk 5 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:180]: thanks for review :) i will fix it

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java (hunk 7 above)
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:41]: thanks for review :)

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java (hunk 3 above)
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:43]: thanks for review, 

I was worried about that.
It seems a little better to use a Sampler without using Mocking.

If so, use Sampler.never() if verboseExceptions is false.

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+        final CompositeException.ExceptionOverview exceptionOverview =
+                (CompositeException.ExceptionOverview) compositeException.getCause();
+        final int separatedStacktraceLength =
+                (int) Arrays.stream(exceptionOverview.getMessage().split(separator))
+                        .filter(line -> !line.contains("Multiple exceptions") && !line.contains("|-- "))
+                        .count();
+
+        // Expected: if verboseException option disabled, max output stacktrace is 20
+        // this case is occurred 2 exceptions (20 * 2)
+        assertThat(separatedStacktraceLength).isEqualTo(40);
```
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:70]: Note to reviewers. I believe the thread that executes this test method has more than 20 lines of the stack trace in most cases.

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+                new StackTraceElement(className, methodName, fileName, 3),
+        };
+        ex2.setStackTrace(customStackTrace);
+        final CompositeException compositeException =
+                new CompositeException(ImmutableList.of(ex1, ex2), neverVerboseExceptionSampler);
+
+        final CompositeException.ExceptionOverview exceptionOverview =
+                (CompositeException.ExceptionOverview) compositeException.getCause();
+        final int separatedStacktraceLength =
+                (int) Arrays.stream(exceptionOverview.getMessage().split(separator))
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:92]: ditto

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+    private static final String separator = System.getProperty("line.separator");
+    private static final Sampler<Class<? extends Throwable>> alwaysVerboseExceptionSampler =
+            Sampler.always();
+    private static final Sampler<Class<? extends Throwable>> neverVerboseExceptionSampler =
+            Sampler.never();
+
+    @Test
+    void verboseExceptionEnabledTest() {
+        final IllegalStateException ex1 = new IllegalStateException();
+        final IllegalArgumentException ex2 = new IllegalArgumentException();
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:37]: How about also adding a test case that creates the composite exception with the exceptions that have cause?
```java
final IllegalArgumentException ex2 = new IllegalArgumentException();
final AnticipatedException ex3 = new AnticipatedException(ex2);
```
I think we need to also check if the padding is correctly appended because we have changed the code. 😉

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 11]
```diff
@@ -0,0 +1,100 @@
...
+import org.junit.jupiter.api.Test;
+
+import com.google.common.collect.ImmutableList;
+
+class CompositeExceptionTest {
+
+    private static final String separator = System.getProperty("line.separator");
+    private static final Sampler<Class<? extends Throwable>> alwaysVerboseExceptionSampler =
+            Sampler.always();
+    private static final Sampler<Class<? extends Throwable>> neverVerboseExceptionSampler =
```
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:31]: thank you for review :)

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 12]
```diff
@@ -0,0 +1,100 @@
...
+    void verboseExceptionEnabledTest() {
+        final IllegalStateException ex1 = new IllegalStateException();
+        final IllegalArgumentException ex2 = new IllegalArgumentException();
+        final CompositeException compositeException =
+                new CompositeException(ImmutableList.of(ex1, ex2), alwaysVerboseExceptionSampler);
+
+        final CompositeException.ExceptionOverview exceptionOverview =
+                (CompositeException.ExceptionOverview) compositeException.getCause();
+        final int separatedStacktraceLength =
+                (int) Arrays.stream(exceptionOverview.getMessage().split(separator))
```
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:44]: thank you for review :)

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:70]: thank you for review :)
I will change the access modifier of the `DEFAULT_MAX_NUM_STACK_TRACES` variable from private to public.

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java (hunk 10 above)
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:37]: It seems necessary. I will add it. 😀

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java]: We shouldn't expose the field to the public. 😄 
Let's make it as package-private.
`static final int DEFAULT_MAX_NUM_STACK_TRACES = 20;`

[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java]: Oh i see :)

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 13]
```diff
@@ -0,0 +1,257 @@
...
+    @Test
+    void verboseExceptionDisabledTest() {
+        final IllegalStateException ex1 = new IllegalStateException();
+        final IllegalArgumentException ex2 = new IllegalArgumentException();
+        final CompositeException compositeException =
+                new CompositeException(ImmutableList.of(ex1, ex2), Sampler.never());
+        final int separatedStacktraceLength =
+                (int) Arrays.stream(compositeException.getCause().getMessage().split(separator))
+                        .filter(line -> !line.contains("Multiple exceptions") && !line.contains("|-- "))
+                        .count();
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:59]: I have seen duplicate code of this logic. How about extracting it so that we can use it in multiple places?
```java
private static long stackTraceLength(CompositeException compositeException) {
    return Arrays.stream(compositeException.getCause().getMessage().split(separator))
                 .filter(line -> !line.contains("Multiple exceptions") && !line.contains("|-- "))
                 .count();
}
```
Please, also, note that we don't need to downcast to integer and the `T` in `stackTrace` is capitalized.

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 14]
```diff
@@ -0,0 +1,257 @@
...
+                new StackTraceElement(className, methodName, fileName, 2),
+                new StackTraceElement(className, methodName, fileName, 3),
+        };
+        ex1.setStackTrace(customStackTrace);
+        ex2.setStackTrace(customStackTrace);
+        ex3.setStackTrace(customStackTrace);
+        final CompositeException compositeException =
+                new CompositeException(ImmutableList.of(ex1, ex3), Sampler.never());
+        final int paddingCount = Arrays.stream(compositeException.getCause().getMessage().split(separator))
+             .filter(line -> !line.contains("Multiple exceptions") && !line.contains("|-- "))
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:241]: The result of the padding is now:
```
|-- com.linecorp.armeria.internal.testing.AnticipatedException: java.lang.IllegalArgumentException
    at CompositeExceptionTest.verboseExceptionDisabledTestIfStackTraceLengthLessThan20(CompositeExceptionTest.java:1)
    ...
  |-- java.lang.IllegalArgumentException: null
```
Shoudn't it be this?
```
|-- com.linecorp.armeria.internal.testing.AnticipatedException: java.lang.IllegalArgumentException
    at CompositeExceptionTest.verboseExceptionDisabledTestIfStackTraceLengthLessThan20(CompositeExceptionTest.java:1)
    ...
    |-- java.lang.IllegalArgumentException: null
        at ...
```

Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java]: yes!
```java
if (!seenCauses.containsKey(inner)) {
    seenCauses.put(inner, true);

    inner = inner.getCause();
    depth += 2;
} else {
```
If so, it should be like this.
that's correct?

Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java]: 스크린샷 2022-08-01 오후 1 19 30

Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java]: But wouldn't that change the variable(variable name?) significantly from its original intention?

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 15]
```diff
@@ -57,15 +60,21 @@
...
+ * <p>If the inner exception is sampled by {@link Flags#verboseExceptionSampler()},
+ * full stack traces are captured. Otherwise, only {@value DEFAULT_MAX_NUM_STACK_TRACES}
+ * stack frames are preserved by default.
  */
 public final class CompositeException extends RuntimeException {
 
     // Forked from RxJava 3.0.0 at e793bc1d1a29dca18be795cf4a7628e2d44a4234
 
     private static final long serialVersionUID = 3026362227162912146L;
+    static final int DEFAULT_MAX_NUM_STACK_TRACES = 20;
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:73]:
```suggestion 
    @VisibleForTesting
    static final int DEFAULT_MAX_NUM_STACK_TRACES = 20;
```

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 16]
```diff
@@ -142,25 +160,27 @@ public synchronized Throwable getCause() { // NOPMD
...
                         final StackTraceElement[] st = inner.getStackTrace();
                         if (st.length > 0) {
-                            aggregateMessage.append("at ").append(st[0]).append(separator);
+                            final boolean isVerboseException =
+                                    verboseExceptionSampler.isSampled(inner.getClass());
+                            final int maxStackTraceSize = isVerboseException ? st.length : Math.min(
+                                                          DEFAULT_MAX_NUM_STACK_TRACES, st.length);
+                            for (int i = 0; i < maxStackTraceSize; i++) {
+                                aggregateMessage.append(messagePadding).append("at ").append(st[i]).append(
+                                        separator);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:182]: nit: For readability.
```suggestion
                                aggregateMessage.append(messagePadding).append("at ")
                                                .append(st[i]).append(separator);
```

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java (hunk 14 above)
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java]: Oops, sorry for making you get confused. 😓 
I have checked the current implementation and it just adds two spaces as the depth is increased and I think it's fine as is. 😄

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 17]
```diff
@@ -0,0 +1,235 @@
...
+        // custom stack trace length )
+        final int expectPaddingCount = 4 * 3 * 2 + (6 * 3);
+        assertThat(paddingCount).isEqualTo(expectPaddingCount);
+    }
+
+    private static long stackTraceLength(final CompositeException exception) {
+        return Arrays.stream(exception.getCause().getMessage().split(separator))
+                        .filter(line -> !line.contains("Multiple exceptions") && !line.contains("|-- "))
+                        .count();
+    }
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:219]: Please check the indentation. 😉 
https://armeria.dev/community/developer-guide#setting-up-your-ide
```suggestion
        return Arrays.stream(exception.getCause().getMessage().split(separator))
                     .filter(line -> !line.contains("Multiple exceptions") && !line.contains("|-- "))
                     .count();
    }
```

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 18]
```diff
@@ -0,0 +1,235 @@
...
+
+    private static int paddingCount(final CompositeException exception) {
+        return Arrays.stream(exception.getCause().getMessage().split(separator))
+                .filter(line -> !line.contains("Multiple exceptions") && !line.contains("|-- "))
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:223]: ditto. 😉

**Review by minwoox — COMMENTED** [review]
Thanks! LGTM once all comments are addressed. 😉

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 19]
```diff
@@ -0,0 +1,235 @@
...
+                     .mapToInt(line -> {
+                         int padding = 0;
+                         final int paddingLength = PADDING.length();
+                         while (line.startsWith(PADDING)) {
+                             line = line.substring(paddingLength);
+                             padding += paddingLength;
+                         }
+                         return padding;
+                     })
+                     .sum();
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:233]: We can probably do:
```suggestion
                     .mapToInt(line -> {
                         for (int i = 0; i < line.length(); i++) {
                             if (line.charAt(i) != ' ') {
                                 return i;
                             }
                         }
                         return 0;
                     })
                     .sum();
```

**Review by minwoox — APPROVED** [review]
Just left minor comments.
Thanks a lot. 😄

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java [hunk 20]
```diff
@@ -0,0 +1,233 @@
...
+        final IllegalArgumentException ex2 = new IllegalArgumentException();
+        final CompositeException compositeException =
+                new CompositeException(ImmutableList.of(ex1, ex2), Sampler.never());
+        final long separatedStacktraceLength = stackTraceLength(compositeException);
+
+        // if verboseException option disabled, max output stacktrace is
+        // CompositeException.DEFAULT_MAX_NUM_STACK_TRACES.
+        // this case is occurred 2 exceptions (20 * 2)
+        assertThat(separatedStacktraceLength).isEqualTo(
+                CompositeException.DEFAULT_MAX_NUM_STACK_TRACES * 2);
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:58]: This test could be broken if the original stack trace is less than `DEFAULT_MAX_NUM_STACK_TRACES`.
How about manually setting stackframes longer than 20 like we added in `verboseExceptionEnabledTestMultipleContainsCustomStackTraces`?

**Review by ikhoon — APPROVED** [review]
Thanks, @devdynam0507! 🚀
Left a minor comment on the test.

**Comment by devdynam0507** [comment]
> Thanks, @devdynam0507! 🚀
> 
> Left a minor comment on the test. 

Thank you for review 😊

File: core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java (hunk 20 above)
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java:58]: Sounds good :)

It would also be good to manually change the `verboseExceptionDisabledTestMultipleContainsCustomStackTraces` method similar to the code above.

**Review by jrhee17 — COMMENTED** [review]
Left a minor comment. Other parts looks good to me 🙇 👍 🙇

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java [hunk 21]
```diff
@@ -130,37 +149,41 @@ public synchronized Throwable getCause() { // NOPMD
...
                         }
 
-                        for (int i = 0; i < depth + 2; i++) {
-                            aggregateMessage.append("  ");
-                        }
                         final StackTraceElement[] st = inner.getStackTrace();
                         if (st.length > 0) {
-                            aggregateMessage.append("at ").append(st[0]).append(separator);
+                            final boolean isVerboseException =
+                                    verboseExceptionSampler.isSampled(innerClass);
```
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java:179]: Agreed. Different verbose in an exception is weird. It makes sense to sample `CompositeException` and apply the result to all inner exceptions.

[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java]: Fixed at [`166df2e` (#4356)](https://github.com/line/armeria/pull/4356/commits/166df2e72e9cab7cd683fd845f05ea52023e7094)

**Comment by minwoox** [comment]
Still LGTM

File: core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java (hunk 21 above)
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java]: Oops.. thanks a lot and sorry @ikhoon 😅

**Review by jrhee17 — APPROVED** [review]
Thanks @devdynam0507  and @ikhoon ! 🙇 👍 🙇
