### PR TITLE
Make @Description annotation at super class/interface work

### LINKED ISSUE #5195: The @Description annotation in super class/interface does not work
### Discussed in https://github.com/line/armeria/discussions/5192

<div type='discussions-op-text'>

<sup>Originally posted by **evgeny-mordyasov** September 20, 2023</sup>
The `@Description` annotation does not work when it is specified in the service interface. When I specify the annotation in the class, then everything is ok. I want to document my services in the interface so as not to clutter the code in the implementation with unnecessary annotations.

My interface:

```
public interface RestClientService {

    HttpResponse findByEntityId(@Description("client id") Long entityId);
}

```

My class:

```
public class RestClientServiceImpl implements RestClientService {

    private final ClientService service;

    public RestClientServiceImpl(ClientService service) {
        this.service = service;
    }

    @Get("/{entityId}")
    @Override
    public HttpResponse findByEntityId(@Param Long entityId) {
       ...
    }
}
```

My Config:

```
@Configuration
public class ArmeriaConfig {

    @Bean
    public ArmeriaServerConfigurator armeriaConfigurator(RestClientService restClientService) {
        return serverBuilder ->
                serverBuilder
                        .serviceUnder("/docs", docService());
    }

    private DocService docService() {
        return DocService.builder().build();
    }
}
```

Dependency maven:

```
<dependency>
    <groupId>com.linecorp.armeria</groupId>
    <artifactId>armeria-spring-boot3-starter</artifactId>
    <version>1.25.2</version>
</dependency>
```</div>

### PR DESCRIPTION
**Pull request by SeungWook-Han**
Motivation:
- The annotation `@Description` is used to give a description for `Class`, `Method`, and `Method parameter` at Doc-service.
- The annotation `@Description` could only exist at Super class or Interface in order to give a common desecription for multiple other class which extend or implmenet them. (First initiative: https://github.com/line/armeria/discussions/5192)
- However, the `@Description` at Super class or Interface is ignored at Doc-service. Let's make it effective.

Explain why you're making this change and what problem you're trying to solve.

Modifications:

- Make `resolveTargetElements#AnnotationUtil` returns all `AnnotatedElement` not only for specific one but also for all in Super class and Interface when the given specific one is `Parameter`or `Method` type.

Result:

- Closes #5195.
- `@Description` annotation which is only annotated on `Parameter` or `Method` at Super class or Interface will be effective at Doc-service.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java [hunk 1]
```diff
@@ -404,26 +443,74 @@ private static void disallowedListAnnotation(Class<? extends Annotation> annotat
...
+
         } else {
-            elements = ImmutableList.of(element);
+            return ImmutableList.of(element);
+        }
+    }
+
+    private static <T extends AnnotatedElement> List<AnnotatedElement> convertToAnnotatedElements(
+            List<T> elements) {
+        return elements.stream().map(element -> (AnnotatedElement)element).collect(Collectors.toList());
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java:477]: We prefer using immutable list.
```suggestion
        return elements.stream().map(element -> (AnnotatedElement) element).collect(toImmutableList());
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java [hunk 2]
```diff
@@ -404,26 +443,74 @@ private static void disallowedListAnnotation(Class<? extends Annotation> annotat
...
+        }
+
+        final boolean collectSuperClassFirst = findOptions.contains(FindOption.COLLECT_SUPER_CLASSES_FIRST);
+
+        if (element instanceof Class) {
+            final List<Class<?>> classes = collectClasses((Class<?>) element, collectSuperClassFirst);
+            return convertToAnnotatedElements(classes);
+
+        } else if (element instanceof Method && findOptions.contains(FindOption.LOOKUP_SUPER_METHODS)) {
+            final Method method = (Method) element;
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java:457]: nit: let's use early return in this method:
```suggestion
            return convertToAnnotatedElements(classes);
        }
        if (element instanceof Method && findOptions.contains(FindOption.LOOKUP_SUPER_METHODS)) {
            final Method method = (Method) element;
```

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java [hunk 3]
```diff
@@ -74,7 +78,19 @@ enum FindOption {
...
+         * is a {@link Method}. Otherwise, this option will be ignored.
+         * This option will work only with the {@link #LOOKUP_SUPER_CLASSES}.
+         */
+        LOOKUP_SUPER_METHODS,
+        /**
+         * Get annotations from methods in super classes of the given {@link AnnotatedElement} if the element
+         * is a {@link Parameter}. Otherwise, this option will be ignored.
+         * This option will work only with the {@link #LOOKUP_SUPER_CLASSES}.
+         */
+        LOOKUP_SUPER_PARAMETERS
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java:93]: Let's reorder:
```
LOOKUP_SUPER_CLASSES,
LOOKUP_SUPER_METHODS,
LOOKUP_SUPER_PARAMETERS,
LOOKUP_META_ANNOTATIONS,
COLLECT_SUPER_CLASSES_FIRST
```

File: core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java [hunk 4]
```diff
@@ -199,27 +201,111 @@ void testMultiPathFailingService() {
...
+        assertThat(descriptionInfo.docString())
+                .isEqualTo("This is a super description from the annotation");
+    }
+
+    @Description(ANNOTATED_DESCRIPTION_SUPER)
+    private interface DescriptionAnnotatedTestInterface {
+        void testMethod3(String param);
+
+        @Description(ANNOTATED_DESCRIPTION_SUPER)
+        void testMethod4(@Description(ANNOTATED_DESCRIPTION_SUPER) String param);
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java:281]: Could you add other parameters to make sure if it works with multiple parameters?

**Review by minwoox — COMMENTED** [review]
This looks great!
Left comments only about style issues. 😉

File: core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java (hunk 4 above)
Comment (SeungWook-Han) [reply core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java:281]: Thanks. Added one more parameter for each method case.

**Comment by SeungWook-Han** [comment]
@minwoox Please take a look this PR 🙏

**Review by minwoox — APPROVED** [review]
Looks great, @SeungWook-Han! Thanks a lot! 👍 👍 👍

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java [hunk 5]
```diff
@@ -64,6 +67,18 @@ enum FindOption {
          * {@link Class}. Otherwise, this option will be ignored.
          */
         LOOKUP_SUPER_CLASSES,
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java:69]: The search target is coupled with the given `AnnotatedElement`.
It seems clear what the supreme element of the element indicates.

My understanding is that we can merge the three options into `LOOKUP_SUPER_ELELMENTS`.
The behavior will be determined depending on the type of `AnnotatedElement`.
What do you think of that?

Comment (SeungWook-Han) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java:69]: Oh, thanks. Actually I had considered merging the three options.
However I thought the goal of this PR is to find the Annotation in Method or Parameter in the super class only when it is `@Description` annotation. For other annotation, I thought we need to keep currnet logic, which is not to try to find the Annotation in the super class. Therefore, strictly speaking the search target is not coupled with the given `AnnotatedElement`.

Here is example,
- `AnnotatedElement` = Method && LOOKUP_SUPER_CLASSES && `@Path` => Return annotation only at specific class (without super class)

If we merge three options (=LOOKUP_SUPER_ELEMENTS)
- `AnnotatedElement` = Method && LOOKUP_SUPER_ELEMENTS && `@Path` => Return annotations at all super class

In order to find Annotation in the all super class only when the target annotation is `@Description` and the `AnnotatedElement` is Method or Parameter (or Class), I choose to add two `FindOption` explicitly.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java:69]: I didn't think of the corner case. Let's keep it as is.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java [hunk 6]
```diff
@@ -109,6 +124,29 @@ public static <T extends Annotation> T findFirst(AnnotatedElement element, Class
...
+     * Otherwise, {@code null} will be returned.
+     *
+     * @param element the {@link AnnotatedElement} to find the first annotation
+     */
+    @Nullable
+    public static Description findFirstDescription(AnnotatedElement element) {
+        final EnumSet<FindOption> options = EnumSet.of(FindOption.LOOKUP_SUPER_CLASSES,
+                                                       FindOption.LOOKUP_META_ANNOTATIONS,
+                                                       FindOption.LOOKUP_SUPER_METHODS,
+                                                       FindOption.LOOKUP_SUPER_PARAMETERS);
```
[the remark this answers is not in the document]
Comment (SeungWook-Han) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java]: Thanks! By the way, is it better to declare a static variable with `ImmutableSet` class to explicitly show the object is immutable?

[the remark this answers is not in the document]
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java]: That's a good question. I don't mind. It seems like we just use `Set` in the declaration part because the field name is all uppercased anyway, implying it's a constant.

[the remark this answers is not in the document]
Comment (SeungWook-Han) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java]: Thanks! Let me use `Set` with the uppercase in variable name in order for reader to figure out that is immutable just with variable name.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java [hunk 7]
```diff
@@ -42,11 +44,13 @@
 
 import com.google.common.collect.ImmutableList;
 import com.google.common.collect.ImmutableList.Builder;
```
[the remark this answers is not in the document]
Comment (SeungWook-Han) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java:46]: Oh. Sure :)

**Review by ikhoon — APPROVED** [review]
Thanks, @SeungWook-Han! 🚀🚀

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java [hunk 8]
```diff
@@ -403,27 +442,73 @@ private static void disallowedListAnnotation(Class<? extends Annotation> annotat
...
+            final List<Parameter> parameters = collectParameters(clazz, executable, parameter,
+                                                                 collectSuperClassFirst);
+            return convertToAnnotatedElements(parameters);
+        }
+        return ImmutableList.of(element);
+    }
+
+    private static <T extends AnnotatedElement> List<AnnotatedElement> convertToAnnotatedElements(
+            List<T> elements) {
+        return elements.stream().map(element -> (AnnotatedElement) element).collect(toImmutableList());
```
[the remark this answers is not in the document]
Comment (SeungWook-Han) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java]: Thanks! updated :)
