### PR TITLE
fix: grpc doc generation failing for options and extensions

### LINKED ISSUE #4123: Proto Documentation generation fails with duplicate keys
My proto definition:
```proto
service AuthorService {
  // AuthorService CRUD operations

  // Create a new author
  rpc AddAuthor(AddAuthorRequest) returns (AddAuthorResponse){
//    TODO update this block, this is for testing only, not prod ready yet for other micro services
    option (google.api.http) = {
      post: "/v1/author"
      body: "author"
    };
  }
```

Error I am getting: 
<details>

```java
2022-02-27 23:52:49.368 [globalEventExecutor-3-1] WARN  com.linecorp.armeria.server.Server traceId:  spanId:  - Failed to notify a server listener: com.linecorp.armeria.server.docs.DocService$1@5c4e50a6
java.lang.IllegalArgumentException: Multiple entries with same key: com.example.author.proto.v1.AuthorService/AddAuthor=    TODO update this block, this is for testing only, not prod ready yet for other micro services
 and com.example.author.proto.v1.AuthorService/AddAuthor= Create a new author

        at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableMap.conflictException(ImmutableMap.java:376)
        at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370)
        at com.linecorp.armeria.internal.shaded.guava.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153)
        at com.linecorp.armeria.internal.shaded.guava.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115)
        at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574)
        at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableMap$Builder.build(ImmutableMap.java:538)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:503)
        at com.linecorp.armeria.internal.server.grpc.GrpcDocStringExtractor.parseFile(GrpcDocStringExtractor.java:115)
        at com.linecorp.armeria.internal.server.grpc.GrpcDocStringExtractor.lambda$getDocStringsFromFiles$1(GrpcDocStringExtractor.java:99)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.linecorp.armeria.internal.server.grpc.GrpcDocStringExtractor.getDocStringsFromFiles(GrpcDocStringExtractor.java:100)
        at com.linecorp.armeria.server.docs.DocStringExtractor.getAllDocStrings0(DocStringExtractor.java:104)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.linecorp.armeria.server.docs.DocStringExtractor.getAllDocStrings(DocStringExtractor.java:68)
        at com.linecorp.armeria.internal.server.grpc.GrpcDocServicePlugin.lambda$loadDocStrings$19(GrpcDocServicePlugin.java:348)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Collections$2.tryAdvance(Collections.java:4719)
        at java.util.Collections$2.forEachRemaining(Collections.java:4727)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.linecorp.armeria.internal.server.grpc.GrpcDocServicePlugin.loadDocStrings(GrpcDocServicePlugin.java:350)
        at com.linecorp.armeria.server.docs.DocService.lambda$addDocStrings$2(DocService.java:209)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.linecorp.armeria.server.docs.DocService.addDocStrings(DocService.java:211)
        at com.linecorp.armeria.server.docs.DocService.access$200(DocService.java:88)
        at com.linecorp.armeria.server.docs.DocService$1.serverStarting(DocService.java:184)
        at com.linecorp.armeria.server.Server$ServerStartStopSupport.notifyStarting(Server.java:652)
        at com.linecorp.armeria.server.Server$ServerStartStopSupport.notifyStarting(Server.java:420)
        at com.linecorp.armeria.common.util.StartStopSupport.notifyListeners(StartStopSupport.java:371)
        at com.linecorp.armeria.common.util.StartStopSupport.lambda$start0$3(StartStopSupport.java:184)
        at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:240)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
</details>

It seems like the documentation service doesn't spin up because the `option` section is breaking it.

### PR DESCRIPTION
**Pull request by Dogacel**
Motivation:

gRPC doc generation fails when options and extensions were being used in proto files.

The test cases have been modified so the `test.proto` file contains an example option. Before changing `GrpcDocStringExtractor`, it wasn't able to produce documentation because of a duplicate key in the map. It was causing the whole Documentation Service to crash.

We might want to consider displaying `options` in documentation service in the future but this implementation un-blocks users who can't use the service because of the aforementioned bug.

The issue is described in #4123 in more detail.

Modifications:

- Ignore comments written on proto service options or extensions.

Result:

- Closes #4123
- The documentation service doesn't crash the whole Armeria service anymore when proto files have comments on service options or extensions.

### CODE REVIEW

**Comment by Dogacel** [comment]
@ikhoon @jrhee17 @minwoox @trustin Can you please take a look?

**Comment by minwoox** [comment]
Thanks a lot for the PR! Today is a holiday in Korea so let us take a look at this tomorrow. 😄

**Review by jrhee17 — APPROVED** [review]
Only one minor comment for me. Thanks @Dogacel ! 🙇 👍 💯

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java [hunk 1]
```diff
@@ -129,6 +129,11 @@ private static String getFullName(FileDescriptorProto descriptor, List<Integer>
...
                 return appendEnumToFullName(enumDescriptor, path, fullNameSoFar);
             case FileDescriptorProto.SERVICE_FIELD_NUMBER:
+                // If there is a fifth path, it means this is an `option`/`extension` and skip it.
+                if (path.size() > 4) {
+                    return null;
+                }
+
                 final ServiceDescriptorProto serviceDescriptor = descriptor.getService(path.get(1));
                 fullNameSoFar = appendNameComponent(fullNameSoFar, serviceDescriptor.getName());
                 if (path.size() > 2) {
```
[the remark this answers is not in the document]
Comment (Dogacel) [reply grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java:139]: @jrhee17 Can you give me an example? I didn't get that and I would like to modify our test cases so it includes that case as well.

[the remark this answers is not in the document]
Comment (Dogacel) [reply grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java]: @jrhee17 I have added a new test proto that will help to generalize this solution to work with every possible option/extension. I have taken that proto file from Google's example and put the license headers as we did for other protos. Let me know if anything looks odd, especially with the licenses.

**Comment by Dogacel** [comment]
> Thanks, @Dogacel!

I have updated this solution to work with a broader range of options. Can we re-run the workflow?

**Comment by Dogacel** [comment]
I have fixed the linting problem but I didn't get why `macos` build failed.

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java [hunk 2]
```diff
@@ -115,11 +115,44 @@ protected boolean acceptFile(String filename) {
...
+                return false;
+        }
+    }
+
     // A path is field number and indices within a list of types, going through a tree of protobuf
     // descriptors. For example, the 2nd field of the 3rd nested message in the 1st message in a file
     // would have path [MESSAGE_TYPE_FIELD_NUMBER, 0, NESTED_TYPE_FIELD_NUMBER, 2, FIELD_FIELD_NUMBER, 1]
     @Nullable
     private static String getFullName(FileDescriptorProto descriptor, List<Integer> path) {
+        if (!canDocumentPath(path)) {
```
Comment (jrhee17) [inline grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java:152]: Instead of filtering before entering the method, what do you think of checking while traversing each path?

e.g.
https://github.com/line/armeria/compare/master...jrhee17:suggestion/fix-grpc-docs-options?expand=1

File: grpc/src/test/proto/com/linecorp/armeria/grpc/testing/options.proto [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
+// The options and example message below are defined in
+// Google's protocol buffer documentation.
+// https://developers.google.com/protocol-buffers/docs/proto#extensions
```
Comment (jrhee17) [inline grpc/src/test/proto/com/linecorp/armeria/grpc/testing/options.proto:46]: Can you also leave a link on where this file was forked from?

**Review by jrhee17 — COMMENTED** [review]
Left some minor suggestions 🙇

File: grpc/src/test/proto/com/linecorp/armeria/grpc/testing/options.proto (hunk 3 above)
Comment (Dogacel) [reply grpc/src/test/proto/com/linecorp/armeria/grpc/testing/options.proto:46]: I didn't see a link that points exactly to this File but rather I copied its content from the link I have entered above.

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java (hunk 2 above)
Comment (Dogacel) [reply grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java:152]: My initial intention was short-circuiting but probably pulling logic into append methods is easier to read & maintain.

**Comment by Dogacel** [comment]
I don't think the documentation service will crash the app again after my changes but how about making it fail-safe just in case? Or do you think this is unnecessary?
 
GrpcDocStringExtractror:115
 ```java                      
  .collect(toImmutableMap(Entry::getKey, Entry::getValue));
  ``` 
  to 
  
 ```java                      
  .collect(toImmutableMap(Entry::getKey, Entry::getValue, (first, second) -> {
    logger.warn("Multiple keys found while parsing proto comments, skipping entry \"{}\".", second);
    return first;
  });
  ```

**Comment by jrhee17** [comment]
> how about making it fail-safe just in case?

sounds good to me 👍

**Comment by Dogacel** [comment]
> > how about making it fail-safe just in case?
> 
> sounds good to me 👍

I have made the change, I would be glad if you can re-run the workflow 🙇 

For some reason, `macOs` builds are failing. I think they were flaky and resolved in the latest master, so I updated my branch to track the latest master. I hope it won't fail again 🙏 

Let's merge this after it passes CI! I am excited.

**Review by jrhee17 — APPROVED** [review]
Changes look really nice 👍  Thank you @Dogacel 👍 🙇 🚀

**Comment by Dogacel** [comment]
@jrhee17 @minwoox I do not have write access to the repo, so I can't merge it. I would be glad if you can merge it 🙇 

Thank you all 🚀

**Comment by ikhoon** [comment]
>  I would be glad if you can merge it 🙇

When maintainers have reviewed and approved this PR, we will merge this PR. Thanks for your effort on this issue. 🙇‍♂️

File: grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java [hunk 4]
```diff
@@ -112,7 +112,13 @@ protected boolean acceptFile(String filename) {
...
                          })
                          .filter(Objects::nonNull)
-                         .collect(toImmutableMap(Entry::getKey, Entry::getValue));
+                         .collect(
+                             toImmutableMap(Entry::getKey, Entry::getValue, (first, second) -> {
+                                logger.warn("Multiple keys found while parsing proto comments," +
+                                        " skipping entry \"{}\".", second);
+                                return first;
+                            })
+                         );
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java:121]: nit: Indent
```suggestion
                         .collect(toImmutableMap(Entry::getKey, Entry::getValue, (first, second) -> {
                             logger.warn("Multiple keys found while parsing proto comments," +
                                         " skipping entry \"{}\".", second);
                             return first;
                         }));

**Review by ikhoon — APPROVED** [review]
Thank you @Dogacel!

**Review by trustin — APPROVED** [review]
Thanks for the fix, @Dogacel 🙇
