### PR TITLE
Fix flaky test `BraveServiceIntegrationTest.childCompletesBeforeServer`

### LINKED ISSUE #2833: Flaky test: `BraveServiceIntegrationTest.childCompletesBeforeServer`
https://ci.appveyor.com/project/line/armeria/builds/33726346/job/a0rrj3t4qfva6v6f#L1682
```
BraveServiceIntegrationTest > childCompletesBeforeServer FAILED
    java.lang.AssertionError: Expected {"traceId":"323fe8defcbd845a","parentId":"323fe8defcbd845a","id":"b216d181a49390e8","name":"child","timestamp":1593058969521364,"duration":11,"localEndpoint":{"serviceName":"BraveServiceIntegrationTest","ipv4":"127.0.0.1"}} to finish after 1593058969521333
        at brave.test.ITRemote.assertSpanInInterval(ITRemote.java:185)
        at brave.test.http.ITHttpServer.childCompletesBeforeServer(ITHttpServer.java:210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

The `Span.start()` and `Span.finish()` estimate the current time using
`baseEpochMicros + (System.nanoTime() - baseTickNanos)`.
However, Armeria achieves the current time using `System.currentTimeMillis() * 1000` in Java8.

The two different way of getting the current time could cause an error of a millisecond.
Sometimes the tolerance makes the server appear to finish earlier than child in test case.
This is not a problem in the Brave{Service,Client} because they only use Armeria timestamp.

Modifications:

- Add 1 millseconds delay to HttpResponse

Result:

Closes #2833

### CODE REVIEW

File: brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java [hunk 1]
```diff
@@ -84,8 +86,16 @@ protected void init() {
...
+            // The `Span.start()` and `Span.finish()` estimate the current time using
+            // `baseEpochMicros + (System.nanoTime() - baseTickNanos)`.
+            // However, Armeria achieves the current time using `System.currentTimeMillis() * 1000` in Java8.
+            // The two different way of getting the current time could cause an error of a millisecond.
+            // Sometimes the tolerance makes the server appear to finish earlier than child in test case.
+            // This is not a problem in the Brave{Service,Client} because they only use Armeria timestamp.
             tracing.tracer().nextSpan().name("child").start().finish();
-            return HttpResponse.of(OK, MediaType.PLAIN_TEXT_UTF_8, "happy");
+            return HttpResponse.delayed(
+                    HttpResponse.of(OK, MediaType.PLAIN_TEXT_UTF_8, "happy"), Duration.ofMillis(1));
```
Comment (trustin) [inline brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java:98]: How about delaying only for Java 8? We use microsecond precision for 9+.

Comment (ikhoon) [reply brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java:98]: That's a good idea.

File: brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java [hunk 2]
```diff
@@ -84,8 +86,21 @@ protected void init() {
...
+            // `baseEpochMicros + (System.nanoTime() - baseTickNanos)`.
+            // However, Armeria achieves the current time using `System.currentTimeMillis() * 1000` in Java8.
+            // The two different way of getting the current time could cause an error of a millisecond.
+            // Sometimes the tolerance makes the server appear to finish earlier than child in this test case.
+            // This is not a problem in the Brave{Service,Client} because they only use Armeria's timestamp.
             tracing.tracer().nextSpan().name("child").start().finish();
-            return HttpResponse.of(OK, MediaType.PLAIN_TEXT_UTF_8, "happy");
+            final Duration delay;
+            if (SystemInfo.javaVersion() > 8) {
+                delay = Duration.ofNanos(1000);
```
Comment (minwoox) [inline brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java:99]: How about just returning here?
`return HttpResponse.of(OK, MediaType.PLAIN_TEXT_UTF_8, "happy");`

Comment (ikhoon) [reply brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java:99]: We need 1 microsecond delay for Java 9 because `Clock.systemUTC().instant()` has microsecond precision. :-)
