### PR TITLE
Fix flaky test in HealthCheckedEndpointGroupIntegrationTest

### LINKED ISSUE #3974: Test failure: HealthCheckedEndpointGroupIntegrationTest
```
HealthCheckedEndpointGroupIntegrationTest > endpoints_containsUnhealthyServer(SessionProtocol) > com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest.endpoints_containsUnhealthyServer(SessionProtocol)[2] FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest 
    Expecting map:
      {"armeria.client.endpoint.group.count#value{name=bar,state=healthy}"=1.0, "armeria.client.endpoint.group.count#value{name=bar,state=unhealthy}"=1.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:1,ip=127.0.0.1,name=bar}"=0.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0}
    to contain entries:
      ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=1.0]
    but the following map entries had different values:
      ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0 (expected: 1.0)] within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest.endpoints_containsUnhealthyServer(HealthCheckedEndpointGroupIntegrationTest.java:190)

        Caused by:
        java.lang.AssertionError: 
        Expecting map:
          {"armeria.client.endpoint.group.count#value{name=bar,state=healthy}"=1.0, "armeria.client.endpoint.group.count#value{name=bar,state=unhealthy}"=1.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:1,ip=127.0.0.1,name=bar}"=0.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0}
        to contain entries:
          ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=1.0]
        but the following map entries had different values:
          ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0 (expected: 1.0)]
            at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest.lambda$endpoints_containsUnhealthyServer$4(HealthCheckedEndpointGroupIntegrationTest.java:198)
```

### PR DESCRIPTION
**Pull request by minwoox**
Close #3974

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java [hunk 1]
```diff
@@ -163,11 +157,10 @@ void endpoints_customPort(SessionProtocol protocol) throws Exception {
 
         try (HealthCheckedEndpointGroup endpointGroup = build(
                 HealthCheckedEndpointGroup.builder(Endpoint.of("127.0.0.1", 1),
-                        HEALTH_CHECK_PATH).port(portOne),
+                                                   HEALTH_CHECK_PATH).port(portOne),
                 protocol)) {
-            await().untilAsserted(() -> {
-                assertThat(endpointGroup.endpoints()).containsOnly(Endpoint.of("127.0.0.1", 1));
-            });
+            endpointGroup.whenReady().join();
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java:162]: 👍

**Review by ikhoon — APPROVED** [review]
Thanks, @minwoox!
