### PR TITLE
Reject most duplicate path mappings

### LINKED ISSUE #529: Show/Throw Error if register Service to the same path
When a user register multiple service to the same path through `ServerBuilder#serviceAt`, armeria creates a `Server` with services but PathMappings only map a request to a service that is registered first.
```java
    @ClassRule
    public static final ServerRule server = new ServerRule() {
        @Override
        protected void configure(ServerBuilder sb) throws Exception {
            sb.serviceAt("/api", new EchoService("1"))
              .serviceAt("/api", new EchoService("2"))
              .serviceAt("/api", new EchoService("3"));
        }
    };
    @Test
    public void test1() throws Exception {
        try (CloseableHttpClient hc = HttpClients.createMinimal()) {
            final HttpGet req = new HttpGet(server.uri("/api"));
            try (CloseableHttpResponse res = hc.execute(req)) {
                assertThat(EntityUtils.toString(res.getEntity()), is("1"));
            }
        }
    }
    private static class EchoService extends AbstractHttpService {
        private final String s;

        public EchoService(String s) {
            this.s = s;
        }

        @Override
        protected final void doGet(ServiceRequestContext ctx, HttpRequest req, HttpResponseWriter res) {
            res.write(HttpHeaders.of(HttpStatus.OK));
            res.write(HttpData.of(s.getBytes()));
            res.close();
        }
    }
```

It would be better to show message (or throw Exception) when ServerBuilder detects same path.

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

When a user binds more than one service at the same path mapping,
`ServerBuilder` should reject such a configuration.

Modifications:

- Add duplicate mapping detection to `Routers.routers()`
- Miscellaneous:
  - Weaken `PathMapping` types in `AnnotatedHttpServiceFactory`

Result:

- Almost fixes #529
- Note that this changeset does not detect all possible cases. For
  example, it does not consider the relationship between media types.
  It will detect most silly mistakes though, which should be enough.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 1]
```diff
@@ -116,6 +121,75 @@
...
+                if (!headerMapping.consumeTypes().isEmpty() &&
+                    headerMapping.consumeTypes().stream().noneMatch(
+                            mediaType -> existingHeaderMapping.consumeTypes().contains(mediaType))) {
+                    // No overlap in consume types.
+                    continue;
+                }
+                if (!headerMapping.produceTypes().isEmpty() &&
+                    headerMapping.produceTypes().stream().noneMatch(
+                            mediaType -> existingHeaderMapping.produceTypes().contains(mediaType))) {
+                    // No overlap in consume types.
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java]: consume -> produce

**Comment by trustin** [comment]
Thank you, reviewers!
