### PR TITLE
Fix for null GraphQL variables

### LINKED ISSUE #4068: null GraphQL parameter causes NPE
GraphQL, unlike Java, has three states for parameters sent through: undefined/missing, null and non-null. Armeria currently assumes all parameters are either undefined/missing or non-null. Null parameters causes the AbstractGraphqlService to return 500 Internal Server Error.

```
{
  "variables": { "value": null },
  "query": "query ($value: String) { optionalInput(value: $value) } "
}
```

The problem seems to be the Guava `ImmutableMap`, which doesn't seem to allow null values.
```
null value in entry: value=null[armeria-common-worker-epoll-2-5]
java.lang.NullPointerException: null value in entry: value=null
    at com.linecorp.armeria.internal.shaded.guava.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
    at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableMap.entryOf(ImmutableMap.java:337)
    at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableMap$Builder.put(ImmutableMap.java:447)
    at com.linecorp.armeria.server.graphql.protocol.AbstractGraphqlService.lambda$toMap$2(AbstractGraphqlService.java:171)
...
```
--edit:
There are three test cases in PR #4069 to help the bug-fixer

### PR DESCRIPTION
**Pull request by tobias-**
Motivation:

This PR adds test cases for null GraphQL variables (those sent in the "variables" part of the json body posted) and fixes the issue #4068.

Modifications:

Fixes issue with null variables in GraphQL json request.

Added test case for GraphQL that tests the three different cases:
- undefined in Apollo client, ie. variables is defined in `query`, but not set in `variables`
- null in Apollo client, ie. GraphQL variables is sent as null
- complex type with inner value in Apollo client, ie. non-null variable sent as json-object with non-null attribute on it
 
Result:

- Closes #4068
- Server will stop responding 500 when sending null GraphQL variable

### CODE REVIEW

File: graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java [hunk 1]
```diff
@@ -152,24 +152,25 @@ protected abstract HttpResponse executeGraphql(ServiceRequestContext ctx, Graphq
         if (Strings.isNullOrEmpty(value)) {
             return ImmutableMap.of();
         }
-        return parseJsonString(value);
+        return toMapFromJson(parseJsonString(value));
```
Comment (ikhoon) [inline graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java:155]: Should we need to additionally call `toMapFromJson()`?

File: graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java [hunk 2]
```diff
@@ -249,4 +266,60 @@ void shouldReturnBadRequestForInvalidQuery() {
...
+                "    }\n" +
+                "  },\n" +
+                "  \"query\": \"query ($value: ComplexTypeInput) { optionalInput(value: $value) }\"\n" +
+                "}\n";
+        final HttpRequest request = HttpRequest.builder().post("/graphql")
+                                               .content(MediaType.GRAPHQL_JSON, query)
+                                               .build();
+        final AggregatedHttpResponse response = WebClient.of(server.httpUri())
+                                                         .execute(request)
+                                                         .aggregate().join();
```
Comment (ikhoon) [inline graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java:304]: How about using a brand new `BlockingWebClient`?
```suggestion
        final AggregatedHttpResponse response = BlockingWebClient.of(server.httpUri()).execute(request);
```

**Review by ikhoon — APPROVED** [review]
Thanks for the quick fix, @tobias-!

File: graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java (hunk 2 above)
Comment (tobias-) [reply graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java:304]: Oh, I just copied without pride from the other test cases. I'll change it!

File: graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java (hunk 1 above)
Comment (tobias-) [reply graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java]: no, that's just wrong. Fixing!

File: graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java [hunk 3]
```diff
@@ -109,8 +109,8 @@ protected HttpResponse doPost(ServiceRequestContext ctx, HttpRequest request) th
                         return HttpResponse.of(HttpStatus.BAD_REQUEST, MediaType.PLAIN_TEXT, "Missing query");
                     }
                     final String operationName = (String) requestMap.get("operationName");
-                    final Map<String, Object> variables = toMap(requestMap.get("variables"));
-                    final Map<String, Object> extensions = toMap(requestMap.get("extensions"));
+                    final Map<String, Object> variables = toMapFromJson(requestMap.get("variables"));
```
Comment (jrhee17) [inline graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java:112]: Note: I feel like it might be worth `try..catch`ing `toMapFromJson` and returning a `BAD_REQUEST`.

As an example, if IAE is thrown the response code will end up being 500.

https://github.com/line/armeria/blob/7e11984205e4325f510b522f81fb241e13ce21da/graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java#L175

Having said this, I don't think this needs to be handled in this PR

File: graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java [hunk 4]
```diff
@@ -155,21 +155,22 @@ protected abstract HttpResponse executeGraphql(ServiceRequestContext ctx, Graphq
...
+            final Map<?, ?> map = (Map<?, ?>) maybeMap;
+            if (map.isEmpty()) {
                 return ImmutableMap.of();
             }
-
-            final ImmutableMap.Builder<String, Object> builder =
-                    ImmutableMap.builderWithExpectedSize(variablesMap.size());
-            variablesMap.forEach((k, v) -> builder.put(String.valueOf(k), v));
-            return builder.build();
+            return (Map<String, Object>) map;
```
Comment (jrhee17) [inline graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java:173]: Q) Is there a reason we're not wrapping in `Collections.unmodifiableMap()`?

```suggestion
            return (Map<String, Object>) Collections.unmodifiableMap(map);
```

**Review by jrhee17 — COMMENTED** [review]
Left a minor question. Thanks for the quick fix 👍

File: graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java (hunk 4 above)
Comment (ikhoon) [reply graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java:173]: I thought it is fine because `parseJsonString()` in `toMap()` already returns a mutable `Map`.
If we decided to pass an immutable `Map` to `GraphqlRequest`, it would be nice to apply the `Map` returned by `parseJsonString()` too.

Comment (jrhee17) [reply graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java:173]: I see. Sounds like this might be out of scope for this PR then 👍

**Review by jrhee17 — APPROVED** [review]
Thanks @tobias- ! 🙇 👍 💯

File: graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java (hunk 3 above)
Comment (tobias-) [reply graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java:112]: I agree to both statements. 500 is wrong when it's clearly a client error, and that it shouldn't be changed in this PR.

File: graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java (hunk 4 above)
Comment (tobias-) [reply graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java:173]: Even before this PR, the `Map` may (and often will) have other maps as values, and they were never converted into immutable maps. That's actually how we're currently circumventing the bug in Armeria, ie. by having complex types.

Imho I even think it's a bad idea to do the immutability, as Armeria is never using the map (just deserializing it and then sending it on), and forwarding immutable maps to Graphql-java when afaik there is no contract stating that immutable maps are ok, could very well break future versions of Graphql-java for no good reason.

**Review by minwoox — APPROVED** [review]
Thanks a lot, @tobias-!

**Comment by minwoox** [comment]
@heowc Do you mind reviewing this PR? 😆

**Comment by heowc** [comment]
> @heowc Do you mind reviewing this PR? 😆

I think it's perfect. 👍👍

Thank you to @tobias- and reviewers for fixing the bug! 😍

**Review by trustin — APPROVED** [review]
