### PR TITLE
Fix flaky `DomainSocket*` tests

### LINKED ISSUE #4959: Test failure: `com.linecorp.armeria.server.DomainSocketServerTest.executionError`
```
java.io.IOException: Failed to delete temp directory /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit9515291060972060513. The following paths could not be deleted (see suppressed exceptions for details): test.sock
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:351)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:252)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
```

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

`DomainSocketServerTest` frequently fails to delete the domain socket file used for testing.
https://github.com/line/armeria/actions/runs/5816889007/job/15770694188?pr=5108#step:7:1746
```
DomainSocketServerTest > executionError FAILED
    java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/armeria17713324805503526473/test.sock
        at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
        at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.linecorp.armeria.internal.testing.TemporaryFolder.delete(TemporaryFolder.java:82)
        at com.linecorp.armeria.internal.testing.TemporaryFolderExtension.after(TemporaryFolderExtension.java:60)
        at com.linecorp.armeria.testing.junit5.common.AbstractAllOrEachExtension.afterAll(AbstractAllOrEachExtension.java:63)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

        Caused by:
        java.nio.file.NoSuchFileException: /tmp/armeria17713324805503526473/test.sock
            at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
```

After checking the Netty code, I found out a race condition that Netty's `ServerDomainSocketChannel` also tries to delete the domain socket file when it is being closed.
https://github.com/netty/netty/blob/9eb029d630b269e907aaa4a19bc86753d70e399c/transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollServerDomainSocketChannel.java#L79-L81

Modifications:

- Do not automatically delete domain socket files used for testing and delegate Netty to delete them

Result:

- Stabilize CI build results
- Fixes #4959

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
Thanks! 👍 🙇 👍

File: testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java [hunk 1]
```diff
@@ -76,18 +70,23 @@ public void delete() throws IOException {
...
-                .forEach(file -> {
-                    try {
-                        file.delete();
-                    } catch (Exception e) {
-                        logger.warn("Unexpected exception while deleting file: {}", file.getName(), e);
-                    }
-                });
-        }
-
+        deleteAll(root.toFile());
```
Comment (jrhee17) [inline testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java:73]: Question) So will the `root` directory be deleted with the current implementation?

**Review by jrhee17 — APPROVED** [review]
Left a minor question but looks good. Thanks @ikhoon 🙇 👍 🙇

File: testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java [hunk 2]
```diff
@@ -76,18 +70,23 @@ public void delete() throws IOException {
...
-                });
+        deleteAll(root.toFile());
+        root = null;
+    }
+
+    private static void deleteAll(File file) throws IOException {
+        // Use File#listFiles() instead of Files#list() to ignore files deleted by other threads during
+        // iteration. See https://github.com/line/armeria/issues/4959
+        if (file.isDirectory()) {
+            final File[] files = file.listFiles();
```
Comment (trustin) [inline testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java:81]: What would happen if someone deletes this directory right after `files.isDirectory()` returns `true`?

File: testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java [hunk 3]
```diff
@@ -76,18 +70,23 @@ public void delete() throws IOException {
...
+            if (files == null) {
+                return;
+            }
+            for (File child : files) {
+                deleteAll(child);
+            }
         }
 
-        root = null;
+        Files.deleteIfExists(file.toPath());
```
Comment (trustin) [inline testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java:90]: Maybe we can just use `file.delete()`?

**Review by trustin — APPROVED** [review]

File: testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java (hunk 2 above)
Comment (ikhoon) [reply testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java:81]: `listFiles()` returns `null` if the path is invalid.
https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/io/File.java#L1175C15-L1176

**Review by trustin — APPROVED** [review]
Thanks a lot, @ikhoon!
