### PR TITLE
Wrap ProxyConnectException with UnprocessedRequestException

### LINKED ISSUE #2601: Wrap ProxyConnectException with UnprocessedRequestException
Because it's an unprocessed request.

### PR DESCRIPTION
**Pull request by jrhee17**
Fixes #2601

**Motivation**
Before proxy connection is successfully negotiated, all writes are pending and not sent.
This signifies proxy negotiation failure is safely retry-able.

**Modification**
Ignore `ProxyConnectException`  due to write failure in `HttpRequestSubscriber`.
Wrap `ProxyConnectException` in `HttpSessionHandler. exceptionCaught`

### CODE REVIEW

**Comment by trustin** [comment]
Is this the best place to wrap a `ProxyConnectException`? Hmm..

File: core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java [hunk 1]
```diff
@@ -350,6 +351,10 @@ public void channelInactive(ChannelHandlerContext ctx) throws Exception {
 
     @Override
     public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
+        if (cause instanceof ProxyConnectException) {
+            setPendingException(ctx, new UnprocessedRequestException(cause));
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java]: Looks like a good place!

File: core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java [hunk 2]
```diff
@@ -334,6 +335,10 @@ private void cancelSubscription() {
     }
 
     private void failAndReset(Throwable cause) {
+        if (cause instanceof ProxyConnectException) {
+            return;
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java]: Could you add some comment? e.g.

```
// ProxyConnectException is handled by HttpSessionHandler.exceptionCaught().
```
