### PR TITLE
Do not record wire timestamp when no request was transferred

### LINKED ISSUE #1911: `RequestLogAvailabilityException: REQUEST_FIRST_BYTES_TRANSFERRED` when `RequestLogAvailability` is `COMPLETE`
Reported by @adriancole:

```
WARN 88577 --- [orageComponent}] c.l.a.c.l.RequestLogListenerInvoker      : onRequestLog() failed with an exception:com.linecorp.armeria.common.logging.RequestLogAvailabilityException: REQUEST_FIRST_BYTES_TRANSFERRED
    at com.linecorp.armeria.common.logging.RequestLog.ensureAvailability(RequestLog.java:120) ~[armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.common.logging.DefaultRequestLog.requestFirstBytesTransferredTimeNanos(DefaultRequestLog.java:446) ~[armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.client.brave.BraveClient.lambda$execute$2(BraveClient.java:126) ~[armeria-brave-0.88.0.jar!/:?]
    at com.linecorp.armeria.common.logging.RequestLogListenerInvoker.invokeOnRequestLog(RequestLogListenerInvoker.java:38) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.common.logging.DefaultRequestLog.notifyListeners(DefaultRequestLog.java:1036) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.common.logging.DefaultRequestLog.updateAvailability(DefaultRequestLog.java:993) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:970) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:949) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse(DefaultRequestLog.java:935) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.internal.ClientUtil.executeWithFallback(ClientUtil.java:50) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.client.UserClient.execute(UserClient.java:159) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:61) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:78) [armeria-0.88.0.jar!/:?]
    at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:74) [armeria-0.88.0.jar!/:?]
    at zipkin2.elasticsearch.internal.client.HttpCall.sendRequest(HttpCall.java:145) [zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
    at zipkin2.elasticsearch.internal.client.HttpCall.doExecute(HttpCall.java:101) [zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
    at zipkin2.Call$Base.execute(Call.java:379) [zipkin-2.15.1-SNAPSHOT.jar!/:?]
    at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:286) [zipkin-reporter-2.8.4.jar!/:?]
    at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:190) [zipkin-reporter-2.8.4.jar!/:?]
```

In BraveClient.java:

```java
        ctx.log().addListener(log -> {
            SpanTags.logWireSend(span, log.requestFirstBytesTransferredTimeNanos(), log);

            // If the client timed-out the request, we will have never received any response data at all.
            if (log.isAvailable(RequestLogAvailability.RESPONSE_FIRST_BYTES_TRANSFERRED)) {
                SpanTags.logWireReceive(span, log.responseFirstBytesTransferredTimeNanos(), log);
            }

            finishSpan(span, log);
        }, RequestLogAvailability.COMPLETE);
```

/cc @anuraaga

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

On the client side, it is possible that a request is not sent to the
wire, e.g. when connection error or validation failure occurs.

Modifications:

- Make sure `REQUEST_FIRST_BYTES_TRANSFERRED` is available before
  logging wire receive.

Result:

- No more `RequestLogAvailabilityException` in `BraveClient` and
  `HttpTracingClient`.
- Fixes #1911

### CODE REVIEW

File: brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java [hunk 1]
```diff
@@ -123,7 +123,10 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) throws Ex
         ctx.onChild(TraceContextUtil::copy);
 
         ctx.log().addListener(log -> {
-            SpanTags.logWireSend(span, log.requestFirstBytesTransferredTimeNanos(), log);
+            // The request might have failed even before it's sent, e.g. validation failure, connection error.
+            if (log.isAvailable(RequestLogAvailability.REQUEST_FIRST_BYTES_TRANSFERRED)) {
+                SpanTags.logWireSend(span, log.requestFirstBytesTransferredTimeNanos(), log);
+            }
```
Comment (minwoox) [inline brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java]: Shouldn't we do something like:
```
if (!log.isAvailable(RequestLogAvailability.REQUEST_FIRST_BYTES_TRANSFERRED)) {
    return;
}
SpanTags.logWireSend(span, log.requestFirstBytesTransferredTimeNanos(), log);
```

Comment (minwoox) [reply brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java]: Never mind, 😓 Misread the code. TT

**Comment by trustin** [comment]
Thanks for reviewing. :smile:
