### PR TITLE
Provide type parameter information to `RequestConverterFunction`

### LINKED ISSUE #2769: `@RequestObject List<Long>` is injected with `List<Integer>`
In the following annotated service method:

```java
@Post("/")
public String method(@RequestObject List<Long> values) {
    for (Long v : values) {
        // ClassCastException in runtime
    }
}
```

`values` is injected with a `List` of `Integer`s, which is not correct, causing `ClassCastException` in runtime. As usual, the request to reproduce is a POST request whose content is a JSON array of numbers, e.g. `[1, 2, 3]`

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

Some generic converters such as `JacksonRequestConverterFunction` need
to get the complete type parameter information from annotated service
methods, so that the type of elements of a container type is known.

For example, let's say a user posts a JSON array:

    [1, 2, 3]

to an annotated service method:

    @Post("/post")
    public String post(List<Long> values) {
        return Joiner.on(", ").join(values);
    }

Without proper type parameter information, `JacksonRequestConverterFunction`
cannot convert the elements into `Long`.

Modifications:

- (Breaking) Changed the signature of `RequestConverterFunction.convertRequest()`
  so that a converter is given with `ParameterizedType`.
- (Breaking) `Optional` is now always handled automatically.
  - If you wrote a `RequestConverterFunction` that converts to an `Optional`, it will not work anymore. Return `null` instead.
- (Breaking) Without `@Nullable`, `null` will never be injected into a request object,
  which was possible when a `RequestConverterFunction` returns `null`.
  - Add `@Nullable` if your converter returns `null`.
- Made sure `ParameterizedType` is passed to the request converter when
  necessary.
- Micellaneous:
  - A value can now be converted to `AsciiString`, `CharSequence` or `Object`.
  - `JacksonRequestConverterFunction` now knows how to convert to
    `TreeNode` and `JsonNode`.

Result:

- Closes #2769
- `JacksonRequestConverterFunction` now considers type parameters during
  conversion.
- A user can write more complex request object converter.
- Can inject `CharSequence`, `AsciiString` and `Object` now.
- (Breaking) Changed the signature of `RequestConverterFunction.convertRequest()`
  so that a converter is given with `ParameterizedType`.
- (Breaking) `Optional` is now always handled automatically.
  - If you wrote a `RequestConverterFunction` that converts to an `Optional`, it will not work anymore. Return `null` instead.
- (Breaking) Without `@Nullable`, `null` will never be injected into a request object,
  which was possible when a `RequestConverterFunction` returns `null`.
  - Add `@Nullable` if your converter returns `null`.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java [hunk 1]
```diff
@@ -1013,7 +966,7 @@ private AnnotatedValueResolver build() {
             if (aDefault != null) {
                 if (supportDefault) {
                     // Warn unusual usage. e.g. @Param @Default("a") Optional<String> param
-                    if (shouldWrapValueAsOptional) {
+                    if (isOptional) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:969]: I'm wondering if we need to warn when `@Nullable` is specified as well.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java [hunk 2]
```diff
@@ -1094,16 +1039,116 @@ private AnnotatedValueResolver build() {
...
+                return null;
+            }
+
+            if (rawType == Iterable.class ||
+                rawType == List.class ||
+                rawType == Collection.class) {
+                return ArrayList.class;
+            }
+
+            if (rawType == Set.class) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:1081]: Can we support `Map`, `GenericArrayType` and arrays as we do in the DocService? 🤔 
Supporting `Map` is maybe too much because we have to use varagrs for `expectedParameterizedResultType` though. 🤔

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:1081]: Not sure about `Map`, but I think it's a good idea to support arrays. Maybe later in another PR? 😁

File: core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java [hunk 3]
```diff
@@ -100,14 +101,19 @@ public String convert2(RequestJsonObj1 obj1) {
...
+        public String convert3(@RequestConverter(TestRequestConverter1.class) Optional<RequestJsonObj1> obj1,
+                               @RequestConverter(TestRequestConverter2.class) Optional<RequestJsonObj2> obj2) {
             assertThat(obj1.isPresent()).isTrue();
             assertThat(obj2.isPresent()).isTrue();
             return obj2.get().strVal();
         }
+
+        @Post("/convert4")
+        @RequestConverter(NullReturningConverter.class)
+        public void convert4(Optional<String> optional, @Nullable String nullable) {
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java:113]: Question: What is the expected behavior if `String nullable` is not annotated by `@Nullable`?
`null` value is injected into `nullable`.

Comment (ikhoon) [reply core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java:113]: By the way, `NullReturningConverter` returns null. It looks like a correct test.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java (hunk 2 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java:1111]: https://github.com/line/armeria/issues/2790

File: core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java (hunk 3 above)
Comment (trustin) [reply core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java:114]: I added another method with non-null parameter which is expected to fail with a 400 Bad Request error.

**Comment by trustin** [comment]
Thanks for reviewing!
