### PR TITLE
Fix a bug when `ConcurrencyLimitingClient` is added after `RetryingClient`

### LINKED ISSUE #4826: Potential deadlock when a `ConcurrencyLimitingClient` is added after a `RetryingClient`
`RetryingClient` relies on several signals to determine whether to trigger retry or not.
1. An exception is thrown while processing the decorator chain
2. Listen to the returned `HttpResponse`
3. Listen to `ClientRequestContext#log`

Not all code-paths will listen to the 3 signals specified above.
For instance in normal cases, the `RetryingClient` doesn't listen to the returned `HttpResponse` and will listen to `ClientRequestContext#log` only.

https://github.com/line/armeria/blob/62349aba927cde2a8bf8936051b7346e7002a2d9/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L378

On the other hand, `ConcurrencyLimitingClient` works by asynchronously acquiring a permit and proxying the request.
If an exception is thrown upstream the response is completed and returned, but the `ClientRequestContext#log` is never completed.

https://github.com/line/armeria/blob/62349aba927cde2a8bf8936051b7346e7002a2d9/core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java#L123-L125

When a `RetryingClient` and `ConcurrencyLimitingClient` are used sequentially, it is possible that `RetryingClient` listens for an event that will never be triggered by the upstream `ConcurrencyLimitingClient`.

We may consider either
1) Also listen to `HttpResponse#whenComplete` events from `RetryingClient`
2) Complete the `ClientRequestContext#log` at `ConcurrencyLimitingClient`
3) Or both.

As a side-note, I don't necessarily think a request throttled by `ConcurrencyLimitingClient` should be deemed a "failed" request which makes me wonder if 2) is really a good solution

repro: https://github.com/jrhee17/armeria/tree/poc/deadlock-repro

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

Usually, Armeria ensures completeness of both `HttpResponse` and `ClientRequestContext#log` when a response is compete.
https://github.com/line/armeria/blob/14294e33bb34c030c6ffb4e4d29aad1974257532/core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java#L231-L239

However in the case of `ConcurrencyLimitingClient` only the `HttpResponse` is completed.

https://github.com/line/armeria/blob/14294e33bb34c030c6ffb4e4d29aad1974257532/core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java#L108-L110

https://github.com/line/armeria/blob/14294e33bb34c030c6ffb4e4d29aad1974257532/core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java#L123-L125

This can result in a deadlock when used with decorators such as `RetryingClient` or `CircuitBreakerClient` which assume that both `ClientRequestContext#log` and `HttpResponse` are complete.

I propose that `ConcurrencyLimitingClient` follows the closing behavior of other request paths and close the `ClientRequestContext#log`.

Note: @minwoox and I also had a discussion on adding a callback to complete `ClientRequestContext#log` where it is created.
To due so, we may want to add a callback which closes the `ClientRequestContext#log` whenever the `HttpResponse` is complete.

e.g.
```
response.whenComplete().handle((ignored, cause) -> {
    if (cause != null) {
        derivedCtx.logBuilder().endResponse(cause);
    }
    ...
});
```
Additionally, the behavior may be better defined if `RetryingClient`, `CircuitBreakerClient` relies on `HttpResponse` completion instead of both `HttpResponse`, `ClientRequestContext#log`.

Let me handle this in a separate PR 🙇 

Modifications:

- Complete `ClientRequestContext#log` when an exception is thrown from `ConcurrencyLimitingClient` or upstream of `ConcurrencyLimitingClient`

Result:

- Closes #4826 . (If this resolves the issue.)
- Describe the consequences that a user will face after this PR is merged.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java [hunk 1]
```diff
@@ -106,7 +106,11 @@ public final O execute(ClientRequestContext ctx, I req) throws Exception {
                         .handleAsync((permit, throwable) -> {
                             if (throwable != null) {
                                 // Wrap the exception with UnprocessedRequestException.
-                                resFuture.completeExceptionally(UnprocessedRequestException.of(throwable));
+                                final UnprocessedRequestException t =
+                                        UnprocessedRequestException.of(throwable);
+                                resFuture.completeExceptionally(t);
+                                ctx.logBuilder().endRequest(t);
+                                ctx.logBuilder().endResponse(t);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java:113]: nit: We can extract these to a method:
```
private static void completeExceptionally(ClientRequestContext ctx,
                                          CompletableFuture<?> resFuture, Throwable t) {
...
}
```

**Review by minwoox — APPROVED** [review]
Just one nit. Thanks a lot!

**Review by ikhoon — APPROVED** [review]
Thanks, @jrhee17!
