### PR TITLE
Fix a bug where RetryConfigMapping is evaluated multiple times per req

### LINKED ISSUE #4753: RetryConfigMapping is re-evaluated on each try; and at least twice (when no retries are engaged)
See [this slack thread](https://line-armeria.slack.com/archives/C1NGPBUH2/p1678687047827359) for more details.

TL;DR: 

`RetryConfigMapping` is evaluated [here](https://github.com/line/armeria/blame/2e91b276816369df6c8d0ece39a81b1e63f69f9d/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L289), which is the code path for every try. There is probably not a lot of value in re-evaluating already computed RetryConfig as it may only add to confusion how these complements interact. Specifically, I'm not sure it's a good idea to swap a `RetryConfig` mid-retry (say on attempt 2 out of 5). What does it even mean, given there is a already a logical state built out of original mapping evaluation.

I'm happy to put together a fix for such that a mapping is evaluated at most once per logical request.

### PR DESCRIPTION
**Pull request by vkostyukov**
Motivation:

As described in #4753, user-configured `RetryConfigMapping` is evaluated multiple time per original/logical request. Twice for the original try, and an additional evaluation per each try. Not only this behavior could be surprising for users, it's also a performance penalty as most of the `RetryConfigMapping`s idempotent (don't change in between the retries).

Modifications:

- Only evaluate `RetryConfigMapping` once and store the result in `ClientReqeustContext`.

Result:

- Closes #4753

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java [hunk 1]
```diff
@@ -509,6 +510,9 @@ void honorRetryMapping() {
         assertThat(client.get("/502-always").aggregate().join().status())
                 .isEqualTo(HttpStatus.valueOf(502));
         assertThat(stopwatch.elapsed()).isBetween(Duration.ofSeconds(0), Duration.ofSeconds(2));
+
+        // We sent 3 logical requests so the retry mapping should have been only evaluated 3 times.
+        assertThat(retryMappingEvaluations.get()).isEqualTo(3);
```
Comment (vkostyukov) [inline core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java:515]: This new assert fails on the "old" code with 14 != 3.

**Review by minwoox — APPROVED** [review]
Thanks a lot for fixing this! 😄

File: core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java [hunk 2]
```diff
@@ -83,8 +83,7 @@ public final O execute(ClientRequestContext ctx, I req) throws Exception {
         requireNonNull(config, "mapping.get() returned null");
 
         final State state = new State(
-                config.maxTotalAttempts(),
-                config.responseTimeoutMillisForEachAttempt(),
+                config,
                 ctx.responseTimeoutMillis());
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java:87]: nit: join three lines that might be easier to read.

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java [hunk 3]
```diff
@@ -324,8 +324,7 @@ private void doExecute0(ClientRequestContext ctx, HttpRequestDuplicator rootReqD
             response = executeWithFallback(unwrap(), derivedCtx,
                                            (context, cause) -> HttpResponse.ofFailure(cause));
         }
-
-        final RetryConfig<HttpResponse> config = mapping().get(ctx, duplicateReq);
+        final RetryConfig<HttpResponse> config = mappedRetryConfig(ctx);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:327]: Could you also fix `RetryingRpcClient`, the counterpart?
https://github.com/line/armeria/blob/aa3c6e1acfd41c8ab4f15f2eff2051a87bc8cc18/core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java#L189

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java (hunk 1 above)
Comment (ikhoon) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java:515]: Would you mind testing `RetryingRpcClient` with Thrift clients?

Comment (vkostyukov) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java]: Done, PTAL.

File: core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java [hunk 4]
```diff
@@ -122,6 +119,14 @@ protected final RetryRule retryRule() {
         return retryRule;
     }
 
+    /**
+     * Fetches the {@link RetryConfig} that was mapped by the configured {@link RetryConfigMapping} for a given
+     * logical request.
+     */
+    protected final RetryConfig<O> mappedRetryConfig(ClientRequestContext ctx) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java:126]: I prefer to make this internal use only since a NullPointerException will be used if this method is invoked before `State` is set.
```suggestion
    final RetryConfig<O> mappedRetryConfig(ClientRequestContext ctx) {
```

**Review by ikhoon — APPROVED** [review]
Thanks for the quick and neat fetch! 👍 💯

File: core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java (hunk 4 above)
Comment (vkostyukov) [reply core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java:126]: Let's do it.

**Review by trustin — APPROVED** [review]
:+1:

**Review by jrhee17 — APPROVED** [review]
Thanks @vkostyukov ! 🙇 🚀 💯
