### PR TITLE
Ignore `CancelledSubscriptionException` when WebFlux's WebClient cancels the upstream

### LINKED ISSUE #3730: Intermittently `CancelledSubscriptionException` triggered earlier than the upstream exception when using Spring Webflux integration
Let's say a user tries to convert a JSON body into an object using `WebClient` of WebFlux.
```kt
val myDomainObject = webClient.post()
    // http://localhost:8080/abnormal will return a JSON body with "text/plain"
    .uri("http://localhost:8080/abnormal")
    .retrieve()
    .awaitBody<MyDomainObject>()
```
If `text/plain;charset=utf-8` for `Content-Type` is received, the `UnsupportedMediaTypeException` is raised as expected. 

```
2021-07-14 15:57:27.420 ERROR 20188 --- [worker-nio-2-32] a.w.r.e.AbstractErrorWebExceptionHandler : [1e260dd5faaa9603]  500 Server Error for HTTP GET "/test1"

org.springframework.web.reactive.function.client.WebClientResponseException: 200 OK from POST http://localhost:8080/abnormal; nested exception is org.springframework.web.reactive.function.UnsupportedMediaTypeException: Content type 'text/plain;charset=utf-8' not supported for bodyType=com.example.demo.model.Abnormal
	at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:229) ~[spring-webflux-5.3.8.jar:5.3.8]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.example.demo.controller.TestController#test1(Continuation) [DispatcherHandler]
	|_ checkpoint ⇢ HTTP GET "/test1" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:229) ~[spring-webflux-5.3.8.jar:5.3.8]
		at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:213) ~[spring-webflux-5.3.8.jar:5.3.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:108) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onComplete(FluxMapFuseable.java:344) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onComplete(FluxFilterFuseable.java:391) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:85) ~[reactor-core-3.4.7.jar:3.4.7]
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143) ~[na:na]
		at reactor.core.publisher.MonoCompletionStage.subscribe(MonoCompletionStage.java:57) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4150) ~[reactor-core-3.4.7.jar:3.4.7]
		at com.linecorp.armeria.spring.web.reactive.ArmeriaHttpResponseBodyStream.subscribe(ArmeriaHttpResponseBodyStream.java:68) ~[armeria-spring-boot2-webflux-autoconfigure-1.9.2.jar:na]
		at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:66) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4150) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2062) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Operators.error(Operators.java:197) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxError.subscribe(FluxError.java:43) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Flux.subscribe(Flux.java:8235) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:208) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:88) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxTakeWhile$TakeWhileSubscriber.onComplete(FluxTakeWhile.java:121) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxTakeWhile$TakeWhileSubscriber.onNext(FluxTakeWhile.java:95) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.7.jar:3.4.7]
		at com.linecorp.armeria.internal.common.DefaultSplitHttpResponse$BodySubscriber.onNext0(DefaultSplitHttpResponse.java:303) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.internal.common.DefaultSplitHttpResponse$BodySubscriber.lambda$onNext$1(DefaultSplitHttpResponse.java:294) ~[armeria-1.9.2.jar:na]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.springframework.web.reactive.function.UnsupportedMediaTypeException: Content type 'text/plain;charset=utf-8' not supported for bodyType=com.example.demo.model.Abnormal
	at org.springframework.web.reactive.function.BodyExtractors.lambda$readWithMessageReaders$12(BodyExtractors.java:201) ~[spring-webflux-5.3.8.jar:5.3.8]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Body from POST http://localhost:8080/abnormal [DefaultClientResponse]
Stack trace:
		at org.springframework.web.reactive.function.BodyExtractors.lambda$readWithMessageReaders$12(BodyExtractors.java:201) ~[spring-webflux-5.3.8.jar:5.3.8]
		at java.base/java.util.Optional.orElseGet(Optional.java:369) ~[na:na]
		at org.springframework.web.reactive.function.BodyExtractors.readWithMessageReaders(BodyExtractors.java:197) ~[spring-webflux-5.3.8.jar:5.3.8]
		at org.springframework.web.reactive.function.BodyExtractors.lambda$toMono$2(BodyExtractors.java:85) ~[spring-webflux-5.3.8.jar:5.3.8]
		at org.springframework.web.reactive.function.client.DefaultClientResponse.body(DefaultClientResponse.java:131) ~[spring-webflux-5.3.8.jar:5.3.8]
		at org.springframework.web.reactive.function.client.DefaultClientResponse.bodyToMono(DefaultClientResponse.java:151) ~[spring-webflux-5.3.8.jar:5.3.8]
		at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.lambda$bodyToMono$3(DefaultWebClient.java:548) ~[spring-webflux-5.3.8.jar:5.3.8]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.7.jar:3.4.7]
		at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:82) ~[reactor-core-3.4.7.jar:3.4.7]
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
		at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.internal.common.DefaultSplitHttpResponse$HeadersFuture.doComplete(DefaultSplitHttpResponse.java:387) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.internal.common.DefaultSplitHttpResponse$BodySubscriber.onNext(DefaultSplitHttpResponse.java:275) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.internal.common.DefaultSplitHttpResponse$BodySubscriber.onNext(DefaultSplitHttpResponse.java:164) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.FilteredStreamMessage$FilteringSubscriber.onNext(FilteredStreamMessage.java:300) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:535) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:507) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:454) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:440) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObject(DefaultStreamMessage.java:343) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.AbstractStreamMessageAndWriter.tryWrite(AbstractStreamMessageAndWriter.java:62) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.tryWrite(DefaultStreamMessage.java:74) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.client.DecodedHttpResponse.tryWrite(DecodedHttpResponse.java:55) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.handleWaitNonInformational(HttpResponseDecoder.java:256) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.tryWrite(HttpResponseDecoder.java:221) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.tryWrite(HttpResponseDecoder.java:149) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.common.stream.StreamWriter.write(StreamWriter.java:70) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:205) ~[armeria-1.9.2.jar:na]
		at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:225) ~[armeria-1.9.2.jar:na]
		...
```

However, intermittenly `c.l.a.c.stream.CancelledSubscriptionException` is raised and users don't see the exect cause of the failure.
```
2021-07-14 15:57:28.227 ERROR 20188 --- [-worker-nio-2-3] a.w.r.e.AbstractErrorWebExceptionHandler : [f7130b25856cfb86]  500 Server Error for HTTP GET "/test1"

com.linecorp.armeria.common.stream.CancelledSubscriptionException: null
```

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

When 1) an error is raised from WebFlux's `WebClient`, the `WebClient`
immediately cancels the upstream. If `whenComplete()` completes with an
`CancelledSubscriptionException`, the actual error raised in 1) will be
ignored and users can't see the actual error.
See: https://github.com/line/armeria/issues/3730

Modifications:

- Silently ignore `CancelledSubscriptionException` and let WebFlux's
  `WebClient` propagate the original error.
- Add `:it:spring:boot2-kotlin` for testing compatibility between
  Spring WebFlux integration and Kotlin

Result:

- You no longer see `CancelledSubscriptionException` when WebFlux's
  `WebClient` receives an unexpected `Content-Type` header.
- Closes #3730

### CODE REVIEW

File: it/spring/boot2-kotlin/src/test/kotlin/com/linecorp/armeria/spring/kotlin/AbnormalController.kt [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+package com.linecorp.armeria.spring.kotlin
+
+import com.fasterxml.jackson.databind.ObjectMapper
+import org.springframework.http.ResponseEntity
+import org.springframework.stereotype.Controller
+import org.springframework.web.bind.annotation.GetMapping
+import org.springframework.web.bind.annotation.ResponseBody
+
+@Controller
+class AbnormalController(private val objectMapper: ObjectMapper) {
```
Comment (trustin) [inline it/spring/boot2-kotlin/src/test/kotlin/com/linecorp/armeria/spring/kotlin/AbnormalController.kt:25]: How about adding a small KotlinDoc like: 'This controller returns a JSON with an incorrect content type header.'

**Review by trustin — APPROVED** [review]
:+1:

**Comment by ikhoon** [comment]
Thanks for reviewing!
