### PR TITLE
Fix HttpJsonTranscodingService to find field descriptor with `field.getMessageType()`

### LINKED ISSUE #4631: Defect: HttpTranscodingService fails to find descriptor for nested message fields
On certain conditions, armeria server fails to start with this error message:
Descriptor for the type 'PROTO_MESSAGE_FULL_NAME' does not exist.
This happens when a nested message is used as a field type from another message
i.e)
```proto
message A {
    string name = 1;
    B b = 2;
    message B {
        string name = 1;
    }
}

message SomeARequest { // error when getting field b type Descriptor for this message
    A.B b = 1;
}
```
The problem is that when finding the descriptor from file (HttpJsonTranscodingService:L333), Descriptors#findMessageTypeByName is used to find the descriptor.
However, this method does not find nested types
``` java
/**
 * Find a message type in the file by name. Does not find nested types.
 *
 * @param name The unqualified type name to look for.
 * @return The message type's descriptor, or {@code null} if not found.
 */
public Descriptor findMessageTypeByName(String name)
```
resulting with exception and the server hangs without starting.

### PR DESCRIPTION
**Pull request by j-min5u**
Motivation:

Bug in HttpJsonTranscodingService when finding descriptor for nested message types

Result:

- Closes #4631

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java [hunk 1]
```diff
@@ -348,7 +348,7 @@ private static Map<String, Field> buildFields(Descriptor desc,
                                 .findFirst().orElse(null);
                     if (typeDesc == null) {
                         // From the proto file.
-                        typeDesc = findTypeDescriptor(desc.getFile(), field);
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:351]: So probably we can replace the usage of `findTypeDescriptor` to `field.getMessageType()` in this class?
Could you check it please?

Comment (j-min5u) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:351]: It seems that `findTypeDescriptor` is no longer needed because we don't directly find the descriptor from files anymore. I removed it in [03aea23](https://github.com/line/armeria/pull/4641/commits/03aea2307fac79a1183acce6abcbe75db6ad2a94)

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java [hunk 2]
```diff
@@ -347,16 +345,7 @@ private static Map<String, Field> buildFields(Descriptor desc,
                                 .filter(d -> d.getFullName().equals(field.getMessageType().getFullName()))
                                 .findFirst().orElse(null);
                     if (typeDesc == null) {
```
Comment (ikhoon) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:347]: Should we also remove `desc.getNestedTypes().stream()...` block?
It seems we directly assign `typeDesc` from `field.getMessageType()` without `@Nullable`.

**Review by minwoox — APPROVED** [review]
LGTM, once @ikhoon's comment is addressed.
Thanks! 😄

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java (hunk 2 above)
Comment (jrhee17) [reply grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:347]: +1

**Review by jrhee17 — APPROVED** [review]
https://github.com/line/armeria/pull/4641/files#r1091507951

Changes look good to me once @ikhoon 's comment is addressed 👍

**Review by ikhoon — APPROVED** [review]
Thanks always! 🙇‍♂️🙇‍♂️
