### PR TITLE
Publish stream events before calling `RequestLogBuilder`

### LINKED ISSUE #2830: 'You tried to set the content preview twice' warning on a client with one preview decorator
We got a report from an internal user:

```
You tried to set the content preview twice: ... 
Did you apply content previewing decorator more than once?
```

Not enough information at the moment to reproduce the problem, but just for the record. 😄 

It seems like the client is decorated with `RetryingClient`, too.

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

We currently call `RequestLogBuilder` methods even before publishing
stream events (`StreamMesssage.write/close/abort()`) in some places,
such as `HttpResponseDecoder`. This can be a problem because the
callbacks added to the `RequestLog` may be invoked even before any
stream events are published.

For example, `HttpResponseDecoder` may fail to publish the received
`ResponseHeaders` when a `RequestLog` callback aborts the response
even before the publication, leading to the following exception:

    io.netty.handler.codec.http2.Http2Exception: failed to consume a HEADERS frame
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:117)
        at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:206)
        at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:219)
        ...
    Caused by: com.linecorp.armeria.common.stream.ClosedStreamException: null
        at com.linecorp.armeria.common.stream.ClosedStreamException.get(ClosedStreamException.java:37)
        at com.linecorp.armeria.common.stream.StreamWriter.write(StreamWriter.java:72)
        at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:203)
        ... 40 common frames omitted

Modifications:

- Add a generalized mechanism to defer any `RequestLogProperty`:
  - `isDeferred(RequestLogProperty)`
  - `defer(RequestLogProperty)`
  - `defer*Content*()` and `isDefer*Content*Set()` have been deprecated.
- Defer setting some log properties before publishing stream events,
  so that they are recorded after the publication.
- Miscellaneous:
  - Do not warn unnecessarily when propagating content previews in
    `DefaultRequestLog.propagate*()`.
  - Make `HttpClientMaxConcurrentStreamTest.exceededMaxStreamsPropagatesFailureCorrectly()`
    less flaky.
  - Optimize `DefaultRequestLog.isAvailable()`

Result:

- No more `Http2Exception: failed to consume a HEADERS frame` error.
- No more `You tried to set the content preview twice` warning.
  - Fixes #2830
- Slightly faster `RequestLogAccess.isAvailable()` implementation.
- (Deprecation) `RequestLogBuilder.defer*Content*()` and
  `isDefer*Content*Set()` have been deprecated in favor of
  `defer(RequestLogProperty)` and `isDeferred(RequestLogProperty)`.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java [hunk 1]
```diff
@@ -248,16 +248,16 @@ private void runThreadLocalContextCustomizers() {
...
-        final RequestLogBuilder logBuilder = logBuilder();
         final UnprocessedRequestException wrapped = new UnprocessedRequestException(cause);
-        logBuilder.endRequest(wrapped);
-        logBuilder.endResponse(wrapped);
-
         final HttpRequest req = request();
         if (req != null) {
             autoFillSchemeAndAuthority();
-            req.abort(cause);
+            req.abort(wrapped);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:255]: Not sure why it was `cause` before. 🤔

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:255]: It seems my mistake. 😱

File: core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java [hunk 2]
```diff
@@ -199,50 +200,73 @@ public boolean isOpen() {
...
+            }
+
+            assert o instanceof HttpHeaders && !(o instanceof RequestHeaders) : o;
+
+            if (o instanceof ResponseHeaders) {
+                final ResponseHeaders headers = (ResponseHeaders) o;
+                final HttpStatus status = headers.status();
+                if (!status.isInformational()) {
+                    state = State.WAIT_DATA_OR_TRAILERS;
+                    if (ctx != null) {
```
Comment (hexoul) [inline core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:237]: It seems unnecessary because of pre-checked condition. https://github.com/line/armeria/pull/2832/files#diff-833e9abb4a1607339097e0e3aab8b26dR226

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:237]: I don't think so because we didn't bail out when `ctx == null`.

Comment (hexoul) [reply core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:237]: Oops sorry I misread. Please ignore this.

File: core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java (hunk 1 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java:255]: I think it didn't do any harm anyways. 😆 
First appeared at: https://github.com/line/armeria/pull/2248/files#diff-d437ddb5e0b4572dba776949bacf9becR233

File: core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java (hunk 2 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java:237]: No worries. I appreciate that you review our work! 🙇

File: core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java [hunk 3]
```diff
@@ -187,26 +188,60 @@ private static boolean isComplete(int flags) {
...
+
+    @Override
+    public boolean isAvailable(Iterable<RequestLogProperty> properties) {
+        requireNonNull(properties, "properties");
+        final int flags = interestedFlags(properties);
+        checkArgument(flags != 0, "properties is empty.");
+        return isAvailable(flags);
     }
 
     private boolean isAvailable(int interestedFlags) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:215]: nit: can remove this method and just call `hasInterestedFlags` directly?

File: core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java [hunk 4]
```diff
@@ -1223,15 +1276,20 @@ public String responseContentPreview() {
...
+        responseContentPreview(responseContentPreview, true);
+    }
+
+    private void responseContentPreview(@Nullable String responseContentPreview, boolean warnIfSetAlready) {
         if (isAvailable(RequestLogProperty.RESPONSE_CONTENT_PREVIEW)) {
-            if (!warnedSettingContentPreviewTwice && responseContentPreview != null) {
+            if (warnIfSetAlready && responseContentPreview != null && !warnedSettingContentPreviewTwice) {
                 warnedSettingContentPreviewTwice = true;
-                logger.warn("You tried to set the content preview twice: {} " +
+                logger.warn("You tried to set the response content preview twice: {} " +
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:1286]: Thanks, I needed it.

File: core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java (hunk 3 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:215]: I guess it's better keeping it for readability - `isAvailable(interestedFlags)` vs. `hasInterestedFlags(this.flags, interestedFlags)`.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:215]: SGTM. 😄

File: core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java [hunk 5]
```diff
@@ -982,8 +1040,8 @@ private void endRequest0(@Nullable Throwable requestCause, long requestEndTimeNa
 
         // Set names if request content is not deferred or it was deferred but has been set
         // before the request completion.
-        if (!isDeferRequestContentSet() ||
-            (isDeferRequestContentSet() && isAvailable(RequestLogProperty.REQUEST_CONTENT))) {
+        if (!hasInterestedFlags(deferredFlags, RequestLogProperty.REQUEST_CONTENT) ||
+            isAvailable(RequestLogProperty.REQUEST_CONTENT)) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java:1044]: 👍
