### PR TITLE
Make sure all safely retriable exceptions are wrapped by UnprocessedR…

### LINKED ISSUE #1653: Change to return UnprocessedRequestException in RetryingClient
When `RetryingClient` sets the timeout, it completes `HttpResponse` with `ResponseTimeoutException` if it passes the timeout deadline.
It makes sense if `RetryingClient` reaches that point after several retries, but it wouldn't make sense when it couldn't even connect to the endpoint and reached the timeout due to heavy jobs in decorator, etc.

### PR DESCRIPTION
**Pull request by ikhoon**
…equestException

Motivation:
`UnprocessedRequestException` means that the request has not been processed by the server.
If we wrap socket connect failures and more with UnprocessedRequestException,
user can safely retry the request without worrying about the idempotency of the request.

Modification:
* Add `GoAwayReceivedException` which raised when a server sent an HTTP/2 GOAWAY.
* Add `RefusedStreamException` which raised when a server set MAX_Current_STREAM to 0.
  see httpwg.org/specs/rfc7540.html#SETTINGS_MAX_CONCURRENT_STREAMS
* Remove singleton `INSTANCE` of `UnprocessedRequestException` and add a new constructor
  which accepts `Throwable` to make sure `UnprocessedRequestExecepion` always has a cause.
* Change `ResponseTimeoutException.get()` to
  `new UnprocessedRequestException(RequestTimeoutException.get())` in ConcurrencyLimitingClient.
* Change `UnprocessedRequestException.get()` to `NullPointerException`
  when sessionProtocol is null in `HttpClientDelegate#doExecute`.

Result:
* We can get more retriable exceptions.

Fixes #1653

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java [hunk 1]
```diff
@@ -202,11 +202,13 @@ private void doExecute(PooledChannel pooledChannel, ClientRequestContext ctx,
...
             res.init(session.inboundTrafficController());
             final SessionProtocol sessionProtocol = session.protocol();
+
+            // Should never reach here.
             if (sessionProtocol == null) {
                 needsRelease = false;
                 try {
                     // TODO(minwoox): Make a test that handles this case
-                    final UnprocessedRequestException cause = UnprocessedRequestException.get();
+                    final NullPointerException cause = new NullPointerException("sessionProtocol");
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java]: I changed this into NullPointerException because it is abnormal behavior and not a retriable case.

File: core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
+ * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+ * License for the specific language governing permissions and limitations
+ * under the License.
+ */
+
+package com.linecorp.armeria.client;
+
+/**
+ * A {@link RuntimeException} raised when a server set MAX_CONCURRENT_STREAMS to 0,
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java]: `HTTP/2 <a href="https://httpwg.org/specs/rfc7540.html#SETTINGS_MAX_CONCURRENT_STREAMS">{@code MAX_CONCURRENT_STREAMS}</a>`

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java [hunk 3]
```diff
@@ -29,19 +29,26 @@
...
-
     /**
-     * Returns an {@link UnprocessedRequestException} which may be a singleton or a new instance, depending on
-     * whether {@linkplain Flags#verboseExceptions() the verbose exception mode} is enabled.
+     * Creates a new instance with the specified {@code message} and {@code cause}.
      */
-    public static UnprocessedRequestException get() {
-        return Flags.verboseExceptions() ? new UnprocessedRequestException() : INSTANCE;
+    public UnprocessedRequestException(@Nullable String message, @Nullable Throwable cause) {
+        super(message, cause);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: Set `false` to `writableStackTrace` if `Flags.verboseExceptions()` is `false`.

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java [hunk 4]
```diff
@@ -29,19 +29,26 @@
...
     }
 
-    private UnprocessedRequestException() {}
+    /**
+     * Creates a new instance with the specified {@code cause}.
+     */
+    public UnprocessedRequestException(@Nullable Throwable cause) {
+        super(cause);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: Set `false` to `writableStackTrace` if `Flags.verboseExceptions()` is `false`.

File: core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingExceedException.java [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+ * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+ * License for the specific language governing permissions and limitations
+ * under the License.
+ */
+
+package com.linecorp.armeria.client.limit;
+
+/**
+ * A {@link RuntimeException} raised when {@link ConcurrencyLimitingClient#numActiveRequests()} exceeds
+ * the configured {@code maxConcurrency}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingExceedException.java]: It's impossible to exceed the max concurrency with `ConcurrencyLimitingClient`. The exception is raised only when the client was not able to send a request until it reaches at the timeout. Could you rename this class and rephrase the Javadoc?

File: core/src/main/java/com/linecorp/armeria/internal/InboundTrafficController.java [hunk 6]
```diff
@@ -82,7 +82,7 @@ public void inc(int numProducedBytes) {
     public void dec(int numConsumedBytes) {
         final int oldValue = getAndAdd(-numConsumedBytes);
         if (oldValue > lowWatermark && oldValue - numConsumedBytes <= lowWatermark) {
-            // Just went below high watermark
+            // Just went below low watermark
```
[the remark this answers is not in the document]
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/InboundTrafficController.java]: Thanks!

File: core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java [hunk 7]
```diff
@@ -22,10 +22,9 @@
 import com.linecorp.armeria.common.HttpHeaders;
 import com.linecorp.armeria.common.Request;
 import com.linecorp.armeria.common.RequestContextWrapper;
-import com.linecorp.armeria.server.ServiceRequestContext;
 
 /**
- * Wraps an existing {@link ServiceRequestContext}.
+ * Wraps an existing {@link ClientRequestContext}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java]: Thanks!

File: core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java [hunk 8]
```diff
@@ -391,7 +392,8 @@ private void notifyConnect(SessionProtocol desiredProtocol, PoolKey key, Future<
                 final SessionProtocol protocol = getProtocolIfHealthy(channel);
                 if (closed || protocol == null) {
                     channel.close();
-                    promise.completeExceptionally(UnprocessedRequestException.get());
+                    promise.completeExceptionally(
+                            new UnprocessedRequestException(ClosedSessionException.get()));
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java]: There are two more `completeExceptionally()` methods below in this method you need to take care of.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java]: Thanks! I wrapped below exception with UnprocessedRequestException.  :-)

File: core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java (hunk 2 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java]: I updated the link.

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java (hunk 4 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: I overrided `fillInStackTrace` for verbose Exception. Is it workaround?
```java
@Override
public Throwable fillInStackTrace() {
    if (Flags.verboseExceptions()) {
        super.fillInStackTrace();
    }
    return this;
}
```

File: core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingExceedException.java (hunk 5 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingExceedException.java]: The `ConcurrencyLimitingExceedException` is changed into `PendingRequestTimeoutException`. What do you think about this name? 🧐

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingExceedException.java]: I like the new name. :+1:

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java [hunk 9]
```diff
@@ -29,19 +34,31 @@
...
-    public static UnprocessedRequestException get() {
-        return Flags.verboseExceptions() ? new UnprocessedRequestException() : INSTANCE;
+    public UnprocessedRequestException(Throwable cause) {
+        super(requireNonNull(cause, "cause"));
     }
 
-    private UnprocessedRequestException() {}
+    @Nonnull
+    @Override
+    public synchronized Throwable getCause() {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: `synchronized` is unnecessary because `super.getCause()` is already synchronized, i.e.

```java
public Throwable getCause() {
    synchronized (this) {
        // return super.getCause() is actually:
        synchronized (this) {
            return (cause==this ? null : cause)
        }
    }
}
```

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java (hunk 4 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: I think it's good as it is. The use of 4-arg constructor is mainly useful when we want to prevent overriding the stack trace or adding suppressed exceptions, i.e. when we want to make an exception a stateless singleton. For `UnprocessedRequestException`, that's not the case, so it's just enough to override `fillInStackTrace()`.

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java [hunk 10]
```diff
@@ -29,19 +34,31 @@
...
 
     /**
-     * Returns an {@link UnprocessedRequestException} which may be a singleton or a new instance, depending on
-     * whether {@linkplain Flags#verboseExceptions() the verbose exception mode} is enabled.
+     * Creates a new instance with the specified {@code cause}.
      */
-    public static UnprocessedRequestException get() {
-        return Flags.verboseExceptions() ? new UnprocessedRequestException() : INSTANCE;
+    public UnprocessedRequestException(Throwable cause) {
+        super(requireNonNull(cause, "cause"));
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: How about passing the string representation of cause as a message?

    super(requireNonNull(cause, "cause").toString(), cause);

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java (hunk 4 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: @trustin Thanks for your kind explanation. 🙏

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java (hunk 9 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: I didn't think of that. Thanks.

File: core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java (hunk 10 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java]: It looks better than the null message. Thanks for all of your nice and gentle feedback. 😁

File: core/src/main/java/com/linecorp/armeria/client/GoAwayReceivedException.java [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
+ * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+ * License for the specific language governing permissions and limitations
+ * under the License.
+ */
+
+package com.linecorp.armeria.client;
+
+/**
+ * A {@link RuntimeException} raised when a server sent an HTTP/2 GOAWAY frame with
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/GoAwayReceivedException.java]: One last nit: How about adding hyperlink to `HTTP/2 GOAWAY frame`?

**Comment by trustin** [comment]
@ikhoon Could you update the PR description?

**Comment by ikhoon** [comment]
@trustin Sure, I will update the PR about the changes soon.

**Comment by ikhoon** [comment]
The squash commit message was updated and PR description was also updated with that.

File: core/src/main/java/com/linecorp/armeria/client/GoAwayReceivedException.java (hunk 11 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/GoAwayReceivedException.java]: Thanks for addressing that! After I saw your other review about javadoc. I have the same idea.

**Comment by trustin** [comment]
@minwoox Any other comments?
