### PR TITLE
Fix a bug where a trailing dot in a host is stripped

### LINKED ISSUE #4538: Trailing dot in domain names is stripped causing search domains to be used
When executing requests against domain names such as `x.com.` (note the dot in the end), Armeria strips the trailing dot [here](https://github.com/line/armeria/blob/27f1d605bea0874bf0bd68962f5e405812ba55fd/core/src/main/java/com/linecorp/armeria/client/Endpoint.java#L125).
As a result search domains are being attempted.
The `.` should be preserved so that DNS resolution treats the domain name as an FQDN.

### PR DESCRIPTION
**Pull request by ikhoon**
Related issue: #4538

Motivation:

A [trailing dot](http://www.dns-sd.org/trailingdotsindomainnames.html) in a request URI is stripped when it is converted into an `Endpoint`. Because `Endpoint` uses Guava's `InternetDomainName` to normalize a host. `InternetDomainName` removes a trailing dot during the normalization process. https://github.com/google/guava/blob/4aaebca4e1f05891ec8e5ff0183cdde9894815f3/guava/src/com/google/common/net/InternetDomainName.java#L136 https://github.com/line/armeria/blob/fee87f8da942d0e6343e814489524b73db60ef3b/core/src/main/java/com/linecorp/armeria/client/Endpoint.java#L156

As a result, a URL containing a trailing dot such as `foo.com.` is converted into `foo.com` and then the DNS resolver uses search domains to find available DNS records for `foo.com`.

Modifications:

- Revive a tailing dot stripped from a host while normalized.
- Strip a tailing dot if a host is converted into an authority.
- Use `Endpoint.toSocketAddress(-1)` to connect to the remote peer.

Result:

- Search domains are no longer used in DNS resolution if an authority ends with a trailing dot. 
- Fixes #4538

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/Endpoint.java [hunk 1]
```diff
@@ -231,12 +237,15 @@ private static String generateAuthority(String host, int port, HostType hostType
...
+                                           int weight, HostType hostType, boolean hasTrailingDot) {
         try (TemporaryThreadLocals tempThreadLocals = TemporaryThreadLocals.acquire()) {
             final StringBuilder buf = tempThreadLocals.stringBuilder();
             buf.append("Endpoint{").append(authority);
+            if (hasTrailingDot) {
+                buf.append('.');
+            }
             if (hostType == HostType.HOSTNAME_AND_IPv4 ||
-                hostType == HostType.HOSTNAME_AND_IPv6) {
+                    hostType == HostType.HOSTNAME_AND_IPv6) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/Endpoint.java:248]: nit: revert?

File: core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java [hunk 2]
```diff
@@ -131,10 +131,15 @@ private void resolveAddress(Endpoint endpoint, ClientRequestContext ctx,
         // IP address has not been resolved yet.
         assert !endpoint.hasIpAddr() && endpoint.hasPort();
 
+        // TODO(ikhoon): Add test codes to verify that the trailing dot is preserved when sending DNS queries.
+        String host = endpoint.host();
+        if (endpoint.hasTrailingDot()) {
+            host = endpoint.host() + '.';
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java:137]: nit: 
```suggestion
            host += '.';
```

File: core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
+package com.linecorp.armeria.client;
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java:1]: nit: copyright?

File: core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+    @RegisterExtension
+    static ServerExtension server = new ServerExtension() {
+        @Override
+        protected void configure(ServerBuilder sb) {
+            sb.service("/", (ctx, req) -> HttpResponse.of("Hello, world!"));
+        }
+    };
+
+    private static class DnsRecordCaptor extends ChannelInboundHandlerAdapter {
+        private Queue<DnsRecord> records = new LinkedBlockingDeque<>();
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java:43]: nit:
```suggestion
        private final Queue<DnsRecord> records = new LinkedBlockingDeque<>();
```

File: core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+            super.channelRead(ctx, msg);
+        }
+    }
+
+    @Test
+    void resolve() throws Exception {
+        final DnsRecordCaptor dnsRecordCaptor = new DnsRecordCaptor();
+        try (TestDnsServer dnsServer = new TestDnsServer(ImmutableMap.of(
+                new DefaultDnsQuestion("foo.com.", A),
+                new DefaultDnsResponse(0).addRecord(ANSWER, newAddressRecord("foo.com.", "127.0.0.1"))), dnsRecordCaptor)) {
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java:61]: nit: line length

**Review by minwoox — APPROVED** [review]
Left minor comments. Thanks! 😄

File: core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java (hunk 3 above)
Comment (ikhoon) [reply core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java:1]: What's wrong with my IDE settings. 😵‍💫

**Comment by ikhoon** [comment]
I will update `Endpoint` after #4846 is merged.

File: core/src/main/java/com/linecorp/armeria/client/Endpoint.java [hunk 6]
```diff
@@ -149,13 +149,17 @@ private static Endpoint create(String host, int port, boolean validateHost) {
...
 
+        boolean hasTrailingDot = false;
         if (validateHost) {
+            if (host.endsWith(".")) {
+                hasTrailingDot = true;
+            }
             host = InternetDomainName.from(host).toString();
         }
-        return new Endpoint(host, null, port, DEFAULT_WEIGHT, HostType.HOSTNAME_ONLY, null);
+        return new Endpoint(host, null, port, DEFAULT_WEIGHT, HostType.HOSTNAME_ONLY, null, hasTrailingDot);
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/client/Endpoint.java:162]: Not strong on this, but `hasTrailingDot` seems to imply that `host` ends with a dot. (it is possible that `host` ends with a dot but `hasTrailingDot == false` if `validateHost == false`

```suggestion
        return new Endpoint(host, null, port, DEFAULT_WEIGHT, HostType.HOSTNAME_ONLY, null, implicitTrailingDot);
```

File: core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+import io.netty.handler.codec.dns.DefaultDnsQuestion;
+import io.netty.handler.codec.dns.DefaultDnsResponse;
+import io.netty.handler.codec.dns.DnsRecord;
+import io.netty.handler.codec.dns.DnsSection;
+import io.netty.util.ReferenceCountUtil;
+
+class TrailingDotAddressResolverTest {
+
+    @RegisterExtension
+    static final EventLoopExtension eventLoopExtension = new EventLoopExtension();
```
Comment (jrhee17) [inline core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java:52]: Q) Is this ever used?

**Review by jrhee17 — COMMENTED** [review]
Mostly looking good 👍  Let me wait for the updated version before approving 🙇

File: core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java (hunk 7 above)
Comment (ikhoon) [reply core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java:52]: Nope. It is cruft. 😅

File: core/src/main/java/com/linecorp/armeria/client/Endpoint.java (hunk 6 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/Endpoint.java]: I removed `hasTrailingDot()` getter and the field name has been changed to `wasTrailingDotStripped`. The stripped training dot will be recovered when it is converted to a `SocketAddress` via `.toSocketAddress(int)`.

**Comment by ikhoon** [comment]
All conflicts have been resolved and used `.toSocketAddress(-)`, which was added in #4846, to recover the stripped trailing dot. PTAL

File: core/src/main/java/com/linecorp/armeria/client/Endpoint.java [hunk 8]
```diff
@@ -377,13 +384,19 @@ public Endpoint withHost(String host) {
...
+                                weight, attributes, false);
         } else if (isDomainSocketAuthority(host)) {
             return new Endpoint(Type.DOMAIN_SOCKET, host, DOMAIN_SOCKET_IP, DOMAIN_SOCKET_PORT,
-                                weight, attributes);
+                                weight, attributes, false);
         } else {
+            boolean hasTrailingDot = false;
+            if (host.endsWith(".")) {
+                hasTrailingDot = true;
+            }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/Endpoint.java:396]:
```suggestion
            final boolean hasTrailingDot = host.endsWith(".");
```
.. or you could even just inline it because it's used only once.

**Review by trustin — COMMENTED** [review]
What do you think about retaining the trailing dot in `Endpoint.host` and strip it only for `Endpoint.authority`?

File: core/src/main/java/com/linecorp/armeria/client/Endpoint.java [hunk 9]
```diff
@@ -377,11 +387,17 @@ public Endpoint withHost(String host) {
...
+                                weight, attributes);
         } else if (isDomainSocketAuthority(host)) {
             return new Endpoint(Type.DOMAIN_SOCKET, host, DOMAIN_SOCKET_IP, DOMAIN_SOCKET_PORT,
                                 weight, attributes);
         } else {
+            final boolean hasTrailingDot = host.endsWith(".");
+            host = InternetDomainName.from(host).toString();
+            if (hasTrailingDot) {
+                host += '.';
+            }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/client/Endpoint.java:400]: Deduplicate?

File: core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+
+    private static class DnsRecordCaptor extends ChannelInboundHandlerAdapter {
+        private final Queue<DnsRecord> records = new LinkedBlockingDeque<>();
+
+        @Override
+        public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
+            if (msg instanceof DatagramDnsQuery) {
+                final DatagramDnsQuery dnsQuery = (DatagramDnsQuery) msg;
+                final DnsRecord dnsRecord = dnsQuery.recordAt(DnsSection.QUESTION, 0);
+                records.add(ByteArrayDnsRecord.copyOf(ReferenceCountUtil.retain(dnsRecord)));
```
Comment (jrhee17) [inline core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java:66]: for other reviewers: double checked blockhound whitelisted this

**Review by jrhee17 — APPROVED** [review]
Looks good! Thanks @ikhoon 🙇 👍 🙇

**Review by trustin — APPROVED** [review]
Great job, @ikhoon! :bow:
