### PR TITLE
Fixed compatibility with logback SocketAppender

### LINKED ISSUE #4546: RequestContextExportingAppender incompatible with ch.qos.logback.classic.net.SocketAppender
Adding at least one `<export>` tag to `RequestContextExportingAppender` causes exception and connection loss when using `SocketAppender`.

Example `logback-spring.xml`:
```xml
    <appender name="REMOTE" class="ch.qos.logback.classic.net.SocketAppender">
        <remoteHost>localhost</remoteHost>
        <port>6810</port>
        <reconnectionDelay>10000</reconnectionDelay>
        <eventDelayLimit>1000</eventDelayLimit>
        <includeCallerData>false</includeCallerData>
    </appender>

    <appender name="REMOTE_RCEA" class="com.linecorp.armeria.common.logback.RequestContextExportingAppender">
        <appender-ref ref="REMOTE"/>
        <export>correlation.id=req.headers.correlation-id</export>
    </appender>
```

The problem is in logback's `LoggingEventPreSerializationTransformer`, which is trying to check event type and make `LoggingEventVO` of it:
```java
public Serializable transform(ILoggingEvent event) {
        if (event == null) {
            return null;
        }
        if (event instanceof LoggingEvent) {
            return LoggingEventVO.build(event);
        } else if (event instanceof LoggingEventVO) {
            return (LoggingEventVO) event;
        } else {
            throw new IllegalArgumentException("Unsupported type " + event.getClass().getName());
        }
    }
```
but `LoggingEventWrapper` only implements `ILoggingEvent` and doesn't extend `LoggingEvent`.

After fixing that issue we will get `InvalidClassException: Unauthorized deserialization attempt` in `HardenedObjectInputStream`.

Second problem is in the way `LoggingEventWrapper` is created. `RequestContextExportingAppender` passes to `LoggingEventWrapper.append(..)` its own type (exporter.export() creates `RequestContextExporter$State`) as propertiesMap, which is then can't be accepted by logback because of classes whiltelist check. 
```
        final Map<String, String> contextMap = exporter.export();
        if (!contextMap.isEmpty()) {
            final Map<String, String> originalMdcMap = eventObject.getMDCPropertyMap();
            final Map<String, String> mdcMap;

            if (!originalMdcMap.isEmpty()) {
                mdcMap = new UnionMap<>(contextMap, originalMdcMap);
            } else {
                mdcMap = contextMap;
            }
            eventObject = new LoggingEventWrapper(eventObject, mdcMap);
        }
```
So, its need to be replaced with one of java.util classes like HashMap.

### PR DESCRIPTION
**Pull request by Yuri999**
Motivation:

`RequestContextExportingAppender` when using with logback `SocketAppender` has following bugs:

- `LoggingEventWrapper` does not extend `LoggingEvent`
- mdcMap object passed to `LoggingEventWrapper` can't be accepted by logback because of it's type

Modifications:

- changed `LoggingEventWrapper` parent type from interface `ILoggingEvent` to class `LoggingEvent`
- changed type of object passed as mdcMap to `LoggingEventWrapper` from `RequestContextExporter$State` to `java.util.HashMap`
- deleted `UnionMap` which is not used anymore

Result:

- Closes #4546
- `RequestContextExportingAppender` can now be used with logback `SocketAppender`

### CODE REVIEW

**Comment by ikhoon** [comment]
Would you mind adding unit tests for the changes?

**Comment by Yuri999** [comment]
> Would you mind adding unit tests for the changes?

I've added a few tests and also changed logic in `SocketAppenderWrapper.doAppend()`

File: logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java [hunk 1]
```diff
@@ -229,7 +226,11 @@ public void stop() {
 
     @Override
     public void addAppender(Appender<ILoggingEvent> newAppender) {
-        aai.addAppender(newAppender);
+        if (newAppender instanceof AbstractSocketAppender) {
```
Comment (ikhoon) [inline logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java:229]: `AbstractSocketAppender` approach looks like a general solution and can isolate the customizing logic to it. But it wouldn't be efficient since both `UnionMap` and `HashMap` are created for `AbstractSocketAppender`. How about adding a flag for whether to use `HashMap` or not? For example:
```java
private boolean needsHashMap;

public void addAppender(Appender<ILoggingEvent> newAppender) {
    if (newAppender instanceof AbstractSocketAppender) {
       needsHashMap = true;
    }
    ...
}

protected void append(ILoggingEvent eventObject) {
    if (needsHashMap) {
        mdcMap = new HashMap<>(contextMap);
        // mdcMap values can be overridden by originalMdcMap
        mdcMap.putAll(originalMdcMap);
    } else {
        mdcMap = new UnionMap<>(contextMap, originalMdcMap);
    }
```

File: logback/src/main/java/com/linecorp/armeria/common/logback/LoggingEventWrapper.java [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+import org.slf4j.Marker;
+
+import com.linecorp.armeria.common.annotation.Nullable;
+
+import ch.qos.logback.classic.Level;
+import ch.qos.logback.classic.spi.ILoggingEvent;
+import ch.qos.logback.classic.spi.IThrowableProxy;
+import ch.qos.logback.classic.spi.LoggerContextVO;
+
+final class LoggingEventWrapper implements ILoggingEvent {
```
Comment (ikhoon) [inline logback/src/main/java/com/linecorp/armeria/common/logback/LoggingEventWrapper.java:29]: If Logback maintainers are not interested in https://github.com/qos-ch/logback/pull/614,
I'm OK to extend `LoggingEvent` with some TODO.
```
// TODO(ikhoon): Use `ILoggingEvent` instead of `LoggingEvent` once https://github.com/qos-ch/logback/pull/614 is merged.
```

File: logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java (hunk 1 above)
Comment (Yuri999) [reply logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java:241]: Yeah, I agree. There's no point to create `UnionMap` and then create `HashMap` of it. I've fixed this.

File: logback/src/main/java/com/linecorp/armeria/common/logback/LoggingEventWrapper.java (hunk 2 above)
Comment (Yuri999) [reply logback/src/main/java/com/linecorp/armeria/common/logback/LoggingEventWrapper.java]: Nice!

File: logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java [hunk 3]
```diff
@@ -229,6 +238,9 @@ public void stop() {
 
     @Override
     public void addAppender(Appender<ILoggingEvent> newAppender) {
+        if (newAppender instanceof AbstractSocketAppender) {
+            needsHashMap = true;
```
Comment (minwoox) [inline logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java:242]: Could you leave a comment that we discussed why we use the `HashMap` and link to the whitelist check?

File: logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java [hunk 4]
```diff
@@ -592,6 +595,75 @@ void testResponseCause() throws Exception {
...
+        final ClientRequestContext ctx = newClientContext("/bar", null);
+        try (SafeCloseable ignored = ctx.push()) {
+            final Integer value = ThreadLocalRandom.current().nextInt();
+            testLogger.trace("{}", value);
+
+            final ArgumentCaptor<ILoggingEvent> eventCaptor = ArgumentCaptor.forClass(ILoggingEvent.class);
+            verify(sa).doAppend(eventCaptor.capture());
+
+            final Map<String, String> mdc = eventCaptor.getValue().getMDCPropertyMap();
+            assertThat(mdc.getClass().getName()).startsWith("java.util");
```
Comment (minwoox) [inline logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java:640]: How about..
```suggestion
            assertThat(mdc).isInstanceOf(HashMap.class);
```
to make it clearer?

File: logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java [hunk 5]
```diff
@@ -592,6 +595,75 @@ void testResponseCause() throws Exception {
...
+            final Integer value = ThreadLocalRandom.current().nextInt();
+            MDC.put("test-prop", "override-test");
+            MDC.put("another-prop", "another-value");
+            testLogger.trace("{}", value);
+
+            final ArgumentCaptor<ILoggingEvent> eventCaptor = ArgumentCaptor.forClass(ILoggingEvent.class);
+            verify(sa).doAppend(eventCaptor.capture());
+
+            final Map<String, String> mdc = eventCaptor.getValue().getMDCPropertyMap();
+            assertThat(mdc.getClass().getName()).startsWith("java.util");
```
Comment (minwoox) [inline logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java:660]: ditto

File: logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java [hunk 6]
```diff
@@ -198,16 +197,26 @@ protected void append(ILoggingEvent eventObject) {
...
-            final Map<String, String> mdcMap;
+            final Map<String, String> mdcMap = prepareMdcMap(contextMap, originalMdcMap);
+            eventObject = new LoggingEventWrapper(eventObject, mdcMap);
+        }
+        aai.appendLoopOnAppenders(eventObject);
+    }
 
+    private Map<String, String> prepareMdcMap(Map<String, String> contextMap,
+                                              Map<String, String> originalMdcMap) {
+        final Map<String, String> mdcMap;
```
Comment (minwoox) [inline logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java:208]: How about using early return?
```java
if (needsHashMap) {
    final Map<String, String> mdcMap = new HashMap<>(contextMap);
    mdcMap.putAll(originalMdcMap);
    return mdcMap;
}
if (!originalMdcMap.isEmpty()) {
    return new UnionMap<>(contextMap, originalMdcMap);
}
return contextMap;
```

**Review by minwoox — COMMENTED** [review]
Thanks for fixing the bug. 
Left minor comments. 😄

**Review by ikhoon — APPROVED** [review]
Thanks a lot, @Yuri999! 🚀
Please address other comments. 🙇‍♂️

**Comment by Yuri999** [comment]
@ikhoon @minwoox 
I'm going to change `addAppender` logic, because `SocketAppender` can be wrapped in `AsyncAppender`.

```java
    @Override
    public void addAppender(Appender<ILoggingEvent> newAppender) {
        needsHashMap = isSocketAppender(newAppender);
        aai.addAppender(newAppender);
    }

    @SuppressWarnings("unchecked")
    private boolean isSocketAppender(Appender<ILoggingEvent> appender) {
        if (appender instanceof AppenderAttachable) {
            boolean result = false;
            for (Iterator<Appender<ILoggingEvent>> i = ((AppenderAttachable<ILoggingEvent>) appender)
                    .iteratorForAppenders(); i.hasNext();) {
                final Appender<ILoggingEvent> nested = i.next();
                result = result || isSocketAppender(nested);
            }
            return result;
        }

        return appender instanceof AbstractSocketAppender;
    }
```
What do you think? In my production code `AsyncAppender` is used.

File: logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java (hunk 3 above)
Comment (Yuri999) [reply logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java:242]: done

File: logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java (hunk 4 above)
Comment (Yuri999) [reply logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java]: ok

File: logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java (hunk 6 above)
Comment (Yuri999) [reply logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java]: looks good

File: logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java [hunk 7]
```diff
@@ -229,9 +235,28 @@ public void stop() {
...
+            boolean result = false;
+            for (Iterator<Appender<ILoggingEvent>> i = ((AppenderAttachable<ILoggingEvent>) appender)
+                    .iteratorForAppenders(); i.hasNext();) {
+                final Appender<ILoggingEvent> nested = i.next();
+                result = result || isSocketAppender(nested);
+            }
+            return result;
+        }
+
+        return appender instanceof AbstractSocketAppender;
```
Comment (minwoox) [inline logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java:257]: Let's do the cheap operation first:
```suggestion
        if (appender instanceof AbstractSocketAppender) {
            return true;
        }
        if (appender instanceof AppenderAttachable) {
            for (final Iterator<Appender<ILoggingEvent>> i = ((AppenderAttachable<ILoggingEvent>) appender)
                    .iteratorForAppenders(); i.hasNext();) {
                if (isSocketAppender(i.next())) {
                    return true;
                }
            }
        }

        return false;
```

Comment (Yuri999) [reply logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java]: you an expert in early returns :) fixed, thanks.

Comment (minwoox) [reply logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java]: 🤣

**Comment by ikhoon** [comment]
Still look good to me. Thanks for the high-quality work!

**Comment by ikhoon** [comment]
@Yuri999 Would you mind checking the test failure?
```
RequestContextExportingAppenderTest > testMdcPropsTypeForSocketAppenderWithPropsAndContext() FAILED
    Wanted but not invoked:
    socketAppender.doAppend(
        <Capturing argument>
    );
    -> at com.linecorp.armeria.common.logback.RequestContextExportingAppenderTest.testMdcPropsTypeForSocketAppenderWithPropsAndContext(RequestContextExportingAppenderTest.java:661)

    However, there were exactly 2 interactions with this mock:
    socketAppender.getName();
    -> at **ch.qos.logback.core.AsyncAppenderBase.addAppender(AsyncAppenderBase.java:248)**
```

**Comment by minwoox** [comment]
Great job, @Yuri999! 🎉 🎉 🎉
