### PR TITLE
Fix buffer leak in the UnaryGrpcClient

### LINKED ISSUE #3733: Potential buffer leak in `UnaryGrpcClient`
Found this leak at https://github.com/line/armeria/runs/3208178703#step:6:2887 while building fcd2d72a73218a3dda4c2c89f4908ec1ad12d810:

@alexc-db Could you take a look? You probably will be able to reproduce by building with `-Pleak` option, which enables expensive leak tracking.

```
17:32:38.374 [armeria-common-worker-epoll-2-3] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.buffer.AbstractPooledDerivedByteBuf.deallocate(AbstractPooledDerivedByteBuf.java:86)
	io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:110)
	io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
	io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:1037)
	io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:102)
	io.netty.buffer.AdvancedLeakAwareByteBuf.release(AdvancedLeakAwareByteBuf.java:941)
	com.linecorp.armeria.common.ByteBufHttpData.close(ByteBufHttpData.java:256)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onError(UnaryGrpcClient.java:256)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onNext(UnaryGrpcClient.java:242)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onNext(UnaryGrpcClient.java:204)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:417)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:395)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:263)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readInt(AdvancedLeakAwareByteBuf.java:436)
	com.linecorp.armeria.internal.common.stream.ByteBufDecoderInput.readInt(ByteBufDecoderInput.java:89)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.readHeader(ArmeriaMessageDeframer.java:136)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.process(ArmeriaMessageDeframer.java:115)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:223)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:185)
	com.linecorp.armeria.common.stream.FixedStreamMessage.onNext(FixedStreamMessage.java:197)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request0(TwoElementFixedStreamMessage.java:150)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request(TwoElementFixedStreamMessage.java:86)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.askUpstreamForElement(DecodedHttpStreamMessage.java:165)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.onRequest(DecodedHttpStreamMessage.java:156)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:253)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
#3:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readByte(AdvancedLeakAwareByteBuf.java:400)
	com.linecorp.armeria.internal.common.stream.ByteBufDecoderInput.readByte(ByteBufDecoderInput.java:69)
	com.linecorp.armeria.common.stream.HttpDecoderInput.readUnsignedByte(HttpDecoderInput.java:45)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.readHeader(ArmeriaMessageDeframer.java:128)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.process(ArmeriaMessageDeframer.java:115)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:223)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:185)
	com.linecorp.armeria.common.stream.FixedStreamMessage.onNext(FixedStreamMessage.java:197)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request0(TwoElementFixedStreamMessage.java:150)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request(TwoElementFixedStreamMessage.java:86)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.askUpstreamForElement(DecodedHttpStreamMessage.java:165)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.onRequest(DecodedHttpStreamMessage.java:156)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:253)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:106)
	com.linecorp.armeria.internal.common.stream.ByteBufDecoderInput.readBytes(ByteBufDecoderInput.java:150)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.readBody(ArmeriaMessageDeframer.java:158)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.process(ArmeriaMessageDeframer.java:117)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:223)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:185)
	com.linecorp.armeria.common.stream.FixedStreamMessage.onNext(FixedStreamMessage.java:197)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request0(TwoElementFixedStreamMessage.java:150)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request(TwoElementFixedStreamMessage.java:86)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.askUpstreamForElement(DecodedHttpStreamMessage.java:165)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.onRequest(DecodedHttpStreamMessage.java:156)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:253)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
#5:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeMedium(AdvancedLeakAwareByteBuf.java:556)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64Decoder.process(Base64Decoder.java:174)
	io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1301)
	io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1281)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64Decoder.decode(Base64Decoder.java:106)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64DecoderUtil.lambda$byteBufConverter$0(Base64DecoderUtil.java:32)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:220)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:185)
	com.linecorp.armeria.common.stream.FixedStreamMessage.onNext(FixedStreamMessage.java:197)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request0(TwoElementFixedStreamMessage.java:150)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request(TwoElementFixedStreamMessage.java:86)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.askUpstreamForElement(DecodedHttpStreamMessage.java:165)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.onRequest(DecodedHttpStreamMessage.java:156)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:253)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
#6:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeShort(AdvancedLeakAwareByteBuf.java:550)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64Decoder.process(Base64Decoder.java:168)
	io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1301)
	io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1281)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64Decoder.decode(Base64Decoder.java:106)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64DecoderUtil.lambda$byteBufConverter$0(Base64DecoderUtil.java:32)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:220)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:185)
	com.linecorp.armeria.common.stream.FixedStreamMessage.onNext(FixedStreamMessage.java:197)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request0(TwoElementFixedStreamMessage.java:150)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request(TwoElementFixedStreamMessage.java:86)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.askUpstreamForElement(DecodedHttpStreamMessage.java:165)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.onRequest(DecodedHttpStreamMessage.java:156)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:253)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:402)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64Decoder.decode(Base64Decoder.java:102)
	com.linecorp.armeria.internal.common.grpc.protocol.Base64DecoderUtil.lambda$byteBufConverter$0(Base64DecoderUtil.java:32)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:220)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:185)
	com.linecorp.armeria.common.stream.FixedStreamMessage.onNext(FixedStreamMessage.java:197)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request0(TwoElementFixedStreamMessage.java:150)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request(TwoElementFixedStreamMessage.java:86)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.askUpstreamForElement(DecodedHttpStreamMessage.java:165)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.onRequest(DecodedHttpStreamMessage.java:156)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:253)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
: 26 leak records were discarded because they were duplicates
17:32:38.383 [armeria-common-worker-epoll-2-3] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:107)
	com.linecorp.armeria.internal.common.stream.ByteBufDecoderInput.readBytes(ByteBufDecoderInput.java:150)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.readBody(ArmeriaMessageDeframer.java:158)
	com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.process(ArmeriaMessageDeframer.java:117)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:223)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage$HttpMessageSubscriber.onNext(DecodedHttpStreamMessage.java:185)
	com.linecorp.armeria.common.stream.FixedStreamMessage.onNext(FixedStreamMessage.java:197)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request0(TwoElementFixedStreamMessage.java:150)
	com.linecorp.armeria.common.stream.TwoElementFixedStreamMessage.request(TwoElementFixedStreamMessage.java:86)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.askUpstreamForElement(DecodedHttpStreamMessage.java:165)
	com.linecorp.armeria.internal.common.stream.DecodedHttpStreamMessage.onRequest(DecodedHttpStreamMessage.java:156)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:253)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:210)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator$1.onSubscribe(UnaryGrpcClient.java:213)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:131)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:56)
	com.linecorp.armeria.client.grpc.protocol.UnaryGrpcClient$GrpcFramingDecorator.lambda$execute$1(UnaryGrpcClient.java:194)
	java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:66)
	com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:443)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:386)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:342)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:328)
	com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:450)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:328)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:361)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:311)
	com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:300)
	com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:272)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by alexc-db**
Motivation:

In case `UnaryGrpcClient` receives malformed request or unexpected number of messages - it stops processing them without properly releasing buffers.

Modifications:

- Add subscription cancellation to the `GrpcFramingDecorator` and use subscription with `CANCELLATION_OPTION`.
- Implement `SafeCloseable` interface for `DeframedMessage`.

Result:

- Closes #3733.
- DeframedMessage has `close()` method that can be used to simplify refcount management.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java [hunk 1]
```diff
@@ -288,37 +288,10 @@ private void notifySubscriberOfCloseEvent0(SubscriptionImpl subscription, CloseE
...
-                try {
-                    @SuppressWarnings("unchecked")
-                    final T obj = (T) e;
-                    onRemoval(obj);
-                } finally {
-                    StreamMessageUtil.closeOrAbort(e, cause);
-                }
+                cleanupCause = event.cause;
             }
+            cleanupObjects(event.cause);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java:294]: - nit: Could extract `event.cause` into a local variable like before.
- Thanks a lot for cleaning this up!

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java [hunk 2]
```diff
@@ -53,6 +54,10 @@ static void closeOrAbort(Object obj, @Nullable Throwable cause) {
         }
 
         PooledObjects.close(obj);
+
+        if (obj instanceof SafeCloseable) {
+            ((SafeCloseable) obj).close();
+        }
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java:60]: How about changing `PooledObjects.close(Object)` to close any `SafeCloseable`s rather than just `HttpData`?

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 3]
```diff
@@ -164,36 +166,40 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
...
                                })
                        .thenCompose(msg -> {
-                           if (!msg.status().equals(HttpStatus.OK) || msg.content().isEmpty()) {
-                               // Nothing to deframe.
-                               return CompletableFuture.completedFuture(msg.toHttpResponse());
-                           }
-
-                           final CompletableFuture<HttpResponse> responseFuture = new CompletableFuture<>();
+                           try (HttpData content = msg.content()) {
+                               if (!msg.status().equals(HttpStatus.OK) || content.isEmpty()) {
```
Comment (trustin) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:189]: Not your fault but there can be only one `HttpStatus` per each code:
```suggestion
                               if (msg.status() != HttpStatus.OK || content.isEmpty()) {
```

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 4]
```diff
@@ -205,29 +211,50 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
...
+                @Nullable
+                private Throwable cause;
                 private int processedMessages;
 
                 @Override
                 public void onSubscribe(Subscription s) {
+                    if (subscription != null) {
+                        s.cancel();
+                        return;
+                    }
```
Comment (trustin) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:225]: Is it possible for this method to get invoked more than once? If not, how about just adding an assertion?
```suggestion
                    assert subscription == null;
```

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 5]
```diff
@@ -205,29 +211,50 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
...
+                    subscription = s;
                     // At least 2 requests are required for receiving trailers.
                     s.request(2);
```
Comment (trustin) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:228]: We may just want to request `Long.MAX_VALUE` because we error if we receive more than one deframed non-trailer message anyway.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 6]
```diff
@@ -239,34 +266,46 @@ public void onNext(DeframedMessage message) {
...
+                    buf.retain();
                     processedMessages++;
                 }
 
                 @Override
                 public void onError(Throwable t) {
+                    setCause(t);
                     content.close();
-                    responseFuture.completeExceptionally(t);
+                    responseFuture.completeExceptionally(cause);
```
Comment (trustin) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:286]: How about making `setCause()` return a `Throwable` so that the relationship between `t` and `cause` are clearer?

```java
final Throwable cause = setCause(t);
content.close();
responseFuture.completeExceptionally(cause);
```

File: grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/DeframedMessage.java [hunk 7]
```diff
@@ -35,13 +37,14 @@
  * and thus return an {@link InputStream} in {@code stream}.
  */
 @UnstableApi
-public final class DeframedMessage {
+public final class DeframedMessage implements SafeCloseable {
```
Comment (trustin) [inline grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/DeframedMessage.java:40]: :heart:

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java (hunk 2 above)
Comment (alexc-db) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java:60]: Looking at the `PooledObjects` docs - it's tailored for the pooled HttpData and supposed to be no-op for all other classes, I'm afraid that if we close any `SafeCloseable` there it'll cause confusion and result in bugs in the future.

What I can suggest as an alternative is to remove `PooledObjects.close(obj);` from here, it's effectively replaced by this new condition. What do you think?

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 3 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:189]: Looks much better, thanks!

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 4 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:225]: I'm following the reactive streams spec https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#specification:

> A Subscriber MUST call Subscription.cancel() on the given Subscription after an onSubscribe signal if it already has an active Subscription.

> Calling onSubscribe, onNext, onError or onComplete MUST return normally except when any provided parameter is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations the only legal way for a Subscriber to signal failure is by cancelling its Subscription.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 5 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:228]: What'd be the benefit of doing that? AFAIU requesting too much demand may result in producer allocating too many deframed messages that will have to be discarded (e.g. if for malformed response, or accidental use of streamed response)

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 6 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: I actually refactored how termination is done to align it better with the reactive streams spec, it doesn't store the cause anymore. PTAL.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 5 above)
Comment (trustin) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:226]: It's OK to do so because we abort the response anyway when we received more than expected, but yeah, it doesn't make much difference indeed.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 4 above)
Comment (trustin) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:223]: TIL :bow: but do we actually expect that to happen? In our case that'd be a bug if it ever happens IIUC.

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java (hunk 2 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java]: SGTM.

**Review by trustin — APPROVED** [review]

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 4 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:223]: > The intent of this rule is to prevent that two, or more, separate Publishers from trying to interact with the same Subscriber. Enforcing this rule means that resource leaks are prevented since extra Subscriptions will be cancelled. Failure to conform to this rule may lead to violations of Publisher rule 1, amongst others. Such violations can lead to hard-to-diagnose bugs.

There's no harm in sticking with the spec. If you'd like, I can add warning logging to make sure this issue is surfaced if it happens.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 8]
```diff
@@ -239,33 +289,33 @@ public void onNext(DeframedMessage message) {
...
+                        cancel(new ArmeriaStatusException(StatusCodes.INTERNAL,
+                                                          "received more than one data message; " +
+                                                          "UnaryGrpcClient does not support streaming."));
                         return;
                     }
                     final ByteBuf buf = message.buf();
                     // Compression not supported.
                     assert buf != null;
                     content = HttpData.wrap(buf);
+                    buf.retain();
```
Comment (minwoox) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:301]: How about managing the reference count in this `process` method instead of releasing it `onNext`: https://github.com/line/armeria/pull/3736/files#diff-4798ea4651999fb5f62ea8b9576d6603af31de5f74e996cff16fcc5a62204624R297 so that we don't have to call `retain`?

**Review by minwoox — COMMENTED** [review]
Thanks! Left some minor comments. 😄

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 9]
```diff
@@ -205,32 +210,77 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
                 private HttpData content = HttpData.empty();
                 @Nullable
                 private HttpHeaders trailers;
+                @Nullable
+                private Subscription subscription;
+                private boolean terminated;
```
Comment (ikhoon) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:215]: nit: How about renaming to `completed` which we have been using in other places.
https://github.com/line/armeria/blob/d3e25529570e340730aed7f83302e9b3fdf4c3ac/core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java#L208-L211
```suggestion
                private boolean completed;
```

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 10]
```diff
@@ -164,36 +165,40 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
...
-                                                       byteBufConverter(ctx.alloc(), isGrpcWebText))
-                              .subscribe(singleSubscriber(ctx, msg, serializationFormat, responseFuture),
-                                         ctx.eventLoop());
-                           return responseFuture;
+                               final CompletableFuture<HttpResponse> responseFuture = new CompletableFuture<>();
+                               final ArmeriaMessageDeframer deframer =
+                                       new ArmeriaMessageDeframer(Integer.MAX_VALUE);
+                               msg.toHttpResponse().decode(deframer, ctx.alloc(),
+                                                           byteBufConverter(ctx.alloc(), isGrpcWebText))
+                                  .subscribe(singleSubscriber(ctx, msg, serializationFormat, responseFuture),
```
Comment (ikhoon) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:198]: How about passing `isGrpcWeb` instead of `serializationFormat` though not related to this PR.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 11]
```diff
@@ -239,33 +289,33 @@ public void onNext(DeframedMessage message) {
...
+                private void cancel(Throwable t) {
+                    if (terminated) {
                         return;
                     }
-                    if (trailers == null) {
-                        trailers = msg.trailers();
+                    terminated = true;
+                    if (subscription != null) {
+                        subscription.cancel();
                     }
```
Comment (ikhoon) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:312]: `subscription` should not be null here. `onNext()`, `onError()` and `onComplete()` MUST be called after `onSubscribe()`. 
Isn't it better to add `assert` than `if` condition?

**Review by ikhoon — COMMENTED** [review]
Mostly looking good!

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 12]
```diff
@@ -205,32 +210,77 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
...
                     s.request(2);
                 }
 
                 @Override
                 public void onNext(DeframedMessage message) {
+                    try {
+                        if (terminated) {
+                            return;
+                        }
+                        process(message);
```
[the remark this answers is not in the document]
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:235]: it's a final consumer of the `message` and is responsible for closing it. If we do move `if` out of the `try` - it'll leak buffers. Think about this as try with resources, but I couldn't use it here because it seems like Java 8 doesn't support try with resources with references, so I had to use `finally` for closing it.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 8 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:301]: It's done this way to clearly separate resource management for the `DeframedMessage` and the processing logic. `onNext` is a final consumer of the `DeframedMessage` and is responsible for closing it to avoid leaks, regardless of the business logic inside `process`. That's why `message.close` is happening in the `finally` statement there. `process` is now only responsible for retaining the buffer in case it needs to keep it inside the `HttpData` to return in the response (only one case our of multiple branches), since `buf` is explicitly retained in that case - even if someone rearranges the code or adds more flow control they don't need to worrying about releasing the buffer to avoid memory leak because `onNext` takes care of that.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 11 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:312]: Not sure, let's discuss. My reading of the reactive streams spec is that Subscriber that follows the spec doesn't throw exceptions, except when any provided parameter is null:

```
Calling onSubscribe, onNext, onError or onComplete MUST return normally except when any provided parameter is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations the only legal way for a Subscriber to signal failure is by cancelling its Subscription. 
```

`assert` will throw, and I'm not sure if that's okay to do since that may cause issues to cascade and make it hard to debug. If you're concerned about this issue being handled silently - how about logging an error in case subscription is null here?

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (minwoox) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:235]: Oops, that was a dumb comment. I misread the code. Please, forget about it. 😅

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 8 above)
Comment (minwoox) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:301]: Thanks for the elaboration. SGTM.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 10 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:198]: serializationFormat.uriText() is used in the error message if trailers are malformed, similar to https://github.com/line/armeria/blob/fcd2d72a73218a3dda4c2c89f4908ec1ad12d810/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java#L395-L397

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 13]
```diff
@@ -205,32 +210,77 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
...
+                        trailers = msg.trailers();
+                    }
+                    responseFuture.complete(HttpResponse.of(msg.headers(), content, trailers));
+                }
+
+                private void process(DeframedMessage message) {
                     if (UnaryGrpcSerializationFormats.isGrpcWeb(serializationFormat) && message.isTrailer()) {
                         final ByteBuf buf;
                         try {
                             buf = InternalGrpcWebUtil.messageBuf(message, ctx.alloc());
```
[the remark this answers is not in the document]
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:266]: Good point, thanks for catching this!

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 10 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: I cached isGrpcWeb in the member variable that's computed once on the subscriber instance creation, hope it addresses your concern, PTAL

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: No worries :)

**Comment by alexc-db** [comment]
@trustin @ikhoon @minwoox codecov/patch failed with `67.34% of diff hit (target 73.45%)` - I'm not sure if I can easily cover those lines with tests since those are mostly dedicated to ensuring correct behavior of the subscriber - currently cannot be triggered because producer is behaving correctly, but IMHO should be there to ensure that future changes to the producer (e.g. `ArmeriaMessageDeframer`) don't trigger unexpected behavior and are handled properly if any issue occurs. Not sure if I should chase those missing % and add a way to inject a faulty producer into the UnaryGrpcClient just to please this check.

**Comment by trustin** [comment]
@alexc-db You don't need to worry about the test coverage. We use it as a reminder, not a hard limit. :smile:

**Comment by trustin** [comment]
By the way, resource leak detection is non-deterministic by its nature (it may miss a leak if GC pressure is too low.) so you might want to run tests with the `-Pleak` option multiple times locally to be totally sure.

**Comment by alexc-db** [comment]
@trustin I was testing it locally w/ -Pleak, multiple times, it didn't trigger for this branch

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 11 above)
Comment (ikhoon) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: It is agreeable. However `assert` has a different meaning compared to other exceptions. 
1. It will be removed from our user's code if `-ea` option is not specified.
  - This would be good for micro optimizations.
  - We don't want to execute `if` and `else` condition if it should be always true.
2. `assert` is commonly used to help IDE and devs statically analyze a stateful code.
3. We assume that `assert` MUST not raise `AssertionError`.

Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: > It is agreeable. However `assert` has a different meaning compared to other exceptions.
> 
> 1. It will be removed from our user's code if `-ea` option is not specified.
    
If `assert` is removed from the user's code and `subscription` is `null` - it'll unexpectedly throw NullPointerException for `subscription.cancel` which would violate the spec - `subscription` is not a is not a provided param for `onNext`. By using `assert` we will intentionally make this subscriber implementation faulty, and with various flavors of faultiness based on the VM options :)

>    * This would be good for micro optimizations.
>    * We don't want to execute `if` and `else` condition if it should be always true.

Modern hardware usually doesn't benefit from micro optimizations like this, conditions that always true are usually cheap to execute thanks to https://en.wikipedia.org/wiki/Branch_predictor.

Micro optimizations are usually only good for micro benchmarking. In real world scenarios code is executed in the conditions that are hard to reproduce in the micro benchmarks, and is limited by other factors. If this method doesn't take a significant % of the CPU flame graph in the production - it's not worth optimizing.

Unless I'm missing something about Java world and you have a way to demonstrate that using if condition here would have a non-negligible impact on Armeria's performance.

> 2. `assert` is commonly used to help IDE and devs statically analyze a stateful code.
> 3. We assume that `assert` MUST not raise `AssertionError`.

True, `assert` is used to document the assumptions in the code, though in this particular case it'd lead to violating the spec since it doesn't mention that `AssertionError` is allowed to be raised, and it MAY be raised if e.g. bug is introduced in the publisher in the future. If that happens - we probably don't want servers in production to be broken by the AsserionError or NullPointerException raised unexpectedly from the subscriber. You can make an argument that given faulty producer it's okay to have faulty subscriber, but I think we should prefer to follow the spec:

1. It'll make things easier for developers familiar with the spec to contribute
2. Less edge cases to consider on publisher side
3. Higher chances that misbehavior of one part of the code won't cause a cascading failure elsewhere, e.g. because publisher wasn't expecting such behavior.

Comment (ikhoon) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: >  though in this particular case it'd lead to violating the spec since it doesn't mention that AssertionError is allowed to be raised, 

It is an important specification not to throw any exception from `Subscriber`. 👍 
However, it might be meaningful when a `Publisher` follows the Reactive Streams specifications.
A `Publisher` should pass a Subscription via `onSubscription(Subsription)` first and other methods have to be invoked. A `Subscriber` is a small state machine. The correct state could be preserved only when a `Publisher` correctly calls the APIs in order.

If the state is broken by the `Publisher`, can we throw `AssertionError` or `IllegalStateException`?
Furthermore, in this case, the `Publisher`s are Armeria's `StreamMessage` that we manage.
Do you think `assert` is still harmful?

> Modern hardware usually doesn't benefit from micro optimizations like this,
Micro optimizations seem overkill. It does not really matter.

**Review by ikhoon — APPROVED** [review]
Thanks! @alexc-db 
Discussion on `assert` will not affect the key changes of this PR.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java [hunk 14]
```diff
@@ -164,110 +167,163 @@ public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) {
...
-                                         ctx.eventLoop());
-                           return responseFuture;
+                               final CompletableFuture<HttpResponse> responseFuture = new CompletableFuture<>();
+                               final ArmeriaMessageDeframer deframer =
+                                       new ArmeriaMessageDeframer(Integer.MAX_VALUE);
+                               msg.toHttpResponse()
+                                  .decode(deframer, ctx.alloc(), byteBufConverter(ctx.alloc(), isGrpcWebText))
+                                  .subscribe(new DeframedMessageSubscriber(
+                                                     msg, serializationFormat, responseFuture),
+                                             ctx.eventLoop());
```
Comment (minwoox) [inline grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:202]: This is not your fault but how about specifying `SubscriptionOption.WITH_POOLED_OBJECTS` when subscribing so that we can reduce the number of byte buf copies?

**Review by minwoox — APPROVED** [review]
Just one nit.
Thanks! 😄

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 14 above)
Comment (trustin) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java:202]: Let me merge once this comment is addressed.

Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: Done.

File: grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java (hunk 11 above)
Comment (alexc-db) [reply grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java]: > > though in this particular case it'd lead to violating the spec since it doesn't mention that AssertionError is allowed to be raised,
> 
> It is an important specification not to throw any exception from `Subscriber`. 👍
> However, it might be meaningful when a `Publisher` follows the Reactive Streams specifications.
> A `Publisher` should pass a Subscription via `onSubscription(Subsription)` first and other methods have to be invoked. A `Subscriber` is a small state machine. The correct state could be preserved only when a `Publisher` correctly calls the APIs in order.
> If the state is broken by the `Publisher`, can we throw `AssertionError` or `IllegalStateException`?

Looking at the provided examples - they don't thrown in such cases. E.g. https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/examples/src/main/java/org/reactivestreams/example/unicast/SyncSubscriber.java#L56 - creates `IllegalStateException` and prints stack trace (but doesn't throw).

> Furthermore, in this case, the `Publisher`s are Armeria's `StreamMessage` that we manage.
> Do you think `assert` is still harmful?

I still do. "return normally" requirement (2.13 in the spec) allows for a straightforward publisher - subscriber interaction - publisher may call `onNext` like this:

```
Stream<T> stream = streamSupplier.get();
stream.forEach(subscriber::onNext);
```

and can reasonably expect that subscriber will normally process or discard all the messages provided on that stream. I we break that invariant (even if that happens due to the faulty producer that "forgot" to call `onSubscribe`) - I can imagine at least a couple of things that can go wrong and could be avoided by strictly following the spec:

1. Depending on the contract between publisher and subscriber - subscriber may be responsible for managing resources (like buffer refcnt in this PR). If `onNext` returns exceptionally - other `onNext` calls in that examples won't be called and there will be a leak. It's expected that even in case of cancellation subscriber may receive `onNext` calls with pending messages https://github.com/reactive-streams/reactive-streams-jvm#2.8 where it can properly release resources if needed.
2. If `onNext` raises - you need to carefully think about how onNext is structured, taking into account not only the regular flow control, but also a possible exception. E.g. in `DeframedMessageSubscriber.onNext` raising an exception directly in place of current `if` condition would result in `completeExceptionally` being skipped and never called. You could argue that fix is as simple as rearranging the lines, but I just don't need to worry about that because I follow the contract and make sure nothing is thrown, `completeExceptionally` is guaranteed to be called even if publisher is faulty and `subscription == null`.

I think there are 2 options:
1. If Armeria wants to conform to the reactive streams spec - it should follow the specification rules strictly. This will help with future contributions and compatibility with other libraries that follow the spec. This spec is a contract that helps developers from multiple projects write software that's compatible and bug-free. Since this model seems to be successful and quite popular in Java world - I'd assume that rules provided in the spec are there for a reason, and we should not diverge from them. If something is not permitted in the spec **explicitly** - it's not allowed. If somehow we need to bend the rules to make something work - there's a high chance that we are using that in a wrong and unexpected way.
2. If reactive streams specification is considered confusing - Armeria should use custom interfaces that are better suited for the job (note that I don't necessarily recommend that 😄 ). The problem we started with is that subscription may not be set when `onNext` is called, that's happening because subscriber is following the reactive streams approach of setting the subscription **after** the object creation, which means there's a part of object lifetime where subscription is `null` - that problem would not have existed if subscription object was provided in the subscriber constructor and verified to be not `null` before any interactions between the publisher and subscriber.

I think it's a bad idea to try to conform to the specification and at the same time occasionally break the rules based on the assumption that "this situation will never happen", because it occasionally will 😉
