### PR TITLE
Deprecate ArmeriaSettings.ip and add ArmeriaSettings.address

### LINKED ISSUE #4597: Deprecate ArmeriaSettings.ip and add ArmeriaSettings.address
Users can specify an IP address of Armeria server via a Spring property file:
https://github.com/line/armeria/blob/39df04b928d5125d3fb7a8a42651817df4200adc/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java#L83-L87

It only takes an IP address so if a hostname is specified, Armeria throws an exception:
https://github.com/line/armeria/blob/7626562204bd4311a1205df9d733203324355a96/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java#L84

However, Spring allows Users to specify a hostname because Spring converts the input to an `InetAddress`.
So we need to also allow users to specify a hostname by
- adding `ArmeriaSettings.address` whose type is `InetAddress`
- deprecating `ArmeriaSettings.ip`

### PR DESCRIPTION
**Pull request by kojilin**
Motivation:

Spring allows Users to specify a hostname because Spring converts the input to an InetAddress.
So we need to also allow users to specify a hostname.

Modifications:

- adding ArmeriaSettings.address whose type is InetAddress
- deprecating ArmeriaSettings.ip

Result:

- Closes #4597

### CODE REVIEW

File: spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java [hunk 1]
```diff
@@ -105,20 +114,39 @@ public static class Port {
...
+        public InetAddress getAddress() {
+            return address;
+        }
+
+        /**
+         * Registers a Network address that the {@link Server} uses.
+         */
+        public void setAddress(InetAddress address) {
+            this.address = address;
+        }
```
Comment (ikhoon) [inline spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java:148]: Should return `this` like other setters?

File: spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+
+    @Inject
+    private Server server;
+
+    @Test
+    public void testIpCanBeUsed() {
+        final Collection<ServerPort> serverPorts = server.activePorts().values();
+        for (ServerPort sp : serverPorts) {
+            final InetAddress address = sp.localAddress().getAddress();
+            Assertions.assertThat(address.isAnyLocalAddress() || address.isLoopbackAddress()).isTrue();
```
Comment (ikhoon) [inline spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java:57]: nit: Prefer static import for assertions.
```suggestion
           assertThat(address.isAnyLocalAddress() || address.isLoopbackAddress()).isTrue();
```

**Review by ikhoon — APPROVED** [review]
Thanks @kojilin for the quick fix! 🙇‍♂️

File: spring/boot2-autoconfigure/src/test/resources/config/application-deprecatedIpTest.yml [hunk 3]
```diff
@@ -0,0 +1,8 @@
+armeria:
+  ports:
+    - ip: 127.0.0.1
```
Comment (jrhee17) [inline spring/boot2-autoconfigure/src/test/resources/config/application-deprecatedIpTest.yml:3]: optional; I'm unsure if this would also work in windows, but I think it would be cool if we can check that non-ip addresses are also accepted

```suggestion
    - address: localhost
```

File: spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
+/*
+ * Copyright 2020 LINE Corporation
```
Comment (jrhee17) [inline spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java:2]:
```suggestion
 * Copyright 2023 LINE Corporation
```

**Review by jrhee17 — APPROVED** [review]
Looks really nice! Thanks @kojilin ! 🙇 👍 🙇

File: spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
+/*
+ * Copyright 2023 LINE Corporation
```
Comment (minwoox) [inline spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java:2]: Happy new year. 🎉 🎉 🎉

File: spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+
+    @Inject
+    private Server server;
+
+    @Test
+    public void testIpCanBeUsed() {
+        final Collection<ServerPort> serverPorts = server.activePorts().values();
+        for (ServerPort sp : serverPorts) {
+            final InetAddress address = sp.localAddress().getAddress();
+            assertThat(address.isAnyLocalAddress() || address.isLoopbackAddress()).isTrue();
```
Comment (minwoox) [inline spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java:58]: Question: are these values different depending on the OS?

File: spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java [hunk 7]
```diff
@@ -71,24 +70,42 @@ public static void configurePorts(ServerBuilder server, List<Port> ports) {
...
         });
     }
 
+    @Nullable
+    private static InetSocketAddress createSocketAddress(Port p) {
+        final InetAddress address = p.getAddress();
+        final String ip = p.getIp();
+        final int port = p.getPort();
+        if (ip != null && address != null) {
+            throw new IllegalStateException("A port cannot have both IP and address: " + p);
```
Comment (minwoox) [inline spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java:86]: Should we override `Port.toString()` to properly create the message?

**Review by minwoox — COMMENTED** [review]
Thanks a lot for adding the address. 😄

File: spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java (hunk 6 above)
Comment (kojilin) [reply spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java:58]: not sure, I just put 127.0.0.1 & 0.0.0.0 at yml, so keep test both

Comment (minwoox) [reply spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java:58]: Ah ha, if so how about branching it so that we can be sure what the test actually means?
```java
if ("127.0.0.1".equals(address.getHostAddress())) {
    assertThat(...).isTrue();
} else {
    // 0.0.0.0
    assertThat(...).isTrue();
}
```

File: spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java [hunk 8]
```diff
@@ -202,6 +205,17 @@ public Port setProtocol(SessionProtocol protocol) {
             protocols = ImmutableList.of(protocol);
             return this;
         }
+
+        @Override
+        public String toString() {
+            return "Port{" +
+                   "ip='" + ip + '\'' +
+                   ", address=" + address +
+                   ", iface='" + iface + '\'' +
```
Comment (minwoox) [inline spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java:214]: question: It seems like we add `''` to only `ip` and `iface`. Is there any specific reason for that?

**Review by minwoox — APPROVED** [review]
Just left one question. Thanks a lot, @kojilin! 😄

File: spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java (hunk 8 above)
Comment (kojilin) [reply spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java:214]: I used Intellij to generate and looks like it adds `'` or not by String or not.
Maybe I should use `MoreObjects.toStringHelper` like others?

Comment (minwoox) [reply spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java]: Didn't know about it. 😄 It looks good now. Thanks!

**Comment by minwoox** [comment]
Thanks a lot, @kojilin! 😄
