### PR TITLE
Fix to set cause correctly in RetryingClient

### LINKED ISSUE #4558: Questions about exception propagation in Armeria gRPC client with a RetryingClient decorator
Hi there! I have 2 questions about how exception propagation behavior in Armeria gRPC client with a RetryingClient decorator. It seems to me that there could be a bug.

## Setup
Armeria version: 1.16.0

### Client setup
I build a gRPC client stub with a [ClientBuilder](https://github.com/line/armeria/blob/c8d1f5ef142f65fd79bd01b87d8155d220c9d0b9/core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java) and I add 3 decorators to the `ClientBuilder` as shown below:

```scala
// Please note that "Site A/B/C/D" mentioned in the comment below will be referred in later discussion.

// Decorator 1
clientBuilder.decorator((delegate, ctx, req) => {
    val httpResponse = delegate.execute(ctx, req)
    httpResponse
        .mapHeaders(respHeaders => {
             // Site A
             // 1. create an exception based on the response header content.
             // 2. throw the created exception.
        }
})

// Decorator 2
clientBuilder.decorator((delegate, ctx, req) => {
    ctx.log() // ClientRequestContext
      .whenComplete()
      .thenAccept(requestLog => {
          val exception = requestLog.responseCause()
          // The above `exception` is always null except in the case where
          // the last retry attempt fails.
          // Site B
       })
    delegate.execute(ctx, req)
})

// Decorator 3
val retryDecorator = RetryingClient.newDecorator(createRetryConfig())
clientBuilder.decorator(retryDecorator)

def createRetryConfig(): RetryConfig = {
   // ...
   val retryRuleBuilder = RetryRule.builder()
   retryRuleBuilder.onException((_: ClientRequestContext, cause: Throwable) => {
     // This callback is NEVER invoked.
     // Site C
   })
   retryRuleBuilder.onResponseTrailers((ctx, trailers) => {
     // This callback is invoked. The retry decision is made based on `trailers`
     // Site D
   })
   // Create a RetryConfig with the above `retryRuleBuilder` and return it.
}
```

### Test setup
I wrote a test where a client with above decorators send one request to a server which always fails the requests and populates the response header with some error information. When the client receives the response, I expect the `decorator 1`'s `httpResponse.mapHeaders` callback (`Site A`) is invoked and an exception is created and thrown there. Then I expect the client to retry up to 3 times and eventually fail (because the server always fails the request and triggers an exception on the client side).

## Observations

1. Retry kicked in and 3 requests were sent sequentially. All 3 attempts failed that lead to client stub invocation failure. This behavior is expected :) 
2. The order of invocation during each request attempt: `Site A --> Site D --> Site B`. Note that `Site C` is never invoked.
3. In the first 2 request attempts at `Site B`,  `requestLog.responseCause() == null`. However, in the 3rd/final request attempt at `Site B`, `requestLog.responseCause() == exception_thrown_at_Site A`.

## Questions
1. For `observation 2`, why does `Site C` never invoked? Is it a bug or I did something wrong?
2. For `observation 3`, is this the expected/correct behavior? Specifically, does Armeria intentionally try to hide the exception from `Site B` (the ctx.log().whenComplete() callback) until the max retry attempt is reached? If it is intentional, could you share the rationale behind this design?

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
When an exception is raised in the decorator between `RetryingClient` and the network layer, the exception is not correctly set to `RequestLog.responseCause()` so that users cannot use the exception to make a decision.

Modification:
- Call `derivedCtx`'s `RequestLogBuilder.endResponse(cause)` when the response is completed exceptionally.

Result:
- Close #4558 
- You can now use the exception, which is raised in the decorator, to make a decision for retrying.

### CODE REVIEW

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+                                             .thenBackoff();
+        final WebClient client =
+                WebClient.builder(server.httpUri())
+                         .decorator((delegate, ctx, req) -> {
+                             ctx.log()
+                                .whenAvailable(RequestLogProperty.RESPONSE_CAUSE)
+                                .thenAccept(log -> logExceptionCounter.incrementAndGet());
+                             return delegate.execute(ctx, req);
+                         })
+                         .decorator((delegate, ctx, req) -> delegate.execute(ctx, req)
```
Comment (Lincong) [inline core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:64]: In https://github.com/line/armeria/issues/4558#issue-1471905262, the order of decorator registration is that this decorator (which throws an exception) is registered to the `builder` first, then the decorator with `ctx.log().whenAvailable...` is registered, and lastly the retrying client/decorator is added.

Could you consider swapping this decorator and the one above so that it is more consistent with the originally reported issue (even though I understand that functionally there is no difference)?

Thanks!

**Review by Lincong — COMMENTED** [review]
Thanks @minwoox !

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+import org.junit.jupiter.api.extension.RegisterExtension;
+
+import com.linecorp.armeria.client.WebClient;
+import com.linecorp.armeria.common.HttpResponse;
+import com.linecorp.armeria.common.logging.RequestLogProperty;
+import com.linecorp.armeria.internal.testing.AnticipatedException;
+import com.linecorp.armeria.server.ServerBuilder;
+import com.linecorp.armeria.testing.junit5.server.ServerExtension;
+
+class RetryingClientWithDecoratorTest {
```
Comment (Lincong) [inline core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:34]: A general question unrelated to this PR change:

Say I have 3 decorators on the client as below:

```scala
// Decorator 1
clientBuilder.decorator((delegate, ctx, req) => {
val httpResponse = delegate.execute(ctx, req)
    httpResponse
        .mapHeaders(respHeaders => {
             // throw the created exception X.
        }
})

// Decorator 2
clientBuilder.decorator((delegate, ctx, req) => {
    ctx.log() // ClientRequestContext
          .whenComplete()
          .thenAccept(/* callback Y */)

    val httpResponse = delegate.execute(ctx, req)
        httpResponse
            .mapError(exception => {
               // callback Z: process exception
            })
})

// Decorator 3
clientBuilder.decorator(/* could be any decorator */)
```

Either with or without the decorator 3, after `exception X` is thrown in decorator 1, `callback Z` will always be invoked before `callback Y`, right?

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java [hunk 3]
```diff
@@ -329,7 +329,13 @@ private void doExecute0(ClientRequestContext ctx, HttpRequestDuplicator rootReqD
         if (!ctx.exchangeType().isResponseStreaming() || config.requiresResponseTrailers()) {
             // XXX(ikhoon): Should we use `response.aggregateWithPooledObjects()`?
             response.aggregate().handle((aggregated, cause) -> {
-                final HttpResponse response0 = cause != null ? HttpResponse.ofFailure(cause) : null;
+                final HttpResponse response0;
+                if (cause != null) {
+                    derivedCtx.logBuilder().endResponse(cause);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:334]: How about passing `cause` directly to `handleResponse` as an argument?
IIUC, it seems possible that `endResponse()` is called first and `.endResponse(cause)` later. If `.endResponse(cause)` is called later, the cause is ignored silently with the current implementation. The cause may happen if there is an async logic with a response in a decorator.
```java
.decorator((delegate, ctx, req) -> {
   final HttpResponse response = delegate.execute(ctx, req);
   return HttpResponse.from(response.aggregate().thenApplyAsync(agg -> {
       return Exceptions.throwUnsafely(new AnticipatedException());
   }));
})
``` 
Or it may happen if we change our implementation unexpectedly by replacing `aggregate().handle()` with `aggregate().handleAsync()`.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:334]: https://github.com/line/armeria/blob/cae3b6da373101c0976e2d00f1f3cbb706d07e00/core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java#L1352-L1355

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+        final AtomicInteger logExceptionCounter = new AtomicInteger();
+        // Retry only 3 times.
+        final RetryRule retryRule = RetryRule.builder()
+                                             .onException((ctx, cause) -> {
+                                                 assert cause instanceof AnticipatedException;
+                                                 return onExceptionCounter.incrementAndGet() != 3;
+                                             })
+                                             .onResponseTrailers((ctx, trailers) -> false)
+                                             .thenBackoff();
+        final WebClient client =
```
[the remark this answers is not in the document]
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:56]: That's exactly. 😄

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java (hunk 2 above)
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:34]: > Either with or without the decorator 3, after exception X is thrown in decorator 1, callback Z will always be invoked before callback Y, right?

I believe so in this case.
However, I don't know about your usage, I think it's not a good idea to rely on the execution order of callbacks because callbacks usually do not run in sequence unless you explicitly make it so:
```java
// The execution order of fooCallback and barCallback is different depending on the future's state.
future.handle(fooCallback); 
future.handle(barCallback);

// fooCallback is always executed before barCallback.
future.handle(fooCallback).handle(barCallback)
```

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Lincong) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:56]: Thanks for the clarification.

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java [hunk 5]
```diff
@@ -329,7 +329,13 @@ private void doExecute0(ClientRequestContext ctx, HttpRequestDuplicator rootReqD
         if (!ctx.exchangeType().isResponseStreaming() || config.requiresResponseTrailers()) {
             // XXX(ikhoon): Should we use `response.aggregateWithPooledObjects()`?
             response.aggregate().handle((aggregated, cause) -> {
-                final HttpResponse response0 = cause != null ? HttpResponse.ofFailure(cause) : null;
+                final HttpResponse response0;
+                if (cause != null) {
```
[the remark this answers is not in the document]
Comment (Lincong) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:332]: Thanks for explaining the code convention!

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+        }
+    };
+
+    @Test
+    void responseCauseIsSetWhenExceptionIsRaisedInDecorator() throws InterruptedException {
+        final AtomicInteger onExceptionCounter = new AtomicInteger();
+        final AtomicInteger logExceptionCounter = new AtomicInteger();
+        // Retry only 3 times.
+        final RetryRule retryRule = RetryRule.builder()
+                                             .onException((ctx, cause) -> {
```
Comment (Lincong) [inline core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:50]: This question may be out of the scope of this PR. Instead, I hope to know Armeria's expected behavior/semantics.

Should/will this `onException` callback be invoked with `cause != null` when a network-level exception happen?

By "network-level exception", I mean one of below situations:

### 1. Connection socket timeout.
E.g. the client tries to connect to a private address `10.255.255.255`.
Thrown exception:
`StatusRuntimeException` -> `UnprocessedRequestException` -> `ConnectTimeoutException`
### 2. Request timeout.
E.g. Server side is too slow and fails to response within a certain period of time.
Thrown exception:
`StatusRuntimeException` -> `ResponseTimeoutException` 
### 3. Connection interrupted.
E.g. server crashes unexpectedly in the middle of transmitting a response.
Thrown exception:
`StatusRuntimeException` -> `UnprocessedRequestException` -> `ClosedSessionException`

### 4. DNS failure.
Client tries to resolve an invalid domain name.
Thrown exception:
`StatusRuntimeException` -> `UnprocessedRequestException` -> `UnknownHostException`

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java (hunk 2 above)
Comment (Lincong) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:34]: Thanks @minwoox for the clarification. 

It makes sense that in your example, `fooCallback` and `barCallback` are added to the same future instance and they may have non-deterministic execution order. However, in my example, `callback Z` is added to `httpResponse` and `callback Y` is added to `ctx.log()`. 

Does that mean Armeria does not guarantee a consistent execution order of callbacks added to different components? IOW, is there no such a contract saying that callbacks added to `ctx.log()` will always be executed before callbacks added to `httpResponse` or vice versa?

The reason why I am asking is because I hope to learn what assumptions I can safely make going forward. Thanks!

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java (hunk 1 above)
Comment (Lincong) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java]: Thanks!

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java (hunk 2 above)
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:34]: > callback Z is added to httpResponse and callback Y is added to ctx.log().
Does that mean Armeria does not guarantee a consistent execution order of callbacks added to different components?

No, we don't guarantee that. In your example, if the exception is raised in `mapHeaders`, then Z is called before Y is called. However, if the exception is raised inside and another decorator is attached such as [this](https://github.com/line/armeria/pull/4559#discussion_r1038730448), Y would be called before Z.

>  I hope to learn what assumptions I can safely make going forward. Thanks!

I believe that we shouldn't rely on the execution order of callbacks unless we make it explicitly or there's happens-before relationship between the callbacks.

> callback Z is added to httpResponse and callback Y is added to ctx.log().

There's no happens-before relationship between the callbacks of `HttpResponse` and `ctx.log()`.

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java (hunk 6 above)
Comment (minwoox) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:50]: > Should/will this onException callback be invoked with cause != null when a network-level exception happen?

Yes, I believe so. If the exception is raised before the request goes to the network layer, the cause will be set by this change. If the exception is raised in the network layer or after that, the cause will be set [here](https://github.com/line/armeria/blob/cae3b6da373101c0976e2d00f1f3cbb706d07e00/core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java#L331-L335) thus we can use it.

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java [hunk 7]
```diff
@@ -340,6 +345,26 @@ private void doExecute0(ClientRequestContext ctx, HttpRequestDuplicator rootReqD
         }
     }
 
+    private void handleMaybeErrorResponse(RetryConfig<HttpResponse> config, ClientRequestContext ctx,
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java:348]: Suggestion: I found it difficult to understand the meaning of this method.
It looks to handle a response without a response body content.
How about naming it `handleResponseWithoutContent()`?

**Review by ikhoon — APPROVED** [review]
Thanks, @minwoox and @Lincong! 🙇‍♂️🚀

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java (hunk 6 above)
Comment (ikhoon) [reply core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java:50]: > By "network-level exception", I mean one of below situations:

In addition to the situations you listed, I recommend you check some cases where `UnprocessedRequestException.of()` is used.

File: core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java (hunk 7 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java]: Renamed it. 😉
