### PR TITLE
Log response bytes transferred when sending a server timeout response…

### LINKED ISSUE #1769: responseFirstBytesTransferredTimeNanos is not available if a response is timed out
# Problem
We are using HttpTracingService as follow. 

```
    @Bean
    HttpServiceRegistrationBean springMvcTomcatService(
            ServletWebServerApplicationContext applicationContext,
            Tracing tracing) {
        TomcatWebServer container =
                (TomcatWebServer) applicationContext.getWebServer();
        container.start();
        Connector tomcatConnector = container.getTomcat().getConnector();

        return new HttpServiceRegistrationBean()
                .setServiceName(SERVICE_NAME)
                .setService(TomcatService.forConnector(tomcatConnector)
                                         .decorate(HttpTracingService.newDecorator(tracing)))
                .setPathMapping(PathMapping.ofPrefix("/api"));
    }
```

When a response to client was timed out (maybe because it has large response), we got `RequestLogAvailabilityException`.

```
2019-05-15 01:01:56.199  WARN [-] [armeria-common-worker-epoll-2-18] c.l.a.c.l.RequestLogListenerInvoker      : onRequestLog() failed with an exception:

com.linecorp.armeria.common.logging.RequestLogAvailabilityException: RESPONSE_FIRST_BYTES_TRANSFERRED
        at com.linecorp.armeria.common.logging.RequestLog.ensureAvailability(RequestLog.java:110)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.responseFirstBytesTransferredTimeNanos(DefaultRequestLog.java:717)
        at com.linecorp.armeria.server.tracing.HttpTracingService.lambda$serve$2(HttpTracingService.java:94)
        at com.linecorp.armeria.common.logging.RequestLogListenerInvoker.invokeOnRequestLog(RequestLogListenerInvoker.java:38)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.notifyListeners(DefaultRequestLog.java:1006)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.updateAvailability(DefaultRequestLog.java:963)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:940)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:919)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse(DefaultRequestLog.java:905)
        at com.linecorp.armeria.server.HttpResponseSubscriber.lambda$addCallbackAndFlush$2(HttpResponseSubscriber.java:421)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:152)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
        at com.linecorp.armeria.server.HttpResponseSubscriber.addCallbackAndFlush(HttpResponseSubscriber.java:418)
        at com.linecorp.armeria.server.HttpResponseSubscriber.failAndRespond(HttpResponseSubscriber.java:403)
        at com.linecorp.armeria.server.HttpResponseSubscriber.onTimeout(HttpResponseSubscriber.java:128)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
```

# Suggestion
Maybe need to call `responseFirstBytesTransferred` at `DefaultRequestLog.endResponse0(responseCause, responseEndTimeNanos)`?

### PR DESCRIPTION
**Pull request by anuraaga**
…, and don't try logging response bytes when a client timed out, therefore no response was sent.

Currently, if the server times out a request, it does send a timeout response, but does not call the log handler to indicate it sent bytes. Also, both tracing implementations try to log response bytes timing always, but if the client times out a request, there was never a response so this needs to actually be checked.

Fixes #1769 

/cc @adriancole

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java [hunk 1]
```diff
@@ -389,6 +389,11 @@ private void failAndRespond(Throwable cause, AggregatedHttpMessage message, Http
                 responseEncoder.writeHeaders(id, streamId, headers, false);
                 future = responseEncoder.writeData(id, streamId, content, true);
             }
+
+            if (!loggedResponseHeadersFirstBytesTransferred) {
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java]: It seems not very different, but how about doing this in the future listener? (like the following code)
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L336-L340 
It sets `responseFirstBytesTransferred` only if it succeeded.

Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java]: Thanks, good idea.

File: zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java [hunk 2]
```diff
@@ -90,6 +96,10 @@
     public final ServerRule server = new ServerRule() {
         @Override
         protected void configure(ServerBuilder sb) throws Exception {
+            // Our test that triggers a timeout will take a second to run. Hopefully it doesn't cause flakiness
```
Comment (minwoox) [inline zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java]: Hope so. 😉

**Comment by minwoox** [comment]
Thanks, @anuraaga!
