### PR TITLE
`RouteCache` correctly handles dynamic predicates

### LINKED ISSUE #4927: Return 404 when request has invalid queryParams
If there is a request to a unregistered path, armeria returns 404 by FallbackService.

However, when there is a service method with `@MatchesParam` in a annotated service and request has no such a query param, it returns 500 by java.lang.IllegalArgumentException: routingResult: RoutingResult{<empty>} (must be present) at Routed:51 --> Http1RequestDecoder:223

```
@PathPrefix("/objects")
class ServiceHandler(
) {

    @Get
    @MatchesParam("id")
    suspend fun getById(
        @Param id: Int
    ) = mapOf()
}
```
```
curl --location 'http://localhost:8080/objects' \
```

```
java.lang.IllegalArgumentException: routingResult: RoutingResult{<empty>} (must be present)
	at com.linecorp.armeria.server.Routed.of(Routed.java:51)
	at com.linecorp.armeria.server.RouteCache$CachingRouter.find(RouteCache.java:126)
	at com.linecorp.armeria.server.VirtualHost.findServiceConfig(VirtualHost.java:392)
	at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:216)
```

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

We received a report where a route cached by `RouteCache` actually didn't have a route present.

https://github.com/line/armeria/blob/ed16bf6f8846415fdadd70d46afc364376669058/core/src/main/java/com/linecorp/armeria/server/RouteCache.java#L127

https://github.com/line/armeria/blob/4b1a2be9ae3b9492925fee179d33d4215a2e60d3/core/src/main/java/com/linecorp/armeria/server/Routed.java#L50-L52

This can be reproduced by 
1. Sending a request first which satisfies the dynamic predicate to populate the cache
2. Send a request which doesn't satisfy the dynamic predicate

In the process of fixing this bug, I also found that `excludedRoutes` cannot be cached correctly, and thus added it to the list of dynamic predicates.

We already have a mechanism to guard against incorrect routing from the cache layer using `ambiguousRoutes`.
I propose that we also add all routes with dynamic predicates to `ambiguousRoutes` to ensure all cached routes are present.

Modifications:

- Expose `Route#isCacheable`
- Use `Route#paramPredicates`, `Route#headerPredicates`, `Route#excludedRoutes` to check if a route has dynamic predicates
- Modify `resolveAmbiguousRoutes` to:
  - Extract routes with dynamic predicates
  - Extract all routes that have the same "routing key" as routes with dynamic predicates. This condition is needed because we can't differentiate from `routingCtx` between routes with and without dynamic predicates.
    - i.e. `/routeA` with `headerPredicate` vs. just `/routeA`

Result:

- Routes with dynamic predicates are not cached
- Closes #4927

### CODE REVIEW

**Comment by jrhee17** [comment]
(finally) ready for review 😄

**Review by minwoox — APPROVED** [review]
Sorry about the late review and this is a good approach to solve the problem. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/Route.java [hunk 1]
```diff
@@ -209,4 +213,18 @@ default RoutingResult apply(RoutingContext routingCtx) {
      * </ul>
      */
     Route withPrefix(String prefix);
+
+    /**
+     * A list of predicates used to determine whether a {@link Route} will accept a request
+     * based on its HTTP parameters.
+     */
+    @UnstableApi
+    List<? extends Predicate<QueryParams>> paramPredicates();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/Route.java:222]: I think the main problem is that `DefaultRoutingContext.equals()` excludes query params or headers from comparison. It makes sense since the cardinality could be huge and the cache hit ratio could be low.

Building `dynamicPredicateRoutes` as a separate list itself sounds also good. But `Route` should know if the route could be cacheable. So what do you think of adding `isCacheable()` property to `Route` instead?

Additionally, I am planning to change the type of `Predicate<QueryParams>` to a data structure instead of a function so that we can extract the properties to the service specification. There is also a need to minimize breaking change for type changes.

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/Route.java:222]: I understood your comment to just expose an `isCacheable` method instead of each `*predicates`.

Route.java
```java 
bool isCacheable() {
  return route.paramPredicates().isEmpty() &&
    route.headerPredicates().isEmpty() &&
    route.excludedRoutes().isEmpty());
}
```

Sure, I'm fine with either way

**Comment by minwoox** [comment]
Still LGTM. 👍

**Review by trustin — APPROVED** [review]
Neat and nice, @jrhee17! :+1:

File: core/src/main/java/com/linecorp/armeria/server/RouteCache.java [hunk 2]
```diff
@@ -128,7 +128,7 @@ public Routed<V> find(RoutingContext routingCtx) {
             }
 
             final Routed<V> result = delegate.find(routingCtx);
-            if (result.isPresent() && !ambiguousRoutes.contains(result.route())) {
+            if (result.isPresent() && !dynamicPredicateRoutes.contains(result.route())) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/RouteCache.java:131]: Could we just use `isCacheable()`?
```suggestion
            if (result.isPresent() && result.route().isCacheable()) {
```

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/RouteCache.java:131]: The worry I had was that it is possible that a cache key is the same between a cacheable route and a non-cacheable route.

> - Extract all routes that have the same "routing key" as routes with dynamic predicates. This condition is needed because we can't differentiate from `routingCtx` between routes with and without dynamic predicates.
>    - i.e. `/routeA` with `headerPredicate` vs. just `/routeA`

Let me know if you think this is not an issue though 😅

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/RouteCache.java]: Pushed your suggestion - if I remember the test suite failed, but I guess it's better to verify via CI

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/RouteCache.java:131]: Verified via CI run: https://github.com/line/armeria/actions/runs/5879154437?pr=4934

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/RouteCache.java:131]: I understood. 
Minor suggestion) Could we first check `isCachable()` and then check `dynamicPredicateRoutes` because `isCachable()` is cheaper? 
```
if (result.isPresent() && result.route().isCacheable() &&
    !dynamicPredicateRoutes.contains(result.route())) {
```

**Review by ikhoon — APPROVED** [review]
Thanks, @jrhee17! 🚀❤️
