### PR TITLE
Fix `FallbackService` not to raise `HttpStatusException`

### LINKED ISSUE #4548: Configure Armeria to Return gRPC Status Code for Invalid Path
## Overview

For an Armeria server that is built with minimal settings and has a simple `GrpcService`, the server returns only HTTP status code `404` but not any gRPC status such as `12` (UNIMPLEMENTED) when an invalid path is given.

Is there a way to configure the Armeria server so that it returns gRPC status code along with HTTP status?

## Examples

Below is an example server that uses `http4s-armeria` as backend:

```scala
import cats.effect.{ExitCode, IO, IOApp}
import org.http4s.armeria.server.ArmeriaServerBuilder

object Main extends IOApp {

  override def run(args: List[String]): IO[ExitCode] = {
    val grpcService = ??? // simple gRPC service defined somewhere else

    ArmeriaServerBuilder[IO]
      .bindHttp(9876, "0.0.0.0")
      .withHttpService(grpcService)
      .resource.useForever.as(ExitCode.Success)
  }
}
```

Example query command:

```shell
curl -v -H 'content-type: application/json' -d '{}' 'http://localhost:9876/io.test.NonExistentService/InvokeInvalidRpc'
```

In the output, only HTTP status `404` is available but there is no `grpc-status` in either the response headers or body.

## Use Case

For gRPC clients that stick to the protobuf service definitions strictly, it is unlikely for them to send requests with invalid paths.

However, for gRPC servers deployed to AWS and sitting behind an application load balancer, AWS performs health checks against targets at path `/AWS.ALB/healthcheck` and expects gRPC status `12` (UNIMPLEMENTED) by default if gRPC is used as the protocol version (see reference [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html#health-check-settings)). 

It'd be great if Armeria server could be configured to return gRPC status (such as `12`) for invalid paths.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

We decided not to use `HttpStatusException` and `HttpResponseException` internally because if an exception is thrown, it breaks through decorator chains and we can't use stream operators in `HttpResponse`. #4117 Thad said, `FallbackService` still throws deferred `HttpStatusException`s which we should've migrated in #4117 but omitted it.

Fixing the bug, I found out that there is a race condition between `FallbackService` and `Http*RequestDecoder`. If a request exceeds the maximum length limit, `Http*RequestDecoder` will return 413 Request Entity Too Large to the request. If a matching route is not found, `FallbackService` returns 404 Not Found. Armeria tests expect 404 for that case. 
https://github.com/line/armeria/blob/be306ab4c9de5386e74999baec5ebaae82618b91/core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java#L598-L605

It was possible since `FallbackService` threw an exception that aborts a request immediately.
https://github.com/line/armeria/blob/8aebaf475eeee1ee3fec6c7c876456878a8b423e/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L365-L372

If `FallbackService` returns a normal response, the request will be closed when a response is written completely. https://github.com/line/armeria/blob/8aebaf475eeee1ee3fec6c7c876456878a8b423e/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L422-L429
As a result, `Http*RequestDecoder` can return a 413
response to the request being handled by `FallbackService`.

 
Modification:

- Return a normal `HttpResponse` instead of throwing `HttpStatusException` in `FallbackService`.
  - A headers-only response is used to finish the response quickly before `Http*RequestDecoder` receives additional messages.
- Fixed `Http1RequestDecoder.fail()` to check if a response to the request was sent before to avoid duplicate responses.

Result:

- You no longer see `HttpStatusException` when there is no matching route.
- Fixes #4548

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/FallbackService.java [hunk 1]
```diff
@@ -35,9 +35,9 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exc
         final RoutingContext routingCtx = ctx.routingContext();
         final HttpStatusException cause = getStatusException(routingCtx);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/FallbackService.java:36]: How about also fixing `getStatusException` not creating `HttpStatusException` and use `HttpStatusException` only if `routingCtx.deferredStatusException()` returns it?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/FallbackService.java:36]: Sounds good.

File: core/src/main/java/com/linecorp/armeria/server/FallbackService.java [hunk 2]
```diff
@@ -33,44 +33,34 @@ private FallbackService() {}
...
         }
 
         final HttpStatusException cause = routingCtx.deferredStatusException();
-        if (cause == null) {
-            return HttpStatusException.of(HttpStatus.NOT_FOUND);
+        if (cause == null || cause.httpStatus() == HttpStatus.NOT_FOUND) {
+            return handleNotFound(ctx, routingCtx);
+        } else {
+            return HttpResponse.of(cause.httpStatus());
         }
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/FallbackService.java:47]: nit: return early?
```suggestion
        return HttpResponse.of(cause.httpStatus());
```

**Review by minwoox — APPROVED** [review]
Thanks a lot! 😄

**Comment by minwoox** [comment]
Oops let's fix the tests that failed. 😉

**Comment by ikhoon** [comment]
> Oops let's fix the tests that failed. 😉

😱😱😱

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 3]
```diff
@@ -260,17 +260,24 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
...
-                                                        .contentLength(req.headers())
-                                                        .transferred(transferredLength)
-                                                        .build();
-                        fail(id, decodedReq.headers(), HttpStatus.REQUEST_ENTITY_TOO_LARGE,
-                             Http2Error.CANCEL, null, cause);
-                        // Wrap the cause with the returned status to let LoggingService correctly log the
-                        // status.
-                        decodedReq.close(HttpStatusException.of(HttpStatus.REQUEST_ENTITY_TOO_LARGE, cause));
+                        final Routed<ServiceConfig> routed = req.route();
+                        if (routed != null && routed.route().isFallback()) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:264]: Question about the changed behavior:

If I understand correctly, when `decodedReq.needsAggregation()` is true then `ctx.fireChannelRead()` would be invoked late meaning that a client would need to wait until the entire request is received before receiving a 404 instead of an immediate 413.

Is this change intentional?

**Review by jrhee17 — COMMENTED** [review]
Looks good! Left a question about the changed behavior 🙏   Can you also check test failures?

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 3 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:264]: `FallbackService` does not set `decodedReq.needsAggregation()` to true. Did you mean a non-request service that returns 404 for a certain path?
The behavior of returning 404 for non-existent service has not changed.
https://github.com/line/armeria/blob/dc700253ad912f099445437cd5008b77c326b7fe/core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java#L598-L605

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:264]: > FallbackService does not set decodedReq.needsAggregation() to true.

Oops, I think you're right 😅 

Still, for instance if a global decorator is handling the request instead of `FallbackService` I'm wondering if just returning a 413 is more appropriate 🤔

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 4]
```diff
@@ -260,17 +260,25 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
...
+                            // Don't need to return an error response. `FallbackService` immediately respond to
+                            // the request without consuming data.
+                            this.req = null;
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:267]: Question) 

1) Is there no need to also close the request in case there are elements in the queue that need cleaning up? (e.g. callbacks waiting on a future that is never completed)
2) Is there no need to set `discarding = true` so that incoming `HttpMessage`s are ignored correctly?


```suggestion
                           discarding = true;
                            this.req.close();
                            this.req = null;
```

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 3 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:264]: Sorry, I didn't get this. It meant if a decorator is in the middle of handling a request, do we need to return 413? I'm not sure we can determine a response status by detecting a decorator which is handling a non-existent URL.

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 4 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:267]: > Is there no need to also close the request in case there are elements in the queue that need cleaning up? (e.g. callbacks waiting on a future that is never completed)

I thought the request is cleaned up when a response is successfully sent by `FallbackService`. However, if there is a decorator that aggregates the request, the future won't be completed until a timeout is triggered. For that case, `req.close()` makes sense.

> Is there no need to set discarding = true so that incoming HttpMessages are ignored correctly?

If a non-`HttpRequest` type object is received when `req` is null, the connection will be reset immediately. I hesitated to set `discarding` to true because `FallbackService` does not send `connection: close` to the client. Speaking of `connection: close`, it would be worth sending `connection: close` when a request content exceeds the limitation.

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 3 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:270]: I think you can ignore this comment, I think I misunderstood how the PR works 😅 

For some reason, I thought `atomicLong` in the following snippet would overflow over `maxRequestLength`.
It turns out with the current diff, all additional `HttpContent` will be ignored, so we don't have to worry about this case.

Sorry about the confusion 😅 

```
sb.decorator((delegate, ctx, req) -> {
    final AtomicLong atomicLong = new AtomicLong();
    req.subscribe(new Subscriber<HttpObject>() {
        @Override
        public void onSubscribe(Subscription s) {
            s.request(Long.MAX_VALUE);
        }

        @Override
        public void onNext(HttpObject httpObject) {
            if (httpObject instanceof HttpData) {
                atomicLong.addAndGet(((HttpData)httpObject).length());
                logger.info("current content size: {}", atomicLong);
            }
        }
    });
    return HttpResponse.delayed(HttpResponse.of(200), Duration.ofSeconds(3));
});
```

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 4 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:274]: > If a non-HttpRequest type object is received when req is null, the connection will be reset immediately

I encountered the following warning log with the test snippet. It seems like after the response is sent, another 400 is sent:
https://github.com/line/armeria/blob/f4781d52a34f874e9459994afd8de763c9608480/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L236
```
22:17:45.969 [armeria-common-worker-nio-2-2] WARN  c.l.a.client.Http1ResponseDecoder - Unexpected exception:
com.linecorp.armeria.common.ProtocolViolationException: unexpected message type: io.netty.handler.codec.http.DefaultLastHttpContent (expected: io.netty.handler.codec.http.HttpResponse, channel: [id: 0xa01f997d, L:/127.0.0.1:51010 ! R:127.0.0.1/127.0.0.1:51006], resId: 2)
	at com.linecorp.armeria.client.Http1ResponseDecoder.failWithUnexpectedMessageType(Http1ResponseDecoder.java:273)
```

Can you check the following snippet?

```
@RegisterExtension
static ServerExtension server = new ServerExtension() {
    @Override
    protected void configure(ServerBuilder sb) throws Exception {
        sb.requestTimeoutMillis(Long.MAX_VALUE);
        sb.idleTimeoutMillis(Long.MAX_VALUE);

        sb.maxRequestLength(100);
        sb.decorator((delegate, ctx, req) -> HttpResponse.delayed(HttpResponse.of(200), Duration.ofSeconds(3)));
        sb.decorator(LoggingService.builder()
                                   .successfulResponseLogLevel(LogLevel.DEBUG)
                                   .newDecorator());
        sb.service("/", (ctx, req) -> HttpResponse.of(200));
    }
};

@Test
void testMaxContentLength() {
    final HttpRequestWriter streaming = HttpRequest.streaming(HttpMethod.POST, "/not-exist");
    final HttpResponse response = WebClient.builder(SessionProtocol.H1C, server.endpoint(SessionProtocol.H1C))
                                           .writeTimeoutMillis(Long.MAX_VALUE)
                                           .responseTimeoutMillis(Long.MAX_VALUE)
                                           .build()
                                           .execute(streaming);
    for (int i = 0; i < 10; i++) {
        streaming.write(HttpData.ofUtf8(Strings.repeat("a", 30)));
    }
    streaming.close();
    System.out.println(response.aggregate().join());
}
```

**Comment by jrhee17** [comment]
> I rescheduled this to 1.22.0 to check it.

Checking in while going through the review queue, this isn't updated yet right? 😄

**Comment by ikhoon** [comment]
I didn’t update this yet. I will keep you updated when it is ready to review.

**Comment by ikhoon** [comment]
Let me update this PR when #4531 is merged.

**Comment by ikhoon** [comment]
Let me update this PR when #4531 is merged.

**Comment by minwoox** [comment]
#4531 is merged. 😉

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java (hunk 4 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java]: > Can you check the following snippet?

Checked in the tests and fixed Http{1,2}RequestDecoder to pass the tests.

**Review by minwoox — APPROVED** [review]
Thanks! 👍 👍 👍

**Review by jrhee17 — APPROVED** [review]
The fix makes sense to me 👍    Thanks @ikhoon ! 🙇 💯 🚀

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 5]
```diff
@@ -138,20 +138,23 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
                     if (!nettyReq.decoderResult().isSuccess()) {
                         final Throwable cause = nettyReq.decoderResult().cause();
                         if (cause instanceof TooLongHttpLineException) {
-                            fail(id, null, HttpStatus.REQUEST_URI_TOO_LONG, "Too Long URI", cause);
+                            fail(id, null, HttpStatus.REQUEST_URI_TOO_LONG, Http2Error.FRAME_SIZE_ERROR,
+                                 "Too Long URI", cause);
                         } else if (cause instanceof TooLongHttpHeaderException) {
                             fail(id, null, HttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE,
-                                 "Request Header Fields Too Large", cause);
+                                 Http2Error.FRAME_SIZE_ERROR, "Request Header Fields Too Large", cause);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:145]:
```suggestion
                                 Http2Error.FRAME_SIZE_ERROR, "Request header fields too large", cause);
```

**Review by trustin — APPROVED** [review]
Nice job! :+1:
