### PR TITLE
Fix a false-positive context leak error when using `RetryingClient`

### LINKED ISSUE #6420: False-positive RequestContext leak warning when using `RetryingClient`
When a `ServiceRequestContext` is pushed, Armeria validates it against any existing `ClientRequestContext` stored in the thread-local.
https://github.com/line/armeria/blob/95ed9e1cfb075da4f04d7e5d5fa5adc63627282d/core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java#L241
If `ClientRequestContext.root()` is null, the validation logic throws an `IllegalStateException` since it thinks the context is leaked.

Normally, `ClientRequestContext.root()` is set when a client is executed within a service, so this check works as expected.
https://github.com/line/armeria/blob/35126bde9731871fa00907d83b34e6aa1468207d/core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java#L256-L260
However, if a client request is executed outside a ServiceRequestContext, which can easily happen during asynchronous composition, then ClientRequestContext.root() remains null.
```java
clientA.execute()
       .thenComposeAsync(unused -> clientB.execute());
```
In such cases, even though the request was initiated and completed from a valid `ServiceRequestContext`, Armeria incorrectly reports a request context leak.

This issue is especially reproducible with `RetryingClient`. Since its responses are completed on a context-aware event loop, a `ClientRequestContext` is always present in the thread-local.
https://github.com/line/armeria/blob/1051e9650432a90f0d4ee8e296f6d37166ec4710/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L246
That is triggering the problematic validation. In contrast, without `RetryingClient`, responses complete on the channel’s event loop and the warning does not occur.
https://github.com/line/armeria/blob/603fc8685059ffafed5096261a14fd502f0be33f/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L286-L288

I do think that Armeria should not report a RequestContext leak when the client request actually starts and completes within a valid service scope.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

Please refer to #6420 for a detail explanation of the problem.

Modifications:

- When `ServiceRequestContext` is pushed, no exception is thrown if the `root()` of the current `ClientRequestContext` is null, since it is not considered a context leak.

Result:

- `RetryingClient` no longer raises a false-positive context leak error.
- Closes #6420

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
👍 👍

File: core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientContextLeakTest.java [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+    private static class MyService {
+        private final WebClient backendClient;
+
+        MyService(WebClient backendClient) {
+            this.backendClient = backendClient;
+        }
+
+        @Get("/")
+        public CompletionStage<String> myMethod() {
+            // Execute an in non-context aware thread to make ClientRequestContext.root() return null.
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientContextLeakTest.java]:
```suggestion
            // Execute in a non-context aware thread to make ClientRequestContext.root() return null.
```
