### PR TITLE
Do not throw exception when annotated service returns `Nothing`

### LINKED ISSUE #3961: `Nothing` in Kotlin annotated rest method throws exception
Having a rest method returning `Nothing` throws an Exception with during init with Armeria 1.13.3. It used to work fine with Armeria 1.9.2. The problem can easily be circumvented by returning `Unit` or `String`.

The method is used to assert that our exception mappers works correctly.

```Kotlin
@PathPrefix("/test/")
class ArmeriaExceptionThrowTestRest {
    @Public
    @Get("/throw/armeria/{exceptionClass}")
    suspend fun armeriaThrow(@Param("exceptionClass") exceptionClass: String): Nothing {
        throw Class.forName(exceptionClass).getConstructor(String::class.java).newInstance("This was Armeria throwing") as Throwable
    }
}
```

The whole stack:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.linecorp.armeria.internal.server.annotation.KotlinUtil.kFunctionGenericReturnType(KotlinUtil.java:203)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.getActualReturnType(AnnotatedService.java:236)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.responseConverter(AnnotatedService.java:202)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.<init>(AnnotatedService.java:159)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.lambda$create$4(AnnotatedServiceFactory.java:326)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.create(AnnotatedServiceFactory.java:331)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.lambda$find$0(AnnotatedServiceFactory.java:184)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.find(AnnotatedServiceFactory.java:187)
	at com.linecorp.armeria.server.AnnotatedServiceBindingBuilder.buildServiceConfigBuilder(AnnotatedServiceBindingBuilder.java:286)
	at com.linecorp.armeria.server.VirtualHostBuilder.lambda$build$8(VirtualHostBuilder.java:1034)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.server.VirtualHostBuilder.build(VirtualHostBuilder.java:1046)
	at com.linecorp.armeria.server.ServerBuilder.buildServerConfig(ServerBuilder.java:1711)
	at com.linecorp.armeria.server.ServerBuilder.build(ServerBuilder.java:1695)
        at Redacted(Redacted.kt:1)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at Redacted(Redacted.kt:1)
	at org.glassfish.jersey.test.RestTest$client$2.invoke(RestTest.kt:61)
	at org.glassfish.jersey.test.RestTest$client$2.invoke(RestTest.kt:49)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.glassfish.jersey.test.RestTest.getClient(RestTest.kt)
	at org.glassfish.jersey.test.RestTest.target(RestTest.kt:76)
	at org.glassfish.jersey.test.RestTest.target$default(RestTest.kt:76)
	at org.glassfish.jersey.test.RestTest.newResource(RestTest.kt:109)
        at Redacted(Redacted.kt:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.util.NoSuchElementException: Array is empty.
	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1013)
	at kotlin.reflect.jvm.internal.KCallableImpl.extractContinuationArgument(KCallableImpl.kt:213)
	at kotlin.reflect.jvm.internal.KCallableImpl.access$extractContinuationArgument(KCallableImpl.kt:23)
	at kotlin.reflect.jvm.internal.KCallableImpl$_returnType$1$1.invoke(KCallableImpl.kt:77)
	at kotlin.reflect.jvm.internal.KCallableImpl$_returnType$1$1.invoke(KCallableImpl.kt:23)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.KTypeImpl.getJavaType(KTypeImpl.kt:48)
	at kotlin.reflect.jvm.ReflectJvmMapping.getJavaType(ReflectJvmMapping.kt:81)
	at com.linecorp.armeria.internal.common.kotlin.ArmeriaKotlinUtil.kFunctionGenericReturnType(ArmeriaKotlinUtil.kt:57)
	... 90 more`

### PR DESCRIPTION
**Pull request by jupiny**
Motivation:

- https://github.com/line/armeria/issues/3961

Modifications:

- If the return type of `AnnotatedService` method is `Nothing`, use `kFunctionReturnType()` exceptionally instead of `kFunctionGenericReturnType()`

Result:

- Closes #3961
- The exception is not thrown when annotated service returns `Nothing`

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java [hunk 1]
```diff
@@ -231,7 +231,7 @@ private static Type getActualReturnType(Method method) {
         final Class<?> returnType;
         final Type genericReturnType;
 
-        if (KotlinUtil.isSuspendingFunction(method)) {
+        if (KotlinUtil.isSuspendingFunction(method) && !KotlinUtil.isReturnTypeNothing(method)) {
```
Comment (jupiny) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:234]: I thought this workaround can be solution for this issue, but if there is any better idea, please advice me freely 🙇

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:234]: The workaround looks good to me.
@ks-yim Could you review this PR?

**Comment by ikhoon** [comment]
Some tests were failed. 
https://github.com/line/armeria/runs/4663671976?check_suite_focus=true#step:6:1575

**Comment by jupiny** [comment]
Oh.. let me check it.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 1 above)
Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:234]: Looks good to me, too but we should do the same thing at `AnnotatedDocServicePlugin.java:L159 `.

BTW, I've just found that `DocService` shows `Unit` return type correctly for suspending functions while it shows `void` for normal kotlin functions 😂..

Maybe we can introduce `isKFunction` method and use it instead of `isSuspendingFunction` here and `AnnotatedDocServicePlugin` to show the correct return type? (if it worth the effort, though)

**Comment by ks-yim** [comment]
The test is failing due to this https://github.com/line/armeria/pull/4005#discussion_r776606844.

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java (hunk 1 above)
Comment (jupiny) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:234]: Thank you for suggestion, @ks-yim :) Do you mean the method like it?

```kotlin
// ArmeriaKotlinUtil.kt
internal fun isKFunction(method: Method): Boolean {
    return method.kotlinFunction != null && !isReturnTypeNothing(method)
}
```

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:234]: @jupiny 
Just...:
```kotlin
// ArmeriaKotlinUtil.kt
internal fun isKFunction(method: Method): Boolean {
    return method.kotlinFunction != null
}
```
and use it instead of `isSuspendingFunction` leaving `isReturnTypeNothing` as it currently is.

Comment (jupiny) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:234]: Ah, actually I tried so, but `Nothing` method is still considered as `kFunction`)(`method.kotlinFunction` is not null). So it makes the same problem. 🤔
If my understand is wrong, please let me know. 😭

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java:234]: @jupiny Sorry to confuse you.

What I meant was it would be better to do the following to get the correct return type though it's a bit out of the scope of this PR.. 😅;;

...at `AnnotatedService.java:L234`:
```kotlin
if (KotlinUtil.isKFunction(method) && !KotlinUtil.isReturnTypeNothing(method)) {
    // Use kotlin reflection
} else {
    // Use Java reflection
}
```

...and this at `AnnotatedDocServicePlugin:L158`:
```kotlin
final TypeSignature returnTypeSignature =
        isKFunction(method) ? toTypeSignature(kFunctionGenericReturnType(method))
                            : toTypeSignature(method.getGenericReturnType());
```

Comment (jupiny) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java]: Aha, I misunderstand a little. Updated following your comments!

File: examples/annotated-http-service-kotlin/src/test/kotlin/example/armeria/server/annotated/kotlin/AnnotatedServiceTest.kt [hunk 2]
```diff
@@ -53,4 +53,12 @@ class AnnotatedServiceTest {
...
         }
     }
+
+    @Test
+    fun testNothingReturnType() {
+        val client = client()
+        client.get("/throw/error").aggregate().join().let {
+            assertThat(it.status()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR)
+        }
+    }
```
Comment (ikhoon) [inline examples/annotated-http-service-kotlin/src/test/kotlin/example/armeria/server/annotated/kotlin/AnnotatedServiceTest.kt:63]: Could you move the test cases under https://github.com/line/armeria/tree/e294957e2999d361c3a2450ac85a2b54c1d2322b/kotlin/src/test/kotlin/com/linecorp/armeria/server?

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java [hunk 3]
```diff
@@ -156,8 +157,10 @@ private static void addMethodInfo(Map<Class<?>, Set<MethodInfo>> methodInfos,
         final Method method = service.method();
         final String name = method.getName();
         final TypeSignature returnTypeSignature =
-                isSuspendingFunction(method) ? toTypeSignature(kFunctionGenericReturnType(method))
-                                             : toTypeSignature(method.getGenericReturnType());
+                isKFunction(method) && !isReturnTypeNothing(method) ? toTypeSignature(
+                        kFunctionGenericReturnType(method))
+                                                                    : toTypeSignature(
+                        method.getGenericReturnType());
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:163]: Could you introduce a private method for readability?

**Review by ikhoon — COMMENTED** [review]
Mostly looking good! Left minor comments.

**Comment by trustin** [comment]
Question: What happens if `Nothing`-returning suspended function calls another suspended function that actually does *something* before throwing? Can we still treat it as a non-suspended function? e.g.

```kotlin
suspended fun foo(): Nothing {
    bar()
    throw ...
}

suspended fun bar(): SomeResult {
    // .. do some socket I/O ..
}
```

**Comment by ks-yim** [comment]
@trustin as far as I know, `AnnotatedService` for `suspend func foo(): Nothing` will still have `isKotlinSuspendingMethod` flag as `true` which will make the method invoked on kotlin coroutines.

This PR is just about detecting the right return type, which will then be used to judge which `ResponseConverterFunction` should be applied`, for suspending functions (with additional fix for `DocService`).

**Comment by trustin** [comment]
@ks-yim Ah, OK, then. :slightly_smiling_face:

**Review by trustin — APPROVED** [review]
Thanks @jupiny for all you did for Armeria including this pull request as well as your blog posts. Looking forward to more activity from you :laughing:

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java (hunk 3 above)
Comment (jupiny) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java]: Updated

File: examples/annotated-http-service-kotlin/src/test/kotlin/example/armeria/server/annotated/kotlin/AnnotatedServiceTest.kt (hunk 2 above)
Comment (jupiny) [reply examples/annotated-http-service-kotlin/src/test/kotlin/example/armeria/server/annotated/kotlin/AnnotatedServiceTest.kt]: Thank you for advice. I moved it.

**Review by ikhoon — APPROVED** [review]
Thanks, @jupiny! 🎉

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java [hunk 4]
```diff
@@ -170,6 +169,13 @@ private static void addMethodInfo(Map<Class<?>, Set<MethodInfo>> methodInfos,
                 });
     }
 
+    private static TypeSignature getReturnTypeSignature(Method method) {
+        if (isKFunction(method) && !isReturnTypeNothing(method)) {
+            return toTypeSignature(kFunctionGenericReturnType(method));
+        }
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:175]: nit; should we call `kFunctionReturnType` if `Nothing` type for more accurate representation in our doc services?

i.e.

```suggestion
        if (isKFunction(method)) {
            if (isReturnTypeNothing(method)) {
                return toTypeSignature(kFunctionReturnType(method));
            }
            return toTypeSignature(kFunctionGenericReturnType(method));
        }
```

**Review by jrhee17 — APPROVED** [review]
Looks great! Thank you @jupiny 👍 🙇 🎉

File: core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java (hunk 4 above)
Comment (jupiny) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:175]: Seems better to use `kFunctionReturnType` for `Nothing` as you commented. 🤔 
Let me update too.

Comment (jupiny) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java:175]: Seems better to use `kFunctionReturnType` for `Nothing`.
Let me update it too.

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java]: Wouldn't this throw an exception, though? (And this was the motivation of this PR).

Comment (ks-yim) [reply core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java]: But, the return type will be just `Void` not `Nothing` even if we do this.

File: kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt [hunk 5]
```diff
@@ -19,25 +19,11 @@ package com.linecorp.armeria.server.kotlin
 import com.fasterxml.jackson.databind.ObjectMapper
 import com.fasterxml.jackson.databind.SerializationFeature
 import com.linecorp.armeria.client.WebClient
-import com.linecorp.armeria.common.AggregatedHttpResponse
-import com.linecorp.armeria.common.HttpHeaders
-import com.linecorp.armeria.common.HttpResponse
-import com.linecorp.armeria.common.HttpStatus
-import com.linecorp.armeria.common.MediaType
-import com.linecorp.armeria.common.ResponseHeaders
+import com.linecorp.armeria.common.*
```
Comment (minwoox) [inline kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt:22]: Could you rever this? we don't use a wildcard for import statements.

File: kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt [hunk 6]
```diff
@@ -19,25 +19,11 @@ package com.linecorp.armeria.server.kotlin
...
-import com.linecorp.armeria.server.annotation.Delete
-import com.linecorp.armeria.server.annotation.ExceptionHandlerFunction
-import com.linecorp.armeria.server.annotation.Get
-import com.linecorp.armeria.server.annotation.HttpResult
-import com.linecorp.armeria.server.annotation.JacksonResponseConverterFunction
-import com.linecorp.armeria.server.annotation.Param
-import com.linecorp.armeria.server.annotation.ProducesJson
-import com.linecorp.armeria.server.annotation.ResponseConverterFunction
-import com.linecorp.armeria.server.annotation.ResponseConverterFunctionProvider
+import com.linecorp.armeria.server.annotation.*
```
Comment (minwoox) [inline kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt:26]: Could you rever this? we don't use a wildcard for import statements.

**Review by minwoox — APPROVED** [review]
Thanks! Left some trivial comments. 😉

**Comment by ikhoon** [comment]
Nice work! 🎉🎉🎉
