### PR TITLE
Fix that `WebSocketService` rejects headers that have multiple values

### LINKED ISSUE #5165: Firefox fails to establish a websocket connection to Armeria Websocket Server
The following code in Firefox fails with a `BAD_REQUEST` when connecting to an Armeria Websocket Server:
```
const socket = new WebSocket("ws://localhost:8080/chat")
socket.addEventListener("open", (event) => {
    console.log(event)
})
```
The reason for the rejection is that Armeria checks for the presence of the `Connection` header which must contain the value `Upgrade`. However Firefox sends the `Connection` header with the `keep-alive, Upgrade` value.
The websocket specification ([section 4.1 page 18](https://datatracker.ietf.org/doc/html/rfc6455#section-4.1) says `The request MUST contain a |Connection| header field whose value MUST include the "Upgrade" token.` So I believe it's allowed to have multiple values in here.

Removal of the `Connection` header happens here: https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java#L732
Rejection of the request happens here: https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java#L42

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
As described in #5165, `Connection` header for a WebSocket upgrade request can have multiple values.

Modifications:
- Establish a WebSocket session if the `Connection` and `Upgrade` headers contain the required value.

Result:
- Close #5165
- A WebSocket session is correctly established if the `Connection` and `Upgrade` headers contain the required value.

To-do:
- Add IT tests that establish WebSocket from FireFox and Chrome.

### CODE REVIEW

**Review by jrhee17 — APPROVED** [review]
Looks good 👍   Thanks for the quick fix @minwoox 🙇 👍 🙇

File: core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java [hunk 1]
```diff
@@ -46,8 +51,66 @@ public static boolean isHttp1WebSocketUpgradeRequest(RequestHeaders headers) {
...
         // ...
         return headers.method() == HttpMethod.GET &&
-               HttpHeaderValues.UPGRADE.contentEqualsIgnoreCase(headers.get(HttpHeaderNames.CONNECTION)) &&
-               HttpHeaderValues.WEBSOCKET.contentEqualsIgnoreCase(headers.get(HttpHeaderNames.UPGRADE));
+               containsValue(headers, HttpHeaderNames.CONNECTION, HttpHeaderValues.UPGRADE, true) &&
+               containsValue(headers, HttpHeaderNames.UPGRADE, HttpHeaderValues.WEBSOCKET, true);
+    }
+
+    // Forked from https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpHeaders.java#L1597-L1651
+    private static boolean containsValue(RequestHeaders headers, CharSequence name,
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java:59]: Q: Is it worth adding this to `HttpHeaders` as a public API?

**Review by ikhoon — APPROVED** [review]
Thanks, @minwoox! 🙇‍♂️

File: core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java (hunk 1 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java:59]: That's a good suggestion. 👍 Let me handle it in a separate PR because `QueryParamGetters` needs a different logic for the method. 😉

**Comment by minwoox** [comment]
Thanks for reviewing. 😉
