### PR TITLE
Close completed response before trying to abort its corresponding request

### LINKED ISSUE #630: Flaky test: HttpServerTest.testTooLargeContent
```
com.linecorp.armeria.server.http.HttpServerTest > testTooLargeContent[0: h1c] FAILED
    java.util.concurrent.ExecutionException: com.linecorp.armeria.common.ClosedSessionException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at com.linecorp.armeria.server.http.HttpServerTest.testTooLargeContent(HttpServerTest.java:516)
        Caused by:
        com.linecorp.armeria.common.ClosedSessionException
```
https://ci.appveyor.com/project/trustin/armeria/build/master.591#L623

### PR DESCRIPTION
**Pull request by hyangtack**
Motivation:
When HttpResponseWrapper is closed, it also aborts the corresponding request and the response is finally closed with a cause by HttpRequestSubscriber#failAndRespond via HttpRequestSubscriber#onError.
However, we should normally close it without a cause if the response has been completed. So we should give a chance to the HttpResponseWrapper to close the response normally before aborting the request.

Modifications:
- Call `request.abort()` after `delegate.close()` in HttpResponseDecoder.
- Close a request instead of aborting if the request is only handled by HttpServerHandler.

Result:
Closes #630

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java [hunk 1]
```diff
@@ -56,7 +56,7 @@ default boolean write(Supplier<? extends T> o) {
     }
 
     /**
-     * Performs the specified {@code task} when there's enough demans from the {@link Subscriber}.
+     * Performs the specified {@code task} when there's enough demands from the {@link Subscriber}.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java]: - there's -> there are

**Comment by trustin** [comment]
Finally! 🙌
