### PR TITLE
Fix a bug where a request has failed to be routed when both a '/path' and a '/{var}' path mappings exist with different HTTP methods

### LINKED ISSUE #3330: `405 Method Not Allowed` if defines both exact path and param path
I found a path parsing bug for Armeria:

`405 Method Not Allowed` will be responded if we defined the path like the following and request `DELETE /test`.

```kotlin
        @Get("/test")
        public String getTest() {
            return "GET /test";
        }

        @Delete("/{id}")
        public String deleteId(@Param String id){
            return "DELETE /{id="$id"}";
        }
```

### PR DESCRIPTION
**Pull request by hyangtack**
Motivation:
Currently `RoutingTrie` can find a route only based on the request path. But there's lots of conditions
used to resolve a correct path such as HTTP methods, content-type header, accept header, and even
a certain HTTP header and/or parameter.
So we need to check whether a route is acceptable for the request or not earlier than now,
in order to avoid picking up wrong routes.

Modifications:
- Introduce `NodeProcessor<?>` and pass a node into it when the node is selected as a candidate.
- Create a `RouteCandidateCollectingNodeProcessor` and pass it to `RoutingTrie#find` method when finding
  `ServiceConfig` instances from `RoutingTrie`.
  - It holds `Routed` instances resolved while visiting the trie.
  - If a node is not acceptable for the request, it would be dropped.
- Create a new fallback route if the original route does not support all HTTP methods.
   The fallback `ServiceConfig` would be served on the fallback route.
- Use `isFallback` value defined in a `DefaultRoute` in order to avoid propagating
  an exception raised while resolving a route to fallback services.
  - For example, assume that a route `/a/b/c/` supports HTTP GET method only. Its fallback route would
    be added like `/a/b/c` with supporting HTTP GET method as well.
    In this case, `404 not found` would be better other than `405 method not allowed` if a request is
    coming like `DELETE /a/b/c`, because the fallback route wasn't specified by a user.

Result:
- Closes #3330

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java [hunk 1]
```diff
@@ -62,42 +66,73 @@
...
     }
 
+    /**
+     * Returns the list of {@link Routed}s which are mapped to the given {@link RoutingContext}.
+     */
+    List<Routed<V>> findAllRoutes(RoutingContext routingCtx) {
+        final ImmutableList.Builder<Routed<V>> routeAccumulator = new Builder<>();
+        findAllNodes(routingCtx, false, routeAccumulator);
+        return routeAccumulator.build();
+    }
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java:117]: Is it okay to replace the existing `find*` methods with these newly added ones?
Please let me know what you think/concern. :-)

File: core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java [hunk 2]
```diff
@@ -225,6 +288,33 @@ private void findAllNodes(Node<V> node, String path, int begin, boolean exact,
...
+                                         @Nullable ImmutableList.Builder<Routed<V>> routeAccumulator) {
+        final List<Routed<V>> routingResults =
+                node.values.stream()
+                           // TODO(hyangtack) Add dryRun parameter to Route.apply
+                           //                 Pass it as true if routeAccumulator is null
+                           //                 not to set deferred exception to context.
+                           .map(v -> {
+                               final Route route = routeResolver.apply(v);
+                               final RoutingResult result = route.apply(routingCtx, isRouteDecorator);
+                               return result.isPresent() ? Routed.of(route, result, v) : null;
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java:304]: Do I need to add `dryRun` mode to `Route` to avoid setting deferred exception to `RoutingContext`?
I guess it's not necessary because we use `RoutingTrie` only for routing a request. Please let me know if I missed something. :-)

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 3]
```diff
@@ -285,44 +315,51 @@
      */
     private static <V> Routed<V> findBest(RoutingContext routingCtx, @Nullable List<V> values,
                                           Function<V, Route> routeResolver) {
+        if (values == null) {
+            return Routed.empty();
+        }
+        return findBest(findAll(routingCtx, values, routeResolver, false));
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java:321]: What's the expected performance hit we're gonna have? Doesn't this mean we have to get the complete list of routing results for all possible routes first?

Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:321]: It's a naming problem. It actually converts all `ServiceConfig` instances into `Routed` instances, not getting all possible routes. Let me change the method name. :-)

File: core/src/test/java/com/linecorp/armeria/server/HttpServerAutoRedirectTest.java [hunk 4]
```diff
@@ -61,9 +61,6 @@ protected void configure(ServerBuilder sb) throws Exception {
             // returning `202 Accepted`.
             sb.service("/f/", service);
             sb.routeDecorator().pathPrefix("/f/").build((delegate, ctx, req) -> HttpResponse.of(202));
-
-            // This should never be invoked in this test.
-            sb.serviceUnder("/", service);
```
Comment (hyangtack) [inline core/src/test/java/com/linecorp/armeria/server/HttpServerAutoRedirectTest.java:66]: @trustin I removed this line because of the following test:
```
            // `GET /e` should be redirected to `/e/`.
            // `DELETE /e` should NOT be redirected to `/e/`.
            sb.route().get("/e/").build(service);
```
Because my fix made `/e/`'s fallback route support HTTP GET only. So the request would be routed the '/' service. Please let me know if I'm wrong. 😄

**Comment by hyangtack** [comment]
@trustin @ikhoon @minwoox Gentle ping 😄

**Comment by ikhoon** [comment]
Sorry. 😭 I will review this today! 🔥

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 5]
```diff
@@ -392,7 +453,7 @@ public void dump(OutputStream output) {
 
         @Override
         public List<Routed<V>> findAll(RoutingContext routingCtx) {
-            return Routers.findAll(routingCtx, values, routeResolver, isRouteDecorator);
+            return Routers.valuesToRoutedList(routingCtx, values, routeResolver, isRouteDecorator);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java:456]:
```suggestion
            return valuesToRoutedList(routingCtx, values, routeResolver, isRouteDecorator);
```

**Comment by minwoox** [comment]
Sorry for the late review. 😄

File: core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java [hunk 6]
```diff
@@ -252,11 +266,24 @@ public boolean equals(@Nullable Object o) {
...
+               setDeferredException == that.setDeferredException;
     }
 
     @Override
     public String toString() {
         return patternString();
     }
+
+    @Override
+    public RouteBuilder toBuilder() {
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java:279]: Ok! :-)

File: core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java [hunk 7]
```diff
@@ -413,6 +415,15 @@ RouteBuilder matchesHeaders(List<RoutingPredicate<HttpHeaders>> headerPredicates
         return this;
     }
 
+    /**
+     * Sets whether the {@link Route} would set a deferred exception to a {@link RoutingContext} instance.
+     * Currently, it is used only when configuring {@link Route}s to fallback services.
+     */
+    RouteBuilder setDeferredExceptionToRoutingContext(boolean setDeferredException) {
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java:422]: It looks better. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/Routers.java (hunk 5 above)
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:456]: Thanks!

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 8]
```diff
@@ -285,53 +315,60 @@
...
                 }
             }
         }
         return result;
     }
 
-    private static <V> List<Routed<V>> findAll(RoutingContext routingCtx, List<V> values,
-                                               Function<V, Route> routeResolver,
-                                               boolean isRouteDecorator) {
+    private static <V> List<Routed<V>> valuesToRoutedList(RoutingContext routingCtx, List<V> values,
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:369]: Sorry, I didn't think about that enough. How about `getRouteCandidates()`?

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 9]
```diff
@@ -358,19 +395,43 @@
...
         }
 
         @Override
         public void dump(OutputStream output) {
             trie.dump(output);
         }
+
+        private final class ResultCachingNodeProcessor implements NodeProcessor<V> {
+            private final RoutingContext routingCtx;
+            private final ImmutableList.Builder<Routed<V>> routeCollector = new Builder<>();
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:416]: Fixed. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 10]
```diff
@@ -285,53 +315,60 @@
...
         return result;
     }
 
-    private static <V> List<Routed<V>> findAll(RoutingContext routingCtx, List<V> values,
-                                               Function<V, Route> routeResolver,
-                                               boolean isRouteDecorator) {
+    private static <V> List<Routed<V>> valuesToRoutedList(RoutingContext routingCtx, List<V> values,
+                                                          Function<V, Route> routeResolver,
+                                                          boolean isRouteDecorator) {
         final ImmutableList.Builder<Routed<V>> builder = ImmutableList.builderWithExpectedSize(values.size());
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:372]: Fixed. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 11]
```diff
@@ -285,53 +315,60 @@
      */
     private static <V> Routed<V> findBest(RoutingContext routingCtx, @Nullable List<V> values,
                                           Function<V, Route> routeResolver) {
+        if (values == null) {
+            return Routed.empty();
+        }
+        return findBest(valuesToRoutedList(routingCtx, values, routeResolver, false));
+    }
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:322]: Fixed. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/Route.java [hunk 12]
```diff
@@ -95,6 +95,11 @@ default RoutingResult apply(RoutingContext routingCtx) {
      */
     RoutingResult apply(RoutingContext routingCtx, boolean isRouteDecorator);
 
+    /**
+     * Returns the {@link PathMapping} of this {@link Route}.
+     */
+    PathMapping pathMapping();
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Route.java]: Removed this method and fixed the following lines:
https://github.com/line/armeria/pull/3340/files#diff-d94019f9ef8458d0b4a04a1be6e2a6ebaf9f85cbab92e2ac6bc6bc42f89f0d2bR81-R96

Is it okay if I use `CatchAllPathMapping.INSTANCE` directly from there? I'm not sure, but I think the fallback route's `PathMapping` must be `CatchAllPathMapping` because `/a/`'s fallback path is always `/a`. So I think it would be better to use `CatchAllPathMapping.INSTANCE` rather than making `PathMapping` public. Please let me know what you think. 🙇‍♂️

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 13]
```diff
@@ -71,13 +76,29 @@
...
+                    final Route fallbackRoute = fallbackServiceConfig.route();
+                    if (originalRoute.complexity() != fallbackRoute.complexity() ||
+                        !originalRoute.methods().containsAll(fallbackRoute.methods())) {
+                        return fallbackServiceConfig.withRoute(
+                                originalRoute.toBuilder()
+                                     .pathMapping(fallbackRoute.pathMapping())
+                                     // Do not propagate an exception raised while resolving a route
+                                     // to fallback services.
+                                     .setDeferredExceptionToRoutingContext(false)
+                                     .build());
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java]: Thanks! From the point of view of the number of route instances, I think yes. Let me add a simple cache for routes.

[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java]: Added https://github.com/line/armeria/pull/3340/commits/822f84fa74104614831029ad6ead9ca2cf4fdc3b

File: core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java [hunk 14]
```diff
@@ -413,6 +415,15 @@ RouteBuilder matchesHeaders(List<RoutingPredicate<HttpHeaders>> headerPredicates
         return this;
     }
 
+    /**
+     * Sets whether the {@link Route} would set a deferred exception to a {@link RoutingContext} instance.
+     * Currently, it is used only when configuring {@link Route}s to fallback services.
+     */
+    RouteBuilder canSetDeferredException(boolean setDeferredException) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java:422]: Suggestion: `allowDeferredException(boolean allowDeferredException)`?

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 15]
```diff
@@ -71,13 +77,41 @@
...
+                                         // Do not propagate an exception raised while resolving a route
+                                         // to fallback services.
+                                         .canSetDeferredException(false)
+                                         .build();
+                    final Route cachedRoute = newFallbackRoutes.get(newFallbackRoute);
+                    if (cachedRoute != null) {
+                        return fallbackServiceConfig.withRoute(cachedRoute);
+                    }
+                    newFallbackRoutes.put(newFallbackRoute, newFallbackRoute);
+                    return fallbackServiceConfig.withRoute(newFallbackRoute);
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java:105]: Maybe this is wrong.
- This function maybe be called in multiple threads.
- On the second thought(😅), is it better to cache `fallbackServiceConfig`s?
```java
final Map<Route, ServiceConfig> newFallbackServiceConfigs = new ConcurrentHashMap<>();
final BiFunction<Route, ServiceConfig, ServiceConfig> fallbackValueConfigurator =
        (originalRoute, fallbackServiceConfig) -> {

final ServiceConfig cachedFallbackConfig = newFallbackServiceConfigs.get(originalRoute);
if (cachedFallbackConfig != null) {
    return cachedFallbackConfig;
}

final Route newFallbackRoute =
        originalRoute.toBuilder()
                     .pathMapping(CatchAllPathMapping.INSTANCE)
                     // Do not propagate an exception raised while resolving a route
                     // to fallback services.
                     .canSetDeferredException(false)
                     .build();
final ServiceConfig newFallbackConfig = fallbackServiceConfig.withRoute(newFallbackRoute);
newFallbackServiceConfigs.put(originalRoute, newFallbackConfig);
return newFallbackConfig;
}
```

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 16]
```diff
@@ -283,65 +326,66 @@
...
             }
         }
         return result;
     }
 
-    private static <V> List<Routed<V>> findAll(RoutingContext routingCtx, List<V> values,
-                                               Function<V, Route> routeResolver,
-                                               boolean isRouteDecorator) {
-        final ImmutableList.Builder<Routed<V>> builder = ImmutableList.builderWithExpectedSize(values.size());
+    private static <V> List<Routed<V>> getRouteCandidates(RoutingContext routingCtx, List<V> values,
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java:371]: `getRouteCandidates` sounds good to me. 👍

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 17]
```diff
@@ -358,19 +402,50 @@
...
+            @Override
+            public Node<V> process(Node<V> node) {
+                final List<Routed<V>> list =
+                        getRouteCandidates(routingCtx, node.values, routeResolver, isRouteDecorator);
+                if (list.isEmpty()) {
+                    // Not acceptable node.
+                    return null;
+                }
+                if (routeCollector == null) {
+                    routeCollector = new Builder<>();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java:443]: nit:
```suggestion
                    routeCollector = ImmutableList.builder();
```

**Review by ikhoon — COMMENTED** [review]
Mostly looking good.

File: core/src/main/java/com/linecorp/armeria/server/Routers.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java]: >  How about getRouteCandidates()? 

Sounds good!

File: core/src/main/java/com/linecorp/armeria/server/Routers.java (hunk 16 above)
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:371]: Thanks!

File: core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java (hunk 14 above)
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java:422]: It'd be better name. Thank you, professor! 
Will change the method name as well.

File: core/src/main/java/com/linecorp/armeria/server/Routers.java (hunk 15 above)
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:105]: Fixed. Thanks!!

File: core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java (hunk 14 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java]: I'm happy if the suggestion was good. 

> Thank you, professor!

🤣

**Comment by trustin** [comment]
@hyangtack Sorry, but would you mind merging master to resolve the conflicts? :sweat_smile:

File: core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java [hunk 18]
```diff
@@ -48,11 +48,13 @@
     private final int hashCode;
     private final int complexity;
 
+    private final boolean allowDeferredException;
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java:51]: Would it be better choice if I use `isFallback` variable instead of this variable? 🤔

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 19]
```diff
@@ -71,13 +76,44 @@
...
+
+                    if (originalRoute.complexity() == fallbackRoute.complexity() &&
+                        originalRoute.methods().containsAll(fallbackRoute.methods())) {
+                        return fallbackServiceConfig;
+                    }
+
+                    checkState(fallbackRoute.equals(Route.ofCatchAll()),
+                               "Fallback service must catch all requests.");
+                    final Route newRoute =
+                            originalRoute.toBuilder()
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java:93]: @trustin I need to create a new fallback route from here. Is it okay to remove `final` keyword from `RouteBuilder#isFallback` variable and make a setter for it?

Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:93]: SGTM

File: core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java (hunk 18 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java:51]: Yeah, I think that makes sense if that's the case, but it'd be nice if we add some comment about why we use `isFallback` where `allowDeferredException` was used before.

Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java:51]: Thank you @trustin. Will add a comment :-)

File: core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java [hunk 20]
```diff
@@ -77,7 +77,15 @@
      * Returns the list of values which is mapped to the given {@code path}.
      */
     List<V> find(String path) {
-        final Node<V> node = findNode(path, false);
+        return find(path, node -> node);
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java:80]: How about adding this to `NodeProcessor`?

```java
interface NodeProcessor {
    static <V> NodeProcessor<V> noop() {
        return node -> node;
    }
    ...
}
```

File: core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java [hunk 21]
```diff
@@ -180,6 +179,20 @@ public RoutingResult apply(RoutingContext routingCtx, boolean isRouteDecorator)
...
 
+    private void deferStatusException(RoutingContext routingCtx, HttpStatus httpStatus) {
+        if (isFallback) {
+            // Do not defer an exception if this route is a fallback route, which is matched
+            // only when no configured route was matched.
+            //
+            // For example, assume that a route '/a/b/c/' supports HTTP GET method only.
+            // Its fallback route would be added as a path of '/a/b/c' with supporting HTTP GET method as well.
+            // In this case, '404 not found' would make sense rather than '405 method not allowed'
+            // if a 'DELETE /a/b/c' request is received, because the fallback route radically does not exist.
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java:190]: What does radically here mean?

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 22]
```diff
@@ -358,19 +404,50 @@
...
+            return getRouteCandidates(routingCtx, trie.findAll(routingCtx.path()),
+                                      routeResolver, isRouteDecorator);
         }
 
         @Override
         public void dump(OutputStream output) {
             trie.dump(output);
         }
+
+        private final class ResultCachingNodeProcessor implements NodeProcessor<V> {
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:426]: It seems better! Thank you!

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 23]
```diff
@@ -358,19 +404,50 @@
 
         @Override
         public Routed<V> find(RoutingContext routingCtx) {
-            return findBest(routingCtx, trie.find(routingCtx.path()), routeResolver);
+            final ResultCachingNodeProcessor processor = new ResultCachingNodeProcessor(routingCtx);
+            trie.find(routingCtx.path(), processor);
+            if (processor.routeCollector != null) {
+                return findBest(processor.routeCollector.build());
+            }
+            return Routed.empty();
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:412]: Good point. Let me change it. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java [hunk 24]
```diff
@@ -300,4 +315,15 @@ public String toString() {
     private static class IntHolder {
         int value;
     }
+
+    @FunctionalInterface
+    interface NodeProcessor<V> {
+        /**
+         * Looks into the node before picking it as a candidate for handling the current request.
+         * Returns it as it is, mutates it if necessary or returns {@code null} if the node is not
+         * a suitable one to handle the current request.
```
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java:324]: The suggested one explains better. 👍

File: core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java (hunk 20 above)
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java:80]: Got it. Will add it. Thanks!

File: core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java (hunk 21 above)
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java:190]: I meant the route wasn't specified by a user. So would it be better if I rewrite it as follows?

`because the fallback route wasn't specified by a user.`

File: core/src/main/java/com/linecorp/armeria/server/Routers.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (hyangtack) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:426]: On second thoughts, how about `RouteCandidateCollectingNodeProcessor`? It's slightly long name, but shows the class's role more clearly.

[the remark this answers is not in the document]
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java]: Sounds good!

**Review by trustin — APPROVED** [review]
Awesome job as usual, @hyangtack. :100:

**Review by ikhoon — APPROVED** [review]
Many thanks for all your hard work! 🙇‍♂️ @hyangtack

**Comment by trustin** [comment]
@minwoox Ping

File: core/src/main/java/com/linecorp/armeria/server/Routers.java [hunk 25]
```diff
@@ -71,13 +76,43 @@
...
+                                         .fallback(true)
+                                         .build();
+                    // We have only one fallback ServiceConfig instance so finding a cached config
+                    // with a Route instance is okay at the moment.
+                    final ServiceConfig cachedConfig = newServiceConfigs.get(newRoute);
+                    if (cachedConfig != null) {
+                        return cachedConfig;
+                    }
+                    final ServiceConfig newConfig = fallbackServiceConfig.withRoute(newRoute);
+                    newServiceConfigs.put(newRoute, newConfig);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/Routers.java:105]: `newServiceConfigs` shouldn't be a `ConcurrentHashMap`?

**Review by minwoox — COMMENTED** [review]
Thanks! just one nit. 😄

File: core/src/main/java/com/linecorp/armeria/server/Routers.java (hunk 25 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/Routers.java:105]: No, it's not. Sorry about it. 😅

**Review by minwoox — APPROVED** [review]
You are the superhero.

**Comment by trustin** [comment]
:tada::tada::tada:
