### PR TITLE
Ensure a user set the endpoint path in DocService when the path is not…

### LINKED ISSUE #1856: DocService annotated http paths are mangled if not exact
This line mangles all annotated http paths that aren't exact.
https://github.com/line/armeria/commit/35416c2b77fd020ee37c4c42d582b142400bbefd#diff-3b29757cfa7d6be5d3ca726a154114b1R54

will chop off the first 6 characters of the path mangling it badly. While the path may not be usable anyway, it will not give a unexpected 404 or 405 error message.

@minwoox If you're doing https://github.com/line/armeria/issues/1855 anyway, this might be an easy fix?

### PR DESCRIPTION
**Pull request by minwoox**
… an exact path type

Motivation:
When the path of s service in `DocService` is not an exact path type, a user should set the endpoint path
and we must validate it.

Modifications:
- Ensure a user set the endpoint path when the path is not an exact type.
- Rename `PROXY_PORT` to `ARMERIA_PORT` for clarity.

Result:
- Close #1856

### CODE REVIEW

File: docs-client/src/containers/MethodPage/DebugPage.tsx [hunk 1]
```diff
@@ -449,6 +447,9 @@ class DebugPage extends React.PureComponent<Props, State> {
   };
 
   private validateEndpointPath(endpointPath: string) {
+    if (!endpointPath) {
+      throw new Error(`You should set the ENDPOINT PATH.`);
```
Comment (ikhoon) [inline docs-client/src/containers/MethodPage/DebugPage.tsx]: nit: How about just using single(`'`) quotes here? :-)

Comment (minwoox) [reply docs-client/src/containers/MethodPage/DebugPage.tsx]: Oops~ fixed. Thank you. 😉

File: docs-client/src/containers/MethodPage/DebugPage.tsx [hunk 2]
```diff
@@ -449,6 +447,9 @@ class DebugPage extends React.PureComponent<Props, State> {
   };
 
   private validateEndpointPath(endpointPath: string) {
+    if (!endpointPath) {
+      throw new Error('You must set the ENDPOINT PATH.');
```
Comment (trustin) [inline docs-client/src/containers/MethodPage/DebugPage.tsx]: `specify the endpoint path`? (set -> specify, no reason to capitalize)

Comment (minwoox) [reply docs-client/src/containers/MethodPage/DebugPage.tsx]: Fixed, thanks!

**Comment by trustin** [comment]
Thanks, @minwoox!

**Comment by minwoox** [comment]
Thanks for reviewing!
