### PR TITLE
Fix to contain te header in gRPC request

### LINKED ISSUE #1963: Armeria failed to call python gRPC server
Hi, armeria client can not call the python server, and please refer to the following debug output of the python server, it seems that it is caused by the missing header of TE . It would be appreciated anyone can fix this issue soon.

armeria version: 0.89
python gRPC server: 1.22.0

```
D0806 02:31:27.965091212      19 tcp_posix.cc:1258]          cannot set inq fd=11 errno=92
I0806 02:31:27.965223260      19 chttp2_transport.cc:841]    W:0x55d743561940 SERVER [ipv4:172.16.71.203:53095] state IDLE -> WRITING [TRANSPORT_FLOW_CONTROL]
I0806 02:31:27.965250787      19 chttp2_transport.cc:841]    W:0x55d743561940 SERVER [ipv4:172.16.71.203:53095] state WRITING -> WRITING+MORE [INITIAL_WRITE]
I0806 02:31:27.965306897      19 chttp2_transport.cc:1877]   perform_transport_op[t=0x55d743561940]: ON_CONNECTIVITY_STATE_CHANGE:p=0x55d743566380:from=IDLE SET_ACCEPT_STREAM:0x7f13f1ba2950(0x55d743566318,...)
I0806 02:31:27.965330061      19 chttp2_transport.cc:1877]   perform_transport_op[t=0x55d743561940]: ON_CONNECTIVITY_STATE_CHANGE:p=0x55d743566380:from=READY
I0806 02:31:27.965365425      19 writing.cc:116]             SERVER: Ping sent [ipv4:172.16.71.203:53095]: 2/2
I0806 02:31:27.965388285      19 chttp2_transport.cc:841]    W:0x55d743561940 SERVER [ipv4:172.16.71.203:53095] state WRITING+MORE -> WRITING [begin write in current thread]
I0806 02:31:27.965439262      19 chttp2_transport.cc:2623]   ipv4:172.16.71.203:53095: Start BDP ping err="No Error"
I0806 02:31:27.965462732      19 chttp2_transport.cc:841]    W:0x55d743561940 SERVER [ipv4:172.16.71.203:53095] state WRITING -> IDLE [finish writing]
I0806 02:31:27.972813083      19 frame_settings.cc:222]      0x55d743561940[svr] adding 983041 for initial_window change
I0806 02:31:27.972845071      19 frame_settings.cc:229]      CHTTP2:SVR:ipv4:172.16.71.203:53095: got setting INITIAL_WINDOW_SIZE = 1048576
I0806 02:31:27.972856826      19 frame_settings.cc:229]      CHTTP2:SVR:ipv4:172.16.71.203:53095: got setting MAX_HEADER_LIST_SIZE = 8192
I0806 02:31:28.041162088      19 chttp2_transport.cc:2639]   ipv4:172.16.71.203:53095: Complete BDP ping err="No Error"
I0806 02:31:28.073737463      19 parsing.cc:656]             parsing initial_metadata
I0806 02:31:28.073776189      19 hpack_parser.cc:636]        Decode: ':method: POST', elem_interned=1 [3], k_interned=1, v_interned=1
I0806 02:31:28.073800916      19 parsing.cc:407]             HTTP:3:HDR:SVR: :method: 50 4f 53 54 'POST'
I0806 02:31:28.073835161      19 hpack_parser.cc:636]        Decode: ':path: /infra.commonserver.address.RakeKeywordsService/ListKeywords', elem_interned=1 [1], k_interned=1, v_interned=1
I0806 02:31:28.073859783      19 parsing.cc:407]             HTTP:3:HDR:SVR: :path: 2f 69 6e 66 72 61 2e 63 6f 6d 6d 6f 6e 73 65 72 76 65 72 2e 61 64 64 72 65 73 73 2e 52 61 6b 65 4b 65 79 77 6f 72 64 73 53 65 72 76 69 63 65 2f 4c 69 73 74 4b 65 79 77 6f 72 64 73 '/infra.commonserver.address.RakeKeywordsService/ListKeywords'
I0806 02:31:28.073882947      19 hpack_parser.cc:636]        Decode: ':authority: 192.168.4.63:8080', elem_interned=1 [1], k_interned=1, v_interned=1
I0806 02:31:28.073905810      19 parsing.cc:407]             HTTP:3:HDR:SVR: :authority: 31 39 32 2e 31 36 38 2e 34 2e 36 33 3a 38 30 38 30 '192.168.4.63:8080'
I0806 02:31:28.073926531      19 hpack_parser.cc:636]        Decode: ':scheme: http', elem_interned=1 [3], k_interned=1, v_interned=1
I0806 02:31:28.073942873      19 parsing.cc:407]             HTTP:3:HDR:SVR: :scheme: 68 74 74 70 'http'
I0806 02:31:28.073967299      19 hpack_parser.cc:636]        Decode: 'content-type: application/grpc', elem_interned=1 [3], k_interned=1, v_interned=1
I0806 02:31:28.073996457      19 parsing.cc:407]             HTTP:3:HDR:SVR: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
I0806 02:31:28.074023374      19 hpack_parser.cc:636]        Decode: 'grpc-accept-encoding: gzip', elem_interned=1 [3], k_interned=1, v_interned=1
I0806 02:31:28.074046275      19 parsing.cc:407]             HTTP:3:HDR:SVR: grpc-accept-encoding: 67 7a 69 70 'gzip'
I0806 02:31:28.074065980      19 hpack_parser.cc:636]        Decode: 'grpc-timeout: 15000000u', elem_interned=1 [1], k_interned=1, v_interned=1
I0806 02:31:28.074084423      19 parsing.cc:407]             HTTP:3:HDR:SVR: grpc-timeout: 31 35 30 30 30 30 30 30 75 '15000000u'
I0806 02:31:28.074111118      19 hpack_parser.cc:636]        Decode: 'user-agent: armeria/0.89.0', elem_interned=1 [1], k_interned=1, v_interned=1
I0806 02:31:28.074129307      19 parsing.cc:407]             HTTP:3:HDR:SVR: user-agent: 61 72 6d 65 72 69 61 2f 30 2e 38 39 2e 30 'armeria/0.89.0'
I0806 02:31:28.074151135      19 chttp2_transport.cc:1710]   perform_stream_op[s=0x55d7435406d8]:  RECV_INITIAL_METADATA
I0806 02:31:28.074168288      19 chttp2_transport.cc:1406]   perform_stream_op_locked:  RECV_INITIAL_METADATA; on_complete = 0
I0806 02:31:28.074243885      19 chttp2_transport.cc:1710]   perform_stream_op[s=0x55d7435406d8]:  CANCEL:{"created":"@1565058688.074188451","description":"Missing :authority or :path","file":"src/core/lib/surface/server.cc","file_line":772,"referenced_errors":[{"created":"@1565058688.074184687","description":"Failed processing incoming headers","file":"src/core/ext/filters/http/server/http_server_filter.cc","file_line":122,"referenced_errors":[{"created":"@1565058688.074181256","description":"Missing header","file":"src/core/ext/filters/http/server/http_server_filter.cc","file_line":178,"key":"te"}]}]}
I0806 02:31:28.074260044      19 chttp2_transport.cc:1406]   perform_stream_op_locked:  CANCEL:{"created":"@1565058688.074188451","description":"Missing :authority or :path","file":"src/core/lib/surface/server.cc","file_line":772,"referenced_errors":[{"created":"@1565058688.074184687","description":"Failed processing incoming headers","file":"src/core/ext/filters/http/server/http_server_filter.cc","file_line":122,"referenced_errors":[{"created":"@1565058688.074181256","description":"Missing header","file":"src/core/ext/filters/http/server/http_server_filter.cc","file_line":178,"key":"te"}]}]}; on_complete = 0x55d74366bb20
I0806 02:31:28.074277377      19 chttp2_transport.cc:841]    W:0x55d743561940 SERVER [ipv4:172.16.71.203:53095] state IDLE -> WRITING [RST_STREAM]
I0806 02:31:28.074298577      19 chttp2_transport.cc:1255]   complete_closure_step: t=0x55d743561940 0x55d74366bb20 refs=0 flags=0x0000 desc=op->on_complete err="No Error" write_state=WRITING
I0806 02:31:28.074319104      19 chttp2_transport.cc:841]    W:0x55d743561940 SERVER [ipv4:172.16.71.203:53095] state WRITING -> WRITING [begin write in current thread]
I0806 02:31:28.074351314      19 chttp2_transport.cc:841]    W:0x55d743561940 SERVER [ipv4:172.16.71.203:53095] state WRITING -> IDLE [finish writing]
I0806 02:31:28.154671248      19 chttp2_transport.cc:1157]   ipv4:172.16.71.203:53095: Got goaway [0] err={"created":"@1565058688.154629453","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1151,"grpc_status":14,"http2_error":0,"raw_bytes":""}
I0806 02:31:28.154707571      19 chttp2_transport.cc:2828]   set connectivity_state=3
I0806 02:31:28.154728520      19 chttp2_transport.cc:1877]   perform_transport_op[t=0x55d743561940]: ON_CONNECTIVITY_STATE_CHANGE:p=0x55d743566380:from=TRANSIENT_FAILURE
I0806 02:31:28.154752879      19 chttp2_transport.cc:2828]   set connectivity_state=4
I0806 02:31:28.154798453      19 chttp2_transport.cc:1877]   perform_transport_op[t=0x55d743561940]: SET_ACCEPT_STREAM:0(0,...)
I0806 02:31:28.154854008      19 chttp2_transport.cc:2623]   ipv4:172.16.71.203:53095: Start BDP ping err={"created":"@1565058688.154749048","description":"Endpoint read failed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2532,"occurred_during_write":0,"referenced_errors":[{"created":"@1565058688.154743074","description":"Socket closed","fd":11,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":509,"grpc_status":14,"target_address":"ipv4:172.16.71.203:53095"},{"created":"@1565058688.154629453","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1151,"grpc_status":14,"http2_error":0,"raw_bytes":""}]}
I0806 02:31:28.154869391      19 chttp2_transport.cc:2639]   ipv4:172.16.71.203:53095: Complete BDP ping err={"created":"@1565058688.154749048","description":"Endpoint read failed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2532,"occurred_during_write":0,"referenced_errors":[{"created":"@1565058688.154743074","description":"Socket closed","fd":11,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":509,"grpc_status":14,"target_address":"ipv4:172.16.71.203:53095"},{"created":"@1565058688.154629453","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1151,"grpc_status":14,"http2_error":0,"raw_bytes":""}]}
```

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
According to the [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests),
gRPC `Request-Headers` has to contain `te` header in order to detect incompatible proxies.

Modification:
- Add `te` header to gRPC request headers

Result:
- Fix #1963

### CODE REVIEW

File: grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java [hunk 1]
```diff
@@ -79,7 +80,8 @@ public UnaryGrpcClient(HttpClient httpClient) {
     public CompletableFuture<byte[]> execute(String uri, byte[] payload) {
         final HttpRequest request = HttpRequest.of(
                 RequestHeaders.of(HttpMethod.POST, uri,
-                                  HttpHeaderNames.CONTENT_TYPE, "application/grpc+proto"),
+                                  HttpHeaderNames.CONTENT_TYPE, "application/grpc+proto",
+                                  HttpHeaderNames.TE, HttpHeaderValues.TRAILERS),
```
Comment (minwoox) [inline grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java]: I didn't add a test case for this because the upstream server does not include `te` header while converting request headers to `MetaData` [here](https://github.com/grpc/grpc-java/blob/v1.22.1/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L422).

**Comment by minwoox** [comment]
I also found out that the upstream metadata doesn't include the pseudo headers.
But we do have all pseudo headers and `te`. Do we need to follow the upstream's conversion strategy? @anuraaga

**Comment by anuraaga** [comment]
There's some context in https://github.com/grpc/grpc-java/issues/5788

There isn't a clear definition of what headers should be in `Metadata` but you're right it's recommended to hide pseudoheaders and hop-by-hop ones. Since it's not defined and seems like an implementation detail, I just went with reduced complexity 😅

**Comment by trustin** [comment]
Thanks, @minwoox !

**Comment by minwoox** [comment]
> There's some context in grpc/grpc-java#5788

Ah, thanks! Yeah, it's not defined and I think it's fine as it is. :-)

**Comment by minwoox** [comment]
Thanks for reviewing!
