### PR TITLE
Fix a bug where HAProxy server handler throws `NPE` if an address fam…

### LINKED ISSUE #2984: NullPointerException is thrown when HAPROXY socket family is `AF_UNSPEC`
When Armeria Server receives a request from HAPROXY whose socket family is `AF_UNSPEC`, NPE is thrown.

- AF_UNSPEC from the [HAPROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt).
``` 
0x0 : AF_UNSPEC : the connection is forwarded for an unknown, unspecified
    or unsupported protocol. The sender should use this family when sending
    LOCAL commands or when dealing with unsupported protocol families. The
    receiver is free to accept the connection anyway and use the real endpoint
    addresses or to reject it. The receiver should ignore address information.
```

- Related stacktrace.
```java
c.l.a.s.HttpServerPipelineConfigurator   : PROXY message V2: null:0 -> null:0 (next: [http])
etty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar!/:4.1.51.Fin
l]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.51.Final-linux-x86_64.ja
!/:4.1.51.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar!/:4.1.51.F
nal]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.ne
ty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLo
alRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:830) [?:
]
Caused by: java.lang.NullPointerException
	at io.netty.util.NetUtil.isValidIpV4Address(NetUtil.java:651) ~[netty-common-4.1.51.Final.ja
!/:4.1.51.Final]
	at io.netty.util.NetUtil.createByteArrayFromIpAddressString(NetUtil.java:371) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at com.lin
corp.armeria.server.HttpServerPipelineConfigurator$ProxiedPipelineConfigurator.decode(HttpServerPipelineConfigurator.java:375) ~[armeria-0.99.9.jar!/:?]
	at co
.linecorp.armeria.server.HttpServerPipelineConfigurator$ProxiedPipelineConfigurator.decode(HttpServerPipelineConfigurator.java:355) ~[armeria-0.99.9.jar!/:?]
t io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
	... 31 more
l]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar!/:4.1.51.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar!/:4.1.51.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar!/:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NullPointerException
	at io.netty.util.NetUtil.isValidIpV4Address(NetUtil.java:651) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.NetUtil.createByteArrayFromIpAddressString(NetUtil.java:371) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at com.linecorp.armeria.server.HttpServerPipelineConfigurator$ProxiedPipelineConfigurator.decode(HttpServerPipelineConfigurator.java:375) ~[armeria-0.99.9.jar!/:?]
	at com.linecorp.armeria.server.HttpServerPipelineConfigurator$ProxiedPipelineConfigurator.decode(HttpServerPipelineConfigurator.java:355) ~[armeria-0.99.9.jar!/:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
	... 31 more
````

### PR DESCRIPTION
**Pull request by ikhoon**
…ily is `AF_UNSPEC`

Motivation:

Armeria HAProxy handler considers that a HAProxyMessage contains addresses information.
However, if the address family is `AF_UNSPEC`, the addresses are null always.
From the HAProxy spec, the receiver can accept the connection or reject it.
There seems to be no harm ignoring the addresses information.

Modifications:

- Ignore proxied addresses information if AddressFamily is `AF_UNSPEC`

Result:

- HAProxy handler does not throw NullPointerException anymore.
- Fixes #2984

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java [hunk 1]
```diff
@@ -370,14 +371,20 @@ protected void decode(ChannelHandlerContext ctx, HAProxyMessage msg, List<Object
                              msg.destinationAddress(), msg.destinationPort(),
                              proxiedCandidates);
             }
+
+            final ProxiedAddresses proxiedAddresses;
+            if (msg.proxiedProtocol().addressFamily() == AddressFamily.AF_UNSPEC) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java:376]: should we also ignore `AF_UNIX` as well?

**Comment by trustin** [comment]
@ikhoon Could you check the leak: https://ci.appveyor.com/project/line/armeria/builds/34568059/job/s6dohpcamm9i5hnx#L135

**Comment by ikhoon** [comment]
> @ikhoon Could you check the leak: https://ci.appveyor.com/project/line/armeria/builds/34568059/job/s6dohpcamm9i5hnx#L135

Oops... 😱
