### PR TITLE
fix debug page popping when URL params are set

### LINKED ISSUE #5047: The Debug popup in DocService reopens after collapsing items in the sidebar
When running `:examples:thrift`, I can reproduce the following:

In the DocService, after opening the Debug popup for an API and testing a call, I can close it by clicking on the background (the URL remains the same). However, if I then try to collapse a service in the sidebar, the Debug menu reopens.

This does not seem to happen with annotated services.

https://github.com/line/armeria/assets/1769968/c63ede43-d018-4f6d-9cab-4e1fab34aa79

### PR DESCRIPTION
**Pull request by Dogacel**
Motivation:

#5047 

Modifications:

- Persist `debug_form_is_open` in URL so we are not accidentally opening the debug form when user navigates on the frontend.

Result:

- Closes #5047 

https://github.com/line/armeria/assets/7023385/ae96a858-63aa-40a8-b85a-e369ebd215ea

Off-the record, I tested visiting the URL, it still opens the Debug page as expected.

### CODE REVIEW

File: docs-client/src/containers/MethodPage/index.tsx [hunk 1]
```diff
@@ -136,7 +136,36 @@ type Props = OwnProps &
...
+        return setDebugFormIsOpenState(valueToSet);
+      },
+      [
+        debugFormIsOpen,
+        setDebugFormIsOpenState,
+        history,
+        location.search,
+        location.pathname,
+      ],
+    );
```
Comment (Dogacel) [inline docs-client/src/containers/MethodPage/index.tsx:168]: We are manually setting all headers in Debug page submit so copied to logic from there. But I believe we can use some param hooks provided by router. Not 100% sure, don't have much time so wanted to fix the bug ASAP 😓

**Comment by Dogacel** [comment]
Gentle ping. @jrhee17 @ikhoon

File: docs-client/src/containers/MethodPage/DebugPage.tsx [hunk 2]
```diff
@@ -214,9 +219,10 @@ const DebugPage: React.FunctionComponent<Props> = ({
     setRequestBody(urlRequestBody || method.exampleRequests[0] || '');
     setAdditionalPath(urlPath || '');
     setAdditionalQueries(urlQueries || '');
-    setDebugFormIsOpen(
-      (isOpen) => isOpen || urlRequestBody !== '' || urlQueries !== '',
-    );
```
Comment (ikhoon) [inline docs-client/src/containers/MethodPage/DebugPage.tsx:219]: I guess this problem is fixed by #5072 since these lines are removed at https://github.com/line/armeria/pull/5072/files#diff-812b896083a854df7bc9731f6b8e0364ee398948b69150196d4d87268a73bc03L217

Comment (Dogacel) [reply docs-client/src/containers/MethodPage/DebugPage.tsx:219]: Yes, it seems like this PR became an optional functionality that allows users to share URLs that automatically open up the debug form. What do you think?

Comment (ikhoon) [reply docs-client/src/containers/MethodPage/DebugPage.tsx:219]: That sounds good to open up the debug modal when a user intended it.

**Comment by Dogacel** [comment]
Should we abandon this PR considering the bug is resolved? Do you see value on automatically opening the debug form if it is shared via a URL when the form was open?

**Comment by ikhoon** [comment]
> Do you see value on automatically opening the debug form if it is shared via a URL when the form was open?

No, I couldn't. I think this patch is useful.

File: docs-client/src/containers/MethodPage/DebugPage.tsx [hunk 3]
```diff
@@ -179,10 +179,15 @@ const DebugPage: React.FunctionComponent<Props> = ({
     const urlParams = new URLSearchParams(location.search);
 
     let urlRequestBody = '';
+    let urlDebugFormIsOpen = false;
     if (useRequestBody) {
       if (urlParams.has('request_body')) {
         urlRequestBody = jsonPrettify(urlParams.get('request_body')!);
       }
+
+      if (urlParams.has('debug_form_is_open')) {
```
Comment (ikhoon) [inline docs-client/src/containers/MethodPage/DebugPage.tsx:188]: Should we open a debug form when `debug_form_is_open` is set to `true` regardless of `useRequestBody`?

**Comment by ikhoon** [comment]
The overall change looks good. Could you resolve the conflicts?

File: docs-client/src/containers/MethodPage/DebugPage.tsx (hunk 3 above)
Comment (Dogacel) [reply docs-client/src/containers/MethodPage/DebugPage.tsx:195]: Yes

**Comment by Dogacel** [comment]
> The overall change looks good. Could you resolve the conflicts?

It has been a busy week, I have the code updates but now I gotta test the actual implementation. I'll let you know.

**Comment by Dogacel** [comment]
Here are my screen recordings for manual tests, I have tested against grpc doc service and annotated service (which has an http request without a body).

https://github.com/line/armeria/assets/7023385/af90c614-9683-488e-acaa-e56fc9c060b3

https://github.com/line/armeria/assets/7023385/d7442760-a8d8-4a16-9c79-3e68ae01e40a


I hope this simplifies the review process 😆

**Review by ikhoon — APPROVED** [review]
Thanks, @Dogacel ❤️

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Review by trustin — APPROVED** [review]
Thanks for fixing this up, @Dogacel! :bow:

**Review by jrhee17 — APPROVED** [review]
Thanks @Dogacel ! 🙇 👍 🙇
