### PR TITLE
Specify event loop when subscribing from stream duplicator from Retry…

### LINKED ISSUE #853: NoSuchElementException from DefaultStreamMessage
Possibly due to #848 or #836?

```
com.linecorp.armeria.client.retry.RetryingHttpClientTest > differentBackoffBasedOnStatus FAILED
    java.util.concurrent.CompletionException: java.util.NoSuchElementException
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.differentBackoffBasedOnStatus(RetryingHttpClientTest.java:490)
        Caused by:
        java.util.NoSuchElementException
            at java.util.AbstractQueue.remove(AbstractQueue.java:117)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:384)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:367)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:298)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage$SubscriptionImpl.request(DefaultStreamMessage.java:580)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.requestDemand(AbstractStreamMessageDuplicator.java:321)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$DownstreamSubscription.request(AbstractStreamMessageDuplicator.java:576)
            at com.linecorp.armeria.internal.HttpHeaderSubscriber.onSubscribe(HttpHeaderSubscriber.java:56)
            at com.linecorp.armeria.common.stream.FilteredStreamMessage$FilteringSubscriber.onSubscribe(FilteredStreamMessage.java:129)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$DownstreamSubscription.invokeOnSubscribe(AbstractStreamMessageDuplicator.java:558)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.subscribe(AbstractStreamMessageDuplicator.java:272)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe0(AbstractStreamMessageDuplicator.java:437)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe(AbstractStreamMessageDuplicator.java:409)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe(AbstractStreamMessageDuplicator.java:403)
            at com.linecorp.armeria.common.stream.StreamMessageWrapper.subscribe(StreamMessageWrapper.java:68)
            at com.linecorp.armeria.common.stream.FilteredStreamMessage.subscribe(FilteredStreamMessage.java:89)
            at com.linecorp.armeria.client.retry.HttpStatusBasedRetryStrategy.shouldRetry(HttpStatusBasedRetryStrategy.java:52)
            at com.linecorp.armeria.client.retry.HttpStatusBasedRetryStrategy.shouldRetry(HttpStatusBasedRetryStrategy.java:35)
            at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute0(RetryingHttpClient.java:132)
            at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute(RetryingHttpClient.java:116)
            at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute(RetryingHttpClient.java:52)
            at com.linecorp.armeria.client.retry.RetryingClient.execute(RetryingClient.java:69)
            at com.linecorp.armeria.client.UserClient.execute(UserClient.java:160)
            at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:55)
            at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:68)
            at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:64)
            at com.linecorp.armeria.client.HttpClient.execute(HttpClient.java:156)
            at com.linecorp.armeria.client.HttpClient.get(HttpClient.java:198)
            ... 1 more
```

### PR DESCRIPTION
**Pull request by anuraaga**
…ingHttpClient.

I don't deeply know this code, so please check it out, but I guess framework code should always be specifying an event loop when subscribing to a stream, even if we handle the underlying issue of properly synchronizing subscriptions made without a subscriber as the latter will probably be suboptimal.

If my understanding of the issue is correct, this will fix #853 (actually I'm still not that sure where the multiple writes come from)

### CODE REVIEW

**Comment by minwoox** [comment]
Thank you for this PR.
As far as I know, there was no multiple writes. :-) The read and write threads can enter the `notifySubscriber` section together, so we needed to guard it from the race condition. But if we use the same approach like you do in `EventLoopStreamMessage` the problem would be gone. Moreover unlike `EventLoopStreamMessage`, this duplicator can specify the eventLoop when it is created. :-)

File: core/src/main/java/com/linecorp/armeria/common/HttpResponseDuplicator.java [hunk 1]
```diff
@@ -68,12 +72,22 @@ public HttpResponseDuplicator(HttpResponse res) {
...
+     * @param executor the executor to use for upstream signals.
+     */
+    public HttpResponseDuplicator(HttpResponse res, long maxSignalLength, @Nullable Executor executor) {
         super(requireNonNull(res, "res"), obj -> {
             if (obj instanceof HttpData) {
                 return ((HttpData) obj).length();
             }
             return 0;
-        }, maxSignalLength);
+        }, null, maxSignalLength);
```
Comment (hyangtack) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponseDuplicator.java]: `null` -> `executor`?

Comment (anuraaga) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponseDuplicator.java]: Oof - thanks

**Comment by trustin** [comment]
Thanks, @anuraaga !
