### PR TITLE
Respond with application/json for httpjson transcoding endpoints

### LINKED ISSUE #4473: HTTP/JSON gRPC transcoding services does not return `application/json` but `applicaiton/grpc+json`
As per https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sending-arbitrary-content, HTTP/JSON gRPC transcoding needs to set `application/json` to the response `content-type` header.
However, there is a regression that HTTP/JSON gRPC transcoding services return `applicaiton/grpc+json` since 1.19.0 caused by #4364

### PR DESCRIPTION
**Pull request by j-min5u**
Motivation:

Wrong response contenttype served for http json transcoding endpoints as result of #4364 

Modifications:

- since AbstractUnframedGrpcService$frameAndServe uses the provided responseContentType parameter directly as the resulting http contenttype, application/json should be provided in HttpJsonTranscodingService instead of application/grpc+json
- alternative would be to respond with the request contenttype ex) JSON -> JSON / JSON_UTF_8 -> JSON_UTF_8 

Result:

- Closes #4473

### CODE REVIEW

File: grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java [hunk 1]
```diff
@@ -603,7 +602,7 @@ private HttpResponse serve0(ServiceRequestContext ctx, HttpRequest req,
                         ctx.setAttr(FramedGrpcService.RESOLVED_GRPC_METHOD, spec.method);
                         frameAndServe(unwrap(), ctx, grpcHeaders.build(),
                                       convertToJson(ctx, clientRequest, spec),
-                                      responseFuture, generateResponseBodyConverter(spec), jsonContentType);
+                                      responseFuture, generateResponseBodyConverter(spec), MediaType.JSON_UTF_8);
```
Comment (minwoox) [inline grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java:605]: nit: Let's leave a link to this https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sending-arbitrary-content that explains why we set JSON media type.

**Review by minwoox — APPROVED** [review]
Thanks, @j-min5u! 😄

**Review by jrhee17 — APPROVED** [review]
Thanks for the quick fix @j-min5u ! 🙇 👍 🙇

**Comment by jrhee17** [comment]
Can you also check the lint failures? 😅

**Review by ikhoon — APPROVED** [review]
LGTM and welcome back! 😁
