### PR TITLE
Recover HttpResponse according to a specific exception class

### LINKED ISSUE #4279: Recover `HttpResponse` according to a specific exception class.
A failed `HttpResponse` can be converted into a normal `HttpResponse` using `HttpResponse.recover(...)`.
For example:
```java
HttpResponse failed = HttpResponse.ofFailure(new IllegalArgumentException("..."));
failed.recover(cause -> {
   if (cause instanceof IllegalArgumentException) {
       return HttpResponse.of(HttpStatus.BAD_REQUEST);
   }

   if (cause instanceof IllegalStateException) {
       return HttpResponse.of(HttpStatus.INTERNAL_SERVER_ERROR);
   }

   if (...) {
      return ...;
   }
   // Don't recover the cause.
   return Exceptions.throwUnsafely(cause);
});
```

If it is not a global exception handler, users may be interested in recovering an exception.
So, we can add a shortcut method for those requirements.
```java
failed.recover(IllegalArgumentException.class, 
               cause -> HttpResponse.of(HttpStatus.BAD_REQUEST))
      .recover(IllegalStateException.class, 
               cause -> HttpResponse.of(HttpStatus.INTERNAL_SERVER_ERROR))
      .recover(....)
```

### PR DESCRIPTION
**Pull request by devdynam0507**
### Motivation:

If it is not a global exception handler, users may be interested in recovering an exception.
So, we can add a shortcut method for those requirements.
For example
```java
HttpResponse failed = HttpResponse.ofFailure(new IllegalStateException("Oops..."));
failed.recover(IllegalArgumentException.class, 
               cause -> HttpResponse.of(HttpStatus.BAD_REQUEST))
      .recover(IllegalStateException.class, 
               cause -> HttpResponse.of(HttpStatus.INTERNAL_SERVER_ERROR))
      .recover(....)
```
Users may be to want recover shortcut specific exception class type.

### Modifications:

- Add `recover()` shortcut method in `HttpResponse`

### Result:

- Close #4279
- You can now map a specific exception to an <type://HttpResponse>.
  ```java
  HttpResponse recovered =
      response.recover(IllegalStateException.class,
                       cause -> HttpResponse.of("Fallback"));
  ```

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 1]
```diff
@@ -937,4 +938,17 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
         requireNonNull(function, "function");
         return of(new RecoverableStreamMessage<>(this, function, /* allowResuming */ false));
     }
+
+	default HttpResponse recover(Class<? extends Throwable> causeClass,
+								 Function<? super Throwable, ? extends HttpResponse> function) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:943]: Thanks for your contribution. 😄 
We use four spaces instead of tabs. Could you check the [developer guide](https://armeria.dev/community/developer-guide#setting-up-your-ide) and apply it for this PR, please?

Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java]: Oops... sorry i missed it 😅
i changed tab to four space and re order imports

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 2]
```diff
@@ -937,4 +938,17 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
         requireNonNull(function, "function");
         return of(new RecoverableStreamMessage<>(this, function, /* allowResuming */ false));
     }
+
+    default HttpResponse recover(Class<? extends Throwable> causeClass,
+                                 Function<? super Throwable, ? extends HttpResponse> function) {
+        requireNonNull(causeClass, "causeClass");
+        requireNonNull(function, "function");
+        final StreamMessage<HttpObject> stream = recover(cause -> {
+            if (cause.getClass().equals(causeClass)) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:947]: How about using `causeClass.isAssignableFrom(...)` to handle the subclasses?

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 3]
```diff
@@ -937,4 +938,17 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
...
+                return function.apply(cause);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:948]: We raise an exception if the function returns `null`: https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java#L222
How about also applying the same approach here?

File: core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java [hunk 4]
```diff
@@ -275,4 +275,26 @@ void nonRecoverableHttpResponse() {
...
+    void shortcutRecoverableHttpResponse() {
+        final HttpResponse failedResponse = HttpResponse.ofFailure(new IllegalStateException("test exception"));
+        final HttpResponse recovered =
+            failedResponse.recover(IllegalStateException.class, cause -> HttpResponse.of("fallback"));
+        final AggregatedHttpResponse response = recovered.aggregate().join();
+        assertThat(response.headers().status()).isEqualTo(HttpStatus.OK);
+        assertThat(response.contentUtf8()).isEqualTo("fallback");
+
+        final HttpResponseWriter failedResponse2 = HttpResponse.streaming();
+        failedResponse2.write(ResponseHeaders.of(HttpStatus.OK));
```
Comment (minwoox) [inline core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java:289]: This is a bit confusing because the response headers from https://github.com/line/armeria/pull/4283/files#diff-fd9ecbc60a1984ec715fcbd5a174803f219c441dc043827f13e403b243edb4afR295 has the same status. 😅 
How about specifying another status? (e.g. HttpStatus.NOT_MODIFIED)

**Review by minwoox — COMMENTED** [review]
Thanks! Left minor comments. 😉

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 5]
```diff
@@ -937,4 +938,17 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
         requireNonNull(function, "function");
         return of(new RecoverableStreamMessage<>(this, function, /* allowResuming */ false));
     }
+
+    default HttpResponse recover(Class<? extends Throwable> causeClass,
+                                 Function<? super Throwable, ? extends HttpResponse> function) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:943]: - Sould we make this type-safer?
```suggestion
    default <T extends Throwable> HttpResponse recover(Class<T> causeClass,
                                 Function<? super T, ? extends HttpResponse> function) {
```
- How about adding the same variant to `StreamMessage.recoverAndResume()`?

Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:943]: **Should we make this type-safer?**
- I will try it  :)

**How about adding the same variant to StreamMessage.recoverAndResume()?**
- I checked the StreamMessage.recoverAndResume() method.
Are you referring to the shortcut function of StreamMessage.recoverAndResume()?

File: core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java (hunk 4 above)
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java:289]: yeah. i will fix it :)

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 3 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:948]: Oh. good idea
I understood that if the function.apply(e) returns null, it should be handled accordingly.
Is that correct?

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:948]: That's correct. 😉

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 5 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java]: i agree adding the same variant to StreamMessage.recoverAndResume() i wiil try it :-)

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 6]
```diff
@@ -772,6 +773,25 @@ default StreamMessage<T> recoverAndResume(
         return new RecoverableStreamMessage<>(this, function, /* allowResuming */ true);
     }
 
+    default <E extends Throwable> StreamMessage<T> recoverAndResume(Class<E> causeClass,
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:776]: - Could you add a Javadoc for this API?
- Add `@UnstableApi` annotation.

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 7]
```diff
@@ -937,4 +938,23 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
         requireNonNull(function, "function");
         return of(new RecoverableStreamMessage<>(this, function, /* allowResuming */ false));
     }
+
+    default <T extends Throwable> HttpResponse recover(Class<T> causeClass,
```
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:942]: sure

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 8]
```diff
@@ -937,4 +938,56 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
...
+     * misMatchRecovered.aggregate().join();
+     * }</pre>
+     * */
+    @UnstableApi
+    default <T extends Throwable> HttpResponse recover(Class<T> causeClass,
+                                                       Function<? super T, ? extends HttpResponse> function) {
+        requireNonNull(causeClass, "causeClass");
+        requireNonNull(function, "function");
+        final StreamMessage<HttpObject> stream = recover(cause -> {
+            if (!cause.getClass().isAssignableFrom(causeClass)) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:980]: I think it makes more sense that the class parameter also handles subclass exceptions. 

```suggestion
            if (!causeClass.isAssignableFrom(cause.getClass())) {
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 9]
```diff
@@ -772,6 +773,52 @@ default StreamMessage<T> recoverAndResume(
...
+     * misMatchRecovered.collect().join();
+     * }</pre>
+     * */
+    @UnstableApi
+    default <E extends Throwable> StreamMessage<T> recoverAndResume(Class<E> causeClass,
+            Function<? super E, ? extends StreamMessage<T>> function) {
+        requireNonNull(causeClass, "causeClass");
+        requireNonNull(function, "function");
+        final StreamMessage<T> stream = recoverAndResume(cause -> {
+            if (!cause.getClass().isAssignableFrom(causeClass)) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:808]: I think it makes more sense that the class parameter also handles subclass exceptions.

```suggestion
            if (!causeClass.isAssignableFrom(cause.getClass())) {
```

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 10]
```diff
@@ -937,4 +938,56 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
         requireNonNull(function, "function");
         return of(new RecoverableStreamMessage<>(this, function, /* allowResuming */ false));
     }
+
+    /**
+     * Recovers an {@link HttpResponse} exception to the specified {@link Throwable} class.
+     * when any error occurs before a {@link ResponseHeaders} is written.
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:944]: This isn't a complete sentence

```suggestion
     * Recovers a failed {@link HttpResponse} by switching to a returned fallback {@link HttpResponse}
     * when the thrown {@link Throwable} is the same type or a subtype of the
     * specified {@code causeClass}.
```

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 8 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:980]: Can you also add a test case for this case?

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java (hunk 9 above)
Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:808]: Can you also add a test case for this case?

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 11]
```diff
@@ -772,6 +773,52 @@ default StreamMessage<T> recoverAndResume(
         return new RecoverableStreamMessage<>(this, function, /* allowResuming */ true);
     }
 
+    /**
+     * Recovers failed {@link StreamMessage} for the specified {@link Throwable} and resumes by subscribing
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:777]:
```suggestion
     * Recovers a failed {@link StreamMessage} for the specified {@link Throwable} and resumes by subscribing
```

File: core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java [hunk 12]
```diff
@@ -74,6 +76,37 @@ void resumeOnError() {
...
+        final StreamMessage<Integer> recoverable =
+            stream.recoverAndResume(IllegalStateException.class, cause -> null);
+        stream.write(1);
+        stream.write(2);
+        stream.write(3);
+        stream.close(ClosedStreamException.get());
+        assertThatThrownBy(() -> recoverable.collect().join())
+            .isInstanceOf(CompletionException.class)
+            .hasCauseInstanceOf(CompositeException.class)
+            .extracting("cause")
```
Comment (jrhee17) [inline core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java:104]: since it's more explicit

```suggestion
            .getCause()
```

**Review by jrhee17 — COMMENTED** [review]
Thanks @devdynam0507 ! I think this PR looks almost ready for merge 👍   Left some minor comments 🙇

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java (hunk 11 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:777]: Thanks. :) i wiil fix it

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 10 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:944]: Thanks! i will fix it

File: core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java (hunk 12 above)
Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java:104]: Thanks ! i will fix it

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java (hunk 9 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:808]: I hadn't thought of this part, but it's a really good idea.
i will fix it and add test case for this case :-)

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 13]
```diff
@@ -772,6 +773,52 @@ default StreamMessage<T> recoverAndResume(
...
+     * stream.write(2);
+     * stream.close(ClosedStreamException.get());
+     * // If the exception type does not match
+     * StreamMessage<Integer> misMatchRecovered =
+     *     stream.recoverAndResume(IllegalStateException.class, cause -> StreamMessage.of(3, 4));
+     *
+     * // In this case, CompletionException is returned. (can't recover exception)
+     * misMatchRecovered.collect().join();
+     * }</pre>
+     * */
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:801]:
```suggestion
     */
```

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 14]
```diff
@@ -937,4 +938,55 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
...
+     * notRecovered.aggregate().join();
+     *
+     * HttpResponse response = HttpResponse.ofFailure(new IllegalStateException("Oops..."));
+     * // If the exception type does not match
+     * HttpResponse misMatchRecovered =
+     *     response.recover(IllegalArgumentException.class, cause -> HttpResponse.of("Fallback"));
+     * // In this case, CompletionException is returned. (can't recover exception)
+     * misMatchRecovered.aggregate().join();
+     * }</pre>
+     * */
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:972]:
```suggestion
     */
```

**Review by ikhoon — APPROVED** [review]
Thanks, @devdynam0507! 🎉🚀

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 14 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java]: Sorry for the trouble! and i reflected

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 15]
```diff
@@ -937,4 +938,55 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
...
+     * HttpResponse notRecovered =
+     *     response.recover(IllegalStateException.class, cause -> HttpResponse.of("Fallback"));
+     * // The IllegalStateException will be raised even though a fallback function was added.
+     * notRecovered.aggregate().join();
+     *
+     * HttpResponse response = HttpResponse.ofFailure(new IllegalStateException("Oops..."));
+     * // If the exception type does not match
+     * HttpResponse misMatchRecovered =
+     *     response.recover(IllegalArgumentException.class, cause -> HttpResponse.of("Fallback"));
+     * // In this case, CompletionException is returned. (can't recover exception)
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:969]:
```suggestion
     * // In this case, CompletionException is thrown. (can't recover exception)
```

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 16]
```diff
@@ -772,6 +773,52 @@ default StreamMessage<T> recoverAndResume(
...
+     *
+     * DefaultStreamMessage<Integer> stream = new DefaultStreamMessage<>();
+     * stream.write(1);
+     * stream.write(2);
+     * stream.close(ClosedStreamException.get());
+     * // If the exception type does not match
+     * StreamMessage<Integer> misMatchRecovered =
+     *     stream.recoverAndResume(IllegalStateException.class, cause -> StreamMessage.of(3, 4));
+     *
+     * // In this case, CompletionException is returned. (can't recover exception)
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:798]:
```suggestion
     * // In this case, CompletionException is thrown. (can't recover exception)
```

**Review by jrhee17 — APPROVED** [review]
Left some minor nits, but looks great! Thanks @devdynam0507 ! 🙇 🚀 👍

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 17]
```diff
@@ -937,4 +938,55 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
...
+     * misMatchRecovered.aggregate().join();
+     * }</pre>
+     */
+    @UnstableApi
+    default <T extends Throwable> HttpResponse recover(Class<T> causeClass,
+                                                       Function<? super T, ? extends HttpResponse> function) {
+        requireNonNull(causeClass, "causeClass");
+        requireNonNull(function, "function");
+        final StreamMessage<HttpObject> stream = recover(cause -> {
```
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:978]: That's a good idea !

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 18]
```diff
@@ -772,6 +773,52 @@ default StreamMessage<T> recoverAndResume(
...
+     * misMatchRecovered.collect().join();
+     * }</pre>
+     */
+    @UnstableApi
+    default <E extends Throwable> StreamMessage<T> recoverAndResume(Class<E> causeClass,
+            Function<? super E, ? extends StreamMessage<T>> function) {
+        requireNonNull(causeClass, "causeClass");
+        requireNonNull(function, "function");
+        final StreamMessage<T> stream = recoverAndResume(cause -> {
```
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:807]: That's a good idea !

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 15 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:969]: 😅

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java (hunk 16 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:798]: 😅

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java [hunk 19]
```diff
@@ -772,6 +773,52 @@ default StreamMessage<T> recoverAndResume(
         return new RecoverableStreamMessage<>(this, function, /* allowResuming */ true);
     }
 
+    /**
+     * Recovers a failed {@link StreamMessage} for the specified {@link Throwable} and resumes by subscribing
+     * to a returned fallback {@link StreamMessage} when any error occurs.
```
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:778]: i will fix it

[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java:778]: good idea :) i will fix it

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 20]
```diff
@@ -937,4 +938,54 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
...
+     * response.write(HttpData.ofUtf8("Hello"));
+     * response.close(new IllegalStateException("Oops..."));
+     * HttpResponse notRecovered =
+     *     response.recover(IllegalStateException.class, cause -> HttpResponse.of("Fallback"));
+     * // The IllegalStateException will be raised even though a fallback function was added.
+     * notRecovered.aggregate().join();
+     *
+     * HttpResponse response = HttpResponse.ofFailure(new IllegalStateException("Oops..."));
+     * // If the exception type does not match
+     * HttpResponse misMatchRecovered =
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:967]: nit:
```suggestion
     * HttpResponse mismatchRecovered =
```
`mismatch` is a word.

**Review by minwoox — COMMENTED** [review]
Thanks! Just one nit. 😄

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 20 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java]: 😅

**Review by minwoox — APPROVED** [review]
Thanks a lot for adding this nice feature. 😄

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 21]
```diff
@@ -937,4 +938,54 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
...
+     * mismatchRecovered.aggregate().join();
+     * }</pre>
+     */
+    @UnstableApi
+    default <T extends Throwable> HttpResponse recover(Class<T> causeClass,
+                                                       Function<? super T, ? extends HttpResponse> function) {
+        requireNonNull(causeClass, "causeClass");
+        requireNonNull(function, "function");
+        return recover(cause -> {
+            if (!causeClass.isAssignableFrom(cause.getClass())) {
```
Comment (trustin) [inline core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:979]: Could be simplified into `!causeClass.isInstance(cause)`?

File: core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java [hunk 22]
```diff
@@ -74,6 +76,50 @@ void resumeOnError() {
         assertThat(recoverable.collect().join()).contains(1, 2, 3, 4, 5, 6);
     }
 
+    @Test
```
Comment (trustin) [inline core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java:79]: Could we also add the tests for chained `recover()` and/or `recoverAndResume()` calls, including the mixture of `recover` and `recoverAndResume`?

Comment (devdynam0507) [reply core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java:79]: of course! 😀

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java (hunk 21 above)
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:979]: that looks better :)

File: core/src/main/java/com/linecorp/armeria/common/HttpResponse.java [hunk 23]
```diff
@@ -937,4 +938,54 @@ default HttpResponse recover(Function<? super Throwable, ? extends HttpResponse>
         requireNonNull(function, "function");
         return of(new RecoverableStreamMessage<>(this, function, /* allowResuming */ false));
     }
+
+    /**
+     * Recovers a failed {@link HttpResponse} by switching to a returned fallback {@link HttpResponse}
+     * when the thrown {@link Throwable} is the same type or a subtype of the
+     * specified {@code causeClass}.
+     *
+     * <p>Example:<pre>{@code
```
[the remark this answers is not in the document]
Comment (devdynam0507) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:947]: Should I add that example to `recover(Function<? super Throwable, ? extends HttpResponse>)` method as well?
It doesn't seem like the correct way to use it, but it can be used.

[the remark this answers is not in the document]
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/common/HttpResponse.java:947]: I think it's enough for now. Thanks for updating the Javadoc 🙇

**Review by trustin — APPROVED** [review]
Thanks a lot, @devdynam0507 🙇

**Comment by minwoox** [comment]
Thanks a lot and congratulations, @devdynam0507! 🎉 🎉 🎉
