### PR TITLE
Fluently add expected exceptions to Logging{Service,Client} 

### LINKED ISSUE #3400: Fluently add expected exceptions to Logging{Service,Client}
A stacktrace of an exception could be excluded from WARN messages and converted into INFO using `responseLogLevelMapper()`
```java
LoggingService.builder()
              .responseLogLevelMapper(log -> {
                  Throwable t = log.responseCause();
                  if (t == null) {
                      return LogLevel.INFO;
                  }
                  if (Execeptions.isExpected(t)) {
                      // Change the log level
                      return LogLevel.INFO;
                  }
                  return LogLevel.WARN;
              })
              .responseCauseSanitizer((ctx, cause) -> {
                  if (Exceptions.isExpected(cause) {
                      // Remove a stacktrace from log
                      return null;
                  }
                  return cause;
              })
              ...;
```

It is possible to program with the existing APIs but a bit complex.
It would be nice if users easily add expected exceptions with a log level.
For example:
```java
LoggingService.builder()
              .addExpectedException(ClosedStreamException.class, LogLevel.INFO)
              .addExpectedException(ClosedSocketException.class, LogLevel.OFF)
              ...
```

### PR DESCRIPTION
**Pull request by ta7uw**
Motivation:

ref. #3400 

Modifications:

- Add `Logging{Service,Client}Builder#responseLogLevel(Class<? extends Throwable> clazz, LogLevel logLevel)`
- Add `Logging{Service,Client}Builder#requestLogLevel(Class<? extends Throwable> clazz, LogLevel logLevel)`

Result:

- Closes #3400
- Users easily add expected exceptions with a log level
For example:
```
        LoggingService.builder()
                      .responseLogLevel(IllegalStateException.class, LogLevel.WARN)
                      .responseLogLevel(IllegalArgumentException.class, LogLevel.ERROR);
                      ...
```

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java [hunk 1]
```diff
@@ -204,9 +211,34 @@ public LoggingDecoratorBuilder responseLogLevelMapper(
...
+            };
+        }
         return responseLogLevelMapper;
     }
 
+    /**
+     * Adds an expected exception and the {@link LogLevel} which will be used when the exception occurred.
+     */
+    public LoggingDecoratorBuilder addExpectedException(Class<? extends Throwable> clazz, LogLevel logLevel) {
+        if (isResponseLogLevelMapperSet) {
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java:234]: I think users might want to use this method and `responseLogLevelMapper` together:
```java
builder.addExpectedException(MyException.class, DEBUG)
       .responseLogLevelMapper(log -> {
            if (infoLog(log.responseHeaders())) {
                // Use INFO depending on the context of the headers.
                return INFO;
            }
            ...
       });
```
In order to make it work, we need to merge #3972 first and keep working on it. 😅

Comment (ta7uw) [reply core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java:234]: I will check this PR.
After PR merged, I redesign this feature.

Comment (ta7uw) [reply core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java]: @minwoox 
I fixed it so that both `addExpectedException ` and `responseLogLevelMapper` can be used at the same time.
Please review again.

File: core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java [hunk 2]
```diff
@@ -223,4 +223,9 @@ public LoggingClientBuilder responseCauseSanitizer(
                     ? extends @Nullable Object> responseCauseSanitizer) {
         return (LoggingClientBuilder) super.responseCauseSanitizer(responseCauseSanitizer);
     }
+
+    @Override
+    public LoggingClientBuilder addExpectedException(Class<? extends Throwable> clazz, LogLevel logLevel) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java:228]: Meanwhile, `ResponseLogLevelMapper` is introduced. Could we move this feature to `ResponseLogLevelMapper`?
```
interface RequestLogLevelMapper {
      static of(Class<? extends Throwable> clazz, LogLevel logLevel) {

      }

      // Optionally, we can add a builder for fluently creating a LogLevel mapper.
}
```

Comment (ta7uw) [reply core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java:228]: It seems good.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java:228]: On second thought, this API is vague whether it is applied to `requestCause()` and `responseCause()`.
How about removing this API and `RequestLogLevelMapper.of(Class<? extends Throwable> clazz, LogLevel logLevel)`.
Everything else is good to me.

Comment (ta7uw) [reply core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java:228]: @ikhoon 
Let me check on your proposal.
Is it correct that the following two points should be addressed?

- `addExpectedException` would be defined only in `LoggingServiceBuilder`
- `RequestLogLevelMapper.of(Class<? extends Throwable> clazz, LogLevel logLevel)` doesn't exist now, Does this refer to `ResponseLogLevelMapper.of(Class<? extends Throwable> clazz, LogLevel logLevel)`?

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java:228]: I'd like to refactor the current implementation like:
- Remove `addExpectedException`. It would be better to add the new API only to `{Request,Response}LogLevelMapper`.
- Add `RequestLogLevelMapper.of(Class<? extends Throwable> clazz, LogLevel logLevel)` and `ResponseLogLevelMapper.of(Class<? extends Throwable> clazz, LogLevel logLevel)`.
- Optionally, add `ResponseLogLevelMapper.builder()` for providing fluent APIs. We may handle this feature in the following PR or if there is a demand for it.

Comment (ta7uw) [reply core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java:228]: Thanks for your detailed explanation!

Comment (ta7uw) [reply core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java]: @ikhoon 
I addressed them.
Please review again.

File: core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java [hunk 3]
```diff
@@ -66,6 +66,26 @@ static ResponseLogLevelMapper of(HttpStatusClass statusClass, LogLevel logLevel)
...
+    static ResponseLogLevelMapper of(Class<? extends Throwable> clazz, LogLevel logLevel) {
+        requireNonNull(clazz, "clazz");
+        requireNonNull(logLevel, "logLevel");
+        return log -> {
+            final Throwable t = log.responseCause();
+            if (t == null) {
+                return null;
+            }
+            final Class<? extends Throwable> throwableClass = t.getClass();
+            if (throwableClass == clazz) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java:82]: Should we use `isAssignableFrom()` so that all subclasses of `clazz` is handled?

File: core/src/main/java/com/linecorp/armeria/common/logging/RequestLogLevelMapper.java [hunk 4]
```diff
@@ -43,6 +43,26 @@ static RequestLogLevelMapper of(LogLevel logLevel) {
...
+    static RequestLogLevelMapper of(Class<? extends Throwable> clazz, LogLevel logLevel) {
+        requireNonNull(clazz, "clazz");
+        requireNonNull(logLevel, "logLevel");
+        return log -> {
+            final Throwable t = log.requestCause();
+            if (t == null) {
+                return null;
+            }
+            final Class<? extends Throwable> throwableClass = t.getClass();
+            if (throwableClass == clazz) {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/logging/RequestLogLevelMapper.java:59]: Ditto. Use `clazz.isAssignableFrom(throwableClass)`?

File: core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java (hunk 3 above)
Comment (ta7uw) [reply core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java]: @ikhoon
I addressed this.
Please review again.

File: core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java [hunk 5]
```diff
@@ -202,6 +202,35 @@ void responseLogLevel() {
                 .isEqualTo(LogLevel.ERROR);
     }
 
+    @Test
+    void responseLogLevelWithThrowable() {
+        builder.successfulResponseLogLevel(LogLevel.INFO)
+               .responseLogLevel(NullPointerException.class, LogLevel.DEBUG)
+               .responseLogLevel(HttpStatusClass.SERVER_ERROR, LogLevel.ERROR)
+               .responseLogLevel(IllegalStateException.class, LogLevel.INFO);
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java:210]: Could we also test hierarchical exceptions?

**Review by ikhoon — APPROVED** [review]
Thanks, @ta7uw! 🙇‍♂️ Left minor comment for tests

**Review by trustin — APPROVED** [review]
Very nice ❤️

**Comment by trustin** [comment]
@jrhee17 @minwoox Gentle ping

File: core/src/main/java/com/linecorp/armeria/common/logging/RequestLogLevelMapper.java [hunk 6]
```diff
@@ -43,6 +43,26 @@ static RequestLogLevelMapper of(LogLevel logLevel) {
         return log -> logLevel;
     }
 
+    /**
+     * Creates a new {@link RequestLogLevelMapper} which returns the specified {@link LogLevel} if the given
+     * class of {@link RequestOnlyLog#requestCause()} is equal to the specified {@link Throwable} class.
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/logging/RequestLogLevelMapper.java:48]:
```suggestion
     * class of {@link RequestOnlyLog#requestCause()} is assignable to the specified {@link Throwable} class.
```

File: core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java [hunk 7]
```diff
@@ -159,6 +169,17 @@ public LoggingDecoratorBuilder responseLogLevel(HttpStatusClass statusClass, Log
         return responseLogLevelMapper(ResponseLogLevelMapper.of(statusClass, logLevel));
     }
 
+    /**
+     * Sets the {@link LogLevel} to use when the response processing failure occurs by specified
+     * {@link Throwable} and logging responses.
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java:174]:
```suggestion
     * Sets the {@link LogLevel} to use when the response fails with the specified {@link Throwable}.
```

File: core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java [hunk 8]
```diff
@@ -105,6 +105,16 @@ public LoggingDecoratorBuilder requestLogLevel(LogLevel requestLogLevel) {
         return requestLogLevelMapper(RequestLogLevelMapper.of(requestLogLevel));
     }
 
+    /**
+     * Sets the {@link LogLevel} to use when the request processing failure occurs by specified
+     * {@link Throwable} and logging requests.
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java:110]:
```suggestion
     * Sets the {@link LogLevel} to use when the response fails with the specified {@link Throwable}.
```

**Review by jrhee17 — APPROVED** [review]
Left some minor documentation related comments but looks great! Thanks @ta7uw ❤️ 👍 🙇

File: core/src/main/java/com/linecorp/armeria/common/logging/RequestLogLevelMapper.java [hunk 9]
```diff
@@ -43,6 +43,26 @@ static RequestLogLevelMapper of(LogLevel logLevel) {
         return log -> logLevel;
     }
 
+    /**
+     * Creates a new {@link RequestLogLevelMapper} which returns the specified {@link LogLevel} if the given
+     * class of {@link RequestOnlyLog#requestCause()} is assignable to the specified {@link Throwable} class.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/logging/RequestLogLevelMapper.java:48]: nit: 
```suggestion
     * class of {@link RequestOnlyLog#requestCause()} is assignable from the specified {@link Throwable} class.
```

File: core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java [hunk 10]
```diff
@@ -66,6 +66,26 @@ static ResponseLogLevelMapper of(HttpStatusClass statusClass, LogLevel logLevel)
         return log -> log.responseStatus().codeClass() == statusClass ? logLevel : null;
     }
 
+    /**
+     * Creates a new {@link ResponseLogLevelMapper} which returns the specified {@link LogLevel} if the given
+     * class of {@link RequestLog#responseCause()} is assignable to the specified {@link Throwable} class.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java:71]: nit:
```suggestion
     * class of {@link RequestLog#responseCause()} is assignable from the specified {@link Throwable} class.
```

**Review by minwoox — APPROVED** [review]
Just nits. Thanks! 😄

**Comment by minwoox** [comment]
Great job as always, @ta7uw 😄
