### PR TITLE
Fix bugs while converting `StreamMessage` to `InputStream`

### LINKED ISSUE #4268: Failed to convert an `HttpResponse` into an `InputStream`
@eisig reported a bug in `StreamMessageInputStream` converter.

> Hi,  I want to use   HttpResponse.toInputStream() to convert httpResponse to inputStream. But The following code would not work, It seems that  inputStream eos is not set.
```java
@Test
void testDownload() throws IOException {
    WebClient webClient = WebClient.builder(serverExtension.httpUri()).decorator(LoggingClient.newDecorator())
            .build();
    HttpResponse response = webClient.prepare().get("/download").queryParam("xx", "xx").execute();
    InputStream inputStream = response.toInputStream(httpObject -> {
        if (httpObject instanceof HttpData) {
            return (HttpData) httpObject;
        }
        return HttpData.empty();
    });
    // just for test. 
    // it would keep waiting here.
    byte[] bytes = ByteStreams.toByteArray(inputStream);
}
```
Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1653303100545389

To fix the bug, If `httpDataConverter` returns `HttpData.empty()`, `StreamMessageInputStreamSubscriber` should request the next element to the upstream to produce bytes.
https://github.com/line/armeria/blob/e08d486816ce9beafd10b5971393667bc288a58b/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageInputStream.java#L133

### PR DESCRIPTION
**Pull request by injae-kim**
**Related Bug Issue** #4268 

### Motivation:
We found some bugs on `StreamMessageInputStream`
1. If `httpDataConverter` returns `HttpData.empty()`, `StreamMessageInputStreamSubscriber` should request the next element to the upstream to produce bytes but currently doesn't request any element
2. `StreamMessageInputStream` could call `subscriber.request()` even if `byteBufsInputStream` has enough data

### Modifications:
- If `httpDataConverter` returns `HttpData.empty()`, `StreamMessageInputStreamSubscriber` requests the next element to the upstream
- `StreamMessageInputStream` calls `subscriber.request()` only when `byteBufsInputStream` has not enough data

### Result:
- Fix two bugs on `StreamMessageInputStream`
- ✅ Close #4268 issue

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageInputStream.java [hunk 1]
```diff
@@ -130,7 +136,12 @@ public void onNext(T item) {
                  return;
             }
             try {
-                byteBufsInputStream.add(httpDataConverter.apply(item).byteBuf());
+                final HttpData result = httpDataConverter.apply(item);
+                if (result.isEmpty()) {
+                    request();
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageInputStream.java:141]:
```suggestion
                if (result.isEmpty()) {
                    result.close();
                    request();
```

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java [hunk 2]
```diff
@@ -318,4 +323,112 @@ void toInputStream_executor() throws IOException {
...
+        assertThat(inputStream.available()).isZero();
+    }
+
+    @Test
+    void httpDataConverter_error_thrown() throws IOException {
+        final StreamMessage<Integer> streamMessage = StreamMessage.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
+        final InputStream inputStream = streamMessage
+                .toInputStream(x -> {
+                    if (x == 6) {
+                        return Exceptions.throwUnsafely(new RuntimeException());
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java:365]: We can throw a non-checked exception in a `Function<T, R>`.
```suggestion
                        throw new RuntimeException();
```

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java [hunk 3]
```diff
@@ -318,4 +323,112 @@ void toInputStream_executor() throws IOException {
...
+        byte[] actual = new byte[readableBytes];
+        for (int i = 0; i < readableBytes; i++) {
+            actual[i] = result.readByte();
+        }
+        assertThat(actual).isEqualTo(ImmutableList.of("12")
+                                                  .stream()
+                                                  .map(String::getBytes)
+                                                  .reduce(Bytes::concat).get());
+        assertThat(inputStream.available()).isEqualTo(0);
+        verify(streamMessage2, never()).subscribe(any(), any(), any());
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java:414]: Could we test this without mocking?
We may use `StreamWriter.whenConsumed()` and `StreamMessage.demand()` to know whether a request is made.

Comment (injae-kim) [reply core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java]: ✅ updated (use `whenConsumed` instead of `mocking`)

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java [hunk 4]
```diff
@@ -318,4 +319,119 @@ void toInputStream_executor() throws IOException {
...
+        int read;
+        while ((read = inputStream.read()) != -1) {
+            result.writeByte(read);
+        }
+
+        final int readableBytes = result.readableBytes();
+        final byte[] actual = new byte[readableBytes];
+        for (int i = 0; i < readableBytes; i++) {
+            actual[i] = result.readByte();
+        }
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java:381]: Should we use `ByteBufUtil.getBytes()`?

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java [hunk 5]
```diff
@@ -318,4 +319,119 @@ void toInputStream_executor() throws IOException {
...
+        byte[] actual = new byte[readableBytes];
+        for (int i = 0; i < readableBytes; i++) {
+            actual[i] = result.readByte();
+        }
+        assertThat(actual).isEqualTo(ImmutableList.of("12")
+                                                  .stream()
+                                                  .map(String::getBytes)
+                                                  .reduce(Bytes::concat).get());
+        assertThat(inputStream.available()).isEqualTo(0);
+        assertThat(consumed.get()).isFalse();
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java:417]: nit:
```suggestion
        assertThat(inputStream.available()).isZero();
        assertThat(consumed).isFalse();
```

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java [hunk 6]
```diff
@@ -318,4 +319,119 @@ void toInputStream_executor() throws IOException {
...
+        int read;
+        while ((read = inputStream.read()) != -1) {
+            result.writeByte(read);
+        }
+
+        readableBytes = result.readableBytes();
+        actual = new byte[readableBytes];
+        for (int i = 0; i < readableBytes; i++) {
+            actual[i] = result.readByte();
+        }
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java:428]: Should we use `ByteBufUtil.getBytes()`?

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java [hunk 7]
```diff
@@ -318,4 +319,119 @@ void toInputStream_executor() throws IOException {
...
+        result.release();
+        assertThat(actual).isEqualTo(ImmutableList.of("34", "56", "78")
+                                                  .stream()
+                                                  .map(String::getBytes)
+                                                  .reduce(Bytes::concat).get());
+        assertThat(inputStream.available()).isZero();
+        assertThat(consumed.get()).isTrue();
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java:435]: I'm not sure this guarantee a happen-before relationship. `whenComsumed()` may call in a different thread.
```suggestion
        await().untilTrue(consumed);
```

**Review by trustin — COMMENTED** [review]
LGTM once @ikhoon's comments are addressed. Thanks, @injae-kim !

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java [hunk 8]
```diff
@@ -318,4 +319,119 @@ void toInputStream_executor() throws IOException {
...
+
+    @Test
+    void maybeRequest_when_not_enough_data() throws IOException {
+        final StreamMessage<String> streamMessage1 = StreamMessage.of("12", "34");
+        final DefaultStreamMessage<String> streamMessage2 = new DefaultStreamMessage<>();
+        streamMessage2.write("56");
+        streamMessage2.write("78");
+        final AtomicBoolean consumed = new AtomicBoolean();
+        streamMessage2.whenConsumed().thenRun(() -> {
+            consumed.getAndSet(true);
```
[the remark this answers is not in the document]
Comment (injae-kim) [reply core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java]: ✅ updated

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java (hunk 5 above)
Comment (injae-kim) [reply core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java]: ✅ updated!

File: core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java (hunk 7 above)
Comment (injae-kim) [reply core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java]: ✅ updated!

**Comment by minwoox** [comment]
Thanks for the fix. 😉 
How about also adding a logic that does not add an empty byte buf here?
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java#L155

**Comment by ikhoon** [comment]
Not related to this PR but If the `InputStream` was closed already, should we release the `ByteBuf` before raising `IllegalStateException`?
https://github.com/line/armeria/blob/e9e1107d6ee935775a3265c1a1d4ca570fd1f28e/core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java?rgh-link-date=2022-06-07T02%3A46%3A17Z#L152-L154

**Comment by trustin** [comment]
> Not related to this PR but If the `InputStream` was closed already, should we release the `ByteBuf` before raising `IllegalStateException`?
https://github.com/line/armeria/blob/e9e1107d6ee935775a3265c1a1d4ca570fd1f28e/core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java?rgh-link-date=2022-06-07T02%3A46%3A17Z#L152-L154

Yes, we do. Could you send out a PR for it, @ikhoon?

**Comment by trustin** [comment]
> Thanks for the fix. 😉 
How about also raising an exception if an empty byte buf is added?
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java#L155

Probably better just silently releasing?

**Comment by trustin** [comment]
@injae-kim Could you check the last comments from @minwoox and @ikhoon?

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java [hunk 9]
```diff
@@ -150,6 +150,7 @@ public void setEos() {
     public void add(ByteBuf buffer) {
         requireNonNull(buffer, "buffer");
         if (eos.get()) {
+            buffer.release();
```
Comment (injae-kim) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:153]: > Not related to this PR but If the InputStream was closed already, should we release the ByteBuf before raising IllegalStateException? https://github.com/line/armeria/pull/4271#issuecomment-1149374229

✅ updated, release buffer before throw exception when InputStream was already closed

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java [hunk 10]
```diff
@@ -150,6 +150,7 @@ public void setEos() {
...
             throw new IllegalStateException("Already closed");
         }
         if (!buffers.add(buffer)) {
```
Comment (injae-kim) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:156]: > Thanks for the fix. 😉
How about also raising an exception if an empty byte buf is added?
... or Probably better just silently releasing? https://github.com/line/armeria/pull/4271#issuecomment-1148133323

```java
ByteBufsInputStream stream = new ByteBufsInputStream();
ByteBuf buffer = Unpooled.buffer(); // empty at first
stream.add(buffer);

buffer.writeByte(1); // write 1
stream.read() // return 1
```
Hmm..  maybe `ByteBufsInputStream` allow to add `empty` ByteBuf,
So I'm not sure we should `release` or `raising` an exception if an `empty` ByteBuf is added. WDYT? 🤔
cc. @minwoox 

https://github.com/line/armeria/blob/7561be45824b691a32e486d8d8a98c3ad930c32b/core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java#L224-L226
(`ByteBufsInputStream` already handles `empty` ByteBuf inside)

Comment (injae-kim) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:156]: > Hmm.. maybe ByteBufsInputStream allow to add empty ByteBuf

So my opinion is just keeping current implementation! (allow to add `empty` ByteBuf on `ByteBufsInputStream`)

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:156]: Let's say that the following `ByteBufs` are added consecutively:
```
ByteBuf(3 bytes) - ByteBuf(0 byte) - ByteBuf(4 bytes) 
```
Even though we have more bytes to read, we can't get the last `ByteBuf` that has 4 bytes in it.
To prevent this, I think we have two possible solutions:
- Return `0` instead of `-1` when `buffer.isReadable()` returns `false` so that we can keep continue to read.
- Do not allow the empty buffer to get added.

Because we add `EMPTY_BUFFER` in the `setEos` method to tell the end of the bytes, if we go to the first solution, we need more work to do. (e.g. adding the special empty buffer instead of `Unpooled.EMPTY_BUFFER` to indicate eos.)
So I prefer the second one which silently releases it and does not add the queue as @trustin suggested.
What do you think? @injae-kim

Comment (injae-kim) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:156]: > ByteBuf(3 bytes) - ByteBuf(0 byte) - ByteBuf(4 bytes) 

oh.. I understood your explanation. I didn't know this case!

> I prefer the second one which silently releases it and does not add the queue as @trustin suggested.

I'll update PR in this way! thanks 👍

Comment (injae-kim) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:160]: https://github.com/line/armeria/blob/7561be45824b691a32e486d8d8a98c3ad930c32b/core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java#L208-L211

> ByteBuf(3 bytes) - ByteBuf(0 byte) - ByteBuf(4 bytes) 

Oh.. after some checking, I found that there's already handling logic for empty bytebuf,
so I think above case is not occurred (`ByteBuf(0 byte)` will be passed during read())

Anyway, I address @minwoox comment and enhance unit test for adding empty bytebuf case 🙇

File: core/src/test/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStreamTest.java [hunk 11]
```diff
@@ -96,6 +98,43 @@ void testPreBuffered() {
         assertThat(resultStrings.get(4)).isEqualTo("fifth");
     }
 
+    @Test
+    void testAdd_ignoreEmptyByteBuf() {
```
Comment (injae-kim) [inline core/src/test/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStreamTest.java:102]: https://github.com/line/armeria/blob/7561be45824b691a32e486d8d8a98c3ad930c32b/core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java#L208-L211

(FYI) @minwoox , thanks to above code, this test anyway passed without my change.
But anyway, I address your comment! (ignore empty bytebuf on add())

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java (hunk 10 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:160]: Ah, I didn't know that we're already handling the case. 😅  thanks.

**Review by minwoox — APPROVED** [review]
Thanks! ❤️

File: core/src/test/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStreamTest.java [hunk 12]
```diff
@@ -96,6 +98,45 @@ void testPreBuffered() {
...
+        strings1.forEach(s -> stream.add(Unpooled.wrappedBuffer(s.getBytes(StandardCharsets.UTF_8))));
+        stream.add(empty);
+        strings2.forEach(s -> stream.add(Unpooled.wrappedBuffer(s.getBytes(StandardCharsets.UTF_8))));
+        stream.setEos();
+
+        final Scanner scanner = new Scanner(stream).useDelimiter(",");
+        final ImmutableList.Builder<String> resultBuilder = ImmutableList.builder();
+        while (scanner.hasNext()) {
+            final String s = scanner.next();
+            System.out.println(s);
```
Comment (ikhoon) [inline core/src/test/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStreamTest.java:119]:
```suggestion
```

File: core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java [hunk 13]
```diff
@@ -150,8 +150,13 @@ public void setEos() {
...
         if (eos.get()) {
+            buffer.release();
             throw new IllegalStateException("Already closed");
         }
+        if (!buffer.isReadable()) {
+            buffer.release();
+            return;
+        }
         if (!buffers.add(buffer)) {
             throw new IllegalStateException("Unable to add new buffer");
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java:161]: The `buffer` should also be released before raising `IllegalStateException("Unable to add new buffer")`.

**Review by trustin — APPROVED** [review]
Thanks for fixing this, @injae-kim! 🙇
