### PR TITLE
Fix incorrect stream ID used for HTTP/2 flow control

### LINKED ISSUE #6367: Http2Connection (stream 0) unexpectedly consumes too many bytes.
Hi team, and thank you for your great work on this project.

After upgrading to Armeria 1.33.1 with Netty 4.2.4.Final, we started encountering the following Http2Exception when handling streams.
This issue has already appeared since Armeria 1.33.0, but when upgrading only netty-bom to 4.2.4.Final (while staying on Armeria 1.32.x), the issue did not occur.
```
Attempting to return too many bytes for stream 0
at  io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:98)
at  io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:141)
at  io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.returnProcessedBytes(DefaultHttp2LocalFlowController.java:434)
at  io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.consumeBytes(DefaultHttp2LocalFlowController.java:443)
at  io.netty.handler.codec.http2.DefaultHttp2LocalFlowController.consumeAllBytes(DefaultHttp2LocalFlowController.java:196)
at  io.netty.handler.codec.http2.DefaultHttp2LocalFlowController.access$500(DefaultHttp2LocalFlowController.java:42)
at  io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$1.onStreamClosed(DefaultHttp2LocalFlowController.java:110)
at  io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:355)
at  io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1043)
at  io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:999)
at  io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515)
at  io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:521)
at  io.netty.handler.codec.http2.Http2ConnectionHandler.doCloseStream(Http2ConnectionHandler.java:919)
at  io.netty.handler.codec.http2.Http2ConnectionHandler.access$900(Http2ConnectionHandler.java:64)
at  io.netty.handler.codec.http2.Http2ConnectionHandler$2.operationComplete(Http2ConnectionHandler.java:632)
at  io.netty.handler.codec.http2.Http2ConnectionHandler$2.operationComplete(Http2ConnectionHandler.java:629)
at  io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:603)
at  io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:596)
at  io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:572)
at  io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:505)
at  io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:649)
at  io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:638)
at  io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:118)
at  io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
at  io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:52)
at  io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31)
at  io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:603)
at  io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:596)
at  io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:572)
at  io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:505)
at  io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:649)
at  io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:638)
at  io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:118)
at  io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
at  io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:381)
at  io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:348)
at  io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:260)
at  io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
at  io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:52)
at  io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31)
at  io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:603)
at  io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:596)
at  io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:572)
at  io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:505)
at  io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:649)
at  io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:638)
at  io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:118)
at  io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
at  io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:747)
at  io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:302)
at  io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:382)
at  io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:381)
at  io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:259)
at  io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:470)
at  io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:428)
at  io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:802)
at  io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:601)
at  io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:766)
at  io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1391)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:789)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:775)
at  io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:761)
at  io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:204)
at  io.netty.handler.flush.FlushConsolidationHandler.flush(FlushConsolidationHandler.java:138)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:791)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:775)
at  io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:761)
at  io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:2325)
at  io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:848)
at  io.netty.handler.ssl.SslHandler.flush(SslHandler.java:825)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:795)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:775)
at  io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:761)
at  com.linecorp.armeria.internal.common.TrafficLoggingHandler.flush(TrafficLoggingHandler.java:49)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:791)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:775)
at  io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:761)
at  io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:195)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:795)
at  io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:775)
at  io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:761)
at  com.linecorp.armeria.server.AbstractHttpResponseSubscriber.onNext(AbstractHttpResponseSubscriber.java:227)
at  com.linecorp.armeria.server.AbstractHttpResponseSubscriber.onNext(AbstractHttpResponseSubscriber.java:57)
at  com.linecorp.armeria.internal.common.stream.RecoverableStreamMessage$RecoverableSubscriber.onNext(RecoverableStreamMessage.java:227)
at  com.linecorp.armeria.common.stream.FuseableStreamMessage$FuseableSubscriber.onNext(FuseableStreamMessage.java:288)
at  com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onNext(DeferredStreamMessage.java:516)
at  com.linecorp.armeria.common.stream.FuseableStreamMessage$FuseableSubscriber.onNext(FuseableStreamMessage.java:288)
at  com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onNext(DeferredStreamMessage.java:516)
at  com.linecorp.armeria.common.stream.FuseableStreamMessage$FuseableSubscriber.onNext(FuseableStreamMessage.java:288)
at  com.linecorp.armeria.internal.common.stream.RecoverableStreamMessage$RecoverableSubscriber.onNext(RecoverableStreamMessage.java:227)
at  com.linecorp.armeria.common.stream.FuseableStreamMessage$FuseableSubscriber.onNext(FuseableStreamMessage.java:288)
at  com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:420)
at  com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:398)
at  io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:148)
at  io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:141)
at  io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:507)
at  io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:183)
at  io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073)
at  io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at  io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

A [related issue](https://github.com/netty/netty/issues/15536) has also been reported in Netty, though in that case it was observed with gRPC.
In our service, based on thread metrics and stack traces, we have confirmed that the same problem occurs with SSL connections as well.

I suspect this may be related to flow control handling. I noticed that [Armeria 1.33.0 introduced improvements in H2 flow control](https://github.com/line/armeria/pull/6266), which might be relevant.
So I've tried the following, but the exception still occurs:

Hypothesis: flow control contention between Armeria and Netty
- Added early return in consumeHttp2Bytes if the connection has received GOAWAY
- Added early return when the stream is already closed

Hypothesis: frequent window size updates
- Adjusted HTTP2_STREAM_WINDOW_UPDATE_RATIO to 90%

Unfortunately, none of these changes prevented the issue.

Any guidance, insights, or suggestions would be greatly appreciated.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

Armeria internally maintains request IDs for a connection which are monotonically increased starting from 1.
https://github.com/line/armeria/blob/603fc8685059ffafed5096261a14fd502f0be33f/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L211
A stream ID for HTTP/2 flow control is calculated from the request ID using (id * 2 + 1).
https://github.com/line/armeria/blob/603fc8685059ffafed5096261a14fd502f0be33f/core/src/main/java/com/linecorp/armeria/internal/common/InboundTrafficController.java#L150-L152
That formula must not be used on the server side because the client may skip a stream ID or a request may be rejected before the ID is incremented.

Modifications:

- Use the actual stream ID provided by Netty instead of deriving from the request ID.

Result:

- Fixed HTTP/2 flow control by using a correct stream ID for computing the window size.
- Closes #6367

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java [hunk 1]
```diff
@@ -527,7 +527,7 @@ public void channelActive(ChannelHandlerContext ctx) throws Exception {
 
             final int id = 0;
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java:528]: Shouldn't it be 1 since it's streamId?

File: core/src/main/java/com/linecorp/armeria/internal/client/DecodedHttpResponse.java [hunk 2]
```diff
@@ -79,8 +79,12 @@ protected void onRemoval(HttpObject obj) {
         if (obj instanceof HttpData) {
             final int length = ((HttpData) obj).length();
             assert inboundTrafficController != null;
-            assert id > -1 : "id must be set before consuming HttpData";
-            inboundTrafficController.dec(id, length);
+            assert streamId > -1 : "id must be set before consuming HttpData";
+            if (streamId == 1) {
+                // The stream ID 1 is used for an HTTP/1 upgrade request.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/client/DecodedHttpResponse.java:88]: If we want to handle this as a special case, I think we should also do it in `tryWrite`.

**Review by minwoox — APPROVED** [review]
Thanks!

File: core/src/main/java/com/linecorp/armeria/internal/client/DecodedHttpResponse.java (hunk 2 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/internal/client/DecodedHttpResponse.java:88]: Makes sense. Done.
