### PR TITLE
Set response content preview after recovering failed responses

### LINKED ISSUE #3969: Response content preview isn't produced if handled by the `ServerErrorHandler`
When a `HttpResponse` is recovered by the `ServerErrorHandler`, the `ContentPreviewingService` doesn't produce `responseContentPreview`. Here's a reproducible test:

```java
public class ContentPreviewingServiceTest {

    static final AtomicReference<ServiceRequestContext> ctxCaptor = new AtomicReference<>();

    @RegisterExtension
    static final ServerExtension server = new ServerExtension() {
        @Override
        protected void configure(ServerBuilder builder) {
            builder.service("/foo", (ctx, req) -> {
                       throw new RuntimeException();
                   })
                   .decorator(ContentPreviewingService.newDecorator(Integer.MAX_VALUE))
                   .decorator((delegate, ctx, req) -> {
                       ctxCaptor.set(ctx);
                       return delegate.serve(ctx, req);
                   })
                   .errorHandler((ctx, cause) -> HttpResponse.of(HttpStatus.INTERNAL_SERVER_ERROR,
                                                                 MediaType.PLAIN_TEXT,
                                                                 "ServerErrorHandler"));
        }
    };

    @Test
    void responseContentPreview() {
        final WebClient client = WebClient.of(server.httpUri());
        final AggregatedHttpResponse res = client.get("/foo").aggregate().join();
        assertThat(res.contentUtf8()).isEqualTo("ServerErrorHandler");

        final ServiceRequestContext ctx = ctxCaptor.get();
        final RequestLog log = ctx.logBuilder().whenComplete().join();
        assertThat(log.responseContentPreview()).isEqualTo("ServerErrorHandler"); // should not be null!!
    }
}
```

This is because a `HttpResponse` returned from the `ServerErrorHandler` isn't decorated by the `ContentPreviewingService`.

### PR DESCRIPTION
**Pull request by 0x1306e6d**
Motivation:

Related issues:
- #3969
- #5076
- #5714

Response content preview on recovered `HttpResponse` is not recorded.

If an `HttpResponse` is failed and recovered by the `ServerErrorHandler`, `ContentPreviewingService` cannot set up the `ContentPreviewerHttpResponse` with the recovered `HttpResponse`.

Modifications:

- Set up `ContentPreviewerHttpResponse` at the recover block on `HttpServerHandler` if service is decorated by `ContentPreviewingService`.

Result:

- Closes #3969
- Fixes a bug that failed and recovered `HttpResponse` does not produce response content preview.

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java [hunk 1]
```diff
@@ -470,7 +471,18 @@ private void handleRequest(ChannelHandlerContext ctx, DecodedHttpRequest req) th
...
+                if (contentPreviewingService != null) {
+                    if (errorRes != null) {
+                        return contentPreviewingService.setUpResponseContentPreviewer(reqCtx, errorRes);
+                    } else {
+                        // Call requestContentPreview(null) to make sure that the log is complete.
+                        reqCtx.logBuilder().responseContentPreview(null);
+                    }
+                }
+                return errorRes;
             }
```
Comment (0x1306e6d) [inline core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: After implementation, I think it increases the complexity of the `HttpServerHandler`. `ServerBuilder#contentPreview` might be better (https://github.com/line/armeria/pull/5076/files#r1363377593). This approach is very similar with my original pull request #5076.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: > I think it increases the complexity of the HttpServerHandler.

I agree with you. I don't think it is a good idea to add decorator-related logic to `HttpServerHandler` either.

The role of `CorsServerErrorHandler` is similar, which provides a fallback mechanism when `CorsService` fails to handle a request. What do you think about abstracting CorsServerErrorHandler into a more general decorator error handler that can also handle `ContentPreviewingErrorHandler` use cases?

We may design the internal API as follows:

```java
interface FailsafeDecoratorErrorHandler {

    void beforeOnServiceException(ServiceRequestContext ctx, Throwable cause);

    HttpResponse afterOnServiceException(ServiceRequestContext ctx, Throwable cause, HttpResponse response);
}

class CorsServerErrorHandler implements FailsafeDecoratorErrorHandler {

    @Override
    public void beforeOnServiceException(ServiceRequestContext ctx, Throwable cause) {
        if (shouldSetCorsHeaders(corsService, ctx)) {
            ...
        }
    }

    @Override
    public HttpResponse afterOnServiceException(ServiceRequestContext ctx, Throwable cause,
                                                HttpResponse response) {
        return response;
    }
}

class ContentPreviewErrorHandler implements FailsafeDecoratorErrorHandler {

    @Override
    public void beforeOnServiceException(ServiceRequestContext ctx, Throwable cause) {
        // No-op for content preview decorator.
    }

    @Override
    public HttpResponse afterOnServiceException(ServiceRequestContext ctx, Throwable cause,
                                                HttpResponse response) {
        // No-op for content preview decorator.
        final ContentPreviewingService contentPreviewingService =
                ctx.findService(ContentPreviewingService.class);
        ...
        return response;
    }
}

final class InternalServerErrorHandler implements ServerErrorHandler {
    ServerErrorHandler serverErrorHandler;
    FailsafeDecoratorErrorHandler failsafeDecoratorErrorHandler;

    ...
    public HttpResponse onServiceException(ServiceRequestContext ctx, Throwable cause) {
        failsafeDecoratorErrorHandler.beforeOnServiceException(ctx, cause);
        HttpResponse response = serverErrorHandler.onServiceException(ctx, cause);
        return failsafeDecoratorErrorHandler.afterOnServiceException(ctx, cause, response);
    }
}
```

Comment (0x1306e6d) [reply core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java]: Thank you, @ikhoon!
I could remove changes from `HttpServerHandler`.

File: core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java [hunk 2]
```diff
@@ -159,10 +161,19 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exc
...
+
+    /**
+     * Sets up the response {@link ContentPreviewer} to set
+     * {@link RequestLogBuilder#responseContentPreview(String)} when the preview is available.
+     */
+    public HttpResponse setUpResponseContentPreviewer(ServiceRequestContext ctx, HttpResponse res) {
+        return ContentPreviewingUtil.setUpResponseContentPreviewer(contentPreviewerFactory,
+                                                                   ctx, res,
+                                                                   responsePreviewSanitizer);
+    }
```
Comment (0x1306e6d) [inline core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java]: We can hide this as package-protected if we make `DecoratingServerErrorHandler` as public (at the internal package) and move the `ContentPreviewServerErrorHandler` to this package.

Comment (jrhee17) [reply core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java]: > We can hide this as package-protected if we make DecoratingServerErrorHandler as public (at the internal package) and move the ContentPreviewServerErrorHandler to this package.

Maybe I'm missing something, but won't `ContentPreviewServerErrorHandler` need to be accessed from the `com.linecorp.armeria.server` package? If there is a way to hide this method, I prefer it over the current public method.

Personally I think it's fine to just take the same approach as `CorsService` (exposing `contentPreviewerFactory` and `responsePreviewSanitizer` publicly).

File: core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java [hunk 3]
```diff
@@ -114,7 +114,10 @@ protected ContentPreviewerHttpResponse(
             this.factory = factory;
             this.ctx = ctx;
             whenComplete().handle((unused, cause) -> {
-                if (responseContentPreviewer != null) {
+                if (responseContentPreviewer == null) {
+                    return null;
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java:118]: I assume this change is to ensure failed responses (e.g. `HttpResponse#ofFailure`) do not record `log#[request|response]ContentPreview`.

**Review by jrhee17 — APPROVED** [review]
Approach looks good to me

File: core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java (hunk 2 above)
Comment (0x1306e6d) [reply core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java]: > Personally I think it's fine to just take the same approach as CorsService (exposing contentPreviewerFactory and responsePreviewSanitizer publicly).

Looks better. I applied this approach.

File: core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java (hunk 3 above)
Comment (0x1306e6d) [reply core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java:118]: Right. I thought that response content preview of the failed response is set here:

https://github.com/line/armeria/pull/6269/files/5e540da155391cc16073c77e88dcc08259a0f1b0

File: core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java [hunk 4]
```diff
@@ -140,6 +140,20 @@ public static ContentPreviewingServiceBuilder builder(ContentPreviewerFactory co
         this.responsePreviewSanitizer = responsePreviewSanitizer;
     }
 
+    /**
+     * Returns the specified {@link ContentPreviewerFactory}.
+     */
+    public ContentPreviewerFactory contentPreviewerFactory() {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java:148]:
```suggestion
    @UnstableApi
    public ContentPreviewerFactory contentPreviewerFactory() {
```

File: core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java [hunk 5]
```diff
@@ -140,6 +140,20 @@ public static ContentPreviewingServiceBuilder builder(ContentPreviewerFactory co
...
+        return contentPreviewerFactory;
+    }
+
+    /**
+     * Returns the specified {@link BiFunction} that sanitizes the request content preview.
+     */
+    public BiFunction<? super RequestContext, String, ? extends @Nullable Object> responsePreviewSanitizer() {
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java:156]: `super` and `extends` are useful when they are applied to method arguments.
```suggestion
    @UnstableApi
    public BiFunction<RequestContext, String, ? extends @Nullable Object> responsePreviewSanitizer() {
```

**Review by ikhoon — APPROVED** [review]
The new design looks nice. 👍 💯

File: core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java (hunk 5 above)
Comment (0x1306e6d) [reply core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java:156]: Thanks.

I tried to use `BiFunction<RequestContext, String, ? extends @Nullable Object>` but couldn't as the type is already `super`:

https://github.com/line/armeria/blob/4296916f1aec328997a2d3ddfd43218191e39e9c/core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java#L125-L126

Maybe I used a wrong type at the beginning (#3795).

File: core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java [hunk 6]
```diff
@@ -140,6 +141,22 @@ public static ContentPreviewingServiceBuilder builder(ContentPreviewerFactory co
...
+    /**
+     * Returns the specified {@link ContentPreviewerFactory}.
+     */
+    @UnstableApi
+    public ContentPreviewerFactory contentPreviewerFactory() {
+        return contentPreviewerFactory;
+    }
+
+    /**
+     * Returns the specified {@link BiFunction} that sanitizes the request content preview.
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java]:
```suggestion
     * Returns the specified {@link BiFunction} that sanitizes the response content preview.
```

**Review by minwoox — APPROVED** [review]
Looks great, thanks! 👍

File: core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java (hunk 5 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java:156]: It is not a big deal. Let's keep it as is.
