### PR TITLE
Abort server startup if `ServerListener.serverStarting` throws an exception 

### LINKED ISSUE #3935: `Server` should abort startup if `ServerListener.serverStarting` throws an exception
Currently, `Server` starts up regardless of whether any `ServerListener` callbacks throw an exception.

https://github.com/line/armeria/blob/43bd08248ba86ab5942f781da33b11a42fe3b1a5/core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java#L368-L387

However, our javadoc specifies that `Server` startup should abort on exception

https://github.com/line/armeria/blob/43bd08248ba86ab5942f781da33b11a42fe3b1a5/core/src/main/java/com/linecorp/armeria/server/ServerListener.java#L34-L37

Reference: https://line-armeria.slack.com/archives/C1NGPBUH2/p1637107630059700

### PR DESCRIPTION
**Pull request by jrhee17**
Motivation:

In our javadoc, it is stated that if `ServerListener#serverStarting` throws an exception `Server` startup is aborted.
https://github.com/line/armeria/blob/43bd08248ba86ab5942f781da33b11a42fe3b1a5/core/src/main/java/com/linecorp/armeria/server/ServerListener.java#L34-L37

However, this behavior currently isn't supported since the introduction of `StartStopSupport`.

Additionally, we have verified that this is still a valid use case. (i.e. users may want to do some validation before proceeding with server startup)

Modifications:

I think it is difficult to cleanly decouple the behavior of `StartStopSupport` and `Server` without breaking changes (see 580560de57c77755300460c3aeccd540366148bf for the attempt). I also think it is acceptable for `StartStopSupport` to support the behavior where an exception in `notifyStarting` fails startup.

- Modify `StartStopSupport#notifyListeners` to throw an exception if `state == State.Starting `
    - Eventually, the exception will be thrown before startup starts in the following line: https://github.com/line/armeria/blob/a1105519e920b00ee3bc848a5074d943925931ef/core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java#L184
- Add `try..catch` statements which ignores the exception (since other states won't propagate the exception + there is no additional behavior required to restore from the exception)

Result:

- Closes #3935
- `StartStopSupport` now aborts startup if `notifyStarting` throws an exception.

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
Nice work! 👍

File: core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java [hunk 1]
```diff
@@ -384,6 +395,11 @@ private void notifyListeners(State state, @Nullable T startArg, @Nullable U stop
                 }
             } catch (Exception cause) {
                 notificationFailed(l, cause);
+
+                // if notifyStarting throws an exception, propagate the exception
+                if (state == State.STARTING) {
+                    throw cause;
+                }
```
Comment (ikhoon) [inline core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java:402]: How about wrapping the cause with `IllegalStateException("Failed to start the server", cause)` and removing `throws Exception`?

**Review by trustin — APPROVED** [review]
