### PR TITLE
Return "431 Request Header Fields Too Large" for long headers on HTTP/1

### LINKED ISSUE #4609: Return "431 Request Header Fields Too Large" when the header value exceeds
Netty HTTP/1 codec raises `TooLongHttpHeaderException` if headers exceed the max length limit.
However, `Http1RequestDecoder` only checks `TooLongHttpLineException` and returns "414 Request-URI Too Long". Otherwise, "400 Bad Request" is returned.
https://github.com/line/armeria/blob/d9d9d3ea16efb17d24b9935885fd2a2b4da25aa9/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L179-L183

It would make sense to return `431 Request Header Fields Too Large` when `TooLongHttpHeaderException` is raised.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

Netty HTTP/1 codec raises `TooLongHttpHeaderException` if headers exceed the max length limit. However, `Http1RequestDecoder` does not take account into `TooLongHttpLineException` and returns "400 Bad Request" instead.

Modifications:

- Make `Http1RequestDecoder` return `431 Request Header Fields Too Large` if a Netty HttpRequest fails with `TooLongHttpHeaderException`

Result:

- `431 Request Header Fields Too Large` is now returned instead of `400 Bad Request` if the size of headers exceeds `ServerBuilder.http1MaxHeaderSize()`.
- Fixes #4609

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 1]
```diff
@@ -151,6 +152,9 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
                         final Throwable cause = nettyReq.decoderResult().cause();
                         if (cause instanceof TooLongHttpLineException) {
                             fail(id, null, HttpStatus.REQUEST_URI_TOO_LONG, "Too Long URI", cause);
+                        } else if (cause instanceof TooLongHttpHeaderException) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:155]: double checked that `TooLongHttpHeaderException` is not related to `TooLongHttpLineException`, so it doesn't matter which if statement is checked first 👍

File: core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java [hunk 2]
```diff
@@ -151,6 +152,9 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
...
+                            fail(id, null, HttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE, "Too Long Header Fields",
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java:156]: How about just using the default message for the http status?

```suggestion
                            fail(id, null, HttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE, "Request Header Fields Too Large",
```

**Review by jrhee17 — APPROVED** [review]
Left a super minor comment! Thanks @ikhoon ! 🙇 👍 🙇

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Review by jrhee17 — APPROVED** [review]
Still looks good 👍

**Comment by jrhee17** [comment]
Thanks @ikhoon ! 🙇 👍 🙇
