### PR TITLE
#3633 Handle errors when invoking a WebOperation

### LINKED ISSUE #3209: Return custom eror page when the execution time is long then armeria sends a response with 503
Our service, https://store.line.me using armeria and embedding tomcat service.
ref: https://armeria.dev/docs/server-servlet

When tomcat execution is long then ameria got timeout error, "503 Service Unavailable" message appears in browser.
We would like to response custom error page to users instead of "503 Service Unavailable" message.

As-Is:
Just  "503 Service Unavailable" message. It's not user friendly.

To-Be:
Should be an error page with message and image. It's more user friendly. 
ex.twitter
c9dd260c

FYI: our service's code base is not public but I prepared a project with same architecture.
ref: https://github.com/policeman-kh/armeria_spring_web

### LINKED ISSUE #3633: [actuator] Uncaught exception in WebOperationService.invoke
When the actuator operation is blocking and `operation.invoke` fails e.g. due to `MissingParametersException`, nobody knows about it, and the response eventually silently times out.
The resulting error 503 is quite hard to debug.

- fix error handling
- add logs

### PR DESCRIPTION
**Pull request by mauhiz**
Without error handling at this level, the response future is never touched and the request times out (giving a 503 with no log)
Closes #3633

### CODE REVIEW

File: spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java [hunk 1]
```diff
@@ -127,7 +128,11 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) {
                 return null;
             }
             if (operation.isBlocking()) {
-                ctx.blockingTaskExecutor().execute(() -> invoke(ctx, aggregatedReq, resFuture));
+                try {
+                    ctx.blockingTaskExecutor().execute(() -> invoke(ctx, aggregatedReq, resFuture));
+                } catch (RejectedExecutionException ree) {
+                    resFuture.completeExceptionally(ree);
+                }
```
Comment (trustin) [inline spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java:135]: How about just catching a `Throwable`?

```java
req.aggregate().handle(... -> {
  if (t != null) { ... }
  try {
    ..
  } catch (Throwable cause) {
    resFuture.completeExceptionally(cause);
  }
  return null;
})
```

**Review by trustin — COMMENTED** [review]
Thanks for fixing this, @mauhiz! :bow:

File: spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java (hunk 1 above)
Comment (mauhiz) [reply spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java:135]: Oh.. how does that make thing better?

Comment (trustin) [reply spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java:135]: - It will catch other exceptions than `RejectedExecutionException`
- We're absolutely sure nothing will ever fail like before, even when `invoke()` below throws an exception.

Comment (mauhiz) [reply spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java:135]: I suppose you mean that custom `ExecutorService` who throw other runtime exceptions or even errors can't cause trouble here?
Okay then

File: spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java [hunk 2]
```diff
@@ -127,7 +128,11 @@ public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) {
                 return null;
             }
             if (operation.isBlocking()) {
-                ctx.blockingTaskExecutor().execute(() -> invoke(ctx, aggregatedReq, resFuture));
+                try {
+                    ctx.blockingTaskExecutor().execute(() -> invoke(ctx, aggregatedReq, resFuture));
```
Comment (ikhoon) [inline spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java:132]: I think we can refactor this code a bit simpler.
```java
@Override
public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) {
    final Executor executor = operation.isBlocking() ? ctx.blockingTaskExecutor() : ctx.eventLoop();
    return HttpResponse.from(req.aggregate()
                                .thenApplyAsync(aggregatedReq -> invoke(ctx, aggregatedReq), executor));
}

private HttpResponse invoke(ServiceRequestContext ctx, AggregatedHttpRequest req) {
    final Map<String, Object> arguments = getArguments(ctx, req);
    final Object result = operation.invoke(new InvocationContext(SecurityContext.NONE, arguments));
    try {
        return handleResult(ctx, result, req.method());
    } catch (Throwable throwable) {
        return Exceptions.throwUnsafely(throwable);
    }
}
```

Comment (ikhoon) [reply spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java:132]: Gentle ping @mauhiz. Any thought on this?

Comment (ikhoon) [reply spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java:132]: On second thought, it seems overkill to refactor the code with this PR. Please ignore this review.

**Review by ikhoon — APPROVED** [review]
Thanks! @mauhiz

**Comment by ikhoon** [comment]
Let me merge this PR and handle additional issues with Spring Boot 2.5 in dependencies upgrade PR. 🙇‍♂️
