### PR TITLE
Disallow query strings in a route path

### LINKED ISSUE #5054: Strip query part automatically when binding a service
If a `?` is used in a path for binding a service, (e.g. `sb.service("/foo?bar, unreachableService)`) the unreachable service is bound without any exception.
We should:
- strip the query part and automatically set it to `RouteBuilder.matchesParams()` when the path type is `EXACT` or `PARAMETERIZED`.
- raise an exception if the path type is `PREFIX`.

We should also raise an exception if the path contain `#` when the path type is `EXACT`, `PARAMETERIZED`, or `PREFIX`.

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

The query string in a path of `Route` is treated as a part of routing path. However, when a service is actually resolved, the query string of the request path is excluded from the target path. As a result, the router fails to locate the service.
https://github.com/line/armeria/blob/95ed9e1cfb075da4f04d7e5d5fa5adc63627282d/core/src/main/java/com/linecorp/armeria/server/RoutingContext.java#L82-L88

Modifications:

- Raise `IllegalArgumentException` if the path of `route()` contains query strings and guide users to use `RouteBuilder.matchParams()`

Result:

- `Route` now properly rejects paths with query strings to avoid incorrect routing behavior.
- Closes #5054

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java [hunk 1]
```diff
@@ -42,6 +42,10 @@ static String mappedPath(String prefix, String path) {
         return path.substring(length);
     }
 
+    static boolean hasQueryString(String path) {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java:45]: Question) For reference, is there a reason `PrefixPathMapping` doesn't apply this check?

**Review by jrhee17 — APPROVED** [review]

File: core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java (hunk 1 above)
Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java:45]: It should be find to add the validation. Since a prefix is expected to contain additional path segments, having a query string there would not be logical. So I though it would not cause confusion unlike a regular path.

However, if adding it is meaningful, I will include it.

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java:45]: +1 for adding it.

Comment (ikhoon) [reply core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java:45]: Fixed at [`7e06404` (#6546)](https://github.com/line/armeria/pull/6546/commits/7e06404f110f5ee394cc5ab3a582812e76929206)
