### PR TITLE
Fix failure of `GrpcDocServicePlugin` when `HttpEndpointSupport` is wrapped

### LINKED ISSUE #4487: `GrpcDocServicePlugin` fails when using `GrpcDecoratingService`-wrapped `GrpcService`
When using `GrpcService` with decorators, `GrpcServiceBuilder` wraps it with `GrpcDecoratingService`. - [code line](https://github.com/line/armeria/blob/c888c86b288e85bb489b2938f2498095b2303e55/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L1043)

However, it makes `GrpcDocServicePlugin` fail to `generateSpecification`, because when [this line](https://github.com/line/armeria/blob/755c28292c734e954bd69aebcfaeabcf7b024c16/grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java#L127) is executed, `grpcService instanceof HttpEndpointSupport` is `false`.

As a result, `methodDefinition` can be `null` on [this line](https://github.com/line/armeria/blob/755c28292c734e954bd69aebcfaeabcf7b024c16/grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java#L177). (Also above `assert` line fails.)

May I give a try fixing this issue?

### PR DESCRIPTION
**Pull request by davin111**
Motivation:

`GrpcDocServicePlugin` fails when using wrapped `GrpcService` since 1.18.0.

Modifications:

- Use unwrapped `GrpcService` in `generateSpecification` of `GrpcDocServicePlugin`.

Result:

- Closes #4487.
- GrpcDocServicPlugin works with GrpcService when HTTP JSON transcoding is enabled and GrpcService is wrapped.

### CODE REVIEW

**Comment by ikhoon** [comment]
> Should I fix something related with failure of ‘windows-latest , 17’ CI build?

No, you don't need it. It is a known bug in Gradle. https://github.com/gradle/gradle/issues/21116

**Review by ikhoon — APPROVED** [review]
Thanks a lot, @davin111! 💯🙏

File: grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java [hunk 1]
```diff
@@ -103,6 +107,18 @@ void servicesTest() throws Exception {
                                                       m.name());
             });
         });
+        services.get(HttpJsonTranscodingTestServiceGrpc.SERVICE_NAME).methods().forEach(m -> {
```
Comment (jrhee17) [inline grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java:110]: While adding to these tests is also useful, what do you think of also adding a decorator (e.g. `LoggingService`) to our integration test at `GrpcDocServiceTest` as well?

https://github.com/line/armeria/blob/f6c4debed749f77d71aec836e98bdffef6537273/grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServiceTest.java#L117

```
-                                       .addService(new TestService())
+                                       .addService(new TestService(),
+                                                   ImmutableList.of(LoggingService.newDecorator()))
```

**Review by jrhee17 — APPROVED** [review]
Left one nit comment but looks good to me! Thank you @davin111 🙇 👍 🚀

File: grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java [hunk 2]
```diff
@@ -103,6 +107,18 @@ void servicesTest() throws Exception {
...
+            m.endpoints().forEach(e -> {
+                assertThat(e.pathMapping()).isEqualTo("/armeria.grpc.testing.HttpJsonTranscodingTestService/" +
+                                                      m.name());
+            });
+        });
+        services.get(HttpJsonTranscodingTestServiceGrpc.SERVICE_NAME +
+                     GrpcDocServicePlugin.HTTP_SERVICE_SUFFIX).methods().forEach(m -> {
+            m.endpoints().forEach(e -> {
+                assertThat(e.pathMapping()).endsWith(m.examplePaths().get(0));
```
Comment (minwoox) [inline grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java:119]: I think this validation doesn't mean anything, but there isn't a good way for checking the path.
Having said this, it's fine as is. 😄

**Review by minwoox — APPROVED** [review]
Thanks, @davin111! 😄
