### PR TITLE
Fix a bug where an incorrect executor used for DNS refresh query

### LINKED ISSUE #5891: WebClient resolver doing eventloop-work on worker
It happens relatively seldom, but maybe once every 10 minutes or so and is only seen when debugging (as it's an assertion that's reporting the issue).

There are multiple WebClient's in the VM, but the simplest one that keeps throwing this is (yes, creates a new WebClient for every request, but it's one request every couple of minutes):
```java
WebClient.of().get("https://host/path")
                .aggregate()
                .get()
```

```
2024-09-04T10:38:24.422795111Z {179} [WARNING] AbstractEventExecutor A task raised an exception. Task: com.linecorp.armeria.client.RefreshingAddressResolver$$Lambda$1341/0x0000000101491218@569ce20b[armeria-common-worker-epoll-3-3]
java.lang.AssertionError
    at com.linecorp.armeria.internal.client.dns.DefaultDnsResolver.resolveOne(DefaultDnsResolver.java:88)
    at com.linecorp.armeria.internal.client.dns.DefaultDnsResolver.resolve(DefaultDnsResolver.java:81)
    at com.linecorp.armeria.client.RefreshingAddressResolver.sendQueries(RefreshingAddressResolver.java:161)
    at com.linecorp.armeria.client.RefreshingAddressResolver.access$500(RefreshingAddressResolver.java:56)
    at com.linecorp.armeria.client.RefreshingAddressResolver$CacheEntry.refresh(RefreshingAddressResolver.java:356)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:173)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:166)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

Issue was present in at least 1.27.3 and is still present in 1.30.0.

`@`-mention me in the [discord thread](https://discord.com/channels/1087271586832318494/1280839727502725140) if you need help reproducing it/stepit or more logs.

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
Each `CacheEntry` should be bound to a specific `RefreshingAddressResolver`, and the associated DNS refresh query must be executed using its own executor. However, there was a bug where the refresh query could be mistakenly executed by the executor of a different resolver accessing the same `CacheEntry`.

Modifications:
- Ensured that the DNS refresh query is always executed by the correct `RefreshingAddressResolver`'s executor.

Result:
- DNS refresh query is executed by the correct executor.
- Close #5891 #6003

### CODE REVIEW

**Comment by minwoox** [comment]
I couldn't make a test case for this. Please bear with me. 🙏

File: core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java [hunk 1]
```diff
@@ -220,8 +221,7 @@ public void onRemoval(DnsQuestion question, @Nullable List<DnsRecord> records,
         final CacheEntry entry = addressResolverCache.getIfPresent(hostname);
         if (entry != null) {
             if (entry.refreshable()) {
-                // onRemoval is invoked by the executor of 'dnsResolverCache'.
-                executor().execute(entry::refresh);
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java:224]: refresh should be called by the entry's executor not by the executor who gets this cache entry from `addressResolverCache`.

File: core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java [hunk 2]
```diff
@@ -263,6 +263,7 @@ public void close() {
 
     final class CacheEntry {
```
Comment (jrhee17) [inline core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java:264]: Note: It may make more sense that `CacheEntry` is not bound to a specific resolver. Since there may be more changes involved, I'm fine with the current implementation

**Review by jrhee17 — APPROVED** [review]

File: core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java (hunk 2 above)
Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java:264]: The `resolverClosed` flag is shared with `CacheEntry` so I just couldn't make this class static. Let me try that later if we really need to. 😉

**Review by ikhoon — APPROVED** [review]

**Comment by minwoox** [comment]
Thanks for reviewing. 😉
