### PR TITLE
Fix a bug where `Server.stop/close()` never finishes

### LINKED ISSUE #3746: The future returned by `Server.stop/close()` is sometimes never completed
Our builds started to timeout since recently. Full thread dump reveals that the test processes are stuck waiting for the future returned by `Server.stop()` or `.close()`:

```
"Test worker" #11 prio=5 os_prio=0 tid=0x00007f62b4a61800 nid=0x79f3 waiting on condition [0x00007f6285be8000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000000f6827138> (a java.util.concurrent.CompletableFuture$Signaller)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
    at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
    at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
    at com.linecorp.armeria.common.util.AsyncCloseableSupport.close(AsyncCloseableSupport.java:152)
    at com.linecorp.armeria.common.util.StartStopSupport.close(StartStopSupport.java:351)
    at com.linecorp.armeria.server.Server.close(Server.java:352)
    at com.linecorp.armeria.client.HttpClientFactoryTest.numConnections_multipleServers(HttpClientFactoryTest.java:104)
```

```
"Test worker" #15 prio=5 os_prio=0 cpu=2390.92ms elapsed=2658.03s tid=0x00007f436c754840 nid=0x2f5c waiting on condition  [0x00007f4341fab000]
   java.lang.Thread.State: WAITING (parking)
    at jdk.internal.misc.Unsafe.park(java.base@16.0.1/Native Method)
    - parking to wait for  <0x00000000e35bcb78> (a java.util.concurrent.CompletableFuture$Signaller)
    at java.util.concurrent.locks.LockSupport.park(java.base@16.0.1/LockSupport.java:211)
    at java.util.concurrent.CompletableFuture$Signaller.block(java.base@16.0.1/CompletableFuture.java:1860)
    at java.util.concurrent.ForkJoinPool.managedBlock(java.base@16.0.1/ForkJoinPool.java:3137)
    at java.util.concurrent.CompletableFuture.waitingGet(java.base@16.0.1/CompletableFuture.java:1894)
    at java.util.concurrent.CompletableFuture.join(java.base@16.0.1/CompletableFuture.java:2113)
    at com.linecorp.armeria.it.server.GracefulShutdownIntegrationTest.testHardTimeout(GracefulShutdownIntegrationTest.java:264)
```

### PR DESCRIPTION
**Pull request by trustin**
Motivation:

The `CompletableFuture` returned by `Server.stop/close()` is completed
when all accepted connections are closed. To get notified when an
accepted connection is closed, it listens to the Netty `ChannelPromise`
returned by `Channel.close()`.

In HTTP/2, the `ChannelPromise` returned by `Channel.close()` is
completed by `GracefulConnectionShutdownHandler`. However,
`GracefulConnectionShutdownHandler` can fail to complete the
`ChannelPromise` when the task scheduled by
`GracefulConnectionShutdownHandler` is cancelled before it completes the
`ChannelPromise`.

Modifications:

- Ensure the `ChannelPromise` is always completed when a connection is
  closed.
  - No need to pass around the promise anymore.
- Miscellaneous:
  - Respect the return value of `drainFuture.cancel()`.
  - Prefer `try{Success,Failure}` to `set{Success,Failure}` because
    `set{Success,Failure}` can throw an exception.
  - Short-circuit when the connection is already closed.

Result:

- Fixes #3746

/cc @alexc-db

### CODE REVIEW

File: core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java [hunk 1]
```diff
@@ -60,29 +60,40 @@ protected GracefulConnectionShutdownHandler(long drainDurationMicros) {
...
-    private void run(ChannelHandlerContext ctx, ChannelPromise promise) {
+    private void run(ChannelHandlerContext ctx) {
         if (drainFuture != null) {
+            final boolean cancelled;
             if (drainFuture.getDelay(TimeUnit.MICROSECONDS) > drainDurationMicros) {
                 // Maybe reschedule below.
-                drainFuture.cancel(false);
+                cancelled = drainFuture.cancel(false);
+            } else {
+                cancelled = false;
```
Comment (minwoox) [inline core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java:93]: nit:
```suggestion
                return;
```

**Review by minwoox — APPROVED** [review]
👍 👍 👍

File: core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java (hunk 1 above)
Comment (trustin) [reply core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java:93]: It's intentional because otherwise I'll have to duplicate the comment below. :smile:

Comment (minwoox) [reply core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java:93]: SGTM. 😄

**Comment by alexc-db** [comment]
Nice fix, thanks @trustin!
